<?php echo $this->render("layout/header.phtml");?>
<div id="page">
		<article class="ac">
		    <?php if($bannel) {?>
			<div class="contact-banner"><a href="<?php echo Common::tjurl($tjUrl, $bannel['id'], 'AD', $bannel['link'],'AD14');?>"><img src="<?php echo $attachPath. $bannel['img'];?>" alt="<?php echo $bannel['title'];?>"></a></div>
			<?php } ?>
			<div class="contact-text">
				<p>● 游戏大厅QQ群：189360286
					<span>加群暗号：爱游戏</span></p>
				<p>● 游戏大厅QQ：1732001808
					<span>加QQ暗号：爱游戏</span></p>
				<p>● 官方邮箱：game@gionee.com</p>
			</div>
		</article>
	</div>
</body>
</html>