<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<title>2014年度盛典-最佳视觉游戏</title>
<link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/events/2014top/css/style.min.css?v=<?php echo $version;?>" />
</head>
<body>
	<div class="ui-pg-top">
		<div class="banner">
			<img src="<?php echo $staticroot; ?>/apps/game/events/2014top/img/06_01.jpg" alt="">
		</div>
		<div class="video-wrap">
			<h3>精彩视频</h3>
			<a class="video-box" href="http://v.youku.com/v_show/id_XODgwNTI4NDQw.html"></a>	
		</div>
		<div class="block">
			<p class="app-img">
				<img src="<?php echo $staticroot; ?>/apps/game/events/2014top/img/06_02.jpg" alt="">
			</p>
			<p class="app-txt">这款年度3D王牌力作，带给我们的是全新的玩法与视觉体验。制作精良的人物形象，打击画面会在不知不觉中让你欲罢不能。其在游戏大厅超高的人气也充分说明了这一点。最佳视觉，名副其实。</p>
		</div>
		<div class="ui-buttons">
			<a class="ui-btn-download" href="http://gamedl.gionee.com/Attachments/dev/apks/2015/01/28/1422438296670_signed.apk">立即下载</a>
		</div>
	</div>
</body>
</html>