<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>万圣节活动---金立游戏大厅</title>
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="format-detection" content="email=no" />
	<link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/events/halloween/assets/css/main.css?v=<?php echo $version;?>" />
</head>
<body>
	<div class="header">
		<div class="head_1"></div>
		<div class="head_2"></div>
	</div>
	<div class="main">
		<div class="card-list-wapper">
			<ul class="card-list">
				<li>
					<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/24/1414114172920_signed.apk', 'WSJ_GID1862');?>&t_bi=<?php echo $source;?>" target="_blank">
						<div class="cardgameBg card1"></div>
						<a class="btn-orange"  href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/24/1414114172920_signed.apk', 'WSJ_GID1862');?>&t_bi=<?php echo $source;?>" target="_blank">立即下载</a>
						<div class="desc"> 
							穿越时空猎杀各类妖魔鬼怪,酣畅淋漓的格斗,快来体验万圣节的刺激吧！
						</div>
					</a>
				</li>
				<li>
					<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/22/1413983111299_signed.apk', 'WSJ_GID3243');?>&t_bi=<?php echo $source;?>" target="_blank">
						<div class="cardgameBg card2"></div>
						<a class="btn-orange" href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/22/1413983111299_signed.apk', 'WSJ_GID3243');?>&t_bi=<?php echo $source;?>" target="_blank">立即下载</a>
						<div class="desc">
							源源不绝的怪物,快装备好弹头,愉快的射击吧！
						</div>
					</a>
				</li>
				<li>
					<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/09/18/1411038979265_signed.apk', 'WSJ_GID2005');?>&t_bi=<?php echo $source;?>" target="_blank">
						<div class="cardgameBg card3"></div>
						<a class="btn-orange" href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/09/18/1411038979265_signed.apk', 'WSJ_GID2005');?>&t_bi=<?php echo $source;?>" target="_blank">立即下载</a>
						<div class="desc">
							每当万圣节来临，怪物侵袭的时候，都应该喊起：去吧,皮卡丘!
						</div>
					</a>
				</li>
				<li>
					<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/22/1413946607327_signed.apk', 'WSJ_GID3159');?>&t_bi=<?php echo $source;?>" target="_blank">
						<div class="cardgameBg card4"></div>
						<a class="btn-orange" href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/22/1413946607327_signed.apk', 'WSJ_GID3159');?>&t_bi=<?php echo $source;?>" target="_blank">立即下载</a>
						<div class="desc">
							我是一名实习死神,想要拿到毕业证书,就必须带走一个人.你准备带走谁?
						</div>
					</a>
				</li>
				<li>
					<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/29/1414567188842.apk', 'WSJ_GID2870');?>&t_bi=<?php echo $source;?>" target="_blank">
						<div class="cardgameBg card5"></div>
						<a class="btn-orange" href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/29/1414567188842.apk', 'WSJ_GID2870');?>&t_bi=<?php echo $source;?>" target="_blank">立即下载</a>
						<div class="desc">
							没有战略的队伍迟早会被打败的!在万圣节变身铠甲勇士集结战斗吧!
						</div>
					</a>
				</li>
				<li>
					<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/23/1414061983990.apk', 'WSJ_GID1273');?>&t_bi=<?php echo $source;?>" target="_blank">
						<div class="cardgameBg card6"></div>
						<a class="btn-orange" href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/23/1414061983990.apk', 'WSJ_GID1273');?>&t_bi=<?php echo $source;?>" target="_blank">立即下载</a>
						<div class="desc">
							在万圣节时期，据说不被光头强抓到就会获得南瓜味的棒棒糖。
						</div>
					</a>
				</li>
				<li>
					<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/27/1414375268141.apk', 'WSJ_GID2279');?>&t_bi=<?php echo $source;?>" target="_blank">
						<div class="cardgameBg card7"></div>
						<a class="btn-orange" href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/27/1414375268141.apk', 'WSJ_GID2279');?>&t_bi=<?php echo $source;?>" target="_blank">立即下载</a>
						<div class="desc">在万圣节,风驰电掣狂飙一把吧!</div>
					</a>
				</li>
				<li>
					<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/23/1414024656255.apk', 'WSJ_GID1355');?>&t_bi=<?php echo $source;?>" target="_blank">
						<div class="cardgameBg card8"></div>
						<a class="btn-orange" href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/23/1414024656255.apk', 'WSJ_GID1355');?>&t_bi=<?php echo $source;?>" target="_blank">立即下载</a>
						<div class="desc">消灭一对是一对,消灭一群是一群!</div>
					</a>
				</li>
			</ul>
		</div>
		<div class="comb-container">
			<div class="comb-header"></div>
			<div class="comb-content">
				<ul class="game-list">
					<li>
						<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/17/1413515692720.apk', 'WSJ_GID2104');?>&t_bi=<?php echo $source;?>" target="_blank">
							<div class="game-container">
								<img src="<?php echo $staticroot; ?>/apps/game/events/halloween/pic/game1.png" alt="">
								<span class="name">3D终极车神</span>
								<span class="btn-orange">立即下载</span>
							</div>
						</a>
					</li>
					<li>
						<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/09/28/1411891539674.apk', 'WSJ_GID1302');?>&t_bi=<?php echo $source;?>" target="_blank">
							<div class="game-container">
								<img src="<?php echo $staticroot; ?>/apps/game/events/halloween/pic/game2.png" alt="">
								<span class="name">植物大战僵尸</span>
								<span class="btn-orange">立即下载</span>
							</div>
						</a>
					</li>
					<li>
						<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/23/1414033155344.apk', 'WSJ_GID1881');?>&t_bi=<?php echo $source;?>" target="_blank">
							<div class="game-container">
								<img src="<?php echo $staticroot; ?>/apps/game/events/halloween/pic/game3.png" alt="">
								<span class="name">天天跑酷HD</span>
								<span class="btn-orange">立即下载</span>
							</div>
						</a>
					</li>
					<li>
						<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/27/14144091841.apk', 'WSJ_GID2497');?>&t_bi=<?php echo $source;?>" target="_blank">
							<div class="game-container">
								<img src="<?php echo $staticroot; ?>/apps/game/events/halloween/pic/game4.png" alt="">
								<span class="name">镭射战机</span>
								<span class="btn-orange">立即下载</span>
							</div>
						</a>
					</li>
					<li>
						<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/20/1413795695609.apk', 'WSJ_GID1687');?>&t_bi=<?php echo $source;?>" target="_blank">
							<div class="game-container">
								<img src="<?php echo $staticroot; ?>/apps/game/events/halloween/pic/game5.png" alt="">
								<span class="name">天天街机捕鱼</span>
								<span class="btn-orange">立即下载</span>
							</div>
						</a>
					</li>
					<li>
						<a href="<?php echo Common::monTjurl($webroot.'/Festival_Wsj/tj', 'http://gamedl.gionee.com/Attachments/dev/apks/2014/10/28/1414493907654.apk', 'WSJ_GID1561');?>&t_bi=<?php echo $source;?>" target="_blank">
							<div class="game-container">
								<img src="<?php echo $staticroot; ?>/apps/game/events/halloween/pic/game6.png" alt="">
								<span class="name">天天斗地主</span>
								<span class="btn-orange">立即下载</span>
							</div>
						</a>
					</li>
				</ul>
			</div>
			<div class="comb-footer"></div>
		</div>
	</div>
	<div class="footer">
		<span class="qrcode"></span>
		<div class="container">
			<div class="info">
			<p>客服电话：<?php echo $servicePhone; ?></p>
			<p>客服QQ：<?php echo $serviceQq; ?></p>
			<p>玩家交流群：189360286</p>
			</div>
		</div>
		<span class="copyright">本次活动最终解释权归金立游戏大厅所有</span>
	</div>
</body>
</html>