<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">日志列表</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
	<tr class="tr">
			<th class="th">用户名</th>
			<td class="td"><input class="input " type="text" name="username" value="<?php echo $param['username'];?>"></td>
	</tr>
	<tr class="tr">
			<th class="th">文件标题</th>
			<td class="td"><input class="input " type="text" name="message" value="<?php echo $param['message'];?>"></td>
	</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>

</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="60">编号</td>
			<td width="100">用户名</td>
			<td>日志内容</td>
			<td width="200">日期</td>
		</tr>
<?php foreach($adminlog as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['username'];?></td>
			<td><?php echo $value['message'];?></td>
			<td><?php echo $value['create_time'] ? date('Y-m-d H:i:s', $value['create_time']) : '';?></td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
