<form method="post" action="" id="edit_form">
	<input name="id" value="<?php echo $info['id']; ?>" type="hidden"/>
	<input name="token" value="<?php echo $token; ?>" type="hidden"/>
	<table class="editTable">
		<tr>
			<th>代码</th>
			<td>
				<input type="text" style="width:250px;" class="easyui-textbox" name="code" required="true" value="<?php echo $info['code']; ?>">
			</td>
		</tr>
		<tr>
			<th>名称</th>
			<td>
				<input type="text" style="width:250px;" class="easyui-textbox" name="name" required="true" value="<?php echo $info['name']; ?>">
			</td>
		</tr>
		<tr>
			<th>内容</th>
			<td><textarea style="width:250px;height: 100px" name="text"><?=$info['text']?></textarea>
		</tr>

		<tr>
			<th>描述</th>
			<td>
				<textarea style="width:250px;" name="desc"><?=$info['desc']?></textarea>
			</td>
		</tr>

	</table>
</form>