<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
		<li class="current"><a href="<?php echo $configUrl?>">转盘抽奖配置</a>
	</ul>
</div>
<div class="h_a">基本配置：</div>
<form method="post" action="/Admin/National/config" id="addFrom">
<input name="token" id="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">	
		<tr class="tr">
			<th class="th">开始时间</th>
			<td class="td"><input type="text" class="input" id="start_time" name="national_day_start_time" width="80px;" value="<?php echo $data['national_day_start_time']; ?>"></td>
		</tr>
		
		<tr class="tr">
			<th class="th">结束时间</th>
			<td class="td"><input type="text" class="input" id="end_time" name="national_day_end_time" width="80px;" value="<?php echo $data['national_day_end_time']; ?>"></td>
		</tr>
		
		<tr class="tr">
			<th class="th">每天可参加活动次数</th>
			<td class="td"><input  type="text"  value="<?php echo max(1,$data['national_day_times']);?>"  name="national_day_times"  class="input"></td>
		</tr>
		
		<tr class="tr">
			<th class="th">奖品过期时间</th>
			<td class="td"><input  type="text"  value="<?php echo $data['national_day_expires'];?>"  name="national_day_expires"  class="input">分钟</td>
		</tr>
		
			<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
			<select name="national_day_status" >
			<option value="1"   <?php if($data['national_day_status'] == 1) echo 'selected';?>>开启</option>
			<option value="0"    <?php if($data['national_day_status'] == 0) echo 'selected';?>>关闭</option>
			</select>
			</td>
		</tr>
		
		<tr class="tr">
			<th class="th">规则说明</th>
			<td class="td"><textarea rows="6" cols="10" name="national_day_rule"  style="width: 600px; height:400px;"><?php echo $data['national_day_rule'];?></textarea></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
	<script src="<?php echo $staticPath; ?>/js/common/jquery-ui-timepicker.js"></script>
	<script src="<?php echo $staticPath;?>/js/admin/kindeditor/kindeditor.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	$('#start_time').datetimepicker();
	$('#end_time').datetimepicker();
	
	 var editor;
	 	KindEditor.ready(function(K) {
	 		K.token = $('#token').val();
	 	    editor = K.create('textarea[name="national_day_rule"]', {
	 	        resizeType : 1,
	 	        allowPreviewEmoticons : false,
	 	        allowImageUpload : true,
	 	        uploadJson : '<?php echo $uploadImgUrl;?>',
	 	        items : EDITOR_ITEMS
	 	    });
	 	});
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/National/config');
	},function(){
  		editor.sync();
  	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
