<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>合作商登陆系统 </title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="format-detection" content="telephone=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="alternate icon" type="image/png" href="assets/i/favicon.png">
   <link rel="stylesheet" href="<?php echo $staticResPath?>/cpadmin/css/amazeui.min.css?version=<?php echo $version;?>"/>
  <style>
    .header {
      text-align: center;
    }
    .header h1 {
      font-size: 200%;
      color: #333;
      margin-top: 30px;
    }
    .header p {
      font-size: 14px;
    }
  </style>
</head>
<body>
<div class="header"> 
  <hr />
</div>
<div class="am-g">
  <div class="am-u-lg-6 am-u-md-8 am-u-sm-centered">
    <h3>登录</h3>
    <hr>
    <br>
    <form method="post" action="" class="am-form">
      <label for="email">用户名:</label>
      <input type="text"  name="name" id="name" value="">
      <br>
      <label for="password">密码:</label>
      <input type="password" name="password" id="password" value="<?php echo $paassword?>">
      <br>
      <label for="remember-me">
        <input id="remember-me" type="checkbox"  name="remember_me">
        记住密码
      </label>
      <br />
      <div class="am-cf">
        <input type="button" name="" value="登 录" class="am-btn am-btn-primary am-btn-sm am-fl"  id="submit">
        <!-- <input type="button" name="" value="忘记密码 ? " class="am-btn am-btn-default am-btn-sm am-fr"> -->
      </div>
    </form>
    <hr>
    <p>@ 2015 版权所有.</p>
  </div>
</div>
</body>
   <script type="text/javascript" src="<?php echo $staticSysPath?>/lib/jquery/jquery.js?version=<?php echo $version;?>"></script>
    <script type="text/javascript" src="<?php echo $staticResPath?>/cpadmin/js/RSA.js"></script>
    <script type="text/javascript" src="<?php echo $staticResPath?>/cpadmin/js/BigInt.js"></script>
    <script type="text/javascript" src="<?php echo $staticResPath?>/cpadmin/js/Barrett.js"></script>
<script type="text/javascript">
	$("#submit").bind('click',function(){
		var account = $("#name").val();
		var password = $("#password").val();
		if(!account.length|| !password.length){
					alert('请输入用户名和密码！');
		}
		var rsa_n = '9EACCB29BD492491715B130B1DA6271412E2452826286E97B354A87BCA74B7A7590A8ED746F2B2BD6C08C2EDE66E00D1448CDF0A1DA30E4150B5A2842698385BEFA65FE75473F15F5EB80A0EEFB71BB5CA54B2793742D9837C4A3D83440DCB6EBF26AE9C213FA177309EDCB9BE09509563C78907B968CBE54D4C427EBB3333E1';
		 setMaxDigits(131); //131 => n的十六进制位数/2+3
		 var key      = new RSAKeyPair("10001", '', rsa_n); //10001 => e的十六进制
		  password = encryptedString(key, password); //不支持汉字
		 $.ajax({
				'url':'/User/cp/loginPost',
				'type':'post',
				'dataType':'json',
				'data':{'token':'<?php echo $token;?>','account':account,'password':password},
				'success':function(e){
					if(e.success){
						location.href=e.data.redirectUrl;
					}else{
						alert(e.msg);
					}
				}
		})
	})
</script>
</html>