<!doctype html>
<html class="no-js">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>合作商登陆系统  </title>
		<meta name="description" content="合作商登陆系统 ">
		<meta name="keywords" content="table">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<meta name="renderer" content="webkit">
		<meta http-equiv="Cache-Control" content="no-siteapp" />
		<link rel="icon" type="image/png" href="assets/i/favicon.png">
		<link rel="apple-touch-icon-precomposed" href="assets/i/app-icon72x72@2x.png">
		<meta name="apple-mobile-web-app-title" content="Amaze UI" />
		<link rel="stylesheet" href="<?php echo $staticResPath?>/cpadmin/css/amazeui.min.css" />
		<link rel="stylesheet" href="<?php echo $staticResPath?>/cpadmin/css/admin.css?version=<?php echo $version;?>">
		<link rel="stylesheet" href="<?php echo $staticResPath?>/cpadmin/css/jquery-ui.min.css"/>
		<style>
		#last-tr td:hover{

						background-color:#fff;	

		}
#last-tr td{

						background-color:#fff;	

		}
		
</style>	
	</head>
	<body>
		<!--[if lte IE 9]>
<p class="browsehappy">你正在使用<strong>过时</strong>的浏览器，Amaze UI 暂不支持。 请 <a href="http://browsehappy.com/" target="_blank">升级浏览器</a>
  以获得更好的体验！</p>
<![endif]-->

		<header class="am-topbar admin-header">
			<div class="am-topbar-brand">
				<strong>CP</strong> <small>管理系统</small>
			</div>
			<button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only" data-am-collapse="{target: '#topbar-collapse'}"><span class="am-sr-only">导航切换</span> <span class="am-icon-bars"></span>
			</button>

			<div class="am-collapse am-topbar-collapse" id="topbar-collapse">
				<ul class="am-nav am-nav-pills am-topbar-nav am-topbar-right admin-header-list">
					<li><a href="javascript:;" id="admin-fullscreen"><span class="am-icon-arrows-alt"></span> <span class="admin-fullText">开启全屏</span></a>
					</li>
				</ul>
			</div>
		</header>

		<div class="am-cf admin-main">
			<!-- sidebar start -->
			<div class="admin-sidebar">
				<ul class="am-list admin-sidebar-list">
					<li><a href="/user/cp/index"><span class="am-icon-home"></span> 首页</a>
					</li>
					<li class="admin-parent">
						<ul class="am-list am-collapse admin-sidebar-sub am-in" id="collapse-nav">
							<li><a href="/user/cp/index"><span class="am-icon-calendar"></span> CP日报查询</a>
							</li>
							<li><a href="/user/cp/month"><span class="am-icon-calendar"></span> CP月对账系统</a>
							</li>
						</ul>
					</li>
					<li><a href="/user/cp/logout"><span class="am-icon-sign-out"></span> 退出</a>
					</li>
				</ul>

			</div>
			<!-- sidebar end -->

			<!-- content start -->
			<div class="admin-content">

				<div class="am-cf am-padding">
					<div class="am-fl am-cf"><strong class="am-text-primary am-text-lg" style="cursor: pointer;">《月对账系统</strong> 
					</div>
				</div>
				<form action="/User/Cp/month" method="post">
				<div class="am-g">
					<div class="am-u-md-6 am-cf">
						<div class="am-fl am-cf">
							<div class="am-btn-toolbar am-fl">
							<div class="am-form-group am-margin-left am-fl">日期: <input type="text" id="datepicker" placeholder="<?php echo $params['date'];?>"  name="date"  value="<?php echo $params['date'];?>"></div>
								<div class="am-form-group am-margin-left am-fl">
									业务名称：<select  name="bid" >
										<option value="">请选择</option>
											<?php foreach ($list as $k=>$v){?>
											<option value="<?php echo $v['id'];?>" <?php if ($v['id'] == $params['bid']) echo 'selected';?>><?php echo $v['name'];?></option>
											<?php }?>
									</select>
								</div>
									<div style="padding-left:450px">
									<div class="">
										<input type="hidden"  value="<?php echo $token;?>"  name="token">
										<span class="am-input-group-btn">
	                  						<button class="am-btn am-btn-default" type="submit"><span class="am-icon-search"></span>搜索</button>
										</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</form>
				<div class="am-g">
					<div class="am-u-sm-12">
						<div class="am-form">
							<!--原标记为form但会影响点击记录删除按钮产生模态框（一闪而过）-->
							<table class="am-table am-table-striped am-table-hover table-main">
								<tbody>
									<tr>
										<th>序号</th>
										<th>月份</th>
										<th>业务名称</th>
										<th>PV</th>
										<th>合作模式</th>
										<th>结算金额</th>
										<th>审核对账</th>
									</tr>
									
									<?php
							
									if(!empty($dataList)){
										foreach($dataList as $k=>$v){?>
										<tr>
											<td><?php echo $k+1;?></td>
											<td><?php echo $date;?></td>
											<td><?php echo $v['bussiness_name'];?></td>
											<td><?php echo $v['pv']?$v['pv']:0;?></td>
											<td><?php echo $modelTypes[$v['model']]?$modelTypes[$v['model']]:'---';?></td>
											<td><?php echo $v['check_status']==1? $v['real_money']:'暂无金额';?></td>
											<td  id="mon_<?php echo $v['id'];?>">
											<button class="am-btn am-btn-default" type="button"  <?php if($v['confirm_status']==0 && $v['check_status'] == 1){?> onclick="cfm('<?php echo $v['id'];?>')"  <?php }?>> <?php echo $confirmStatus[$v['confirm_status']];?></button></td>
										</tr>
										<?php }?>
										<tr id="last-tr">
											<td colspan="6"></td>
											<td>
											<?php  if($unconfirmNum){?>
													<button  class="am-btn am-btn-default"  id="confrimAll"  onclick="confirmAll()">一键全部确认</button>
												<?php }else{?>
													<button  class="am-btn am-btn-default"  >已全部确认</button>
											<?php }?>
											</td>
											</tr>
										<?php }else{?>
										<tr><td colspan=3"></td><td>暂无相关数据</td><td colspan="3"></td></tr>
										<?php }?>
								</tbody>
								
							</table>
							<div class="am-cf">
								共 <span class="record-num"><?php echo $total;?></span> 条记录
								<?php echo $pager;?>
							</div>
							<hr />
						</div>
					</div>

				</div>
			</div>
			<!-- content end -->
		</div>

		<footer>
			<hr>
			<p style="padding-left: 600px;">© 2015 金立通讯</p>
		</footer>


		<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="assets/js/polyfill/rem.min.js"></script>
<script src="assets/js/polyfill/respond.min.js"></script>
<script src="assets/js/amazeui.legacy.js"></script>
<![endif]-->

		<!--[if (gte IE 9)|!(IE)]><!-->
		<script src="<?php echo $staticResPath?>/cpadmin/js/jquery.min.js"></script>
		<script src="<?php echo $staticResPath?>/cpadmin/js/amazeui.min.js"></script>
		<!--<![endif]-->
		<script src="<?php echo $staticResPath?>/cpadmin/js/app.js"></script>
		<script src="<?php echo $staticResPath?>/cpadmin/js/jquery-ui.min.js"></script>
		<script src="<?php echo $staticResPath?>/cpadmin/js/main.js"></script>
	</body>

	<script type="text/javascript">

		function cfm(id){
			if(id>0){
				$.ajax({
					'url':'/user/cp/ajaxConfirm',
					'dataType':'json',
					'type':'post',
					'data':{'token':'<?php echo $token;?>','id':id},
					'success':function(e){
						if(!e.success){
							alert(e.msg);
						}else{
							 var msg = '<button class="am-btn am-btn-default" type="button" >已确认</button>';
								$("#mon_"+id).html(msg);
						}
					}
				});
			}else{
				alert('参数有错！');
			}
		}

		function confirmAll(){
			if(confirm('确实要全部确认?')){
				$.ajax({
					'url':'/user/cp/ajaxAllconfirm',
					'dataType':'json',
					'type':'post',
					'data':{'token':'<?php echo $token;?>','pid':'<?php echo $userInfo['id'];?>'},
					'success':function(e){
							if(e.success){
								alert(e.msg);
								location.reload();
							}else{
								alert(e.msg);
							}
					}
				})
			}
		}
	</script>
</html>