<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $indexUrl;?>?version_type=<?php echo $info['version_type'];?>&info_type=<?php echo $info['info_type'];?>"><?php echo $info_type_array[$info['info_type']]['name'];?>列表</a></li>
	    <li class="current"><a href="javascript:;"><?php echo $info_type_array[$info['info_type']]['name'];?>主题</a></li>
	</ul>
</div>
<div class="h_a">修改主题</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">排序</th>
				<td class="td"><input type="text" class="input" name="sort" value="<?php echo $info['sort'];?>"></td>
			</tr>
			<tr class="t">
				<th class="th">版本</th>
				<td class="td">
					<select name="version_type">
						<?php foreach ($info_version_array as $key => $val): ?>
							<option
								value="<?php echo $key; ?>" <?php if ($key == $info['version_type']) echo 'selected="selected"' ?>><?php echo $val; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">名称</th>
				<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title'];?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">分类</th>
				<td class="td">
					<select name="cate_id">
					<?php foreach ($category as $key=>$val):?>
						<option value="<?php echo $val['id'];?>" <?php if ($val['id'] == $info['cate_id']) echo 'selected="selected"';?>><?php echo $val['title'];?></option>
					<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">主题图</th>
				<td class="td">
					<ul class="uploadImg">
						<li id="AdImg">
							<img src="<?php echo $attachPath.$info['img'];?>"/>
						<input type="hidden" name="img" value="<?php echo $info['img'];?>">
						</li>
					</ul>			
					<p style="clear:both;">
		                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
					</p></td>
			</tr>
			<tr class="tr">
				<th class="th">链接地址</th>
				<td class="td"><input type="text" class="input wc" name="url" value="<?php echo $info['url'];?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">渠道号</th>
				<td class="td"><input type="text" class="input" name="channel_code" value="<?php echo $info['channel_code'];?>"></td>
			</tr>
			<tr class="tr">
			<th class="th">模块-平台</th>
			<td class="td">
				<select name="module_id">
					<option value="">选择模块</option>
					<?php foreach($modules as $key=>$value) { ?>
					<option value="<?php echo $value['id'];?>" <?php if($info['module_id'] == $value['id']) echo  'selected="selected"';?>><?php echo $value['name'];?></option>
					<?php }?>
				</select>
				
				<select name="cid">
					<option value="">选择平台</option>
					<?php foreach($channel_names as $key=>$value) { ?>
					<option value="<?php echo $value['id'];?>" <?php if($info['cid'] == $value['id']) echo  'selected="selected"';?>><?php echo $value['name'];?></option>
					<?php }?>
				</select>
			</td>
		</tr>
			<tr class="tr">
				<th class="th">开始结束时间</th>
				<td class="td">
					<div>
						<input class="input" type="text" maxlength="30" style="width:143px;" 
							id="start_time" name="start_time" value="<?php if(!empty($info['start_time'])) echo date('Y-m-d H:i:s', $info['start_time']);?>" /> 至 
						<input class="input" type="text" maxlength="30" style="width:143px;" 
							id="end_time" name="end_time" value="<?php if(!empty($info['end_time'])) echo date('Y-m-d H:i:s', $info['end_time']);?>" />
					</div>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td">
					<select class="wa" name="status">
						<option value="1" <?php echo $info['status'] == 1 ? 'selected="selected"' : '';?>>开启</option>
						<option value="0" <?php echo $info['status'] == 0 ? 'selected="selected"' : '';?>>关闭</option>
					</select>
				</td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>

<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	$('#start_time').datetimepicker();
	$('#end_time').datetimepicker();
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $indexUrl;?>?s=1&version_type=<?php echo $info['version_type'];?>&info_type=<?php echo $info['info_type'];?>');
	});
});
$(function(){
	$("select[name=version_type]").change(function(){
		var version_type = $(this).val();
		$.ajax({
			url :"/Admin/Store_Info/getCat",
			type:"get",
			dataType:"json",
			data:{version_type:version_type},
			success:function(ret){
				html = '<option value="0">...请选择分类...</option>';
				$.each(ret.data, function (k,v) {
					html += '<option value="'+ v.id +'">'+ v.title+'</option>'
				});
				$("select[name=cate_id]").html(html);

			}
		});
	});
});
</script>

<?php echo $this->render("layout/footer.phtml");?>
