<?php
echo <<<HTML
<!doctype html>
<html>
<meta charset="utf-8">
<title>管理系统</title>
<script type="text/javascript" src="{$staticPath}/../game/admin/assets/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="{$staticPath}/../game/admin/assets/js/jquery-ui.1.11.4.js"></script>
<script type="text/javascript" src="{$staticPath}/../game/admin/assets/js/jquery.form.js"></script>

<script src="$staticPath/js/common/common.js?v=$version"></script>
<script>
var token = "$token";
var baseurl = "$adminroot";
</script>
<link href="$staticPath/css/style.css?v=$version" rel="stylesheet" />
<link rel="stylesheet" href="{$staticPath}/../game/admin/assets/css/jquery-ui-1.3.css?v=$version" />
<link href="$staticPath/css/star/star.source.css?v=$version" rel="stylesheet" />
</head>
<body>
<div class="wrap">
HTML;
?>
