<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">标签列表</a></li>
    <li class="current"><a href="javascript:;">编辑标签</a></li>
	</ul>
</div>
<div class="h_a">编辑标签</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input wa" name="sort" value="<?php echo $info['sort'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">分类</th>
			<td class="td">
				<select class="wa" id="root" name="root_id">
				<?php foreach ($roots as $key=>$value) {?>
					<option <?php if ($category['root_id'] == $value['id']) echo 'selected = selected';?>  value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
				<?php }?>
				</select>
				<select id="parent" name="category_id" >
        		<?php foreach ($parents as $key=>$value){?>
        		<option <?php if($value['id'] == $info['category_id']) echo 'selected';?> value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
        	<?php }?>
        	</select>			
			</td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td"><select name="status" class="wa">
                	<option <?php if($info['status'] == 1) echo 'selected="selected"';?> value="1">开启</option>
                	<option <?php if($info['status'] == 0) echo 'selected="selected"';?> value="0">关闭</option>
            </select></td>
		</tr>
		<tr class="tr">
			<th class="th">标签名称</th>
			<td class="td"><input type="text" class="input wc" name="name" value="<?php echo $info['name'];?>"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/admin/jquery.chainSelect.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Tag/index?s=1');
	});

	var options = {
			remote: true,
			chains: {
				dom: '#root',
				url: '<?php echo $getRootstUrl;?>',
				id: 'id',
				name: 'name',
				next: {
					dom: '#parent',
					url: '<?php echo $getParenstUrl;?>',
					id: 'id',
					name: 'name',
			    }
		    }
	    }

		$('#root').chainSelect(options);

})
</script>


<?php echo $this->render("layout/footer.phtml");?>
