<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $indexUrl;?>">短信平台</a></li>
		<li class="current"><a href="javascript:;">短信日志</a></li>
	</ul>
</div>
<form action="<?php echo $logUrl;?>" method="get">
    <input name="token" type="hidden" value="<?php echo $token;?>" />
    <div class="table_full">
        <table width="100%">
            <tr class="tr">
                <th class="th">内容</th>
                <td class="td">
                    <input type="text" class="input" name="content"	value="<?php echo $search['content'];?>">
                </td>
                <th class="th">号码</th>
                <td class="td">
                    <input type="text" class="input" name="tel"	value="<?php echo $search['tel'];?>">
                </td>
            </tr>
        </table>
    </div>
    <div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td>手机号码</td>
			<td width="800px">发送内容</td>
			<td>发送状态</td>
		</tr>
<?php foreach($sms as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['tel'];?></td>
			<td><?php echo $value['content'];?></td>
			<td><?php echo $value['status'] == 1 ? '成功' : '失败';?></td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
