<?php
if (!defined('BASE_PATH')) exit('Access Denied!');

$staticroot = Yaf_Application::app()->getConfig()->staticroot;
$v = Common::getConfig('siteConfig', 'version');

$config = array(
	'Front_Index_index'=>array(
			'CACHE'=>array(
					$staticroot . '/apps/gou/pic/blank.gif',
					$staticroot . '/apps/gou/assets/img/ico_search.jpg',
					$staticroot . '/apps/gou/assets/img/ico_theme.png',
					$staticroot . '/apps/gou/assets/img/pic_imgDefault.png',
					$staticroot . '/apps/gou/assets/img/ico_helper.png',
					$staticroot . '/apps/gou/assets/img/ico_tuan.png',
					$staticroot . '/apps/gou/assets/img/ico_mall.png',
					$staticroot . '/apps/gou/assets/img/amigo_subtitle.jpg',
					$staticroot . '/apps/gou/assets/js/main.js?t=' . $v,
					$staticroot . '/sys/reset/phonecore.css?t=' . $v,
					$staticroot . '/sys/icat/1.1.6/icat.js?t=' . $v,
					$staticroot . '/apps/gou/assets/css/gou.css?t=' . $v,
					$staticroot . '/apps/gou/assets/css/mvc.css?t=' . $v,
					$staticroot . '??/sys/icat/1.1.6/mvc.js,/apps/gou/assets/js/mvc/view.js,/apps/gou/assets/js/mvc/model.js,/apps/gou/assets/js/mvc/controller.js?t='.$v,
					$staticroot . '/sys/lib/jquery/jquery.js?t=' . $v,
			),
			'NETWORK'=>array('*'),
	),
	'Front_Cod_index'=>array(
			'CACHE'=>array(
					$staticroot . '/apps/gou/pic/blank.gif',
					$staticroot . '/apps/gou/assets/img/ico_search.jpg',
					$staticroot . '/apps/gou/assets/img/ico_theme.png',
					$staticroot . '/apps/gou/assets/img/pic_imgDefault.png',
					$staticroot . '/apps/gou/assets/img/ico_helper.png',
					$staticroot . '/apps/gou/assets/img/ico_tuan.png',
					$staticroot . '/apps/gou/assets/img/ico_mall.png',
					$staticroot . '/apps/gou/assets/img/amigo_subtitle.jpg',
					$staticroot . '/apps/gou/assets/js/main.js?t=' . $v,
					$staticroot . '/sys/reset/phonecore.css?t=' . $v,
					$staticroot . '/sys/icat/1.1.6/icat.js?t=' . $v,
					$staticroot . '/apps/gou/assets/css/gou.css?t=' . $v,
					$staticroot . '??/sys/icat/1.1.6/mvc.js,/apps/gou/assets/js/mvc/view.js,/apps/gou/assets/js/mvc/model.js,/apps/gou/assets/js/mvc/controller.js?t='.$v,
					$staticroot . '/sys/lib/jquery/jquery.js?t=' . $v,
			),
			'NETWORK'=>array('*'),
	),
	'Channel_Index_index'=>array(
			'CACHE'=>array(
					$staticroot . '/apps/gou/pic/blank.gif',
					$staticroot . '/apps/gou/assets/img/ico_search.jpg',
					$staticroot . '/apps/gou/assets/img/ico_theme.png',
					$staticroot . '/apps/gou/assets/img/pic_imgDefault.png',
					$staticroot . '/apps/gou/assets/img/ico_helper.png',
					$staticroot . '/apps/gou/assets/img/ico_tuan.png',
					$staticroot . '/apps/gou/assets/img/ico_mall.png',
					$staticroot . '??/sys/reset/phonecore.css,/apps/gou/channel/assets/css/gou.css?v=' . $v,
					$staticroot . '??/sys/icat/1.1.5/icat.js,/apps/gou/channel/assets/js/main.js?v=' . $v,
					$staticroot . '??/apps/gou/channel/assets/js/mvc/view.js,/apps/gou/channel/assets/js/mvc/model.js,/apps/gou/channel/assets/js/mvc/controller.js?v=' . $v,
					$staticroot . '??/sys/lib/jquery/jquery.js,/apps/gou/channel/assets/js/plugin/gngou.new.js?v='.$v
	
			),
			'NETWORK'=>array('*'),
	),
	'Channel_Cod_index'=>array(
			'CACHE'=>array(
					$staticroot . '/apps/gou/pic/blank.gif',
					$staticroot . '/apps/gou/assets/js/main.js?t=' . $v,
					$staticroot . '/sys/reset/phonecore.css?t=' . $v,
					$staticroot . '/sys/icat/1.1.6/icat.js?t=' . $v,
					$staticroot . '/apps/gou/assets/css/gou.css?t=' . $v,
					$staticroot . '/apps/gou/assets/css/mvc.css?t=' . $v,
					$staticroot . '??/sys/icat/1.1.6/mvc.js,/apps/gou/assets/js/mvc/view.js,/apps/gou/assets/js/mvc/model.js,/apps/gou/assets/js/mvc/controller.js?t='.$v,
					$staticroot . '/sys/lib/jquery/jquery.js?t=' . $v,
			),
			'NETWORK'=>array('*'),
	),
	'Apk_Index_index'=>array(
			'CACHE'=>array(
					$staticroot . '/apps/gou/pic/blank.gif',
					$staticroot . '/apps/gou/assets/img/ico_search.jpg',
					$staticroot . '/apps/gou/assets/img/ico_theme.png',
					$staticroot . '/apps/gou/assets/img/pic_imgDefault.png',
					$staticroot . '/apps/gou/assets/img/ico_helper.png',
					$staticroot . '/apps/gou/assets/img/ico_tuan.png',
					$staticroot . '/apps/gou/assets/img/ico_mall.png',
					$staticroot . '/apps/gou/assets/js/main.js?t=' . $v,
					$staticroot . '/sys/reset/phonecore.css?t=' . $v,
					$staticroot . '/sys/icat/1.1.6/icat.js?t=' . $v,
					$staticroot . '/apps/gou/assets/css/gou.css?t=' . $v,
					$staticroot . '/apps/gou/assets/css/mvc.css?t=' . $v,
					$staticroot . '??/sys/icat/1.1.6/mvc.js,/apps/gou/assets/js/mvc/view.js,/apps/gou/assets/js/mvc/model.js,/apps/gou/assets/js/mvc/controller.js?t='.$v,
					$staticroot . '/sys/lib/jquery/jquery.js?t=' . $v,
			),
			'NETWORK'=>array('*'),
	),
	'Apk_Cod_index'=>array(
			'CACHE'=>array(
					$staticroot . '/apps/gou/pic/blank.gif',
					$staticroot . '/apps/gou/assets/js/main.js?t=' . $v,
					$staticroot . '/sys/reset/phonecore.css?t=' . $v,
					$staticroot . '/sys/icat/1.1.6/icat.js?t=' . $v,
					$staticroot . '/apps/gou/assets/css/gou.css?t=' . $v,
					$staticroot . '/apps/gou/assets/css/mvc.css?t=' . $v,
					$staticroot . '??/sys/icat/1.1.6/mvc.js,/apps/gou/assets/js/mvc/view.js,/apps/gou/assets/js/mvc/model.js,/apps/gou/assets/js/mvc/controller.js?t='.$v,
					$staticroot . '/sys/lib/jquery/jquery.js?t=' . $v,
			),
			'NETWORK'=>array('*'),
	),
	'Market_Index_index'=>array(
			'CACHE'=>array(
					$staticroot . '/apps/gou/pic/blank.gif',
					$staticroot . '/apps/gou/assets/img/ico_search.jpg',
					$staticroot . '/apps/gou/assets/img/ico_theme.png',
					$staticroot . '/apps/gou/assets/img/pic_imgDefault.png',
					$staticroot . '/apps/gou/assets/img/ico_helper.png',
					$staticroot . '/apps/gou/assets/img/ico_tuan.png',
					$staticroot . '/apps/gou/assets/img/ico_mall.png',
					$staticroot . '/apps/gou/assets/js/main.js?t=' . $v,
					$staticroot . '/sys/reset/phonecore.css?t=' . $v,
					$staticroot . '/sys/icat/1.1.6/icat.js?t=' . $v,
					$staticroot . '/apps/gou/assets/css/gou.css?t=' . $v,
					$staticroot . '/apps/gou/assets/css/mvc.css?t=' . $v,
					$staticroot . '??/sys/icat/1.1.6/mvc.js,/apps/gou/assets/js/mvc/view.js,/apps/gou/assets/js/mvc/model.js,/apps/gou/assets/js/mvc/controller.js?t='.$v,
					$staticroot . '/sys/lib/jquery/jquery.js?t=' . $v,
			),
			'NETWORK'=>array('*'),
	),
	'Market_Cod_index'=>array(
			'CACHE'=>array(
					$staticroot . '/apps/gou/pic/blank.gif',
					$staticroot . '/apps/gou/assets/js/main.js?t=' . $v,
					$staticroot . '/sys/reset/phonecore.css?t=' . $v,
					$staticroot . '/sys/icat/1.1.6/icat.js?t=' . $v,
					$staticroot . '/apps/gou/assets/css/gou.css?t=' . $v,
					$staticroot . '/apps/gou/assets/css/mvc.css?t=' . $v,
					$staticroot . '??/sys/icat/1.1.6/mvc.js,/apps/gou/assets/js/mvc/view.js,/apps/gou/assets/js/mvc/model.js,/apps/gou/assets/js/mvc/controller.js?t='.$v,
					$staticroot . '/sys/lib/jquery/jquery.js?t=' . $v,
			),
			'NETWORK'=>array('*'),
	),
		
	'App_Index_index'=>array(
			'CACHE'=>array(
					$staticroot . '/apps/gou/pic/blank.gif',
					$staticroot . '/apps/gou/assets/img/ico_search.jpg',
					$staticroot . '/apps/gou/assets/img/ico_theme.png',
					$staticroot . '/apps/gou/assets/img/pic_imgDefault.png',
					$staticroot . '/apps/gou/assets/img/ico_helper.png',
					$staticroot . '/apps/gou/assets/img/ico_tuan.png',
					$staticroot . '/apps/gou/assets/img/ico_mall.png',
					$staticroot . '/apps/gou/assets/img/amigo_subtitle.jpg',
					$staticroot . '/apps/gou/assets/js/main.js?t=' . $v,
					$staticroot . '/sys/reset/phonecore.css?t=' . $v,
					$staticroot . '/sys/icat/1.1.6/icat.js?t=' . $v,
					$staticroot . '/apps/gou/assets/css/gou.css?t=' . $v,
					$staticroot . '/apps/gou/assets/css/mvc.css?t=' . $v,
					$staticroot . '??/sys/icat/1.1.6/mvc.js,/apps/gou/assets/js/mvc/view.js,/apps/gou/assets/js/mvc/model.js,/apps/gou/assets/js/mvc/controller.js?t='.$v,
					$staticroot . '/sys/lib/jquery/jquery.js?t=' . $v,
			),
			'NETWORK'=>array('*'),
	),
	'App_Cod_index'=>array(
			'CACHE'=>array(
					$staticroot . '/apps/gou/pic/blank.gif',
					$staticroot . '/apps/gou/assets/img/ico_search.jpg',
					$staticroot . '/apps/gou/assets/img/ico_theme.png',
					$staticroot . '/apps/gou/assets/img/pic_imgDefault.png',
					$staticroot . '/apps/gou/assets/img/ico_helper.png',
					$staticroot . '/apps/gou/assets/img/ico_tuan.png',
					$staticroot . '/apps/gou/assets/img/ico_mall.png',
					$staticroot . '/apps/gou/assets/img/amigo_subtitle.jpg',
					$staticroot . '/apps/gou/assets/js/main.js?t=' . $v,
					$staticroot . '/sys/reset/phonecore.css?t=' . $v,
					$staticroot . '/sys/icat/1.1.6/icat.js?t=' . $v,
					$staticroot . '/apps/gou/assets/css/gou.css?t=' . $v,
					$staticroot . '??/sys/icat/1.1.6/mvc.js,/apps/gou/assets/js/mvc/view.js,/apps/gou/assets/js/mvc/model.js,/apps/gou/assets/js/mvc/controller.js?t='.$v,
					$staticroot . '/sys/lib/jquery/jquery.js?t=' . $v,
			),
			'NETWORK'=>array('*'),
	),
);
return $config;
