<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $indexUrl?>">道具兑换</a></li>
        <li class="current"><a href="javascript:;">道具兑换记录</a></li>
	</ul>
</div>
<div class="h_a">
	<span>奖品：<?php echo $prizeData['name'];?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">UUID</td>
			<td width="100">奖品</td>
			<td width="100">兑奖人</td>
			<td width="100">电话号码</td>
			<td width="120">收货地址</td>
			<td width="50">发放状态</td>
			<td width="80">兑奖时间</td>
			<td width="50">操作</td>
		</tr>
		<?php foreach ($exchangeData as $item):?>
			<tr class = "ct">
		    	<td><?php echo $item['uuid'];?></td>
		    	<td><?php echo $prizeData['name'];?></td>
				<td><?php echo ($prizeData['prize_type']==1) ? ($item['contact'] ? $item['contact'] : '--') : '--';?></td>
				<td><?php echo ($prizeData['prize_type']==1) ? ($item['phone'] ? $item['phone'] : '--') : '--';?></td>
				<td><?php echo ($prizeData['prize_type']==1) ? ($item['address'] ? $item['address'] : '--') : '--';?></td>
				<td><?php echo ($item['status']) ? '已发放' : '未发放';?></td>
				<td><?php echo date('Y-m-d  H:i:s', $item["create_time"]);?></td>
				<td>
				    <?php if(!$item['status']):?>
				    <a href="javascript:" onclick="sendOne('<?php echo $sendPrizeUrl;?>/?id=<?php echo $item['id'];?>', '', event);" class="mr10">发放</a>
				    <?php endif;?>
				</td>
			</tr>
		<?php endforeach;?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script>
//删除单个信息
function sendOne(url, msg, e) {
	if (msg == '')
		msg = '确认发放该奖品码？';
	showConfirm(msg, function() {
				$.ajax({
							url : url,
							type : 'POST',
							dataType : 'json',
							data : 'token='+token,
							success : function(ret) {
								if (ret.success) {
									showMsg('', ret.msg);
									setTimeout(function() {
										location.reload();
									}, 500);
								} else {
								showError('', ret.msg);
						        }
				     }
			});
	}, e);
}
</script>
<?php echo $this->render("layout/footer.phtml");?>
