<div class="table_list">
	<form action="<?php echo $this->baseUrl; ?>" id="edit_form" name="form" method="post">
		<input type="hidden" name="id" value="<?php echo $info['id']; ?>">
		<input type="hidden" name="token" value="<?php echo $token; ?>">
		<table class="editTable">
			<tr class="hd">
				<th style="width: 100px">key</th>
				<td class="td2"><?php echo sprintf('%s?t=%s', Common::getPrevShortUrl(), $info['key']); ?></td>
			</tr>
			<tr class="hd">
				<th style="width: 100px">名称(后台显示用):</th>
				<td class="td2"><input type="text" value="<?=$info['name'];?>" name="name" id="name"></td>
			</tr>
			<tr class="hd">
				<th style="width: 100px">地址:</th>
				<td class="td2"><input type="text" style="width: 300px;" value="<?=$info['url'];?>" name="url" id="url">
				</td>
			</tr>
			<tr class="hd">
				<th style="width: 100px">分组(后台归类用):</th>
				<td class="td2"><input type="text" value="<?=$info['sub_type'];?>" name="sub_type" id="sub_type">(默认为空,方便以后统计归类英文字母)
				</td>

			</tr>
		</table>
	</form>
</div>
