<?php echo $this->render("layout/header.phtml");?>
<div class="wrap rotate_wrap">
	<div class="content">
		<div class="main">
			<!-- 防沉迷介绍 s-->
			<div class="mod_box feedback_box">
				<div class="hd"><i class="hd_ico"></i><h2 class="title">意见反馈</h2></div>
					<div class="bd">
						<form action="/Front/about/feed_post" id="form_feedback" method="post">
						<div class="feedback_con">
							<p class="feedback_tip">金立游戏大厅用心倾听您的建议，如果您在使用时遇到问题，或者对我们有任何意见建议，<br/> 欢迎在此留言，我们将关注您的问题并尽快与您联系。</p>
							<label class="keyName">内容：</label>
							<textarea class="textarea" id="content" name="react"  onfocus="if(value=='请填写反馈内容') {value=''}" onblur="if (value=='') {value='请填写反馈内容'}" value="请填写反馈内容" >请填写反馈内容</textarea>
							<span class="feedback_error fr" id="feedback_error_content_empty">内容不能为空</span>
							<span class="feedback_error fr" id="feedback_error_content_max">内容超出长度，请控制在1000字符以内</span>
						</div>
						<div class="feedback_contact">
							<p class="feedback_tip">请在此留下您的联系方式，我们期待与您取得联系，您的私人信息将受到严格保密。</p>
							<ul class="edit_list">
								<li class="cur">
									<i class="ico"></i>
									<input maxlength="30"  style="width:257px" class="input_txt" type="text" name="mobile" id="mobile" placeholder="请输入手机号码" value="请输入手机号码" onfocus="if(value=='请输入手机号码') {value=''}" onblur="if (value=='') {value='请输入手机号码'}"/> <span class="feedback_error" id="feedback_error_mobile">请输入正确的手机号</span>
								</li>
								<li>
									<i class="ico"></i>
									<input maxlength="30"  style="width:257px" class="input_txt" name="email" placeholder="请输入邮箱" id="email" type="text" value="请输入邮箱" onfocus="if(value=='请输入邮箱') {value=''}" onblur="if (value=='') {value='请输入邮箱'}"/>
									<span class="feedback_error"id="feedback_error_email">请输入正确的邮箱</span>
								</li>
								<li>
									<i class="ico"></i>
									<input maxlength="30"  style="width:257px" class="input_txt" type="text" name="qq" id="qq" placeholder="请输入QQ号码" value="请输入QQ号码" onfocus="if(value=='请输入QQ号码') {value=''}" onblur="if (value=='') {value='请输入QQ号码'}"/>
									<span class="feedback_error"id="feedback_error_qq">请输入正确的QQ号</span>
								</li>
							</ul>
							<div class="submit_area">
								<input type="submit" id="btn_feedback_submit" class="submit" value="提交" disabled=disabled>
							</div>
						</div>
					</form>
					</div>
			</div>
		</div>
		<div class="aside">
			 <?php echo $this->render("layout/right_nav.phtml");?>
		</div>
		<!-- 右侧的悬浮框 -->
	    <?php echo $this->render("layout/right.phtml");?>
	</div>
</div>
<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>