<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<title>兑换中心</title>
<link rel="stylesheet" type="text/css" href="<?php echo $staticResPath;?>/call/css/style.min.css?ver=<?php echo $version;?>" />
</head>

<body class="ui-app">

<div class="ui-top-bar">
	<a class="ui-pos icon-back" href="<?=$webroot;?>/user/index/index"></a>
	<span class="ui-top-txt">兑换中心</span>
	<!-- <a class="ui-pos icon-menu" href="#"></a> -->
</div>

<div class="ui-page ui-award-main js-active">
	<div class="ui-page-content">
		<div class="ui-box">
			<div class="ui-award-info">
				<a class="s s2" href="<?php echo $webroot;?>/user/center/score">
					<span class="span-jifen">当前金币：<b><?php echo !empty($userScores)?$userScores['remained_score']:0;?></b><em class="icon-gold"></em></span>
				</a>
			</div>
		</div>
		<!-- 消息列表 START-->
		<div class="ui-box">
			<div class="ui-box-nav">
				<ul class="ui-groupbutton">
					<li class="ui-button js-active" data-toggle="tab" data-target="#page1-tab1" aria-controls="tab1" role="tab">免费分钟</li>
					<li class="ui-button" data-toggle="tab" data-target="#page1-tab2" aria-controls="tab1" role="tab">虚拟奖品</li>
					<li class="ui-button" data-toggle="tab" data-target="#page1-tab3" aria-controls="tab1" role="tab">实物奖品</li>
				</ul>
			</div>
			<div id="page1-tab1" class="ui-tab ui-box-award js-active" role="tabpanel">
				<ul class="ui-award-list">
				
				<?php foreach ($list['calls'] as $k=>$v){
					$title = $v['title']?$v['title']:'立即兑换';
					?>
					<li class="ui-award-item">
						<div class="pic">
						<img src="<?php echo empty($v['image'])?"#": $attachPath.$v['image'];?>" width="104" height="62" />
						<span class="count"><?php echo $v['show_number']?$v['show_number'].'份':'已换完'; ?></span>
						</div>
						<div class="txt"><?php echo $v['name'];?></div>
						<div class="btn">
						<?php 
						if($userScores['remained_score'] >= $v['scores'] && $v['show_number']>0){?>
							<a href="<?php echo $webroot;?>/user/goods/detail?goods_id=<?php echo $v['id'];?>&flag=<?php echo $flag;?>" class="ui-button ui-normal" ><?php echo $title;?></a>
						<?php }else{?>
							<span class="ui-button ui-disable"><?php echo $title;?></span>
						<?php }?>
						</div>
					</li>
					<?php }?>
				</ul>
			</div>
			<div id="page1-tab2" class="ui-tab ui-box-award" role="tabpanel">
				<ul class="ui-award-list">
					<?php foreach($list['virtuals'] as $k=>$v){
						$title = $v['title']?$v['title']:'立即兑换';
					?>
					<li class="ui-award-item">
						<div class="pic">
						<img src="<?php echo empty($v['image'])?'#':$attachPath.$v['image'];?>" width="104" height="62" />
						<span class="count"><?php echo $v['show_number']?$v['show_number'].'份':'已换完'; ?></span>
						</div>
						<div class="txt"><?php echo $v['name'];?></div>
						<div class="btn">
						<?php if($userScores['remained_score'] >= $v['scores'] && $v['show_number']>0){?>
							<a  href="<?php echo $webroot;?>/user/goods/detail?goods_id=<?php echo $v['id'];?>" class="ui-button ui-normal" ><?php echo $title;?></a>
						<?php }else{?>
							<span class="ui-button ui-disable"><?php echo $title;?></span>
						<?php }?>
						</div>
					</li>
					<?php }?>
				</ul>
			</div>
			<div id="page1-tab3" class="ui-tab ui-box-award" role="tabpanel">
				<ul class="ui-award-list">
					<?php  foreach($list['entites'] as $m=>$n){
						$title = $n['title']?$n['title']:'立即兑换';
						?>
					<li class="ui-award-item">
						<div class="pic">
							<img src="<?php echo  empty($v['image'])?"#": $attachPath.$n['image'];?>" width="104" height="62" />
							<span class="count"><?php echo $n['show_number']?$n['show_number'].'份':'已换完'; ?></span>
						</div>
						<div class="txt"><?php echo $n['name'];?></div>
						<div class="btn">
						<?php if($userScores['remained_score'] >= $n['scores'] && $n['show_number']>0){?>
							<a href="<?php echo $webroot;?>/user/goods/detail?goods_id=<?php echo $n['id'];?>" class="ui-button ui-normal" ><?php echo $title;?></a>
						<?php }else{?>
							<span class="ui-button ui-disable"><?php echo $title;?></span>
						<?php }?>
						</div>
					</li>
					<?php }?>
				</ul>
			</div>
		</div>
		<!-- 消息列表 END-->
	</div>
</div>

<!--
<div id="myActionsheet" role="dialog" class="ui-dialog" aria-labelledby="myActionsheetLable" aria-hidden="true">
    <div class="js-dialog-content ui-actionsheet">
        <ul>
            <li></li>
            <li role="button" id="js-actionsheet-ok">确定</li>
        </ul>
        <a role="button" data-dismiss="dialog" class="ui-actionsheet-cancel">取消</a>
    </div>
</div>
<script type="text/javascript">
	var token = "<?php echo $token;?>";
</script>
 -->
<script type="text/javascript">
	var token = "<?php echo $token;?>", version = "<?php echo $version;?>";
</script>
<script id="main" data-baseurl="<?php echo $staticResPath;?>/call/js" data-version="<?php echo $version;?>" src="<?php echo $staticResPath;?>/call/js/lib/require.js?v=<?php echo $version;?>"></script>
<script>
    require(['<?php echo $staticResPath;?>/call/js/common.js?v=<?php echo $version;?>'],function(){
        require(['page/award']);
    });
</script>
</body>
</html>