
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<title>兑换中心</title>
<link rel="stylesheet" type="text/css" href="<?=$staticResPath?>/call/css/style.min.css?ver=<?php echo $version;?>" />
</head>

<body class="ui-app">

<div class="ui-top-bar">
	<a class="ui-pos icon-back" href="<?php echo empty($refurl)?$webroot.'/user/index/index':$refurl;?>"></a>
	<span class="ui-top-txt">兑换中心</span>
	<!-- <a class="ui-pos icon-menu" href="#"></a> -->
</div>

<div class="ui-page page1 js-active">
	<div class="ui-page-content">
		<div class="ui-box">
			<div class="ui-award-info">
				<a class="s s2" href="<?php echo $webroot;?>/user/center/score"><span class="span-jifen">当前金币：<b><?php echo $userScores['remained_score'];?></b><em class="icon-gold"></em></span>
				</a>
			</div>
		</div>
		<div class="ui-box">
			<div class="ui-caption">兑换</div>
		</div>
		<!-- 消息列表 START-->
		<div class="ui-box">
			<div class="ui-box-award">
				<div class="ui-award-detail ui-award-success">
					<div class="pic"><img src="<?php echo $attachPath.$goods['image'];?>" width="104" height="62" /></div>
					<div class="txt"  style="color:red">您的订单正在处理中，请关注消息中心</div>
				</div>

				<div class="ui-panel ui-border-b">
					<a href="<?=$backUrl?>" class="ui-button ui-block ui-normal">完成</a>
				</div>
			</div>
		</div>
		<!-- 消息列表 END-->
	</div>
</div>
</body>
</html>