<div class="ft">
	<?php if ($hasfooter) {?>
   <nav>
		<ul class="navLink">
			<li><a href="http://3g.gionee.com/nav">金立导航</a></li>
			<li><a href="http://game.gionee.com/?source=jinligou">金立游戏</a></li>
			<li><a href="http://goudl.gionee.com/apps/shoppingmall/GN_Gou.apk?source=gou">客户端下载</a></li>
		</ul>
	</nav>
	<?php }?>
	<footer>
	
			<div class="button hidden">
				<a href="<?php echo $webroot,'/user/login/login_step';?>" class="btn gray">注册/登录</a>
			</div>
			<iframe src="<?php echo $webroot,'/user/account/state?curPageUrl=',urlencode($curPageURL);?>" frameborder="0" scrolling="no"></iframe>
		<script type="text/javascript">
		if(window.navigator.onLine != true){
			$('.ft .button').show();
			$('.ft iframe').hide();
		} else {
			$('.ft .button').hide();
			$('.ft iframe').show();
		}
		</script>
		<p class="copyright">
		官方QQ群：237057997<br/>
		copyright© 2012 粤ICP备05087105号</p>
	</footer>
</div>