<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">列表</a></li>
		<li><a href="<?php echo $editUrl;?>">添加</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">序号</td>
			<td width="100">cp来源名</td>
			<td width="100">总数量/天|频率/次</td>
			<td>推送时间点</td>
			<td width="80">抓取几天前数据</td>
			<td width="50">状态</td>
			<td width="100">操作</td>
		</tr>
		<?php foreach($list as $key => $value) {
			$times    = explode(',', $value['time']);
			$perNum   = floor($value['num'] / count($times));
		?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><?php echo $cpUrls[$value['url_id']]['title'];?></td>
			<td><?php echo "{$value['num']}|{$perNum}";?></td>
			<td><?php echo $value['time'];?></td>
			<td><?php echo $value['history_day'];?></td>
			<td><?php echo $value['status']?'开启':'关闭';?></td>
			<td>
				<a href="<?php echo $editUrl; ?>/?id=<?php echo $value['id']; ?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $delUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
		<?php } ?>
	</table>
</div>

<?php echo $this->render("layout/footer.phtml");?>
