<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<title>2014年度盛典-最佳音乐游戏</title>
<link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/events/2014top/css/style.min.css?v=<?php echo $version;?>" />
</head>
<body>
	<div class="ui-pg-top">
		<div class="banner">
			<img src="<?php echo $staticroot; ?>/apps/game/events/2014top/img/09_01.jpg" alt="">
		</div>
		<div class="video-wrap">
			<h3>精彩视频</h3>
			<a class="video-box" href="http://v.youku.com/v_show/id_XODgxMzYwOTgw.html"></a>	
		</div>
		<div class="block">
			<p class="app-img">
				<img src="<?php echo $staticroot; ?>/apps/game/events/2014top/img/09_02.jpg" alt="">
			</p>
			<p class="app-txt">关于音乐的游戏从来就不会停止对视听的追求，当然对于这款音乐游戏，结婚系统，离婚系统也是相当的出彩。多元化的活动辅以年轻的主题十分符合游戏大厅用户的年龄段，相信一定会有更多喜爱舞蹈游戏的朋友对这款游戏爱不释手。</p>
		</div>
		<div class="ui-buttons">
			<a class="ui-btn-download" href="http://gamedl.gionee.com/Attachments/dev/apks/2015/01/20/1421759483918_signed.apk">立即下载</a>
		</div>
	</div>
</body>
</html>