<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<title>2014年度盛典-最佳改编游戏</title>
<link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/events/2014top/css/style.min.css?v=<?php echo $version;?>" />
</head>
<body>
	<div class="ui-pg-top">
		<div class="banner">
			<img src="<?php echo $staticroot; ?>/apps/game/events/2014top/img/08_01.jpg" alt="">
		</div>
		<div class="video-wrap">
			<h3>精彩视频</h3>
			<a class="video-box" href="http://v.youku.com/v_show/id_XODgxMzMxNDc2.html"></a>	
		</div>
		<div class="block">
			<p class="app-img">
				<img src="<?php echo $staticroot; ?>/apps/game/events/2014top/img/08_02.jpg" alt="">
			</p>
			<p class="app-txt">根据金庸小说改编的手游。游戏的故事情节大部分玩家都熟悉，游戏易上手。超高的知名度以及经典的玩法让这款游戏一直占比网游下载以及各大榜单的前几名。爱武侠，爱金庸，更爱天龙八部。</p>
		</div>
		<div class="ui-buttons">
			<a class="ui-btn-download" href="http://gamedl.gionee.com/Attachments/dev/apks/2015/01/15/1421322129626_signed.apk">立即下载</a>
		</div>
	</div>
</body>
</html>