<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $gameListUrl;?>">游戏列表</a></li>
	    <li><a href="<?php echo $privilegeGiftListUrl;?>">特权礼包</a></li>
        <li><a href="<?php echo $hotUrl;?>" style="width:150px">新手礼包(热门礼包)</a></li>
	    <li class="current"><a href="javascript:;">添加热门礼包</a></li>
	</ul>
</div>
<div class="h_a">添加热门礼包</div>
<form method="post" action="<?php echo $addHotPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
	   <tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input wc" name="sort"></td>
		</tr>
		<tr class="tr">
			<th class="th">礼包ID</th>
			<td class="td"><input type="text" class="input wc" name="gift_id" id="gift_id"><button type="button" id="getGiftInfo" style="margin-left:20px;">获取礼包信息</button><br>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">礼包名称</th>
			<td class="td"><input type="text" class="input wc" name="gift_name" id="gift_name"></td>
		</tr>
		<tr class="tr">
			<th class="th">热门生效时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="effect_start_time" name="effect_start_time" value="" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="effect_end_time" name="effect_end_time" value="" /></div>
			</td>
		</tr>
		<tr class="tr" >
			<th class="th">状态</th>
			<td class="td">
			<select name="status">
                	<option value="1">开启</option>
                	<option value="0">关闭</option>
            	</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('#use_start_time').datetimepicker();
    $('#use_end_time').datetimepicker();
    $('#effect_start_time').datepicker();
    $('#effect_end_time').datepicker();
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Gift/hot');
	});
})
$('#getGiftInfo').click(function(){
	$.ajax({
		url : baseurl + "/Admin/Client_Gift/getGiftInfo",
		type : 'POST',
		dataType : 'json',
		data : 'token='+'<?php echo $token;?>'+'&gift_id='+$("#gift_id").val(),
		success : function(ret) {
			 if (ret.success) {
				var list = ret.data.list;
				$('#gift_name').val(list.name) ;
				$('#effect_start_time').val(list.effect_start_time);
				$('#effect_end_time').val(list.effect_end_time) ;
			} else {
				showError('', ret.msg);
			}
		}
	});
	return false;
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
