<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
     <li><a href="<?php echo $listUrl;?>">广告列表</a></li>
	 <li><a href="<?php echo $addUrl;?>">添加广告</a></li>
	 <li class="current"><a href="<?php echo $addfreeUrl;?>">添加免流量图片</a></li>
	</ul>
</div>
<form method="post" action="<?php echo $addfreePostUrl;?>" id="editForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
	
	<div class="table_full">
		<table width="100%">
			<tr class="tr" style="height:250px;">
				<th class="th">免流量图片</th>
				<td class="td">
				<ul class="uploadImg">
					<li id="AdImg">
					    <?php if(!$game_free_img){?>
					    <img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
					    <?php } else {?>
						<img src="<?php echo $attachPath.$game_free_img;?>"/>
						<?php } ?>
						<input type="hidden" name="img" value="<?php echo $game_free_img;?>">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:60px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('editForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Ad_Picture/addfree');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>