<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl;?>">第三方商品库列表</a></li>
		<li class="current"><a href="javascript:;">编辑商品</a></li>
	</ul>
</div>
<div class="h_a">编辑商品</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">标题</th>
				<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title'];?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">产品ID</th>
				<td class="td"><input type="text" class="input" name="goods_id"	value="<?php echo $info['goods_id'];?>"></td>
			</tr>
            <tr class="tr">
                <th class="th">抓取次数</th>
                <td class="td"><input type="text" class="input" name="request_count" value="<?php echo $info['request_count'];?>"></td>
            </tr>
            <tr class="tr">
                <th class="th">价格</th>
                <td class="td"><input type="text" class="input" name="price" value="<?php echo $info['price'];?>"></td>
            </tr>
            <tr class="tr">
                <th class="th">图片</th>
                <td class="td">
                    <ul class="uploadImg">
                        <li id="NewsImg">
                            <img src="<?php
                            if (empty($info['img'])) {
                                echo $staticPath . '/img/content/nopic.jpg';
                            } else {
                                if (strpos($info['img'], 'http://') === false) {
                                    echo $attachPath . $info['img'];
                                } else {
                                    echo $info['img'];
                                }
                            } ?>"/>
                            <input type="hidden" name="img" value="<?php echo $info['img'];?>">
                        </li>
                    </ul>
                    <p style="clear:both;">
                          <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=NewsImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
                    </p></td>
            </tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Third_Goods/index?s=1');
	});
})

</script>
<?php echo $this->render("layout/footer.phtml");?>