<html lang="en">
<head>
	<meta charset="UTF-8">
	<title><?php echo $info['name']; ?></title>
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="format-detection" content="email=no" />
	<link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/smallGame/catsEatFish/assets/css/css.min.css?v=<?php echo $version;?>" />
    <script>var token='<?php echo $token?>'; var blankPic="<?php echo "{$staticroot}/apps/game/smallGame/catsEatFish/pic/blank.gif?v={$version}";?>";</script>
    <script type="text/javascript" src="<?php echo "{$staticroot}/apps/game/smallGame/catsEatFish/assets/js/sys/jquery-1.11.3.min.js?v={$version}";?>"></script>
    <script type="text/javascript" src="<?php echo "{$staticroot}/apps/game/smallGame/catsEatFish/assets/js/sys/Model.js?v={$version}";?>"></script>
    <script type="text/javascript" src="<?php echo "{$staticroot}/apps/game/smallGame/catsEatFish/assets/js/sys/fastclick.js?v={$version}";?>"></script>
    <script type="text/javascript" src="<?php echo "{$staticroot}/apps/game/smallGame/catsEatFish/assets/js/sys/touchSwipe.min.js?v={$version}";?>"></script>
    <script type="text/javascript" src="<?php echo "{$staticroot}/apps/game/smallGame/catsEatFish/assets/js/sys/Common.js?v={$version}";?>"></script>
    <script type="text/javascript" src="<?php echo "{$staticroot}/apps/game/smallGame/catsEatFish/assets/js/sys/Form.js?v={$version}";?>"></script>

</head>
