<?php
$arr    = json_decode($info['message'], true);
$msg    = Common::jsonEncode($arr[2]);
$action = $arr[0] . '_' . $arr[1];
?>

<table class="editTable">
	<tr>
		<th>用户名</th>
		<td><?=$info['username']?></td>
	</tr>
	<tr>
		<th>操作</th>
		<td><?=$action?></td>
	</tr>
	<tr>
		<th>内容</th>
		<td><textarea id="jsonTextArea" style="width: 400px;height: 200px;"><?=$msg?>></textarea></td>
	</tr>


	</td>
	</tr>
</table>



