<?php echo $this->render("layout/header3.phtml"); ?>

<div data-options="region:'center',split:true,border:false" style="overflow: hidden;">
	<div id="datagrid_toolbar" style="padding:5px;">
		<form method="post" id="search_form" style="padding: 0px;">
			用户:<input id="name" name="filter[username]" style="width: 100px" value="">
			<input name="token" value="<?php echo $token; ?>" type="hidden"/>
			<input name="togrid" value="1" type="hidden"/>
			<a href="javascript:search(datagrid,'#search_form');" class="easyui-linkbutton" iconCls="icon-search" plain="true">查 询</a>
		</form>
	</div>
	<table id="datagrid" toolbar="#datagrid_toolbar" border="false"></table>
</div>
<script>
	var token = "<?php echo $token;?>";
	var edit_W = 500;
	var edit_H = 400;
	var datagrid;
	$(function () {
		//数据列表
		datagrid = $("#datagrid").datagrid({
			url: '<?php echo $logUrl;?>',
			queryParams: {'togrid': 1, 'token': token},
			fit: true,
			autoRowHeight: false, //自动行高
			border: false,
			pagination: true, //分页栏
			pagePosition: 'bottom', //分页栏位置
			rownumbers: true,//显示行数
			striped: true,//显示条纹
			showFooter: true, //显示统计行
			pageSize: 20,//每页记录数
			remoteSort: true,//是否通过远程服务器对数据排序
			singleSelect: false,//只允许选择单行
			// main content

			sortName: 'id',//默认排序字段
			sortOrder: 'desc',//默认排序方式 'desc' 'asc'
			idField: 'id',
			columns: [[
				{field: 'id', title: 'id', sortable: false, align: 'center', width: 60},
				{field: 'uid', title: 'UID', sortable: false, align: 'center', width: 60},
				{field: 'username', title: '用户', sortable: false, width: 100},
				{field: 'action', title: '操作', sortable: false, align: 'center', width: 120},
				{field: 'msg', title: '数据内容', sortable: false, align: 'center', width: 400},
				{field: 'create_time', title: '时间', sortable: false, align: 'center', width: 120},
			]],

			onLoadSuccess: function () {
				$(this).datagrid('clearSelections');//取消所有的已选择项
				$(this).datagrid('unselectAll');//取消全选按钮为全选状态
			},
			onRowContextMenu: function (e, rowIndex, rowData) {
				e.preventDefault();
				$(this).datagrid('unselectAll');
				$(this).datagrid('selectRow', rowIndex);
				$('#datagrid_menu').menu('show', {
					left: e.pageX,
					top: e.pageY
				});
			},
			onDblClickRow: function (rowIndex, rowData) {
				edit(rowIndex, rowData);
			}
		});

	});


	function edit(rowIndex, rowData) {
		editData(rowIndex, rowData, "编辑", '#edit_form', datagrid, "<?php echo $editlogUrl;?>", edit_W, edit_H, 'id');
	}
</script>
<?php echo $this->render("layout/footer3.phtml"); ?>