<form method="post" action="<?php echo $passwdPostUrl; ?>" id="editUserFrom">
	<input name="token" value="<?php echo $token; ?>" type="hidden"/>
	<table class="editTable">
		<tr>
			<th>当前密码</th>
			<td>
				<input class="easyui-textbox" type="password" maxlength="20" name="current_password">
				<span class="col_require">*</span>
			</td>
		</tr>
		<tr>
			<th>新密码</th>
			<td>
				<input class="easyui-textbox" type="password" maxlength="20" name="password">
				<span class="col_require">*</span>
			</td>
		</tr>
		<tr>
			<th>重复密码</th>
			<td>
				<input class="easyui-textbox" type="password" maxlength="20" name="r_password">
				<span class="col_require">*</span>
			</td>
		</tr>
	</table>
</form>
<!-- <script type="text/javascript">
	//用户表单数据提交
    $(function(){
        $('#editUserFrom').form({
            success:function(data){
            	var data = JSON.parse(data);
            	if(data.success){
                	$.messager.alert('提示信息', data.msg, 'success');
            	} else {
                	$.messager.alert('提示信息', data.msg, 'error');
            	}
            }
        });
    });
</script> -->