<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">分享活动</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
	<tr class="tr">
			<th class="th">手机号</th>
			<td class="td"><input class="input wb" type="text" name="phone" value="<?php echo $search['phone'];?>"></td>
			<th class="th">用户uid</th>
			<td class="td"><input class="input wb" type="text" name="uid" value="<?php echo $search['uid'];?>"></td>
		</tr>
		<tr class="tr">
			
		</tr>
		<tr class="tr">
			<th class="th">分享时间</th>
			<td class="td">
			<input class="input" type="text" maxlength="30" id="start_time" name="start_time" value="<?php echo $search['start_time'];?>">
			<input class="input" type="text" maxlength="30" id="end_time" name="end_time" value="<?php echo $search['end_time'];?>">
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></div>

</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="150">手机号</td>
			<td>UID</td>
			<td>分享时间</td>
			<td width="200">点击量</td>
			<td>状态</td>
			<td>操作</td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['phone'];?></td>
			<td><?php echo $value['uid'];?></td>
            <td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
			<td><?php echo $value['hits'];?></td>
			<td><?php echo $value['status'] == 1 ? '有效' : '无效';?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/admin/highcharts.js"></script>
<script type="text/javascript">
$(document).ready(function() {
	$("#start_time").datepicker({
				dateFormat : 'yy-mm-dd'
	});
	$("#end_time").datepicker({
		dateFormat : 'yy-mm-dd'
});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
