<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">商家列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加商家</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<td class="td">类型</td>
			<td class="td">
				<select name="type_id" class="wa">
						<option <?php if (!$search['type_id']) echo 'selected';?>  value="">所有类型</option>
					<?php foreach ($types as $key=>$value) {?>
						<option <?php if ($search['type_id'] == $key) echo 'selected = selected';?>  value="<?php echo $key;?>"><?php echo $value;?></option>
					<?php }?>
				</select>
			</td>
			<td class="td">国家</td>
			<td class="td">
				<select name="country_id" class="wa">
						<option <?php if (!$search['country_id']) echo 'selected';?>  value="">所有类型</option>
					<?php foreach ($countrys as $key=>$value) {?>
						<option <?php if ($search['country_id'] == $value['id']) echo 'selected = selected';?>  value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
					<?php }?>
				</select>
			</td>
			
		</tr>
		<tr class="tr">
			<td class="td">商家名称</td>
			<td class="td">
				<input class="input wb" type="text" name="name" value="<?php echo $search['name'];?>">
			</td>
			<td class="td">状态</td>
			<td class="td">
				<select name="status" class="wa">
					<option value="0">所有状态</option>
					<option <?php if ($search['status'] == 2) echo 'selected';?>  value="2">关闭</option>
					<option <?php if ($search['status'] == 1) echo 'selected';?>  value="1">开启</option>
				</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">排序</td>
			<td width="40">商家ID</td>
			<td>商家名称</td>
			<td>类型</td>
			<td>国家</td>
			<td>是否推荐</td>
			<td>logo</td>
           <td>状态</td>
			<td>操作</td>
		</tr>
<?php foreach($malls as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['name'];?></td>
			<td><?php echo $types[$value['type_id']];?></td>
			<td><?php echo $countrys[$value['country_id']]['name'];?></td>
			<td><?php echo $value['is_top'] == 1 ? '是' : '否';?></td>
			<td><img src="<?php echo $attachPath.$value['logo'];?>" width="60" /></td>
			<td><?php echo $value['status'] == 1 ? '开启' : '关闭';?></td>
			<td>
				<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
