<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<title>使用说明</title>
<link rel="stylesheet" type="text/css" href="<?php echo $staticResPath;?>/call/css/style.min.css?version=<?php echo $version; ?>" />
</head>

<body class="ui-app">
<div class="ui-top-bar">
	<a class="ui-pos link-back" href="/user/index/index"></a>
	<span class="ui-top-txt">使用说明</span>
</div>

<div class="ui-page page1 js-active">
	<div class="ui-page-content">
		<div class="ui-page-blank">
		<?php echo $content;?>
		</div>
	</div>
</div>
</body>
</body>
</html>