<?php echo $this->render("../../Front/views/layout/header.phtml");?>
<div id="page">
		<header class="hd">
			<h1>兑奖</h1>
			<div class="back">
				<a href="<?php echo $webroot?>/user/index/signin"><span class="left-arrow"><i></i></span></a>
			</div>
		</header>
		
		<article class="ac">
			<div class="prize-box">
				<div class="prize-top prize-bg">
					<h1>恭喜你！</h1>
					<p>你获得<?php echo $prize['name'];?>！！</p>
				</div>
				<div class="prize-main">
					<h2>奖品领取</h2>
					<p>
						填写完整的个人信息。
					</p>
				</div>
				<div class="prize-info">
					<a href="<?php echo $webroot;?>/user/userinfo/index">
						<dl>
							<dt>个人信息</dt>
							<dd><label>账号：</label><span><?php echo $user_info['username'];?></span></dd>
							<dd><label>姓名：</label><span><?php echo $user_info['realname'];?></span></dd>
							<dd><label>QQ：</label><span><?php echo $user_info['qq'];?></span></dd>
							<dd><label>地址：</label><span><?php echo $user_info['address'];?></span></dd>
						</dl>
					</a>

				</div>
			</div>
		</article>
	</div>
<?php echo $this->render("../../Front/views/layout/tj.phtml");?>
<?php echo $this->render("../../Front/views/layout/footer.phtml");?>