<!DOCTYPE HTML>
<html>
<head>
    <title>购物大厅-手机购物，一个就够了</title>
    <meta charset="UTF-8">
    <meta name="keywords" content="购物大厅下载，逛淘宝，淘宝，掏宝，网上购物，在线交易，网上交易，网上买，网上卖，购物网站，团购，店铺，热门推荐，人气宝贝，特惠，热榜，手机购物，智能推荐，购物软件，购物应用，购物指南，同款比价，美丽说，蘑菇街，口袋，口袋购物，购物，购物中心，购物大厅，导购，淘宝网，手机购物，话费充值">
    <meta name="description" content="购物大厅官方网站。千万用户选择的智能手机购物软件，不用再烦恼手机内存不够，要安装淘宝、天猫、京东、唯品会、团购、话费、彩票……手机购物，下载一个就购了！ ">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />

    <link rel="shortcut icon" href="<?php echo $staticResPath;?>/assets/img/favicon.ico" type="image/x-icon">
    <link type="text/css" rel="stylesheet" href="<?php echo $staticSysPath;?>/reset/phonecore.css?t=<?php echo $version;?>">
    <link rel="stylesheet" type="text/css" href="http://assets.3gtest.gionee.com/apps/17gou/assets/css/mdownload.css?t=<?php echo $version;?>">
</head>

<body>

<div class="module">
    <section class="top-banner">
        <div class="legend">版本：<?php echo $configs['apk_version'];?>   更新日期：<?php echo $configs['apk_uptime'];?></div>
        <a onclick="_hmt.push(['_trackEvent','17gou手机版','点击','免费下载'])" href="<?php echo $dlapkUrl;?>" class="btn btn-download">立即免费下载</a>
    </section>
    <section class="content">
        <ul class="content-ul">
            <li>
                <i class="icon icon-home"></i>
                <div class="item">
                    <h3>一站通达</h3>
                    <p>全网电商齐入驻，淘宝、天猫、京东，想去哪就去哪</p>
                </div>
            </li>
            <li>
                <i class="icon icon-heart"></i>
                <div class="item">
                    <h3>量身定制</h3>
                    <p>自由组合喜欢的网购站点，随时随地增加或取消站点，只爱您所爱</p>
                </div>
            </li>
            <li>
                <i class="icon icon-tool"></i>
                <div class="item">
                    <h3>超省内存</h3>
                    <p>购物大厅（1.5M）=淘宝+天猫+京东+唯品会+亚马逊+苏宁+一号店+…</p>
                </div>
            </li>
            <li>
                <i class="icon icon-group"></i>
                <div class="item">
                    <h3>千万用户</h3>
                    <p>千万次的下载，每天都有数万人和您一起加入购物大厅</p>
                </div>
            </li>
        </ul>
        <a href="tel:<?php echo $configs['kefu_phone'];?>;" class="btn-contact">拨打客服电话</a>
    </section>
    <footer id="footer">
        <div class="version">
            <div class="vertion">
                <a href="http://gou.gionee.com/?source=17gou" title="购物大厅">触屏版</a>
                <span class="line">&nbsp;|&nbsp;</span>
                <a href="/front/index/pc">电脑版</a>
            </div>
        </div>
        <div class="copyright">copyright © 2014 粤ICP备05087105号</div>
    </footer>
</div>

<script type="text/javascript" src="<?php echo $staticSysPath;?>/lib/zepto/zepto.js?t=<?php echo $version;?>"></script>
<script type="text/javascript" src="<?php echo $staticResPath;?>/assets/js/mdownload.js?t=<?php echo $version;?>"></script>
<script type="text/javascript">
    var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
    document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F74bcaf75461ade64fa3da20abb4a15a2' type='text/javascript'%3E%3C/script%3E"));
</script>
</body>
</html>