<!DOCTYPE HTML>
<html>
<head>
    <title>购物大厅-手机购物，一个就够了</title>
    <meta charset="UTF-8">
    <meta name="keywords" content="购物大厅下载，逛淘宝，淘宝，掏宝，网上购物，在线交易，网上交易，网上买，网上卖，购物网站，团购，店铺，热门推荐，人气宝贝，特惠，热榜，手机购物，智能推荐，购物软件，购物应用，购物指南，同款比价，美丽说，蘑菇街，口袋，口袋购物，购物，购物中心，购物大厅，导购，淘宝网，手机购物，话费充值">
    <meta name="description" content="购物大厅官方网站。千万用户选择的智能手机购物软件，不用再烦恼手机内存不够，要安装淘宝、天猫、京东、唯品会、团购、话费、彩票……手机购物，下载一个就购了！ ">

    <link rel="shortcut icon" href="<?php echo $staticResPath;?>/assets/img/favicon.ico" type="image/x-icon">
    <link type="text/css" rel="stylesheet" href="<?php echo $staticResPath;?>/assets/css/html5-doctor-reset-stylesheet.css?t=<?php echo $version;?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $staticResPath;?>/assets/css/download.css?t=<?php echo $version;?>">
    <!--[if lt IE 9]>
    <script src="<?php echo $staticResPath;?>/assets/js/lib/html5shiv.min.js?t=<?php echo $version;?>"></script>
    <![endif]-->
</head>

<body>
<header id="header">
    <div class="header-body">
        <div class="logo">
            <img src="<?php echo $staticResPath;?>/assets/img/logo.png" alt="购物大厅-为你量身定制一款全能的手机购物软件">
        </div>
        <a class="btn-contact" id="J_contact_btn" href="javascript:;"></a>
    </div>
</header>

<section id="banner">
    <div class="content">
        <div class="handle-phone"></div>
        <div class="main">
            <div class="title"></div>
            <div class="legend">版本：<?php echo $configs['apk_version'];?>&nbsp;&nbsp;&nbsp;更新日期：<?php echo $configs['apk_uptime'];?></div>
            <div class="wrap">
                <div class="btn-wrap">
                    <a onclick="_hmt.push(['_trackEvent','17gou-PC版','点击','android免费下载'])" href="<?php echo $configs['android_dl_url'];?>" id="J_android_btn" class="btn btn-android"></a><br>
                    <a onclick="_hmt.push(['_trackEvent','17gou-PC版','点击','ios免费下载'])" href="<?php echo $configs['ios_dl_url'];?>" id="J_iphone_btn" class="btn btn-iphone"></a>
                </div>
                <div class="code">
                    <img src="<?php echo $erwm;?>">
                    <span>扫描二维码下载</span>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="description mt">
            <img src="<?php echo $staticResPath;?>/assets/img/desc1.jpg" alt="一站通达-全网电商齐入驻，淘宝、天猫、京东，想去哪就去哪"/>
        </div>
        <div class="description">
            <img src="<?php echo $staticResPath;?>/assets/img/desc2.jpg" alt="量身定制-自由组合喜欢的网购站点，随时随地增加或取消站点，只爱您所爱~"/>
        </div>
        <div class="description">
            <img src="<?php echo $staticResPath;?>/assets/img/desc3.jpg" alt="超省内存-购物大厅（1.5M）=淘宝+天猫+京东+唯品会+当当网+亚马逊+苏宁+一号店+凡客+彩票+聚划算+团购..."/>
        </div>
        <div class="description">
            <img src="<?php echo $staticResPath;?>/assets/img/desc4.jpg" alt="千万用户-千万次的下载，每天都有万人和你一起加入购物大厅"/>
        </div>
</section>

<nav id="nav">
    <ul class="nav-ul">
        <li class="item1">
            <h3>客服</h3>
            <p>邮箱：<?php echo $configs['kefu_mail'];?></p>
            <p>电话：<?php echo $configs['kefu_phone'];?></p>
        </li>
        <li class="item2">
            <h3>商务合作</h3>
            <p>邮箱：<?php echo $configs['bd_mail'];?></p>
            <p>电话：<?php echo $configs['bd_phone'];?></p>
        </li>
        <li class="item3">
            <h3>关注我们</h3>
            <p><i class="icon icon-weibo"></i>微博号：<?php echo $configs['gz_weibo'];?></p>
            <p><i class="icon icon-weixin"></i>微信号：<?php echo $configs['gz_weixin'];?></p>
            <p><i class="icon icon-qq"></i>QQ群：<?php echo $configs['gz_qq'];?></p>
        </li>
        <li class="item4">
            <h3>扫码下载</h3>
            <img src="<?php echo $erwm;?>">
        </li>
    </ul>
</nav>

<footer id="footer">
    <div class="vertion"><a href="http://gou.gionee.com/?source=17gou" title="购物大厅">触屏版</a> | <span class="dis">电脑版<span></div>
    <div class="copyright">copyright © 2014 粤ICP备05087105号</div>
</footer>

<div id="J_contact_box" class="contact-box" style="display: none;">
    <div class="box-heading"></div>
    <div class="box-content">
        <h3>商家入驻</h3>
        <p>1.卖家/商家合作：淘宝/天猫店铺，独立购物电商合作；</p>
        <p>2.电商平台合作：购物电商平台联盟合作；</p>
        <p>请Email：bd@gouwudating.com</p>
        <h3>市场合作</h3>
        <p>如果您有关于广告投放、商务合作、渠道合作、资源互换等多种形式合作的问题，请Email: bd@gouwudating.com，或联系QQ:1754626171，并简要介绍合作需求.</p>
    </div>
</div>


<script type="text/javascript" src="<?php echo $staticResPath;?>/assets/js/lib/jquery.min.js?t=<?php echo $version;?>"></script>
<script type="text/javascript" src="<?php echo $staticResPath;?>/assets/js/lib/layer/layer.min.js?t=<?php echo $version;?>"></script>
<script type="text/javascript" src="<?php echo $staticResPath;?>/assets/js/download.js?t=<?php echo $version;?>"></script>
<script type="text/javascript">
    var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
    document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F74bcaf75461ade64fa3da20abb4a15a2' type='text/javascript'%3E%3C/script%3E"));
</script>
</body>
</html>