<?php echo $this->render("layout/header.phtml");?>
<header id="header"><span class="hd-title">装机必备</span></header>
<section class="main">
<ul class="app-list J_app_item" >
	</ul>
	<div class="load-more J_loadMore" style="display:none;" data-ajaxUrl="<?php echo $webroot.$moreUrl."?cku={$cku}&chl={$chl}";?>" data-hasnext="<?php echo ($hasnext)? "true" : "false"?>" data-curpage="0">
		<span id="J_text_tip" class="text-tip" >上拉加载更多应用...</span>
		<span id="J_img_tip" class="img-tip"></span>
	</div>
</section>
<?php echo $this->render("layout/footer.phtml");?>