<!DOCTYPE html>
<html lang="en">
<head>
        <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="format-detection" content="email=no" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="format-detection" content="email=no" />
        <meta charset="UTF-8">
        <link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/apkv1/assets/css/holidayPreheationg.sourc.css?v=<?php echo $version;?>">
        <title>假期任务</title>
</head>
<body>      
        <div class="date-content">
                <p class="title">活动即将开始，剩余</p>
                <p class="date" id="date">2天14小时32分</p>
        </div>
        <div class="activity-title">
                <h2>活动提醒: </h2>
                <p>为了您能顺利参加活动，请先更新游戏大厅版本至<?php echo $limitClientVersion;?>以上 并登录账号 </p>
        </div>
        <div class="but">
                <input type="button" id="update" value="更新至<?php echo $limitClientVersion;?>以上版本" />
        </div>

        <div class="holiday-preheationg" style="background-image:url(<?php echo $attachPath.$preImg; ?>)">
        </div>
</body>
<script src="<?php echo $staticroot; ?>/apps/game/apkv1/assets/js/sys/zepto.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticroot; ?>/apps/game/apkv1/assets/js/sys/Common.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticroot; ?>/apps/game/apkv1/assets/js/holiday/preheationg.js?v=<?php echo $version;?>"></script>
<script type="text/javascript">
        holidayData = <?php echo json_encode($holidayData); ?>
</script>
</html>