<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
    <ul class="cc">
        <li class="current"><a href="<?php echo $indexUrl;?>">行为列表</a></li>
    </ul>
</div>
<form action="<?php echo $indexUrl;?>" method="get" id="logForm">
    <input name="token" type="hidden" value="<?php echo $token;?>" />
    <div class="table_full">
        <table width="100%">
            <tr class="tr">
                <th class="th">URL关键词</th>
                <td class="td">
                    <input type="text" class="input wb" name="module" id="module" value="<?php echo $param['module'];?>"/>
                </td>
                <th class="th">操作时间</th>
                <td class="td">
                    <input class="input" type="text"  id="from_time" name="from_time" value="<?php echo $param['from_time'];?>">-
                    <input class="input" type="text"  id="to_time" name="to_time" value="<?php echo $param['to_time'];?>">
                </td>
            </tr>
            <tr class="tr">
                <th class="th">用户名</th>
                <td class="td">
                    <input type="text" class="input wb" name="username" id="username" value="<?php echo $param['username'];?>"/>
                </td>
                <th class="th">用户组</th>
                <td class="td">
                    <select name="groupid" id="groupid" >
                        <option value="">请选择</option>
                        <?php foreach ($groups as $key => $item): ?>
                        <option value="<?php echo $key; ?>" <?php if ($key == $param['groupid']) echo 'selected="selected"' ?>><?php echo $item['name']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr class="tr">
                <th class="th">&nbsp;</th>
                <td class="td" colspan="3">
                    <span class="btn"><span><button type="submit">搜 索</button></span></span>
                    <span class="btn"><span><button type="button" onclick="deleteLog();">删 除</button></span></span>
                </td>
            </tr>
        </table>
    </div>
</form>
<div class="table_list">
    <table width="100%">
        <tr class="hd">
            <td width="5%">用户ID</td>
            <td width="8%">用户名</td>
            <td width="8%">用户组</td>
            <td width="45%">URL</td>
            <td width="10%">Action</td>
            <td width="15%">操作时间</td>
            <td width="10%">操作</td>
        </tr>
        <r>
        <?php foreach($logs as $key => $value) {?>
            <tr class="ct">
                <td><?php echo $value['uid'];?></td>
                <td><a href="<?php echo $userUrl;?>/?uid=<?php echo $value['uid'];?>"><?php echo $value['username'];?></a></td>
                <td><?php echo isset($groups[$value['groupid']]) ? $groups[$value['groupid']]['name']: '-';?></td>
                <td><?php echo $value['url'];?></td>
                <td><?php echo $value['type'];?></td>
                <td><?php echo date('Y-m-d H:i:s', $value['time']);?></td>
                <td><a href="<?php echo $detailUrl;?>/?id=<?php echo $value['_id'];?>">查看</a></td>
            </tr>
        <?php } ?>
    </table>
</div>
<div class="mr10 cc">
    <?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script>
    $(document).ready(function() {
        $("#to_time").datetimepicker();
        $("#from_time").datetimepicker();
    });

    deleteLog = function(e){
        showConfirm("确认批量删除日志？", function() {
            ajaxLoader.show();
            var module = $('#module').val();
            var username = $('#username').val();
            var groupid = $('#groupid').val();
            var from_time = $('#from_time').val();
            var to_time = $('#to_time').val();
            $.ajax({
                url	:'<?php echo $patchDeleteUrl; ?>',
                type:'post',
                dataType: 'json',
                data:'token=<?php echo $token;?>&module='+module+'&username='+username+'&groupid='+groupid+'&from_time='+from_time+'&to_time='+to_time,
                success : function(ret) {
                    ajaxLoader.hide();
                    if (ret.success) {
                        alert(ret.msg);
                        location.reload();
                    } else {
                        showError('', ret.msg);
                    }
                }
            });
        }, e);
    };

</script>
<?php echo $this->render("layout/footer.phtml");?>
