<?php echo $this->render("layout/header3.phtml");
$_listUrl = $this->addresslistUrl;
$_editUrl = $this->addresseditUrl;
?>

	<div data-options="region:'center',split:true,border:false" style="overflow: hidden;">

		<div id="datagrid_toolbar" style="padding:5px;">

		</div>
		<table id="datagrid" toolbar="#datagrid_toolbar" border="false"></table>
	</div>


	<script>
		var token = "<?php echo $token;?>";
		var edit_W = 400;
		var edit_H = 300;
		var datagrid;
		$(function () {

			//数据列表
			datagrid = $("#datagrid").datagrid({
				url: '<?php echo $_listUrl;?>',
				queryParams: {'togrid': 1, 'token': token},
				fit: true,
				autoRowHeight: false, //自动行高
				border: false,
				pagination: true, //分页栏
				pagePosition: 'bottom', //分页栏位置
				rownumbers: true,//显示行数
				striped: true,//显示条纹
				showFooter: true, //显示统计行
				pageSize: 20,//每页记录数
				remoteSort: true,//是否通过远程服务器对数据排序
				singleSelect: false,//只允许选择单行
				// main content

				sortName: 'id',//默认排序字段
				sortOrder: 'desc',//默认排序方式 'desc' 'asc'
				idField: 'id',
				columns: [[
					{field: 'ck', checkbox: true},
					{field: 'id', title: 'ID', sortable: true, align: 'center', width: 60},
					{field: 'openid', title: 'openid', sortable: false, width: 160},
					{field: 'nickname', title: '呢称', sortable: false, width: 100},
					{field: 'rank', title: '名次', sortable: false, width: 60},
					{field: 'username', title: '名称', sortable: false, width: 100},
					{field: 'province_id', title: '省份', sortable: false, width: 60},
					{field: 'city_id', title: '城市', sortable: false, width: 60},
					{field: 'address', title: '地址', sortable: false, align: 'center', width: 500},
					{field: 'phone', title: '手机', sortable: false, align: 'center', width: 80},
					{field: 'created_at', title: '参加时间', sortable: false, align: 'center', width: 100},
				]],

				onLoadSuccess: function () {
					$(this).datagrid('clearSelections');//取消所有的已选择项
					$(this).datagrid('unselectAll');//取消全选按钮为全选状态
				},
				onRowContextMenu: function (e, rowIndex, rowData) {
					e.preventDefault();
					$(this).datagrid('unselectAll');
					$(this).datagrid('selectRow', rowIndex);
					$('#datagrid_menu').menu('show', {
						left: e.pageX,
						top: e.pageY
					});
				},
				onDblClickRow: function (rowIndex, rowData) {
					edit(rowIndex, rowData);
				}
			});

		});


		function add() {
			addData("添加", "#edit_form", datagrid, "<?php echo $_editUrl;?>", edit_W, edit_H);
		}
		function edit(rowIndex, rowData) {
			editData(rowIndex, rowData, "编辑", '#edit_form', datagrid, "<?php echo $_editUrl;?>", edit_W, edit_H, 'id');
		}
		function del() {
			delData(datagrid, "<?php echo $_delUrl;?>");
		}
	</script>
<?php echo $this->render("layout/footer3.phtml"); ?>