<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li class="current"></li>

	</ul>
</div>
<div class="table_full">
	<form method="post" action="<?php echo $baseUrl; ?>" id="addFrom">
		<input type="hidden" name="token" value="<?php echo $token; ?>"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">时间范围</th>
					<td class="td">
						<input class="input" type="text" maxlength="30" id="sdate" name="sdate"
						       value="<?php echo $searchParam['sdate']; ?>"> 至
						<input class="input" type="text" id="edate" maxlength="30" name="edate"
						       value="<?php echo $searchParam['edate']; ?>">

					</td>
				</tr>
				<tr class="tr">
					<th class="th">活动名称</th>
					<td class="td">
						<select name="event_id">
							<?php
							foreach ($list as $v) {
								$checked = ($v['id'] == $searchParam['event_id']) ? 'selected="selected"' : '';
								echo sprintf('<option value="%s" %s>%s</option>', $v['id'], $checked, $v['title']);
							}
							?>
						</select>

					</td>
				</tr>

			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
		<input type="hidden" id="hidden_export" name="export" value="0"/>

		<div class="h_a">
			&nbsp; <span id="total" style="color: red;font-size:14px"></span>
			<span style="float:left;"><input type="button" value="导出" id="downLoad"></span>
		</div>
	</form>
</div>
<div class="table_list">

	<div id="main" style="height:400px;"></div>

	<script src="<?php echo $staticPath; ?>/v2/echarts/echarts.js" type="text/javascript"></script>


	<script type="text/javascript">


		require.config({
			paths: {"echarts": "<?php echo $staticPath;?>/v2/echarts"},
			packages: [
				{
					name: 'echarts',
					location: '../../src',
					main: 'echarts'
				},
			]
		});

		var option = {
			tooltip: {
				trigger: 'axis'
			},
			xAxis: [
				{
					type: 'category',
					data: <?php echo json_encode(array_keys($dataList));?>
				}
			],
			yAxis: [
				{
					type: 'value'
				}
			],
			series: [
				{
					name: '蒸发量',
					type: 'line',
					data:<?php echo json_encode(array_values($dataList));?>
				},
			]
		};

		require(
			[
				'echarts',
				'echarts/chart/line',
			],
			function (ec) {
				var myChart = ec.init(document.getElementById('main'));
				myChart.setOption(option);
			}
		)
	</script>

</div>
<script src="<?php echo $staticPath; ?>/js/common/jquery-ui-timepicker.js"></script>

<script type="text/javascript">
	$(document).ready(function () {
		$("#sdate").datetimepicker();
		$("#edate").datetimepicker();

		$("#downLoad").bind('click', function () {
			$("#hidden_export").val(1);
			$("#addFrom").submit();
			$("#hidden_export").val(0);
		});
	});
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
	
	