<?php echo $this->render("layout/header.phtml");?>
	<div data-role="page" id="page" class="service" data-theme="no">
		<?php echo $this->render("layout/nav.phtml");?>
		<nav class="sub-nav">
				<ul>
					<li><a href="<?php echo $servicesUrl;?>"><span>联系方式</span></a></li>
					<li  class="selected"><a href="<?php echo $servicesFaqUrl;?>"><span>常见问题</span></a></li>
					<li><a href="<?php echo $servicesSaleUrl;?>"><span>销售网点</span></a></li>
					<li><a href="<?php echo $servicesBranchUrl;?>"><span>服务网点</span></a></li>
				</ul>
		</nav>
		<div class="ct text">
			<p>问：手机通话后为什么会黑屏？<br> 答：在通话过程中黑屏有两个好处，第一是可以省电，第二是手机屏幕比大也是触屏手机，以免误触摸其他按键，引起误操作。灭屏有两种原因，第一个原因是距离感应器，智能手机特意增加这个功能的，当你接听电话的时候靠近耳朵的时候屏灭，这样也是避免脸或者是什么碰触其他按键，引起误操作，当你拿离开耳朵屏就自然点亮，这个时候可以进行任何的操作，第二个原因是屏幕自然灭了，这个时候你可以按下HOME键（主屏幕键）或者是power键点亮屏幕。在通话的主界面按menu键是无效是因为通话界面的菜单已经完全显示在屏幕上，因此调不出任何的菜单。如果需要进入到手机中其他菜单，按下返回键，通话继续，在状态栏上有个正在通话的图标。
			</p>
			<p>问：手机在充电或使用过程中，使用久了机身均会发烫<br>
			答：手机充电的时候是会发热的，如果不烫手的话属于正常，对比其他智能手机都是如此，其他品牌手机如三星，MOTO，HTC都是这样的。
			</p>
			<p>问：在静音模式下，触按音量键会切回之前模式<br>
			答：Android智能手机设计是这样的，和以前的功能手机不一样，不存在情景模式，当你铃声音量最小的时候自动进入到静音模式，你也可以在当前的音量下进入设置直接勾选静音，这个时候你按减小音量键是不会回到之前的模式，如果你是增大音量键，那么系统就智能的认为你是要回到之前的模式，就切换回去了。
			</p>
			<p>问：如何添加待机界面窗口?<br>
			答：在待机界面，长按屏幕空白的地方会有弹出添加到主屏幕，快捷方式，窗口小部件，文件夹，壁纸等选项，也可以在主屏幕界面按下menu，选择添加。
			</p>
		</div>
	</div>
<?php echo $this->render("layout/footer.phtml");?>
