<?php echo $this->render("layout/header.phtml"); ?>
	<div class="h_a">导入应用</div>
	<form method="post" action="<?php echo $importUrl; ?>" id="addFrom" enctype="multipart/form-data">
		<input name="token" value="<?php echo $token; ?>" type="hidden"/>

		<div class="table_full">
			<table width="100%">

				<tr class="tr">
					<th class="th">分类文件</th>
					<td class="td"><input type="file" class="input" name="localnav[type]" value=""></td>
					<td class="td"><a href="<?php echo $exportUrl; ?>?type=type">导出</a></td>
				</tr>
			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
	</form>
	<form method="post" action="<?php echo $importUrl; ?>" id="addFrom" enctype="multipart/form-data">
		<input name="token" value="<?php echo $token; ?>" type="hidden"/>

		<div class="table_full">
			<table width="100%">

				<tr class="tr">
					<th class="th">栏目文件</th>
					<td class="td"><input type="file" class="input" name="localnav[column]" value=""></td>
					<td class="td"><a href="<?php echo $exportUrl; ?>?type=column">导出</a></td>
				</tr>
			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
	</form>
	<form method="post" action="<?php echo $importUrl; ?>" id="addFrom" enctype="multipart/form-data">
		<input name="token" value="<?php echo $token; ?>" type="hidden"/>

		<div class="table_full">
			<table width="100%">

				<tr class="tr">
					<th class="th">链接文件</th>
					<td class="td"><input type="file" class="input" name="localnav[list]" value=""></td>
					<td class="td">
						<?php foreach ($types as $v): ?>
							<a href="<?php echo $exportUrl; ?>?type=list&type_id=<?php echo $v['id']; ?>">导出<?php echo $v['name']; ?></a>
							<br>
						<?php endforeach; ?>
					</td>
				</tr>
			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
	</form>
	<script type="text/javascript">
		//广告表单数据提交
		$(document).ready(function () {
			ajaxForm('addFrom', function (ret) {
				ajaxRedirect(ret, baseurl + '/Admin/Localnav/list');
			});
		})
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>