<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl; ?>">闪屏列表</a></li>
		<li class="current"><a href="javascript:;">添加闪屏</a></li>
	</ul>
</div>
<div class="h_a">添加闪屏</div>
<form method="post" action="<?php echo $addPostUrl; ?>" id="addFrom">
	<input name="token" value="<?php echo $token; ?>" type="hidden"/>

	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">闪屏标题</th>
				<td class="td"><input type="text" class="input wc" name="title" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">闪屏图片</th>
				<td class="td">
					<ul class="uploadImg">
						<li id="AdImg">
							<img src="<?php echo $staticPath; ?>/img/content/nopic.jpg"/>
							<input type="hidden" name="img_url" value="">
						</li>
					</ul>
					<p style="clear:both;">
						<iframe name="upload" src="<?php echo $uploadUrl . '/?imgId=AdImg'; ?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
					</p>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">闪屏版本</th>
				<td class="td"><input type="text" class="input" name="version" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">开始结束时间</th>
				<td class="td">
					<div>
						<input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value=""/> 至
						<input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value=""/>
					</div>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">闪屏状态</th>
				<td class="td"><select name="status">
						<option value="1">开启</option>
						<option value="0">关闭</option>
					</select></td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script src="<?php echo $staticPath; ?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
	//广告表单数据提交
	$(document).ready(function () {
		$('#start_time').datetimepicker();
		$('#end_time').datetimepicker();
		ajaxForm('addFrom', function (ret) {
			ajaxRedirect(ret, baseurl + '/Admin/Splash/index');
		});
	})
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
