<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">专题列表</a></li>
    <li class="current"><a href="javascript:;">编辑专题</a></li>
	</ul>
</div>
<div class="h_a">编辑专题</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="<?php echo $info['sort'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">专题名称</th>
			<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">专题简述</th>
			<td class="td"><textarea style="width: 600px; height: 200px" class="textarea"
						name="resume"><?php echo $info['resume'];?></textarea></td>
		</tr>
		<tr class="tr" style="display:none">
			<th class="th">是否推荐专题</th>
			<td class="td">
				<label class="mr20"><input <?php if($info['hot'] == 1) echo 'checked';?> " name="hot" value="1" type="radio">是</label>
				<label class="mr20"><input <?php if($info['hot'] == 0) echo 'checked';?>  name="hot" value="0" type="radio">否</label>
				
			</td>
		</tr>
		<tr class="tr">
			<th class="th">专题图标</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="sicon">
						<img src="<?php echo $attachPath,$info['icon'];?>"/>
						<input type="hidden" name="icon" value="<?php echo $info['icon'];?>">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=sicon';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">专题图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="simg">
						<img src="<?php echo $attachPath,$info['img'];?>"/>
						<input type="hidden" name="img" value="<?php echo $info['img'];?>">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=simg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">开始结束时间</th>
			<td class="td">
				<div>
					<input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo date('Y-m-d H:i:s', $info['start_time']);?>" /> 
					至 
					<input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="<?php echo date('Y-m-d H:i:s', $info['end_time']);?>" />
				</div>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
				<select name="status">
                	<option <?php if($info['status'] == 1) echo 'selected';?> value="1">开启</option>
                	<option <?php if($info['status'] == 0) echo 'selected';?> value="0">关闭</option>
            	</select>
            </td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script type="text/javascript">
//专题表单数据提交
showContent = function(flag) {
	if (flag == 2) {
		$("#link").hide();
	} else {
		$("#link").show();
	}
}
showContent(<?php echo $info['st_type'];?>);
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Subject/index?s=1');
	});
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
