
<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 导航栏Ajax加载 指向navagator.html  menuOn表示分别需要高亮的菜单栏id 用下划线_隔开 eg:bz_taotu_taotuPack-->
<section class="navigator" menuOn="zt_myThemes">

</section>

<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <!-- 壁纸详情-wp01-->
    <div id="zt_usr_01">
        <!-- 页面内容区域 注意：每个页面无论是否有内容 必定有一个content-->
        <div class="content">
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">状态</label>
                    <div class="tb_cont tb_cell">

                        <ul class="tag_list tag_one"><!-- tag_one 一级标签 只能选中一个 -->
                            <li value="0" class="<?php if (!$type) echo 'on' ?>">
                                <a href="/Admin/File/index">所有状态</a>
                            </li>
                            <?php foreach ($status as $k => $v) { ?>
                                <li value="<?php echo $k ?>" class="<?php if ($type == $k) echo 'on' ?>">
                                    <a href="/Admin/File/index?tid=<?php echo $k ?>"><?php echo $v ?></a>
                                </li>
                            <?php } ?>

                        </ul>

                    </div>
                    <div class="tb_cell">
                        <ul class="tb_switch">
                            <!--<li class="txt_switch">批量管理</li>
                            <li class="btn_switch switch_pics" openId="viewPics">宫格</li><!-- openId 表示点击时 显示哪个id下的内容 -->
                            <li class="btn_switch switch_list on" openId="viewList">列表</li>
                        </ul>
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->


            <!-- 宫格模式 admin_mode显示各子项目的管理按钮-->
            <section class="view view_pics " id="viewPics">
                <!-- 批量管理内容 默认隐藏 -->
                <div class="view_admin view_pics_admin">
                    <!-- checkObj表示 点击后 哪些class要被选中 -->
                    <button class="btn_check btn_check_all" checkClass="btn_check_pics"></button><label>全选</label><span class="btn btn_s1 pack_del">批量删除</span>
                </div>
                <h1 class="block_name">全部主题</h1>
                <ul class="view_pics_wrap "><!--  -->
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>

                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>


                </ul>
                <div class="clear-fix"></div>
            </section>

            <!-- 列表模式 -->
            <section class="view view_list show" id="viewList">
                <!-- 批量管理内容 默认隐藏 -->
                <div class="view_admin view_list_admin">
                    <!-- checkObj表示 点击后 哪些class要被选中 -->
                    <button class="btn_check btn_check_all" checkClass="btn_check_list"></button><label>全选</label><span class="btn btn_s1 pack_del">批量删除</span>
                </div>
                <table class="view_list_tb">
                    <thead>
                        <tr><th style="width:12rem">主题</th>
                            <th>名称</th>
                            <th>英文名</th>
                            <th>标签</th>
                            <th>上传时间</th>
                            <th>包类</th>
                            <th>操作</th>
                            <th>状态</th>
                            <th>下载</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php foreach ($theme as $v) { ?>
                            <tr>
                                <td>
                                    <button class="btn_check btn_check_list"></button>
                                    <img src="<?php echo $imageurl . '/' . str_replace('.webp', '.jpg', $themeimage[$v['id']][0]['img']); ?>" style="width:5rem; height:auto">
                                </td>
                                <td><?php echo $v['title'] ?></td>
                                <td><?php echo $v['Ename'] ?></td>
                                <td>
                                    <?php
                                    //一级标签;
                                    foreach ($idx as $t) {
                                        if ($v['id'] == $t['file_id']) {
                                            echo $alltype[$t['type_id']] . " ";
                                        }
                                    }
                                    ?>
                                </td>
                                <td><?php echo date("Y-m-d H:i:s", $v['create_time']) ?></td>
                                <td><?php echo 'V' . $v['package_type'] ?></td>
                                <td>
                                    <?php if ($v['status'] < 3 || $v['status'] > 4) { ?>
                                        <a class="btn_txt"
                                           href="/Admin/File/editFile?themeid=<?php echo $v['id'] ?>">编辑</a>

                                        <a val="<?php echo $v["id"]; ?>"  class="btn_txt pop_btn delBtn" openPopId="fixDetele">删除</a>
                                    <?php } ?>
                                </td>
                                <td><?php echo $status[$v['status']] ?></td>
                                <td><?php echo $v['down'] ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </section>

        </div><!-- content end -->

    </div>
</section>
<?php echo $this->render("common/pageshow.phtml"); ?>
<!-- 弹窗 消息+按钮-->
<div class="pop_wraper" id="fixDetele">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_tip">
                    <p class="tip_mes">是否要删除？</p>
                    <div class="tip_btns"><button class="btn_s2 del_ok">确定</button><button class="btn_s2 btnCancel">取消</button></div>
                    <div class="pop_close"></div>
                </div>

            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->
<script type="text/javascript">
    $(function () {
        $(".delBtn").click(function () {
            var theme = $(this).attr("val");
            $(".del_ok").click(function () {
                var data = "id=" + theme + "&token=" + token;
                var url = "/Admin/File/delete";
                $(".pop_wraper").removeClass("show");
                $.post(url, data, function (d) {
                    if (d) {
                        window.location.href = "/Admin/File/index";

                    }
                })
            })
        })

    })
</script>
</body>

</html>