<?php echo $this->render("layout/header2.phtml");?>
<link href="<?php echo "$staticPath/game/assets/css/finger-games.css?v=$version"; ?>" rel="stylesheet" />
<script type="text/javascript" src="<?php echo "$staticPath/game/assets/js/Form.js?v=$version"; ?>"></script>
<script type="text/javascript" src="<?php echo "$staticPath/game/assets/js/validate.js?v=$version"; ?>"></script>
<script type="text/javascript" src="<?php echo "$staticPath/game/assets/js/fingerGames.js?v=$version"; ?>"></script>
<script type="text/javascript" src="<?php echo "$staticPath/game/assets/js/template/fingerGames.js?v=$version"; ?>"></script>
<div class="nav">
    <ul class="cc">
        <li><a href="<?php echo $indexUrl;?>">划屏游戏列表</a></li>
        <li class="current"><a href="javascript:void();">添加活动</a></li>
    </ul>
</div>

<div id="prizeForm">
    <table class="holiday-task-border prize-task">
        <tr>
            <td class="space-left" style="min-width: 105px;">
                活动名称
            </td>
            <td class="space-left" colspan="6">
                <input name="name" type="text"/>
            </td>
        </tr>
        <tr>
            <td class="space-left">
                预热时间
            </td>
            <td  class="space-left" colspan="6">
                <input name="preheat_time" id="preheat_time" class="time" />
            </td>
        </tr>
        <tr>
            <td class="space-left">
                活动有效时间
            </td>
            <td  class="space-left" colspan="6">
                <input id="start_time" name="start_time" class="time"/>
                至
                <input id="end_time" name="end_time" class="time"/>
            </td>
        </tr>
        <tr>
            <td class="space-left">
                游戏记分时间
            </td>
            <td  class="space-left" colspan="6">
                <input id="game_start_time" name="game_start_time" class="time"  />
                至
                <input id="game_end_time" name="game_end_time" class="time" />
                <span style="color: red">&nbsp;&nbsp;这个时间段游戏能够获得分数与积分</span>
            </td>
        </tr>
        <tr>
            <td  class="space-left" >
                登录描述
            </td>
            <td class="space-left"  colspan="6">
                <input  type="text" name="login_desc" style="width:500px;"/>
            </td>
        </tr>
        <tr>
            <td class="space-left">
                预热图片
            </td>
            <td  class="space-left" colspan="2">
                <h6>背景图</h6>
                <ul class="uploadImg">
                    <li id="preHeatImg1">
                        <img class="js_form" src="<?php echo $staticPath;?>/img/content/nopic.jpg" />
                        <input type="hidden" name="preheat_img1" value="" />
                    </li>
                </ul>
                <p style="clear:both;">
                    <iframe name="upload" src="<?php echo $uploadUrl."/?imgId=preHeatImg1";?>" style="height:80px;width:100%;" frameborder="0" scrolling="no"></iframe>
                </p>
            </td>
            <td  class="space-left" colspan="2">
                <h6>素材1</h6>
                <ul class="uploadImg">
                    <li id="preHeatImg2">
                    <img class="js_form" src="<?php echo $staticPath;?>/img/content/nopic.jpg" />
                    <input type="hidden" name="preheat_img2" value="" />
                    </li>
                </ul>
                <p style="clear:both;">
                    <iframe name="upload" src="<?php echo $uploadUrl."/?imgId=preHeatImg2";?>" style="height:80px;width:100%;" frameborder="0" scrolling="no"></iframe>
                </p>
            </td>
            <td  class="space-left">
                <h6>素材2</h6>
                <ul class="uploadImg">
                    <li id="preHeatImg3">
                    <img class="js_form" src="<?php echo $staticPath;?>/img/content/nopic.jpg" />
                    <input type="hidden" name="preheat_img3" value="" />
                    </li>
                </ul>
                <p style="clear:both;">
                    <iframe name="upload" src="<?php echo $uploadUrl."/?imgId=preHeatImg3";?>" style="height:80px;width:100%;" frameborder="0" scrolling="no"></iframe>
                </p>
            </td>
        </tr>
        <tr>
            <td  class="space-left" >
                活动说明
            </td>
            <td colspan="6">
                <textarea  name="descript" class="ke-edit-textarea" hidefocus="true" style="width: 100%; height: 308px; "></textarea>
            </td>
        </tr>
        <tr>
            <td class="space-left">
                活动素材图片
            </td>
            <td class="space-left">
                <h6>背景图</h6>
                <ul class="uploadImg">
                    <li id="imgConfig1">
                        <img class="js_form" src="<?php echo $staticPath;?>/img/content/nopic.jpg" />
                        <input type="hidden" name="img_config_background" value="" />
                    </li>
                </ul>
                <p style="clear:both;">
                    <iframe name="upload" src="<?php echo $uploadUrl."/?imgId=imgConfig1";?>" style="height:80px;width:100%;" frameborder="0" scrolling="no"></iframe>
                </p>
            </td>
            <td class="space-left">
                <h6>记分道具</h6>
                <ul class="uploadImg">
                    <li id="imgConfig6">
                        <img class="js_form" src="<?php echo $staticPath;?>/img/content/nopic.jpg" />
                        <input type="hidden" name="img_config_store" value="" />
                    </li>
                </ul>
                <p style="clear:both;">
                    <iframe name="upload" src="<?php echo $uploadUrl."/?imgId=imgConfig6";?>" style="height:80px;width:100%;" frameborder="0" scrolling="no"></iframe>
                </p>
            </td>
            <td class="space-left">
                <h6>排行榜</h6>
                <ul class="uploadImg">
                    <li id="imgConfig2">
                        <img class="js_form" src="<?php echo $staticPath;?>/img/content/nopic.jpg" />
                        <input type="hidden" name="img_config_rank" value="" />
                    </li>
                </ul>
                <p style="clear:both;">
                    <iframe name="upload" src="<?php echo $uploadUrl."/?imgId=imgConfig2";?>" style="height:80px;width:100%;" frameborder="0" scrolling="no"></iframe>
                </p>
            </td>
            <td class="space-left">
                <h6>积分商城</h6>
                <ul class="uploadImg">
                    <li id="imgConfig3">
                        <img class="js_form" src="<?php echo $staticPath;?>/img/content/nopic.jpg" />
                        <input type="hidden" name="img_config_mall" value="" />
                    </li>
                </ul>
                <p style="clear:both;">
                    <iframe name="upload" src="<?php echo $uploadUrl."/?imgId=imgConfig3";?>" style="height:80px;width:100%;" frameborder="0" scrolling="no"></iframe>
                </p>
            </td>
            <td class="space-left">
                <h6>积分抽奖</h6>
                <ul class="uploadImg">
                    <li id="imgConfig4">
                        <img class="js_form" src="<?php echo $staticPath;?>/img/content/nopic.jpg" />
                        <input type="hidden" name="img_config_prize" value="" />
                    </li>
                </ul>
                <p style="clear:both;">
                    <iframe name="upload" src="<?php echo $uploadUrl."/?imgId=imgConfig4";?>" style="height:80px;width:100%;" frameborder="0" scrolling="no"></iframe>
                </p>
            </td>
            <td class="space-left">
                <h6>分享</h6>
                <ul class="uploadImg">
                    <li id="imgConfig5">
                        <img class="js_form" src="<?php echo $staticPath;?>/img/content/nopic.jpg" />
                        <input type="hidden" name="img_config_share" value="" />
                    </li>
                </ul>
                <p style="clear:both;">
                    <iframe name="upload" src="<?php echo $uploadUrl."/?imgId=imgConfig5";?>" style="height:80px;width:100%;" frameborder="0" scrolling="no"></iframe>
                </p>
            </td>
        </tr>
        <tr>
            <td  class="space-left">
                道具设置
            </td>
            <td class="space-left" name="news-prize" colspan="6">
                <div class="add-news-prize">
                    <input name="add" type="button" class="but-yellow but-blue" value="添加新道具" />
                </div>
            </td>
        </tr>
        <tr>
            <td class="space-left">
                活动阈值
            </td>
            <td class="space-left" colspan="6">
                <div style="padding-bottom:10px">
                    <input type="text" name="waring_score" />  超过此分数，自动无效，不计入排行榜
                </div>
                <div>
                    <input type="text" name="waring_point" />  每人每天可获得积分数量
                </div>
            </td>
        </tr>
        <tr class="tr">
            <td class="space-left">
                状态
            </td>
            <td class="space-left" colspan="6">
                <select name="status">
                    <option value="1">开启</option>
                    <option value="0">关闭</option>
                </select>
            </td>
        </tr>
    </table>
    <div class="ok">
        <input value="完成" id="submit" type="button" class="but-yellow" />
    </div>
</div>

<div id="alert">
    <p name="msg"></p>
</div>
<div id="progressbar">
    <div id="loadIng" style="margin-top:20px">
        <div class="progress-label"></div>
    </div>
</div>

<script src="<?php echo $staticPath;?>/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script type="text/javascript">
    var imgPath = "<?php echo $attachPath; ?>";
    $(document).ready(function() {
        $('#preheat_time').datetimepicker();
        $('#start_time').datetimepicker();
        $('#end_time').datetimepicker();
        $('#game_start_time').datetimepicker();
        $('#game_end_time').datetimepicker();
    });

    var holidayTaskData = {}
        ,ajaxUrl = '<?php echo $addPostUrl;?>'
        ,backUrl = '<?php echo $indexUrl;?>'
        ,token = '<?php echo $token;?>'
        ;
    var editor;
    KindEditor.ready(function(K) {
        K.token = '<?php echo $token;?>';
        editor = K.create('textarea[name="descript"]', {
            resizeType : 1,
            allowPreviewEmoticons : false,
            allowImageUpload : true,
            uploadJson : '<?php echo $uploadImgUrl;?>',
            items : EDITOR_ITEMS
        });
    });
</script>
<?php echo $this->render("layout/footer.phtml");?>
