<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class=""><a href="<?php echo $channelUrl; ?>">渠道号管理</a></li>
			<li class="current"><a href="<?php echo $hotwordsUrl; ?>">首页热词模块</a></li>
		</ul>

	</div>
	<div class="h_a">规则说明：</div>
	<form method="post" action="/Admin/config/hotwords" id="addFrom">
		<input name="token" id="token" value="<?php echo $token; ?>" type="hidden"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">文字内容</th>
					<td class="td">
						<textarea rows="6" cols="10" name="3g_hotwords_tpl" style="width: 600px; height:400px;"><?php echo $data; ?></textarea>
					</td>
				</tr>

			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
	</form>

	<script type="text/javascript">
		//广告表单数据提交
		$(document).ready(function () {
			ajaxForm('addFrom', function (ret) {
				ajaxRedirect(ret, baseurl + '/Admin/config/hotwords');
			},
		})
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>