<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	<?php foreach($at_ptypes as $key=>$value)  {?>
        <li><a href="<?php echo $listUrl.'?sid='.$key;?>"><?php echo $value;?></a></li>
	<?php } ?>
	<li class="current" ><a href="javascript;">编辑属性</a></li>
	</ul>
</div>

<form method="post" action="<?php echo $editPostUrl;?>" id="editFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<input name="sid" value="<?php echo $sid;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">类型</th>
			<td class="td">
			   <select name="at_type" onchange='showtd()'>
			   <?php foreach($at_ptypes as $key=>$value) { ?>
			   <option <?php if($info['at_type'] == $key)  echo 'selected';?> value="<?php echo $key;?>"><?php echo $value;?></option>
			   <?php }?>
			</select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title'];?>"></td>
		</tr>
		<tr class="tr"  style="display:none;" id="tdstatus">
			<th class="th">状态</th>
			<td class="td">
				<select name="status">
                	<option <?php if($info['status'] == 1) echo 'selected';?> value="1">开启</option>
                	<option <?php if($info['status'] == 0) echo 'selected';?> value="0">关闭</option>
            	</select>
            </td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
function showtd(){
	var value=$("select[name=at_type]").val();
	if(value == 1) {
		$('#tdstatus').show();
	} else {
		$('#tdstatus').hide();
	}
}
$(document).ready(function(){
	ajaxForm('editFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Resource_Attribute/index?sid=<?php echo $sid;?>');
	});
	showtd();
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
