<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">国家列表</a></li>
    <li class="current"><a href="javascript:;">编辑国家</a></li>
	</ul>
</div>
<div class="h_a">编辑国家</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">标题</th>
				<td class="td"><input type="text" class="input wc" name="name" value="<?php echo $info['name'];?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">币种代码</th>
				<td class="td"><input type="text" class="input wc" name="currency" value="<?php echo $info['currency'];?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">语言代码</th>
				<td class="td"><input type="text" class="input wc" name="lang_code" value="<?php echo $info['lang_code'];?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">图片</th>
				<td class="td">
					<ul class="uploadImg">
						<li id="AdImg">
							<img src="<?php echo $attachPath.$info['logo'];?>"/>
							<input type="hidden" name="logo" value="<?php echo $info['logo'];?>">
						</li>
					</ul>
					<p style="clear:both;">
						  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
					</p>
				</td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//国家表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Country/index?s=1');
	});
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
