<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">手机号列表</a></li>
    <li class="current"><a href="javascript:;">编辑状态</a></li>
	</ul>
</div>
<div class="h_a">编辑状态</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="editFrom">
    <input name="id" value="<?php echo $info['id'];?>" type="hidden"/>
    <input name="token" value="<?php echo $token;?>" type="hidden" />
	<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">手机号</th>
			<td class="td"><?php echo $info['qq'];?></td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td"><select name="status" min-width="100px">
                	<option <?php if($info['status'] == 2) echo 'selected="selected"';?> value="2">已发奖</option>
                	<option <?php if($info['status'] == 1) echo 'selected="selected"';?> value="1">未发奖</option>
            </select></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">保存</button></span></span></div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('editFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Activity_ShareQq/index');
	});
})

</script>
<?php echo $this->render("layout/footer.phtml");?>
