<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<title>2014年度盛典-最佳游戏续作</title>
<link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/events/2014top/css/style.min.css?v=<?php echo $version;?>" />
</head>
<body>
	<div class="ui-pg-top">
		<div class="banner">
			<img src="<?php echo $staticroot; ?>/apps/game/events/2014top/img/02_01.jpg" alt="">
		</div>
		<div class="video-wrap">
			<h3>精彩视频</h3>
			<a class="video-box" href="http://v.youku.com/v_show/id_XODgxOTA4NzQ0.html"></a>	
		</div>
		<div class="block">
			<p class="app-img">
				<img src="<?php echo $staticroot; ?>/apps/game/events/2014top/img/02_02.jpg" alt="">
			</p>
			<p class="app-txt">捕鱼系列此前作品运用的是2D技术，但此次却升级为3D立体画面，画风也继承了捕鱼系列的国际化，变成欢快热闹的3D卡通范。捕鱼达人3在画面，操控各方面都有质的飞跃，也收获了游戏大厅玩家的好评如潮。最佳续作，实至名归。</p>
		</div>
		<div class="ui-buttons">
			<a class="ui-btn-download" href="http://gamedl.gionee.com/Attachments/dev/apks/2014/12/23/1419316068930.apk">立即下载</a>
		</div>
	</div>
</body>
</html>