<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li><a href="<?php echo $listUrl . '?type=' . $info['type']; ?>">数据列表</a></li>
			<li class="current"><a href="javascript:;">编辑数据</a></li>
		</ul>
	</div>
	<div class="h_a">编辑搜索</div>
	<form method="post" action="<?php echo $editPostUrl; ?>" id="addFrom">
		<input name="token" value="<?php echo $token; ?>" type="hidden"/>
		<input name="id" value="<?php echo $info['id']; ?>" type="hidden"/>
		<input name="type" value="<?php echo $info['type']; ?>" type="hidden"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">名称</th>
					<td class="td"><input type="text" class="input" name="name" value="<?php echo $info['name']; ?>">
					</td>
				</tr>
				<tr class="tr">
					<th class="th">地址</th>
					<td class="td"><input type="text" class="input wc" name="url" value="<?php echo $info['url']; ?>">
					</td>
				</tr>
				<?php if (in_array($info['type'], array(2, 3))): ?>
					<tr class="tr">
						<th class="th">展示地址</th>
						<td class="td"><input type="text" class="input wc" name="show_url"
						                      value="<?php echo $info['show_url']; ?>"></td>
					</tr>
				<?php endif; ?>
				<tr class="tr">
					<th class="th">图标</th>
					<td class="td">
						<ul class="uploadImg">
							<li id="AppImg">
								<img src="<?php echo $attachPath . $info['icon']; ?>"/>
								<input type="hidden" name="icon" value="<?php echo $info['icon']; ?>">
							</li>
						</ul>
						<p style="clear:both;">
							<iframe name="upload" src="<?php echo $uploadUrl . '/?imgId=AppImg'; ?>"
							        style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
						</p>
					</td>
				</tr>
				<tr class="tr">
					<th class="th">app</th>
					<td class="td">
						<?php
						foreach (Gionee_Service_Browserurl::$app as $key => $val):
							$checked = '';
							if ($key & $info['app']) {
								$checked = 'checked="checked"';
							}
							?>
							<input id="app<?php echo $key; ?>" type="checkbox" class="input" name="filter_app[]" <?php echo $checked; ?> value="<?php echo $key; ?>">
							<label for="app<?php echo $key; ?>"><?php echo $val; ?></label>
						<?php endforeach; ?>
					</td>
				</tr>
				<!--
				<tr class="tr">
					<th class="th">排序</th>
					<td class="td"><input type="text" class="input" name="sort" value="<?php echo $info['sort']; ?>">（填写一个数字，数字越小越靠前）
					</td>
				</tr>
				-->
			</table>
		</div>


		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
	</form>
	<script type="text/javascript">
		//表单数据提交
		$(document).ready(function () {
			ajaxForm('addFrom', function (ret) {
				ajaxRedirect(ret, baseurl + '/Admin/Browserurl/index?type=<?php echo $info['type'];?>');
			});
		})
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>