<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class="current">
				<a href="<?php echo $listUrl . '?type=' . $type; ?>">数据列表</a>
			</li>
			<?php foreach (Gionee_Service_Browserurl::$app as $k => $v): ?>
				<li><a href="<?php echo $listUrl . '?type=' . $type . '&app=' . $k; ?>"><?php echo $v; ?></a></li>
			<?php endforeach; ?>
			<li><a href="<?php echo $editUrl . '?type=' . $type; ?>">添加数据</a></li>

            <a href="/Admin/browserurl/export?type=<?=$type?>" class="easyui-linkbutton" iconCls="icon-add" plain="true">导出</a>
            <a href="/Admin/browserurl/import?type=<?=$type?>" class="easyui-linkbutton" iconCls="icon-add" plain="true">导入</a>

		</ul>
	</div>

	<div class="table_list">
		<table width="100%">
			<tr class="hd">
				<td width="50">ID</td>
				<td width="100">名称</td>
				<td width="80">图标</td>
				<td width="200">地址</td>
				<td width="50">状态</td>
				<td width="100">App</td>
				<td width="100">操作</td>
			</tr>
			<?php foreach ($list as $key => $value) { ?>
				<tr class="ct">
					<td><?php echo $value['id']; ?></td>
					<td><?php echo $value['name']; ?></td>
					<td><img src="<?php echo $value['icon'] ? $attachPath . $value['icon'] : ''; ?>" width="30"/></td>
					<td><?php
						echo $value['url'] . "<br>";
						if (in_array($value['type'], array(2, 3))) {
							echo $value['show_url'];
						}
						?></td>

					<td><?php echo $value['operation'] ? '删除' : '更新'; ?></td>
					<td>
						<?php
						$tmp = array();
						foreach (Gionee_Service_Browserurl::$app as $key => $val) {
							if ($key & $value['app']) {
								$tmp[] = $val;
							}
						}
						echo implode(',', $tmp);
						?>
					</td>
					<td>
						<a href="<?php echo $editUrl; ?>/?id=<?php echo $value['id']; ?>" class="mr10">编辑</a>
						<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
					</td>
				</tr>
			<?php } ?>
		</table>
	</div>
	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>
<?php echo $this->render("layout/footer.phtml"); ?>