<?php echo $this->render("layout/admin_header.phtml");?>
	<div class="body">
	    <h1 class="page-title" >添加礼包</h1>
		<?php echo $this->render("layout/side.phtml");?>
		<div class="col-main">
			<div class="J_gift_error_tips error-pop-tips hidden">
			</div>
			<div class="gift-body">
				<div class="gift-edit-container">
					<div class="gift-column-container">
						<span class="text">礼包名称<em class="asterisk">*</em>:</span>
						<input id="giftName1" class="input" />
						<!-- <span class="J_tips_ok tips-ok">√</span> -->
					</div>
					<div class="gift-column-container">
						<span class="text">礼包类型<em class="asterisk">*</em>:</span>
						<select id="codeType" class="select" >
							<option selected value="2">多个</option>
							<option value="1">1个</option>
						</select>
					</div>
					<div class="gift-column-container">
						<span class="text">礼包信息<em class="asterisk">*</em>:</span>
						<div class="editorContainer">
							<!--style给定宽度可以影响编辑器的最终宽度-->
						<script type="text/plain" id="myEditor" style="width:500px;height:400px;"></script>
						</div>
					</div>
					<div class="gift-column-container">
						<span class="text">激活码<em class="asterisk">*</em>:</span>
						<div class="code-container" id="codeUploadDiv" >
							<span class="text dark">(请上传txt文档，每行一个礼包)</span>
							<a href="javascript:;" class="btn-upload">
								<input id="giftFile" type="file" name="file" >添加激活码
							</a>
							<a id="startUploadCode" data-ajaxUrl="<?php echo $fileUploadUrl?>"  href="javascript:;" class="btn-upload">开始上传</a>
							<!-- <span class="J_tips_ok tips-ok">√</span> -->
							<span id="giftCodeName" class="text dark hidden "></span>
						</div>
						<div class="code-container" id="giftCodeDiv" style="display: none;">
							<input id="giftCode" class="input" />
						</div>
					</div>
					<div class="gift-column-container">
						<span class="text">兑换有效期<em class="asterisk">*</em>:</span>
						<input type="text" id="exStartDate" class="J_datePicker J_readonly input">
						<label class="sep-text">到</label>
						<input type="text" id="exEndDate" class="J_datePicker J_readonly input">
						<!-- <span class="J_tips_ok tips-ok">√</span> -->
					</div>
					<div class="gift-column-container">
						<span class="text">中奖概率<em class="asterisk">*</em>:</span>
						<div class="rate-container">
							<input id="giftRate" class="input" />
							<!-- <span class="J_tips_ok tips-ok">√</span> -->
							<span class="text dark">(请填写0-1之间的数字,  最多四位小数)</span>
						</div>
					</div>
					<div class="gift-column-container">
						<span class="text">是否有效<em class="asterisk">*</em>:</span>
						<select id="selectStatus" class="select">
							<option value="1">有效</option>
							<option value="0">无效</option>
						</select>
					</div>
					<div class="J_giftEventDate gift-column-container">
						<span class="text">活动有效期<em class="asterisk">*</em>:</span>
						<input type="text" id="eventStartDate" class="J_datePicker J_readonly input">
						<label class="sep-text">到</label>
						<input type="text" id="eventEndDate" class="J_datePicker J_readonly input">
					</div>
				</div>
				<div class="btn-container">
					<button id="giftPreview" class="btn">预览</button>
					<button id="giftSave" class="btn" data-ajaxUrl="<?php echo $addEditPortUrl?>" >保存</button>
					<a href="<?php echo $listUrl?>" class="btn">取消</a><!-- 回到上一页 -->
				</div>
			</div>
		</div>
	</div>
	<?php echo $this->render("layout/footer.phtml");?>
	<?php echo $this->render("layout/datePicker.phtml");?>
	<?php echo $this->render("layout/ueditor.phtml");?>
	<div class="J_dialog mask hidden">
		<div class="gift-preview-container">
			<div class="gift-header-wrapper">
				<i id="closePreviewDialog" class="icon-close">X</i>
				<span >热门礼包</span>
			</div>
			<div class="gift-banner-wrapper">
				<h1>礼包刮刮乐</h1>
				<div class="scratch-container">
				</div>
			</div>
			<div class="info-container">
				<div class="gift-info">
					<h3>礼包名称：</h3>
					<div id="preview-giftName"></div>
					<h3>兑换时间：</h3>
					<div id="preview-giftExTime"></div>
					<h3>礼包信息：</h3>
					<div id="preview-gift" class="ui-editor"></div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>