<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>微信管理系统</title>
	<?php echo $this->render("layout/header.phtml");?>
</head>
<body>
	<div class="gift-body iframe-Dialog">
		<div class="search-bar">
			<form action="<?php echo $dialogUrl;?>" method="get">
				<label>状态：</label>
				<select name="status" class="select">
					<option  value="0">全部</option>
					<option <?php if($inputVars['status'] == 1) echo 'selected';?> value="1">有效</option>
					<option <?php if($inputVars['status'] == 2) echo 'selected';?> value="2">无效</option>
				</select>
				<br/>
				<label>名称：</label><input class="input" name="keyword" value="<?php echo $inputVars['keyword']?>"/>
				<button type="submit" class="btn">查询</button>
			</form>
		</div>
		<table class="J_table table">
			<thead>
				<tr>
					<th>选择</th>
					<th>ID</th>
					<th>礼包名称</th>
					<th>状态</th>
					<th>活动时间</th>
					<th>兑换时间</th>
					<th>类型</th>
					<th>礼包数量(剩余/总)</th>
				</tr>
			</thead>
			<tbody>
<?php 
$format = 'Y/m/d H:i:s';
foreach ($list as $giftBag){
?>
				<tr>
					<td><input type="radio" name="giftRadio" data-url="<?php echo $giftBag['url']?>" data-id="<?php echo $giftBag['id'];?>" /></td>
					<td><?php echo $giftBag['id'];?></td>
					<td><?php echo $giftBag['title'];?></td>
					<td><?php echo $giftBag['status'] == 1 ? '有效' : '无效';?></td>
					<td>
						<div><?php echo date($format, $giftBag['activity_start_time']);?></div>
						<div><?php echo date($format, $giftBag['activity_end_time']);?></div>
					</td>
					<td>
						<div><?php echo date($format, $giftBag['exchange_start_time']);?></div>
						<div><?php echo date($format, $giftBag['exchange_end_time']);?></div>
					</td>
					<td><?php echo $giftBag['code_type'] == Admin_Service_Gift::CODE_TYPE_MULTI ? '多个' : '1个';?></td>
					<td><span><?php echo $giftBag['residue'];?></span> / <span><?php echo $giftBag['total'];?></span></td>
				</tr>
<?php }?>
			</tbody>
		</table>
		<?php echo $pager;?>
	</div>
	
</body>
</html>