<?php echo $this->render("layout/header.phtml");?>
<body module-id="loginRegister">
<div class="module gradient-background">
    <div class="login-wrap">
        <div class="login-logo"></div>
        <div class="login-content">
            <h1>Ola Job</h1>
            <form id="J_loginForm">
                <ul class="login-inner">
                    <li>
                        <label><i class="icon-phone"></i></label>
                        <div class="input-wrap">
                            <input id="J_phone" class="phone" name="phone" type="tel" placeholder="请输入手机号码"
                                require data-verify="\d{11}" data-msg="{'require':'请输入手机号码', 'verify':'请输入正确的手机号'}">
                        </div>
                    </li>
                    <li>
                        <label><i class="icon-password"></i></label>
                        <div class="input-wrap">
                            <input id="J_password" class="password" name="password" type="password" placeholder="请输入密码"
                                require data-msg="{'require':'请输入密码'}">
                        </div>
                    </li>
                </ul>
                <div class="btn btn-login-submit" id="J_login" data-ajax="<?php echo $webroot?>/api/user/login_post">登录</div>
                <div class="login-footer">
                    <!-- <a href="">忘记密码?</a> -->
                </div>
            </form>
        </div>
        <div class="registe-wrap">
            <a href="<?php echo $webroot,$registerUrl;?>" class="btn btn-registe">注册</a>
        </div>
    </div>
</div>
<?php echo $this->render("layout/footer.phtml");?>