<?php echo $this->render("layout/header.phtml");?>
    <body module-id="publishJobs">
    <div class="module">
        <form class="layout-center user-edit-form">
            <ul class="form-list" data-attr-url="<?php echo $webroot?>/api/job/attr">
                <li>
                    <label><em>*</em>兼职名称：</label>
                    <div class="input-wrap">
                        <input name="title" type="text" placeholder="请输入2-20个英文字符"
                            require data-verify="^[a-zA-Z\u4e00-\u9fa5]{2,20}$"
                            data-msg="{'require':'请输入2-20个英文字符', 'verify':'兼职名称请输入2-20个中英文字符'}"/>
                    </div>
                </li>
                <li class="J_listSelect" data-title="请选择兼职分类" data-type="category">
                    <label><em>*</em>兼职分类：</label>
                    <div class="flex" >
                        <span class="holder">请选择兼职分类</span>
                        <input type="hidden" value="" name="category_id" 
                            require data-msg="{'require':'请选择兼职分类'}"/>
                    </div>
                    <div class="side"><i class="icon-put-right"></i></div>
                </li>
                <li>
                    <label><em>*</em>薪资待遇：</label>
                    <div class="input-wrap">
                        <input class="pay" type="number" name="money" placeholder="请输入金额"
                            require data-verify="^\d+(\.\d+)?$" data-msg="{'require':'请输入金额', 'verify':'金额必须为数字'}"/>
                    </div>
                    <div class="unit J_listSelect" data-type="moneyType" data-title="请选择单位">
                        <em>*</em>单位：<span class="holder"></span>
                        <input type="hidden" value="" name="money_type" 
                            require data-msg="{'require':'请选择单位'}"/>
                        <div class="side"><i class="icon-put-right"></i></div>
                    </div>
                </li>
                <li class="J_listSelect" data-type="checkType" data-title="请选择结算方式">
                    <label><em>*</em>结算方式：</label>
                    <div class="flex">
                        <span class="holder">请选择结算方式</span>
                        <input type="hidden" value="" name="check_type" 
                            require data-msg="{'require':'请选择结算方式'}"/>
                    </div>
                    <div class="side"><i class="icon-put-right"></i></div>
                </li>
                <li class="J_listSelect" data-type="sex" data-title="请选择性别">
                    <label><em>*</em>性别限制：</label>
                    <div class="flex">
                        <span class="holder">男女不限</span>
                        <input type="hidden" value="3" name="sex" 
                            require data-msg="{'require':'请选择性别'}"/>
                    </div>
                    <div class="side"><i class="icon-put-right"></i></div>
                </li>
                <li class="J_listSelect" data-type="area" data-title="请选择工作区域">
                    <label><em>*</em>工作区域：</label>
                    <div class="flex">
                        <span class="holder">请选择工作区域</span>
                        <input type="hidden" value="" name="area_id" 
                            require data-msg="{'require':'请选择工作区域'}"/>
                    </div>
                    <div class="side"><i class="icon-put-right"></i></div>
                </li>
                <li>
                    <label>&ensp;具体地址：</label>
                    <div class="input-wrap">
                        <input type="text" name="address" placeholder="请填写具体地址"/>
                    </div>
                </li>
                <li class="J_listSelect" data-type="jobType" data-title="请选择职位来源">
                    <label><em>*</em>职位来源：</label>
                    <div class="flex">
                        <span class="holder">请选择职位来源</span>
                        <input type="hidden" value="" name="job_type" 
                            require data-msg="{'require':'请选择职位来源'}"/>
                    </div>
                    <div class="side"><i class="icon-put-right"></i></div>
                </li>
                <li style="display:none" id="J_company">
                    <label><em>*</em>公司名称：</label>
                    <div class="input-wrap"></div>
                </li>
                <li>
                    <label><em>*</em>负&ensp;责&ensp;人：</label>
                    <div class="input-wrap">
                        <input type="text" name="author" placeholder="请填写负责人姓名"
                            require data-msg="{'require':'请填写负责人姓名'}"/>
                    </div>
                </li>
                <li>
                    <label><em>*</em>联系方式：</label>
                    <div class="input-wrap">
                        <input type="tel" name="phone" placeholder="请填写联系方式"
                            require data-verify="^\d{11}|\d+(-\d+)*$" data-msg="{'require':'请填写联系方式', 'verify':'联系方式格式不正确'}"/>
                    </div>
                </li>
            </ul>
            <div class="textarea-wrap">
                <div class="title"><em>*</em>职位描述：</div>
                <textarea maxlength="500" name="description" placeholder="请填写职位详情信息（工作时间、工作内容等）"
                    require data-msg="{'require':'请填写职位详情信息（工作时间、工作内容等）'}"></textarea>
            </div>
            <div class="btn-wrap">
                <div class="btn btn-login-submit" id="J_publish" data-ajax="<?php echo $webroot?>/api/job/publish">发布</div>
            </div>
        </form>
    </div>

    <div class="modal J_modal" id="J_templateModal" style="display:none;"></div>

    <script type="text/template" id="J_listTemplate">
        <div class="simple-list">
            <div class="box-wrap">
                <dl><dt><%=title%></dt></dl>
                <dl>
                    <%if(data instanceof Array){%>
                        <%for(var i=0, len=data.length; i<len; i++){%>
                            <dd class="J_select" data-id="<%=data[i].id%>" data-name="<%=data[i].title || data[i].name%>">
                                <p><%=data[i].title || data[i].name%></p>
                                <%if(val == data[i].id){%>
                                <i class="icon-selected"></i>
                                <%}%>
                            </dd>
                        <%}%>
                    <%} else {%>
                        <%for(var id in data){%>
                            <dd class="J_select" data-id="<%=id%>" data-name="<%=data[id]%>">
                                <p><%=data[id]%></p>
                                <%if(val == id){%>
                                <i class="icon-selected"></i>
                                <%}%>
                            </dd>
                        <%}%>
                    <%}%>
                </dl>
            </div>
        </div>
    </script>

<?php echo $this->render("layout/footer.phtml");?>