<?php echo $this->render("layout/header.phtml");?>
<body module-id="loginRegister">
<div class="module gradient-background">
    <div class="login-wrap">
        <div class="login-logo"></div>
        <div class="login-content">
            <h1>Ola Job</h1>
            <form id="J_registerForm">
                <ul class="login-inner">
                    <li>
                        <label><i class="icon-phone"></i></label>
                        <div class="input-wrap">
                            <input id="J_phone" class="phone" name="phone" type="tel" placeholder="请输入手机号码" require data-verify="^\d{11}$" data-msg="{'require':'请输入手机号码', 'verify':'请输入正确的手机号'}">
                        </div>
                    </li>
                    <li>
                        <label><i class="icon-message"></i></label>
                        <div class="input-wrap">
                            <input id="J_code" class="code" name="code" type="number" placeholder="请输入验证码" require data-verify="^\d{4}$" data-msg="{'require':'请输入验证码', 'verify':'验证码为4位数字'}">
                            <span class="get-code" id="J_getCode" data-ajax="<?php echo $webroot?>/api/user/sms_post">获取验证码</span>
                        </div>
                    </li>
                    <li>
                        <label><i class="icon-password"></i></label>
                        <div class="input-wrap">
                            <input id="J_password" class="password" name="password" type="password" placeholder="请设置6-16个字符的密码" require data-msg="{'require':'请设置6-16个字符的密码'}">
                        </div>
                    </li>
                </ul>
                <div class="btn btn-login-submit" id="J_register" data-ajax="<?php echo $webroot?>/api/user/register_post">提交</div>
                <div class="login-footer"></div>
            </form>
        </div>
    </div>
</div>

<?php echo $this->render("layout/footer.phtml");?>