

	<div class="fixed_head">
		<div id="top_down"></div>
		<div class="header_home"><a href="/?f=inner" class="ico_logo">高清影视</a> <span class="top_icons"> <a
					href="javascript:;" w="topicons" stat="15424" class="ico_user" style="display: none;">我的</a> <a
					href="javascript:;" w="topicons" stat="15425" class="ico_his" style="display: none;">历史</a> <a
					href="/search.php" w="topicons" stat="15426" class="ico_search_home">搜索</a> </span> <span
				class="update_tip" style="display: none;"></span></div>
		<div id="nav" class="scroll_wrap"
		     style="backface-visibility: hidden; -webkit-backface-visibility: hidden; overflow-x: hidden; transform: translate3d(0px, 0px, 0px); -webkit-transform: translate3d(0px, 0px, 0px);">
			<div class="scroller"
			     style="backface-visibility: hidden; -webkit-backface-visibility: hidden; transform: translate3d(0px, 0px, 0px); -webkit-transform: translate3d(0px, 0px, 0px); transition-property: -webkit-transform; -webkit-transition-property: -webkit-transform; transition-duration: 0s; -webkit-transition-duration: 0s;">
				<a stat="15414" w="nav" href="category.php?cat_id=1&amp;title=电影&amp;type=recommend">电影</a><a
					stat="15415" w="nav" href="category.php?cat_id=2&amp;title=电视剧&amp;type=recommend">电视剧</a><a
					stat="15416" w="nav" href="category.php?cat_id=4&amp;title=综艺">综艺</a><a stat="15417" w="nav"
				                                                                            href="category.php?cat_id=3&amp;title=动漫">动漫</a><a
					stat="18926" w="nav" href="/news/">资讯</a><a stat="" w="nav" href="/ent/">娱乐</a><a stat="15418"
				                                                                                      w="nav"
				                                                                                      href="rank.php">榜单</a>
			</div>
		</div>
	</div>
	<!-- 首页 -->
	<div id="main"> <!-- 加载模块 -->
		<div class="banner_wrap">
			<ul class="slide_main" id="slider"
			    style="width: 3840px; height: 140px; -webkit-transform: translate3d(-2880px, 0px, 0px); -webkit-transition-duration: 0.6s; transition-duration: 0.6s;">
				<li style="width: 320px; height: 140px;"><a
						href="http://v.m.liebao.cn/detail.php?tsid=272823&amp;title=花千骨" stat="66324" w="banner"
						title="花千骨" stat-new="66324" w-new="485"> <img
							src="http://dh2.kimg.cn/kimg/v/m/upload/20150611/1300df13d2e1ac442c6fa0aaee2fe2c9.jpg_640x280.jpg?q=60"
							class="">

						<div class="text_info">【花千骨】霍建华赵丽颖高颜值仙魔极致虐恋</div>
					</a></li>
				<li style="width: 320px; height: 140px;"><a
						href="http://v.m.liebao.cn/detail.php?tsid=273231&amp;title=疯狂的麦克斯4：狂暴之路" stat="70415"
						w="banner" title="疯狂的麦克斯4：狂暴之路" stat-new="70415" w-new="485"> <img
							src="http://dh2.kimg.cn/kimg/v/m/upload/20150402/995f17a69615cc12417052ba2215032f.jpg_640x280.jpg?q=60">
						<i class="tip_purple" style="background:#FF0000">新</i>

						<div class="text_info">【疯狂麦克斯4】噩梦般特效 邪恶重口猛烈来袭</div>
					</a></li>
				<li style="width: 320px; height: 140px;"><a
						href="http://v.m.liebao.cn/detail.php?tsid=272993&amp;title=极限挑战" stat="70403" w="banner"
						title="极限挑战" stat-new="70403" w-new="485"> <img
							src="http://dh2.kimg.cn/kimg/v/m/upload/20150622/08de1f339da0ad4446cc7c52d9c8b03e.jpg_640x280.jpg?q=60"
							class="">

						<div class="text_info">【极限挑战】黄渤遇美女送饭 张艺兴飙泪</div>
					</a></li>
				<li style="width: 320px; height: 140px;"><a
						href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1434623692.html" stat="70307" w="banner"
						title="仙侠女神" stat-new="70307" w-new="485"> <img
							src="http://dh2.kimg.cn/kimg/v/m/upload/20150619/ad0027fb7640013fa3e4ebedad4c914e.jpg_640x280.jpg?q=60"
							class=""> <i class="tip_purple" style="background:#FF0066">专题</i>

						<div class="text_info">【仙侠女神】那些年痴迷过的仙侠女神</div>
					</a></li>
				<li style="width: 320px; height: 140px;"><a
						href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1434526371.html" stat="70372" w="banner"
						title="父亲节喜当爹" stat-new="70372" w-new="485"> <img
							src="http://dh2.kimg.cn/kimg/v/m/upload/20150621/401a9d0e98bb373645a0428cd89dd533.jpg_640x280.jpg?q=60"
							class=""> <i class="tip_purple" style="background:#FF0066">专题</i>

						<div class="text_info">【父亲节】扒扒明星喜当爹 主动式被动式</div>
					</a></li>
				<li style="width: 320px; height: 140px;"><a
						href="http://v.m.liebao.cn/detail.php?tsid=271886&amp;title=奔跑吧兄弟 第2季" stat="70333" w="banner"
						title="奔跑吧兄弟 第2季" stat-new="70333" w-new="485"> <img
							src="http://dh2.kimg.cn/kimg/v/m/upload/20150620/a359de2bd5b2293cc318f17fd32a3e59.jpg_640x280.jpg?q=60"
							class="">

						<div class="text_info">【奔跑吧兄弟2】钟汉良井柏然长城开撕</div>
					</a></li>
				<li style="width: 320px; height: 140px;"><a
						href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1434679842.html" stat="70325" w="banner"
						title="周末影院 欲望" stat-new="70325" w-new="485"> <img
							src="http://dh2.kimg.cn/kimg/v/m/upload/20150619/4e655ba22eb0b80570c98b8393a9486e.jpg_640x280.jpg?q=60"
							class=""> <i class="tip_purple" style="background:#FF0066">专题</i>

						<div class="text_info">【周末影院】在堕落中高潮，欲望在骚动</div>
					</a></li>
				<li style="width: 320px; height: 140px;"><a
						href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1434698605.html" stat="70323" w="banner"
						title="一周最热短视频" stat-new="70323" w-new="485"> <img
							src="http://dh2.kimg.cn/kimg/v/m/upload/20150619/7a492d4d213edfc49720fb4657277c37.jpg_640x280.jpg?q=60"
							class=""> <i class="tip_purple" style="background:#FF0066">专题</i>

						<div class="text_info">【一周最热】英国裸骑日+18岁钢管女神</div>
					</a></li>
				<li style="width: 320px; height: 140px;"><a
						href="http://v.m.liebao.cn/detail.php?tsid=272930&amp;title=盗墓笔记" stat="66488" w="banner"
						title="盗墓笔记" stat-new="66488" w-new="485"> <img
							src="http://dh2.kimg.cn/kimg/v/m/upload/20150612/84463b46b3aeef2d69a567d95167ddb0.jpg_640x280.jpg?q=60"
							class="">

						<div class="text_info">【盗墓笔记】跟着大侄子去护宝</div>
					</a></li>
				<li style="width: 320px; height: 140px;"><a
						href="http://v.m.liebao.cn/detail.php?tsid=273073&amp;title=偏偏喜欢你" stat="70105" w="banner"
						title="偏偏喜欢你" stat-new="70105" w-new="485"> <img
							src="http://dh2.kimg.cn/kimg/v/m/upload/20150616/3fdbae1459cfe9af3e382b05f8671b14.jpg_640x280.jpg?q=60"
							class="">

						<div class="text_info">【偏偏喜欢你】陈乔恩变身军校麻辣女教官</div>
					</a></li>
				<li style="width: 320px; height: 140px;"><a
						href="http://v.m.liebao.cn/detail.php?tsid=272823&amp;title=花千骨" stat="66324" w="banner"
						title="花千骨" stat-new="66324" w-new="485"> <img
							src="http://dh2.kimg.cn/kimg/v/m/upload/20150611/1300df13d2e1ac442c6fa0aaee2fe2c9.jpg_640x280.jpg?q=60"
							class="">

						<div class="text_info">【花千骨】霍建华赵丽颖高颜值仙魔极致虐恋</div>
					</a></li>
				<li style="width: 320px; height: 140px;"><a
						href="http://v.m.liebao.cn/detail.php?tsid=273231&amp;title=疯狂的麦克斯4：狂暴之路" stat="70415"
						w="banner" title="疯狂的麦克斯4：狂暴之路" stat-new="70415" w-new="485"> <img
							src="http://dh2.kimg.cn/kimg/v/m/upload/20150402/995f17a69615cc12417052ba2215032f.jpg_640x280.jpg?q=60">
						<i class="tip_purple" style="background:#FF0000">新</i>

						<div class="text_info">【疯狂麦克斯4】噩梦般特效 邪恶重口猛烈来袭</div>
					</a></li>
			</ul>
			<div class="slide_tab"><i class=""></i><i class=""></i><i class=""></i><i class=""></i><i class=""></i><i
					class=""></i><i class=""></i><i class=" "></i><i class=" cur"></i><i class=""></i></div>
		</div>
		<div class="list_wrap"><h3 class="h_title list_hot"><a href="http://v.m.liebao.cn/news/" class="h_t" stat=""
		                                                       w="tv" stat-new="more" w-new="3470"> 今日热门 </a> <a
					href="http://v.m.liebao.cn/news/play/18602.html" style="color:" class="rec" stat="70420" w="tv"
					stat-new="70420" w-new="3470"> 实拍美女口吞三毒蛇 </a> <a href="http://v.m.liebao.cn/news/" class="link_more"
		                                                             stat="" w="tv" stat-new="more" w-new="3470"> <i
						class="more"></i> </a></h3>
			<ul class="list list_2col">
				<li><a class="list_cont" href="http://v.m.liebao.cn/news/play/18733.html" stat="70461" w="tv"
				       stat-new="70461" w-new="3470" title="3女子被强行注射不明液体">
						<div class="pic_info">
							<div class="img"
							     style="background-image: url(http://dh2.kimg.cn/kimg/v/upload/20150623/c0998062760b5e1c9c34f95dfe7cdda0.jpg_320x192.jpg?q=85);"></div>
						</div>
						<div class="title" stat="70461" w="tv"> 3女子被强行注射不明液体 <span class="desc">1人死亡系离职协警所为</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/news/play/18735.html" stat="70449" w="tv"
				       stat-new="70449" w-new="3470" title="多名女初中生围殴同学">
						<div class="pic_info">
							<div class="img"
							     style="background-image: url(http://dh2.kimg.cn/kimg/v/upload/20150623/d7986e911c03541c66dad6b98344ac28.jpg_320x192.jpg?q=85);"></div>
						</div>
						<div class="title" stat="70449" w="tv"> 多名女初中生围殴同学 <span class="desc">砸脑袋逼下跪</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/news/play/18617.html" stat="70419" w="tv"
				       stat-new="70419" w-new="3470" title="老汉因托梦挖泉眼每天喷鱼">
						<div class="pic_info">
							<div class="img"
							     style="background-image: url(http://dh2.kimg.cn/kimg/v/upload/20150623/b87aff9f540c6092962851f45941f4ca.jpg_320x192.jpg?q=85);"></div>
						</div>
						<div class="title" stat="70419" w="tv"> 老汉因托梦挖泉眼每天喷鱼 <span class="desc">农屋秒变聚宝盆</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/news/play/18611.html" stat="70416" w="tv"
				       stat-new="70416" w-new="3470" title="美女抛胸罩呼吁关注乳腺">
						<div class="pic_info">
							<div class="img"
							     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150623/400ade3745ea1eca1af9546e1a1f7414.jpg_320x192.jpg?q=85);"></div>
						</div>
						<div class="title" stat="70416" w="tv"> 美女抛胸罩呼吁关注乳腺 <span class="desc">男人也很支持</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/news/play/18636.html" stat="70437" w="tv"
				       stat-new="70437" w-new="3470" title="广西玉林“狗肉节”昨开幕">
						<div class="pic_info">
							<div class="img"
							     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150623/4ca513e5e2c44f3cc88ad91f28bd01b3.jpg_320x192.jpg?q=85);"></div>
						</div>
						<div class="title" stat="70437" w="tv"> 广西玉林“狗肉节”昨开幕 <span class="desc">整条街都是狗尸</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/news/play/18639.html" stat="70465" w="tv"
				       stat-new="70465" w-new="3470" title="男子不甘女友另结新欢">
						<div class="pic_info">
							<div class="img"
							     style="background-image: url(http://dh2.kimg.cn/kimg/v/upload/20150623/e1a519a83e611c9ad6fdd319560cb2eb.jpg_320x192.jpg?q=85);"></div>
						</div>
						<div class="title" stat="70465" w="tv"> 男子不甘女友另结新欢 <span class="desc">发私密照给“情敌”</span></div>
					</a></li>
			</ul>
		</div>
		<div class="banner_s_wrap"><h3 class="h_title list_tv"><a
					href="http://v.m.liebao.cn/category.php?cat_id=2&amp;title=%E7%94%B5%E8%A7%86%E5%89%A7&amp;type=recommend"
					class="h_t" stat="" w="tv" stat-new="more" w-new="2843"> 小编推荐 </a> <a
					href="http://v.m.liebao.cn/category.php?cat_id=2&amp;title=%E7%94%B5%E8%A7%86%E5%89%A7&amp;type=recommend"
					class="link_more" stat="" w="tv" stat-new="more" w-new="2843"> <i class="more"></i> </a></h3>

			<div class="banner_s"><a href="/detail.php?tsid=272970&amp;title=两生花" stat="69995" w="" stat-new="69995"
			                         w-new="2843">
					<div class="pic_info">
						<div class="img"
						     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150623/6ec1996c0aeca2f0c3269d1ac8d615cc.jpg_640x280.jpg?q=60);"></div>
					</div>
				</a>

				<div class="banner_s_desc"><strong style="background:#990033">两生花</strong>
					<span>刘恺威变暖男奶爸 与王丽坤上演凄美之恋</span></div>
			</div>
		</div>
		<div class="list_wrap">
			<ul class="list list_2col">
				<li><a class="list_cont" href="/detail.php?tsid=273073&amp;title=偏偏喜欢你" stat="70107" w="tv"
				       stat-new="70107" w-new="490" title="偏偏喜欢你">
						<div class="pic_info">
							<div class="img"
							     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150623/e07bd77686ae52471c86b2781e922c2b.jpg_320x192.jpg?q=85);"></div>
							<i class="tip_purple" style="background:#FF0000">新</i>

							<div class="img_layer">更新至12集</div>
						</div>
						<div class="title" stat="70107" w="tv"> 偏偏喜欢你 <span class="desc">陈乔恩遇山贼险失身</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=272930&amp;title=盗墓笔记" stat="66490" w="tv"
				       stat-new="66490" w-new="490" title="盗墓笔记">
						<div class="pic_info">
							<div class="img"
							     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150623/b311224f68a3a9d45d5fb64f44b113ff.jpg_320x192.jpg?q=85);"></div>
							<i class="tip_purple" style="background:#FF8800">热</i>

							<div class="img_layer">更新至3集</div>
						</div>
						<div class="title" stat="66490" w="tv"> 盗墓笔记 <span class="desc">只因为人群中多看了你一眼</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=272823&amp;title=花千骨" stat="66326" w="tv"
				       stat-new="66326" w-new="490" title="花千骨">
						<div class="pic_info">
							<div class="img"
							     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150618/ce576126c67e45f9bc506e3e8998a753.jpg_320x192.jpg?q=85);"></div>
							<div class="img_layer">更新至8集</div>
						</div>
						<div class="title" stat="66326" w="tv"> 花千骨 <span class="desc">赵丽颖受重伤 霍建华救爱徒</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=273003&amp;title=你是我的姐妹" stat="70065" w="tv"
				       stat-new="70065" w-new="490" title="你是我的姐妹">
						<div class="pic_info">
							<div class="img"
							     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150623/fb6a374941e95faf858b955b877c554b.jpg_320x192.jpg?q=85);"></div>
							<div class="img_layer">更新至18集</div>
						</div>
						<div class="title" stat="70065" w="tv"> 你是我的姐妹 <span class="desc">刘恺威变身都市痞男</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=272028&amp;title=屌丝男士第4季" stat="63571" w="tv"
				       stat-new="63571" w-new="490" title="屌丝男士第4季">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150618/955b02cb802353fd3e8750e35e245bf1.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">更新至5集</div>
						</div>
						<div class="title" stat="63571" w="tv"> 屌丝男士第4季 <span class="desc">屌男屌女相遇画风突变</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=273108&amp;title=生死连" stat="70434" w="tv"
				       stat-new="70434" w-new="490" title="生死连">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/47adef6f22f53496cc786d990d80eefa.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">更新至12集</div>
						</div>
						<div class="title" stat="70434" w="tv"> 生死连 <span class="desc">高颜值剃头匠杀鬼子逆袭</span></div>
					</a></li>
			</ul>
		</div>
		<div class="adbanner">
			<div id="gdt" data-posid="8030309010338868" data-appid="1102297551">
				<div style="left: 0px; bottom: 0px; width: 100%; height: 50px;" id="gdt_banner_popup_wrap">
					<div class="gdth_popup_floater"></div>
					<div class="gdth_popup_wrap" style="margin:0 auto;position:relative;max-width:1280px;">
						<iframe id="gdt_banner_ifr"
						        style="width: 100%; position: static !important; display: block !important; margin: 0px !important; padding: 0px !important; visibility: visible !important; float: none !important; border-width: 0px !important; height: 50px;"
						        scrolling="no" frameborder="0" marginheight="0" marginwidth="0" allowtransparency="true"
						        src="http://qzonestyle.gtimg.cn/qzone/biz/res/tmpl/banner.html#_spoint=1435051164733&amp;posid=8030309010338868&amp;posh=100&amp;posw=640&amp;posdomain=http%3A%2F%2Fv.m.liebao.cn&amp;postnum=0.5622489668894559&amp;adtype=banner&amp;ishybrid=false&amp;platform=web&amp;posclass=undefined&amp;appid=1102297551&amp;win_w=320&amp;win_h=8884&amp;conw=320&amp;conh=0&amp;scale=1&amp;conw=320"></iframe>
					</div>
				</div>
			</div>
			<!-- <script type="text/javascript" id="gdt-8030309010338868"> var TencentGDT = TencentGDT || []; TencentGDT.push({ posid:'8030309010338868', type:'banner',   filltype:'full', appid: "1102297551" }); (function() { var doc=document, h=doc.getElementsByTagName('head')[0], s=doc.createElement('script'); s.async=true; s.src='http://qzs.qq.com/qzone/biz/res/i.js '; h && h.insertBefore(s,h.firstChild) })() </script> -->
		</div>
		<div class="list_wrap"><h3 class="h_title list_hot"><a href="http://v.m.liebao.cn/ent/" class="h_t" stat=""
		                                                       w="tv" stat-new="more" w-new="494"> 社会·八卦 </a> <a
					href="http://v.m.liebao.cn/ent/play/18605.html" style="color:" class="rec" stat="70431" w="tv"
					stat-new="70431" w-new="494"> 邓紫棋用iPhone打乒乓 </a> <a href="http://v.m.liebao.cn/ent/"
		                                                                class="link_more" stat="" w="tv" stat-new="more"
		                                                                w-new="494"> <i class="more"></i> </a></h3>
			<ul class="list list_2col">
				<li><a class="list_cont" href="http://v.m.liebao.cn/ent/play/18640.html" stat="70432" w="tv"
				       stat-new="70432" w-new="494" title="王俊凯微博创吉尼斯纪录">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/upload/20150623/c7e5f8cb736c9ab8a8a2f32593d02bdf.jpg_320x192.jpg?q=85"></div>
						</div>
						<div class="title" stat="70432" w="tv"> 王俊凯微博创吉尼斯纪录 <span class="desc">妈妈粉力量大！</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/ent/play/18632.html" stat="70428" w="tv"
				       stat-new="70428" w-new="494" title="郝蕾因拍激情戏与邓超分手">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/upload/20150623/56ae84ec41ad738158e2026326d879ea.jpg_320x192.jpg?q=85"></div>
						</div>
						<div class="title" stat="70428" w="tv"> 郝蕾因拍激情戏与邓超分手 <span class="desc">称他是个小心眼</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/ent/play/18603.html" stat="70429" w="tv"
				       stat-new="70429" w-new="494" title="广电“喊停”嘉宾主持">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/upload/20150623/a12f20c1ce255c77c95a931f7ea70caa.jpg_320x192.jpg?q=85"></div>
						</div>
						<div class="title" stat="70429" w="tv"> 广电“喊停”嘉宾主持 <span class="desc">限令一出卫视堪忧</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/ent/play/18618.html" stat="70451" w="tv"
				       stat-new="70451" w-new="494" title="昆凌挺大肚探班周杰伦">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/upload/20150623/ff2da0d08693cc4db83a11be2cd9427d.jpg_320x192.jpg?q=85"></div>
						</div>
						<div class="title" stat="70451" w="tv"> 昆凌挺大肚探班周杰伦 <span class="desc">低调助阵好声音</span></div>
					</a></li>
			</ul>
		</div>
		<div class="banner_s_wrap"><h3 class="h_title list_movie"><a
					href="http://v.m.liebao.cn/category.php?cat_id=1&amp;type=recommend" class="h_t" stat="" w="tv"
					stat-new="more" w-new="2852"> 电影最新热播大片 </a> <a
					href="http://v.m.liebao.cn/category.php?cat_id=1&amp;type=recommend" class="link_more" stat=""
					w="tv" stat-new="more" w-new="2852"> <i class="more"></i> </a></h3>

			<div class="banner_s"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1434679842.html" stat="70430" w=""
			                         stat-new="70430" w-new="2852">
					<div class="pic_info">
						<div class="img lazy_bg"
						     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/3e0d1647ba8fb71b47edd73a5941b899.jpg_640x280.jpg?q=60"></div>
						<i class="tip_purple" style="background:#FF0066">专题</i></div>
				</a>

				<div class="banner_s_desc"><strong style="background:#990033">欲望在骚动</strong> <span>在堕落中高潮，欲望在挥霍中发酵，人性本兽，无边的欲望在咆哮！</span>
				</div>
			</div>
		</div>
		<div class="list_wrap">
			<ul class="list list_2col">
				<li><a class="list_cont" href="/detail.php?tsid=273231&amp;title=疯狂的麦克斯4" stat="70436" w="tv"
				       stat-new="70436" w-new="491" title="疯狂的麦克斯4">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/ac6bdf60517f8f9bc8096d68911a1d4f.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer layer_notext"><span class="score_left">8.8</span></div>
						</div>
						<div class="title" stat="70436" w="tv"> 疯狂的麦克斯4 <span class="desc">邪恶重口，疯狂特效</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=100029&amp;title=杀破狼" stat="70433" w="tv"
				       stat-new="70433" w-new="491" title="杀破狼">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/6fbd3864b6a67a1022388679490328fa.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer layer_notext"><span class="score_left">8.6</span></div>
						</div>
						<div class="title" stat="70433" w="tv"> 杀破狼 <span class="desc">警匪嗜血缠斗</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=273010&amp;title=念念" stat="70135" w="tv"
				       stat-new="70135" w-new="491" title="念念">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150617/5dbd21dcacce25f6da667e35c810ce50.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer layer_notext"><span class="score_left">7.2</span></div>
						</div>
						<div class="title" stat="70135" w="tv"> 念念 <span class="desc">梁洛施痴恋张孝全</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=273187&amp;title=两男变错身" stat="70109" w="tv"
				       stat-new="70109" w-new="491" title="两男变错身">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150616/a04ddcba0fced829c1f631458c8697fd.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer layer_notext"><span class="score_left">6.7</span></div>
						</div>
						<div class="title" stat="70109" w="tv"> 两男变错身 <span class="desc">重口大尺度换妻游戏</span></div>
					</a></li>
			</ul>
		</div>
		<div class="banner_s_wrap">
			<div class="banner_s"><a href="http://www.liebao.cn/game/ygys/?f=ys" stat="61268" w="" stat-new="61268"
			                         w-new="5624">
					<div class="pic_info">
						<div class="img lazy_bg"
						     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150410/8f6770dc4901a08226b2c63d635b71a4.jpg_640x280.jpg?q=60"></div>
						<i class="tip_purple" style="background:#FF0000">推广</i></div>
				</a>

				<div class="banner_s_desc"><span></span></div>
			</div>
		</div>
		<!-- 腾讯广告2 --> <!-- <div id="qvapp"></div> -->
		<div class="banner_s_wrap"><h3 class="h_title list_tv"><a
					href="http://v.m.liebao.cn/category.php?cat_id=2&amp;type=&amp;area=%E9%9F%A9%E5%9B%BD&amp;year="
					class="h_t" stat="" w="tv" stat-new="more" w-new="2853"> 日韩热播剧 </a> <a
					href="http://v.m.liebao.cn/category.php?cat_id=2&amp;type=&amp;area=%E9%9F%A9%E5%9B%BD&amp;year="
					class="link_more" stat="" w="tv" stat-new="more" w-new="2853"> <i class="more"></i> </a></h3>

			<div class="banner_s"><a href="/detail.php?tsid=272785&amp;title=上流社会" stat="66306" w="" stat-new="66306"
			                         w-new="2853">
					<div class="pic_info">
						<div class="img lazy_bg"
						     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/aafdfd797fb00ea84a20c1f5f7482a7a.jpg_640x280.jpg?q=60"></div>
					</div>
				</a>

				<div class="banner_s_desc"><strong style="background:#990033">上流社会</strong>
					<span>盛骏野心钓富家女 韩剧史上大长腿CP诞生</span></div>
			</div>
		</div>
		<div class="list_wrap">
			<ul class="list list_2col">
				<li><a class="list_cont" href="/detail.php?tsid=272363&amp;title=假面" stat="64182" w="tv"
				       stat-new="64182" w-new="960" title="假面">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/19070b42342721aa3d991d1f58cf1f62.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">更新至8集</div>
						</div>
						<div class="title" stat="64182" w="tv"> 假面 <span class="desc">假千金嫁入豪门</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=269676&amp;title=The Lover" stat="62389" w="tv"
				       stat-new="62389" w-new="960" title="The Lover">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150605/56b5060e19506e9b03d4b469dbf7f3a3.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">更新至11集</div>
						</div>
						<div class="title" stat="62389" w="tv"> The Lover <span class="desc">19禁韩剧 大谈性话题</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=271828&amp;title=情侣酒店" stat="66208" w="tv"
				       stat-new="66208" w-new="960" title="情侣酒店">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150608/76acbc86ca0558daa31a27f1722bf19e.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">5集完</div>
						</div>
						<div class="title" stat="66208" w="tv"> 情侣酒店 <span class="desc">AV女优开房谎称自己第一次</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=267243&amp;title=第二爱情" stat="59610" w="tv"
				       stat-new="59610" w-new="960" title="第二爱情">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150316/dc3fab39f1d5a85cb2fd09955c9a142a.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">7集完</div>
						</div>
						<div class="title" stat="59610" w="tv"> 第二爱情 <span class="desc">龟梨和也激情上演不伦恋</span></div>
					</a></li>
			</ul>
		</div>
		<div class="banner_s_wrap"><h3 class="h_title list_tv"><a
					href="http://v.m.liebao.cn/category.php?cat_id=2&amp;type=&amp;area=%E7%BE%8E%E5%9B%BD&amp;year="
					class="h_t" stat="" w="tv" stat-new="more" w-new="2851"> 欧美海外剧场 </a> <a
					href="http://v.m.liebao.cn/category.php?cat_id=2&amp;type=&amp;area=%E7%BE%8E%E5%9B%BD&amp;year="
					class="link_more" stat="" w="tv" stat-new="more" w-new="2851"> <i class="more"></i> </a></h3>

			<div class="banner_s"><a href="/detail.php?tsid=272220&amp;title=兄弟连(限时免费)" stat="64183" w=""
			                         stat-new="64183" w-new="2851">
					<div class="pic_info">
						<div class="img lazy_bg"
						     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150529/f0991b0d19ca9f76ddb2c9bece2fd955.jpg_640x280.jpg?q=60"></div>
					</div>
				</a>

				<div class="banner_s_desc"><strong style="background:#990033">兄弟连</strong> <span>二战史诗级巅峰之作来袭！</span>
				</div>
			</div>
		</div>
		<div class="list_wrap">
			<ul class="list list_2col">
				<li><a class="list_cont" href="/detail.php?tsid=265216&amp;title=真爱如血" stat="57824" w="tv"
				       stat-new="57824" w-new="961" title="真爱如血">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150319/cab3b35610b56e3df1b7134fde3173c1.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">80集完</div>
						</div>
						<div class="title" stat="57824" w="tv"> 真爱如血 <span class="desc">18禁算什么？这片25禁！</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=270043&amp;title=罗马第2季" stat="60292" w="tv"
				       stat-new="60292" w-new="961" title="罗马第2季">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150407/70ce2470f0658544f3dfaaa7690d922b.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">10集完</div>
						</div>
						<div class="title" stat="60292" w="tv"> 罗马第2季 <span class="desc">一段香艳彪悍的帝国史诗</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=272766&amp;title=超感八人组第1季" stat="66482" w="tv"
				       stat-new="66482" w-new="961" title="超感八人组第1季">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150612/af509877e77c8b8e9c3487ad3cda40bd.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">12集完</div>
						</div>
						<div class="title" stat="66482" w="tv"> 超感八人组第1季 <span class="desc">科幻 群P 激情四射</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=260257&amp;title=妖女迷行第5季" stat="66211" w="tv"
				       stat-new="66211" w-new="961" title="妖女迷行第5季">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150608/4590fd72d004d7bb61dd8360288ecf7a.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">更新至8集</div>
						</div>
						<div class="title" stat="66211" w="tv"> 妖女迷行第5季 <span class="desc">吸食男子的百合女淫妖</span></div>
					</a></li>
			</ul>
		</div>
		<div class="banner_s_wrap"><h3 class="h_title list_tv"><a
					href="http://v.m.liebao.cn/category.php?cat_id=2&amp;title=%E7%94%B5%E8%A7%86%E5%89%A7&amp;type=recommend"
					class="h_t" stat="" w="tv" stat-new="more" w-new="2860"> 爆笑网络剧 </a> <a
					href="http://v.m.liebao.cn/category.php?cat_id=2&amp;title=%E7%94%B5%E8%A7%86%E5%89%A7&amp;type=recommend"
					class="link_more" stat="" w="tv" stat-new="more" w-new="2860"> <i class="more"></i> </a></h3>

			<div class="banner_s"><a href="/detail.php?tsid=272755&amp;title=我是你的喋喋phone" stat="66218" w=""
			                         stat-new="66218" w-new="2860">
					<div class="pic_info">
						<div class="img lazy_bg"
						     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150608/786ebceddbc29294871e234183d9eaf6.jpg_640x280.jpg?q=60"></div>
					</div>
				</a>

				<div class="banner_s_desc"><strong style="background:#990033">我是你的喋喋phone</strong>
					<span>李易峰化身梦幻手机暖男</span></div>
			</div>
		</div>
		<div class="list_wrap">
			<ul class="list list_2col">
				<li><a class="list_cont" href="/detail.php?tsid=272828&amp;title=仙剑客栈第1季" stat="70096" w="tv"
				       stat-new="70096" w-new="2861" title="仙剑客栈第1季">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/f45e75ab812660c1c57117ceb3dd7250.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0000">新</i>

							<div class="img_layer">更新至3集</div>
						</div>
						<div class="title" stat="70096" w="tv"> 仙剑客栈第1季 <span class="desc">吴磊演绎少年李逍遥</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=134319&amp;title=成人记" stat="55128" w="tv"
				       stat-new="55128" w-new="2861" title="成人记">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150609/48e580a906f49b07f206b95bd0a06d36.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">10集完</div>
						</div>
						<div class="title" stat="55128" w="tv"> 成人记 <span class="desc">蕉男集体重口味玩突破</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=270268&amp;title=尖叫制片厂" stat="70201" w="tv"
				       stat-new="70201" w-new="2861" title="尖叫制片厂">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150618/48ddb7fa886508245bf10d3c7b742a46.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">10集完</div>
						</div>
						<div class="title" stat="70201" w="tv"> 尖叫制片厂 <span class="desc">悬疑版《五十度灰》</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=266565&amp;title=小明和他的小伙伴们2" stat="66538" w="tv"
				       stat-new="66538" w-new="2861" title="小明和他的小伙伴们2">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150612/88324cd0431d51e6f448327d7dd8c413.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">更新至7集</div>
						</div>
						<div class="title" stat="66538" w="tv"> 小明和他的小伙伴们2 <span class="desc">女老师和体育教练有一腿</span></div>
					</a></li>
			</ul>
		</div>
		<div class="banner_s_wrap"><h3 class="h_title list_tv"><a
					href="http://v.m.liebao.cn/category.php?cat_id=4&amp;title=%E7%BB%BC%E8%89%BA" class="h_t" stat=""
					w="tv" stat-new="more" w-new="2854"> 热门综艺 </a> <a
					href="http://v.m.liebao.cn/category.php?cat_id=4&amp;title=%E7%BB%BC%E8%89%BA" class="link_more"
					stat="" w="tv" stat-new="more" w-new="2854"> <i class="more"></i> </a></h3>

			<div class="banner_s"><a href="/detail.php?tsid=270309&amp;title=奔跑吧兄弟第2季" stat="61854" w=""
			                         stat-new="61854" w-new="2854">
					<div class="pic_info">
						<div class="img lazy_bg"
						     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150620/ef3156f838bd97bb28d7a164958c6342.jpg_640x280.jpg?q=60"></div>
					</div>
				</a>

				<div class="banner_s_desc"><strong style="background:#990033">奔跑吧兄弟第2季</strong> <span>钟汉良上演湿身诱惑，李晨爆发五分钟狂撕两人</span>
				</div>
			</div>
		</div>
		<div class="list_wrap">
			<ul class="list list_2col">
				<li><a class="list_cont" href="/detail.php?tsid=212567&amp;title=花样姐姐" stat="61871" w="tv"
				       stat-new="61871" w-new="489" title="花样姐姐">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150525/fb6305702bfcab4f86c7d777d0cc47a7.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF8800">热</i>

							<div class="img_layer"> 2015-05-31</div>
						</div>
						<div class="title" stat="61871" w="tv"> 花样姐姐 <span class="desc">杨紫父亲现身，马天宇羡慕痛哭</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=81898&amp;title=快乐大本营" stat="46343" w="tv"
				       stat-new="46343" w-new="489" title="快乐大本营">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150621/c8f7b10397c4ddb9655c81de0603d3c2.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer"> 2015-06-20</div>
						</div>
						<div class="title" stat="46343" w="tv"> 快乐大本营 <span class="desc">黄宗泽娇羞变少女</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=81905&amp;title=天天向上" stat="46791" w="tv"
				       stat-new="46791" w-new="489" title="天天向上">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150620/e38b94030e8e5d7912956335282ccd69.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer"> 2015-06-19</div>
						</div>
						<div class="title" stat="46791" w="tv"> 天天向上 <span class="desc">张静初变女汉子猛揍钱枫</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=88456&amp;title=Running Man" stat="60451" w="tv"
				       stat-new="60451" w-new="489" title="Running Man">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150622/2c5dd1f5f5255e1d89cfc56324950031.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer"> 2015-06-21</div>
						</div>
						<div class="title" stat="60451" w="tv"> Running Man <span class="desc">刘赫下跪自尊心受创伤</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=270951&amp;title=真正男子汉" stat="61870" w="tv"
				       stat-new="61870" w-new="489" title="真正男子汉">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150620/47324794ba747b5152eb47029ebae824.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer"> 2015-06-19</div>
						</div>
						<div class="title" stat="61870" w="tv"> 真正男子汉 <span class="desc">男子汉大闹军营婚礼</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=81890&amp;title=康熙来了" stat="57146" w="tv"
				       stat-new="57146" w-new="489" title="康熙来了">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150620/9665f1819d3c8939b7c3bfaed2dccb02.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer"> 2015-06-22</div>
						</div>
						<div class="title" stat="57146" w="tv"> 康熙来了 <span class="desc">胖妹小甜甜遭“排挤”</span></div>
					</a></li>
			</ul>
		</div>
		<div class="list_wrap"><h3 class="h_title list_tv"><a
					href="http://v.m.liebao.cn/category.php?cat_id=4&amp;title=%E7%BB%BC%E8%89%BA" class="h_t" stat=""
					w="tv" stat-new="more" w-new="2926"> 综艺最爆点 </a> <a
					href="http://v.m.liebao.cn/category.php?cat_id=4&amp;title=%E7%BB%BC%E8%89%BA" class="link_more"
					stat="" w="tv" stat-new="more" w-new="2926"> <i class="more"></i> </a></h3>
			<ul class="list list_2col">
				<li><a class="list_cont" href="/detail.php?tsid=271224&amp;title=奥莉扮空姐萌萌哒" stat="66147" w="tv"
				       stat-new="66147" w-new="2926" title="奥莉扮空姐萌萌哒">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150621/98152e2334daafc6580738428ab69d10.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer"> 2015-06-20</div>
						</div>
						<div class="title" stat="66147" w="tv"> 奥莉扮空姐萌萌哒 <span class="desc">爸爸回来了2</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=81953&amp;title=陆毅定女婿标准：要善良" stat="56431" w="tv"
				       stat-new="56431" w-new="2926" title="陆毅定女婿标准：要善良">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150621/b6bd10f505e75ddb72211b7aa7164d23.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer"> 2015-06-20</div>
						</div>
						<div class="title" stat="56431" w="tv"> 陆毅定女婿标准：要善良 <span class="desc">非诚勿扰</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=270713&amp;title=井宝接棒导演陷崩溃边缘" stat="63939" w="tv"
				       stat-new="63939" w-new="2926" title="井宝接棒导演陷崩溃边缘">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150621/078a67b0afa4439b1b8472cae785a113.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer"> 2015-06-20</div>
						</div>
						<div class="title" stat="63939" w="tv"> 井宝接棒导演陷崩溃边缘 <span class="desc">花儿与少年2</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=195617&amp;title=Ella：我也遭遇过渣男！" stat="55473" w="tv"
				       stat-new="55473" w-new="2926" title="Ella：我也遭遇过渣男！">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150621/c28bc4cbaa714720dc89b3165bcea79c.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer"> 2015-06-17</div>
						</div>
						<div class="title" stat="55473" w="tv"> Ella：我也遭遇过渣男！ <span class="desc">大牌驾到</span></div>
					</a></li>
			</ul>
		</div>
		<div class="banner_s_wrap"><h3 class="h_title list_tv"><a
					href="http://v.m.liebao.cn/category.php?cat_id=3&amp;title=%E5%8A%A8%E6%BC%AB" class="h_t"
					stat="15421" w="comic" stat-new="more" w-new="2857"> 动漫 </a> <a
					href="http://v.m.liebao.cn/category.php?cat_id=3&amp;title=%E5%8A%A8%E6%BC%AB" class="link_more"
					stat="15421" w="comic" stat-new="more" w-new="2857"> <i class="more"></i> </a></h3>

			<div class="banner_s"><a href="/detail.php?tsid=270203&amp;title=尸兄第2季 我叫白小飞" stat="61791" w=""
			                         stat-new="61791" w-new="2857">
					<div class="pic_info">
						<div class="img lazy_bg"
						     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150417/d20242c34dabd5152f1a68c0fa2babc7.jpg_640x280.jpg?q=60"></div>
						<i class="tip_purple" style="background:#FF0000">新</i></div>
				</a>

				<div class="banner_s_desc"><strong style="background:#990033">尸兄第2季</strong> <span>尸兄回归啦！依旧没节操！一起床就看见三个女性生物躺在自己床上的事情我会告诉你嘛</span>
				</div>
			</div>
		</div>
		<div class="list_wrap">
			<ul class="list list_2col">
				<li><a class="list_cont" href="/detail.php?tsid=85854&amp;title=火影忍者" stat="15223" w="tv"
				       stat-new="15223" w-new="492" title="火影忍者">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150410/4432a5428b9dfc31f6c3740998f11e67.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">更新至636集</div>
						</div>
						<div class="title" stat="15223" w="tv"> 火影忍者 <span class="desc">连载15年即将大结局</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=88030&amp;title=熊出没" stat="17525" w="tv"
				       stat-new="17525" w-new="492" title="熊出没">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141027/2977be6707d4495246b0a889f94efa73.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">更新至104集</div>
						</div>
						<div class="title" stat="17525" w="tv"> 熊出没 <span class="desc">熊大熊二丛林较量光头强</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=263094&amp;title=秦时明月之君临天下" stat="61390" w="tv"
				       stat-new="61390" w-new="492" title="秦时明月之君临天下">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150410/acac148fb14fbdf76e8774ff17c74611.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0000">新</i>

							<div class="img_layer">更新至7集</div>
						</div>
						<div class="title" stat="61390" w="tv"> 秦时明月之君临天下 <span class="desc">美剧式剧情悬念迭起</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=227903&amp;title=航海王(海贼王)" stat="15372" w="tv"
				       stat-new="15372" w-new="492" title="航海王(海贼王)">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150410/cf945087381f46b77ca821f5fad535e1.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">更新至698集</div>
						</div>
						<div class="title" stat="15372" w="tv"> 航海王(海贼王) <span class="desc">热血史诗航海少年梦</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=166834&amp;title=妖精的尾巴" stat="62970" w="tv"
				       stat-new="62970" w-new="492" title="妖精的尾巴">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150511/b345b0dd4551365b87b65e7fa1992265.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">更新至238集</div>
						</div>
						<div class="title" stat="62970" w="tv"> 妖精的尾巴 <span class="desc">御姐还童变萝莉悲惨遭虐</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=269526&amp;title=关于完全听不懂老公在说什么的事 第2季" stat="61837"
				       w="tv" stat-new="61837" w-new="492" title="关于完全听不懂老公在说什么的事 第2季">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150417/75ab960612fa6a1b2bc4dfb3a68bf6cd.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0000">新</i>

							<div class="img_layer">更新至12集</div>
						</div>
						<div class="title" stat="61837" w="tv"> 关于完全听不懂老公在说什么的事 第2季 <span
								class="desc">【第2季】不带这样虐狗的！</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=220946&amp;title=中国惊奇先生" stat="61391" w="tv"
				       stat-new="61391" w-new="492" title="中国惊奇先生">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150410/cbfc694d2db06a8267ec2e532d86df99.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0000">新</i>

							<div class="img_layer">更新至31集</div>
						</div>
						<div class="title" stat="61391" w="tv"> 中国惊奇先生 <span class="desc">神作再现！屌丝道士捉鬼记</span></div>
					</a></li>
				<li><a class="list_cont" href="/detail.php?tsid=217859&amp;title=十万个冷笑话第2季" stat="39160" w="tv"
				       stat-new="39160" w-new="492" title="十万个冷笑话第2季">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20140808/30926ee81aea1ee078bdeb433c94d467.jpg_320x192.jpg?q=85"></div>
							<div class="img_layer">更新至13集</div>
						</div>
						<div class="title" stat="39160" w="tv"> 十万个冷笑话第2季 <span class="desc">中国版日和</span></div>
					</a></li>
			</ul>
		</div>
		<div class="banner_s_wrap"><h3 class="h_title list_hot"><span class="h_t"> 疯狂系列之感官盛宴 </span></h3>

			<div class="banner_s"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1432096568.html" stat="64100" w=""
			                         stat-new="64100" w-new="5677">
					<div class="pic_info">
						<div class="img lazy_bg"
						     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150528/932658d084c3f8755dc074333b5b3d31.jpg_640x280.jpg?q=60"></div>
						<i class="tip_purple" style="background:#FF0066">专题</i></div>
				</a>

				<div class="banner_s_desc"><strong style="background:#990033">简单·暴力·痛快</strong> <span>最直接的视觉冲击</span>
				</div>
			</div>
		</div>
		<div class="list_wrap">
			<ul class="list list_2col">
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1416194762.html" stat="63529"
				       w="tv" stat-new="63529" w-new="5678" title="全网最新大片">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150519/134e7f83156a58cab155c16fcc6f1c99.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="63529" w="tv"> 全网最新大片 <span class="desc">嘘~都在我这儿呢</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1427427117.html" stat="61530"
				       w="tv" stat-new="61530" w-new="5678" title="哈哈哈哈停不下来">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150413/0cbb5b3aea3c21e46fa4ca1e8bd2d7e2.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="61530" w="tv"> 哈哈哈哈停不下来 <span class="desc">不看会后悔系列！</span></div>
					</a></li>
			</ul>
		</div>
		<div class="banner_s_wrap"><h3 class="h_title list_movie"><span class="h_t"> 特色专题 </span></h3>

			<div class="banner_s"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1433474551.html" stat="66432" w=""
			                         stat-new="66432" w-new="2928">
					<div class="pic_info">
						<div class="img lazy_bg"
						     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150609/b2a0a96bd23e2076b08ca604712acddb.jpg_640x280.jpg?q=60"></div>
						<i class="tip_purple" style="background:#FF0066">专题</i></div>
				</a>

				<div class="banner_s_desc"><strong style="background:#990033">苦逼的终点线</strong>
					<span>【独家策划】苦逼的终点线，滚蛋吧高考</span></div>
			</div>
		</div>
		<div class="list_wrap">
			<ul class="list list_2col">
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1429787503.html" stat="63524"
				       w="tv" stat-new="63524" w-new="493" title="惊你一啪悬疑片">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150424/7a4cee50a99b2b0ac0fb080623eb70de.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="63524" w="tv"> 惊你一啪悬疑片 <span class="desc">困你MB起来嗨</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1428919000.html" stat="63525"
				       w="tv" stat-new="63525" w-new="493" title="激燃火爆妞">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150424/c72a59defe2de503391a933337d0a60d.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="63525" w="tv"> 激燃火爆妞 <span class="desc">极致诱惑，嗜血如命</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1431000941.html" stat="63526"
				       w="tv" stat-new="63526" w-new="493" title="漫改集中营">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150428/c4e2cd00f28d8562833590dea85980a1.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="63526" w="tv"> 漫改集中营 <span class="desc">激燃狂飙荷尔蒙</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1431339935.html" stat="63527"
				       w="tv" stat-new="63527" w-new="493" title="第68届戛纳电影节">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150514/08d909438a178c4970bd8a60f489310e.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="63527" w="tv"> 第68届戛纳电影节 <span class="desc">高阶逼格速成指南</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/topics/70.html" stat="63519" w="tv" stat-new="63519"
				       w-new="493" title="抗日神剧节操碎满地">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150519/5f2ad7d20bd6054d528c510737d13154.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="63519" w="tv"> 抗日神剧节操碎满地 <span class="desc">我爷爷八岁就被鬼子杀害了！</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1427439388.html" stat="63518"
				       w="tv" stat-new="63518" w-new="493" title="穿越剧特辑">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150519/cf44488d0b61bbc9090c40d48f6c1d67.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="63518" w="tv"> 穿越剧特辑 <span class="desc">为你我已等待千年</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1418801592.html" stat="60337"
				       w="tv" stat-new="60337" w-new="493" title="那些神剧情的MV">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141217/56c07dee337947623ad8d167dfd5f76a.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="60337" w="tv"> 那些神剧情的MV <span class="desc">屁股满屏飞也是醉了</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1424939029.html" stat="60335"
				       w="tv" stat-new="60335" w-new="493" title="乐一乐">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150228/71c81b889b9a26abe49c52ff6d083b8c.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="60335" w="tv"> 乐一乐 <span class="desc">美女选秀用胸部作画</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1420354319.html" stat="60334"
				       w="tv" stat-new="60334" w-new="493" title="一起涨姿势">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150105/e6ec17acbe2d44c793975dcb2a041a15.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="60334" w="tv"> 一起涨姿势 <span class="desc">闻屁也能赚大钱？！</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1421214144.html" stat="60331"
				       w="tv" stat-new="60331" w-new="493" title="那些炸裂的创意">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150114/ebf74b4fde021d14ec4aaed0c31a32bc.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="60331" w="tv"> 那些炸裂的创意 <span class="desc">醉人广告集锦包你满意</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1423650018.html" stat="56902"
				       w="tv" stat-new="56902" w-new="493" title="唐嫣吻遍男神">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150215/42216fbe58c969f897d8fc6dc0028b2e.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="56902" w="tv"> 唐嫣吻遍男神 <span class="desc">这才是人生赢家啊！</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1419498581.html" stat="55712"
				       w="tv" stat-new="55712" w-new="493" title="2015年十大受期待电视剧">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141231/3c4831b74af3d2a92d17fbabb8993980.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="55712" w="tv"> 2015年十大受期待电视剧 <span class="desc">精彩抢先看！</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1421303669.html" stat="58638"
				       w="tv" stat-new="58638" w-new="493" title="历代美艳武媚娘大盘点">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150215/b7d7ac186406ebd759508576006d13cf.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="58638" w="tv"> 历代美艳武媚娘大盘点 <span class="desc">范爷完胜？</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1421997513.html" stat="58637"
				       w="tv" stat-new="58637" w-new="493" title="最佳荧幕情侣大盘点">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150215/5138bf05ce8818b1fa1b80d61b30c893.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="58637" w="tv"> 最佳荧幕情侣大盘点 <span class="desc">全民高呼“在一起”！</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1420355846.html" stat="56102"
				       w="tv" stat-new="56102" w-new="493" title="2014我们追的国产剧">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150105/7c83edbf3f0b792ce791087b6b35d625.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="56102" w="tv"> 2014我们追的国产剧 <span class="desc">盘点年度十佳电视剧</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1418375038.html" stat="55711"
				       w="tv" stat-new="55711" w-new="493" title="盘点金庸剧的奇葩翻拍">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141231/4f00c2aaf60d1c7a7cb28d133edc1e6d.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="55711" w="tv"> 盘点金庸剧的奇葩翻拍 <span class="desc">于正请放下那本小说！</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1412820934.html" stat="52449"
				       w="tv" stat-new="52449" w-new="493" title="周末影院：黑帮风云">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141013/3af132fb279425a4255d3a28b1ce8250.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="52449" w="tv"> 周末影院：黑帮风云 <span class="desc">嗜血的梦想与荣耀</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1415272771.html" stat="51462"
				       w="tv" stat-new="51462" w-new="493" title="霸道将军也温柔">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141113/b39727d6e869143fde3d6d417e9bd992.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="51462" w="tv"> 霸道将军也温柔 <span class="desc">将军你让我小鹿乱撞啊</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1415340302.html" stat="51464"
				       w="tv" stat-new="51464" w-new="493" title="15年连载火影完结">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141113/71ecfbf68be12d3d5035f6200850f59b.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="51464" w="tv"> 15年连载火影完结 <span class="desc">盘点那些年一起追的动漫</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1415850774.html" stat="51471"
				       w="tv" stat-new="51471" w-new="493" title="古装销魂角色魔女">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141113/051390b034c432fe53c8101de9ca6b31.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="51471" w="tv"> 古装销魂角色魔女 <span class="desc">冷艳销魂致命诱惑</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1414647925.html" stat="51463"
				       w="tv" stat-new="51463" w-new="493" title="被翻拍的海外剧">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141113/cc5a204f822aec531f31a6b34afb9e47.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="51463" w="tv"> 被翻拍的海外剧 <span class="desc">男女神被土产毁成渣</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1413965034.html" stat="51561"
				       w="tv" stat-new="51561" w-new="493" title="盘点那些毁三观的神剧">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141114/203f535b1f33e340fb4b90b927f7cc24.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="51561" w="tv"> 盘点那些毁三观的神剧 <span class="desc">前世出轨 今生乱伦</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1415006977.html" stat="51390"
				       w="tv" stat-new="51390" w-new="493" title="史诗级灾难大片">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20140723/1139da91f69be702d110b2c311cdb4ed.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="51390" w="tv"> 史诗级灾难大片 <span class="desc">惊险刺激，震撼人心！</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1413189936.html" stat="51353"
				       w="tv" stat-new="51353" w-new="493" title="“渤”金档：百变“卅帝”黄渤">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141013/51b755b2a76b78aaaffcae1cd941c6f9.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="51353" w="tv"> “渤”金档：百变“卅帝”黄渤 <span class="desc">屌丝式逆袭：从小人物到30亿帝</span>
						</div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/topics/47.html" stat="58639" w="tv" stat-new="58639"
				       w-new="493" title="男神的正确打开方式">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150215/d4f5929660ab4e031204f4444ead343e.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="58639" w="tv"> 男神的正确打开方式 <span class="desc">就该有颜有钱又任性！</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1412062900.html" stat="47386"
				       w="tv" stat-new="47386" w-new="493" title="点爆了的重口味大片">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141001/c111dffa46915de21620f4068fbea343.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="47386" w="tv"> 点爆了的重口味大片 <span class="desc">毁灭性快感！胆小者慎入</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/topic/index.php?zt=m_zhuanti_1404891109"
				       stat="40869" w="tv" stat-new="40869" w-new="493" title="仙侠古装情">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141113/d62d232dbcec1cb102a0a1194800956b.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="40869" w="tv"> 仙侠古装情 <span class="desc">游戏改编、魔幻仙侠</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1413883441.html" stat="52448"
				       w="tv" stat-new="52448" w-new="493" title="苍井空最近很忙">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141022/56c42abf3a5aac7ee1dfc76fdb01e0e3.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="52448" w="tv"> 苍井空最近很忙 <span class="desc">不一样的苍井空！~</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1412838097.html" stat="48586"
				       w="tv" stat-new="48586" w-new="493" title="真实案件改编电影">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141013/8bf99e0fe26e6a94cf7b6a9e54133e1e.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="48586" w="tv"> 真实案件改编电影 <span class="desc">百分之八十还原事实真相！</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1412062918.html" stat="47392"
				       w="tv" stat-new="47392" w-new="493" title="史上最雷大片">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20140825/53afa2895f57c9404495b2bf627ac1a4.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="47392" w="tv"> 史上最雷大片 <span class="desc">雷死你没商量~</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1411955482.html" stat="47388"
				       w="tv" stat-new="47388" w-new="493" title="史上小成本大票房神作">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141009/58ef9b1bc0fdb503c8e7e166a0b33f61.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="47388" w="tv"> 史上小成本大票房神作 <span class="desc">部部秒杀好莱坞大片！</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1411901953.html" stat="47384"
				       w="tv" stat-new="47384" w-new="493" title="盘点瞬间笑尿你的神剧">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141009/734cca6764d110f9cf39e755fbf57a21.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="47384" w="tv"> 盘点瞬间笑尿你的神剧 <span class="desc">G奶荤段子姐妹花带你装X</span></div>
					</a></li>
			</ul>
		</div>
		<div class="list_wrap"><h3 class="h_title list_hot"><a
					href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1415612668.html" class="h_t" stat="" w="tv"
					stat-new="more" w-new="3944"> 最爆点系列 </a> <a
					href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1415612668.html" class="link_more" stat="" w="tv"
					stat-new="more" w-new="3944"> <i class="more"></i> </a></h3>
			<ul class="list list_2col">
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1415860273.html" stat="52445"
				       w="tv" stat-new="52445" w-new="3944" title="爆点：假胸女星">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141114/35a07dbe7a5155a4a4897b1456ac52c3.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="52445" w="tv"> 爆点：假胸女星 <span class="desc">通缉圈内十大假胸女星</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1414572729.html" stat="52444"
				       w="tv" stat-new="52444" w-new="3944" title="爆点：史上最强胎动">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141029/a6b8986c6168813cdec2160292097621.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="52444" w="tv"> 爆点：史上最强胎动 <span class="desc">孩子在肚中拳打脚踢</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1414487505.html" stat="52443"
				       w="tv" stat-new="52443" w-new="3944" title="爆点：囧往事">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141028/0bfcb6ccda9c12ab52bd718d20f6cf59.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="52443" w="tv"> 爆点：囧往事 <span class="desc">那些明星最想销毁的过去</span></div>
					</a></li>
				<li><a class="list_cont" href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1414054190.html" stat="51694"
				       w="tv" stat-new="51694" w-new="3944" title="爆点：丧病MV">
						<div class="pic_info">
							<div class="img lazy_bg"
							     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20141023/48de53bf3814f42a3f3ce060c77ba68c.jpg_320x192.jpg?q=85"></div>
							<i class="tip_purple" style="background:#FF0066">专题</i></div>
						<div class="title" stat="51694" w="tv"> 爆点：丧病MV <span class="desc">老奶奶与少年啪啪啪！</span></div>
					</a></li>
			</ul>
		</div>
		<div class="list_site">
			<ul class="clearfix">
				<li><a href="http://m.video.baidu.com/" stat="15369" w="site" stat-new="15369" w-new="488" title="百度">
						<img
							src="http://dh2.kimg.cn/v/m/upload/20140516/c0b4efe70af8863d6da07dc580270ab1.png?v=1400223273">
						百度 </a></li>
				<li><a href="http://www.youku.com" stat="15216" w="site" stat-new="15216" w-new="488" title="优酷"> <img
							src="http://dh2.kimg.cn/v/m/upload/20131231/28c0ef5ac0d36eeb91264b17d313e7bf.png?v=1388479537">
						优酷 </a></li>
				<li><a href="http://m.tv.sohu.com" stat="15365" w="site" stat-new="15365" w-new="488" title="搜狐"> <img
							src="http://dh2.kimg.cn/v/m/upload/20140102/8ae1c43d4e1dd24107fb5267a80057bf.png?v=1388666467">
						搜狐 </a></li>
				<li><a href="http://m.v.qq.com" stat="15366" w="site" stat-new="15366" w-new="488" title="腾讯"> <img
							src="http://dh2.kimg.cn/v/m/upload/20140102/0e14125e08f33c09ba164edd80f8b2aa.png?v=1388666583">
						腾讯 </a></li>
				<li><a href="http://m.iqiyi.com" stat="15368" w="site" stat-new="15368" w-new="488" title="爱奇艺"> <img
							src="http://dh2.kimg.cn/v/m/upload/20140102/b6385a4155ed4084ad747547e39b8b60.png?v=1388666630">
						爱奇艺 </a></li>
				<li><a href="http://m.letv.com" stat="15370" w="site" stat-new="15370" w-new="488" title="乐视"> <img
							src="http://dh2.kimg.cn/v/m/upload/20140102/8bf6a186277b971aa90231b13f4cd9aa.png?v=1388667090">
						乐视 </a></li>
			</ul>
		</div>
	</div>
