<?php echo $this->render("layout/newheader.phtml");?>
<div id="page">
		<?php if ($hasheader) {?>
		<header id="iHeader" class="hd">
			<div class="top-wrap">
				<div class="title">
					<a href="<?php echo $webroot.'/user/account/index';?>" class="back"></a>
					<h1>更多资料</h1>
				</div>
			</div>
		</header>
		<?php }?>
		
		<div class="paccount" id="iscrollWrap">
			<div class="mainWrap">
				<!-- 内容区域 START-->
				<div class="ct-form">
					<form  method="post" action="<?php echo $webroot.$addPostUrl; ?>" id="J_saveForm">
					<input type="hidden" name="token" value="<?php echo $token?>"/>
						<section class="form-field">
							<div class="form-input form-text">
								<div><label for="">邮    箱：</label></div>
								<div><input type="text" name="email" value="" /></div>
							</div>
						</section>
						<section class="form-field">
							<div class="form-input form-text">
								<div><label for="">Q    Q：</label></div>
								<div><input type="text" name="qq" value="" /></div>
							</div>
						</section>
						<section class="form-field">
							<div class="form-select">
								<div><label for="">职    业：</label></div>
								<div>
									<select name="job">
									    <option value="0">请选择</option>
										<option value="1">销售/采购</option>
										<option value="2">IT/通讯</option>
										<option value="3">房地产/建筑</option>
										<option value="4">保险/金融</option>
										<option value="5">医药/化工</option>
										<option value="6">管理/人事行政</option>
										<option value="7">设计/媒体</option>
										<option value="8">生产/物流</option>
										<option value="9">机关单位/公务员</option>
										<option value="10">其他</option>
									</select>
								</div>
							</div>
						</section>
						<section class="form-field">
							<div class="form-select">
								<div><label for="">爱    好：</label></div>
								<div>
									<select name="love">
									    <option value="0">请选择</option>
										<option value="1">游戏</option>
										<option value="2">购物</option>
										<option value="3">旅游</option>
										<option value="4">健身</option>
										<option value="5">美食</option>
										<option value="6">电子产品</option>
										<option value="7">电影</option>
										<option value="8">美妆</option>
										<option value="9">养生</option>
										<option value="10">宅</option>
										<option value="11">看书</option>
										<option value="12">写作</option>
										<option value="13">其他</option>
									</select>
								</div>
							</div>
						</section>
						<section class="form-field">
							<div class="form-select">
								<div><label for="">年龄段：</label></div>
								<div>
									<select name="age">
									    <option value="0">请选择</option>
										<option value="1">18岁以下</option>
										<option value="2">19—25岁</option>
										<option value="3">26—35岁</option>
										<option value="4">36—45岁</option>
										<option value="5">46—55岁</option>
										<option value="6">56岁以上</option>
									</select>
								</div>
							</div>
						</section>
						<section class="form-field">
							<div class="form-button button">
								<button type="submit" class="btn gray">保存</button>
							</div>
						</section>
					</form>
				</div>
				<!-- 内容区域 END-->
			</div>
		</div>
	</div>
</body>
</html>