<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl . '?show_type=' . $show_type;?>">商品列表</a></li>
    <li class="current"><a href="javascript:;">添加商品</a></li>
	</ul>
</div>
<div class="h_a">添加商品</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="show_type" value="<?php echo $show_type;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
	 	<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input wa" name="sort" value="0"></td>
		</tr>
	   <!-- <tr class="tr">
			<th class="th">是否推荐首页</th>
			<td class="td">
				<label class="mr20"><input name="isrecommend"  value="1" type="radio">是</label>
				<label class="mr20"><input name="isrecommend"  value="2" type="radio" checked="true">否</label>
			</td>
	   </tr>-->
	   <tr class="tr">
			<th class="th">是否货到付款</th>
			<td class="td">
				<label class="mr20"><input name="iscash"  value="1" type="radio">是</label>
				<label class="mr20"><input name="iscash"  value="2" type="radio" checked="true">否</label>
			</td>
		</tr>
		<tr class="tr" <?php if(empty($show_type)) echo 'style="display: none;"';?>>
			<th class="th">是否新人专供</th>
			<td class="td">
				<label class="mr20"><input name="is_new_user"  value="1" type="radio">是</label>
				<label class="mr20"><input name="is_new_user"  value="2" type="radio" checked="true">否</label>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">商品类型</th>
			<td class="td">
				<select name="goods_type" class="wa">
				<?php foreach ($goods_types as $key=>$value) {?>
					<option value="<?php echo $key;?>"><?php echo $value;?></option>
				<?php }?>
				</select>				
			</td>
		</tr>
		<tr class="tr">
			<th class="th">供应商</th>
			<td class="td">
				<select name="supplier" class="wb">
				<?php foreach($suppliers as $key=>$value) { ?>
					<option value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
				<?php }?>
				</select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td"><select name="status" class="wb">
                	<option value="1">开启</option>
                	<option value="0">关闭</option>
            </select></td>
		</tr>
		<tr class="tr">
			<th class="th">售价</th>
			<td class="td"><input type="text" class="input wb" name="price" value=""></td>
		</tr>
		<tr class="tr" <?php if(empty($show_type)) echo 'style="display: none;"';?>>
			<th class="th">银币使用上限</th>
			<td class="td"><input type="text" class="input wb" name="silver_coin" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">可销售的库存</th>
			<td class="td"><input type="text" class="input wb" name="stock_num" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">每人限购数</th>
			<td class="td"><input type="text" class="input wb" name="limit_num" value=""></td>
		</tr>
		<tr class="tr" id="purchase_num">
			<th class="th">已购买数量</th>
			<td class="td"><input type="text" class="input wb" name="purchase_num" value=""></td>
		</tr>
		 <tr class="tr">
			<th class="th">商品名称</th>
			<td class="td"><input type="text" class="input wc" name="title" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">商品图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">产品详情图片</th>
			<td class="td">
				<div id="imgs">				
				</div>
				<div class="mb10"><button onclick="addupload();" onfocus="blur();" type="button" class="btn">＋添加产品图片</button></div>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">商品起止时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="" /></div>
			</td>
		</tr>
		<tr class="tr" id="descrip">
				<th class="th">内容</th>
				<td class="td"><textarea
						style="width: 800px; height: 500px" class="textarea"
						name="descrip"></textarea>
				</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script src="<?php echo $staticPath;?>/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
<script type="text/javascript">
var editor;
KindEditor.ready(function(K) {
	K.token = token;
    editor = K.create('textarea[name="descrip"]', {
        resizeType : 1,
        allowPreviewEmoticons : false,
        allowImageUpload : true,
        uploadJson : '<?php echo $adminroot.$uploadImgUrl;?>',
        items : EDITOR_ITEMS
    });
});
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/LocalGoods/index?show_type=<?php echo $show_type;?>');
	});

	var imgc = 1;
	addupload  = function() {
		var al = $('<ul class="uploadImg"><li id="Img'+imgc+'"><img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/><input type="hidden" name="simg['+imgc+']" value=""></li></ul><p style="clear:both;"><iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=Img';?>'+imgc+'" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe></p>');
		$('#imgs').append(al);
		imgc++;
	}
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
