<?php echo $this->render("layout/header.phtml"); ?>
<style>
	.iform {
		width: 200px;
	}
</style>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $indexUrl; ?>">商品列表</a></li>
		<li class="current"><a href="<?php echo $addUrl; ?>">添加商品</a></li>
		<li><a href="<?php echo $summaryUrl; ?>">汇总信息</a></li>
	</ul>
</div>
<div class="h_a">添加商品</div>
<form method="post" action="<?php echo $addPostUrl; ?>" id="addForm">
	<input name="token" value="<?php echo $token; ?>" type="hidden"/>

	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">分类</th>
				<td class="td">
				<select id="cat_id" name="cat_id">
						<option value="0">请选择</option>
						<?php foreach ($category as $k => $v) { ?>
							<option value="<?php echo $v['id']; ?>"><?php echo $v['name']; ?></option>
						<?php } ?>
					</select></td>
			</tr>

			<tr class="tr">
				<th class="th">名称</th>
				<td class="td"><input type="text" class="input" name="name" value=""></td>
			</tr>
			
			
			<tr class="tr" id="tr_out_ad_id" style="display:none">
				<th class="th">百度广告id</th>
				<td class="td"><input type="text" class="input" name="out_ad_id" value=""></td>
			</tr>

			<tr class="tr" id="tr_link">
				<th class="th">链接</th>
				<td class="td"><input type="text" name="link"  class="input"></td>
			</tr>
			<tr class="tr">
				<th class="th">产生积分数</th>
				<td class="td"><input type="text" name="scores" id="scores" class="input"></td>
			</tr>
			<tr class="tr">
				<th class="th">开始时间</th>
				<td class="td"><input name="start_time" id="start_time" class="input" type="text"></td>
			</tr>
			<tr class="tr">
				<th class="th">结束时间</th>
				<td class="td"><input name="end_time" id="end_time" class="input" type="text"></td>
			</tr>

			<tr class="tr">
				<th class="th">排序</th>
				<td class="td"><input type="text" name="sort" id="sort" class="input" value="1"></td>
			<tr>

			<tbody id="image">
			<tr class="tr" id="tr_image">
				<th class="th">图片</th>
				<td class="td">
					<ul class="uploadImg">
						<li id="productImage">
							<img src="<?php echo $staticPath; ?>/img/content/nopic.jpg"/>
							<input type="hidden" name="image" value="">
						</li>
					</ul>
					<p style="clear:both;">
						<iframe name="upload" src="<?php echo $uploadUrl . '/?imgId=productImage'; ?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
					</p>
				</td>
			</tr>
			</tbody>

			<tr class="tr" id="tr_is_special">
				<th class="th">是否为特权商品</th>
				<td class="td">
					<select name="is_special" id="is_special">
						<option value="1">是</option>
						<option value="0">否</option>
					</select>
				</td>
			</tr>

			<tr class="tr">
				<th class="th">状态</th>
				<td class="td"><select name="status" class="select">
						<option value="1">开启</option>
						<option value="0">关闭</option>
					</select></td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button  onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script
	src="<?php echo $staticPath; ?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script type="text/javascript">
	//用户表单数据提交
	$(document).ready(function () {
		$('#start_time').datetimepicker();
		$('#end_time').datetimepicker();

		ajaxForm('addForm', function (ret) {
			ajaxRedirect(ret, baseurl + '/Admin/produces/index');
		});

		$('#cat_id').change(function(){
	       value = $(this).val();
	       if(value == 8){		
	    	   $("#tr_link").css('display', 'none');
	    	   $("#tr_is_special").css('display', 'none');
	    	   $("#tr_image").css('display', 'none');
	    	   $("#tr_out_ad_id").css('display', '');
	  
			}else{
				$("#tr_link").css('display', '');
				$("#tr_is_special").css('display', '');
		    	$("#tr_image").css('display', '');
		    	$("#tr_out_ad_id").css('display', 'none');
			}
		
		});
	})

</script>
<?php echo $this->render("layout/footer.phtml"); ?>
