<!DOCTYPE html>
<html lang="en">
<head>
	<?php $this->title="";$this->hasSearch=false; ?>
	<meta charset="UTF-8">
	<title>游戏大厅</title>
	<?php echo $this->render("layout/cssInc.phtml");?>
</head>
<body>
	<?php echo $this->render("layout/header.phtml");?>
	<div id="container"></div>
	<div id="footer"></div>
</body>
<?php echo $this->render("layout/scriptInc.phtml"); ?>
<script type="text/javascript">
	var searchHotData = {
		list:<?php echo $apihot?>,
                defaultSearch: '<?php echo $defaultKeyword?>',
		searchMoreUrl:'/Api/Local_Search/searchMore?type=h5'
                ,href:'/search/list?t_bi=<?=$bi?>'
	};
	searchHotData.picturePath = '<?php echo $appImg?>';
	React.render(
		React.createElement(SearchGameHotWords, {items: searchHotData})
	  , document.getElementById('container')
	);
	$(function(){
		 $('#footer').html('<?php echo str_replace(PHP_EOL, '', $this->render("layout/footer.phtml")); ?>');	   
 })
	
</script>
<?php echo $this->render("layout/lastscriptInc.phtml"); ?>
</html>