<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $listUrl;?>">会员列表</a></li>
        <li><a href="<?php echo $giftUrl;?>">生日礼物</a></li>
        <li><a href="<?php echo $vipSuperDescUrl;?>">尊贵身份说明</a></li>
        <li><a href="<?php echo $vipActivityDescUrl;?>">活动返利说明</a></li>
        <li class="current"><a href="javascript:;">会员说明</a></li>
	</ul>
</div>
<div style="float: right;">
	<a href="/Admin/Account_VipIcon/index">vip图标</a>
	<a href="/Admin/Account_VipIcon/addVipValue">vip测试</a>
</div>
<form method="post" action="<?php echo $vipDescUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<td class="th">会员等级说明</td>
			<td class="td">
			     <textarea style="width: 60%; height: 100px" class="textarea" name="info"><?php echo $info;?></textarea>
			</td>
		</tr>
		<tr class="tr">
			<td class="th">成长值明细说明</td>
			<td class="td">
			     <textarea style="width: 60%; height: 100px" class="textarea" name="valueInfo"><?php echo $valueInfo;?></textarea>
			</td>
		</tr>
		<tr class="tr">
			<td class="th">排行榜说明</td>
			<td class="td">
			     <textarea style="width: 60%; height: 100px" class="textarea" name="rankInfo"><?php echo $rankInfo;?></textarea>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $vipDescUrl;?>');
	});
})
</script>

<?php echo $this->render("layout/footer.phtml");?>