<?php echo $this->render("../../Front/views/layout/header.phtml");?><section id="page">
<section id="page">
	<header id="header"><!-- HEADER --></header>
	<!-- 主体内容 -->
	<section id="content">
		<section class="about">
			<section class="top-info">
				<ul class="mod-text-list mod-ws-box">
					<li>
						<dl class="mod-dl-list">
							<dd>金立购，为金立旗下的官方购物平台，主要致力于为金立用户提供价优物美又实用的商品。有反馈用户的积分换购，
							有主编精心推荐的优质商品，有包罗万象的日常所需。金立购一个更懂你的省钱助手。
							</dd>
						</dl>
					</li>
				</ul>

				<ul class="mod-text-list">
					<li><a href="http://gou.gionee.com">网址：gou.gionee.com</a></li>
					<li><a href="tel:075582518551" class="r-arrow">客服电话：075582518551</a></li>
					<li>官方Q群：237057997</li>
					<li><a href="http://ti.3g.qq.com/g/s?sid=AesfnwLsS27aRWXY61fzYj9B&r=723442&aid=h&hu=gionee-gou" class="r-arrow">官方微博：http://t.qq.com/gionee-gou</a></li>
				</ul>
			</section>
			<footer class="version">
				软件版本：<?php echo $version;?> <br>
				深圳市金立通信设备有限公司 <br>
        		copyright© 2012
			</footer>
		</section>
	</section>
	<!--  /主体内容 -->
	<footer id="footer"><!-- FOOTER --></footer>
</section>
</body>
</html>