<?php echo $this->render("layout/webheader.phtml");?>

<body data-pagerole="body">
	<div class="module credit-rule">
		<div class="score-todo-bg J_lazyload_img">
			<img src="<?php echo $staticResPath?>/pic/blank.gif" data-src="<?php echo $staticResPath?>/pic/score-todo-bg.jpg">
		</div>
		<div class="score-todo J_lazyload_img">
			<img src="<?php echo $staticResPath?>/pic/blank.gif" data-src="<?php echo $staticResPath?>/pic/score-todo.jpg">
		</div>
		<div class="score-list">
			<ul>
				<li class="item">每日签到</li>
				<li class="score"><em>+50分</em></li>
				<li class="flex">限每日第1次启动有效</li>
			</ul>
			<ul>
				<li class="item">连续3天登录</li>
				<li class="score"><em>+50分</em></li>
				<li class="flex"><span></span></li>
			</ul>
			<ul>
				<li class="item">砍价</li>
				<li class="score"><em>+25分</em></li>
				<li class="flex">限每日前2次砍价有效</li>
			</ul>
			<ul>
				<li class="item">好友帮忙砍价</li>
				<li class="score"><em>+30分</em></li>
				<li class="flex">限每日前4个好友有效</li>
			</ul>
			<ul>
				<li class="item">分享砍价商品</li>
				<li class="score"><em>+30分</em></li>
				<li class="flex">限每日前4次分享有效</li>
			</ul>
			<ul>
				<li class="item">分享购物大厅给好友</li>
				<li class="score"><em>+40分</em></li>
				<li class="flex">限每日前4次分享有效</li>
			</ul>
			<ul>
				<li class="item">分享购物、知物链接</li>
				<li class="score"><em>+20分</em></li>
				<li class="flex">限每日前5次分享有效</li>
			</ul>
			<ul>
				<li class="item">关注购物大厅微博</li>
				<li class="score"><em>+50分</em></li>
				<li class="flex">限一次关注有效</li>
			</ul>
		</div>
		<div class="score-list">
			<ul>
				<li class="pl">累计登录<em>15天</em></li>
				<li class="center">额外奖励<em>1000分</em></li>
			</ul>
			<ul>
				<li class="pl">累计砍价<em>30次</em></li>
				<li class="center">额外奖励<em>1000分</em></li>
			</ul>
			<ul>
				<li class="pl">累计邀请好友砍价<em>60次</em></li>
				<li>额外奖励<em>1000分</em></li>
			</ul>
			<ul>
				<li class="pl">累计分享砍价商品<em>60次</em></li>
				<li>额外奖励<em>1000分</em></li>
			</ul>
		</div>
		<div class="legend">
			活动声明：本活动是深圳帮购科技有限公司组织，与苹果公司无关。
		</div>
	</div>


<?php echo $this->render("layout/tj.phtml");?>
<?php echo $this->render("layout/newfooter.phtml");?>