<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<title><?php echo $pageTitle?> - 金立3g门户</title>
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="appRef" content="<?php echo $staticResPath;?>" />
	<link rel="stylesheet" href="<?php echo $staticSysPath;?>/reset/mpcore.css?v=<?php echo $version;?>" />
	<link rel="stylesheet" href="<?php echo $staticResPath;?>/assets/css/browser.css?v=<?php echo $version;?>" />
	<script type="text/javascript" src="<?php echo $staticSysPath;?>/icat/1.1.3/icat.js?v=<?php echo $version;?>"  corelib="//zepto.js" main="../browser.js"></script>
	<script type="text/javascript">var token= '<?php echo $token;?>'</script>
</head>
<body dt-cr="<?php echo $crUrl;?>">
