<?php $isLast = preg_match('/^2/', $nav) > 0 ? true:false;?>

		<header class="hd">
			<div class="line-top"></div>
			<div class="menu">
				<ul>
					<li <?php if(!$isLast){?>class="selected"<?php }?>>
						<span class="top-arrow"><i></i></span>
						<a href="<?php echo $webroot;?>">金立世界</a>
					</li>
					<li <?php if($isLast){?>class="selected"<?php }?>>
						<span class="top-arrow"><i></i></span>
						<a href="<?php echo $webroot;?>/news">我的乐园</a>
					</li>
				</ul>
			</div>
			<div class="sub-menu">
<?php if($isLast){?>
				<ul>
					<li><a <?php if($nav=='2-1'){?>class="selected"<?php }?> href="<?php echo $webroot;?>/news">新闻资讯</a><i></i></li>
					<li><a <?php if($nav=='2-2'){?>class="selected"<?php }?> href="<?php echo $webroot;?>/picture">美图在线</a><i></i></li>
					<li><a <?php if($nav=='2-4'){?>class="selected"<?php }?> href="<?php echo $webroot;?>/user/index/signin">每日签到</a></li>
				</ul>
<?php }else{?>
				<ul>
					<li><a <?php if($nav=='1-1'){?>class="selected"<?php }?> href="<?php echo $webroot;?>">金立手机</a><i></i></li>
					<li><a <?php if($nav=='1-2'){?>class="selected"<?php }?> href="<?php echo $webroot;?>/resource">资源下载</a><i></i></li>
					<li><a <?php if($nav=='1-3'){?>class="selected"<?php }?> href="<?php echo $webroot;?>/parts">手机配件</a><i></i></li>
					<li><a <?php if($nav=='1-4'){?>class="selected"<?php }?> href="<?php echo $webroot;?>/services">售后服务</a></li>
				</ul>
<?php }?>
			</div>
		</header>
