<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $indexUrl;?>">统计列表</a></li>
    <li class="current"><a href="javascript:;">添加分类</a></li>
    <li><a href="<?php echo $listUrl;?>">分类列表</a></li>
	</ul>
</div>
<div class="h_a">添加分类</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">		
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="name" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">上级分类</th>
			<td class="td">
		<select name="parent_id">
		<option value="0">顶级分类</option>
<?php foreach($parents as $key => $value) {?>
                <option value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
<?php }?>
                </select></td>
		</tr>
	<tr class="tr">
			<th class="th">链接</th>
			<td class="td"><input type="text" class="input wc" name="url" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="order_id" value=""></td>
		</tr>
		
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Crcategory/index');
	});
})

</script>
<?php echo $this->render("layout/footer.phtml");?>
