<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li class="current"><a href="<?php echo $indexUrl;?>">统计列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加分类</a></li>
		<li><a href="<?php echo $listUrl;?>">分类列表</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>" method="post">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">日期</th>
				<td class="td"><input class="input" type="text" maxlength="30"
					id="sdate" name="sdate" value="<?php echo $sdate;?>"> 至 <input
					class="input" type="text" id="edate" maxlength="30" name="edate"
					value="<?php echo $edate;?>"></td>

			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button type="submit">搜 索</button></span></span>
	</div>

</form>

<script src="<?php echo $staticPath;?>/admin/js/admin/highcharts.js"></script>
<script src="<?php echo $staticPath;?>/admin/js/admin/stat.js"></script>

<div class="table_full">
<table width="100%" cellspacing="0" cellpadding="0">
    <tr class="tr1">
        <td class="td2">
<?php foreach($crlist as $key=>$value) {?>
	<div id="container<?php echo $key;?>"></div>
	<script>
	showChart({
		wrapId: 'container<?php echo $key;?>',
		wrapHeight: <?php echo $value['itemcount'] * 50 ;?>,
		title: '<?php echo $value['name'];?>',
		data: <?php echo json_encode($value['items']);?>
	});
	</script>
<?php }?>

        </td>
    </tr>
    <tr class="tr">
			<td class="td">其它页面总点击量：<?php echo $others;?></td>
	</tr>
</table>
</div>


<script type="text/javascript">
$(document).ready(function() {
	$("#sdate").datepicker({
				dateFormat : 'yy-mm-dd'
			});
	$("#edate").datepicker({
				dateFormat : 'yy-mm-dd'
			});
})

</script>
<?php echo $this->render("layout/footer.phtml");?>