<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
    <ul class="cc">
	     <li><a href="<?php echo $editUrl;?>">猜你喜欢管理</a></li>
	     <li class="current"><a href="<?php echo $guessUrl;?>">喜欢默认数据</a></li>
	     <li><a href="<?php echo $addCtUrl;?>">添加默认数据</a></li>
	     <li><a href="<?php echo $editCtUrl;?>">编辑默认数据</a></li>
     </ul>
</div>
<div class="h_a">
	<span>共<?php echo $total;?>条结果</span>
</div>
<form action="<?php echo $guessUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td">
			<select name="hot" class="wa">
			    <option  value="0">全部</option>
				<option <?php if($search['hot'] == 1) echo 'selected';?> value="1">最新</option>
				<option <?php if($search['hot'] == 2) echo 'selected';?> value="2">最热</option>
			</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">排序</td>
			<td width="100">游戏ID</td>
			<td>标题</td>
			<td>图标</td>
			<td>大小</td>
			<td>版本号</td>
			<td width="120">下载量</td>
			<td width="120">上线时间</td>
			<td>状态</td>
		</tr>
		<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><?php echo $value['game_id'];?></td>
			<td><?php echo $client_games[$value['game_id']]['name'];?></td>
			<td><img src="<?php echo $client_games[$value['game_id']]['img'];?>" style="width:7.2em;height:7.2em"/></td>
        	<td><?php echo $oline_versions[$value['game_id']]['size'];?>M</td>
        	<td><?php echo $oline_versions[$value['game_id']]['version'];?></td>
        	<td><?php echo $value['downloads'];?></td>
        	<td><?php echo date('Y-m-d H:i:s', $value['online_time']);?></td>
        	<td><?php echo $value['status'] ? '已上线' : '已下线';?></td>
		</tr>
	<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
