
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
    <meta name="viewport" content="width=320.1,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <title>恭喜发财，大吉大利！</title>
    <style>
        body{
            font:normal 14px Tahoma,"Lucida Grande",Verdana,"Microsoft Yahei",STXihei,hei;
            background:#080808;
            background-size:100%;
            color:#353535;
        }
        body,div,a,ul,li,p,span{
            padding:0;
            margin:0;
        }
        a{
            text-decoration:none;
            color:#000;
        }
        .first-box{
            width:81.67%;
            position:absolute;
            left:9.165%;
            top:10%;
        }
        img.body{
            width:100%;
        }
        .user-headimg{
            position: absolute;
            border-radius: 10000px;
            left: 50%;
            top: 9.75%;
            width: 20.65%;
            margin-left: -10.5%;
        }
        .hot-click{
            position: absolute;
            border-radius: 10000px;
            left: 50%;
            top: 61%;
            width: 36%;
            height: 26%;
            margin-left: -18%;
        }
        .nickname{
            width: 100%;
            position: absolute;
            text-align: center;
            color: #FFF;
            top: 28.5%;
            font-size:1.15em;
        }

        .second-box{
            width:100%;
            height:100%;
            position:absolute;
            overflow:hidden;
            top:0;
            left:0;
        }
        .second-wrapper{
            overflow:hidden;
            width:auto;
            position:relative;
        }
        .second-bg{
            width:100%;
        }
        .second-headimg{
            position: absolute;
            border-radius: 10000px;
            left: 50%;
            top: 13%;
            width: 23%;
            margin-left: -11.5%;
        }
        .second-nickname{
            width: 100%;
            position: absolute;
            text-align: center;
            top: 26.8%;
            font-size:1.25em;
        }
        .money{
            position:absolute;
            text-align:center;
            width:100%;
            top:37%;
            color:#000;
        }
        .money-number{
            font-size:4.5em;
            padding-left:0.25em;
        }
        .yuan{
            font-size:1.1em;
            position:relative;
            top:-1px;
        }




        .tips-box{
            position:absolute;
            top:50%;
            width:100%;
            height:100px;
            margin-top:-50px;
            background:#fff;
            overflow:hidden;
            z-index:9999;
            text-align:center;
        }
        .explain{
            font-size:18px;
            padding:5px 8px;
            margin-top:4px;
            margin-bottom:8px;
        }
        .zhenggu-btn{
            background-color:#FE8007;
            color:#fff;
            padding:6px 14px;
            border-radius:3px;
        }
        .bg-cover{
            width:100%;
            height:100%;
            top:0;
            left:0;
            position:fixed;
            background:#000;
            opacity:0.6;
            z-index:999;
        }
    </style>
    <script>
        var _czc = _czc || [];
        _czc.push(["_setAccount", "1254867535"]);
        if(window.location.search.indexOf('from=singlemessage') != -1) {
            _czc.push(["_setCustomVar","访客来源","单聊",2]);
        }
        else if(window.location.search.indexOf('from=groupmessage') != -1) {
            _czc.push(["_setCustomVar","访客来源","群聊",2]);
        }
        else if(window.location.search.indexOf('from=timeline') != -1) {
            _czc.push(["_setCustomVar","访客来源","朋友圈",2]);
        }
        else if(window.location.search.indexOf('from=') != -1) {
            _czc.push(["_setCustomVar","访客来源","其他来路",2]);
        }
        else
        {
            _czc.push(["_setCustomVar","访客来源","没有来路",2]);
        }
        _czc.push(["_trackEvent","红包","查看红包"]);
    </script>
</head>
<body>
<div style="display:none">
    <img src="https://dn-yrjhb.qbox.me/static/images/hongbao_icon.jpg">
</div>


<div class="first-box">
    <img class="body" src="https://dn-yrjhb.qbox.me/static/images/fools_1.png">
    <img class="user-headimg" src="<?php echo $user["headimgurl"];?>">
    <div class="hot-click"></div>
    <div class="nickname"><?php echo $user["nickname"];?></div>
</div>
<div class="second-box" style="display:none">
    <div class="second-wrapper">
        <img class="second-bg" src="https://dn-yrjhb.qbox.me/static/images/fools_2.png">
        <img class="second-headimg" src="<?php echo $user["headimgurl"];?>">
        <div class="second-nickname"><?php echo $user["nickname"];?>的红包</div>
        <div class="money">
            <span class="money-number">88.00</span>
            <span class="yuan">元</span>
        </div>
    </div>
</div>
<div class="tips-box" style="display:none">
    <div class="explain">别看了，没有天上掉下来的馅饼！<br>快去整回别人吧→_→</div>
    <a class="zhenggu-btn" href="http://www.findjoy.cn/front/zheng/index?act=zheng&id=<?php echo $mid;?>">我也要整蛊</a>
</div>
<div class="bg-cover" style="display:none"></div>
<script type="text/javascript" src="https://dn-yrjhb.qbox.me/static/js/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script type="text/javascript">
    var fools_show=function(){
        $(".bg-cover").show();
        $(".tips-box").show();
    };
    $(function(){
        $(".hot-click").click(function(){
            $(".first-box").hide();
            $(".second-box").show();
            var t=setTimeout('fools_show()',1750);
        });
        $(".second-box").click(fools_show);
    });

        wx.ready(function(){
            wx.showOptionMenu();
            wx.hideMenuItems({
                menuList: [
                    'menuItem:readMode',
                    'menuItem:copyUrl',
                    'menuItem:share:qq'
                ]
            });
            wx.onMenuShareAppMessage({
                title: '恭喜发财，岁岁平安！',
                desc: '点击领取红包',
                link: 'http://www.findjoy.cn/front/zheng/index?id=<?php echo $id;?>',
                imgUrl: 'http://lab.h6app.com/static/images/hongbao_icon.jpg'
            });
            wx.onMenuShareTimeline({
                title: '恭喜发财，岁岁平安！',
                desc: '点击领取红包',
                link: 'http://www.findjoy.cn/front/zheng/index?id=<?php echo $id;?>',
                imgUrl: 'http://lab.h6app.com/static/images/hongbao_icon.jpg'
            });
        });
</script>
</body>
</html> 