<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $indexUrl;?>">渠道列表</a></li>
    <li class="current"><a href="javascript:;">添加渠道</a></li>
	</ul>
</div>
<div class="h_a">添加渠道</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">		
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="name" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">上级渠道</th>
			<td class="td">
		<select name="parent">
		<option value="0">顶级渠道</option>
<?php foreach($list as $key => $value) {?>
                <option value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
                <?php foreach($value['items'] as $k=>$item)	{?>
                 <option value="<?php echo $item['id'];?>"><?php echo '|－'.$item['name'];?></option>
<?php }}?>
                </select></td>
		</tr>
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value=""></td>
		</tr>
		
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Channel/index');
	});
})

</script>
<?php echo $this->render("layout/footer.phtml");?>
