<?php echo $this->render("common/navigator.phtml"); ?>

<!-- 导航栏Ajax加载 指向navagator.html  menuOn表示分别需要高亮的菜单栏id 用下划线_隔开 eg:bz_taotu_taotuPack-->
<section class="navigator" menuOn="bz_daily_dailyAdd">

</section>

<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <!-- 页面唯一id标识符  一般情况下id=文件名  eg:bz_admin_taotu02-->
    <div id="bz_operation_daily_add02">
        <!-- 页面内容区域 注意：每个页面无论是否有内容 必定有一个content-->
        <div class="content">
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">名称</label>
                    <div class="tb_cont tb_cell">
                        <input type="text" class="rd_1">
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">标签</label>
                    <div class="tb_cont tb_cell">
                        <div class="select_box">
                            <label class="select_val">标签</label>
                            <ul class="select_option">
                                <li>美女</li>
                                <li>帅哥</li>
                            </ul>
                        </div><!-- select_box -->
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->

            <div class="drag_sort_wrap">
                <div class="drag_sort">
                    <label>已选壁纸</label>
                    <ul class="drag_sort_list" id="dragSortTxt1">
                        <li>壁纸一</li>
                        <li>壁纸二</li>
                        <li>壁纸三</li>
                        <li>壁纸四</li>
                        <li>壁纸五</li>
                        <li>壁纸六</li>
                    </ul>
                </div><!-- drag_sort end -->

                <div class="drag_sort">
                    <label>缩略图</label>
                    <ul class="drag_sort_img" id="dragSortImgPack">
                        <li class="img_list"><img src="image/t_img01.jpg"></li>
                        <li class="img_list"><img src="image/t_img02.jpg"></li>
                        <li class="img_list"><img src="image/t_img03.jpg"></li>
                        <li class="img_list"><img src="image/t_img04.jpg"></li>
                        <li class="img_list"><img src="image/t_img05.jpg"></li>
                        <li class="img_list"><img src="image/t_img06.jpg"></li>
                    </ul>
                </div><!-- drag_sort end -->

                <div class="clear-fix"></div>
            </div><!-- drag_sor_wrap end -->

            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">发布时间</label>
                    <div class="tb_cont tb_cell">
                        <input type="text" class="datepicker rd_2" readonly>
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->

            <div class="bnts_wrap">
                <button class="btn_s2" id="bzDailyAddPrev" ><a href="/Admin/wallpapersets/pubdaily">上一步</a></button>
                <button openPopId="fixTipView" class="btn_s2 pop_btn" id="bzDailyAddSubmit">提交</button></div>

        </div>
        <!-- content end -->
    </div>
</section>

<!-- 弹窗 消息+按钮-->
<div class="pop_wraper" id="fixTipView">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_tip">
                    <p class="tip_mes">提交成功</p>
                    <div class="tip_btns"><button class="btn_s2" id="dailyPopBtnAdd">继续添加</button><button class="btn_s2" id="dailyPopBtnReturn">返回每日精选列表</button></div>
                    <div class="pop_close"></div>
                </div>

            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->
</body>
</html>