<?php echo $this->render("common/navigator.phtml"); ?>

<!-- 导航栏Ajax加载 指向navagator.html  menuOn表示分别需要高亮的菜单栏id 用下划线_隔开 eg:bz_taotu_taotuPack-->
<section class="navigator" menuOn="bz_daily_dailyAdd">

</section>

<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <!-- 页面唯一id标识符  一般情况下id=文件名  eg:bz_admin_taotu02-->
    <div id="bz_operation_daily_add01">
        <!-- 页面内容区域 注意：每个页面无论是否有内容 必定有一个content-->
        <div class="content">
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">一级标签</label>
                    <div class="tb_cont tb_cell">
                        <ul class="tag_list tag_one"><!-- tag_one 一级标签 只能选中一个 -->
                            <li>风景</li>
                            <li>情感</li>
                            <li>简约</li>
                            <li>美女</li>
                            <li>动漫</li>
                            <li>帅哥</li>
                            <li>款式</li>
                        </ul>

                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->

            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">状态</label>
                    <div class="tb_cont tb_cell">
                        <div class="select_box">
                            <label class="select_val">打包时间</label>
                            <ul class="select_option">
                                <li>美女</li>
                                <li>帅哥</li>
                            </ul>
                        </div><!-- select_box -->
                    </div>

                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->

            <!-- 列表模式 -->
            <section class="view view_list show admin_mode" id="viewList">
                <!-- 批量管理内容 默认隐藏 -->
                <div class="view_admin view_list_admin">
                    <!-- checkClass表示 点击后 哪些class要被选中 -->
                    <button class="btn_check btn_check_all" checkClass="btn_check_list"></button><label>全选</label>
                </div>
                <table class="view_list_tb">
                    <thead>
                        <tr><th>壁纸</th><th>名称</th><th>颜色</th><th>标签</th><th>上线次数</th><th>打包时间</th><th>操作</th></tr>
                    </thead>
                    <tbody>
                        <tr><td class="tb_img"><button class="btn_check btn_check_list"></button>
                                <img src="image/test_img01.png"></td><td>趣味生活</td>
                            <td><span class="color_pan"></span>
                                <span class="color_val">#f07804</span></td>
                            <td>风景</td><td>10</td><td>2014-09-17</td>
                            <td><a class="btn_txt" href="bz_operation_daily_add02.html">详情</a> <a class="btn_txt pop_btn" openPopId="fixTipView">删除</a></td></tr>
                        <tr><td class="tb_img"><button class="btn_check btn_check_list"></button><img src="image/test_img02.png"></td><td>趣味生活</td><td><span class="color_pan"></span><span class="color_val">#4b5ff8</span></td><td>风景</td><td>41</td><td>2014-09-17</td><td><a class="btn_txt" href="bz_operation_daily_add02.html">详情</a> <a class="btn_txt pop_btn" openPopId="fixTipView">删除</a></td></tr>
                    </tbody>
                </table>
            </section>

            <div class="bnts_wrap">
                <button class="btn_s2" id="bzDailyAddNext">下一步</button>
            </div>
        </div>
    </div>
</section>



<!-- 弹窗 消息+按钮-->
<div class="pop_wraper" id="fixTipView">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_tip">
                    <p class="tip_mes">是否删除<span>特仑苏</span></p>
                    <div class="tip_btns"><button class="btn_s2">确定</button><button class="btn_s2 btnCancel">取消</button></div>
                    <div class="pop_close"></div>
                </div>

            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->

</body>
</html>