
<div class="novel-header" >
	<a href="/index.html" class="i-title">阅读</a>
	<!--<a href="/index.html" class="logo"></a>-->
	<a href="/search/" class="i-search" stat="cid_sousuo" w="sousuo"></a>
</div><!-- novel-header end -->
<div class="novel-tabs clearfix">
	<ul>
		<li><a href="/index.html" stat="1" w="front_index">热门</a></li>
		<li><a href="/ranking.html" stat="2" w="front_ranking">排行</a></li>
		<li class="on"><a href="/category.html" stat="3" w="front_category">分类</a></li>
		<li id="bookTips"><a href="/bookshelf.html" stat="4" w="front_bookshelf">书架</a></li>
	</ul>
</div><!-- novel-tabs end -->

<div class="novel-content">
	<div class="novel-mod">
		<div class="hd">分类小说</div>
		<div class="bd">
			<div class="novel-elist clearfix">
				<ul>
					<li><a href="//category/3.html" stat="9" w="b_flxs_flsx">都市言情</a></li>
					<li><a href="//category/8.html" stat="14" w="b_flxs_flsx">总裁豪门</a></li>
					<li><a href="//category/1.html" stat="7" w="b_flxs_flsx">玄幻奇幻</a></li>
					<li><a href="//category/7.html" stat="13" w="b_flxs_flsx">穿越时空</a></li>
					<li><a href="//category/6.html" stat="12" w="b_flxs_flsx">古代言情</a></li>
					<li><a href="//category/4.html" stat="10" w="b_flxs_flsx">军事历史</a></li>
					<li><a href="//category/2.html" stat="8" w="b_flxs_flsx">武侠仙侠</a></li>
					<li><a href="//category/10.html" stat="16" w="b_flxs_flsx">悬疑灵异</a></li>
					<li><a href="//category/9.html" stat="15" w="b_flxs_flsx">耽美同人</a></li>
					<li><a href="//category/5.html" stat="11" w="b_flxs_flsx">科幻游戏</a></li>
				</ul>
			</div>
		</div>
	</div>


	<div class="novel-mod">
		<div class="hd">分类漫画</div>
		<div class="bd">
			<div class="novel-elist clearfix">
				<ul>
					<li><a href="/manhua/category/2.html" stat="71" w="b_flxs_mh">四格漫画</a></li>
					<li><a href="/manhua/category/3.html" stat="72" w="b_flxs_mh">绘本漫画</a></li>
					<li><a href="/manhua/category/1.html" stat="73" w="b_flxs_mh">故事漫画</a></li>
					<li><a href="" stat="74" w="b_flxs_mh"></a></li>
				</ul>
			</div>
		</div>
	</div>


</div><!-- novel-content end -->
