
<div class="novel-header" >
	<a href="/index.html" class="i-title">阅读</a>
	<!--<a href="/index.html" class="logo"></a>-->
	<a href="/search/" class="i-search" stat="cid_sousuo" w="sousuo"></a>
</div><!-- novel-header end -->
<div class="novel-tabs clearfix">
	<ul>
		<li><a href="/index.html" stat="1" w="front_index">热门</a></li>
		<li class="on"><a href="/ranking.html" stat="2" w="front_ranking">排行</a></li>
		<li><a href="/category.html" stat="3" w="front_category">分类</a></li>
		<li id="bookTips"><a href="/bookshelf.html" stat="4" w="front_bookshelf">书架</a></li>
	</ul>
</div><!-- novel-tabs end -->

<div class="novel-content">
	<div class="novel-tab novel-tab-2 clearfix">
		<ul>
			<li class="on">小说热搜榜</li>
			<li >动漫热搜榜</li>
		</ul>
	</div>

	<div class="novel-dlist" >
		<dl id="0">
			<a  href="/detail/13667.html" stat="734" w="排行榜"><dt><img src="http://dh3.kimg.cn/kimg/mbook/cover/20141105/13667_8289162.jpg_180x250.jpg?q=50&mode=1" /><i>1</i></dt>
				<dd>
					<p><strong>一吻成瘾</strong></p>
					<p><span>纳兰海映</span><i>|</i><span>都市言情</span></p>
					<p>原书名《一夜缠情：女人，要定你！》在充满了暧昧，浪漫气息的伦敦，那一夜，她做了一次大胆热辣的女人。
						　　【成年了吗？】他玩味的眼神审读着她，不沾染未成年，这是他的底线。
						　　原本以为一辈子不会再有交集的两个人，在她回国后，他们再一次相遇：
						　　她耍手段，玩阴谋，肆无忌惮的惹怒他，不知收敛，最后，才知道自己惹不起他。
						　　【一千万，这些钱，够玩你一次吧！】他步步紧逼着她，熟悉的味道，熟悉的温度，熟悉的心跳，一切都在不停的勾出伦敦一夜的回忆。
						　　她是他玩过的女人，可这一辈子，他想玩的女人却只有她一</p>
					<p><span class="green">已完结</span>174万字</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/966.html" stat="782" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/966_4538807.jpg_180x250.jpg?q=50&mode=1" /><i>2</i></dt>
				<dd>
					<p><strong>总裁宠妻百分百</strong></p>
					<p><span>无墨兮</span><i>|</i><span>总裁豪门</span></p>
					<p>送个外卖而已，被霸道男人粗暴占有，事后竟大言不惭的让她去买避孕药。
						想忘记那些耻辱的画面，再也不要看见那个瘟神，可总裁大人偏偏阴魂不散的找上门来。
						高高在上的总裁大人也会遭遇催婚，干脆把小丫头娶回来好好调教。
						可是，这丫头简直就是制造麻烦的专业户。放下几千亿的生意给她善后不说，还要陪着她一起丢人现眼。苍天啊！
						咦！这是神马情况？小丫头竟然桃花连连，送情书的、送玫瑰的，还有送房产证求婚的……愁的总裁大人要吐血了！神啊！那是我的私宠小娇妻，谁都不许染指！</p>
					<p><span class="blue">连载中</span>更新于2015-05-19</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/94.html" stat="827" w="排行榜"><dt><img src="http://dh3.kimg.cn/kimg/mbook/cover/20140926/94_9048577.jpg_180x250.jpg?q=50&mode=1" /><i>3</i></dt>
				<dd>
					<p><strong>浅婚深爱</strong></p>
					<p><span>陌上迟归</span><i>|</i><span>总裁豪门</span></p>
					<p>一次醉酒，从此她和某只狐狸结缘！还没来得急落荒而逃，却被带着去见证男友劈腿。“现在我们可以来谈谈结婚的事了吧？”“禽兽！啊！呜……”可这还没结婚呢，各路女人轮番来抢！栽赃，陷害，无所不用其极……幸得他护她周全宠她上天……</p>
					<p><span class="blue">连载中</span>更新于2015-06-23</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/4985.html" stat="828" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/4985_2157293.jpg_180x250.jpg?q=50&mode=1" /><i>4</i></dt>
				<dd>
					<p><strong>绝色校草霸道爱</strong></p>
					<p><span>流水微微</span><i>|</i><span>总裁豪门</span></p>
					<p>指腹为婚？男扮女装？多么戏剧的词汇，却是那么真实地在萧沐雪的身上上演了。
						在好友的威胁下参加了文艺社。不过……这个人就是社长？
						本来是一个让她有些敬畏的人，没有想到……她明明就是男儿打扮，这个人竟然会告白，一定是她在做梦。
						一味的想要逃避的人却没有想到她怎么逃都是逃不掉的，本来待人疏远的人竟然也化身霸道男一心在她的身上。
						最后才发现…… 巧合无处不在……</p>
					<p><span class="green">已完结</span>24万字</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/5147.html" stat="829" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/5147_3058443.jpg_180x250.jpg?q=50&mode=1" /><i>5</i></dt>
				<dd>
					<p><strong>与狼同眠：危险总裁宠娇妻</strong></p>
					<p><span>风流砖头</span><i>|</i><span>总裁豪门</span></p>
					<p>好不容易当了次好人，本以为可以趁机狠狠敲诈一笔，没想到她一毛钱都没拿到，还要陪吃陪喝陪人陪笑陪睡觉！
						大灰狼总裁不动声色巧立名目步步为营。小白兔学生迷迷糊糊一步一步钻进陷阱。
						他将她拆吃入腹，她还一脸懵懂：你到底是喜欢我啊还是喜欢我啊还是喜欢我啊……</p>
					<p><span class="green">已完结</span>43万字</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/79.html" stat="861" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/79_8812438.jpg_180x250.jpg?q=50&mode=1" /><i>6</i></dt>
				<dd>
					<p><strong>村医</strong></p>
					<p><span>书海扬帆</span><i>|</i><span>都市言情</span></p>
					<p>左手古武右手医术，李小乐成为美女贴身神医，搅动风云。他武逆乾坤，敌人胆寒；他神医妙手，庸医低头；他笑傲世界，名利双收。看极品村医如何纵横乡野逍遥都市，平步青云畅游花丛……
						每天稳定更新，求收藏推荐、订阅打赏、月票书评。新建书群214621989，欢迎交流。</p>
					<p><span class="blue">连载中</span>更新于2014-12-15</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/17833.html" stat="862" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/static/images/public/upload/20150410/6ccd6dcab7f840c5d2cc65e913d105a4.jpg_180x250.jpg?q=50&mode=1" /><i>7</i></dt>
				<dd>
					<p><strong>御天神帝</strong></p>
					<p><span>乱世狂刀</span><i>|</i><span>玄幻奇幻</span></p>
					<p>乱世狂刀，热血新作</p>
					<p><span class="blue">连载中</span>更新于2015-06-22</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/24.html" stat="873" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/24_2791127.jpg_180x250.jpg?q=50&mode=1" /><i>8</i></dt>
				<dd>
					<p><strong>极品杀手房东</strong></p>
					<p><span>星辰羽</span><i>|</i><span>都市言情</span></p>
					<p>回归都市的秦风发现自家房子住进了两个美女，阴差阳错下他开始了一条被彪悍的新生活，他发誓要多买几栋房子，然后多养几个女房客，以包租公的身份走上人生巅峰.....</p>
					<p><span class="blue">连载中</span>更新于2015-05-31</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/374.html" stat="874" w="排行榜"><dt><img src="http://dh3.kimg.cn/kimg/mbook/cover/20140926/374_9538698.jpg_180x250.jpg?q=50&mode=1" /><i>9</i></dt>
				<dd>
					<p><strong>我的女神</strong></p>
					<p><span>周行文</span><i>|</i><span>都市言情</span></p>
					<p>女神天降，岁月悠长。人生路上想有知己，想要红颜，想得到许多关注的目光，也想留更多欢声笑语。
						可否此心换彼心？
						少年，一路向前去验证吧。
						（QQ群：281811087，女神的石榴裙）</p>
					<p><span class="green">已完结</span>328万字</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/757.html" stat="877" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/757_1411291.jpg_180x250.jpg?q=50&mode=1" /><i>10</i></dt>
				<dd>
					<p><strong>大荒蛮神</strong></p>
					<p><span>更俗</span><i>|</i><span>玄幻奇幻</span></p>
					<p>地球少年持魔尊传承降临异界，任蛮为亲，以神为骨，吞九幽噬阴阳，武霸蛮荒！修圣武，锻神体，上斩诸神屠万佛，逆掌万界我为皇！
						【更俗的书迷世界，俗人部落第一千人群：385122373】</p>
					<p><span class="blue">连载中</span>更新于2015-06-22</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/633.html" stat="749" w="排行榜"><dt><img src="http://dh3.kimg.cn/kimg/mbook/cover/20140926/633_7346165.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>九阳踏天</strong></p>
					<p><span>食堂包子</span><i>|</i><span>玄幻奇幻</span></p>
					<p>世间修炼，灵肉两极。
						灵者灵魂，操纵天地元力，感悟大道规则！
						肉者体魄，淬炼血肉筋骨，融合血脉传承！
						世人修炼，皆为有朝一日，能够至高无上，踏临九天！
						而当灵魂足够强大，便需无坚不摧的强大肉身作为祭台，点燃那永不消亡的火焰……</p>
					<p><span class="blue">连载中</span>更新于2015-06-23</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/12471.html" stat="815" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/mbook/cover/20141105/12471_1759326.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>特种教师</strong></p>
					<p><span>黑暗崛起</span><i>|</i><span>都市言情</span></p>
					<p>男儿两行泪，一行为苍生，一行为美人……
						　　★★★★★★★★★★★★★★★★★★本文走轻松路线，仅供娱乐休闲阅读，好事者、卫道士请绕道！</p>
					<p><span class="blue">连载中</span>更新于2015-06-23</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/12587.html" stat="822" w="排行榜"><dt><img src="http://dh2.kimg.cn/kimg/mbook/cover/20141112/59215e7e1f459c6ec476fbecfbea41e6.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>总裁一吻好羞羞</strong></p>
					<p><span>我是木木</span><i>|</i><span>都市言情</span></p>
					<p>原名《天才宝宝上阵：腹黑总裁乖乖听话》：http://www.cmread.com/bookDetail?bid=371943766移动和阅读3.5亿点击，畅销总榜前10作品！
						　　↓豪门一夜，她卖身给一个陌生人，但是万万没想到……她竟然上错床？床上是一个帅到外星球的暴戾男！
						　　她只好将错就错，把他“吃光”后果断携款潜逃！
						　　最终还是逃不过他布下的天罗地网，而他除了捞到了那个日思夜想的嚣张女人外，竟然还被免费附送一对天才宝宝！
						　　什么？那是我儿子和女儿？！</p>
					<p><span class="green">已完结</span>247万字</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/14928.html" stat="823" w="排行榜"><dt><img src="http://dh2.kimg.cn/kimg/mbook/cover/20141105/14928_9498907.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>妻妾成群</strong></p>
					<p><span>东门吹牛</span><i>|</i><span>军事历史</span></p>
					<p>简介：明末清初，秦淮八艳，满蒙美女，东瀛尤物粉墨登场！
						　　************************************************新书《九五至尊》。《妻妾成群》《大唐寻芳谱》都已完本。
						　　************************************************新书与妻妾有些关系，可以看做前传，也可以看做续集，也是独立成书的新故事************************************************鲜花，收藏请给新书！谢谢！读</p>
					<p><span class="green">已完结</span>286万字</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/17375.html" stat="871" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/mbook/cover/20141211/17375_5471119.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>毒步天下：腹黑世子妃</strong></p>
					<p><span>月下绵绵</span><i>|</i><span>古代言情</span></p>
					<p>重生前，她软弱娇憨，却落得个，儿子惨死，她被挖心的凄惨下场。
						重生后，她披着软萌妹纸的皮囊，表面上对谁都温柔善良，暗地里却狠戾凶残，再不受半分凄凉。
						重生前，她视爱成命，却是爱错了人，死不瞑目。
						重生后，冷酷战神视她为掌中宝，眼中最好，以天下为聘，只为换她一颗真心，而她，却已是无心之人。</p>
					<p><span class="blue">连载中</span>更新于2015-06-23</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/17493.html" stat="872" w="排行榜"><dt><img src="http://dh3.kimg.cn/kimg/mbook/cover/20150112/17493_8944038.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>豪门追婚令</strong></p>
					<p><span>草草酱</span><i>|</i><span>总裁豪门</span></p>
					<p>逼婚？堂堂的景总居然逼婚到她家指名要娶她？阿喂，她不就是不小心‘整’了你一顿么？至于报复心这么强？可是这个混蛋居然告诉她只是找不到人结婚，还打算一路缠她到底！</p>
					<p><span class="blue">连载中</span>更新于2015-04-06</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/12067.html" stat="755" w="排行榜"><dt><img src="http://dh2.kimg.cn/kimg/mbook/cover/20141212/121d0569e21435b7396399dea54eb914.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>承少独宠：试婚99天</strong></p>
					<p><span>墨春花</span><i>|</i><span>总裁豪门</span></p>
					<p>他是江南省的新晋权贵，拥有雄厚的家世，显赫的BEI景。而她，身份不堪到了极点。他们，一个在天，一个在地。他不请自来，作为她的丈夫，带着天价聘礼。她冷静应对，以不变应万变。
						“你该是知道我的身份。”“知道。”“那你还要娶我？”“要娶。”“叶特助，你有病。”“试婚99天。你若满意，这辈子凑合过了。你若不满，离婚便是。”
						不是不知道他打着什么鬼主意，但她还是坚定的丢下一个字。
						“嫁！”什么试婚99天，不过是一笔交易，各取所需，等价交换罢了。</p>
					<p><span class="blue">连载中</span>更新于2015-03-24</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/13865.html" stat="763" w="排行榜"><dt><img src="http://dh2.kimg.cn/kimg/mbook/cover/20141105/13865_7894980.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>掠爱：错惹冷情王爷</strong></p>
					<p><span>端木诺晴</span><i>|</i><span>都市言情</span></p>
					<p>【原名：《掠爱：错上王爷榻》】她与他是奉子成婚，却在新婚第二天便被他蹂躏小产。本想求的一片清净，却被诬陷为杀人凶手深陷牢狱。面对危机四伏的处境，她小心谨慎，步步为营……
						　　身为王爷的他，明知她的出嫁是宰相府的精心布局，但冰冷的心还在一点点沦陷。面对权势的争夺，注定他们一个是棋子，一个是执棋的人，纵使升起万般情愫，也只能掩盖在水深火热的争斗中，显的冰冷无情……
						　　明明是错，却要一错到底。当一切以怨恨开始，又将以什么终结？
						　　所谓爱，不过是一场掠夺……
						　　【昊与染画的故事至卷七末完结，卷八讲楚</p>
					<p><span class="green">已完结</span>172万字</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/15998.html" stat="742" w="排行榜"><dt><img src="http://dh3.kimg.cn/kimg/mbook/cover/20141105/15998_4068268.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>幸孕：冷枭的契约情人</strong></p>
					<p><span>忆江</span><i>|</i><span>都市言情</span></p>
					<p>孪生姐妹，一个是养尊处优的公主，一个是流落他乡的灰姑娘。灰姑娘终于翻身做了公主，却是代其坠入地狱！
						　　他，堂堂帝国的总裁，黑白两道闻风丧胆的枭雄，在整个亚洲要风得风要雨得雨。拥有一张天妒俊颜的他，身边从来不缺女人。
						　　一纸契约，十八岁她作为姐姐的替代品成了他的情人，一再的忍让和退步，只换来他更残忍的羞辱和践踏。
						　　他，拥有无数FANS的天皇巨星，心里却只喜欢邻家小妹清纯如水的她。在相见，她已妖娆风情为人情妇，重重误会下，能否拨开迷雾。
						　　开新文了，期待支持啊《婚久情深，爱上夺心妻》http</p>
					<p><span class="green">已完结</span>117万字</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/1980.html" stat="864" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/1980_7240170.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>无病阔少</strong></p>
					<p><span>忆见</span><i>|</i><span>总裁豪门</span></p>
					<p>一场“奇特”的闹剧，猎奇旺盛的他抓住一只狡猾的“新宠”
						鬼魅妖孽的男人，恰恰利用她特殊的职业，试图“登峰造极”
						自那以后，闹剧频频……
						一个真护理，一个假病人，却是互相设计，百般刁难。
						当狡猾女护理碰上妖孽少总裁，笑料频出的一对活宝，却被命运屡次捉弄。
						父女二人齐上阵，丫头发誓，一定抢回我的彪悍“后妈”
						ps：较量，从未止步！</p>
					<p><span class="green">已完结</span>44万字</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/17738.html" stat="865" w="排行榜"><dt><img src="http://dh3.kimg.cn/kimg/mbook/cover/20150312/17738_4796220.png_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>终极护美</strong></p>
					<p><span>落雨辰</span><i>|</i><span>都市言情</span></p>
					<p>混沌强者转世，神秘天族少主天宸被无良老头收为徒，派出执行一个保护妹子的任务…在香艳护美的路上，各路美女纷纷拥怀！然而，随着前世记忆的恢复，各大隐匿势力也开始缓缓浮出…【本文纯属小白文，不喜请勿喷】本书书友群： 250478182</p>
					<p><span class="blue">连载中</span>更新于2015-06-22</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/174.html" stat="866" w="排行榜"><dt><img src="http://dh2.kimg.cn/kimg/mbook/cover/20140926/174_7689358.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>霉运阴阳眼</strong></p>
					<p><span>司徒北</span><i>|</i><span>都市言情</span></p>
					<p>一个每天见鬼的家伙，被无数的灵魂所骚扰，希望张坤能帮他们完成未了的心愿，医生，护士，国术高手，赌王……，当一个一个灵魂找来的时候，张坤该何去何从？尽自己的力量，以一个17岁少年的身份去完成那些灵魂所未完成的事情，还是置之不顾，任凭骚扰？
						张坤忍不住扶头悲痛的道：“不要再来了，呜呜……！”（四鬼出品，必属精品，四鬼阁欢迎大家，群号：107606139）</p>
					<p><span class="blue">连载中</span>更新于2015-06-23</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/790.html" stat="867" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/790_6540000.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>秘密保镖</strong></p>
					<p><span>楚国太傅</span><i>|</i><span>都市言情</span></p>
					<p>三年前，他是杀手界的超级王牌，只手遮天，叱咤风云！
						三年后，他褪去荣光，华丽转身，成为保镖，于是，关于秘密保镖的传奇就开始了！</p>
					<p><span class="blue">连载中</span>更新于2015-06-22</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/667.html" stat="868" w="排行榜"><dt><img src="http://dh2.kimg.cn/kimg/mbook/cover/20140926/667_6645953.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>傲世九界</strong></p>
					<p><span>煜刖</span><i>|</i><span>玄幻奇幻</span></p>
					<p>巧得《九天玄塔》图，穿行玄天九界。丈道而行，历经万难找回失去记忆寻回自我，踏上九天强者之路。
						罗天：“三天之下尽皆凡尘，吾便仗剑三天让众仙归尘！九幽冥界肆虐苍生，吾便诛尽魔神！九钥齐聚，吾便要看看这九天之上到底有何隐秘！”
						书群： 77739743</p>
					<p><span class="blue">连载中</span>更新于2015-06-23</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/157.html" stat="869" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/157_2548186.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>仙魔同修</strong></p>
					<p><span>化十</span><i>|</i><span>玄幻奇幻</span></p>
					<p>误碰太古之器，普通少年林昊穿越至修行界，修至尊古体，获混沌本源，夺天地造化，炼万古天罡，铸就无上仙识……</p>
					<p><span class="blue">连载中</span>更新于2015-06-23</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/708.html" stat="875" w="排行榜"><dt><img src="http://dh2.kimg.cn/kimg/mbook/cover/20140926/708_5797739.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>兽血沸腾2</strong></p>
					<p><span>静官</span><i>|</i><span>玄幻奇幻</span></p>
					<p>胡高带着某人的灵魂碎片一起穿越了！
						这里兽族沉睡，人类觉醒图腾之力统治大陆！
						兽血再次沸腾，新的征程起航！
						欢迎大家加我微信：直接搜索静官即可。
						兽血沸腾纵横群号164667428答案纵横书友
						静官粉丝营架势堂群号323955687需投过月票或粉丝级达到弟子以上书友输入纵横ID验证后加入</p>
					<p><span class="blue">连载中</span>更新于2015-06-23</p>
				</dd></a>
		</dl>
		<dl id="0">
			<a  href="/detail/17737.html" stat="876" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg/mbook/cover/20150312/17737_5798955.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>我捉鬼的那几年</strong></p>
					<p><span>踏步云巅</span><i>|</i><span>悬疑灵异</span></p>
					<p>午夜十二点，千万不要在高速路上行走，因为，冤死的魂魄正在那里等待。
						火葬场里面的恐怖身影，医院太平间内的离奇死亡，这背后，到底隐藏着什么?
						风水秘术的争斗，各种不同的道法传承，尽在我捉鬼的那几年……
						（新书改名为我捉鬼的那几年，还请大家多多支持）</p>
					<p><span class="blue">连载中</span>更新于2015-04-24</p>
				</dd></a>
		</dl>
	</div>
	<div class="novel-dlist" style="display:none;">
		<dl id="1">
			<a  href="/manhua/detail/984.html" stat="582" w="排行榜"><dt><img src="http://dh2.kimg.cn/kimg//static/images/public/manhua/2014/1226/4e5393b2fea8b340abfeab2d0653536b.jpg_180x250.jpg?q=50&mode=1" /><i>1</i></dt>
				<dd>
					<p><strong>噬规者</strong></p>
					<p><span>张国鹏/陈诚</span><i>|</i><span>故事漫画</span></p>
					<p>原本是普通人类的警察雷恩，因为一次事件机缘巧合而获得了“天瞳”能力。从此，他对原来世界的认知受到了极大的颠覆与冲击。追求梦想与正义，不惜与这个世界的规则对抗，气势磅礴的奇幻少年漫画，将带你进入一个全新的世界！</p>
					<p><span class="blue">连载中</span>更新于2015-06-22</p>
				</dd></a>
		</dl>
		<dl id="1">
			<a  href="/manhua/detail/1002.html" stat="578" w="排行榜"><dt><img src="http://dh3.kimg.cn/kimg//static/images/public/manhua/2015/0204/8521fcd90a7ed229c92e8e13dc324b4f.jpg_180x250.jpg?q=50&mode=1" /><i>2</i></dt>
				<dd>
					<p><strong>黑瞳</strong></p>
					<p><span>兔B</span><i>|</i><span>故事漫画</span></p>
					<p>恐怖降临，死亡大门敞开……
						警告：不要盯着“黑瞳”看太长时间，否则一切后果自负！！
						警告：——胆小者勿看——
						注：此作品不会追求太恐怖的东西，点到为止，希望大家都能接受！谢谢！！
						断指魔2（201106）</p>
					<p><span class="blue">连载中</span>更新于2015-06-17</p>
				</dd></a>
		</dl>
		<dl id="1">
			<a  href="/manhua/detail/365.html" stat="583" w="排行榜"><dt><img src="http://dh2.kimg.cn/kimg//static/images/public/manhua/2014/1226/ab1ce0623887241867117729464f9215.jpg_180x250.jpg?q=50&mode=1" /><i>3</i></dt>
				<dd>
					<p><strong>端脑</strong></p>
					<p><span>壁水羽</span><i>|</i><span>故事漫画</span></p>
					<p>《端脑》简介：端脑是什么？如果从字面意思来讲，端脑就是由左右两个大脑组成的生物器官。在这部故事里，它用来描述由对冲宇宙构成的庞大系统，我们叫它端脑宇宙，故事从一个个未知的杀人案开始，逐步揭开掩藏在整个宇宙中的巨大秘密，从骇人听闻的阴谋，到银河系战争，从反人类的背叛到伟大的牺牲，人类从来未曾了解自己是如此的落后，如此的弱小，她将对自己的命运做出最后的一搏。</p>
					<p><span class="blue">连载中</span>更新于2015-06-17</p>
				</dd></a>
		</dl>
		<dl id="1">
			<a  href="/manhua/detail/912.html" stat="586" w="排行榜"><dt><img src="http://dh3.kimg.cn/kimg//static/images/public/manhua/2014/1226/804203c5a2382f2f31f7968f8ef88318.jpg_180x250.jpg?q=50&mode=1" /><i>4</i></dt>
				<dd>
					<p><strong>无视者</strong></p>
					<p><span>壁水羽</span><i>|</i><span>故事漫画</span></p>
					<p>你看得见我，但你感知不到我</p>
					<p><span class="blue">连载中</span>更新于2015-06-23</p>
				</dd></a>
		</dl>
		<dl id="1">
			<a  href="/manhua/detail/369.html" stat="585" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg//static/images/public/manhua/2014/1226/ae713de13861dc1da2a390c0749fa8c0.jpg_180x250.jpg?q=50&mode=1" /><i>5</i></dt>
				<dd>
					<p><strong>MTJJ多格杂集</strong></p>
					<p><span>mtjj</span><i>|</i><span>四格多格</span></p>
					<p>那些乱七八糟的事儿~</p>
					<p><span class="blue">连载中</span>更新于2015-01-27</p>
				</dd></a>
		</dl>
		<dl id="1">
			<a  href="/manhua/detail/1001.html" stat="581" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg//static/images/public/manhua/2015/0204/63ddb8a7caafa89e8c29543f47eab7b1.jpg_180x250.jpg?q=50&mode=1" /><i>6</i></dt>
				<dd>
					<p><strong>日渐崩坏的世界</strong></p>
					<p><span>大叔酱</span><i>|</i><span>故事漫画</span></p>
					<p>这是一部爆笑恐怖漫画，请谨慎观看，配合吐槽食用更佳。</p>
					<p><span class="blue">连载中</span>更新于2015-06-20</p>
				</dd></a>
		</dl>
		<dl id="1">
			<a  href="/manhua/detail/101.html" stat="635" w="排行榜"><dt><img src="http://dh3.kimg.cn/kimg//static/images/public/manhua/2014/1226/472c6b24ba0f926ef5a65c6486142946.jpg_180x250.jpg?q=50&mode=1" /><i>7</i></dt>
				<dd>
					<p><strong>镇魂街</strong></p>
					<p><span>许辰</span><i>|</i><span>故事漫画</span></p>
					<p>镇魂街，此乃吸纳亡灵镇压恶灵之地。这是一个人灵共存的世界，但不是每个人都能进入镇魂街，只有拥有守护灵的寄灵人才可进入。夏铃原本是一名普通的大学实习生，但一次偶然导致她的人生从此不再平凡。。。在这个充满恶灵的世界，你能与你的守护灵携手生存下去吗？</p>
					<p><span class="blue">连载中</span>更新于2015-06-22</p>
				</dd></a>
		</dl>
		<dl id="1">
			<a  href="/manhua/detail/711.html" stat="580" w="排行榜"><dt><img src="http://dh3.kimg.cn/kimg//static/images/public/manhua/2014/1226/7b6eedb79a85a05fc45c97d814755a24.jpg_180x250.jpg?q=50&mode=1" /><i>8</i></dt>
				<dd>
					<p><strong>那年那兔那些事儿</strong></p>
					<p><span>黯花儿</span><i>|</i><span>绘本</span></p>
					<p>俏兔子大战傻贼鹰！没有吐槽，没有搞笑，没有历史带入，没有对号入座，完全毁三观，请谨慎观赏。作者：-逆光飞行- 首发：微漫画、超级大本营、飞扬军事  。</p>
					<p><span class="blue">连载中</span>更新于2015-06-13</p>
				</dd></a>
		</dl>
		<dl id="1">
			<a  href="/manhua/detail/761.html" stat="577" w="排行榜"><dt><img src="http://dh1.kimg.cn/kimg//static/images/public/manhua/2014/1226/01aada574770f7c7d6e409f019b44ad0.jpg_180x250.jpg?q=50&mode=1" /><i>9</i></dt>
				<dd>
					<p><strong>白象的军备大茶几</strong></p>
					<p><span>左手王ZSW</span><i>|</i><span>绘本</span></p>
					<p>该来不来十余年的维氏航母，待字闺中三十载的光辉姬，耗资巨多的巨囧靶车阿琼坦克，以及空壳一个恶意卖萌的歼敌者黑鱼......印度白象家的军备可以用一个词来形容：茶几←_←</p>
					<p><span class="blue">连载中</span>更新于2015-05-21</p>
				</dd></a>
		</dl>
		<dl id="1">
			<a  href="/manhua/detail/996.html" stat="621" w="排行榜"><dt><img src="http://dh3.kimg.cn/kimg//static/images/public/manhua/2014/1226/3af563a2abe18667069cf769b62e8630.jpg_180x250.jpg?q=50&mode=1" /><i>10</i></dt>
				<dd>
					<p><strong>日常幻想指南</strong></p>
					<p><span>漫天星mstars</span><i>|</i><span>四格多格</span></p>
					<p>大家知道，妄想症这种病吗？如果一觉醒来，身边的一切事物，都变成了美少年的模样，你会觉得这样的人生很美好吗？才怪呢！身患此病并饱受折磨的的屌丝漫画家阿栓，在绝望的人生中，遇到了搬到隔壁的怪异邻居……？？</p>
					<p><span class="blue">连载中</span>更新于2015-06-23</p>
				</dd></a>
		</dl>
		<dl id="1">
			<a  href="/manhua/detail/2.html" stat="622" w="排行榜"><dt><img src="http://dh2.kimg.cn/kimg//static/images/public/manhua/2014/1226/86ac303ad022e445c43425ad3fa392f1.jpg_180x250.jpg?q=50&mode=1" /></dt>
				<dd>
					<p><strong>雏蜂</strong></p>
					<p><span>白猫sunny</span><i>|</i><span>故事漫画</span></p>
					<p>公元XX年 新一代的军备竞争开始，“尖兵”作为一种新型的武器开始广泛的运用在军事纷争中。女主角琉璃是马上退役的尖兵。在她最后的380天里她接到了最后的任务。。。。。 官方微博：@雏蜂官网 http://weibo.com/u/3756609373</p>
					<p><span class="blue">连载中</span>更新于2015-06-22</p>
				</dd></a>
		</dl>
	</div>

</div><!-- novel-content end -->
