<?php echo $this->render("layout/header2.phtml"); ?>
	<section class="main-content">
		<form method="post" action="<?php echo $editPostUrl; ?>" id="editForm">
			<header class="header navbar bg-default">
				<ul class="nav navbar-nav">
					<li class="active">
						<a href="#">功能机页面配置</a>
					</li>
				</ul>
				<div class="btn-group pull-right mg-r-sm">
					<button type="submit" class="btn btn-sm btn-primary navbar-btn">
						提 交
					</button>
					<a href="#" class="btn btn-sm btn-default navbar-btn">
						预览
					</a>
				</div>
			</header>
			<div class="content-wrap">
				<div class="row">
					<div class="col-lg-12">
						<!-- table content start -->
						<section class="panel">
							<input name="token" id="token" value="<?php echo $token; ?>" type="hidden"/>
							<textarea name="gionee_machine" style="width: 100%; height: 400px;"><?php echo $gionee_machine; ?></textarea>
						</section>
					</div>
				</div>
			</div>
		</form>
	</section>
	<script src="<?php echo $staticPath; ?>/js/admin/kindeditor/kindeditor.js"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			var editor;
			KindEditor.ready(function (K) {
				K.token = $('#token').val();
				editor = K.create('textarea[name="gionee_machine"]', {
					resizeType: 1,
					allowPreviewEmoticons: false,
					allowImageUpload: true,
					uploadJson: '<?php echo $uploadImgUrl;?>',
					items: EDITOR_ITEMS
				});
			});

			ajaxForm('editForm', function (ret) {
				ajaxRedirect(ret, baseurl + '/Admin/Machine/index');
			}, function () {
				editor.sync();
			});
		})
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>