<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">频道内容列表</a></li>
    <li class="current"><a href="javascript:;">编辑频道内容</a></li>
	</ul>
</div>
<div class="h_a">编辑频道内容</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">标题</th>
			<td class="td"><textarea class="textarea wc" name="title"><?php echo $info['title'];?></textarea></td>
		</tr>
		<tr class="tr">
			<th class="th">链接地址</th>
			<td class="td"><input type="text" class="input wc" name="link" value="<?php echo $info['link'];?>"></td>
		</tr>
		<tr class="tr">
		<th class="th">所属频道</th>
			<td class="td"><select name="channel_id">
<?php 
foreach($channels as $key => $value) {
?>
                <option <?php echo $info['channel_id'] == $value['id']? 'selected="selected"' : '';?> value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
<?php 
}
?>
	            </select></td>
		</tr>
		<tr class="tr">
			<th class="th">统计到</th>
			<td class="td"><select name="click_type">
<?php 
foreach($typelist as $key => $value) {
?>
                <option <?php echo $info['click_type'] == $value['id']? 'selected="selected"' : '';?> value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
                <?php
			     $i = 0;
	             foreach($value['items'] as $k=>$item)
				{?>
                 <option  <?php echo $info['click_type'] == $item['id']? 'selected="selected"' : '';?> value="<?php echo $item['id'];?>"><?php echo '&nbsp;&nbsp;&nbsp;&nbsp;'.$item['name'];?></option>
                <?php }?>
<?php 
}
?>
            </select></td>
		</tr>
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="<?php echo $info['sort'];?>">（填写一个数字，数字越大越靠前）</td>
		</tr>
		<tr class="tr">
			<th class="th">开始结束时间</th>
			<td class="td"><div><input class="input" type="text" style="width:143px;" id="start_time" name="start_time" value="<?php echo date('Y-m-d H:i:s', $info['start_time']);?>" /> 至 <input class="input" type="text" style="width:143px;" id="end_time" name="end_time" value="<?php echo date('Y-m-d H:i:s', $info['end_time']);?>" /></div>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td"><select name="status" min-width="100px">
                	<option <?php if($info['status'] == 1) echo 'selected="selected"';?> value="1">开启</option>
                	<option <?php if($info['status'] == 0) echo 'selected="selected"';?>value="0">关闭</option>
            </select></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Channelcontent/index');
	});
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
