<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">频道内容列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加频道内容</a></li>
	</ul>
</div>

<form action="<?php echo $listUrl;?>" method="post">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">频道</th>
				<td class="td">
				<select name="channel_id">
				<option value="">所有频道</option>
<?php 
foreach($channels as $key => $value) {
?>
                <option <?php echo ($param['channel_id'] == $key)? 'selected="selected"' : '';?> value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
<?php 
}
?>
	            </select>
				</td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button type="submit">搜 索</button></span></span>
	</div>

</form>

<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">排序</td>
			<td>标题</td>
			<td width="100">频道</td>
			<td width="120">开始时间</td>
			<td width="120">结束时间</td>
			<td width="60">状态</td>
			<td width="100">操作</td>
		</tr>
<?php foreach($channelcontents as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><?php echo $channels[$value['channel_id']]['name'];?></td>
		    <td><?php echo date('Y-m-d H:i:s', $value['start_time']);?></td>
		    <td><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
			<td><?php echo $value['status'] == 1 ? '开启' : '关闭';?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
