<?php echo $this->render("layout/header.phtml");?>
    <div class="table_full">
        <form action="<?php echo $indexUrl;?>" method="POST">
            <input type="hidden" name="token" value="<?php echo $token;?>" />
            <table width="100%" cellspacing="0" cellpadding="0">
                <tr class="tr1">
                    <td class="td1">
                        选择日期：
                        <select name="quick" id="quick">
                            <?php
                            $monthSelect = $quick == 'month' ? ' selected' : '';
                            $quarterSelect = $quick == 'quarter' ? ' selected' : '';
                            ?>
                            <option value="week">最近一周</option>
                            <option value="month"<?php echo $monthSelect;?>>最近一月</option>
                            <option value="quarter"<?php echo $quarterSelect;?>>最近三月</option>
                        </select>
                        <input class="input" type="text" id="sdate" maxlength="30" name="sdate" value="<?php echo $sdate;?>"> 至
                        <input class="input" type="text" id="edate" maxlength="30" name="edate" value="<?php echo $edate;?>">
                        <span class="btn"><span><button type="submit">生成报表</button></span></span>
                        <span class="btn"><span><button type="button" onclick="downloadOrder();">下载</button></span></span>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <form action="<?php echo $downloadUrl;?>" method="post" id="DownloadForm" >
        <input name="token" type="hidden" value="<?php echo $token;?>"/>
        <input type="hidden" name="sdate" value="<?php echo $sdate;?>">
        <input type="hidden" name="edate" value="<?php echo $edate;?>">
    </form>
    <div class="h_a">数据报表</div>
    <input type="hidden" id="lineData" value="<?php echo $lineData;?>" />
    <input type="hidden" id="listUrl" value="<?php echo $indexUrl;?>" />
    <table width="100%" cellspacing="0" cellpadding="0">
        <tr class="tr1">
            <td class="td2">
                <div id="container" style="height: 400px; margin: 0 auto"></div>
            </td>
        </tr>
    </table>
    <div class="h_a">其他数据</div>
    <table width="100%" cellspacing="0" cellpadding="0">
        <tr class="ct">
            <td class="td"><?php echo $nickname_stat['name'];?></td>
            <td class="td"><?php echo $nickname_stat['stat'];?></td>
        </tr>
        <tr class="ct">
            <td class="td"><?php echo $avatar_stat['name'];?></td>
            <td class="td"><?php echo $avatar_stat['stat'];?></td>
        </tr>
    </table>

    <script src="<?php echo $staticPath;?>/js/admin/highcharts.js"></script>
    <script src="<?php echo $staticPath;?>/js/admin/exporting.js"></script>
    <script src="<?php echo $staticPath;?>/js/admin/stat.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            var yesterday = "<?php echo $yesterday;?>";
            var weekday = "<?php echo $weekday;?>";
            var monthday = "<?php echo $monthday;?>";
            var threemonth = "<?php echo $threemonth;?>";
            $("#sdate").datepicker({
                dateFormat : 'yy-mm-dd'
            });
            $("#edate").datepicker({
                dateFormat : 'yy-mm-dd'
            });
            $('#app').bind('change', function(){
                var app = $(this).val();
                window.location.href = $('#listUrl').val() + 'app=' + app;
            });
            $('#quick').bind('change',function(){
                var selectDate = $(this).val();
                console.log($('#listUrl').val());
                if (selectDate == 'week') {
                    window.location.href = $('#listUrl').val() + '/?sdate=' + weekday + '&edate=' + yesterday + '&quick=week';
                } else if (selectDate == 'month') {
                    window.location.href = $('#listUrl').val() + '/?sdate=' + monthday + '&edate=' + yesterday + '&quick=month';
                } else if (selectDate == 'quarter') {
                    window.location.href = $('#listUrl').val() + '/?sdate=' + threemonth + '&edate=' + yesterday + '&quick=quarter';
                }
            });
            $('#quick').bind('change',function(){
                var selectDate = $(this).val();
            });
            if ($('#lineData').val()) {
                var lineData = '<?php echo $lineData;?>';
                draw(eval('('+lineData+')'), '问答统计', 'Num/Date');
            }
        })

        function downloadOrder(){
            $('#DownloadForm').submit();
        }

    </script>
<?php echo $this->render("layout/footer.phtml");?>