<script type="text/javascript">
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?0405d1a68dae612416258f53465d3ede";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
<div class="copyright">
		<p>增值电信许可证:<a href="<?php echo $staticResPath; ?>/pic/1.jpg" target="_blank">粤B2-20120350</a></p>
		<p>Copyright © 2014 <a target="_blank" href="http://www.miitbeian.gov.cn/">粤ICP备05087105号</a></p>
		<p>网络文化经营许可证:<a href="<?php echo $staticResPath; ?>/pic/2.jpg" target="_blank">粤网文[2013]029-029号</a></p>
</div>
