<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">push消息列表</a></li>
	<li><a href="<?php echo $addUrl;?>">添加push消息</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">编号</td>
			<td  width="200">标题</td>
			<td>内容</td>
			<td width="200">添加时间</td>
			<td width="120">操作</td>
		</tr>
<?php foreach($msgs as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><?php echo $value['content'];?></td>
			<td><?php echo date('Y-m-d H:i:s',$value['create_time']);?></td>
			<td>
			<a href="<?php echo $pushstepUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">发送</a>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
