<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">频道列表</a></li>
    <li class="current"><a href="javascript:;">编辑频道</a></li>
	</ul>
</div>
<div class="h_a">编辑频道</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input wc" name="name" value="<?php echo $info['name'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">链接地址</th>
			<td class="td"><input type="text" class="input wc" name="link" value="<?php echo $info['link'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">统计到</th>
			<td class="td"><select name="click_type">
<?php 
foreach($typelist as $key => $value) {
?>
                <option <?php echo $info['click_type'] == $value['id']? 'selected="selected"' : '';?> value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
                <?php
			     $i = 0;
	             foreach($value['items'] as $k=>$item)
				{?>
                 <option  <?php echo $info['click_type'] == $item['id']? 'selected="selected"' : '';?> value="<?php echo $item['id'];?>"><?php echo '&nbsp;&nbsp;&nbsp;&nbsp;'.$item['name'];?></option>
                <?php }?>
<?php 
}
?>
            </select></td>
		</tr>
		<tr class="tr">
			<th class="th">图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="IndexchannelImg">
						<img src="<?php echo $attachPath.$info['img'];?>"/>
						<input type="hidden" name="img" value="<?php echo $info['img'];?>">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=IndexchannelImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="<?php echo $info['sort'];?>">（填写一个数字，数字越大越靠前）</td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td"><select name="status" min-width="100px">
                	<option <?php if($info['status'] == 1) echo 'selected="selected"';?> value="1">开启</option>
                	<option <?php if($info['status'] == 0) echo 'selected="selected"';?>value="0">关闭</option>
            </select></td>
		</tr>
		<tr class="tr">
				<th class="th">是否随机显示</th>
				<td class="td">
				<input type="hidden" name="is_rand" id="is_rand" value="<?php echo $info['is_rand'];?>"/>
				<input type="checkbox" onclick="if(this.checked){$('#is_rand').val(1);}else{$('#is_rand').val(0);}"
					<?php echo $info['is_rand'] == 1 ? 'checked="checked"' : '';?> >(选中表示设置为随机显示)</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Indexchannel/index');
	});
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
