<script src="<?php echo $staticRoot;?>/sys/lib/zepto/zepto-1.1.6.js?t=<?php echo $version;?>"></script>
<script src="<?php echo $staticRoot;?>/sys/lib/underscore/underscore.js?t=<?php echo $version;?>"></script>
<script src="<?php echo $staticRoot;?>/sys/lib/backbone/backbone-1.1.2.js?t=<?php echo $version;?>"></script>
<script src="<?php echo $staticRoot;?>/sys/lib/requirejs/require.js?t=<?php echo $version;?>"></script>
<script src="<?php echo $staticRoot;?>/apps/findjoy/assets/js/web.js?t=<?php echo $version;?>"></script>

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?b71f6d1a879de92694179b3e4c36a530";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

