<script type="text/javascript">
   var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
   document.write(unescape("%3Cscript async src='"+ _bdhmProtocol + "stats.gionee.com/stats/g.js%3F0F383847972EECB5' type='text/javascript'%3E%3C/script%3E"));
</script>
<?php 
$baidu_tj = Gou_Service_Config::getValue('gou_baidu_stat');
if($baidu_tj) {
?>
<script type="text/javascript">
	var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
	document.write(unescape("%3Cscript async src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F725967d6ad7b02063cb567595bf04f27' type='text/javascript'%3E%3C/script%3E"));
</script>
<?php }?>

<!-- cnzz -->
<?php 
function _cnzzTrackPageView($siteId) {
    $cs = new Util_Cnzz($siteId);
    return $cs->trackPageView();
}
echo '<img src="'._cnzzTrackPageView(1253692327).'" style="display:none" width="0" height="0"/>';
?>