<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl.'?type='.$type;?>">全部游戏</a></li>
    <?php if ($type == 2) {?>
    <li style="display: none;"><a href="<?php echo $step1Url.'?type='.$type;?>">添加游戏</a></li>
    <?php }?>
	</ul>
</div>
<form action="<?php echo $listUrl.'?type='.$type;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>"/>
<input name="type" type="hidden" value="<?php echo !$params['type'] ? $type : $params['type'];?>"/>
<div class="table_full">
	<table width="100%">
	   <tr class="tr">
			<th class="th">分类</th>
			<td class="td" colspan="3">
			 <?php foreach($categorys as $key=>$value) {?>
			 <?php if($value['editable'] != 1) {?>
			 <label class="mr20"><input type="checkbox" <?php if (in_array($value['id'], $params['category'])) echo 'checked';?> name="category[]" value="<?php echo $value['id'];?>"><?php echo $value['title'];?></label>
			 <?php }}?>
		    </td>
		</tr>
		<tr class="tr">
		    <th class="th">状态</th>
			<td class="td">
			<select name="status" class="select wa">
			    <option value="0">全部</option>
				<option <?php if($params['status'] == 2) echo 'selected';?> value="2">已上线</option>
				<option <?php if($params['status'] == 1) echo 'selected';?> value="1">已下线</option>
			</select>
			</td>
			<th class="th">关键字</th>
			<td class="td">
			<input type="text" class="input " name="name" value="<?php echo $params['name'];?>">
		    </td>
	    </tr>
	    <tr class="tr">
			<th class="th">开发者账号</th>
			<td class="td">
			<input type="text" class="input " name="company" value="<?php echo $params['company'];?>">
		    </td>
		    <th class="th">游戏ID</th>
			<td class="td">
			<input type="text" class="input" name="id" value="<?php echo $params['id'];?>">
		    </td>
		</tr>
		 <tr class="tr">
			<th class="th">合作方式</th>
			<td class="td">
			<select name="cooperate" class="select wa">
			    <option value="0">全部</option>
				<option <?php if($params['cooperate'] == 2) echo 'selected';?> value="2">普通</option>
				<option <?php if($params['cooperate'] == 1) echo 'selected';?> value="1">联运</option>
			</select>
		    </td>
		    <th class="th">APPID</th>
			<td class="td">
			<input type="text" class="input" name="appid" value="<?php echo $params['appid'];?>">
		    </td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="h_a">
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="80">游戏ID</td>
			<td width="80">APPID</td>
			<td>标题</td>
			<td>图标</td>
			<?php if ($type >= 1) {?>
			<td width="80">开发者账号</td>
			<?php }?>
			<?php if ($type == 2) {?>
			<td>评级</td>
			<?php }?>
			<td>包名</td>
			<td>上线时间</td>
			<td>状态</td>
			<td>版本数量</td>
			<td>线上/最新</td>
			<?php if ($type >= 1) {?>
			<td>版本管理</td>
			<?php }?>
			<?php if ($type == 2) {?>
			<td>管理</td>
			<?php }?>
		</tr>
<?php foreach($games as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['appid'];?></td>
			<td><a target="blank" href="<?php echo $frontroot . '/client/index/detail/?id=',$value['id'].'&preview=true';?>"><?php echo $value['name']; ?></a></td>
			<td><img src="<?php echo $value['img'];?>" style="width:7.2em;height:7.2em"/></td>
			<?php if ($type >= 1) {?>
			<td><?php echo $value['company'];?></td>
			<?php } ?>
			<?php if ($type == 2) {?>
			<td><?php echo $game_level[$value['id']] ? $game_level[$value['id']]: '无';?></td>
			<?php } ?>
			<td><?php echo $value['package'];?></td>
			<td><?php echo  date('Y-m-d H:i:s', $value['online_time']);?></td>
			<td><?php echo $value['status'] ? '已上线' : '已下线';?></td>
			<td><?php echo $versions[$value['id']]['num'];?></td>
			<td><?php echo $online_versions[$value['id']]['version'].'/'.$new_versions[$value['id']]['version'];?></td>
			<?php if ($type >= 1) {?>
			<td><a href="<?php echo $step2editUrl;?>/?id=<?php echo $value['id'];?>&type=<?php echo $type;?>" class="mr10">版本管理</a></td>
			<?php }?>
			<?php if ($type == 2) {?>
			<td>
			<a href="<?php echo $step5Url;?>/?id=<?php echo $value['id'];?>&type=<?php echo $type;?>" class="mr10">管理</a>
			<a style="display: none;" href="<?php echo $step1editUrl;?>/?id=<?php echo $value['id'];?>&type=<?php echo $type;?>" class="mr10">编辑</a>
			<a  style="display: none;" href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
			<?php }?>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
