<!DOCTYPE html>
<html lang="en">
<head>
	<?php $this->title="功略详情";$this->hasSearch="true"; ?>
	<meta charset="UTF-8">
	<title>金立游戏大厅</title>
	<?php echo $this->render("layout/cssInc.phtml");?>
</head>
<body>
	<?php echo $this->render("layout/header.phtml");?>
	<div id="container"></div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
<?php echo $this->render("layout/scriptInc.phtml"); ?>
<script type="text/javascript">
	var rankingData = {
		name:'<?=$strategyInfo['name']?>'
		,original:'<?=$strategyInfo['fromto']?>'
		,date:'<?=date('Y-m-d', $strategyInfo['create_time'])?>'
		,href:'<?php echo $strategyInfo['fromto']?Common::tjurl($tjUrl, $strategyInfo['id'], $intersrc, 'http://wap.fwan.cn/info/infos/'.$strategyInfo['out_id'].'.shtml'):'';?>'
		,info:'<?=html_entity_decode($strategyInfo['content']);?>'
	};
	React.render(
		React.createElement(Article, {items: rankingData})
	  , document.getElementById('container')
	);
</script>
<?php echo $this->render("layout/lastscriptInc.phtml"); ?>
</html>