<?php echo $this->render("../../Front/views/layout/header.phtml");?>
<section id="page">
	<!-- 主体内容 -->
	<section id="content">
		<section class="order">
			<section class="order-detail">
				<ul class="mod-text-list">
					<li>
						<dl class="mod-dl-list top-dl-list">
							<dd>实付款：<?php echo $order['real_price'];?>元（使用银币<span class="zt-orange"><?php echo $order['silver_coin'];?></span>元）</dd>
							<dd>订单号：<span class="J_orderNo" data-tradeNo="<?php echo $order['out_trade_no'];?>" data-tradeUrl="<?php echo $webroot,'/user/account/order_detail?id=',$order['id'];?>" data-payUrl="<?php echo $webroot.'/order/pay';?>"><?php echo $order['trade_no'];?></span></dd>
							<dd>状态：
							 <?php if($order['iscash'] == 1){?>
							   货到付款
							 <?php } else {?>
							   <?php echo Gc_Service_Order::orderStatus($order['status']); ?>
							 <?php }?>
							</dd>
							<dd>成交时间：<?php echo date('Y-m-d H:i:s', $order['create_time']);?></dd>
							<dd>付款时间：<?php echo ($order['pay_time'] == 0 ? '' : date('Y-m-d H:i:s', $order['pay_time']));?></dd>
						</dl>
					</li>
					<li>
						<ul class="mod-tw-list">
							<li><img src="<?php echo $attachPath . $goods['img'];?>" alt="" /></li>
							<li>
								<dl>
									<dd><?php echo $goods['title'];?></dd>
									<dd>单价：<span><?php echo $goods['price'];?></span>元</dd>
									<dd>数量：<?php echo $order['number'];?></dd>
								</dl>
							</li>
						</ul>
						<p>实际支付：<?php echo $order['real_price'];?>元（使用<span class="zt-orange"><?php echo $order['silver_coin'];?></span>元银币）</p>
					</li>
					<li>
						<dl class="mod-dl-list">
							<dd>收货人：<?php echo $address['buyer_name'];?></dd>
							<dd>手机号：<?php echo $address['mobile'];?></dd>
							<dd>收货地址：<?php echo $address['country'],$address['province'],$address['city'],$address['detail_address'];?></dd>
							<dd>邮编：<?php echo $address['postcode'];?></dd>
						</dl>
					</li>
				</ul>
				<nav class="button">
				    <a href="<?php echo $webroot.'/about/';?>">
						<span>联系我们</span>
					</a>
					<?php if($order['status'] == 1 && $order['iscash'] == 2){?>
					<a id="J_goToPay" href="javascript:;">
						<span>立即付款</span>
					</a>
					<?php } ?>
				</nav>
			</section>
		</section>
	</section>
	<!--  /主体内容 -->
	<footer id="footer"><!-- FOOTER --></footer>
</section>
</body>
</html>