<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">广告位2列表</a></li>
    <li class="current"><a href="javascript:;">广告位2</a></li>
	</ul>
</div>
<div class="h_a">编辑广告位2</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
	<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="<?php echo $info['sort'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">标题</th>
			<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title'];?>"></td>
		</tr>
		<tr class="tr" style="display:none">
			<th class="th">分类</th>
			<td class="td">
				<select name="ad_ptype">
<?php foreach($ad_ptypes as $key=>$value) { ?>
					<option value="<?php echo $key;?>" <?php if($info['ad_ptype'] == $key) echo 'selected="selected"';?>><?php echo $value;?></option>
<?php }?>
				</select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">链接类型</th>
			<td class="td">
				<label class="mr20"><input <?php if($info['ad_ptype'] == 1) echo 'checked';?> name="ad_ptype"  value="1" type="radio">内容</label>
				<label class="mr20"><input <?php if($info['ad_ptype'] == 2) echo 'checked';?> name="ad_ptype"  value="2" type="radio">分类</label>
				<label class="mr20"><input <?php if($info['ad_ptype'] == 3) echo 'checked';?> name="ad_ptype"  value="3" type="radio">专题</label>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">链接ID</th>
			<td class="td"><input type="text" name="link" class="input" value="<?php echo $info['link'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg">
						<img src="<?php echo $attachPath.$info['img'];?>"/>
						<input type="hidden" name="img" value="<?php echo $info['img'];?>">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">开始结束时间</th>
			<td class="td"><div><input class="input" type="text" style="width:143px;" id="start_time" name="start_time" value="<?php echo date('Y-m-d H:i:s', $info['start_time']);?>" /> 至 <input class="input" type="text" style="width:143px;" id="end_time" name="end_time" value="<?php echo date('Y-m-d H:i:s', $info['end_time']);?>" /></div>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td"><select name="status" min-width="100px">
                	<option <?php if($info['status'] == 1) echo 'selected="selected"';?> value="1">开启</option>
                	<option <?php if($info['status'] == 0) echo 'selected="selected"';?>value="0">关闭</option>
            </select></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Ad_Public/index');
	});
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
