<?php echo $this->render("layout/header3.phtml"); ?>

	<div data-options="region:'center',split:true,border:false" style="overflow: hidden;">

		<div id="datagrid_toolbar" style="padding:5px;">
			<div style="float: left;">

			</div>
			<div align="left">
				<a href="#" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="add()">新增</a>
				<span class="toolbar-btn-separator"></span>
				<a href="#" class="easyui-linkbutton" iconCls="icon-edit" plain="true" onclick="edit()">编辑</a>
				<span class="toolbar-btn-separator"></span>
				<a href="#" class="easyui-linkbutton" iconCls="icon-remove" plain="true" onclick="del()">删除</a>
				<block name="button"></block>
				<a href="#"></a>
			</div>
		</div>
		<table id="datagrid" toolbar="#datagrid_toolbar" border="false"></table>
	</div>


	<script>
		var token = "<?php echo $token;?>";
		var edit_W = 500;
		var edit_H = 400;
		var datagrid;
		$(function () {
			//数据列表
			datagrid = $("#datagrid").datagrid({
				url: '<?php echo $commandUrl;?>',
				queryParams: {'togrid': 1, 'token': token},
				fit: true,
				autoRowHeight: false, //自动行高
				border: false,
				pagination: true, //分页栏
				pagePosition: 'bottom', //分页栏位置
				rownumbers: true,//显示行数
				striped: true,//显示条纹
				showFooter: true, //显示统计行
				pageSize: 20,//每页记录数
				remoteSort: true,//是否通过远程服务器对数据排序
				singleSelect: false,//只允许选择单行
				// main content

				sortName: 'id',//默认排序字段
				sortOrder: 'asc',//默认排序方式 'desc' 'asc'
				idField: 'id',
				columns: [[
					{field: 'id', title: 'ID', sortable: false, align: 'center', width: 60},
					{field: 'key', title: '名称', sortable: false, width: 100},
					{field: 'val', title: '内容', sortable: false, width: 200},
					{field: 'type', title: '类型', sortable: false, width: 60},
					{field: 'status', title: '状态', sortable: false, width: 60},
					{field: 'created_at', title: '建立时间', sortable: false, align: 'center', width: 120},
					{field: 'updated_at', title: '更新时间', sortable: false, align: 'center', width: 120},
				]],

				onLoadSuccess: function () {
					$(this).datagrid('clearSelections');//取消所有的已选择项
					$(this).datagrid('unselectAll');//取消全选按钮为全选状态
				},
				onRowContextMenu: function (e, rowIndex, rowData) {
					e.preventDefault();
					$(this).datagrid('unselectAll');
					$(this).datagrid('selectRow', rowIndex);
					$('#datagrid_menu').menu('show', {
						left: e.pageX,
						top: e.pageY
					});
				},
				onDblClickRow: function (rowIndex, rowData) {
					edit(rowIndex, rowData);
				}
			});

		});


		function add() {
			addData("添加", "#edit_form", datagrid, "<?php echo $commandeditUrl;?>", edit_W, edit_H);
		}
		function edit(rowIndex, rowData) {
			editData(rowIndex, rowData, "编辑", '#edit_form', datagrid, "<?php echo $commandeditUrl;?>", edit_W, edit_H, 'id');
		}
		function del() {
			delData(datagrid, "<?php echo $commanddelUrl;?>");
		}
	</script>
<?php echo $this->render("layout/footer3.phtml"); ?>