<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>感恩回馈 VIP豪礼专享</title>
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="format-detection" content="email=no" />
	<link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/events/rebate/assets/css/main.css?v=<?php echo $version;?>" />
	<link rel="shortcut icon" href="<?php echo $staticroot; ?>/apps/game/web/images/favicon.ico?v=<?php echo $version;?>" type="image/x-icon">
</head>
<body id="vip-page">
	<div class="header">
		<div class="head_3"></div>
		<div class="head_4"></div>
	</div>
	<div class="main">
		<div class="vipSstate-container">
			<div class="vip-title">
				<h1>VIP充值用户&nbsp;&nbsp;&nbsp;一路陪伴&nbsp;&nbsp;&nbsp;感谢有你</h1>
			</div>
			<p>
				本次感恩回馈是针对金立游戏大厅月消费top10的玩家。消费排名第
				一的玩家获赠金立elifeS5.1，全球最薄智能手机一部。消费排名二到十
				的玩家分别获赠金立V188手机一部。感谢支持，回馈有礼。
			</p>
		</div>
		<div class="top1-container">
		</div>
		<div class="top2To10-container"></div>
		<div class="thanks-container">
			<div class="info">
				<h1>感恩回馈活动后续会每月进行，敬请期待！</h1>
				<p>发奖说明：</p>
				<p>我们会在返利活动结束后7天内联系用户进行实物奖励的发放。</p>
			</div>
		</div>
		<div class="vipBtn-container">
			<a href="<?php echo Common::monTjurl($webroot.'/game/Festival_Ggj/tj', 'http://game.gionee.com/subject/detail/?id=224', 'GGJ_SUBJECT_VIPMORE');?>&t_bi=<?php echo $source;?>" target="_blank" class="btn-vip">
				更多精彩返利活动
			</a>
		</div>
	</div>
	
	<div class="footer">
		<div class="info">
			<p>客服电话：<?php echo $servicePhone; ?></p>
			<p>客服QQ：<?php echo $serviceQq; ?></p>
		</div>
		<span class="copyright">本次活动最终解释权归金立游戏大厅所有</span>
	</div>
</body>
</html>