<?php echo $this->render("../../Front/views/layout/header.phtml");?>
<div id="page">
		<header class="hd">
			<h1>兑奖</h1>
			<div class="back">
				<a href="<?php echo $webroot?>/user/index/signin"><span class="left-arrow"><i></i></span></a>
			</div>
		</header>
		
		<article class="ac">
			<div class="congrats">
				<h3>恭喜你！</h3>
				<p>你获得<?php echo $prize['name'];?>！！！</p>
				<p>请完善您的个人信息，方便给您颁发奖品！</p>
				<!-- <p>建议：您的人品已经激增100，快去买彩票吧，说不定大奖正等着你呢!</p> -->
			</div>
			<div class="form-box wprize">
				<ul>
					<li>
						姓名：<?php echo $user_info['realname']?>
					</li>
					<li>
						手机：<?php echo $user_info['mobile']?>
					</li>
					<li>
						QQ：	<?php echo $user_info['qq']?>
					</li>
					<li>
						地址：<?php echo $user_info['address']?>
					</li>
					<li><input type="submit" name="submit" value="提交" class="btn" /></li>
				</ul>
			</div>
		</article>
	</div>

<?php echo $this->render("../../Front/views/layout/footer.phtml");?>