<?php echo $this->render("layout/header.phtml");?>
	<div id="page">
		<header class="hd">
			<h1>常见问题</h1>
			<div class="back">
				<a href="<?php echo $webroot?>/services/questions"><span class="left-arrow"><i></i></span></a>
			</div>
		</header>
		
		<article class="ac">
			<div class="qa-item">
				<h2><?php echo $question['question'];?></h2>
				<p>回复：<?php echo html_entity_decode($question['answer']);?></p>
			</div>
		</article>
	</div>
<?php echo $this->render("layout/tj.phtml");?>
<?php echo $this->render("layout/footer.phtml");?>
