<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl;?>">评论列表</a></li>
		<li class="current"><a href="javascript:;">编辑评论</a></li>
	</ul>
</div>
<div class="h_a">编辑评论</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">UID</th>
				<td class="td"><input type="text" class="input wc" name="uid" value="<?php echo $info['uid'];?>"></td>
			</tr>
            <tr class="tr">
                <th class="th">内容</th>
                <td class="td"><textarea name="content" cols="87" rows="3"><?php echo html_entity_decode($info['content']); ?></textarea></td>
            </tr>
            <tr class="tr">
                <th class="th">原始内容</th>
                <td class="td"><textarea name="old_content" cols="87" rows="3"><?php echo html_entity_decode($info['old_content']); ?></textarea></td>
            </tr>
            <tr class="tr">
                <th class="th">状态</th>
                <td class="td"><select name="status" class="select">
                    <option <?php if($info['status'] == 1) echo 'selected="selected"';?> value="1">已审核</option>
                    <option <?php if($info['status'] == 0) echo 'selected="selected"';?> value="0">未审核</option>
                </select></td>
            </tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Comment/index?s=1');
	});
})

</script>
<?php echo $this->render("layout/footer.phtml");?>