<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li class="current"><a href="<?php echo $listUrl; ?>">闪屏列表</a></li>
		<li><a href="<?php echo $addUrl; ?>">添加闪屏</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td>闪屏标题</td>
			<td>闪屏图片</td>
			<td width="100">闪屏版本</td>
			<td width="120">开始时间</td>
			<td width="120">结束时间</td>
			<td width="100">闪屏状态</td>
			<td width="100">闪屏操作</td>
		</tr>
		<?php foreach ($splashs as $key => $value) { ?>
			<tr class="ct">
				<td><?php echo $value['title']; ?></td>
				<td><img src="<?php echo $attachPath . $value['img_url']; ?>" style="width:200px"/></td>
				<td><?php echo $value['version']; ?></td>
				<td><?php echo date('Y-m-d H:i:s', $value['start_time']); ?></td>
				<td><?php echo date('Y-m-d H:i:s', $value['end_time']); ?></td>
				<td><?php echo $value['status'] == 1 ? '开启' : '关闭'; ?></td>
				<td>
					<a href="<?php echo $editUrl; ?>/?id=<?php echo $value['id']; ?>" class="mr10">编辑</a>
					<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
				</td>
			</tr>
		<?php } ?>
	</table>
</div>
<div class="mr10 cc">
	<?php echo $pager; ?>
</div>
<?php echo $this->render("layout/footer.phtml"); ?>
