<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
    <ul class="cc">
        <li class="current"><a href="<?php echo $indexUrl;?>">回复列表</a></li>
        <li><a href="<?php echo $addUrl;?>">添加回复</a></li>
    </ul>
</div>
<form action="<?php echo $indexUrl;?>" method="get" id="searchForm" >
    <input name="token" type="hidden" value="<?php echo $token;?>"/>
    <div class="table_full">
        <table width="100%">
            <tr class="tr">
                <th class="th">问题</th>
                <td class="td">
                    <input type="text" name="name" value="<?php echo $search['name']; ?>"/>
                </td>
                <th class="th">答案</th>
                <td class="td">
                    <input type="text" name="answer" value="<?php echo $search['answer']; ?>"/>
                </td>
                <th class="th">状态</th>
                <td class="td">
                    <select name="status">
                        <option value=-1 <?php echo $search['status']==-1?'selected=selected':''; ?>>不限</option>
                        <option value=0  <?php echo $search['status']==0?' selected=selected':''; ?>>无效</option>
                        <option value=1  <?php echo $search['status']==1?' selected=selected':''; ?>>有效</option>
                    </select>
                </td>
            </tr>
        </table>
    </div>
    <div class="mb10 tac">
		<span class="btn">
			<span>
				<button type="submit">搜 索</button>
			</span>
		</span>
    </div>
</form>
<div class="table_list">
    <table width="100%">
        <tr class="hd">
            <td width="30">排序</td>
            <td width="30">ID</td>
            <td width="30">是否有效</td>
            <td width="320">问题</td>
            <td>答案</td>
            <td width="90">操作</td>
        </tr>
        <?php foreach($data as $key => $value) {?>
            <tr class="ct">
                <td><?php echo $value['sort']; ?></td>
                <td><?php echo $value['id']; ?></td>
                <td><?php echo $value['status']?'是':'否'; ?></td>
                <td><?php echo $value['name']; ?></td>
                <td><?php echo $value['answer']; ?></td>
                <td>
                    <a href="<?php echo $editUrl; ?>/?id=<?php echo $value['id']; ?>" class="mr10">编辑</a>
                    <a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>
<div class="mr10 cc">
    <?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
