<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    	<li class=""><a href="<?php echo $listUrl;?>">软件列表</a></li>
    	<li class="current"><a href="<?php echo $addUrl;?>">添加软件</a></li>
	</ul>
</div>
<div class="h_a">添加软件</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr" id="category">
				<th class="th">软件包名称</th>
				<td class="td"><input type="text" class="input wc" name="package" value=""> 例如：com.taobao.taobao</td>
			</tr>
			<tr class="tr" id="category">
				<th class="th">APK名称</th>
				<td class="td"><input type="text" class="input wc" name="apk" value=""> 例如：taobao.apk</td>
			</tr>
			<tr class="tr" id="category">
				<th class="th">版本号</th>
				<td class="td"><input type="text" class="input wc" name="version" value=""></td>
			</tr>
			<tr class="tr" id="category">
				<th class="th">md5</th>
				<td class="td"><input type="text" class="input wc" name="apk_md5" value=""></td>
			</tr>
			<tr class="tr" id="category">
				<th class="th">下载地址</th>
				<td class="td"><input type="text" class="input wc" name="download_url" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td"><select name="status">
                	<option value="1">开启</option>
                	<option value="0">关闭</option>
            </select></td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Marketsoft/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>