<?php echo $this->render("layout/header2.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="javascript:;">添加合辑或图片</a></li>
	</ul>
</div>
<div class="h_a">添加游戏合辑或图片</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="day_id" value="<?php echo $day_id;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">推荐方式(<span style="color: red">*</span>)</th>
			<td class="td">
			<select name="rec_type" class="input">
			<option value="0">合集</option>
			<option value="1">图片</option>
    		</select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">标题(<span style="color: red">*</span>)</th>
			<td class="td"><input type="text" class="input wc" name="title" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">描述</th>
			<td class="td"><textarea rows="3" cols="30" class="input" name="content"></textarea></td>
		</tr>
	</table>
</div>
<div class="mb10 tac">
    <span class="btn"><span><a href="<?php echo $listEditUrl.'?day_id='.date('Y-m-d', $day_id);?>"><button type="button">返回</button></a></span></span>
    <span class="btn"><span><button onfocus="blur();" type="submit">下一步</button></span></span>
</div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	 $('#start_time').datetimepicker({
         timeFormat: "hh:00:00",
         dateFormat: "yy-mm-dd"
     });
     $('#end_time').datetimepicker({
         timeFormat: "hh:00:00",
         dateFormat: "yy-mm-dd"
     });
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $gamesUrl . "?id=";?>' + ret.data);
	});
});
</script>
<?php echo $this->render("layout/footer.phtml");?>
