<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li class="current"><a href="<?php echo $listUrl; ?>">机型列表</a></li>
		<li><a href="<?php echo $editUrl."?type={$type}"; ?>">添加机型</a></li>
	</ul>
</div>
<div class="table_list">


	<div class="nav">
			<table width="100%">
				<tbody>
				<tr class="tr">
					<th class="th" style="width: 40px;">系列</th>
					<td>
						<select id="specType" name="specType" onchange="setType(this.value)">
							<option value="">选择机型系列</option>
							<?php
							foreach ($types as $val) {
								if ($v['type'] == '预置机型') {
									continue;
								}
								$selected = ($val['type'] == $type) ? ' selected ' :'';
								echo "<option value=\"{$val['type']}\" {$selected}>{$val['type']}</option>";
							}
							?>
						</select>
					</td>
				</tr>
				</tbody>
			</table>

	</div>


	<table width="100%">
		<tr class="hd">
			<td width="40">ID</td>
			<td width="200">名称</td>
			<td width="120">操作</td>
		</tr>
		<?php foreach ($list as $key => $value) { ?>
			<tr class="ct">
				<td><?php echo $value['id']; ?></td>
				<td><?php echo $value['name']; ?></td>
				<td>
					<?php //if ($key != 0): ?>
					<a href="<?php echo $editUrl; ?>/?id=<?php echo $value['id']; ?>" class="mr10">编辑</a>
					<a href="javascript:" onclick="deleteOne('<?php echo $delUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
					<?php //endif; ?>
				</td>
			</tr>
		<?php } ?>
	</table>
</div>
<script>
	setType = function(id) {
		window.location.href = "<?php echo $listUrl . '/?type='; ?>"+id;
	}
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
