<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li class="current"><a href="<?php echo $initUrl; ?>">预置机型列表</a></li>
		<li><a href="<?php echo $editUrl; ?>">添加机型</a></li>
	</ul>
</div>
<div class="table_list">

	<table width="100%">
		<tr class="hd">
			<td width="40">ID</td>
			<td width="200">名称</td>
			<td width="120">操作</td>
		</tr>
		<?php foreach ($list as $key => $value) { ?>
			<tr class="ct">
				<td><?php echo $value['id']; ?></td>
				<td><?php echo $value['name']; ?></td>
				<td>
					<?php //if ($key != 0): ?>
					<a href="<?php echo $editUrl; ?>/?id=<?php echo $value['id']; ?>" class="mr10">下载链接编辑</a>
					<a href="javascript:" onclick="deleteOne('<?php echo $delUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
					<?php //endif; ?>
				</td>
			</tr>
		<?php } ?>
	</table>
</div>

<?php echo $this->render("layout/footer.phtml"); ?>
