<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class=""><a href="<?php echo $indexUrl; ?>">分类列表</a></li>
			<li class=""><a href="<?php echo $catAddUrl; ?>">添加分类</a></li>
			<li class="current"><a href="<?php echo $contentsUrl; ?>">内容列表</a></li>
			<li class=""><a href="<?php echo $addContentUrl; ?>">添加内容</a></li>
			<li><a href="<?php echo $importUrl; ?>">数据导入</a></li>
			<li class=""><a href="<?php echo $tongjiUrl; ?>">统计信息</a></li>
		</ul>
	</div>

	<form action="<?php echo $contentsUrl; ?>" method="post">
		<input name="token" type="hidden" value="<?php echo $token; ?>"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">一级分类</th>
					<td class="td">
						<select name="first_level" id="first_level">
							<option value="0">请选择分类</option>
							<?php foreach ($topData as $k => $v) { ?>
								<option value="<?php echo $v['id']; ?>" <?php if ($v['id'] == $postData['first_level']) echo 'selected'; ?>><?php echo $v['name']; ?></option>
							<?php } ?>
						</select>
					</td>
				</tr>
				<tbody id="cate_data" style="display: <?php echo $postData['second_level'] ? '' : 'none' ?>">
				<tr class="tr">
					<th class="th">二级分类</th>
					<td class="td">
						<select name="second_level" id="second_level">
							<option value="0">请选择</option>
							<?php foreach ($secondData as $k => $v) { ?>
								<option value="<?php echo $v['id']; ?>" <?php if ($v['id'] == $postData['second_level']) echo 'selected'; ?>><?php echo $v['name'] ?></option>
							<?php } ?>
						</select>
					</td>
				</tr>
				</tbody>
			</table>
		</div>
		<div class="mb10 tac">
			<span class="btn"><span><button type="submit">搜 索</button></span></span>
		</div>
	</form>

	<div class="table_list">
		<table width="100%">
			<tr class="hd">
				<td width="5%">ID</td>
				<td width="8%">名称</td>
				<td width="8%">一级分类</td>
				<td width="9%">二级分类</td>
				<td width="5%">状态</td>
				<td width="5%">排序</td>
				<td width="12%">开始时间</td>
				<td width="12%">结束时间</td>
				<td width="12%">添加时间</td>
				<td width="4%">是否显示</td>
				<td width="10%">操作</td>
			</tr>
			<?php foreach ($data as $key => $value) {
				?>
				<tr class="ct">
					<td><?php echo $value['id']; ?></td>
					<td><?php echo $value['name']; ?></td>
					<td><?php echo $value['first_level']; ?></td>
					<td><?php echo $value['cat_name']; ?></td>
					<td><?php echo $value['status'] == 1 ? '开启' : '关闭'; ?></td>
					<td><?php echo $value['sort']; ?></td>
					<td><?php echo date("Y-m-d H:i:s", $value['start_time']); ?></td>
					<td><?php echo date("Y-m-d H:i:s", $value['end_time']); ?></td>
					<td><?php echo date("Y-m-d H:i:s", $value['add_time']); ?></td>
					<td><?php echo $value['is_special'] == '1' ? '是' : '否' ?></td>
					<td><a href="<?php webroot; ?>/Admin/sites/cedit?id=<?php echo $value['id']; ?>">编辑</a>
						<a href="javascript:" onclick="deleteOne('<?php echo $cdeleteUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
					</td>
				</tr>
			<?php } ?>
		</table>
	</div>
	<div class="mr10 cc">
		<?php echo $pager; ?></div>

	<script type="text/javascript">
		$("#first_level").bind('change', function () {
			var fristLevel = $("#first_level option:selected").val();
			if (fristLevel > 0) {
				$.ajax({
					'type': 'post',
					'dataType': 'json',
					'data': {'token': '<?php echo $token;?>', 'parent_id': fristLevel},
					'url': '/Admin/sites/ajaxGetSecondLevelData',
					'success': function (e) {
						var msg = '<option value="0">请选择</option>';
						$.each(e.data, function (i, m) {
							msg += '<option value="' + m.id + '">' + m.name + "</option>";
						});
						$("#second_level").html(msg);
						$("#cate_data").show();
					}
				});
			} else {
				$("#cate_data").hide();
			}
		});
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>