<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">广告列表</a></li>
    <li class="current"><a href="javascript:;">添加广告</a></li>
	</ul>
</div>
<div class="h_a">添加广告</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="0"></td>
		</tr>
		<tr class="tr">
			<th class="th">标题</th>
			<td class="td"><input type="text" class="input wc" name="title" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">类型</th>
			<td class="td">
				<label class="mr20"><input name="ad_type" onclick="showContent(1);" value="1" type="radio">外链</label>
				<label class="mr20"><input name="ad_type" checked onclick="showContent(2);" value="2" type="radio">站内通告</label>
			</td>
		</tr>
		<tr class="tr" id="link">
			<th class="th">链接</th>
			<td class="td"><input type="text" name="link" class="input wc"></td>
		</tr>
		<tr class="tr">
			<th class="th">图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">开始结束时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="" /></div>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td"><select name="status">
                	<option value="1">开启</option>
                	<option value="0">关闭</option>
            </select></td>
		</tr>
		<tr class="tr" id="descrip">
				<th class="th">内容</th>
				<td class="td"><textarea
						style="width: 800px; height: 500px" class="textarea"
						name="descrip"></textarea>
				</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script src="<?php echo $staticPath;?>/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
<script type="text/javascript">
showContent = function(flag) {
	if (flag == 2) {
		$("#link").hide();
		$("#descrip").show();
	} else {
		$("#link").show();
		$("#descrip").hide();
	}
}
var editor;
KindEditor.ready(function(K) {
	K.token = token;
    editor = K.create('textarea[name="descrip"]', {
        resizeType : 1,
        allowPreviewEmoticons : false,
        allowImageUpload : true,
        uploadJson : '<?php echo $adminroot.$uploadImgUrl;?>',
        items : EDITOR_ITEMS
    });
});
showContent(2);
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Cod_Ad/index');
	});
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
