<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">装机必备列表</a></li>
		<li class="current"><a href=""> 管理装机必备</a></li>
	</ul>
</div>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="action" id="action" type="hidden" value="" />
<input name="id" id="id" type="hidden" value="<?php echo $id;?>" />
<div class="h_a">
    <span class="btn2"><span><button onclick="$('#action').val('sort');" type="submit">重新排序</button></span></span>
	<span class="btn2"><span><button onclick="$('#action').val('delete');" type="submit">删除</button></span></span>
	<span>共<?php echo !$total ? '0' : $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td><input type="checkbox" onclick="checkAll('.checkbox')"></td>
			<td width="60">排序</td>
			<td width="30">ID</td>
			<td>标题</td>
			<td>图标</td>
			<td>分类</td>
			<td>大小</td>
			<td>版本</td>
			<td>状态</td>
		</tr>
<?php if($games) {?>
<?php foreach($games as $key => $value) {?>
		<tr class="ct">
		    <td><input class="checkbox" name="ids[]" value="<?php echo $value['id'];?>" type="checkbox"></td>
		    <td><input type="text" class="input" style="width:30px" name="sort[<?php echo $installe_games[$value['id']]['id'];?>]" value="<?php echo $installe_games[$value['id']]['sort'];?>"></td>
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['name'];?></td>
			<td><img src="<?php echo $value['img'];?>" style="width:7.2em;height:7.2em"/></td>
			<td><?php echo $resource_games[$value['id']]['category_title'];?></td>
        	<td><?php echo $resource_games[$value['id']]['size'];?>M</td>
        	<td><?php echo $resource_games[$value['id']]['version'];?></td>
        	<td><?php echo $value['status'] ? '已上线' : '已下线';?></td>
		</tr>
<?php }} ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
</form>
<script>
$(document).ready(function(){
	ajaxForm('batchForm', function(data) {
		ajaxRedirect(data, baseurl+'/Admin/Client_Installe/editCt?id=<?php echo $id;?>');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
