<?php echo $this->render("layout/webheader.phtml");?>
	<body data-pagerole="body">
	<div class="module">
		<section id="iScroll">
			<div class="cut-rule J_lazyload_img">
				<div class="pic">
					<img src="<?php echo $staticResPath;?>/pic/blank.gif" data-src="<?php echo "$staticResPath"; ?>/assets/img/game-download-01.png">
				</div>
				<div class="pic">
					<img src="<?php echo $staticResPath;?>/pic/blank.gif" data-src="<?php echo "$staticResPath"; ?>/assets/img/game-download-02.png">
				</div>
			</div>
		</section>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
<?php echo $this->render("layout/newfooter.phtml");?>