<?php echo $this->render("layout/webheader.phtml");?>
<body data-pagerole="body">
<div class="module">
	<section id="iScroll">
		<div class="cut-rule J_lazyload_img">
			<div class="cut-rule J_lazyload_img">
				<div class="pic">
					<img src="<?php echo $staticResPath;?>/pic/blank.gif" data-src="<?php echo "$staticResPath"; ?>/assets/img/game-rule-01.png">
				</div>
				<div class="pic">
					<img src="<?php echo $staticResPath;?>/pic/blank.gif" data-src="<?php echo "$staticResPath"; ?>/assets/img/game-rule-02-new.png">
				</div>
				<div class="pic">
					<img src="<?php echo $staticResPath;?>/pic/blank.gif" data-src="<?php echo "$staticResPath"; ?>/assets/img/game-rule-03.png">
				</div>
				<div class="pic">
					<img src="<?php echo $staticResPath;?>/pic/blank.gif" data-src="<?php echo "$staticResPath"; ?>/assets/img/game-rule-04.png">
				</div>
				<div class="pic">
					<img src="<?php echo $staticResPath;?>/pic/blank.gif" data-src="<?php echo "$staticResPath"; ?>/assets/img/game-rule-05.jpg">
				</div>
			</div>
		</div>
	</section>
</div>

<?php echo $this->render("layout/tj.phtml");?>
<?php echo $this->render("layout/newfooter.phtml");?>