<?php echo $this->render("layout/webheader.phtml");?>
<body data-pagerole="body">
<div class="module">
	<section id="iScroll" class="cut-detail J_lazyload_img">
		<div class="gotop">
			<span>返回顶部</span>
		</div>
		<div class="content-edit">
			<p><?php echo html_entity_decode($store['description']); ?></p>
		</div>
	</section>
</div>

<?php echo $this->render("layout/tj.phtml");?>
<?php echo $this->render("layout/newfooter.phtml");?>