<?php echo $this->render("layout/header.phtml");?>

<div class="h_a">当前用户</div>
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">UID</th>
			<td class="td"><?php echo $uid;?></td>
		</tr>
		<tr class="tr">
			<th class="th">用户名</th>
			<td class="td"><?php echo $username;?></td>
		</tr>
	</table>
</div>
<?php if($message) { ?>
<div class="h_a">有<?php echo $count;?>条未读消息</div>
<div class="table_list">
	<table width="100%">		
<?php foreach ($message as $key=>$value) {?>
		<tr class="ct">
			<td <?php if($value['status'] == 0) echo 'class="strong"';?>><?php echo Util_String::strlen($value['content']) > 60 ? Util_String::substr($value['content'], 0, 60).'...' : $value['content'];?></td>
			<td  width="140"><?php echo $value['create_time'] ? date('Y-m-d H:i:s', $value['create_time']) : '';?></td>
			<td width="120"><a href="javascript:" onclick="deleteOne('/Admin/Message/delete/?id=<?php echo $value['id'];?>', '', event);">删除</a>&nbsp;&nbsp;
			<a href="<?php echo $webroot;?>/Admin/Message/detail/?id=<?php echo $value['id'];?>" class="mr10">查看</a></td>
		</tr>
<?php } ?>
	</table>
</div>
<?php }?>
<?php echo $this->render("layout/footer.phtml");?>
