<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class="current"><a href="<?php echo $indexUrl; ?>">用户列表</a></li>
			<li class=""><a href="<?php echo $logUrl; ?>">中奖记录</a></li>
		</ul>
	</div>
	<div class="table_full">
		<form action="<?php echo $indexUrl; ?>" method="POST" id="form">
			<input type="hidden" name="token" value="<?php echo $token; ?>"/>
			<table width="100%" cellspacing="0" cellpadding="0">
				<tr class="tr">
					<th class="th">用户名：</th>
					<td class="td"><input name="uname"  value="<?php echo $uname;?>" type="text"  class="input"></td>
				</tr>
			</table>
			<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
			</div>
		</form>
	</div>

	<div class="table_list">
		<table style="width: 100%">
			<tr class="hd">
				<th class="th">ID</th>
				<th class="th">游客名</th>
				<th class="th">用户ID</th>
				<th class="th">用户名</th>
				<th class="th">添加时间</th>
				<th class="th">编辑时间</th>
				<th class="th">当前日期</th>
				<th class="th">奖品ID</th>
			</tr>
			<?php foreach ($dataList as $v) { ?>
				<tr class="ct">
					<td class="td" align="left"><?=$v['id'];?></td>
					<td class="td" align="left"><?=$v['uname'];?></td>
					<td class="td"><?php echo $v['uid'];?></td>
					<td class="td"><?php echo $v['username'] ?></td>
					<td class="td"><?php echo date("Y-m-d H:i:s",$v['create_time']) ?></td>
					<td class="td"><?php echo date("Y-m-d H:i:s",$v['update_time']) ?></td>
					<td class="td"><?php echo $v['cur_date'];?></td>
					<td class="td"><?php echo $v['log_id']; ?></td>
				</tr>
			<?php } ?>
		</table>
	</div>

	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>
<?php echo $this->render("layout/footer.phtml"); ?>