<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $indexUrl;?>">分类列表</a></li>
    <li class="current"><a href="javascript:;">编辑分类</a></li>
	</ul>
</div>
<div class="h_a">编辑分类</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="<?php echo $info['sort'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">分类名称</th>
			<td class="td"><input type="text" class="input wa" name="name" value="<?php echo $info['name'];?>"></td>
		</tr>
        <tr>
            <th class="th">状态</th>
            <td class="td">
                <select name="status">
                    <option value=1 <?php echo $info['status']==1?'selected=selected':''; ?>>有效</option>
                    <option value=0 <?php echo $info['status']==0?'selected=selected':''; ?>>无效</option>
                </select>
            </td>
        </tr>
		<tr class="tr">
			<th class="th">分类标题</th>
			<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">图标</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg">
						<img src="<?php echo $attachPath.$info['icon'];?>"/>
						<input type="hidden" name="icon" value="<?php echo $info['icon'];?>">
					</li>
				</ul>
				<p style="clear:both;">
					<iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script type="text/javascript">

    $(document).ready(function(){
        ajaxForm('addForm',function(ret){
            ajaxRedirect(ret, '<?php echo Util_Http::getServer("HTTP_REFERER"); ?>');
        });
    })
</script>


<?php echo $this->render("layout/footer.phtml");?>
