<form method="post" action="" id="edit_form">
	<input name="id" value="<?php echo $info['id']; ?>" type="hidden"/>
	<input name="token" value="<?php echo $token; ?>" type="hidden"/>
	<table class="editTable">
		<tr>
			<th>名称</th>
			<td>
				<input type="text" style="width:250px;" class="easyui-textbox" name="name" required="true" value="<?php echo $info['name']; ?>">
			</td>
		</tr>
		<tr>
			<th>位置</th>
			<td>
				<input type="text" style="width:100px;" class="easyui-textbox" name="from" required="true" value="<?php echo $info['from']; ?>">
			</td>
		</tr>
		<tr>
			<th>搜索链接</th>
			<td>
				<input type="text" style="width:250px;" class="easyui-textbox" name="url" required="true" value="<?php echo $info['url']; ?>">
			</td>
		</tr>
		<tr>
			<th>生成链接</th>
			<td><?=Common::getPrevSearchUrl()?>?keyword={searchTerms}&from=<?php echo $info['from']; ?></td>
		</tr>
	</table>
</form>