<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $listUrl;?>">福利任务</a></li>
		<li ><a href="<?php echo $dlistUrl;?>">连续登录</a></li>
		<li ><a href="<?php echo $dailyTaskUrl;?>">每日任务</a></li>
		<li><a href="<?php echo $taskInfoConfigUrl;?>">任务说明</a></li>
		<li  class="current"><a href="javascript:void();">连续登录明细</a></li>
	</ul>
</div>
<form action="<?php echo $continueLoginDetailUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
      <table width="100%">
	   <tr class="tr">
			<th class="th">金立UUID</th>
			<td class="td"><input type="text" class="input wc" name="uuid" value="<?php echo $s['uuid'];?>"></td>
			<th class="th">账号</th>
			<td class="td"><input type="text" class="input" name="uname" value="<?php echo $s['uname'];?>"></td>
	 </tr>
	 </table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="h_a">
        <span>&nbsp;&nbsp;&nbsp;&nbsp;共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td>金立UUID</td>
			<td width="150">昵称</td>
			<td>账号</td>
			<td>当前进度</td>
			<td width="120">完成时间</td>
			<td width="200"> 奖励</td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['uuid'];?></td>
			<td><?php echo $userInfo[$value['uuid']]['nickname'];?></td>
			<td><?php echo $userInfo[$value['uuid']]['uname'];?></td>
			<td><?php echo $value['days'].'/7';?></td>
			<td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
			<td><?php echo intval($value['denomination']).(($value['send_object'] == 1)?'积分':'A券');?></td>
			
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
