<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>管理中心 Management center</title>
<link rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/v2/easyui/themes/<?php echo $sitetheme; ?>/easyui.css">
<link rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/v2/easyui/themes/icon.css">
<link rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/v2/css/ui.css">
<link rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/v2/css/main.css">
<script type="text/javascript" src="<?php echo $staticPath; ?>/v2/easyui/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/v2/easyui/jquery-extend.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/v2/easyui/jquery.easyui.min.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/v2/js/easyui-lang-zh_cn.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/v2/js/main.js"></script>
</head>
<body class="easyui-layout panel-noscroll" style="width: 100%; height: 100%; overflow-y: hidden;">
<!-- <body class="easyui-layout"> -->