<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li class="current"><a href="javascript:;">添加游戏</a></li>
	</ul>
</div>
<form id="batchForm" action="<?php echo $listOpenSortPostUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="day_id" value="<?php echo $day_id;?>" type="hidden" />
<div class="h_a">
	<span>共<?php echo count($list);?>条结果</span>
</div>
<div class="table_list">
	<table id="table_list" width="100%">
	<thead>
		<tr class="hd">
			<td width="30">排序</td>
			<td width="20">ID</td>
			<td width="20">图标</td>
			<td width="50">游戏名称</td>
			<td width="30">开服时间</td>
			<td width="30">开服名称</td>
			<td width="30">分类</td>
		</tr>
	 </thead>
	 <tbody>
		<?php foreach($list as $key => $value) {?>
		<tr class="ct">
			<td><input type="text" class="input" style="width:30px" name="sort[]" value="<?php echo $value['sort'];?>"></td>
			<td><?php echo $value['gameId']?></td>
			<td><img src="<?php echo $value['gameIcon']?>" style="width:70px;height:70px;"/></td>
			<td><?php echo $value['gameName']?></td>
			<td><?php echo $value['open_time']?></td>
			<td><?php echo $value['server_name']?></td>
			<td><?php echo $value['gameCategory']?></td>
		</tr>
	   <?php } ?>
    </tbody>
	</table>
</div>
<div class="mb10 tac">
    <span class="btn"><span><a href="<?php echo $listOpenSelectUrl.'?day_id='.$day_id;?>"><button type="button">返回</button></a></span></span>
    <span class="btn"><span><button onfocus="blur();" type="submit">完成</button></span></span>
</div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $editUrl.'?dayId='.$day_id;?>');
	});

	var fixHelperModified = function(e, tr) {
	    var $originals = tr.children();
	    var $helper = tr.clone();
	    $helper.children().each(function(index) {
	        $(this).width($originals.eq(index).width())
	    });
	    return $helper;
	};
	var updateIndex = function(e, ui) {
		var length = $("input[class='input']").length;		
		$("input[class='input']", ui.item.parent()).each(function (i) {
			$(this).val(length - i);
		});
	};

	$("#table_list tbody").sortable({
	    helper: fixHelperModified,
	    stop: updateIndex
	});
	$("#table_list tbody").disableSelection();
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
