<?php echo $this->render("layout/header2.phtml");?>
<body>
	<div data-role="page" data-theme="no" id="page" class="free-charge">
	<?php if ($hasheader) {?>
		<header class="hd">
			<h1><strong>免费赢话费</strong></h1>
			<p><a href="/index/index"　data-ajax="false"><img src="<?php echo $staticResPath;?>/pic/btn_backhome.png" alt="" /></a></p>
		</header>
	<?php }?>
		<div class="ct">
			<section>
				<p class="tip"><span>恭喜您抽中大奖，请输入您参加活动时的手机号和通关密语，以便核实您的身份。</span></p>
				<form class="form-box" action="<?php echo $chargePostUrl;?>" method="POST">
				<input type="hidden" name="token" value="<?php echo $token;?>"/>
					<ul>
						<li><label for=""><em>手机号：</em></label><input type="text" name="mobile" class="l" value="" /></li>
						<li><label for=""><em>通关密语：</em></label>
							<select name="question">
								<option value="wantgo">你最想去的地方是？</option>
								<option value="shengri">你的生日是？</option>
								<option value="chushengdi">你的出生地是？</option>
							</select>
							<input type="text" name="answer" class="l" /></li>
						<li><button data-role="none"><span>确定</span></button></li>
					</ul>
				</form>
			</section>
		</div>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>