<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<title>导航收入日报</title>
<style type="text/css">
	*{margin:0; padding: 0;}

	.navbar{
		background: #00a1e9;
		height: 50px;
		line-height: 50px;
		padding: 0 5px;
		color:#fff;
		text-shadow:0 1px #000;
	}
	.table{
		width: 100%;
		border-collapse: collapse;
		border-spacing: 0;
		overflow: hidden;
		font-size:12px;
	}
	.table thead tr{
		height: 50px;
		background: #eee;
	}
	.table thead tr th{
		padding: 10px 0 10px 5px;
		text-align: left;
		font-weight: normal;
	}
	.table tbody tr td{
		height: 20px;
		line-height: 20px;
		padding: 10px 0 10px 5px;
	}

	.table tbody tr td:nth-child(2){
		color:red;
	}

	.table tbody tr.even{
		background: #fff;
	}
	.table tbody tr.odd{
		background: rgb(240, 244, 253);
	}
</style>
</head>

<body>
	<section id="">
		<header class="header navbar">
	        <p class="navbar-text pull-left">导航收入日报</p>
	    </header>
		<table class="table">
			<thead>
				<tr>
					<th>日期</th>
					<th>总收入</th>
					<th>CPS</th>
					<th>CPC</th>
					<th>CPT</th>
					<th>CPA</th>
					<th>PUSH</th>
				</tr>	
			</thead>
			<tbody>
			<?php if($dataList){?>
			<?php foreach ( $dataList as $k=>$v){?>
				<tr class="<?php echo $k%2==0?'even':'odd';?>">
					<td><?php echo date('m/d',$v['get_time']);?></td>
					<td><?php echo $v['income'];?></td>
					<td><?php echo $v['cps'];?></td>
					<td><?php echo $v['cpc'];?></td>
					<td><?php echo $v['cpt'];?></td>
					<td><?php echo $v['cpa'];?></td>
					<td><?php echo $v['push'];?></td>
				</tr>
			<?php } }else{ 
				echo '暂无相关数据！';
			}?>
			</tbody>
		</table>
	</section>
</body>
</html>