<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">分类列表</a></li>
    <li class="current"><a href="javascript:;">编辑分类</a></li>
	</ul>
</div>
<div class="h_a">编辑分类</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="editForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" maxlength="30" value="<?php echo $info['sort'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">分类</th>
			<td class="td">
		<select name="type">
<?php foreach($types as $key=>$value){ ?>
			<option <?php echo $info['type'] == $key ? 'selected="selected"' : '';?> value="<?php echo $key;?>"><?php echo $value;?></option>
<?php }?>
		</select>
		</td>
		</tr>

		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="name" maxlength="30" value="<?php echo $info['name'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">描述</th>
			<td class="td"><input type="text" class="input" name="descrip" maxlength="30" value="<?php echo $info['descrip'];?>"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('editForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Navtype/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
