<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">会员列表</a></li>
        <li><a href="<?php echo $giftUrl;?>">生日礼物</a></li>
        <li><a href="<?php echo $vipSuperDescUrl;?>">尊贵身份说明</a></li>
        <li><a href="<?php echo $vipActivityDescUrl;?>">活动返利说明</a></li>
        <li><a href="<?php echo $vipDescUrl;?>">会员说明</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post" id="searchForm">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th" width="7%">UUID</th>
			<td class="td" width="26%"><input type="text" class="input" name="uuid" value="<?php echo ($search['uuid']) ? $search['uuid'] : '';?>"></td>
			<th class="th" width="7%">昵称</th>
			<td class="td" width="26%"><input type="text" class="input" name="nickname" value="<?php echo ($search['nickname']) ? $search['nickname'] : '';?>"></td>
			<th class="th" width="7%">VIP等级</th>
			<td class="td" width="27%"><input type="text" class="input" name="vip" value="<?php echo ($search['vip']) ? $search['vip'] : '';?>" onkeyup="value=value.replace(/[^\d]/g,'')"></td>
		</tr>
		<tr class="tr">
			<th class="th" width="7%">账号</th>
			<td class="td" width="26%"><input type="text" class="input" name="uname" value="<?php echo ($search['uname']) ? $search['uname'] : '';?>"></td>
			<th class="th">注册时间</th>
			<td class="td" colspan="5"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo $search['start_time'];?>" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="<?php echo $search['end_time'];?>" /></div>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="h_a">
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="60">序号</td>
			<td width="60">VIP等级</td>
			<td width="200">金立UUID</td>
			<td width="100">昵称</td>
			<td width="120">注册时间</td>
			<td width="120">最后登录时间</td>
			<td width="100">操作</td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['vip'] ? 'VIP'.$value['vip'] : '';?></td>
			<td><?php echo $value['uuid'];?></td>
			<td><?php echo $value['nickname'];?></td>
		    <td><?php echo date('Y-m-d H:i:s', $value['regTime']);?></td>
		    <td><?php echo date('Y-m-d H:i:s', $value['lastLoginTime']);?></td>
			<td>
			<a href="<?php echo $infoUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">详情</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
