<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class="current"><a href="<?php echo $newUrl; ?>">批量生成订单</a></li>
		</ul>
	</div>
	<div class="h_a">数据导入</div>
	<form method="post" action="/Admin/Order/addNew" id="addFrom" enctype="multipart/form-data">
		<input name="token" value="<?php echo $token; ?>" type="hidden"/>

		<div class="table_full">
			<table width="100%">

				<tr class="tr">
					<th class="th">一级分类</th>
					<td class="td"><select name="group_type" id="group_type">
							<option value="0">请选择类型</option>
							<?php foreach ($types as $k => $v) { ?>
								<option value="<?php echo $k; ?> " <?php if ($k == $type) echo 'selected'; ?>><?php echo $v; ?></option>
							<?php } ?>
						</select>
					</td>
				</tr>

				<tr class="tr" id="tr_type_id" style="display: none">
					<th class="th">二级分类</th>
					<td class="td">
						<select name="type_id" id="type_id"></select>
					</td>
				</tr>

				<tr class="tr" id="tr_card_id" style="display: none">
					<th class="th">面值信息</th>
					<td class="td">
						<select name="card_id" id="card_id"></select>
					</td>
				</tr>

				<tr class="tr">
					<th class="th">选择文件</th>
					<td class="td"><input type="file" class="input" name="data" value=""></td>
					<td class="td"><a href="<?php echo $exportUrl; ?>">导出</a></td>
				</tr>
			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
	</form>
	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>

	<script type="text/javascript">
		//广告表单数据提交
		$(document).ready(function () {
			ajaxForm('addFrom', function (ret) {
				ajaxRedirect(ret, baseurl + '/Admin/Order/new');
			});
		})

		$("#group_type").bind('change', function () {
			var group_type = $("#group_type option:selected").val();
			if (group_type != '0') {
				$.ajax({
					'type': 'post',
					'dataType': 'json',
					'url': '/Admin/Order/AjaxGetCardMsg',
					'data': {'token': '<?php echo $token;?>', 'group_type': group_type},
					'success': function (e) {
						var html = '<option value="0">请选择</option>';
						$.each(e.data, function (i, m) {
							html += '<option value="' + m.type_id + '">' + m.type_name + '</option>';
						})
						$("#type_id").html(html);
						$("#tr_type_id").show();
					}
				});
			} else {
				$("tr_type_id").hide();
			}
		});

		$("#type_id").bind('change', function () {
			var type_id = $("#type_id option:selected").val();
			if (type_id > 0) {
				$.ajax({
					'type': 'post',
					'dataType': 'json',
					'url': '/Admin/Order/AjaxGetCardMsg',
					'data': {'token': '<?php echo $token;?>', 'type_id': type_id},
					'success': function (e) {
						var html = '<option value="0">请选择</option>';
						$.each(e.data, function (i, m) {
							html += '<option value="' + m.id + '">' + m.card_name + '</option>';
						})
						$("#card_id").html(html);
						$("#tr_card_id").show();
					}
				});
			}
			else {
			}
		});
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>