<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>管理系统</title>
<script src="<?php echo $staticPath;?>/js/common/jquery.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui.min.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticPath;?>/js/common/jquery.form.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticPath;?>/js/common/common.js?v=<?php echo $version;?>"></script>
<?php
if($ueditor == true) {?>
    <script type="text/javascript" charset="utf-8" src="<?php echo $staticPath;?>/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8">window.UEDITOR_CONFIG.serverUrl = "<?php echo $ueditorAction;?>?dir=<?php echo $dir;?>";</script>
    <script type="text/javascript" charset="utf-8" src="<?php echo $staticPath;?>/ueditor/ueditor.all.js"> </script>
    <script type="text/javascript" charset="utf-8" src="<?php echo $staticPath;?>/ueditor/lang/zh-cn/zh-cn.js"></script>
<?php }?>
<script>
    var token = "<?php echo $token;?>";
    window.token = token;
    var baseurl = "<?php echo $adminroot;?>";
</script>
<link rel="shortcut icon" href="/favicon.ico" />
<link href="<?php echo $staticPath;?>/css/style.css" rel="stylesheet" />
<link rel="stylesheet" href="<?php echo $staticPath;?>/css/jquery-ui.css?v=<?php echo $version;?>" />
</head>
<body>
<div class="wrap">