<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">公告列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加公告</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="ad_type" type="hidden" value="<?php echo $ad_type;?>" />
<div class="table_full">
	<table width="100%">	
		<tr>
		   <th class="th">状态</th>
			<td class="td">
			<select name="status" class="wa">
			    <option  value="0">全部</option>
				<option <?php if($search['status'] == 2) echo 'selected';?> value="2">开启</option>
				<option <?php if($search['status'] == 1) echo 'selected';?> value="1">关闭</option>
			</select>
			</td>
			<th class="th">类型</th>
			<td class="td">
			<select name="ad_ptype" class="select wa">
			    <option value="0">全部</option>
				<option <?php if($search['ad_ptype'] == 1) echo 'selected';?> value="1">内容</option>
				<option <?php if($search['ad_ptype'] == 2) echo 'selected';?> value="2">分类</option>
				<option <?php if($search['ad_ptype'] == 3) echo 'selected';?> value="3">专题</option>
				<option <?php if($search['ad_ptype'] == 5) echo 'selected';?> value="5">活动</option>
				<option <?php if($search['ad_ptype'] == 4) echo 'selected';?> value="4">外链</option>
			</select>
		    </td>
		</tr>
		<tr class="tr">
			<th class="th">关键字</th>
			<td class="td"><input type="text" class="input" name="title" value="<?php echo empty($search['title'])?'':$search['title'];?>"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="action" id="action" type="hidden" value="" />
<div class="h_a">
	<span class="btn2"><span><button onclick="$('#action').val('sort');" type="submit">重新排序</button></span></span>
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td><input type="checkbox" onclick="checkAll('.checkbox')"></td>
			<td width="60">排序</td>
			<td  width="150" style="display:none">标头</td>
			<td  width="150">标题</td>
			<td>类型</td>
			<td width="150">链接ID</td>
			<td>开始时间</td>
			<td>结束时间</td>
			<td>状态</td>
			<td>操作</td>
		</tr>
<?php foreach($ads as $key => $value) {?>
		<tr class="ct">
		    <td><input class="checkbox" name="ids[]" value="<?php echo $value['id'];?>" type="checkbox"></td>
			<td><input type="text" class="input" style="width:30px" name="sort[<?php echo $value['id'];?>]" value="<?php echo $value['sort'];?>"></td>
			<td style="display:none"><?php echo $value['head'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><?php echo $value['ad_ptype'] ? $ad_types[$value['ad_ptype']] :'';?></td>
			<td><?php echo $value['link'];?></td>
		    <td><?php echo date('Y-m-d H:i:s', $value['start_time']);?></td>
		    <td><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
			<td><?php echo $value['status'] == 1 ? '开启' : '关闭';?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
</form>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Ad_Activity/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
