<?php
$str = '<ul class="col-3-img col-3-txt ui-tapimg-wrap">';
foreach ($list as $val) {
	$str .= sprintf('<li><a href="%s"><img class="pic" src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==" data-src="%s" width="86" height="118"><p>%s</p></a></li>', $val['link'], $val['img'], $val['name']);
}
$str .= '</ul>';
echo $str;


