<?php echo $this->render("layout/webheader.phtml");?>
<body data-pagerole="body">
<div class="module">
	<section id="iScroll">
		<div class="cut-rule J_lazyload_img">
			<div class="pic">
				<img src="<?php echo $staticResPath?>/pic/blank.gif" data-src="<?php echo $staticResPath?>/pic/cut-rule-01.png">
			</div>
			<div class="pic">
				<img src="<?php echo $staticResPath?>/pic/blank.gif" data-src="<?php echo $staticResPath?>/pic/cut-rule-02.png">
			</div>
			<div class="pic">
				<img src="<?php echo $staticResPath?>/pic/blank.gif" data-src="<?php echo $staticResPath?>/pic/cut-rule-03.png">
			</div>
			<div class="pic">
				<img src="<?php echo $staticResPath?>/pic/blank.gif" data-src="<?php echo $staticResPath?>/pic/cut-rule-04.png">
			</div>
			<div class="pic">
				<img src="<?php echo $staticResPath?>/pic/blank.gif" data-src="<?php echo $staticResPath?>/pic/cut-rule-05.png">
			</div>
			<div class="pic">
				<img src="<?php echo $staticResPath?>/pic/blank.gif" data-src="<?php echo $staticResPath?>/pic/cut-rule-06.png">
			</div>
		</div>
	</section>
</div>

<?php echo $this->render("layout/tj.phtml");?>
<?php echo $this->render("layout/newfooter.phtml");?>