<footer class="footer">
	<nav class="nav-top">
		<ul>
			<li>
				<a href="/index">
					<i class="icon-home"></i>
					首页
				</a>
			</li>
			<li>
				<a href="/Category/index">
					<i class="icon-category"></i>
					分类
				</a>
			</li>
			<li>
				<a href="/Channel/webgame">
					<i class="icon-webGame"></i>
					网游
				</a>
			</li>
			<li>
				<a href="/Channel/singlegame">
					<i class="icon-singleGame"></i>
					单机
				</a>
			</li>
			<li>
				<a href="<?php echo '/rank/index'?>">
					<i class="icon-rank"></i>
					排行
				</a>
			</li>
		</ul>
	</nav>
	<div class="qrcode-wrapper">
		<img src="http://game.3gtest.gionee.com/attachs/game/webimg/201503/551641f580da4.png" alt="">
		<div class="follow-tips">
			<p>微信号：gioneegame</p>
			<p>欢迎关注游戏大厅微信公众帐号！</p>
	    </div>
	</div>
	<nav class="nav-bottom">
		<ul>
			<li>
				<a href="/Feedback/about">关于我们</a>
			</li>
			<li>
				<a href="/Feedback/faq">常见问题</a>
			</li>
			<li>
				<a href="/Feedback/index">意见反馈</a>
			</li>
			<li>
				<a href="/Feedback/client">客户端</a>
			</li>
		</ul>
	</nav>
	<div class="copyright">
		<p>增值电信许可证:<a href="http://assets.3gtest.gionee.com/apps/game/3g/pic/1.jpg" target="_blank">粤B2-20120350</a></p>
		<p>Copyright © 2015 <a target="_blank" href="http://www.miitbeian.gov.cn/">粤ICP备05087105号</a></p>
		<p>网络文化经营许可证:<a href="http://assets.3gtest.gionee.com/apps/game/3g/pic/2.jpg" target="_blank">粤网文[2013]029-029号</a></p>
	</div>
</footer>