<script type="text/javascript" src="<?php echo "$appJs/sys/zetop.source.js$timestamp";?>"></script>
<script type="text/javascript" src="<?php echo "$appJs/sys/react.js$timestamp";?>"></script>
<script type="text/javascript" src="<?php echo "$appJs/sys/JSXTransformer.js$timestamp";?>"></script>
<script type="text/javascript" src="<?php echo "$appJs/sys/Model.js$timestamp";?>"></script>
<script type="text/javascript" src="<?php echo "$appJs/sys/lazyload.source.js$timestamp";?>"></script>

<script type="text/javascript" src="<?php echo "$appJs/view/public.js$timestamp";?>"></script>

<script src="<?php echo "$appJs/view/collection.js$timestamp";?>"></script>
<script src="<?php echo "$appJs/view/advertising.js$timestamp";?>"></script>
<script src="<?php echo "$appJs/view/infoBulletin.js$timestamp";?>"></script>
<script src="<?php echo "$appJs/view/topic.js$timestamp";?>"></script>
<script src="<?php echo "$appJs/view/gameList.js$timestamp";?>"></script>
<script src="<?php echo "$appJs/view/container.js$timestamp";?>"></script>
<script src="<?php echo "$appJs/sys/pgwslider.js";?>"></script>
<script src="<?php echo "$appJs/view/gameDetails.js$timestamp";?>"></script>
<script src="<?php echo "$appJs/view/packageDetails.js$timestamp";?>"></script>
<script src="<?php echo "$appJs/view/article.js$timestamp";?>"></script>
<script src="<?php echo "$appJs/view/search.js$timestamp";?>"></script>
<script src="<?php echo "$appJs/view/category.js$timestamp";?>"></script>
<!--<script src="<?php echo "$appJs/view/template.js$timestamp";?>"></script>-->
