<div class="other_fixed_assist">
		<a href="#head" class="ico backTop" id="top">返回顶部</a>
		<a href="<?php echo Common::aimiTjUrl($tjUrl, $tj_channel, $tj_cku, 'visit', 'feedback', $tj_intersrc, $webroot.'/Front/About/feedback/');?>" class="ico leaveMg">留言</a>
		<a href="javascript:void(0)" id="weixin" class="ico weixin">
			<div id="wx"><?php 
			$temp = Common::aimiTjUrl($tjUrl, $tj_channel, $tj_cku, 'QR', 'com.android.amigame', $tj_intersrc, html_entity_decode($ami_android_url));
			?>
			<img src="<?php echo $webroot . '/api/qrcode/index?p='. urlencode($temp); ?>" alt="QR code" width="100" height="100" />
			<p>金立游戏大厅二维码扫描</p></div>
		</a>
</div>