<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">消息列表</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td>内容</td>
			<td width="200">日期</td>
			<td width="100">操作</td>
		</tr>
<?php foreach($message as $key => $value) {?>
		<tr class="ct">
			<td <?php if($value['status'] == 0) echo 'class="strong"';?>><?php echo Util_String::strlen($value['content']) > 60 ? Util_String::substr($value['content'], 0, 60).'...' : $value['content'];?></td>
			<td><?php echo $value['create_time'] ? date('Y-m-d H:i:s', $value['create_time']) : '';?></td>
			<td><a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			<a href="<?php echo $detailUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">查看</a></td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
