<?php echo $this->render("layout/header.phtml");?>
<div class="wrap rotate_wrap">
	<div class="content">
		<div class="main">
			<!-- 联系我们 s-->
			<div class="mod_box contactUs_box">
				<div class="hd"><i class="hd_ico"></i><h2 class="title">联系我们</h2></div>
				<div class="bd">
					<ul class="contact_list">
						<li><strong class="name">新浪微博:</strong>
						<a href="<?php echo Common::aimiTjUrl($tjUrl, $tj_channel, $tj_cku, 'visit', 'amisinaweibo', $tj_intersrc.'_sinaweibo', $ami_sina_weibo?html_entity_decode($ami_sina_weibo):'http://weibo.com/gioneegamehall');?>" alt="" target="_blank">金立游戏大厅</a>
						</li>
						<li><strong class="name">官方微信:</strong>金立游戏大厅(微信号：gioneegame)</li>
						<li><strong class="name">官方邮箱</strong><a href="mailto:game@gionee.com">game@gionee.com</a></li>
						<li><strong class="name">客服QQ:</strong><?php echo $serviceQq; ?> <script charset="utf-8" type="text/javascript" src="http://wpa.b.qq.com/cgi/wpa.php?key=XzkzODAxNTgyN18yMzg0MzFfNDAwNjI4NjYxOF8"></script> </li>
						<li><strong class="name">地址：</strong>广东省深圳市深南大道7008号阳光高尔夫大厦15楼</li>
						<li><strong class="name">邮编：</strong>518042</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="aside">
			 <?php echo $this->render("layout/right_nav.phtml");?>
		</div>
	    <!-- 右侧的悬浮框 -->
	    <?php echo $this->render("layout/right.phtml");?>
	</div>
</div>
<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>