<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>用户登录</title>
	<?php echo $this->render("layout/header.phtml");?>
</head>
<body  id="login-page">
	<div class="login-container">
		<div class="login-content-left">
			<div class="text-container">
				<p class="text1"><span class="text-gionee">Gionee</span> &nbsp;金立</p>
				<p class="text2">&nbsp;&nbsp;&nbsp;&nbsp;金品质&nbsp;&nbsp;&nbsp;立天下</p>
			</div>
		</div>
		<div class="login-content-right">
			<div class="login-box">
				<h1>微信后台管理系统</h1>
				<input id="txtUserName" class="input"  placeholder="请输入用户名">
				<input id="txtPwd" class="input" type="password" placeholder="请输入密码">
				<p><input id="chkRmb" type="checkbox" />记住帐号</p>
				<!--data-ajaxUrl：登录接口地址 -->
				<input id="login" type="button" class="btn btn-login" value="登陆" data-ajaxUrl="<?php echo $loginPostUrl; ?>" />
			</div>
		</div>
	</div>
	<div class="J_dialog mask hidden">
		<div class="dialog-error-container">
			<h1>错误提示</h1>
			<p><i class="icon-info"></i>您输入的帐号和密码错误，请重新输入！</p>
			<input id="confirm" class="btn-ok" type="button" value="确定" />
		</div>
	</div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>