<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl; ?>">网点列表</a></li>
		<li class="current"><a href="javascript:;">添加网点</a></li>
	</ul>
</div>
<div class="h_a">添加网点</div>
<form method="post" action="<?php echo $addPostUrl; ?>" id="addAddressForm">
	<input name="token" value="<?php echo $token; ?>" type="hidden"/>

	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">排序</th>
				<td class="td"><input type="text" class="input" name="sort" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">省份</th>
				<td class="td"><select name="province" onchange="setcity(this.value)">
						<?php foreach ($province as $key => $value) { ?>
							<option value="<?php echo $value['id']; ?>"><?php echo $value['name']; ?></option>
						<?php } ?>
					</select></td>
			</tr>
			<tr class="tr">
				<th class="th">城市</th>
				<td class="td">
					<select name="city"></select>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">网点类型</th>
				<td class="td"><select name="address_type" onchange="showservice(this.value);">
						<?php foreach ($address_type as $key => $value) { ?>
							<option value="<?php echo $key; ?>"><?php echo $value; ?></option>
						<?php } ?>
					</select></td>
			</tr>
			<tr class="tr" id="service_type">
				<th class="th">服务类型</th>
				<td class="td"><select name="service_type">
						<?php foreach ($service_type as $key => $value) { ?>
							<option value="<?php echo $key; ?>"><?php echo $value; ?></option>
						<?php } ?>
					</select></td>
			</tr>
			<tr class="tr">
				<th class="th">网点名称</th>
				<td class="td"><input type="text" class="input wc" name="name" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">详细地址</th>
				<td class="td"><input type="text" class="input wc" name="address" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">电话</th>
				<td class="td"><input type="text" class="input  wc" name="tel" value=""></td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script type="text/javascript">
	$(document).ready(function () {
		ajaxForm('addAddressForm', function (ret) {
			ajaxRedirect(ret, baseurl + '/Admin/Address/index');
		});

		var citys = <?php echo json_encode($city);?>;
		setcity = function (province) {
			var options = '';
			$.each(citys, function (index, data) {
				var s = '';
				if (data.parent_id == province) {
					options += '<option value="' + data.id + '">' + data.name + '</option>';
				}
			});
			$("select[name='city']").html(options);
		}
		setcity(<?php echo $province[0]['id'];?>);

		showservice = function (flag) {
			if (flag == 2) {
				$("#service_type").show();
				//$("select[name='service_type']").html(option);

			} else {
				$("#service_type").hide();
				$("select[name='service_type'] option:selected").val(0);
				//$("select[name='service_type']").html('');
			}
		}
		$("#service_type").hide();
		$("select[name='service_type'] option:selected").val(0);
		//$("select[name='service_type']").html('');
	})
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
