<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li class="current"><a href="<?php echo $listUrl; ?>">网点列表</a></li>
		<li><a href="<?php echo $addUrl; ?>">添加网点</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl; ?>" method="post">
	<input name="token" type="hidden" value="<?php echo $token; ?>"/>

	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">省份</th>
				<td class="td">
					<select name="province" onchange="setcity(this.value, 0)">
						<option value="">所有省份</option>
						<?php foreach ($province as $key => $value) { ?>
							<option <?php echo ($search['province'] == $value['id']) ? 'selected="selected"' : ''; ?> value="<?php echo $value['id']; ?>"><?php echo $value['name']; ?></option>
						<?php } ?>
					</select>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">城市</th>
				<td class="td">
					<select name="city"></select>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">网点类型</th>
				<td class="td"><select name="address_type" onchange="showservice(this.value);">
						<option value="">所有类型</option>
						<?php foreach ($address_type as $key => $value) { ?>
							<option value="<?php echo $key; ?>" <?php echo ($search['address_type'] == $key) ? 'selected="selected"' : ''; ?>><?php echo $value; ?></option>
						<?php } ?>
					</select></td>
			</tr>
			<tr class="tr" id="service_type">
				<th class="th">服务类型</th>
				<td class="td"><select name="service_type">
						<option value="">所有类型</option>
						<?php foreach ($service_type as $key => $value) { ?>
							<option value="<?php echo $key; ?>" <?php echo ($search['service_type'] == $key) ? 'selected="selected"' : ''; ?>><?php echo $value; ?></option>
						<?php } ?>
					</select></td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button type="submit">搜 索</button></span></span>
	</div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">排序</td>
			<td width="100">省份</td>
			<td width="100">城市</td>
			<td width="150">网点类型 (服务类型)</td>
			<td>名称</td>
			<td width="120">电话</td>
			<td width="100">操作</td>
		</tr>
		<?php foreach ($address as $key => $value) { ?>
			<tr class="ct">
				<td><?php echo $value['sort']; ?></td>
				<td><?php echo $province[$value['province']]['name']; ?></td>
				<td><?php echo $city[$value['city']]['name']; ?></td>
				<td><?php echo $address_type[$value['address_type']]; ?><?php if ($value['service_type']) echo '--' . $service_type[$value['service_type']]; ?></td>
				<td><?php echo $value['name']; ?></td>
				<td><?php echo $value['tel']; ?></td>
				<td>
					<a href="<?php echo $editUrl; ?>/?id=<?php echo $value['id']; ?>" class="mr10">编辑</a>
					<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
				</td>
			</tr>
		<?php } ?>
	</table>
</div>
<div class="mr10 cc">
	<?php echo $pager; ?>
</div>
<script type="text/javascript">
	$(document).ready(function () {
		var citys = <?php echo json_encode($searchcity);?>;
		setcity = function (province, chval) {
			var options = '<option value="">所有城市</option>';
			$.each(citys, function (index, data) {
				var s = '';
				if (data.parent_id == province) {
					if (data.id == chval) s = 'selected';
					options += '<option value="' + data.id + '" ' + s + '>' + data.name + '</option>';
				}
			});
			$("select[name='city']").html(options);
		}
		setcity(<?php echo $search['province'] ? $search['province'] : 0;?>, <?php echo $search['city'] ? $search['city'] : 0;?>);

		showservice = function (flag) {
			if (flag == 2) {
				$("#service_type").show();
			} else {
				$("#service_type").hide();
			}
		}
		<?php if($search['address_type'] && $search['address_type'] == 2) { ?>
		$("#service_type").show();
		<?php } else { ?>
		$("#service_type").hide();
		<?php }?>
	})
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
