<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li class="current"><a href="<?php echo $listUrl;?>">积分商城</a></li>
        <li><a href="<?php echo $pointPrizeIndexUrl;?>">积分抽奖</a></li>
        <li><a href="<?php echo $presendIndexUrl;?>">人工发放</a></li>
        <li><a href="<?php echo $pointDescIndexUrl;?>">积分说明管理</a></li>
	</ul>
</div>
<div class="h_a">
    <a href="<?php echo $logUrl.'?mall_id='.$goodInfo['id']."&category_id=".$goodInfo['category_id'];?>"><input type="button" value="兑奖码管理"/></a>
</div>
<div class="table_full">
<dl style="display:-webkit-box">
	<dt style="width:64px;height:64px; " >
	<img style="height: 100%;width:auto;" src="<?php echo $goodInfo['img'];?>" alt="" >
	</dt>
	<dd style="padding-left: 64px">
		<p><span class="name">商品名称:<?php echo $goodInfo['title'];?></span></p>
		<p><span class="id">商品分类名称:<?php echo $goodCategory['title'];?></span></p>
	</dd>
</dl>
</div>
<form method="post" action="<?php echo $editExchangeCodePostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="goodId" value="<?php echo $goodInfo['id'];?>" type="hidden" />
<input name="giftExchangeCodeId" value="<?php echo $giftExchangeCodeInfo['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">激活码</th>
			<td class="td"><input type="text" class="input wc" name="activation_code" value="<?php echo $giftExchangeCodeInfo['activation_code'];?>"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Mall_Goods/giftExchangeLog?id=<?php echo $goodInfo['id'];?>');
	});
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
