<?php
$maxSize    = empty($size) ? '2000000' : $size * 1000;
$maxSizeTxt = empty($size) ? '2M' : $size . 'K';
?>
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<title>upload</title>
</head>
<body>
<?php if (!$code && !empty($msg)) { ?>
	<font color=red><?php echo $msg; ?></font> <a href="<?php echo $uploadUrl . '?imgId=' . $imgId; ?>">[返回]</a>
<?php } elseif (!empty($data)) { ?>
	<b>上传成功！</b> <a href="<?php echo $uploadUrl, '?imgId=', $imgId; ?>">[上传]</a>
<?php } else { ?>
	<form id="form1" name="form1" method="post" action="<?php echo $uploadPostUrl; ?>" onsubmit="return checkFrom()"
	      enctype="multipart/form-data">
		<input type="hidden" name="token" value="<?php echo $token; ?>"/>
		<input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $maxSize; ?>"/>
		<input name="imgId" value="<?php echo $imgId; ?>" type="hidden"/>
		<input type="file" id="img" name="img" class="mr20"/>
		<input type="submit" name="sub" value="上传" class="btn"> 允许上传的图片格式为：png jpeg jpg gif
		                                                        且图片大小不能超过<?php echo $maxSizeTxt; ?>
	</form>
<?php } ?>
<script>
	var par = /^.*?\.(jpg|gif|jpeg|png)$/i;
	function checkFrom() {
		if (document.getElementById('img').value == '') {
			window.parent.showError('出错', '请选择要上传的图片');
			return false;
		} else if (!par.test(document.getElementById('img').value)) {
			window.parent.showError('出错', '仅支持JPG、GIF、PNG图片文件，且图片大小不能超过<?php echo $maxSizeTxt; ?>');
			return false;
		} else {
			return true;
		}
	}
	<?php if(!empty($data)){?>
	window.parent.showAttach('<?php echo $imgId;?>', '<?php echo $attachPath.$data;?>', '<?php echo $data;?>');
	<?php }?>
</script>
</body>
</html>
<!-- <?php echo $this->render("layout/footer.phtml"); ?> -->


