<?php echo $this->render("layout/singleheader.phtml");?>
<body id="mjb" data-pagerole="body">
<div class="mjb_main">
    <div class="mjb_top">
        <h1>什么是集分宝?</h1>
        <p>集分宝是支付宝提供的积分服务，支付宝付款时当钱花！100个集分宝=1元。<br/>
            集分宝不支持兑换现金，无法转让和转出到银行卡。</p>
        <h1>如何赚取集分宝?</h1>
        <p class="remind">亲爱的，由于参与人数较多，建议亲在早起的清晨就开始来赚钱喔~</p>
        <p>通过答题获得集分宝，不同店铺赚取的金额也有所不同，成功完成任务后即可获得奖励。</p>
        <div class="mjb_steps steps_bor">
            <div class="steps1">输入淘宝账号和密码，确认登录，跳转到首页即可开始赚钱啦！
            <p class="pic"><img src="<?php echo $staticResPath;?>/pic/mjb/step1.jpg"></p>
            </div>
            <div class="steps2">点击“答题”，进入店铺界面可看到答题任务，如确定回答此问题，点击“
                <span>我要接这个任务</span>”，并注意看题目哦！仔细浏览店铺页面的文字或者图片，手机屏幕滑动至下方，15秒后即可答题，根据所浏览的内容，点击你认为的正确答案即可！
                <p class="pic"><img src="<?php echo $staticResPath;?>/pic/mjb/step2.jpg"></p>
            </div>
            <div class="steps3">如第一次回答错误，则等待15秒后继续答题，如答题成功，则会弹窗提示“恭喜您答对啦！将会获得X集分宝”，届时可以选择<span>订阅提醒该店铺最新活动信息</span>或者<span>回到任务列表</span>继续参与答题。</div>
        </div>
    </div>

    <div class="mjb_bottom">
        <h1 id="J_whatMjbEl">使用前提条件</h1>
        <p id="J_whatMjb" style="display:none;">1、正常状态的淘宝账户。<br/>
            2、淘宝账户已<span>绑定支付宝</span>并<span>通过实名认证</span>，淘宝账户和支付宝账户<span>需正常状态</span>。</p>
        <h1 id="J_howCollectEl">如何使用集分宝?</h1>
        <div id="J_howCollect" style="display:none;">
            <h3 class="cash">集分宝抵现</h3>
            <p>在使用支付宝收银台付款时，选择<span>集分宝来抵扣现金</span>。集分宝满10个即可使用。付款失败，集分宝将不会扣掉，下次可以继续使用。在支付宝付款界面可以查到集分宝抵扣明细，如下图所示：
            <div class="pic biger">
                <img src="<?php echo $staticResPath;?>/pic/mjb/step3.jpg">
            </div>
            </p>
            <div class="steps_bor">
                <h3 class="pay">支付宝客户端支付方式操作</h3>
                <div class="mjb_steps">
                    <div class="steps1">打开支付宝客户端“财富”页面，点击右上角设置，再点击“支付设置”
                        <p class="pic"><img src="<?php echo $staticResPath;?>/pic/mjb/step4.jpg"></p>
                    </div>
                    <div class="steps2">选择“默认付款方式”，然后将“优先使用集分宝”选项打开即可。
                        <p class="pic"><img src="<?php echo $staticResPath;?>/pic/mjb/step5.jpg"></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>