<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $indexUrl;?>">游戏分类列表</a></li>
    <li><a href="<?php echo $subListUrl.'?id='. $parentId;?>">管理子分类</a></li>
    <li class="current"><a href="javascript:;">添加游戏子分类</a></li>
	</ul>
</div>
<div class="h_a">添加游戏子分类</div>
<form method="post" action="<?php echo $addSubPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="parentId" value="<?php echo $parentId;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="0"></td>
		</tr>
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="title" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
			<select name="status" class="select">
				<option value="1">开启</option>
				<option value="0">关闭</option>
			</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Resource_Category/sublist?id=<?php echo $parentId;?>');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
