<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $indexUrl;?>">游戏分类列表</a></li>
    <li><a href="<?php echo $subListUrl . '?id=' . $info['parent_id'];?>">管理子分类</a></li>
    <li class="current"><a href="javascript:;">编辑游戏子分类</a></li>
	</ul>
</div>
<div class="h_a">编辑游戏子分类</div>
<form method="post" action="<?php echo $editSubPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<input name="parentId" value="<?php echo $info['parent_id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="<?php echo $info['sort'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="title" value="<?php echo $info['title'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
			<select name="status" class="select">
				<option <?php if ($info['status'] == 1) echo 'selected';?> value="1">开启</option>
				<option <?php if ($info['status'] == 0) echo 'selected';?> value="0">关闭</option>
			</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Resource_Category/sublist?id=<?php echo $info['parent_id'];?>');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
