<?php echo $this->render("layout/header.phtml");?>
<style>
	.coloum{
		width:200px;
		text-align: center;
	}
	.inner_table tr td{
		padding: 7px 10px 9px;
	}
	.inner_table tr td:hover{
		background: none!important;
	}
	.handpick_mask{
		display: none;
	}
</style>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl.'/?column_version=1.5.2';?>">1.5.2</a></li>
		<li><a href="<?php echo $listUrl.'/?column_version=1.5.3';?>">1.5.3-1.5.7</a></li>
		<li><a href="<?php echo $listUrl.'/?column_version=1.5.8';?>">1.5.8及以上</a></li>
		<li class="current"><a href="javascript:;">新增栏目配置</a></li>
	</ul>
</div>
<div class="step mb10">
		<ul class="cc">
			<li style="width:25%;background: #74B88A;"  ><span class="fl"><em>设置栏目</em></span></li>
			<li class="line" style="left:25%"></li>
			<li style="width:25%;background: #74B88A;"  ><span class="fl"><em>设置频道</em></span></li>
			<li class="line" style="left:50%"></li>
			<li style="width:25%;background: #74B88A;" ><span class="fl"><em>频道排序</em></span></li>
			<li class="line" style="left:75%"></li>
			<li  style="width:25%" class="current"><span class="fl"><em>设置时间</em></span></li>
		
		</ul>
</div>
<div class="h_a">新增栏目配置-<?php echo ($column_version == '1.5.2')?'1.5.2':(($column_version == '1.5.3')?'1.5.3-1.5.7':'1.5.8及以上');?></div>
<form method="post" action="<?php echo $cloumnAttriPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="column_version" value="<?php echo $column_version; ?>" type="hidden"/>
<input name="log_id" value="<?php echo $log_id; ?>" type="hidden"/>
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="column_name" value="" ></td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
			<select name="status" class="select">
                	<option value="1">开启</option>
                	<option value="0">关闭</option>
            </select></td>
		</tr>
		<tr class="tr">
			<th class="th">活动时间</th>
			<td class="td"><div>
				 <label><input id="effect" name="effect" type="checkbox"  value="1" />立即生效 </label> <br />
			<input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="" /> 
			</div>
			</td>
		</tr>
	</table>	
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">完成</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('#start_time').datetimepicker();
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Columnnew/index/？column_version='+ret.data.column_version);
	});
	 $("[name = effect]:checkbox").click(function () {
         if ($(this).is(":checked")) {
        	 $('#start_time').attr('disabled',true);
         }else{
        	 $('#start_time').attr('disabled',false);
         }
     });
})
</script>
<?php echo $this->render("layout/footer.phtml");?>