<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li class="current"><a href="<?php echo $listUrl; ?>">玩咖配置列表</a></li>
		<li><a href="<?php echo $addUrl; ?>">添加玩咖配置</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="120">机型</td>
			<td width="120">浏览器版本</td>
			<td>wk_main_switch</td>
            <td>wk_searchEngines_switch</td>
            <td>wk_hotKeyword_switch</td>
			<td >wk_suggested_switch</td>
			<td width="100">操作</td>
		</tr>
		<?php foreach ($wanka as $key => $value) { ?>
			<tr class="ct">
				<td><?php echo $value['name']; ?></td>
				<td><?php echo $value['app_ver']; ?></td>
				<td><?php echo $value['wk_main_switch'] == 1 ? '开启' : '关闭'; ?></td>
				<td><?php echo $value['wk_searchEngines_switch'] == 1 ? '开启' : '关闭'; ?></td>
				<td><?php echo $value['wk_hotKeyword_switch'] == 1 ? '开启' : '关闭'; ?></td>
				<td><?php echo $value['wk_suggested_switch'] == 1 ? '开启' : '关闭'; ?></td>
				<td>
					<a href="<?php echo $editUrl; ?>/?id=<?php echo $value['id']; ?>" class="mr10">编辑</a>
					<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
				</td>
			</tr>
		<?php } ?>
	</table>
</div>
<?php echo $this->render("layout/footer.phtml"); ?>
