<?php echo $this->render("layout/admin_header.phtml");?>
	<div class="body">
	<h1 class="page-title" >管理后台</h1>
		<?php echo $this->render("layout/side.phtml");?>
		
		<div class="col-main">
			<div class="J_gift_error_tips error-pop-tips hidden">
			</div>
			<div class="keyword-body">
			<form name="editpassword" action="<?=$editPasswdPostUrl?>" method="post">
			<input type="hidden" name="token" value="<?=$_COOKIE['_securityCode']?>">
				<h2 class="title">修改您的登录密码</h2>
				<div class="keyword-edit-container">
					<div class="keyword-column-container">
						<span class="text">原密码:</span>
						<div class="keyword-container">
							<input id="oldpassword" name="oldpassword" class="input"  type="password" value=""/>
						</div>
					</div>
					
					<div class="keyword-column-container">
						<span class="text">新密码:</span>
						<div class="keyword-container">
							<input id="newpassword" name="newpassword" class="input" type="password" value=""/>
						</div>
					</div>
					<div class="keyword-column-container">
						<span class="text">重复新密码:</span>
						<div class="keyword-container">
							<input id="renewpassword" name="renewpassword" class="input" type="password" value=""/>
						</div>
					</div>
					
					<div class="btn-container">
						<button name="submit" type="submit" class="btn">保存</button>
					</div>
				</div>
			</form>
			</div>
		</div>
		
	</div>
	<?php echo $this->render("layout/footer.phtml");?>
<script type="text/javascript">
    $(document).ready(function() {
    	$("form").submit(function(e){
        	if($('#oldpassword').val() == '') {
				alert('	请输入旧密码');
				return false;
        	}
        	if($('#newpassword').val() !== $('#renewpassword').val() || $('#newpassword').val() == '') {
				alert('两次输入的密码不一致或为空');
				return false;
        	}
  		});
    });
</script>
</body>
</html>