<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $newUrl;?>">最新发布</a></li>
	    <li class="current"><a href="<?php echo $listUrl;?>">下载最多/周榜</a></li>
	     <li><a href="<?php echo $monthUrl;?>">月榜</a></li>
             <li><a href="<?php echo $olrankUrl;?>">网游活跃榜</a></li>
	    <li><a href="<?php echo $soaringUrl;?>">游戏飙升榜</a></li>
        <li><a href="<?php echo $setUrl;?>">排行榜设置</a></li>
        <li><a href="<?php echo $manUrl;?>">排行榜管理</a></li>
	</ul>
</div>
<form method="post" action="<?php echo $listUrl;?>">
<input name="token" value="<?php echo $token;?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">时间</th>
				<td class="td">
				   <input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo $start_time;?>" />
				</td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<div class="h_a">
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">ID</td>
			<td>标题</td>
			<td>图标</td>
			<td>分类</td>
			<td>专题</td>
			<td width="80">下载量</td>
			<td width="120">版本</td>
			<td width="120">大小</td>
			<td width="120">上线时间</td>
			<td width="120">状态</td>
		</tr>
<?php foreach($games as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['name'];?></td>
			<td><img src="<?php echo $value['img'];?>" style="width:70px;height:70px;"/></td>
			<td><?php echo implode($category_title[$value['id']], ',');?></td>
			<td><?php echo implode($game_subjects[$value['id']], ',');?></td>
			<td><?php echo $bi_games[$value['id']]['dwnload'];?></td>
			<td><?php echo $value['version'];?></td>
		    <td><?php echo $value['size'];?>M</td>
		    <td><?php echo date('Y-m-d H:i:s', $value['online_time']);?></td>
			<td><?php echo $value['status'] == 1 ? '已上线' : '已下线';?></td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
	ajaxForm('editForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Rank/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
