<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<meta name="format-detection" content="email=no" />

<link rel="stylesheet" href="<?php echo "$appCss/main$source.css$timestamp";?>" />
<script>var t_bi='abcdef123456';var token='<?php echo $token?>';var attachroot='<?php echo $attachroot?>';</script>