<?php echo $this->render("layout/webheader.phtml");?>
<body>
<div class="module">
    <section id="iScroll">
        <div id="J_story_detail" class="story-detail">
        	<div class="gotop gotop-custom">
        		<span>返回顶部</span>
        	</div>
            <h1><?php echo $data['title'] ?></h1>
            <div class="sub">
            
            <?php 
            if(date('Y-m-d',$data['start_time'])!=date("Y-m-d")) {
                 echo date('Y-m-d',$data['start_time']);
             }  else {
                echo date('Y-m-d H:i',$data['start_time']);
                }
             ?>
                 <span><?php echo $data['author']; ?></span></div>
            <div class="detail">
                <?php  echo html_entity_decode($data['content']); ?>
            </div>
        </div>
        <article id="J_story_comments" class="story-comments" data-item="<?php echo $data['id'];?>">
            <div class="title-bar">
                <h2><i class="icon-message-orange"></i>评论</h2>
            </div>
            <article class="comments-list custom"></article>
        </article>
    </section>
    <?php echo $this->render("layout/tj.phtml");?>
</div>
</body>
</html>