<?php echo $this->render("layout/header.phtml");?>
<script>
var token = '<?php echo $token;?>';
</script>
<div id="page" class="superfile">
		<article class="ac">
			<div class="item-box cla">
				<ul>
				    <li>
						<a href="<?php echo $webroot.'/super/category/detail/?id=0&intersrc=CATEGORY00&t_bi='.$source;?>">
							<div class="pic"><img src="<?php echo $attachPath. $configs['game_img'];?>" alt=""></div>
						</a>
					</li>
					<?php 
					 foreach($categorys as $key=>$value){
                     if($value['id'] < 10){
                     	$t_id = 'CATEGORY0'.$value['id'];
                     } else {
                     	$t_id = 'CATEGORY'.$value['id'];
                     }
  ?>
					 
					<li>
						<a href="<?php echo $webroot.'/super/category/detail/?id='.$value['id'].'&intersrc='.$t_id.'&t_bi='.$source;?>">
							<div class="pic"><img src="<?php echo $attachPath. $value['img'];?>" alt=""></div>
						</a>
					</li>
					<?php }?>
				</ul>
			</div>
			<?php if($hasnext) {?>
			<div class="load-more J_loadMore" data-ajaxUrl="<?php echo $webroot.'/super/category/more/?t_bi='.$source;?>" data-hasnext="<?php echo $hasnext;?>" data-curpage="<?php echo $page;?>" data-curClass="<?php echo $tid;?>">
				<span>加载更多</span>
			</div>
			<?php }?>
		</article>

		<footer class="ft">
			<div class="back-top"><a class="btn" href="#top">返回顶部</a></div>
		</footer>
	</div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>