<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
		<li class="current"><a href="<?php echo $configUrl?>">转盘抽奖配置</a>
		<li class=""><a href="<?php echo $snatchConfigUrl?>">夺宝奇兵配置</a>
		<li class=""><a href="<?php echo $answerConfigUrl?>">答题配置</a>
	</ul>
</div>
<div class="h_a">基本配置：</div>
<form method="post" action="/Admin/Ulottery/config" id="addFrom">
<input name="token" id="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">	
		<tr class="tr">
			<th class="th">单次抽奖消耗金币数</th>
			<td class="td"><input  type="text"  value="<?php echo max(0,$data['ulottery_per_cosume']);?>"  name="ulottery_per_cosume"  class="input"></td>
		</tr>
		
		<tr class="tr">
			<th class="th">单天免费抽奖次数</th>
			<td class="td"><input  type="text"  value="<?php echo max(0,$data['ulottery_free_times']);?>"  name="ulottery_free_times"  class="input"></td>
		</tr>
		
		<tr class="tr">
			<th class="th">单天消耗金币最大抽奖次数</th>
			<td class="td"><input  type="text"  value="<?php echo max(0,$data['ulottery_max_times']);?>"  name="ulottery_max_times"  class="input"></td>
		</tr>
		
			<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
			<select name="ulottery_status" >
			<option value="1"   <?php if($data['ulottery_status'] == 1) echo 'selected';?>>开启</option>
			<option value="0"    <?php if($data['ulottery_status'] == 0) echo 'selected';?>>关闭</option>
			</select>
			</td>
		</tr>
		
		<tr class="tr">
			<th class="th">规则说明</th>
			<td class="td"><textarea rows="6" cols="10" name="ulottery_rule_content"  style="width: 600px; height:400px;"><?php echo $data['ulottery_rule_content'];?></textarea></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/admin/kindeditor/kindeditor.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 var editor;
	 	KindEditor.ready(function(K) {
	 		K.token = $('#token').val();
	 	    editor = K.create('textarea[name=""ulottery_rule_content""]', {
	 	        resizeType : 1,
	 	        allowPreviewEmoticons : false,
	 	        allowImageUpload : true,
	 	        uploadJson : '<?php echo $uploadImgUrl;?>',
	 	        items : EDITOR_ITEMS
	 	    });
	 	});
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Ulottery/config');
	},function(){
  		editor.sync();
  	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
