<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
		<li><a href="<?php echo $couponListUrl; ?>">书券列表</a></li>
		<li  class="current"><a href="<?php echo $conponUrl; ?>">数据导入</a></li>
		<li><a href="<?php echo $manualUrl; ?>">人工赠送书券</a></li>
		</ul>
	</div>
	<div class="h_a">数据导入</div>
	<form method="post" action="<?php echo $conponUrl; ?>" id="addFrom" enctype="multipart/form-data">
		<input name="token" value="<?php echo $token; ?>" type="hidden"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">选择文件</th>
					<td class="td"><input type="file" class="input" name="data" value=""></td>
					<td class="td"><a href="<?php echo $exportUrl; ?>">导出</a></td>
				</tr>
			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
	</form>

	<script type="text/javascript">
		//广告表单数据提交
		$(document).ready(function () {
			ajaxForm('addFrom', function (ret) {
				ajaxRedirect(ret, baseurl + '/Admin/Ulottery/coupon');
			});
		});
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>