<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li><a href="<?php echo $indexUrl; ?>">奖品列表</a></li>
			<li class="current"><a href="<?php echo $editUrl; ?>">添加奖品</a></li>
			<li><a href="<?php echo $sindexUrl; ?>">夺宝奇兵奖品</a></li>
			<li><a href="<?php echo $seditUrl; ?>">添加夺宝奇兵奖品</a></li>
		</ul>
	</div>
	<div class="table_list">
		<form method="post" action="<?php echo $editPostUrl; ?>" id="addForm">
			<input name="token" value="<?php echo $token; ?>" type="hidden"/>

			<div class="table_full">
				<table style="width: 100%">
					<tr class="tr">
						<th class="th">奖品名称</th>
						<td class="td"><input name="name" id="name" class="input" value="<?php echo $data['name']; ?>">
						</td>
					</tr>
					<tr class="tr">
						<th class="th">奖品等级</th>
						<td class="td">
							<select name="level">
								<option>请选择</option>
								<?php foreach ($levels as $k => $v) { ?>
									<option value="<?php echo $k; ?>" <?php if ($k == $data['level']) echo 'selected'; ?>><?php echo $v; ?></option>
								<?php } ?>
							</select>
						</td>
					</tr>
					<tr class="tr">
						<th class="th">数量</th>
						<td class="td">
							<input name="number" id="number" class="input" value="<?php echo $data['number']; ?>"></td>
					</tr>
					<tr class="tr">
						<th class="th">奖品类型</th>
						<td class="td">
							<select name="type">
								<?php foreach ($prizeTypes as $k => $v) { ?>
									<option value="<?php echo $k; ?>" <?php if ($data['key'] == $k) echo 'selected'; ?>><?php echo $v; ?></option>
								<?php } ?>
							</select>
						</td>
					</tr>

					<tr class="tr">
						<th class="th">获得金币数</th>
						<td class="td"><input name="val" id="val" class="input" value="<?php echo $data['val']; ?>">
						</td>
					</tr>

					<tr class="tr">
						<th class="th">中奖概率</th>
						<td class="td">
							<input name="ratio" id="ratio" class="input" value="<?php echo $data['ratio']; ?>"></td>
					</tr>

					<tr class="tr">
						<th class="th">排序</th>
						<td class="td">
							<input name="sort" id="" sort"" class="input" value="<?php echo $data['sort']; ?>">
						</td>
					</tr>

					<tr class="tr">
						<th class="th">图片</th>
						<td class="td">
							<ul class="uploadImg">
								<li id="lotteryImage">
									<?php if ($data['image']) { ?>
										<img src="<?php echo $attachPath . $data['image']; ?>"/>
									<?php } else { ?>
										<img src="<?php echo $staticPath; ?>/img/content/nopic.jpg"/>
									<?php } ?>
									<input type="hidden" name="image" value="<?php echo $data['image']; ?>">
								</li>
							</ul>
							<p style="clear:both;">
								<iframe name="upload" src="<?php echo $uploadUrl . '/?imgId=lotteryImage'; ?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
							</p>
						</td>
					</tr>
					<tr class="tr">
						<th class="th">状态</th>
						<td class="td">
							<select name="status">
								<option value="1"   <?php if ($data['status'] == '1') echo 'selected'; ?>>开启</option>
								<option value="0"   <?php if ($data['status'] == 0) echo 'selected'; ?>>关闭</option>
							</select>
						</td>
					</tr>

				</table>
				<div class="mb10 tac">
					<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
				</div>
				<input type="hidden" value="<?php echo $data['id']; ?>" name="id">
			</div>
		</form>
	</div>

	<script type="text/javascript">
		//用户表单数据提交
		$(document).ready(function () {
			ajaxForm('addForm', function (ret) {
				ajaxRedirect(ret, baseurl + '/Admin/Ulottery/index');
			});
		})
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>