<?php echo $this->render("layout/header.phtml");?>
<script>
var token = '<?php echo $token;?>';
</script>
<body>
<div id="list-page">
	<section class="wrap">
		<div class="item-list J_gameItem">
			<ul>
				<?php foreach($resource_games as $key=>$value) {?>
				<?php 
				    $location = '';
				    $intersrc = 'CATEGORY'.$id.'_GID'.$value['id'];
				    if($key <=2) $location = '&location='.($key + 1);
				    $href = $webroot.'/client/index/detail/?id='.$value['id'].'&pc=1&intersrc='.$intersrc.'&t_bi='.$source.$location;
				    $evaluateStr = '';
				    if ($value['pc_info']){
					 	$evaluateStr = ',评测,' . $webroot.'/client/evaluation/detail/?id='.$value['pc_info'].'&pc=3&intersrc='.$intersrc.'&t_bi='.$source;
					}
					if (($checkver >= 2)) {
						$data_info = '游戏详情,'.$href.','.$value['id'] . $evaluateStr;
					} else {
						$data_info = $value['name'].','.$href.','.$value['infpage'];
					}
				  ?>
				<li>
					<a <?php if ($checkver >= 2) {?> data-type = '1' <?php }?> data-infpage="<?php echo $data_info;?>">
						<span class="icon"><img src="<?php echo $staticResPath; ?>/pic/blank.gif" alt="" data-src="<?php echo $value['img'];?>"></span>
						<span class="desc">
							<em><?php echo $value['name'];?></em>
							<p>
							<em>大小：<?php echo $value['size'].'M';?></em>
							<em class="tips">
							<?php if ($checkver >= 2) {?> 
								<?php if ($value['pc_info']) {?><span class="comment">评</span> <?php }?>
								<?php if ($value['gift_info']) {?> <span class="gift">礼</span> <?php } ?>
								<?php if ($value['device']) {?> <span class="grip">游戏手柄</span> <?php } ?>
							<?php }?>
							 </em>
							</p>
							<b><?php echo $value['resume'];?></b>
						</span>
					</a>
				</li>
				<?php }?>
			</ul>
		</div>
	</section>
   <?php if($hasnext){ ?>
		<div class="loading J_loadMore" style="display:none;" data-ajaxUrl="<?php echo $webroot.'/client/category/moreCt/?id='.$id.'&intersrc='.$intersrc.'&t_bi='.$source.'&sp='.$sp;?>" data-hasnext="<?php echo $hasnext;?>" data-curpage="<?php echo $page;?>">
			<span class="load"></span>
		</div>
  <?php } ?>
</div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>