<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    	<li class="current"><a href="<?php echo $indexUrl;?>?cate_id=<?php echo $cate_id;?>">商品专题列表</a></li>
		<li><a href="<?php echo $addUrl;?>?cate_id=<?php echo $cate_id;?>">添加商品专题</a></li>
	</ul>
</div>

<form action="<?php echo $indexUrl;?>?cate_id=<?php echo $cate_id;?>" method="get" id="searchForm" >
	<input name="token" type="hidden" value="<?php echo $token;?>"/>
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">商品专题名称</th>
				<td class="td">
					<div>
						<input class="input wc" type="text" id="title" name="title" value="<?php echo $params['title'];?>" />
					</div>
				</td>
				<th class="th">商品专题类型</th>
				<td class="td">
					<div>
                        <select name="type_id" class="input wc">
                            <option value="">全部</option>
                            <?php foreach($typeids as $key=>$val): ?>
                                <option value="<?php echo $key ?>" <?php if($params['type_id']==$key) echo 'selected="selected"'; ?>><?php echo $val; ?></option>
                            <?php endforeach; ?>
                        </select>
					</div>
				</td>
			</tr>
            <tr class="tr">
				<th class="th">商品专题分类</th>
				<td class="td">
					<div>
                        <select name="cate_id" class="input wc">
                            <option value="">全部</option>
                            <?php foreach ($category as $key=>$val):?>
                                <option value="<?php echo $key;?>" <?php if ($key == $params['cate_id']) echo 'selected="selected"';?>><?php echo $val;?></option>
                            <?php endforeach; ?>
                        </select>
					</div>
				</td>
				<td class="td" colspan="2">
					<div>
						<div class="mb10 tac" style="display: inline;"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
					</div>
				</td>
			</tr>
		</table>
	</div>
</form>

<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">排序</td>
			<td width="30">ID</td>
			<td width="150">名称</td>
			<td width="100">类型</td>
			<td width="100">分类</td>
			<td width="100">图片</td>
			<td width="100">开始时间</td>
			<td width="100">结束时间</td>
			<td width="50">点赞数</td>
			<td width="50">总点击量</td>
			<td width="30">状态</td>
			<td width="120">操作</td>
		</tr>
		<?php if(!empty($list)): foreach ($list as $val):?>
		<tr class="ct">
			<td><?php echo $val['sort'];?></td>
			<td><?php echo $val['id'];?></td>
			<td><?php echo $val['title'];?></td>
            <td><?php echo $typeids[$val['type_id']];?></td>
            <td><?php echo $category[$val['cate_id']];?></td>
			<td><img src="<?php echo $attachPath . $val['img'];?>" width=52/></td>
			<td><?php if(!empty($val['start_time'])) echo date('Y-m-d H:i:s', $val['start_time']);?></td>
			<td><?php if(!empty($val['end_time'])) echo date('Y-m-d H:i:s', $val['end_time']);?></td>
			<td><?php echo $val['praise'] ?></td>
			<td><a href="/admin/stat/click?type_id=27&item_id=<?php echo $val['id'];?>" target="_blank"><?php echo $val['hits'];?></a></td>
			<td><?php echo $val['status'] == 1 ? '开启' : '关闭';?></td>
			<td>
				<a href="<?php echo $goodsUrl;?>/?topic_id=<?php echo $val['id'];?>" class="mr10">关联商品</a>
				<a href="<?php echo $editUrl;?>/?cate_id=<?php echo $cate_id;?>&id=<?php echo $val['id'];?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $val['id'];?>', '', event);">删除</a>
			</td>
		</tr>
		<?php endforeach; endif;?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>

<script type="text/javascript">
//导购表单数据提交
$(document).ready(function(){
     submitForm = function() {
  		$("#searchForm").submit();
  	};
})
</script>

<?php echo $this->render("layout/footer.phtml");?>