<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">发布员列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加发布员</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="80">发布员ID</td>
			<td width="250">UID</td>
			<td width="250">昵称</td>
			<td width="250">用户名</td>
			<td width="250">封面图</td>
            <td width="120">操作</td>
		</tr>
<?php foreach($data as $key => $value) {?>
		<tr class="ct <?php if($value['status']) echo 'blue';?>">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['uid']?></td>
			<td><?php echo $value['nickname']?></td>
			<td><?php echo $value['username']?></td>
			<td><?php if($value['avatar']) {?><img src="<?php echo $attachPath.$value['avatar']; ?>" height="24" /><?php }?></td>

			<td>
				<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>

