<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $indexUrl;?>">教程列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加教程</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>" method="get">
    <input name="token" type="hidden" value="<?php echo $token;?>" />
    <div class="table_full">
        <table width="100%">
            <tr class="tr">
                <th class="th">标题</th>
                <td class="td">
                    <input class="input" type="text"   name="title"  value="<?php echo $param['title'];?>" >
                </td>
            </tr>
        </table>
    </div>
    <div class="mb10 tac">
		<span class="btn">
			<span>
				<button type="submit">搜 索</button>
			</span>
		</span>
    </div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
            <td width="64">ID</td>
			<td width="100">标题</td>
            <td width="40">点击</td>
            <td width="100">操作</td>
		</tr>
<?php foreach($data as $key => $value) {?>
		<tr class="ct <?php if($value['status']) echo 'blue';?>">
            <td><?php echo $value['id'];?></td>
			<td><?php echo $value['title']?></td>
            <td><a href="/admin/stat/click?type_id=29&item_id=<?php echo $value['id'];?>" target="_blank"><?php echo $value['hits'];?></a></td>
			<td>
                <a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
                <a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
            </td>
		</tr>
<?php } ?>
	</table>
</div>

<div class="mr10 cc">
<?php echo $pager;?>
</div>

<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script>
$(function(){
    $('a.active_btn').click(function(){
        var data = {};
        data.id  = $(this).data('id');
        data.token  = '<?php echo $token; ?>';
        data.status  = $(this).data('status');
        $.ajax({
            url:'<?php echo $activeUrl ?>',
            type:'post',
            data:data,
            dataType:'json',
            success:function(res){
                if(res.success==true){
                    window.location.reload();
                }
            }
        });
    });
   $('a.top_btn').click(function(){
       var data = {};
       data.id  = $(this).data('id');
       data.token  = '<?php echo $token; ?>';
       data.type  = $(this).data('type');
       $.ajax({
           url:'<?php echo $topUrl ?>',
           type:'post',
           data:data,
           dataType:'json',
           success:function(res){
               if(res.success==true){
                    window.location.reload();
               }
           }
       });
   });

});


$(document).ready(function() {
    $("#to_time").datepicker({
        dateFormat : 'yy-mm-dd'
    });

    $("#from_time").datepicker({
        dateFormat : 'yy-mm-dd'
    });
});
</script>
<?php echo $this->render("layout/footer.phtml");?>

