<?php echo $this->render("layout/webheader.phtml");?>
<body data-pagerole="body">
	<div class="module">
<?php if($hasheader){?>
		<header id="iHeader" class="hd">
			<div class="top-wrap">
				<div class="title">
					<h1>订单状态</h1>
					<span class="voice"></span>
				</div>
			</div>
		</header>
<?php }?>
		<section id="iScroll">
			<div class="success-box">
				<div class="tip">
					<div class="ico"><span<?php if($result['code'] == 3 || $result['status'] == 6){?> class="fail"<?php }?>></span></div>
					<p><?php echo $result['msg']; ?></p>
					<p>订单号：<?php echo $order['trade_no']?></p>
				</div>
				<div class="web-btn">
<?php if($result['code'] == 3 && $order['pay_type'] == 1){?>
				<a href="<?php echo $webroot;?>/recharge/pay?out_order_no=<?php echo $order['out_trade_no'];?>">继续支付</a>
<?php }?>
				</div>
			</div>
		</section>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>