<?php echo $this->render("../../Front/views/layout/header.phtml");?>
<section id="page">
	<header id="header"><!-- HEADER --></header>
	<!-- 主体内容 -->
	<section id="content">
		<section class="order">
			<div class="pcnee mod-form-list">
				<form action="<?php echo $webroot.$editaddressPostUrl.'?id=',$user_info['id'];?>" method="post" id="J_checkForm">
					<div class="field"><label>收&nbsp;&nbsp;货&nbsp;&nbsp;人：</label><input type="text" name="cneename" autocomplete="off" value="<?php echo $user_info['username']?>" /></div>
					<div class="field"><label>手机号码：</label><input type="text" name="phone" autocomplete="off" value="<?php echo $user_info['mobile']?>" /></div>
					<div class="field">
						<label>省&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;份：</label><select>
							<option><?php echo $adress['province']?></option>
						</select>
					</div>
					<div class="field">
						<label>城&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;市：</label><select>
							<option><?php echo $adress['city'];?></option>
						</select>
					</div>
					<div class="field"><label>详细地址：</label><input type="text" name="address" autocomplete="off" value="<?php echo $adress['detail_address'];?>" /></div>
					<div class="field">
						<label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;编：</label><input type="text" name="code" autocomplete="off" value="<?php echo $adress['postcode'];?>" />
					</div>
					<div class="field button"><button type="submit" class="btn orange">保存</button></div>
				</form>
			</div>
		</section>
	</section>
	<!--  /主体内容 -->
	<footer id="footer"><!-- FOOTER --></footer>
</section>
</body>
</html>