<?php echo $this->render("../../Front/views/layout/header.phtml");?>
<section id="page">
	<header id="header"><!-- HEADER --></header>
	<!-- 主体内容 -->
	<section id="content">
		<section class="account">
			<div class="pinfo mod-form-list">
				<form action="<?php echo $webroot.$userinfoPostUrl;?>" method="post" id="J_checkForm">
					<input type="hidden" name="id" value="<?php echo $user['id'];?>"/>
					<input type="hidden" name="token" value="<?php echo $token;?>"/>
					<div class="field"><label>账 号 ：</label><?php echo $user['username'];?></div>
					<div class="field"><label>用户名 ：</label><input type="text" name="username" autocomplete="off" value="<?php echo $user['realname'];?>" /></div>
					<div class="field">
						<label>性别 ：</label>
						<input <?php if($user['sex'] == 0) echo 'checked';?>  name="sex" value="0" type="radio"> 男
						<input <?php if($user['sex'] == 1) echo 'checked';?>  name="sex" value="1" type="radio"/> 女
					</div>
					<div class="field">
						<label>生日 ：</label>
						<select name="year">
						<?php $birthday = explode('-', $user['birthday']);?>
						<?php for ($i = 1960; $i <= date('Y', Common::getTime()); $i++){ ?>
						  <option <?php if($i == $birthday[0]) echo 'selected';?> ><?php echo $i;?></option>
						<?php } ?>
						</select>年
						<select name="month">
						<?php for ($i = 1; $i <= 12; $i++){ ?>
						   <option <?php if($i == $birthday[1]) echo 'selected';?> ><?php echo $i<10?'0'.$i:$i;?></option>
						<?php } ?>   
						</select>月
						<select name="day">
						   <?php for ($i = 1; $i <= 31; $i++){ ?>
						   <option <?php if($i == $birthday[2]) echo 'selected';?> ><?php echo $i<10?'0'.$i:$i;?></option>
						   <?php } ?>  
						</select>日
					</div>
					<div class="field button"><button type="button" id="J_saveForm" class="btn orange">确认</button></div>
				</form>
			</div>
		</section>
	</section>
	<!--  /主体内容 -->
	<footer id="footer"><!-- FOOTER --></footer>
</section>
</body>
</html>