<?php echo $this->render("layout/newheader.phtml");?>
<body class="bg-coin-success">
	<div id="page">
		<div class="paccount" id="iscrollWrap">
			<div class="mainWrap">
				<!-- 内容区域 START-->
				<!-- 主体内容 -->
				<section class="psuccess">
					<div class="coin-success">
						<div class="txt">
							<h3>可领取<span class="zt-orange"><?php echo $rule['first'] + ($rule['later'] * $rule['times'])?></span>银币</h3>
							<p>在积分换购区中银币可充当现金使用，<span class="zt-orange">1银币=1人民币</span></p>
							<p>注册为购物大厅用户赠送<?php echo $rule['first'] + ($rule['later'] * $rule['times'])?>银币，即时可用<?php echo $rule['first'];?>银币。</p>
							<p>积分换购专区开启时间：2012年12月30日<p>
							<div class="button"><a href="javascript:void(0);" data-ajaxUrl="<?php echo $webroot,'/user/account/gain_post';?>" id="J_getCoinLink" class="btn orange">马上领取</a></div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
</body>
</html>