<?php echo $this->render("layout/newheader.phtml");?>
<div id="page">
		<div id="iscrollWrap">
			<div class="mainWrap">
				<?php if ($hasheader) {?>
		        <header id="iHeader" class="hd">
					<div class="top-wrap">
						<div class="title">
							<a href="<?php echo $webroot.'/user/account/index';?>" class="back"></a>
							<h1>金币使用规则</h1>
						</div>
					</div>
				</header>
		        <?php }?>
		        
				<!-- 内容区域 START-->
				<section class="precord">
					<div class="record-wrap">
						<ul class="mod-item-list">
							<li class="zt-orange">金币在积分换购专区中可以无限制使用。</li>
							<li>1金币=1人民币。<br />积分获取:<br /><br />
								<p style="text-align:right;">敬请期待！</p>
							</li>
						</ul>
					</div>
				</section>
				<!-- 内容区域 END-->
			</div>
		</div>
</div>
</body>
</html>