<?php echo $this->render("layout/newheader.phtml");?>
<div id="page">
		<div id="iscrollWrap">
			<div class="mainWrap">
				<?php if ($hasheader) {?>
		        <header id="iHeader" class="hd">
					<div class="top-wrap">
						<div class="title">
							<a href="<?php echo $webroot.'/user/account/index';?>" class="back"></a>
							<h1>银币使用规则</h1>
						</div>
					</div>
				</header>
		        <?php }?>
		        
				<!-- 内容区域 START-->
				<section class="precord">
					<div class="record-wrap">
						<ul class="mod-item-list">
							<li>如何使用银币?</li>
							<li>1. 1银币=1人民币<br/>
								2. 银币在积分换购专区中可以根据商品使用限额抵现使用。</li>
						</ul>
					</div>
					<div class="record-wrap mr10">
						<ul class="mod-item-list">
							<li>如何获取银币?</li>
							<li> 在购物大厅中非积分换购专区购物，可获得一定的积分奖励，在您确认收货后，奖励的积分将进入您的账号中。</li>
						</ul>
					</div>
				</section>
				<!-- 内容区域 END-->
			</div>
		</div>
	</div>
</body>
</html>