<!DOCTYPE HTML>
<html>
<head>
	<meta charset="UTF-8">
	<title></title>
	<style type="text/css">
	html{font-size:13.3px; -webkit-text-size-adjust:none;}
	@media all and (min-width:360px){html{font-size:15px;}}
	*{margin:0; padding:0;}
	body{font:1rem/1 \5FAE\8F6F\96C5\9ED1,\5b8b\4f53,Tahoma,Helvetica,Arial,sans-serif;}

	.button{margin:.75rem 0 .35rem; text-align:center;}
	.button a{color:#666; text-decoration:none;}
	.button .btn {
	display: inline-block;
	width: 6rem;
	padding: 0 .5rem;
	height: 2.85rem;
	line-height: 2.85rem;
	font-size: 1.2rem;
	-webkit-user-select: none;
	text-align: center;
	color: #fff;
	vertical-align: top;
	-webkit-border-radius: 3px;
	-moz-border-radius: 3px;
	-ms-border-radius: 3px;
	-o-border-radius: 3px;
	border-radius: 3px;
	text-shadow: 0 1px 1px rgba(255, 255, 255, 0.2);
	}
	.button .gray {
	color: #555555;
	font-size: 1.2rem;
	display: inline-block;
	width: 70%;
	height: 3rem;
	line-height: 3rem;
	border: 1px solid #f4f4f4;
	border-top: 1px solid #fff;
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	-ms-border-radius: 5px;
	-o-border-radius: 5px;
	border-radius: 5px;
	background-color: #e5e5e5;
	background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #f4f4f4), color-stop(100%, #e5e5e5));
	background-image: -webkit-linear-gradient(top, #f4f4f4, #e5e5e5);
	background-image: -moz-linear-gradient(top, #f4f4f4, #e5e5e5);
	background-image: -o-linear-gradient(top, #f4f4f4, #e5e5e5);
	background-image: linear-gradient(top, #f4f4f4, #e5e5e5);
	-webkit-box-shadow: 0 1px 1px 1px #b1b1b1;
	-moz-box-shadow: 0 1px 1px 1px #b1b1b1;
	box-shadow: 0 1px 1px 1px #b1b1b1;
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	box-sizing: border-box;
	}
	.button .gray:active {
	background-color: #f4f4f4;
	background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #e5e5e5), color-stop(100%, #f4f4f4));
	background-image: -webkit-linear-gradient(top, #e5e5e5, #f4f4f4);
	background-image: -moz-linear-gradient(top, #e5e5e5, #f4f4f4);
	background-image: -o-linear-gradient(top, #e5e5e5, #f4f4f4);
	background-image: linear-gradient(top, #e5e5e5, #f4f4f4);
	}
	</style>
</head>
<body>
	<div class="button">
	<?php if ($user) {?>
			<a href="javascript:top.window.location.href='<?php echo $webroot,'/user/account/index?return='.$curPageUrl?>';" class="btn gray">账号:<?php echo $user['username'];?></a>
		<?php } else {?>
			<a href="javascript:top.window.location.href='<?php echo $webroot,'/user/login/login_step?refer='.$curPageUrl.'&return='.$curPageUrl;?>';" class="btn gray">注册/登录</a>
		<?php }?>
	</div>
</body>
</html>