<html lang="en">
<head>
	<meta charset="UTF-8">
	<title><?php echo $festivalInfo['title'].($subTitle?('-'.$subTitle):''); ?></title>
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="format-detection" content="email=no" />
	<link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/events/medalEvent/assets/css/main.source.css?v=<?php echo $version;?>" />
	<script>var t_bi='abcdef123456';
	        var token='<?php echo $token?>';
	        var festivalId = '<?php echo $festivalInfo['id'];?>';
	        var clientVersion = '<?php echo $limitClientVersion; ?>';
	</script>	
	<script src="<?php echo $staticroot; ?>/apps/game/events/medalEvent/assets/js/sys/zepto.js?v=<?php echo $version;?>" ></script>
    <script src="<?php echo $staticroot; ?>/apps/game/events/medalEvent/assets/js/sys/Common.js?v=<?php echo $version;?>"></script>
    <script src="<?php echo $staticroot; ?>/apps/game/events/medalEvent/assets/js/main.source.js?v=<?php echo $version;?>" ></script>
</head>