<?php echo $this->render("layout/header.phtml");?>
	<div id="page">
		<article class="ac">
			<div class="slide-pic">
				<div class="slideWrap">
					<?php foreach ($subjects as $key=>$value) {?>
					<div class="pic">
						<a><img class="lazy" data-lazyload="true" data-src="<?php echo $attachPath . $value['img'];?>"></a>
					</div>
					<?php }?>
				</div>
			</div>
			
			<div class="home-list item-list J_itemList clearfix" data-hasnext="<?php echo $hasnext; ?>" data-ajaxUrl="<?php echo $webroot.'/index/more';?>">
				<ul>
<?php 
$i = 1;
foreach($list as $key=>$value){
$pre = $next = 1;
if ($i == 1) $pre = 0;
if ($file_total == $i) $next = 0;
if ($i%$perpage == 0 && ($file_total - ($page * $perpage) == 0) ) $next = 0;
if($value['channel_id'] == 1) {
	$out_id = $file_data[$value['channel_id']][$value['file_id']]['out_id'];
	$icon = $file_data[$value['channel_id']][$value['file_id']]['icon'];
	$link = sprintf("%s/detail?id=%d&out_id=%d&channel=%d&pre=%d&next=%d&update_time=%d&refer=%s&version=%d",$webroot, $value['id'], $out_id, $value['channel_id'], $pre, $next, $file_data[$value['channel_id']][$value['file_id']]['update_time'], 'index', $kernel_list[$out_id]['res_version']);
} else {
	$icon = $attachPath.$file_data[$value['channel_id']][$value['file_id']]['icon'];
	$link = sprintf("%s/detail?id=%d&channel=%d&pre=%d&next=%d&update_time=%d&refer=%s",$webroot,$value['id'], $value['channel_id'], $pre, $next, $file_data[$value['channel_id']][$value['file_id']]['update_time'], 'index');
}
?>
					<li>
						<a <?php if (in_array($value['id'], $newsubjects)) echo "class='isnew'"; ?> 
						 data-inftheme="<?php echo $value['title']?>,<?php echo $link;?>,<?php echo $webroot.$downloadUrl.'?id='.$value['id'];?>">
							<div class="pic"><img class="lazy" src="<?php echo $staticResPath;?>/pic/pic_nopreview.jpg" data-lazyload="true" data-src="<?php echo $icon;?>" /></div>
							<div class="desc">
								<h3><?php echo $value['title'];?></h3>
							</div>
						</a>
					</li>
<?php 
$i++;
}
?>
				</ul>
				<div class="ui-refresh-down"></div>
			</div>
		</article>
	</div>
	<script id="J_itemView" type="text/template">
	{each data.list}
	<li>
		<a data-infTheme="{$value.title},{$value.link},{$value.down}">
			<div class="pic"><img class="lazy" src="<?php echo $staticResPath;?>/pic/pic_nopreview.jpg" data-lazyload="true" data-src="{$value.img}" ></div>
			<div class="desc">	
				<h3>{$value.title}</h3>
			</div>
		</a>
	</li>
	{/each}
	</script>
<?php echo $this->render("layout/footer.phtml");?>
