<?php echo $this->render("layout/header.phtml");?>

<script src="jquery-ui.js"></script>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui.js?v=<?php echo $version;?>"></script>
<style type="text/css">
	.select-box{width:600px; overflow:hidden;}
	.select-box div{float:left; width:300px;}
	.select-box ul{width:206px; height:300px; overflow-y:auto; overflow-x:hidden; border:1px solid; border-color: #999999 #e1e1e1 #e1e1e1 #999999;background:#fff; font-size:1em;color:#000;}
	.select-box li{height:26px; line-height:26px; padding:0 10px;}
	.select-box li:active{background-color:#09f;}
	.select-box input[type=text]{display:block; width:200px; padding:5px 10px;border:1px solid; border-color: #999999 #e1e1e1 #e1e1e1 #999999;padding:3px;background:#fff; font-size:1em;color:#000;}
</style>

<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $indexUrl;?>">货架管理</a></li>
	</ul>
</div>
<div class="h_a">货架管理</div>
<form method="post" action="<?php echo $postUrl;?>" id="editFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">	
		<tr class="tr">
			<th class="th">货架名称</th>
			<td class="td">
			<select name="key" onchange="window.location.href = '<?php echo $editUrl;?>?key='+this.options[this.selectedIndex].value">
                <option <?php echo $info['key'] == 'new' ? 'selected="selected"' : '';?> value="new">最新</option>
                <option <?php echo $info['key'] == 'hot' ? 'selected="selected"' : '';?> value="hot">最热</option>
                </select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">货架</th>
			<td class="td">
				<div class="select-box">
					<div class="J_supply"><!-- multiple="true"  -->
						<input type="text" value="" autocomplete="off"  />
						<ul></ul>
					</div>
					<div class="J_receive">
						<ul style="margin-top:25px;"></ul>
						<input type="hidden" value="<?php echo $value;?>" name="value"/>
					</div>
				</div>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//表单数据提交
$(document).ready(function(){
	ajaxForm('editFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Storage/index?key=<?php echo $info['key'];?>');
	});

})

	var SELECT_DATA = <?php echo $files;?>, EXSIT_DATA = <?php echo $exsit?>;
		
	var eChange = document.all ? 'keyup':'input', arrSupply = [], arrReceive = [], sData = SELECT_DATA,
		
		supplyWrap = $('.J_supply ul'), receiveWrap = $('.J_receive ul'),
		
		_hasItem = function(arr, item){
			var hasItem = false;
			$.each(arr, function(i, v){
				if(item==v)
					hasItem = true;
			});
			return hasItem;
		},
		
		_removeItem = function(arr, item){
			if($.isArray(item)){
				$.each(item, function(ii, vv){
					_removeItem(arr,vv);
				});
				return arr;
			} else {
				$.each(arr, function(i, v){
					if(v==item)
						arr.splice(i, 1);
				});
				return arr;
			}
		},
		
		_noRepeat = function(arr){
			var oArr = {};
			
			$.each(arr, function(i, v){
				if(!oArr[v]){
					oArr[v] = true;
				} else {
					arr.splice(i, 1);
				}
			});
			
			return arr;
		},
		
		_filterData = function(data, filter){
			var arrGetData = [], isArray = $.isArray(filter),
				oReg = isArray? filter : new RegExp(filter);
			$.each(data, function(i, v){
				if(isArray){
					if(_hasItem(oReg,v.id))
						arrGetData.push(v);
				} else {
					if(oReg.test(v.title))
						arrGetData.push(v);
				}
			});
			return arrGetData;
		},
		
		_renderItem = function(data,pNode){
			var s = '';
			$.each(data, function(i, v){
				s += '<li id="'+v.id+'">'+v.title+'</li>';
			});
			pNode.html(s);
		};

	$('.J_supply input').val('');
	_renderItem(SELECT_DATA, supplyWrap);
	_renderItem(EXSIT_DATA, receiveWrap);
	
	$('.J_supply ul').sortable({
		connectWith:'ul',
		update: function(evt, ui){
			//console.log(this.parentNode.className+':'+$(this).sortable('toArray'));
			var item = $(this).sortable('toArray'), val = document.querySelector('.J_supply input').value;
			
			if(val){
				setTimeout(function(){//console.log(arrReceive);
					arrSupply = _removeItem(arrSupply, arrReceive);
					sData = _filterData(SELECT_DATA, arrSupply);
				}, 10);
				//arrSupply = _noRepeat(arrSupply.concat(item));
			} else {
				arrSupply = item;
				sData = _filterData(SELECT_DATA, arrSupply);
			}
			//console.log(arrSupply);
			//console.log(sData);
		}
	});
	
	$('.J_receive ul').sortable({
		connectWith:'ul',
		update: function(evt, ui){
			//console.log(this.parentNode.className+':'+$(this).sortable('toArray'));
			arrReceive = $(this).sortable('toArray');
			$(this.parentNode).find('input').val(arrReceive.join(','));
		}
	});
	
	$('.J_supply input').bind(eChange, function(){
		//console.log(_filterData(SELECT_DATA, this.value));
		this.value = this.value.replace(/\s|\n/g, '');
		_renderItem(_filterData(sData, this.value), supplyWrap);
		//$('.J_supply ul').sortable('option', 'disabled', this.value? true:false);
	});
</script>
<?php echo $this->render("layout/footer.phtml");?>
