<?php echo $this->render("layout/header.phtml");?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<div class="nav">
	<ul class="cc">
	    <li class="current"><a href="<?php echo $listUrl.'?activity_id='.$info['id'].'&act=edit';?>">免流量活动</a></li>
		<li><a href="<?php echo $ulistUrl;?>">用户统计</a></li>
        <li><a href="<?php echo $flistUrl;?>">流量统计</a></li>
        <li><a href="<?php echo $blistUrl;?>">黑名单</a></li>
	</ul>
</div>
<?php if($info['htype'] == 1) {?>
<div class="step mb10" id='setcont'>
		<ul class="cc">
			<li style="width:33.3%">编辑活动</li>
			<li class="line" style="left:33%"></li>
			<li style="width:32.3%" ><span ass="fl"><em></em></span>内容配置</li>
			<li class="line" style="left:66%"></li>
			<li class="current" style="width:33.3%"><span class="fl"><em></em></span>预警设置</li>
		</ul>
</div>
<?php } else if($info['htype'] == 2) {?>
<div class="step mb10" id='setcontline'>
		<ul class="cc">
			<li class="current" >编辑活动</li>
			<li class="line" ></li>
			<li><span class="fl"><em></em></span>预警设置</li>
		</ul>
</div>
<?php } ?>
<div class="h_a"><?php echo $act == 'add' ? "创建" : "编辑";?>活动</div>
<form method="post" action="<?php echo $addWarnPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="activity_id" type="hidden" value="<?php echo $activity_id;?>" />
<input name="act" type="hidden" value="edit" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">整体预警额度</th>
			<td class="td"><input type="text" class="input" name="total_warning" value="<?php echo $info['total_warning'];?>">T</td>
		</tr>
		<tr class="tr">
			<th class="th">用户预警额度</th>
			<td class="td"><input type="text" class="input" name="user_warning" value="<?php echo $info['user_warning'];?>">M</td>
		</tr>
		<tr class="tr">
			<th class="th">预警邮箱</th>
			<td class="td"><textarea style="width: 500px; height: 300px" class="textarea" name="email_warning"><?php echo $info['email_warning'];?></textarea>
			<br/>
			<br/>
			<span style="color:red">填写预警邮箱,使用“|”符号分割。</span>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
			<select name="status" class="select wa">
				<option <?php if ($info['status'] == 1) echo 'selected';?> value="1">开启</option>
				<option <?php if ($info['status'] == 0) echo 'selected';?> value="0">关闭</option>
			</select>
			</td>
		</tr>
		<tr class="tr">
				<th class="th">黑名单规则</th>
			    <td class="td">
			         <div style="height: 120px;"> 
			            <div>说明：勾选并填写条件后规则才能生效</div>
			            <div><input class="input" type="checkbox" name="warn_check_1" value="1" style="display: none;" />1天内下载同一个内容超过 <input type="text" class="input" name="warn_1" value="<?php echo $blacklist_rule[1];?>"> 次<span style="color:red">(必填项)</span></div>
			            <div><input class="input" type="checkbox" <?php if ($blacklist_rule[2]) echo 'checked';?> name="warn_check_2" value="2" />1小时消耗免流量额度超过 <input type="text" class="input" name="warn_2" value="<?php echo $blacklist_rule[2];?>"> M<span style="color:red">(勾选后，填写值才能生效)</span></div>
			            <div><input class="input" type="checkbox" <?php if ($blacklist_rule[3]) echo 'checked';?> name="warn_check_3" value="3" />1天内消耗免流量额度超过 <input type="text" class="input" name="warn_3" value="<?php echo $blacklist_rule[3];?>"> M<span style="color:red">(勾选后，填写值才能生效)</span></div>
			            <div><input class="input" type="checkbox" <?php if ($blacklist_rule[4]) echo 'checked';?> name="warn_check_4" value="4" />1月内消耗免流量额度超过 <input type="text" class="input" name="warn_4" value="<?php echo $blacklist_rule[4];?>"> M<span style="color:red">(勾选后，填写值才能生效)</span></div>
			         </div>
			    </td>
			   
			    
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Freedl_Hd/index?activity_id=<?php echo $activity_id;?>&act=edit');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
