<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">分类列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加分类</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">专区</th>
			<td class="td">
			<select name="area_id" class="wa">
				<option value="0">所有</option>
<?php foreach($areas as $key=>$value) {?>
                	<option <?php if($key == $search['area_id']) echo 'selected';?> value="<?php echo $key;?>"><?php echo $value;?></option>
<?php }?>
			</select>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">排序</td>
			<td width="30">ID</td>
			<td>所属专区</td>
			<td>分类名称</td>
			<td>分类图片</td>
			<td>开始时间</td>
			<td>结束时间</td>
			<td>状态</td>
			<td>操作</td>
		</tr>
<?php foreach($categorys as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><?php echo $value['id'];?></td>
			<td><?php echo $areas[$value['area_id']];?></td>
			<td><?php echo $value['title'];?></td>
			<td><?php if($value['img']) {?><img src="<?php echo $attachPath,$value['img'];?>" width="100"/><?php }?></td>
	        	<td><?php echo date('Y-m-d H:i:s', $value['start_time']);?></td>
	        	<td><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
			<td><?php echo $value['status'] == 1 ? '开启' : '关闭';?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
