<?php echo $this->render("layout/header.phtml");?>
<style>
.step2 li{
    width: 23%;
}
.step2 li.line{
	position: static;
}
</style>
<div class="nav">
	<ul class="cc">
	   <li ><a href="<?php echo $indexUrl;?>">道具兑换</a></li>
       <li class="current"><a href="javascript:;">编辑兑换活动</a></li>
	</ul>
</div>
<div class="step step2 mb10">
		<ul class="cc">
			<li class="current">编辑活动</li>
			<li class="line"></li>
			<li><span class="fl"><em></em></span>编辑道具</li>
			<li class="line"></li>
			<li><span class="fl"><em></em></span>编辑游戏</li>
			<li class="line"></li>
			<li><span class="fl"><em></em></span>编辑奖品</li>
		</ul>
</div>
<form method="post" action="<?php echo $editStep1PostUrl.'/?id='. $infoData['id'];?>" id="addFrom">
<input name="festivalId" value="<?php echo $infoData['id'];?>" type="hidden" />
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">活动标题</th>
			<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $infoData['title'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">生效时间</th>
			<td class="td">
			     <div>
			         <input class="input" type="text" maxlength="30" style="width:143px;" id="startTime" name="startTime" value="<?php echo date('Y-m-d H:i:s', $infoData['start_time']);?>" />
			          至 
			         <input class="input" type="text" maxlength="30" style="width:143px;" id="endTime" name="endTime" value="<?php echo date('Y-m-d H:i:s', $infoData['end_time']);?>" />
			     </div>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">广告图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg">
						<img src="<?php echo $attachPath.$infoData['banner_img'];?>"/>
						<input type="hidden" name="bannerImg" value="<?php echo $infoData['banner_img'];?>">
					</li>
				</ul>			
                <p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">活动说明</th>
			<td class="td">
			         <textarea name="description" style="height:240px;width:800px"><?php echo $infoData['description'];?></textarea>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">游戏大厅版本</th>
			<td class="td">
			    <span><label>请选择最低参与版本<br/></label></span>
			    <?php foreach ($clientConfig as $key=>$item):?>
				<span><label><input type="radio" name="clientVersion" value="<?php echo $key;?>" <?php echo ($key == $infoData['client_versions']) ? 'checked' : '';?>><?php echo $item;?></label></span>
				<?php endforeach;?>
			   	</td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
			<select name="status">
                	<option value="1" <?php echo ($infoData['status']==1) ? 'selected' : '';?> >开启</option>
                	<option value="0" <?php echo ($infoData['status']==0) ? 'selected' : '';?> >关闭</option>
            </select></td>
		</tr>
		<?php $config = json_decode($infoData['config'], true);?>
		<tr class="tr">
			<th class="th">首页配置图片一</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg1">
						<img src="<?php echo $attachPath.$config['img1'];?>"/>
						<input type="hidden" name="config[img1]" value="<?php echo $config['img1'];?>">
					</li>
				</ul>			
                <p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg1';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
			 </p></td>
		</tr>
		<tr class="tr">
			<th class="th">首页配置图片二</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg2">
						<img src="<?php echo $attachPath.$config['img2'];?>"/>
						<input type="hidden" name="config[img2]" value="<?php echo $config['img2'];?>">
					</li>
				</ul>			
                <p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg2';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
			 </p></td>
		</tr>
		<tr class="tr">
			<th class="th">首页配置图片三</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg3">
						<img src="<?php echo $attachPath.$config['img3'];?>"/>
						<input type="hidden" name="config[img3]" value="<?php echo $config['img3'];?>">
					</li>
				</ul>			
                <p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg3';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
			 </p></td>
		</tr>
		<tr class="tr">
			<th class="th">首页配置图片四</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg4">
						<img src="<?php echo $attachPath.$config['img4'];?>"/>
						<input type="hidden" name="config[img4]" value="<?php echo $config['img4'];?>">
					</li>
				</ul>			
                <p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg4';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
			 </p></td>
		</tr>
		<tr class="tr">
			<th class="th">版本过低图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg5">
						<img src="<?php echo $attachPath.$config['img5'];?>"/>
						<input type="hidden" name="config[img5]" value="<?php echo $config['img5'];?>">
					</li>
				</ul>			
                <p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg5';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
			 </p></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">下一步</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 var editor;
	 KindEditor.ready(function(K) {
	     K.token = '<?php echo $token;?>';
	        editor = K.create('textarea[name="description"]', {
	        resizeType : 1,
	        allowPreviewEmoticons : false,
	        allowImageUpload : true,
	        uploadJson : '<?php echo $uploadImgUrl;?>',
	        items : EDITOR_ITEMS
	   });
     });
	 $('#startTime').datetimepicker();
     $('#endTime').datetimepicker();
	 ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $editStep2Url.'/?id='. $infoData['id'];?>');
	 }, function(){
			editor.sync();
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>