<?php echo $this->render("layout/header.phtml");?>
<script>
var token = '<?php echo $token;?>';
</script>
<body>
	<div id="page">
		<div class="article">
			<div class="desc">
				<p><?php echo $info['title'];?></p>
				<p><?php echo  date('Y-m-d',$info['create_time']); ?></p>
			</div>
			<div class="content ui-editor">
					<p><?php echo html_entity_decode($info['content']);?></p>
			</div>
		</div>
	</div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>