<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $indexUrl;?>?cate_id=<?php echo $cate_id;?>&channel_id=<?php echo $channel_id;?>">平台列表</a></li>
	    <li class="current"><a href="javascript:;">添加平台</a></li>
	</ul>
</div>
<div class="h_a">添加平台</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<input name="channel_id" value="<?php echo $channel_id;?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">名称</th>
				<td class="td"><input type="text" class="input wc" name="name" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">分类</th>
				<td class="td">
					<select name="cate_id">
					<?php foreach ($category as $key=>$val):?>
						<option value="<?php echo $val['id'];?>" <?php if ($val['id'] == $cate_id) echo 'selected="selected"'?>><?php echo $val['title'];?></option>
					<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">短描述</th>
				<td class="td"><textarea class="input wc" name="description1" rows="3"></textarea></td>
			</tr>
		<tr class="tr">
			<th class="th">颜色</th>
			<td class="td">
				<input type="text" class="input" name="color" value="">(填写颜色值，如:红色#e51c23;绿色#259b24;橙色#fd5a19;蓝色#5677fc;紫色#9c27b0;青色#009688, 不填写则显示为默认颜色)
			</td>
		</tr>
			<tr class="tr">
				<th class="th">长描述</th>
				<td class="td"><textarea class="input wc" name="description" rows="3"></textarea></td>
			</tr>
			<tr class="tr">
				<th class="th">链接</th>
				<td class="td"><textarea class="input wc" name="link">http://</textarea></td>
			</tr>
			<tr class="tr">
			<th class="th">模块-平台</th>
			<td class="td">
				<select name="module_id">
					<option value="">选择模块</option>
					<?php foreach($modules as $key=>$value) { ?>
					<option value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
					<?php }?>
				</select>
				
				<select name="cid">
					<option value="">选择平台</option>
					<?php foreach($channel_names as $key=>$value) { ?>
					<option value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
					<?php }?>
				</select>
			</td>
		</tr>
			<tr class="tr">
				<th class="th">平台号</th>
				<td class="td"><input type="text" class="input" name="channel_code" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">图标</th>
				<td class="td">
					<ul class="uploadImg">
						<li id="AdImg">
							<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
							<input type="hidden" name="img" value="">
						</li>
					</ul>			
					<p style="clear:both;">
		                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
					</p></td>
			</tr>
			<tr class="tr">
				<th class="th">排序</th>
				<td class="td"><input type="text" class="input" name="sort" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">推荐</th>
				<td class="td">
					<select class="wa" name="top">
						<option value="1">是</option>
						<option value="0">否</option>
					</select>
				</td>
			</tr>
			<tr class="tr">
			<th class="th">是否标记</th>
			<td class="td">
				<select class="wa" name="is_recommend">
				    <option value="0">否</option>
					<option value="1">是</option>
				</select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">是否人气关注</th>
			<td class="td">
				<select class="wa" name="is_hot">
				    <option value="0">否</option>
					<option value="1">是</option>
				</select>
			</td>
		</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td">
					<select class="wa" name="status">
						<option value="1">开启</option>
						<option value="0">关闭</option>
					</select>
				</td>
			</tr>
		<tr class="tr">
			<th class="th">开始结束时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo $start_time;?>" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="<?php echo $end_time;?>" /></div>
			</td>
		</tr>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	$('#start_time').datetimepicker();
	$('#end_time').datetimepicker();
	
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Clientchannel/index?s=1&cate_id=<?php echo $cate_id;?>&channel_id=<?php echo $channel_id;?>');
	});
});
</script>
<?php echo $this->render("layout/footer.phtml");?>
