<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    	<li class="current"><a href="<?php echo $indexUrl;?>?channel_id=<?php echo $search['channel_id'];?>">平台列表</a></li>
		<li><a href="<?php echo $addUrl;?>?channel_id=<?php echo $search['channel_id'];?>">添加平台</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>" method="get">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="channel_id" type="hidden" value="<?php echo $search['channel_id'];?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">分类</th>
			<td class="td">
			<select name="cate_id">
			<option value="">所有</option>
<?php foreach($category as $key=>$value) {?>
				<option <?php echo ($cate_id == $value['id']) ? 'selected="selected"' :'';?> value="<?php echo $value['id'];?>"><?php echo $value['title'];?></option>
<?php }?>
			</select>
			
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">排序</td>
			<td width="30">ID</td>
			<td >名称</td>
			<td width="100">描述</td>
			<td width="80">分类</td>
			<td width="60">图标</td>
			<td width="40">推荐</td>
			<td width="30">状态</td>
			<td width="30">标记</td>
			<td width="30">平台号</td>
			<td width="40"><a href="<?php echo $url . '&is_hot=1' ?>">人气 &darr;</a></td>
			<td width="150">开始结束时间</td>
			<td width="120">操作</td>
		</tr>
		<?php if(!empty($list)): foreach ($list as $val): list($module_id, $channel_id) = explode("_", $val['module_channel'])?>
		<tr class="ct">
			<td><?php echo $val['sort'];?></td>
			<td><?php echo $val['id'];?></td>
			<td><?php echo $val['name'];?></td>
			<td  <?php if($val['color']) echo 'style="color:'.$val['color'].'"'?>><?php echo $val['description1'];?></td>
			<td><?php echo $category[$val['cate_id']]['title'];?></td>
			<td><img src="<?php echo $attachPath . $val['img'];?>" width=52/></td>
			<td><?php echo $val['top'] == 1 ? '是' : '否';?></td>
			<td><?php echo $val['status'] == 1 ? '开启' : '关闭';?></td>
			<td><?php echo $val['is_recommend'] == 1 ? '是' : '否';?></td>
			<td><?php echo $val['channel_code'];?></td>
			<td><?php echo $val['is_hot'] == 1 ? '是' : '否';?></td>
			<td><?php if($val['start_time']) { echo date('Y-m-d H:i:s', $val['start_time']).'<br/>'.date('Y-m-d H:i:s', $val['end_time']);}?></td>
			<td>
            <a target="_blank" href="/admin/stat/thirdpart/?version_id=<?php echo Stat_Service_Log::V_APK;?>&module_id=<?php echo $module_id;?>&channel_id=<?php echo $channel_id;?>&item_id=<?php echo $val['id'];?>" class="mr10">点击量</a>
				<a href="<?php echo $editUrl;?>/?id=<?php echo $val['id'];?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $val['id'];?>', '', event);">删除</a>
			</td>
		</tr>
		<?php endforeach; endif;?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
