<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">消息列表</a></li>
    <li class="current"><a href="javascript:;">查看消息</a></li>
	</ul>
</div>
<div class="h_a">查看消息</div>
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">消息内容</th>
			<td class="td"><?php echo $info['content'];?></td>
		</tr>
		<tr class="tr">
			<th class="th">时间</th>
			<td class="td"><?php echo date('Y-m-d H:i:s', $info['create_time']);?></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onclick="javascript:history.back(-1);" type="button">返回</button></span></span></div>
<?php echo $this->render("layout/footer.phtml");?>
