<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl;?>">规则列表</a></li>
		<li class="current"><a href="javascript:;">添加规则</a></li>
	</ul>
</div>
<div class="h_a">添加浏览记录规则</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
            <tr class="tr">
                <th class="th">平台</th>
                <td class="td"><input type="text" class="input wc" name="src"	value=""></td>
            </tr>
            <tr class="tr">
                <th class="th">类型</th>
                <td class="td"><select name="type" class="select">
                        <option value="shop">店铺</option>
                        <option value="goods">商品</option>
                    </select></td>
            </tr>
            <tr class="tr">
				<th class="th">规则</th>
				<td class="td"><input type="text" class="input wc" name="preg"	value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td"><select name="status" class="select">
						<option value="1">开启</option>
						<option value="0">关闭</option>
				</select></td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $listUrl ?>');
	});
})

</script>
<?php echo $this->render("layout/footer.phtml");?>
