<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <script type="text/javascript"
        src="<?php echo $dataPath . "/jssdk/jquery.min.js" ?>"></script>
        <div><?php echo $webroot; ?></div>

        <div>dataPath :<?php echo $dataPath; ?></div>
    </body>
</html>