<?php echo $this->render("layout/header.phtml");?>
<div id="page">
	<header id="header">
		<div class="m-nav">
			<section><a class="back" href="<?php echo $webroot.'/product/detail?sid='.$series_id.'&id='.$id;?>"><span>返回</span></a></section>
			<section><span>技术规格</span></section>
			<section></section>
		</div>
	</header>
	<div id="content">
			<div class="module">
				<div class="in-editer-cont">
					<?php echo html_entity_decode($product['descrip']);?>
				</div>
			</div>
		</div>
</div>
<?php echo $this->render("layout/tj.phtml");?>
<?php echo $this->render("layout/footer.phtml");?>