<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="UTF-8">
	<title>刮一刮 中秋好礼抱回家-金立游戏大厅</title>
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="format-detection" content="email=no" />

<link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/events/midAutumn/assets/css/main.css?v=<?php echo $version;?>" />

</head>
<body>
	<div class="header">
		<div class="head_1"></div>
		<div class="head_2"></div>
	</div>
	<div class="main">
		<!-- 活动一 -->
		<h1 class="event_time">活动时间：2014年09月06日- 09-08日</h1>
		<div class="vein"></div>
		<div class="main_bg_1"></div>
		<div class="container">
			<div class="scratcherArea">
				<span class="no">NO:024500024568326</span>
				<a onclick="javascript:tjUrl();" class="share" target="_blank" href="http://service.weibo.com/share/share.php?url=http://game.gionee.com/monact/index/?intersrc=weibo&title=全球最薄手机S5.5，精美游戏周边！哇塞@金立游戏大厅 精彩活动太给力辣，你还在犹豫神马？快点召集小伙伴一起来吧。&pic=<?php echo $staticroot; ?>/apps/game/events/midAutumn/pic/banner.png" ></a>
				<div id="Scratch_Holder" data-href="<?php echo $webroot; ?>/monact/addlog/">
					<div class="scratcherContainer">
						<span class="chance-tips hidden">您今天已经抽过奖了<br/><em>明天再试试运气</em></span>
						<canvas id="scratcher"  width="248" height="64"></canvas>
					</div>
				</div>
				<div class="J_prizetips tips">
					<span class="tip">刮开50%进行下一步操作</span>
					<span class="pct">当前刮开<em id="scraPercent">0%</em></span>
				</div>
				<a onclick="javascript:tjUrl();" id="shareToHer" target="_blank" class="btn-darkblue invisible">分享给Ta</a>
				<a id="getPrize" class="btn-orange hidden">领取奖品</a>
			</div>
			<div class="scratcherInstr">
				<div class="tips">
					<span class="tip">中奖说明：</span>
					<span class="no"></span>
				</div>
				<ul class="prizeType">
					<li class="prize1"></li>
					<li class="prize2"></li>
					<li class="prize3"></li>
					<li class="prize4"></li>
				</ul>
			</div>
			<div class="rules">
				<h1>活动规则:</h1>
				1.活动期间每人每天有且仅有一次刮奖机会；<br/>
				2.实物奖励将在15个工作日内寄出，话费奖励将在7个工作日内充值到中奖用户所提供的手机号码。
			</div>

		</div>
		<!-- 活动二 -->
		<div class="main_bg_2"></div>
		<div class="container">
			<ul class="game-list">
			   <li>
						<a href="<?php echo Common::monTjurl('http://gamedl.gionee.com/Attachments/dev/apks/2014/08/27/1409148423166_signed.apk', 'MONACT_GID2431');?>&t_bi=<?php echo $source;?>">
						<div class="left">
							<span class="name">新济公活佛</span>
							<img class="icon" src="http://s.dev.gionee.com/Attachments/dev/icons/2014/08/27/53fde77a5dfbe.png" data-src="" alt="">
						</div>
						<span class="desc">
							<em class="first">大经验卡*2</em>
							<em>宝物经验卡*2</em>
							<em>中将魂丹*1</em>
								<span class="download">下载游戏</span>
						</span>
					</a>
				</li>
				
				<li>
						 <a href="<?php echo Common::monTjurl('http://gamedl.gionee.com/Attachments/dev/apks/2014/08/29/1409304404346_signed.apk', 'MONACT_GID2328');?>&t_bi=<?php echo $source;?>">
					    <div class="left">
					    <span class="name">天天英雄</span>
							<img class="icon" src="http://s.dev.gionee.com/Attachments/dev/icons/2014/08/29/54004817166b0.png" data-src="" alt="">
						</div>
						<span class="desc">
							<em class="first">超级经验书x1</em>
							<em>水晶苹果x5</em>
							<em>星妈魂石x2</em>
								<span class="download">下载游戏</span>
						</span>
					</a>
				</li>
				
				<li>
						<a href="<?php echo Common::monTjurl('http://gamedl.gionee.com/Attachments/dev/apks/2014/08/22/1408689441293_signed.apk', 'MONACT_GID1862');?>&t_bi=<?php echo $source;?>">
						<div class="left">
							<span class="name">时空猎人</span>
							<img class="icon" src="http://s.dev.gionee.com/Attachments/dev/icons/2014/08/22/53f6e60b11ad9.png" data-src="" alt="">
						</div>
						<span class="desc">
							<em class="first">魔力蛋糕*20</em>
							<em>魔晶*80000</em>
							<em>竞技点*1500</em>
								<span class="download">下载游戏</span>
						</span>
					</a>
				</li>
				
				<li>
						<a href="<?php echo Common::monTjurl('http://gamedl.gionee.com/Attachments/dev/apks/2014/09/03/1409726027191_signed.apk', 'MONACT_GID2460');?>&t_bi=<?php echo $source;?>">
						<div class="left">
							<span class="name">酷酷爱魔兽</span>
							<img class="icon" src="http://s.dev.gionee.com/Attachments/dev/icons/2014/08/22/53f715c641883.png" data-src="" alt="">
						</div>
						<span class="desc">
							<em class="first">稀有钱袋*5</em>
							<em>精力体力丹*2</em>
							<em>技能卷轴*5</em>
								<span class="download">下载游戏</span>
						</span>
					</a>
				</li>
				
				<li>
						<a href="<?php echo Common::monTjurl('http://gamedl.gionee.com/Attachments/dev/apks/2014/07/28/1406496105917_signed.apk',  'MONACT_GID2005');?>&t_bi=<?php echo $source;?>">
						<div class="left">
							<span class="name">去吧皮卡丘</span>
							<img class="icon" src="http://s.dev.gionee.com/Attachments/dev/icons/2014/07/28/53d5704783d83.png" data-src="" alt="">
						</div>
						<span class="desc">
							<em class="first">金币*400000</em>
							<em>徽章500</em>
							<em>银宝箱*1</em>
								<span class="download">下载游戏</span>
						</span>
					</a>
				</li>
				
				<li>
						<a href="<?php echo Common::monTjurl('http://gamedl.gionee.com/Attachments/dev/apks/2014/07/21/140594229583_signed.apk', 'MONACT_GID1926');?>&t_bi=<?php echo $source;?>">
						<div class="left">
							<span class="name">剑魂之刃</span>
							<img class="icon" src="http://s.dev.gionee.com/Attachments/dev/icons/2014/07/21/53cc7b6a489b4.png" data-src="" alt="">
						</div>
						<span class="desc">
							<em class="first">80钻石</em>
							<em>50万金币</em>
							<em>初级强化石*3</em>
								<span class="download">下载游戏</span>
						</span>
					</a>
				</li>
				
			</ul>
		<a class="btn-green" href="<?php echo Common::monTjurl('http://gamedl.gionee.com/Attachments/dev/apks/2014/07/02/1404282324653.apk', 'MONACT_GID117');?>&t_bi=<?php echo $source;?>">下载客户端领取中秋游戏礼包</a>
		</div>
		<!-- 活动三 -->
		<div class="main_bg_3"></div>
		<div class="container">
			<div class="event3"></div>
			<a target="_blank" href="<?php echo Common::monTjurl('http://bbs.amigo.cn/thread-7600-1-1.html',  'MONACT_Imm_Party');?>&t_bi=<?php echo $source;?>" class="btn-brown">立即参与</a>
		</div>
			
	</div>
	<div class="clearfix footer">
		<span class="qrcode"></span>
		<div class="container">
			<div class="info">
			<p>客服电话：0755-83211672</p>
			<p>客服QQ：1732001808</p>
			<p>玩家交流群：189360286</p>
			</div>
		</div>
		<span class="copyright">本次活动最终解释权归金立游戏大厅所有</span>
	</div>
	
	<!-- dialog -->
	<div class="J_mask mask hidden">
		<div class="mask-header">
			<span class="cong">恭喜您中奖！</span>
			<span class="tips">请填写您的中奖信息以便工作人员联系发奖 </span>
		</div>
		<div class="mask-content ">
			<div class="name">
				<span class="text">姓名:</span>
				<input class="username" />
			</div>
			<div class="phone ">
				<span class="text">手机号码:</span>
				<input class="telephone" />
				<span class="errorTips">输入错误</span>
			</div>
			
			<div class="action">
				<i class="chk">分享活动至新浪微博</i>
				<a class="btn-blue"  id="submit" data-ajaxUrl="<?php echo $webroot; ?>/monact/roll/">确定</a>
			</div>
		</div>
		
	</div>

	
	<script >
	    var hasChance=<?php echo $status ? 'true': 'false';?>;
		var WinCheck=<?php echo $prize;?>;
		var token = '<?php echo $token;?>';
		var sign = '<?php echo $sign;?>';
		var ret_id = '<?php echo $ret_id;?>';
	</script>
	<script src="<?php echo $staticroot; ?>/apps/game/events/midAutumn/assets/js/jquery.js" ></script>
	<script src="<?php echo $staticroot; ?>/apps/game/events/midAutumn/assets/js/scratcher.js" ></script>
	<script data-main src="<?php echo $staticroot; ?>/apps/game/events/midAutumn/assets/js/main.js"  ></script>
   <script>
//统计的js，拼接url
function tjUrl(){ 
	tourl = '<?php echo $webroot?>/monact/index?intersrc=weibo';
	$.ajax({url:tourl,
		    async:false,	
	});
}
</script>

</body>
</html>