<script type="text/javascript" src="<?php echo $staticSysPath;?>/icat/1.1.3/icat.js?v=<?php echo $version;?>" corelib="//zepto.js" main="../game.js"></script>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F0405d1a68dae612416258f53465d3ede' type='text/javascript'%3E%3C/script%3E"));
</script>
