<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class="current"><a href="<?php echo $listColumn . '/?parent_id=' . $parent_id; ?>">栏目列表</a></li>
			<li><a href="<?php echo $addColumn . '/?parent_id=' . $parent_id; ?>">添加栏目</a></li>
		</ul>
	</div>
	<form method="post" action="<?php echo $sortColumnPostUrl; ?>" id="sortForm">
		<input name="token" type="hidden" value="<?php echo $token; ?>"/>

		<div class="table_list">
			<table width="100%">
				<tr class="hd">
					<td width="50">选择</td>
					<td width="50">排序</td>
					<td width="50">编号</td>
					<td width="100">名称</td>
					<td>CP来源</td>
					<td>颜色</td>
					<td>是否推荐</td>
					<td>状态</td>
					<td>操作</td>
				</tr>
				<?php foreach ($columns as $key => $value) { ?>
			<tr class="ct" <?php if ($value['status']) echo 'blue'; ?>">
				<td><input type="checkbox" name="ids[<?php echo $value['id']; ?>]" value="<?php echo $value['id']; ?>"></td>
				<td><input type="text" name="sort[<?php echo $value['id']; ?>]" class="input" value="<?php echo $value['sort']; ?>" style="width:30px;"></td>
				<td><?php echo $value['id']; ?></td>
				<td><?php echo $value['name']; ?></td>
				<td><?php echo $types[$value['source_id']]; ?></td>
				<td><div style="height:20px;width:50px;background-color:<?php echo $value['color']; ?>;"></div></td>
				<td><?php echo $value['is_recommend'] == 1 ? '推荐' : '<font color="red">不推荐</font>'; ?></td>
				<td><?php echo $value['status'] == 1 ? '开启' : '关闭'; ?></td>
				<td>
				<a href="<?php echo $editColumn . '/?parent_id=' . $parent_id . '&id=' . $value['id']; ?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteColumn . "/?id=" . $value['id']; ?>', '', event);">删除</a>
				</td>
			</tr>
	<?php } ?>
			</table>
		</div>
		<div class="mb10 tac">
			<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
	</form>
	<script type="text/javascript">
		//用户表单数据提交
		$(document).ready(function () {
			ajaxForm('sortForm', function (ret) {
				ajaxRedirect(ret, baseurl + '/Admin/Jhtype/column/?parent_id=<?php echo $parent_id;?>');
			});
		})

	</script>
<?php echo $this->render("layout/footer.phtml"); ?><?php
