<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $listUrl;?>">vip图标列表</a></li>
	    <li class="current"><a href="javascript:;">添加vip图标</a></li>
	</ul>
</div>
<div class="h_a">添加vip图标</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">vip等级(<span style="color: red">*</span>)</th>
			<td class="td"><select name="vip" class="input">
					<?php foreach($vipList as $value) {?>
    			    <option value="<?php echo $value;?>">Vip<?php echo $value;?></option>
    			    <?php }?>
			  </select></td>
		</tr>
		<tr class="tr">
			<th class="th">icon(<span style="color: red">*</span>)</th>
			<td class="td">
                <ul class="uploadImg">
					<li id="img">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img" />
					</li>
				</ul>
                <p style="clear:both;">
	                <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=img';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $listUrl;?>');
	});
});
</script>
<?php echo $this->render("layout/footer.phtml");?>
