
<!DOCTYPE HTML>
<html>
<head>
    <title>发免费书券啦</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
    <meta name="apple-touch-fullscreen" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="format-detection" content="telephone=no" />
    <link rel="stylesheet" href="<?php echo $staticResPath;?>/events/css/booktoken.min.css?ver=<?php echo $version;?>" />
</head>
<body>
<div class="app">
    <div class="banner">
        <img src="<?php echo $staticResPath;?>/events/pic/bt_banner.jpg" usemap="#btn-getBookToken" />
        <map name="btn-getBookToken">
            <area href="<?php echo $webroot?>/user/index/index" shape="rect" coords="300,210,180,160" />
        </map>
    </div>
    <div class="main">
        <div class="title"><h2>使用说明</h2></div>
        <div class="part part1">
            <img src="<?php echo $staticResPath;?>/events//pic/bt_step1.jpg" />
            <div class="step"><em>1</em>点击“个人中心”<br/>进入首页登录后签到即可<br/><strong>免费领取书券；</strong></div>
        </div>
        <div class="part part2">
            <img src="<?php echo $staticResPath;?>/events/pic/bt_step2.jpg" />
            <div class="step"><em>2</em><strong>发送短信sqdhgioneeXXX<br/>至10658080充值</strong>成功后，进入<br/>http://www.cmread.com/页面<br/>后便可使用。</div>
        </div>
        <div class="part part3">
            <img src="<?php echo $staticResPath;?>/events/pic/bt_step3.jpg" />
            <div class="step"><em>3</em>书券<strong>仅支持中国移动<br/>手机号码</strong>进行充值。</div>
        </div>
        <div class="part part4">
            <img src="<?php echo $staticResPath;?>/events/pic/bt_step4.jpg" />
            <div class="step"><em>4</em>书券有效期：<strong>截至时间为<br/>2015年12月31日。</strong></div>
        </div>
        <div class="part part5">
            <img src="<?php echo $staticResPath;?>/events/pic/bt_step5.jpg" />
            <div class="step"><em>5</em>每名账户<strong>仅限一次免<br/>费领取。</strong></div>
        </div>
    </div>
    <div class="footer">
        <p>最终解释权归金立浏览器所有</p>
    </div>
</div>
</body>
</html>