<?php echo $this->render("common/navigator.phtml"); ?>
<link href="<?php echo $staticPath ?>jssdk/plugins/datepicker/laydate.css" rel="stylesheet" type="text/css">

<script type="text/javascript"
src="<?php echo $staticPath ?>jssdk/plugins/datepicker/laydate.js"></script>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="zt_ucenter_edit">
        <div class="content">
        	<div class="pay_detail_det">
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">名称</label>
                        <div class="tb_cont tb_cell">
                            <?php echo $theme['title']; ?>
                        </div>
                    </div><!-- com_tb end -->
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">作者</label>
                        <div class="tb_cont tb_cell">
                            <?php echo $theme['designer']; ?>
                        </div>
                    </div><!-- com_tb end -->
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">预览图</label>
                            <div class="cell_img_detial" id="cell_img_detial">
                                <!-- 已经存在了的预览图 start-->
                                <?php foreach($imgs as $img){ ?>
                                <a><img src="<?php echo $imageurl . $img['img'] ?>" class="tb_cell_img" style="height: auto;"></a>
                                <?php } ?>
                                <!-- 已经存在了的预览图 end-->
                            </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">一级标签</label>
                         <div class="tb_cont tb_cell">
                            <ul class="tag_list tag_one">
                                <li><?php echo $theme['type_name']; ?></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell align_top">二级标签</label>
                        <div class="tb_cont tb_cell">
                            <ul class="tag_add_wrap">
                                <?php foreach($theme['sec_type_name'] as $type) { ?>
                                <li class="btn_tag"><span><?php echo $type; ?></span><i class="tag_del"></i></li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell align_middle">主题介绍</label>
                        <div class="tb_cont tb_cell txt_editor_wrap"><?php echo $theme['descript']; ?></div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">状态</label>
                        <div class="tb_cont tb_cell">
                            <ul class="tag_list tag_one">
                                <li><?php echo $status[$theme['status']]; ?></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">上线时间</label>
                        <div  class="tb_cont tb_cell">
                            <?php echo date('Y-m-d H:i:s', $theme['create_time']); ?>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">下载次数</label>
                        <div class="tb_cont tb_cell">
                            <div class="buyer_num bottom_icon"><span><?php echo $theme['download_times']; ?></li>
                            </ul></span></div>
                            <div class="buyer_detail none"><p>显示下载次数的内容</p></div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">购买次数</label>
                        <div class="tb_cont tb_cell">
                            <div class="down_num bottom_icon"><span><?php echo $theme['purchase_times']; ?></span></div>
                            <div class="showdetail none"><p>显示购买次数的内容</p></div>
                            <div class="userInfo">
                                <ul>
                                    <?php foreach($buyers as $buyer){?>
                                    <li><?php echo $buyer['nick_name']; ?></li>
                                    <?php } ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">购买营业额</label>
                        <div class="tb_cont tb_cell">
                            <p><?php echo $theme['sum']; ?></p>
                        </div>
                    </div>
                </div>

                <div class="bnts_wrap">
                    <button class="btn_s2" onclick="history.go(-1);">返回</button>
                </div>
        	</div>
        </div><!-- content end -->
    </div>
</section>

<script type="text/javascript">
    $(function(){
        $('.down_num').on('click',function(){
            if($(this).hasClass('bottom_icon')){
                $(this).removeClass('bottom_icon').addClass('top_icon');
                $('.showdetail').removeClass('none');

            }else
            if($(this).hasClass('top_icon')){
                $(this).removeClass('top_icon').addClass('bottom_icon');
                $('.showdetail').addClass('none');
            }
        });
        $('.buyer_num').on('click',function(){
            if($(this).hasClass('bottom_icon')){
                $(this).removeClass('bottom_icon').addClass('top_icon');
                $('.buyer_detail').removeClass('none');

            }else
            if($(this).hasClass('top_icon')){
                $(this).removeClass('top_icon').addClass('bottom_icon');
                $('.buyer_detail').addClass('none');
            }
        });
    })
</script>
</body>
</html>