<div class="com_tb_wrap">
    <div class="com_tb">
        <label class="tb_cell">搜索:</label>
        <div class="tb_cont tb_cell">
            <input type="text" style="width:350px;" class="rd_1 search_name" value="<?php echo $keyword;?>">
            <button class="btn_s2 detial_search_btn" id="search_btn">搜索</button>
        </div>
    </div><!-- com_tb end -->
</div>
<div class="pay_content_mid">
	<div class="container">
		<div class="pay_view_tab" id="recently">
			<ul>
				<li class="firstWeek <?php if($recently == 'week'){ echo 'hover'; }?>" val="week">一周</li>
				<li <?php if($recently == 'month'){ echo 'class="hover"'; }?> val="month">一个月</li>
				<li <?php if($recently == 'half_year'){ echo 'class="hover"'; }?>  val="half_year">半年</li>
				<li <?php if($recently == 'year'){ echo 'class="hover"'; }?>  val="year">一年</li>
			</ul>
		</div>
		<div class="pay_time ">
			<input name="from" type="text" onClick="laydate({istime:   true, format: 'YYYY-MM-DD hh:mm:ss'})" readonly class="time_start laydate-icon datepicker" style="margin-right:0.2rem" value="<?php echo $from;?>">
			<label class="end_time">至</label>
			<input name="to" type="text" onClick="laydate({istime:   true, format: 'YYYY-MM-DD hh:mm:ss'})" readonly class="time_end laydate-icon datepicker" value="<?php echo $to;?>">
			<button class="btn_s2 search_btn" id="query_btn">查询</button>
		</div>
	</div>
	<div class="clear-fix"></div>
</div>