<?php echo $this->render("common/navigator.phtml"); ?>
<link href="<?php echo $staticPath ?>jssdk/plugins/datepicker/laydate.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $staticPath ?>jssdk/plugins/datepicker/laydate.js"></script>
<script type="text/javascript" src="<?php echo $staticPath ?>jssdk/plugins/highchart/highcharts.js"></script>
<script type="text/javascript" src="<?php echo $staticPath ?>jssdk/plugins/highchart/exporting.js"></script>
<script type="text/javascript" src="<?php echo $staticPath ?>appjs/payment/payment-line.js"></script>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="pay_payindex_index">
        <div class="content">
        	<!--支付内容开始-->
        	<div class="py_content">
        		<div class="py_content_top">
        			<table>
        				<thead>
                        <tr><th>总销售量</th><th>总营业额</th>
                            <th>基本支付营业额</th>
                        </tr>
                    	</thead>
                    	<tbody>
                    		<tr>
                    			<td><b><?php echo $all_num;?></b>套</td>
                    			<td><b><?php echo $all_coin;?></b>币</td>
                    			<td><b><?php echo $all_total;?></b>RMB</td>
                    		</tr>
                    	</tbody>
        			</table>
        		</div>
        		<div class="pay_content_mid">
                    <div class="container">
            			<div class="pay_view_tab" id="recently">
            				<ul>
                                <li class="firstWeek <?php if(empty($_GET['recently']) || $_GET['recently'] == 'week'){ echo 'hover'; }?>" val="week">一周</li>
                                <li <?php if($_GET['recently'] == 'month'){ echo 'class="hover"'; }?> val="month">一个月</li>
                                <li <?php if($_GET['recently'] == 'half_year'){ echo 'class="hover"'; }?>  val="half_year">半年</li>
                                <li <?php if($_GET['recently'] == 'year'){ echo 'class="hover"'; }?>  val="year">一年</li>
                            </ul>
            			</div>
                        <div class="pay_time">
                                <input name="from" type="text" onClick="laydate({istime:   true, format: 'YYYY-MM-DD hh:mm:ss'})" readonly class="time_start laydate-icon datepicker" style="margin-right:0.2rem" value="<?php echo $from;?>">
                                <label>至</label>
                                <input name="to" type="text" onClick="laydate({istime:   true, format: 'YYYY-MM-DD hh:mm:ss'})" readonly class="time_end laydate-icon datepicker" value="<?php echo $to;?>">
                                <button class="btn_s2 search_btn" id="query_btn">查询</button>
                        </div>
                    </div>
        			<div class="clear-fix"></div>
                    <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
        		</div>
        		<div class="pay_content_btm">
                        <div class="pay_all_account"><p>总销售量</p><span class="pay_num"><b><?php echo $recently_num;?></b>套</span></div>
        				<div class="pay_all_account price"><p>总营业额</p><span class="pay_money"><b><?php echo $recently_coin;?></b>A币</span></div>
        		</div>
        	</div>
        	<!--支付内容结束-->
        </div><!-- content end -->
    </div>
</section>

</body>
<script type="text/javascript">
    var categories = <?php echo json_encode($keys); ?>;
    var result_data = <?php echo json_encode($sorts); ?>;
	$(function(){
    	$('.pay_view_tab li').each(function(index){
			var $this = $(this);
			$this.click(function(){
				$this.siblings().removeClass('hover');
				$this.addClass('hover');	
				});
	   });
    });
</script>
</html>