<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">回帖列表</a></li>
    <li class="current"><a href="javascript:;">编辑回帖</a></li>
	</ul>
</div>
<div class="h_a">编辑回帖</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="editForm">
<input name="token" id="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">内容</th>
			<td class="td">
				<textarea name="content" style="width: 800px; height: 400px;"><?php echo $info['content'];?></textarea>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('editForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Forumreply/index');
	});

})

</script>
<?php echo $this->render("layout/footer.phtml");?>
