<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<ul class="cc">
        <li><a href="<?php echo $listUrl;?>">栏目管理</a></li>
		<li><a href="<?php echo $listChannelUrl;?>">频道管理</a></li>
    	<li><a href="<?php echo $editChanneAllUrl;?>">编辑频道位置</a></li>
		<li class="current"><a href="javascript:;">频道位置说明</a></li>
	</ul>
</div>

<div class="table_full">
<p>1. 一级栏目共5个
可配置名称，位置，图标</p>
<p>2. 二级频道
如图示橙色位置
首页4个频道为2级频道位
每个一级栏目的TAB为2级频道位，不限定数量
 </p>
<p>3. 设置一级栏目
将每个一级栏目中的首个二级频道即为打开该一级栏目默认显示的频道
一级栏目的名称和图标可在后台配置</p>
<p> 
4. 设置二级频道
二级频道可随意在二级频道位置调换
可新增二级频道，支持列表和网页2种模版
每个一级栏目最多支持4个二级频道</p>
<br>
<br>
<img src="<?php echo $staticPath.'/img/u0.png'; ?>"  title="" />
<img src="<?php echo $staticPath.'/img/u1.png'; ?>"  title="" />
</div>



</script>
<?php echo $this->render("layout/footer.phtml");?>