<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $recListUrl;?>">推荐列表</a></li>
		<li><a href="<?php echo $recImgUrl;?>">推荐图片</a></li>
		<li><a href="<?php echo $imgUrl;?>">图片广告</a></li>
		<li><a href="<?php echo $imgLogUrl;?>">历史列表图片</a></li>
		<li class="current"><a href="<?php echo $oldListUrl;?>">旧版本说明</a></li>
	</ul>
</div>
<div class="h_a">
	<p>一、旧版本推荐调整前和调整后的栏目对应关系</p>
	<p>
		1. 广告管理&gt;客户端&gt;广告位1=<span>广告管理&gt;客户端&gt;旧版本推荐&gt;历史列表图片</span>
	</p>
	<p>
		<span>2.&nbsp;<span>广告管理&gt;</span><span>客户端&gt;图片</span><span>广告</span><span>=</span><span>广告管理&gt;客户端&gt;旧版本推荐&gt;<span>图片广告(适用客户端1.5.4-1.5.6)</span></span></span>
	</p>
	<p>
		<span><span>3.&nbsp;</span><span>广告管理&gt;</span><span>客户端&gt;</span><span>推荐列表图片</span><span>=</span><span>广告管理&gt;客户端&gt;旧版本推荐&gt;<span>推荐图片（适用客户端1.5.4-1.5.6）</span></span><br></span>
	</p>
	<p>
		<span><span>4.&nbsp;</span><span>广告管理&gt;</span><span>客户端&gt;</span><span>推荐列表旧</span><span>=</span><span>广告管理&gt;客户端&gt;旧版本推荐&gt;推荐列表（适用客户端1.5.6及以下的版本）</span><br></span>
	</p>
	<p>
		<span><br> </span>
	</p>
</div>
<?php echo $this->render("layout/footer.phtml");?>
