<!DOCTYPE HTML>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
<body id="recoment" data-pagerole="body">
	<script type="text/javascript">
    tanx_c = window.tanx_c || {};
    tanx_c.mm_26632362_9250945_31214226 = {widthEl:'PARENT',response:'TRUE'};
	tanx_c.webview = 1;
	tanx_c.sn = "1111"; //imei here
	tanx_c.config = encodeURIComponent(JSON.stringify({"keyword":"羽绒服"})); //keyword here
    document.write('<a style="display:none!important" id="tanx-a-mm_26632362_9250945_31214226"></a>');
    tanx_s = document.createElement("script");
    tanx_s.type = "text/javascript";
    tanx_s.charset = "gbk";
    tanx_s.id = "tanx-s-mm_26632362_9250945_31214226";
    tanx_s.async = true;
    tanx_s.src = "http://p.tanx.com/ex?i=mm_26632362_9250945_31214226&m=1";
    tanx_h = document.getElementsByTagName("head")[0];
    if(tanx_h)tanx_h.insertBefore(tanx_s,tanx_h.firstChild);
</script>
</body>

</html>