<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li class="current"><a href="<?php echo $listUrl;?>">免流量活动</a></li>
		<li><a href="<?php echo $ulistUrl;?>">用户统计</a></li>
        <li><a href="<?php echo $flistUrl;?>">流量统计</a></li>
         <li><a href="<?php echo $blistUrl;?>">黑名单</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">	
	   <tr class="tr">
			<th class="th">活动名称</th>
			<td class="td"><input type="text" class="input" name="title" value="<?php echo $s['title'];?>"></td>
			<th class="th">活动状态</th>
			<td class="td">
			 <select name="status" class="select wa">
			    <option  value="0">全部</option>
				<option <?php if ($s['status'] == 2) echo 'selected';?> value="2">开启</option>
				<option <?php if ($s['status'] == 1) echo 'selected';?> value="1">关闭</option>
			 </select>
		   </td>
		</tr>
		<tr class="tr">
		    <th class="th">时间</th>
			<td class="td" colspan="2"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo $s['start_time'];?>" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="<?php echo $s['end_time'];?>" /></div>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="h_a">
	<span class="btn2"><span><button><a href="<?php echo $addUrl;?>" class="mr10" style="color:white;">添加活动</a></button></span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td width="80">ID</td>
			<td width="50">名称</td>
			<td width="50">类型</td>
			<td width="50">内容数量</td>
			<td width="50">总大小</td>
			<td width="200">生效时间</td>
			<td width="80">下载量</td>
			<td width="50">消耗流量</td>
			<td width="50">状态</td>
			<td width="120">操作</td>
		</tr>
<?php foreach($hds as $key => $value) {?>
		<tr class="ct">
		    <td><?php echo $value['id'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><?php echo $htype[$value['htype']];?></td>
			<td><?php echo $value['htype'] == 1 ? $value['num'] : '';?></td>
			<td><?php echo $value['htype'] == 1 ? $value['total'] : '';?></td>
			<td><?php echo date('Y-m-d H:i:s', $value['start_time']);?><br><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
			<td><?php echo $value['download'];?></td>
			<td><?php echo $value['phone_consume'];?>M</td>
			<td><?php echo $value['status'] ? '开启' : '关闭';?></td>		
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			&nbsp;&nbsp;<a href="<?php echo $hdetailUrl;?>/?activity_id=<?php echo $value['id'];?>">明细</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	 ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Freedl_Hd/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
