
<input type="hidden" id="page_type" value="novel"><div class="novel-header">
	<a href="javascript:;" class="i-back">返回</a>
	<span class="i-title">小说详情</span>
	<a href="javascript:;" class="i-share" stat="share" w="分享">分享</a>
</div><!-- novel-header end -->

<div class="novel-content novel-content-fix">

	<div class="novel-intro">
		<dl>
			<dt><a href="http://m.zongheng.com/h5/chapter/list?bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" stat="17672" w="详情图片" data-out="data-out"><img src="http://dh1.kimg.cn/kimg/mbook/cover/20150213/17672_3666708.jpg_180x250.jpg?q=50&amp;mode=1"></a></dt>
			<dd>
				<p><strong><a href="http://m.zongheng.com/h5/chapter/list?bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" stat="17672" w="详情标题" data-out="data-out">丹武九重天</a></strong></p>
				<p class="mt10"><span>红豆香烟</span><i>|</i><span>玄幻奇幻</span></p>
				<p><span class="blue">连载中</span></p>
				<p>更新于2015-06-23</p>
			</dd>
		</dl>
		<a href="http://m.zongheng.com/h5/chapter?cid=7907951&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056194835&amp;k=398023" class="novel-intro-orange" frt_chapter_name="第一章 古墓谜团" frt_chapter_id="7434060" frt_chapter_url="http://m.zongheng.com/h5/chapter?cid=7434060&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" id="readBook" data-chapter="7907951" data-title="第一百九十七章 惊魂之战(上)" stat="17672" w="读书章节" data-out="data-out">继续阅读：第一百九十七章 惊魂之战(上)</a>
		<a href="http://m.zongheng.com/h5/chapter?cid=7907951&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" class="novel-intro-gray" id="updataBook" data-chapter="7907951" stat="17672" w="更新章节" data-out="data-out">更新：第一百九十七章 惊魂之战(上)</a>
	</div>
	<div class="novel-mod mt10">
		<div class="hd">小说简介</div>
		<div class="bd">
			<div class="novel-info">
				<p>　　在众人眼中没有前途的李飞，意外深埋山腹，大难不死，被迫踏上了修炼之道！……
					在充满无限危险却热血沸腾的天途旅行中，李飞成就丹道至尊、逆袭一界霸主，携美纵横九天！
					当然更少不了被无数高手追杀的惊险与刺激……</p>
			</div>
			<a href="javascript:;" class="novel-more show-info" style="-webkit-transform-origin: 0px 0px 0px; opacity: 1; -webkit-transform: scale(1, 1);">显示全部内容</a>
		</div>
	</div>

	<div class="novel-mod">
		<div class="hd"><a href="javascript:;" class="i-order r" order="0">倒序↑↓</a>小说目录<span class="i-tip">（共197章）</span></div>
		<div class="bd">
			<div class="novel-glist">
				<ul>
					<li><a href="http://m.zongheng.com/h5/chapter?cid=7907951&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" data-chapter="7907951" stat="17672" w="详细章节" data-out="data-out">第一百九十七章 惊魂之战(上)</a></li>
					<li><a href="http://m.zongheng.com/h5/chapter?cid=7905852&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" data-chapter="7905852" stat="17672" w="详细章节" data-out="data-out">第一百九十六章 古修洞府</a></li>
					<li><a href="http://m.zongheng.com/h5/chapter?cid=7901834&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" data-chapter="7901834" stat="17672" w="详细章节" data-out="data-out">第一百九十五章 恶劣的环境</a></li>
					<li><a href="http://m.zongheng.com/h5/chapter?cid=7898916&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" data-chapter="7898916" stat="17672" w="详细章节" data-out="data-out">第一百九十四章 初到试炼星</a></li>
					<li><a href="http://m.zongheng.com/h5/chapter?cid=7894656&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" data-chapter="7894656" stat="17672" w="详细章节" data-out="data-out">第一百九十三章 生死赌博</a></li>
					<li><a href="http://m.zongheng.com/h5/chapter?cid=7891763&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" data-chapter="7891763" stat="17672" w="详细章节" data-out="data-out">第一百九十二章 绝地死战</a></li>
					<li><a href="http://m.zongheng.com/h5/chapter?cid=7888707&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" data-chapter="7888707" stat="17672" w="详细章节" data-out="data-out">第一百九十一章 再入险境</a></li>
					<li><a href="http://m.zongheng.com/h5/chapter?cid=7885783&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" data-chapter="7885783" stat="17672" w="详细章节" data-out="data-out">第一百九十章 北极秘殿</a></li>
					<li><a href="http://m.zongheng.com/h5/chapter?cid=7882915&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" data-chapter="7882915" stat="17672" w="详细章节" data-out="data-out">第一百八十九章 步步惊心</a></li>
					<li><a href="http://m.zongheng.com/h5/chapter?cid=7879366&amp;bookid=444107&amp;fr=liebao_freexx&amp;v=1435056130963&amp;k=74a177" data-chapter="7879366" stat="17672" w="详细章节" data-out="data-out">第一百八十八章 幻灭罗先大阵</a></li>

				</ul>
			</div>
			<div class="novel-pages" book_id="17672" total="197" fr="zongheng" is_rsy="1" time="120" page="1" max_page="20">
				<a href="javascript:;" pn="1" class="first disabled">首页</a>
				<a href="javascript:;" pn="1" class="prev disabled">上一页</a>
				<select max="20"><option value="1">1/20</option><option value="2">2/20</option><option value="3">3/20</option><option value="4">4/20</option><option value="5">5/20</option><option value="6">6/20</option><option value="7">7/20</option><option value="8">8/20</option><option value="9">9/20</option><option value="10">10/20</option><option value="11">11/20</option><option value="12">12/20</option><option value="13">13/20</option><option value="14">14/20</option><option value="15">15/20</option><option value="16">16/20</option><option value="17">17/20</option><option value="18">18/20</option><option value="19">19/20</option><option value="20">20/20</option></select>
				<a href="javascript:;" pn="2" class="next">下一页</a>
				<a href="javascript:;" pn="20" class="end">末页</a>
			</div>
		</div>
	</div>

	<div class="novel-mod">
		<div class="hd"><a class="i-change r" href="javascript:;" stat="17" w="换一换"><i class="icon-ref"></i>换一换</a>猜你喜欢</div>
		<div class="bd">
			<div class="novel-alist clearfix cur ">
				<ul>
					<li><a href="/detail/922.html" stat="783" w="b_xqygl_cnxh"><span class="imgbox"><img src="http://dh1.kimg.cn/kimg/mbook/cover/20141009/0706e368d66c8c6b9e62b48aecff2725.jpg_180x250.jpg?q=50&amp;mode=1" data-src="http://dh1.kimg.cn/kimg/mbook/cover/20141009/0706e368d66c8c6b9e62b48aecff2725.jpg_180x250.jpg?q=50&amp;mode=1"><i>风烟净</i></span><span class="novel-title">风流探花</span></a></li>
					<li><a href="/detail/17453.html" stat="357" w="b_xqygl_cnxh"><span class="imgbox"><img src="http://dh1.kimg.cn/kimg/mbook/cover/20150104/17453_8280803.jpg_180x250.jpg?q=50&amp;mode=1" data-src="http://dh1.kimg.cn/kimg/mbook/cover/20150104/17453_8280803.jpg_180x250.jpg?q=50&amp;mode=1"><i>卜小爷</i></span><span class="novel-title">霸婚总裁小蛮妻</span></a></li>
					<li><a href="/detail/816.html" stat="626" w="b_xqygl_cnxh"><span class="imgbox"><img src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/816_4285717.jpg_180x250.jpg?q=50&amp;mode=1" data-src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/816_4285717.jpg_180x250.jpg?q=50&amp;mode=1"><i>野蛮阿三</i></span><span class="novel-title">桃运教师</span></a></li>
					<li><a href="/detail/17362.html" stat="355" w="b_xqygl_cnxh"><span class="imgbox"><img src="http://dh2.kimg.cn/kimg/mbook/cover/20141210/17362_7049346.jpg_180x250.jpg?q=50&amp;mode=1" data-src="http://dh2.kimg.cn/kimg/mbook/cover/20141210/17362_7049346.jpg_180x250.jpg?q=50&amp;mode=1"><i>蘑菇大大王</i></span><span class="novel-title">至尊战仙</span></a></li>
					<li><a href="/detail/17565.html" stat="358" w="b_xqygl_cnxh"><span class="imgbox"><img src="http://dh3.kimg.cn/kimg/mbook/cover/20150123/17565_3692517.jpg_180x250.jpg?q=50&amp;mode=1" data-src="http://dh3.kimg.cn/kimg/mbook/cover/20150123/17565_3692517.jpg_180x250.jpg?q=50&amp;mode=1"><i>习炎</i></span><span class="novel-title">史上最强抢婚</span></a></li>
					<li><a href="/detail/79.html" stat="747" w="b_xqygl_cnxh"><span class="imgbox"><img src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/79_8812438.jpg_180x250.jpg?q=50&amp;mode=1" data-src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/79_8812438.jpg_180x250.jpg?q=50&amp;mode=1"><i>书海扬帆</i></span><span class="novel-title">村医</span></a></li>
				</ul>
			</div>
			<div class="novel-alist clearfix  " style="display:none;">
				<ul>
					<li><a href="/detail/12067.html" stat="842" w="b_xqygl_cnxh"><span class="imgbox"><img data-src="http://dh2.kimg.cn/kimg/mbook/cover/20141212/121d0569e21435b7396399dea54eb914.jpg_180x250.jpg?q=50&amp;mode=1" src=""><i>墨春花</i></span><span class="novel-title">试婚99天</span></a></li>
					<li><a href="/detail/17506.html" stat="843" w="b_xqygl_cnxh"><span class="imgbox"><img data-src="http://dh1.kimg.cn/kimg/mbook/cover/20150114/17506_9657310.jpg_180x250.jpg?q=50&amp;mode=1" src=""><i>白孤魂</i></span><span class="novel-title">仙游都市</span></a></li>
					<li><a href="/detail/452.html" stat="844" w="b_xqygl_cnxh"><span class="imgbox"><img data-src="http://dh3.kimg.cn/kimg/mbook/cover/20140926/452_844734.jpg_180x250.jpg?q=50&amp;mode=1" src=""><i>冰公主</i></span><span class="novel-title">盛世婚宠：老公送上门</span></a></li>
					<li><a href="/detail/839.html" stat="845" w="b_xqygl_cnxh"><span class="imgbox"><img data-src="http://dh2.kimg.cn/kimg/mbook/cover/20150123/177480fb427f9e9e7de9ccb47aceb77d.jpg_180x250.jpg?q=50&amp;mode=1" src=""><i>梅儿若雪</i></span><span class="novel-title">买个爹地宠妈咪</span></a></li>
					<li><a href="/detail/12030.html" stat="846" w="b_xqygl_cnxh"><span class="imgbox"><img data-src="http://dh1.kimg.cn/kimg/mbook/cover/20141021/12030_5581960.jpg_180x250.jpg?q=50&amp;mode=1" src=""><i>红泪</i></span><span class="novel-title">先婚试爱：千亿爱人的宠妻</span></a></li>
					<li><a href="/detail/2594.html" stat="847" w="b_xqygl_cnxh"><span class="imgbox"><img data-src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/2594_4667955.jpg_180x250.jpg?q=50&amp;mode=1" src=""><i>流浪仙人</i></span><span class="novel-title">媚骨仙成</span></a></li>
				</ul>
			</div>
			<div class="novel-alist clearfix  " style="display:none;">
				<ul>
					<li><a href="/detail/17672.html" stat="848" w="b_xqygl_cnxh"><span class="imgbox"><img data-src="http://dh1.kimg.cn/kimg/mbook/cover/20150213/17672_3666708.jpg_180x250.jpg?q=50&amp;mode=1" src=""><i>红豆香烟</i></span><span class="novel-title">丹武九重天</span></a></li>
					<li><a href="/detail/17477.html" stat="849" w="b_xqygl_cnxh"><span class="imgbox"><img data-src="http://dh1.kimg.cn/kimg/mbook/cover/20150109/17477_1517582.jpg_180x250.jpg?q=50&amp;mode=1" src=""><i>龙腾万里</i></span><span class="novel-title">不死剑神</span></a></li>
					<li><a href="/detail/4978.html" stat="851" w="b_xqygl_cnxh"><span class="imgbox"><img data-src="http://dh2.kimg.cn/kimg/mbook/cover/20140926/4978_2836774.jpg_180x250.jpg?q=50&amp;mode=1" src=""><i>乱世狂刀</i></span><span class="novel-title">国王万岁</span></a></li>
					<li><a href="/detail/1024.html" stat="852" w="b_xqygl_cnxh"><span class="imgbox"><img data-src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/1024_8405204.jpg_180x250.jpg?q=50&amp;mode=1" src=""><i>流浪的蛤蟆</i></span><span class="novel-title">鬼神无双</span></a></li>
					<li><a href="/detail/263.html" stat="853" w="b_xqygl_cnxh"><span class="imgbox"><img data-src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/263_4394583.jpg_180x250.jpg?q=50&amp;mode=1" src=""><i>步履无声</i></span><span class="novel-title">特种护花兵王</span></a></li>
					<li><a href="/detail/17449.html" stat="854" w="b_xqygl_cnxh"><span class="imgbox"><img data-src="http://dh2.kimg.cn/kimg/static/images/public/upload/20150424/b098a7e509318489cd79c61ed1b834fc.jpg_180x250.jpg?q=50&amp;mode=1" src=""><i>七月生我</i></span><span class="novel-title">妙手仁医</span></a></li>
				</ul>
			</div>
		</div>
	</div>

</div><!-- novel-content end -->
<input type="hidden" class="tongjidate" pvnode="1223137" pvsnode="1051" c_node="1223137" c_snode="1152" d_node="1223137" d_snode="1453" shareid="17672" idx="xiaoshuo">
<input type="hidden" id="shareConfig" title="丹武九重天" desc="在众人眼中没有前途的李飞，意外深埋山腹，大难不死，被迫踏上了修炼之道！……
在充满无限危险却热血沸腾的天途旅行中，李飞成就丹道至尊、逆袭一界霸主，携美纵横九天！
当然更少不了被无数高手追杀的惊险与刺激……" img="http://dh1.kimg.cn/kimg/mbook/cover/20150213/17672_3666708.jpg_180x250.jpg?q=50&amp;mode=1"><div class="novel-footer">
	<p>所有</p>
</div><!-- novel-footer end -->


