
<div class="novel-header" >
	<a href="/index.html" class="i-title">阅读</a>
	<!--<a href="/index.html" class="logo"></a>-->
	<a href="/search/" class="i-search" stat="cid_sousuo" w="sousuo"></a>
</div><!-- novel-header end -->
<div class="novel-tabs clearfix">
	<ul>
		<li><a href="/index.html" stat="1" w="front_index">热门</a></li>
		<li><a href="/ranking.html" stat="2" w="front_ranking">排行</a></li>
		<li><a href="/category.html" stat="3" w="front_category">分类</a></li>
		<li id="bookTips" class="on"><a href="/bookshelf.html" stat="4" w="front_bookshelf">书架</a></li>
	</ul>
</div><!-- novel-tabs end -->

<div class="novel-content">

	<div id="myBookList" class="novel-alist clearfix">
		<ul>
		</ul>
	</div>


	<div class="novel-mod">
		<div class="hd"><a class="i-change r" href="javascript:;" stat="16" w="换一换"><i class="icon-ref"></i>换一换</a>猜你喜欢</div>
		<div class="bd" >
			<div class="novel-alist clearfix cur " >
				<ul>
					<li><a href="/detail/898.html" href="/detail/898.html" stat="624" w="b_sjxs_cnxh"><span class="imgbox"><img  src="http://dh3.kimg.cn/kimg/mbook/cover/20140926/898_2300956.jpg_180x250.jpg?q=50&mode=1" data-src="http://dh3.kimg.cn/kimg/mbook/cover/20140926/898_2300956.jpg_180x250.jpg?q=50&mode=1" /><i>隐仙者</i></span><span class="novel-title">无尽破碎</span></a></li>
					<li><a href="/detail/358.html" href="/detail/358.html" stat="230" w="b_sjxs_cnxh"><span class="imgbox"><img  src="http://dh3.kimg.cn/kimg/mbook/cover/20140926/358_8688105.jpg_180x250.jpg?q=50&mode=1" data-src="http://dh3.kimg.cn/kimg/mbook/cover/20140926/358_8688105.jpg_180x250.jpg?q=50&mode=1" /><i>暗夜茗香</i></span><span class="novel-title">赌徒</span></a></li>
					<li><a href="/detail/412.html" href="/detail/412.html" stat="231" w="b_sjxs_cnxh"><span class="imgbox"><img  src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/412_7790289.jpg_180x250.jpg?q=50&mode=1" data-src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/412_7790289.jpg_180x250.jpg?q=50&mode=1" /><i>魔语冰殇</i></span><span class="novel-title">老子是村长</span></a></li>
					<li><a href="/detail/667.html" href="/detail/667.html" stat="233" w="b_sjxs_cnxh"><span class="imgbox"><img  src="http://dh2.kimg.cn/kimg/mbook/cover/20140926/667_6645953.jpg_180x250.jpg?q=50&mode=1" data-src="http://dh2.kimg.cn/kimg/mbook/cover/20140926/667_6645953.jpg_180x250.jpg?q=50&mode=1" /><i>煜刖</i></span><span class="novel-title">傲世九界</span></a></li>
					<li><a href="/detail/32.html" href="/detail/32.html" stat="234" w="b_sjxs_cnxh"><span class="imgbox"><img  src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/32_5697794.jpg_180x250.jpg?q=50&mode=1" data-src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/32_5697794.jpg_180x250.jpg?q=50&mode=1" /><i>慕容小呆</i></span><span class="novel-title">宠昏甜妻</span></a></li>
					<li><a href="/detail/17556.html" href="/detail/17556.html" stat="623" w="b_sjxs_cnxh"><span class="imgbox"><img  src="http://dh2.kimg.cn/kimg/mbook/cover/20150121/17556_1797146.jpg_180x250.jpg?q=50&mode=1" data-src="http://dh2.kimg.cn/kimg/mbook/cover/20150121/17556_1797146.jpg_180x250.jpg?q=50&mode=1" /><i>烟雨流</i></span><span class="novel-title">甜妻有点坏</span></a></li>
				</ul>
			</div>
			<div class="novel-alist clearfix  " style="display:none;">
				<ul>
					<li><a href="/detail/79.html" href="/detail/79.html" stat="830" w="b_sjxs_cnxh"><span class="imgbox"><img  data-src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/79_8812438.jpg_180x250.jpg?q=50&mode=1" src=""  /><i>书海扬帆</i></span><span class="novel-title">村医</span></a></li>
					<li><a href="/detail/670.html" href="/detail/670.html" stat="831" w="b_sjxs_cnxh"><span class="imgbox"><img  data-src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/670_5120110.jpg_180x250.jpg?q=50&mode=1" src=""  /><i>短刀</i></span><span class="novel-title">低调术士</span></a></li>
					<li><a href="/detail/17608.html" href="/detail/17608.html" stat="832" w="b_sjxs_cnxh"><span class="imgbox"><img  data-src="http://dh3.kimg.cn/kimg/mbook/cover/20150130/17608_1000212.jpg_180x250.jpg?q=50&mode=1" src=""  /><i>灵犀蝌蚪</i></span><span class="novel-title">宠婚萌爱</span></a></li>
					<li><a href="/detail/1977.html" href="/detail/1977.html" stat="833" w="b_sjxs_cnxh"><span class="imgbox"><img  data-src="http://dh3.kimg.cn/kimg/mbook/cover/20140926/1977_7668890.jpg_180x250.jpg?q=50&mode=1" src=""  /><i>旧日支配者</i></span><span class="novel-title">爱上恶鬼</span></a></li>
					<li><a href="/detail/124.html" href="/detail/124.html" stat="834" w="b_sjxs_cnxh"><span class="imgbox"><img  data-src="http://dh2.kimg.cn/kimg/mbook/cover/20140926/124_7628986.jpg_180x250.jpg?q=50&mode=1" src=""  /><i>流浪的蛤蟆</i></span><span class="novel-title">龙神决</span></a></li>
					<li><a href="/detail/916.html" href="/detail/916.html" stat="835" w="b_sjxs_cnxh"><span class="imgbox"><img  data-src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/916_6273062.jpg_180x250.jpg?q=50&mode=1" src=""  /><i>末之未央</i></span><span class="novel-title">绝世仙华</span></a></li>
				</ul>
			</div>
			<div class="novel-alist clearfix  " style="display:none;">
				<ul>
					<li><a href="/detail/1081.html" href="/detail/1081.html" stat="836" w="b_sjxs_cnxh"><span class="imgbox"><img  data-src="http://dh3.kimg.cn/kimg/mbook/cover/20140926/1081_5937320.jpg_180x250.jpg?q=50&mode=1" src=""  /><i>湖澜</i></span><span class="novel-title">祸患下山乱江湖</span></a></li>
					<li><a href="/detail/849.html" href="/detail/849.html" stat="837" w="b_sjxs_cnxh"><span class="imgbox"><img  data-src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/849_7434748.jpg_180x250.jpg?q=50&mode=1" src=""  /><i>烽火戏诸侯</i></span><span class="novel-title">雪中悍刀行</span></a></li>
					<li><a href="/detail/12078.html" href="/detail/12078.html" stat="838" w="b_sjxs_cnxh"><span class="imgbox"><img  data-src="http://dh1.kimg.cn/kimg/mbook/cover/20141027/12078_3024061.jpg_180x250.jpg?q=50&mode=1" src=""  /><i>陌上杨柳</i></span><span class="novel-title">引妻入瓮</span></a></li>
					<li><a href="/detail/4344.html" href="/detail/4344.html" stat="839" w="b_sjxs_cnxh"><span class="imgbox"><img  data-src="http://dh1.kimg.cn/kimg/mbook/cover/20140926/4344_2292237.jpg_180x250.jpg?q=50&mode=1" src=""  /><i>逝水幻心</i></span><span class="novel-title">绝代歌妃</span></a></li>
					<li><a href="/detail/276.html" href="/detail/276.html" stat="840" w="b_sjxs_cnxh"><span class="imgbox"><img  data-src="http://dh3.kimg.cn/kimg/mbook/cover/20140926/276_2453573.jpg_180x250.jpg?q=50&mode=1" src=""  /><i>饕餮居士</i></span><span class="novel-title">死亡名单</span></a></li>
					<li><a href="/detail/414.html" href="/detail/414.html" stat="841" w="b_sjxs_cnxh"><span class="imgbox"><img  data-src="http://dh2.kimg.cn/kimg/mbook/cover/20140926/414_8333584.jpg_180x250.jpg?q=50&mode=1" src=""  /><i>九蚊虫</i></span><span class="novel-title">欢喜禅法</span></a></li>
				</ul>
			</div>
		</div>
	</div>
</div><!-- novel-content end -->
