insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (1,'Afghanistan','AF','93');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (2,'Albania','AL','355');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (3,'Algeria','DZ','213');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (4,'American Samoa','AS','684');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (5,'Andorra','AD','376');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (6,'Angola','AO','244');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (7,'Anguilla','AI','1-264');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (8,'Antarctica','AQ','672');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (9,'Antigua and Barbuda','AG','1-268');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (10,'Argentina','AR','54');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (11,'Armenia','AM','374');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (12,'Aruba','AW','297');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (13,'Australia','AU','61');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (14,'Austria','AT','43');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (15,'Azerbaijan','AZ','994');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (16,'Bahamas','BS','1-242');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (17,'Bahrain','BH','973');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (18,'Bangladesh','BD','880');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (19,'Barbados','BB','1-246');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (20,'Belarus','BY','375');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (21,'Belgium','BE','32');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (22,'Belize','BZ','501');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (23,'Benin','BJ','229');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (24,'Bermuda','BM','1-441');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (25,'Bhutan','BT','975');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (26,'Bolivia','BO','591');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (27,'Bosnia and Herzegovina','BA','387');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (28,'Botswana','BW','267');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (29,'Bouvet Island','BV','');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (30,'Brazil','BR','55');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (31,'British Indian Ocean Territory','IO','1-284');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (32,'Brunei Darussalam','BN','673');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (33,'Bulgaria','BG','359');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (34,'Burkina Faso','BF','226');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (35,'Burundi','BI','257');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (36,'Cambodia','KH','855');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (37,'Cameroon','CM','237');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (38,'Canada','CA','1');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (39,'Cape Verde','CV','238');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (40,'Cayman Islands','KY','1-345');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (41,'Central African Republic','CF','236');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (42,'Chad','TD','235');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (43,'Chile','CL','56');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (44,'China','CN','86');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (45,'Christmas Island','CX','61');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (46,'Cocos (Keeling) Islands','CC','61');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (47,'Colombia','CO','57');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (48,'Comoros','KM','269');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (49,'Congo','CG','242');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (50,'Congo, The Democratic Republic Of The','ZR','243');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (51,'Cook Islands','CK','682');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (52,'Costa Rica','CR','506');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (53,'Cote D\'Ivoire','CI','225');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (54,'Croatia (local name: Hrvatska)','HR','385');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (55,'Cuba','CU','53');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (56,'Cyprus','CY','357');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (57,'Czech Republic','CZ','420');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (58,'Denmark','DK','45');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (59,'Djibouti','DJ','253');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (60,'Dominica','DM','1-767');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (61,'Dominican Republic','DO','1-809');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (62,'East Timor','TP','670');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (63,'Ecuador','EC','593');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (64,'Egypt','EG','20');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (65,'El Salvador','SV','503');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (66,'Equatorial Guinea','GQ','240');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (67,'Eritrea','ER','291');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (68,'Estonia','EE','372');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (69,'Ethiopia','ET','251');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (70,'Falkland Islands (Malvinas)','FK','500');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (71,'Faroe Islands','FO','298');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (72,'Fiji','FJ','679');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (73,'Finland','FI','358');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (74,'France','FR','33');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (75,'France Metropolitan','FX','33');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (76,'French Guiana','GF','594');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (77,'French Polynesia','PF','689');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (78,'French Southern Territories','TF','');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (79,'Gabon','GA','241');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (80,'Gambia','GM','220');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (81,'Georgia','GE','995');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (82,'Germany','DE','49');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (83,'Ghana','GH','233');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (84,'Gibraltar','GI','350');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (85,'Greece','GR','30');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (86,'Greenland','GL','299');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (87,'Grenada','GD','1-473');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (88,'Guadeloupe','GP','590');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (89,'Guam','GU','1-671');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (90,'Guatemala','GT','502');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (91,'Guinea','GN','224');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (92,'Guinea-Bissau','GW','245');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (93,'Guyana','GY','592');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (94,'Haiti','HT','509');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (95,'Heard and Mc Donald Islands','HM','');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (96,'Honduras','HN','504');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (97,'Hong Kong','HK','852');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (98,'Hungary','HU','36');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (99,'Iceland','IS','354');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (100,'India','IN','91');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (101,'Indonesia','ID','62');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (102,'Iran (Islamic Republic of)','IR','98');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (103,'Iraq','IQ','964');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (104,'Ireland','IE','353');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (105,'Isle of Man','IM','');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (106,'Israel','IL','972');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (107,'Italy','IT','39');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (108,'Jamaica','JM','1-876');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (109,'Japan','JP','81');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (110,'Jordan','JO','962');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (111,'Kazakhstan','KZ','7');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (112,'Kenya','KE','254');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (113,'Kiribati','KI','686');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (114,'Kuwait','KW','965');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (115,'Kyrgyzstan','KG','996');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (116,'Lao People\'s Democratic Republic','LA','');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (117,'Latvia','LV','371');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (118,'Lebanon','LB','961');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (119,'Lesotho','LS','266');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (120,'Liberia','LR','231');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (121,'Libyan Arab Jamahiriya','LY','218');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (122,'Liechtenstein','LI','423');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (123,'Lithuania','LT','370');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (124,'Luxembourg','LU','352');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (125,'Macau','MO','853');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (126,'Madagascar','MG','261');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (127,'Malawi','MW','265');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (128,'Malaysia','MY','60');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (129,'Maldives','MV','960');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (130,'Mali','ML','223');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (131,'Malta','MT','356');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (132,'Marshall Islands','MH','692');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (133,'Martinique','MQ','596');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (134,'Mauritania','MR','222');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (135,'Mauritius','MU','230');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (136,'Mayotte','YT','269');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (137,'Mexico','MX','52');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (138,'Micronesia','FM','691');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (139,'Moldova','MD','373');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (140,'Monaco','MC','377');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (141,'Mongolia','MN','976');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (142,'Montenegro','MNE','382');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (143,'Montserrat','MS','1-664');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (144,'Morocco','MA','212');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (145,'Mozambique','MZ','258');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (146,'Myanmar','MM','95');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (147,'Namibia','NA','264');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (148,'Nauru','NR','674');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (149,'Nepal','NP','977');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (150,'Netherlands','NL','31');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (151,'Netherlands Antilles','AN','599');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (152,'New Caledonia','NC','687');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (153,'New Zealand','NZ','64');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (154,'Nicaragua','NI','505');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (155,'Niger','NE','227');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (156,'Nigeria','NG','234');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (157,'Niue','NU','683');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (158,'Norfolk Island','NF','672');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (159,'North Korea','KP','850');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (160,'Northern Mariana Islands','MP','1670');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (161,'Norway','NO','47');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (162,'Oman','OM','968');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (163,'Pakistan','PK','92');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (164,'Palau','PW','680');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (165,'Palestine','PS','970');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (166,'Panama','PA','507');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (167,'Papua New Guinea','PG','675');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (168,'Paraguay','PY','595');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (169,'Peru','PE','51');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (170,'Philippines','PH','63');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (171,'Pitcairn','PN','872');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (172,'Poland','PL','48');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (173,'Portugal','PT','351');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (174,'Puerto Rico','PR','1-787');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (175,'Qatar','QA','974');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (176,'Reunion','RE','262');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (177,'Romania','RO','40');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (178,'Russian Federation','RU','7');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (179,'Rwanda','RW','250');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (180,'Saint Kitts and Nevis','KN','');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (181,'Saint Lucia','LC','');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (182,'Saint Vincent and the Grenadines','VC','');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (183,'Samoa','WS','685');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (184,'San Marino','SM','378');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (185,'Sao Tome and Principe','ST','');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (186,'Saudi Arabia','SA','966');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (187,'Senegal','SN','221');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (188,'Serbia','SRB','381');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (189,'Seychelles','SC','248');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (190,'Sierra Leone','SL','232');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (191,'Singapore','SG','65');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (192,'Slovakia (Slovak Republic)','SK','421');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (193,'Slovenia','SI','386');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (194,'Solomon Islands','SB','677');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (195,'Somalia','SO','252');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (196,'South Africa','ZA','27');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (197,'South Korea','KR','82');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (198,'Spain','ES','34');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (199,'Sri Lanka','LK','94');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (200,'St. Helena','SH','290');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (201,'St. Pierre and Miquelon','PM','508');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (202,'Sudan','SD','249');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (203,'Suriname','SR','597');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (204,'Svalbard and Jan Mayen Islands','SJ','');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (205,'Swaziland','SZ','268');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (206,'Sweden','SE','46');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (207,'Switzerland','CH','41');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (208,'Syrian Arab Republic','SY','963');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (209,'Taiwan','TW','886');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (210,'Tajikistan','TJ','992');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (211,'Tanzania','TZ','255');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (212,'Thailand','TH','66');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (213,'The former Yugoslav Republic of Macedonia','MK','389');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (214,'Togo','TG','228');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (215,'Tokelau','TK','690');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (216,'Tonga','TO','676');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (217,'Trinidad and Tobago','TT','1-868');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (218,'Tunisia','TN','216');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (219,'Turkey','TR','90');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (220,'Turkmenistan','TM','993');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (221,'Turks and Caicos Islands','TC','1-649');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (222,'Tuvalu','TV','688');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (223,'Uganda','UG','256');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (224,'Ukraine','UA','380');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (225,'United Arab Emirates','AE','971');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (226,'United Kingdom','UK','44');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (227,'United States','US','1');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (228,'United States Minor Outlying Islands','UM','');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (229,'Uruguay','UY','598');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (230,'Uzbekistan','UZ','998');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (231,'Vanuatu','VU','678');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (232,'Vatican City State (Holy See)','VA','39');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (233,'Venezuela','VE','58');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (234,'Vietnam','VN','84');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (235,'Virgin Islands (British)','VG','1284');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (236,'Virgin Islands (U.S.)','VI','1340');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (237,'Wallis And Futuna Islands','WF','681');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (238,'Western Sahara','EH','685');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (239,'Yemen','YE','967');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (240,'Yugoslavia','YU','381');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (241,'Zambia','ZM','260');
insert  into `dhm_country`(`id`,`name`,`code`,`call_code`) values (242,'Zimbabwe','ZW','263');
