<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl; ?>">玩咖配置列表</a></li>
		<li class="current"><a href="javascript:;">编辑玩咖配置</a></li>
	</ul>
</div>
<div class="h_a">编辑玩咖配置</div>
<form method="post" action="<?php echo $editPostUrl; ?>" id="editForm">
	<input name="token" value="<?php echo $token; ?>" type="hidden"/>
	<input name="id" value="<?php echo $info['id']; ?>" type="hidden"/>

	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">机型</th>
				<td class="td">
					<select name="name">
					    <option <?php echo $info['name'] == 'default' ? 'selected="selected"' : ''; ?> value="default">default</option>
						<?php foreach ($modelList as $key => $value) { ?>
							<option <?php echo $info['name'] == $value ? 'selected="selected"' : ''; ?> value="<?php echo $value; ?>"><?php echo $value; ?></option>
						<?php } ?>
					</select>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">浏览器版本号</th>
				<td class="td"><input type="text" class="input wc" name="app_ver" value="<?php echo $info['app_ver']; ?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">wk_main_switch</th>
				<td class="td"><select name="wk_main_switch" min-width="100px">
						<option <?php if ($info['wk_main_switch'] == 1) echo 'selected="selected"'; ?> value="1">开启</option>
						<option <?php if ($info['wk_main_switch'] == 0) echo 'selected="selected"'; ?>value="0">关闭</option>
					</select></td>
			</tr>
			<tr class="tr">
				<th class="th">wk_searchEngines_switch</th>
				<td class="td"><select name="wk_searchEngines_switch" min-width="100px">
						<option <?php if ($info['wk_searchEngines_switch'] == 1) echo 'selected="selected"'; ?> value="1">开启</option>
						<option <?php if ($info['wk_searchEngines_switch'] == 0) echo 'selected="selected"'; ?>value="0">关闭</option>
					</select></td>
			</tr>
			<tr class="tr">
				<th class="th">wk_hotKeyword_switch</th>
				<td class="td"><select name="wk_hotKeyword_switch" min-width="100px">
						<option <?php if ($info['wk_hotKeyword_switch'] == 1) echo 'selected="selected"'; ?> value="1">开启</option>
						<option <?php if ($info['wk_hotKeyword_switch'] == 0) echo 'selected="selected"'; ?>value="0">关闭</option>
					</select></td>
			</tr>
			<tr class="tr">
				<th class="th">wk_suggested_switch</th>
				<td class="td"><select name="wk_suggested_switch" min-width="100px">
						<option <?php if ($info['wk_suggested_switch'] == 1) echo 'selected="selected"'; ?> value="1">开启</option>
						<option <?php if ($info['wk_suggested_switch'] == 0) echo 'selected="selected"'; ?>value="0">关闭</option>
					</select></td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script type="text/javascript">
	//用户表单数据提交
	$(document).ready(function () {
		ajaxForm('editForm', function (ret) {
			ajaxRedirect(ret, baseurl + '/Admin/Wanka/index');
		});
	})

</script>
<?php echo $this->render("layout/footer.phtml"); ?>
