<?php echo $this->render("layout/header2.phtml");?>
<div id="page">
		<div id="iscrollWrap">
			<div class="mainWrap">
				<header class="hdWrap">
					<div class="hd-l"><a href="<?php echo $webroot.'/goods/index';?>" class="l-arrow">back</a></div>
					<div class="hd-r"><h1>积分换购规则</h1></div>	
				</header>
				<!-- 内容区域 START-->
				<section class="prule">
					<div class="mod-dialog">
						<div class="title"><h2>如何获取积分</h2></div>
						<div class="text">
							1.注册为金立购用户赠送100银币。<br/>
							2.在金立购—赚取积分专区中购物，可获得一定的积分奖励，当您确认收货后，奖励积分会进入到您的积分余额中。
						</div>
						
						<div class="title"><h2>如何使用积分</h2></div>
						<div class="text">
							1.银币在积分换购区中根据商品可抵现额度，直接抵现使用。<br/>
							2.金币在积分换购专区中可以无限制使用。
						</div>
					</div>
				</section>
				<!-- 内容区域 END-->
			</div>
		</div>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>