<?php echo $this->render("layout/webheader.phtml");?>
<body>
	<div id="iScroll" class="help-warp">
		<article class="ac">
			<div class="info">
				<p class="intro">购物大厅介绍</p>
				<p class="desc">购物大厅是专为安卓用户打造的一站式导购平台，具有商品搜索、购物信息推荐等功能。</p>
				<p class="special">特色功能：</p>
				<ul >
					<li>多渠道购物入口。优质购物网站随心选。</li>
					<li>分类导购。搜罗性价比最高的网购资讯，购物省心又省钱。</li>
					<li>货到付款专区。线上购物，线下货到再付款，购物更安心。</li>
				</ul>
				<p class="com"><br/><br/><br/>深圳市金立通信设备有限公司 </p>
					<p class="copyright">copyright© 2012 粤ICP备05087105号</p>
					<div class="contact">
						<a href="tel:075582583525" class="btn">联系我们</a>
					</div>
			</div>
		</article>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>