<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    	<li><a href="<?php echo $indexUrl;?>">活动列表</a></li>
		<li class="current"><a href="<?php echo $editUrl;?>">修改活动</a></li>
	</ul>
</div>
<div class="h_a">修改分类</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">名称</th>
				<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title']?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">奖品数量(种类)</th>
				<td class="td"><input type="text" class="input wb" name="awards_num" value="<?php echo $info['awards_num']?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">排序</th>
				<td class="td"><input type="text" class="input wb" name="sort" value="<?php echo $info['sort']?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">开始日期</th>
				<td class="td"><input type="text" class="input wb" name="start_time" value="<?php echo date("Y-m-d",$info['start_time']);?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">结束日期</th>
				<td class="td"><input type="text" class="input wb" name="end_time" value="<?php echo date("Y-m-d",$info['end_time']); ?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td">
					<select class="wa" name="status">
						<option value="1" <?php if($info['status'] == 1){echo 'selected="selected"';}?>>开启</option>
						<option value="0" <?php if($info['status'] == 0){echo 'selected="selected"';}?>>关闭</option>
					</select>
				</td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $indexUrl;?>');
	});
});
$('input[name="end_time"]').datepicker();
$('input[name="start_time"]').datepicker();
</script>
<?php echo $this->render("layout/footer.phtml");?>
