<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li ><a href="<?php echo $listUrl;?>">发放活动</a></li>
		<li><a href="<?php echo $addUrl;?>">添加活动</a></li>
		<li><a href="<?php echo $ticketDetailUrl;?>">代金券明细列表</a></li>
		<li><a href="<?php echo $moneyDetailUrl;?>">A币交易明细</a></li>
		<li><a href="<?php echo $detailUrl;?>">A券说明</a></li>
        <li><a href="<?php echo $gameVoucherDetailUrl;?>">游戏券说明</a></li>
		<li class="current"><a href="<?php echo $sendTicketUrl;?>">手动赠送</a></li>
	</ul>
</div>
<div class="table_full">
<form method="post" action="<?php echo $sendTicketPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
	<table width="100%">
        <tr class="tr">
            <th class="th">代金券类型</th>
            <td>
                <select name="ticketType" id="ticketType">
                    <?php foreach ($ticketType as $key => $value) { ?>
                        <option value="<?php echo $key?>"><?php echo $value?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr class="tr" id ="ticketObject" style="display:none;">
            <th class="th">游戏券应用范围</th>
            <td>
				<span>
					<label>
                        <input type="radio" name="ticketObject" value="1" checked>全平台
                        <input type="radio" name="ticketObject" value="2">单个游戏
                    </label>
				</span>
            </td>
        </tr>
        <tr class="tr" id="gameId" style="display:none;">
            <th class="th">游戏ID</th>
            <td>
                <input type="text" name="gameId" value=""> 必须要是联运游戏
            </td>
        </tr>
		<tr class="tr">
			<th class="th">赠送对象</th>
			<td>
				<span>
					<label>
						<input type="radio" name="userObject" value="1" checked>选择csv文件
						<input type="radio" name="userObject" value="2" >单个用户
					</label>
				</span>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">用户类型</th>
			<td>
				<span>
					<label>
						<input type="radio" name="userType" value="1" checked>用户名
						<input type="radio" name="userType" value="2" >UUID
					</label>
				</span>
			</td>
		</tr>
		<tr class="tr" id="csv">
			<th class="th">导入的csv文件</th>
			<td class="td">
				<input type="file" class="input" name="csv" value="">
				<a href="<?php echo $getTemplateUrl.'/?type=1';?>">用户名_csv模板</a>&nbsp;&nbsp;
				<a href="<?php echo $getTemplateUrl.'/?type=2';?>">uuid_csv模板</a>
			</td>
		</tr>
		<tr class="tr" id="uname" style="display:none;">
			<th class="th" id="unameTitle" >用户名</th>
			<td class="td">
				<input type="text" class="input wc" name="uname" value="">
			</td>
		</tr>
		<tr class="tr" id="denomination" style="display:none;">
			<th class="th">代金券面额</th>
			<td class="td"><input type="text" class="input" name="denomination" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">代金券开始结束时间</th>
			<td class="td">
			<input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="" />
			至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="" /></td>
		</tr>
		<tr class="tr">
				<th class="th">赠送原因</th>
				<td class="td">
                    <input class="input" type="text" maxlength="50" style="width:200px;"  name="reason" />  赠送原因最好控制在10个字
				</td>
			</tr>
		<tr>
			<td></td>
			<td><span class="btn2"><span><button type="submit">提交</button></span></span></td>
		</tr>			
	</table>
 </form>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script>
$(document).ready(function(){
	ajaxForm('addFrom', function(data) {
		ajaxRedirect(data, baseurl+'/Admin/Client_Acoupon/sendTicket');
	});
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();

     $('[name="userObject"]').click(function(){
    	 userObject = $(this).val();
          if(userObject == 1){
  				$('#csv').show();
  				$('#uname').hide();
  				$('#denomination').hide();
          }else if(userObject == 2){
        	    $('#csv').hide();
				$('#uname').show();
				$('#denomination').show();
          }
      });

     $('[name="userType"]').click(function(){ 
    	 userType = $(this).val();
         if(userType == 1){
        	 $('#unameTitle').html('用户名');
         }else{
        	 $('#unameTitle').html('UUID');
         }
       });

    $('#ticketType').change(function() {
        $('#ticketObject').hide();
        $('#gameId').hide();
        ticketType = $(this).val();
        ticketObj = $("input[name='ticketObject']:checked").val();
        if(ticketType == 2){
            $('#ticketObject').show();
            if(ticketObj ==2){
                $('#gameId').show();
            }
        }
    });

    $("input[name='ticketObject']").click(function(){
        $('#ticketType').trigger('change');
    });
})

</script>
<?php echo $this->render("layout/footer.phtml");?>