<?php echo $this->render("layout/admin_header.phtml");?>
	<div class="body">
	<h1 class="page-title" >管理后台</h1>
		<?php echo $this->render("layout/side.phtml");?>
		<div class="col-main">
			<div class="J_gift_error_tips error-pop-tips hidden">
			</div>
			<div class="keyword-body">
				<h2 class="title">信息提示</h2>
				<div style="border: 1px #CCC solid; padding: 10px 20px;">
				<p><?=$msg?></p>
				<p><a href="<?=$url?>">如果浏览器没有跳转, 请点击这里</a></p>
				</div>
			</div>
		</div>
	</div>
<script type="text/javascript">
setTimeout(goto,'<?=$waittime?>');
function goto() {
	window.location.href='<?=$url?>';
}
</script>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>