<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl; ?>">常见问题列表</a></li>
		<li class="current"><a href="javascript:;">编辑常见问题</a></li>
	</ul>
</div>
<div class="h_a">编辑常见问题</div>
<form method="post" action="<?php echo $editPostUrl; ?>" id="editForm">
	<input name="token" value="<?php echo $token; ?>" type="hidden"/> <input
		name="id" value="<?php echo $info['id']; ?>" type="hidden"/>

	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">排序</th>
				<td class="td"><input type="text" class="input" name="sort"
				                      value="<?php echo $info['sort']; ?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">问题</th>
				<td class="td"><input type="text" class="input wc" name="question"
				                      value="<?php echo $info['question']; ?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td"><select name="status" class="select">
						<option value="1" <?php if ($info['status'] == 1) echo 'selected'; ?>>开启</option>
						<option value="0" <?php if ($info['status'] == 0) echo 'selected'; ?>>关闭</option>
					</select></td>
			</tr>
			<tr class="tr">
				<th class="th">答案</th>
				<td class="td"><textarea id="answer"
				                         style="width: 800px; height: 500px" class="textarea"
				                         name="answer"><?php echo $info['answer']; ?></textarea>
				</td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script
	src="<?php echo $staticPath; ?>/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
<script type="text/javascript">
	var editor;
	KindEditor.ready(function (K) {
		K.token = $('#token').val();
		editor = K.create('textarea[name="answer"]', {
			resizeType: 1,
			allowPreviewEmoticons: false,
			allowImageUpload: false,
			items: EDITOR_ITEMS
		});
	});
	$(document).ready(function () {
		ajaxForm('editForm', function (ret) {
			ajaxRedirect(ret, baseurl + '/Admin/Questions/index');
		}, function () {
			editor.sync();
		});
	})
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
