<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<title>2014年度盛典-最佳动作游戏</title>
<link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/events/2014top/css/style.min.css?v=<?php echo $version;?>" />
</head>
<body>
	<div class="ui-pg-top">
		<div class="banner">
			<img src="<?php echo $staticroot; ?>/apps/game/events/2014top/img/05_01.jpg" alt="">
		</div>
		<div class="video-wrap">
			<h3>精彩视频</h3>
			<a class="video-box" href="http://v.youku.com/v_show/id_XODgxMzY0MTE2.html"></a>	
		</div>
		<div class="block">
			<p class="app-img">
				<img src="<?php echo $staticroot; ?>/apps/game/events/2014top/img/05_02.jpg" alt="">
			</p>
			<p class="app-txt">这是一款还未问世就备受期待，可谓是终于等到你，还好你没让我失望。凭借微操作格斗的核心玩法，超真实打击感彻底俘获游戏大厅玩家的心。一个字，真值。</p>
		</div>
		<div class="ui-buttons">
			<a class="ui-btn-download" href="http://gamedl.gionee.com/Attachments/dev/apks/2015/01/21/142182873133_signed.apk">立即下载</a>
		</div>
	</div>
</body>
</html>