<!DOCTYPE HTML>
<html>
<head>
<title><?php echo $title?$title:'金立游戏大厅';?></title> 
<meta charset="UTF-8">
<meta name="keyword" content="金立, 金立游戏, 游戏大厅" />
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<meta name="format-detection" content="email=no" />
</head>
<body>
<?php echo $info;?>
</body>
</html>