<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li style="display:none;"><a href="<?php echo $listUrl;?>">积分概况</a></li>
		<li><a href="<?php echo $presendIndexUrl;?>">人工发放</a></li>
        <li class="current"><a href="<?php echo $listUrl;?>">积分商城</a></li>
        <li><a href="<?php echo $pointDescIndexUrl;?>">积分说明管理</a></li>
	</ul>
</div>
<div class="h_a">添加商品</div>
<form method="post" action="<?php echo $addGoodPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="htype" id = "htype" type="hidden" value="2" />
<div class="table_full">
	<table width="100%">
	    <tr class="tr">
			<th class="th">商品名称</th>
			<td class="td"><input type="text" class="input wc" name="title" value=""></td>
	    </tr>
		<tr class="tr">
			<th class="th">商品图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">商品icon</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="iconImg">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="icon" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=iconImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
	   <tr class="tr">
			<th class="th">商品类型</th>
			<td class="td">
				<select name="type" onchange='showtd()'>
<?php foreach($type as $key=>$value) {?>				
					<option value="<?php echo $key;?>"><?php echo $value;?></option>
<?php }?>
				</select>
				&nbsp;&nbsp;&nbsp;<span id="effectime">有效期:<input type="text" class="input" name="effect_time" value=""></span>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">总数量</th>
			<td class="td"><input type="text" class="input" name="total_num" value=""></td>
		     
		</tr>
		<tr class="tr">
			<th class="th">每人兑换数量</th>
			<td class="td"><input type="text" class="input" name="preson_limit_num" value=""></td>
		     
		</tr>
		<tr class="tr">
			<th class="th">兑换消耗积分</th>
			<td class="td"><input type="text" class="input" name="consume_point" value=""></td>
		     
		</tr>
		<tr class="tr">
			<th class="th">生效时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="" /></div>
			</td>
		</tr>
		<tr class="tr" >
			<th class="th">状态</th>
			<td class="td">
			<select name="status" class="select wa">
				<option "selected" value="1">开启</option>
				<option  value="0">关闭</option>
			</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">保存</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
function showtd(){
	var value=$("select[name=type]").val();
	if(value == 1) {
		$('#effectime').hide();
	} else {
		$('#effectime').show();
	}
}
$(document).ready(function(){
	 $('#effectime').show();
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	 ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Mall_Goods/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
