<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
      <li class="current"><a href="<?php echo $listUrl;?>">游戏分类列表</a></li>
	</ul>
</div>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="action" id="action" type="hidden" value="" />
<input name="id" id="id" type="hidden" value="<?php echo $info['id'];?>" />
<div class="h_a">
	<span class="btn2"><span><button onclick="$('#action').val('sort');" type="submit">重新排序</button></span></span>
	<span class="btn2" style="display: none;"><span><button onclick="$('#action').val('open');" type="submit">开启</button></span></span>
	<span class="btn2" style="display: none;"><span><button onclick="$('#action').val('close');" type="submit">关闭</button></span></span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td><input type="checkbox" onclick="checkAll('.checkbox')"></td>
			<td width="100">排序</td>
			<td width="100">ID</td>
			<td>名称</td>
			<td>分类图片</td>
			<td>状态</td>
			<td>操作</td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><input class="checkbox" name="ids[]" value="<?php echo $value['id'];?>" type="checkbox"></td>
			<td><input type="text" class="input" style="width:30px" name="sort[<?php echo $value['id'];?>]" value="<?php echo $value['sort'];?>"></td>
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><img src="<?php echo $attachPath,$value['img'];?>" style="width: 150px; heigh:100px;"/></td>
			<td><?php echo $value['status'] ? '开启' : '关闭';?></td>
			<?php if($value['editable'] != 1) {?>
			<td><a href="<?php echo $editCtUrl;?>/?id=<?php echo $value['id'];?>">内容排序</a></td>
			<?php }?>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
</form>
<script>
$(document).ready(function(){
	ajaxForm('batchForm', function(data) {
		ajaxRedirect(data, baseurl+'/Admin/Client_Category/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
