<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>管理中心 Management center</title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
	<meta content="" name="description"/>
	<meta content="" name="author"/>
	<!-- <link href="<?php echo $staticPath; ?>/adminlab/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" /> -->
	<!-- <link href="<?php echo $staticPath; ?>/adminlab/assets/font-awesome/css/font-awesome.css" rel="stylesheet" /> -->
	<!-- <link href="<?php echo $staticPath; ?>/adminlab/new/css/login.css" rel="stylesheet"/> -->
	<style type="text/css">
		#login-body{
			background-color:#f7f7f7!important;margin:0;padding:0;
		}
		#login-body .alert{position:absolute;top:70px;left:0;right:0}
		.login-header{background:#2dcb73;border-width:0;height:60px}
		input,button{border:0;outline:0}
		#login{background:#f7f7f7;border:1px solid #dbdbdb;
				-webkit-border-radius:4px;border-radius:4px;background-color:white;background-image:-webkit-gradient(linear,50% 0,50% 100%,color-stop(0%,#f4f4f4),color-stop(100%,#fff));background-image:-webkit-linear-gradient(top,#f4f4f4,#fff);background-image:linear-gradient(top,#f4f4f4,#fff);-webkit-box-shadow:1px 1px 8px rgba(199,199,199,0.25),-1px -1px 8px rgba(199,199,199,0.25),0 1px 1px white inset;box-shadow:1px 1px 8px rgba(199,199,199,0.25),-1px -1px 8px rgba(199,199,199,0.25),0 1px 1px white inset;width:370px;margin:140px auto 0;padding:20px}
	#login .form-wrap{margin-bottom:15px}#login .form-wrap h4{margin-bottom:11px;font-weight:bold;color:#5d5d5d}#login .form-input{width:100%;margin-bottom:10px}
	#login .form-input input{width:348px;padding:10px;border:1px solid #ccc;-webkit-box-shadow:0 3px 3px rgba(0,0,0,0.08) inset;box-shadow:0 3px 3px rgba(0,0,0,0.08) inset}
	#login .form-pull{overflow:hidden;height:18px;line-height:18px;font-size:11px}#login .form-pull .pull-left{float:left;color:#868686}#login .form-pull .pull-right{float:right;color:#363636}
	#login .form-pull .pull-right a{color:#363636;text-decoration:none}#login .form-pull .pull-right a:hover{text-decoration:underline}#login .login-btn{display:block;width:100%;background:#2dcb73;box-shadow:1px 0 1px white,0 0 3px rgba(0,0,0,0.2) inset;-moz-box-shadow:1px 0 1px white,0 0 3px rgba(0,0,0,0.2) inset;-webkit-box-shadow:1px 0 1px white,0 0 3px rgba(0,0,0,0.2) inset;font-size:16px;color:#fff;text-shadow:none;padding:10px 0}
	#login .login-btn:hover{opacity:.8;color:#fff}input[type="checkbox"]{margin:0;vertical-align:middle;margin-top:-1px}#login-copyright{text-align:center;margin:0 auto;padding:10px 10px 0 10px;color:#999;font-size:11px}
	</style>
	<script>if (parent.window.location.href != location.href) parent.window.location.href = location.href;</script>
</head>

<body id="login-body">
<div id="login-wrap">
	<div class="login-header"></div>
	<div id="login">
		<form id="loginform" method="post" action="<?php echo $loginUrl; ?>">
			<div class="form-wrap">
				<h4>统一登录中心</h4>

				<div class="form-label form-input">
					<input id="input-username" type="text" name="username" autofocus="true" placeholder="用户名" value=""/>
				</div>
				<div class="form-label form-input">
					<input id="input-password" type="password" name="password" placeholder="密码"/>
				</div>
				<div class="form-label form-pull">
					<div class="pull-left">
						<input type="checkbox" name="remember" id="label-remember-me">
						<label for="label-remember-me" style="display:inline-block;">记住我</label>
					</div>
					<div class="pull-right">
						<a href="javascript:;" class="" id="forget-password">忘记密码？</a>
					</div>
				</div>
			</div>
			<input type="submit" id="login-btn" class="btn-block login-btn" value="登录"/>
		</form>
	</div>
	<!-- <div id="login-copyright">
		Copyright <a href="http://www.gionee.com/" target="_blank" d="">©Gionee</a> All Rights Reserved. Powered by <a href="javascript:;" target="_blank">H5 R&D Team</a>
	</div> -->
</div>
</body>
</html>