<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li ><a href="<?php echo $listUrl;?>">账号列表</a></li>
    <li class="current"><a href="javascript:;">账号详情</a></li>
	</ul>
</div>
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">金立UUID</th>
			<td class="td"><?php echo $user['uuid'];?></td>
		</tr>
		<tr class="tr">
			<th class="th">账号</th>
			<td class="td"><?php echo $user['uname'];?></td>
		</tr>
		<tr class="tr">
			<th class="th">昵称</th>
			<td class="td"> <?php echo $userInfo['nickname'];?></div>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">注册时间</th>
			<td class="td"> <?php echo date('Y-m-d H:i:s', $user['reg_time']) . "(" . $mode[$reglog['mode']] . ")";?></div>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">最后登录时间</th>
			<td class="td"> <?php echo date('Y-m-d H:i:s', $user['last_login_time']) . "(" . $mode[$lllog['mode']] . ")";?></div>
			</td>
		</tr>
	</table>
</div>
<?php echo $this->render("layout/footer.phtml");?>