<?php echo $this->render("layout/header.phtml");?>
	<div data-role="page" id="page" class="pro-detail" data-theme="no">
		<?php echo $this->render("layout/nav.phtml");?>
		<h1 class="inner-title"><strong>机型：<?php echo $info['mark'];?></strong></h1>
		</header>
		<div class="ct">
			<div class="scroll-pro">
				<a href="<?php echo $detailUrl . '?type='.$type.'&mark=' . $pre;?>" class="handle"><img src="<?php echo $staticResPath;?>//pic/jt_left.png" alt="" /></a>
				<a href="<?php echo $detailUrl . '?type='.$type.'&mark=' . $next;?>" class="handle"><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></a>
				<div class="box img-text">
					<ul class="oz">
						<li>
							<a href="<?php echo $picsUrl . '?type='.$type.'&mark=' . $mark;?>"><img
									src="<?php echo $attachPath.'/' . $info['thumb'];?>" alt="" />
								<span>参考价格：<em><?php echo $info['price'] ? '￥'.$info['price']: '即将上市' ;?></em><br /><?php echo $info['title'];?></span>
							</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="tab J_tabBox">
				<div class="J_tabHandle tab-handle clearfix">
					<ul>
						<li class="selected">参数</li>
						<li>功能</li>
					</ul>
				</div>
				<div class="J_tabMain text">
					<p><?php echo $info['param'] ;?></p>
				</div>
				<div class="J_tabMain text" style="display:none;">
					<p><?php echo $info['descrip'] ;?></p>
				</div>
			</div>
			<div class="ask">
				<p><a href="tel:4007796666">免费咨询</a></p>
			</div>
		</div>
	</div>
<?php echo $this->render("layout/footer.phtml");?>

