<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $indexUrl;?>">会员列表</a></li>
    <li class="current"><a href="javascript:;">编辑会员</a></li>
	</ul>
</div>
<div class="h_a">编辑会员</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="editFrom">
    <input name="id" value="<?php echo $userInfo['id'];?>" type="hidden"/>
    <input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">用户名</th>
			<td class="td"><?php echo $userInfo['username'];?></td>
		</tr>
		<tr class="tr">
			<th class="th">手机</th>
			<td class="td"><?php echo $userInfo['mobile'];?></td>
		</tr>
		<tr class="tr">
			<th class="th">生日</th>
			<td class="td"><?php echo $userInfo['birthday'];?></td>
		</tr>
		<tr class="tr">
			<th class="th">性别</th>
			<td class="td"><?php echo $sex[$userInfo['sex']];?></td>
		</tr>
		<tr class="tr">
			<th class="th">注册时间</th>
			<td class="td"><?php echo date('Y-m-d H:i:s', $userInfo['register_time']);?></td>
		</tr>
		<tr class="tr">
			<th class="th">最后登录时间</th>
			<td class="td"><?php echo date('Y-m-d H:i:s', $userInfo['last_login_time']);?></td>
		</tr>
		
		<tr class="tr">
			<th class="th">注册时间</th>
			<td class="td"><?php echo date('Y-m-d H:i:s', $userInfo['last_login_time']);?></td>
		</tr>
		
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
			<select name="status">
			<?php foreach($status as $key => $value) {?>
			       <option <?php echo $userInfo['status'] == $key ? 'selected="selected"' : '';?> value="<?php echo $key;?>"><?php echo $value;?></option>
			<?php }?>
            </select>
            </td>
		</tr>
	</table>
</div>
<div class="h_a">积分信息</div>
<div class="table_list">
	<table width="100%">
		<tr class="ct">
			<td width="200">银币</td>
			<td><?php echo $userInfo['silver_coin'];?></td>
		</tr>
		<tr class="ct">
			<td width="200">冻结银币</td>
			<td><?php echo $userInfo['freeze_silver_coin'];?></td>
		</tr>
		<tr class="ct">
			<td width="200">金币</td>
			<td><?php echo $userInfo['gold_coin'];?></td>
		</tr>
		<tr class="ct">
			<td width="200">冻结金币</td>
			<td><?php echo $userInfo['freeze_gold_coin'];?></td>
		</tr>
	</table>
</div>

<div class="h_a">第三方账号绑定</div>
<div class="table_list">
	<table width="100%">
		<tr class="ct">
			<td width="200">淘宝账号</td>
			<td><?php echo urldecode($userInfo['taobao_nick']);?></td>
		</tr>
	</table>
</div>

<div class="h_a">收货地址</div>
<div class="table_list">
	<table width="100%">
		<tr class="ct">
			<td><?php echo $address['adds'].'&nbsp;&nbsp;'.$address['detail_address'].'&nbsp;&nbsp;'.$address['realname'].'&nbsp;&nbsp;'.$address['mobile'].'&nbsp;&nbsp;'.$address['phone'].'&nbsp;&nbsp;'.$address['postcode'];?></td>
		</tr>
	</table>
</div>

<div class="h_a">更多资料</div>
<?php if($extends['id']){ ?>
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">邮 箱</th>
			<td class="td"><?php echo $extends['email'];?></td>
		</tr>
		<tr class="tr">
			<th class="th">QQ</th>
			<td class="td"><?php echo $extends['qq'];?></td>
		</tr>
		<tr class="tr">
			<th class="th">职 业</th>
			<td class="td"><?php echo $extends['job'] =="请选择" ? '':$extends['job'] ;?></td>
		</tr>
		<tr class="tr">
			<th class="th">爱 好</th>
			<td class="td"><?php echo $extends['love'] =="请选择" ? '':$extends['love'];?></td>
		</tr>
		<tr class="tr">
			<th class="th">年龄段</th>
			<td class="td"><?php echo $extends['age'] =="请选择" ? '':$extends['age'];?></td>
		</tr>
	</table>
<?php } ?>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">保存</button></span></span></div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('editFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Gouuser/index?s=1');
	});
})

</script>
<?php echo $this->render("layout/footer.phtml");?>
