<!DOCTYPE HTML>
<html>
<head>
    <title>娱乐休闲</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
    <meta name="apple-touch-fullscreen" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="format-detection" content="telephone=no" />
    <link rel="stylesheet" href="<?=$staticResPath?>/joke/css/style.min.css?v=<?=$version?>" />
</head>
<body class="ui-pg-app">
<div class="ui-pg-toolbar">
    <a class="btn-back" href="<?=$prevUrl?>"></a> <span class="txt">返回</span>
</div>

<div class="mod-main">
    <div class="mod-list">
        <div class="item" data-id="<?=$info['id']?>">
            <div class="">
                <h3 class="title"><?=$info['title']?></h3>

                <div class="text">
                    <?=$info['content']?>
                </div>
            </div>
            <div class="from"><a href="<?=$info['link']?>"><?=$info['from']?></a></div>

            <div class="tools">
                <?php
                $disable = 'icon-disable';
                if (empty($info['op_1_flag']) && empty($info['op_2_flag'])) {
                    $disable = '';
                }
                ?>
                <span class="icon-zan <?php echo $info['op_1_flag'] == 1 ? 'active' : $disable; ?>" data-like="<?=$info['op_1_flag']?>"><?=$info['op_1']?></span>
                <span class="icon-cai <?php echo $info['op_2_flag'] == 1 ? 'active' : $disable; ?>" data-like="<?=$info['op_2_flag']?>"><?=$info['op_2']?></span>
                <a href="#SOHUCS" id="changyan_count_unit" class="icon-discuss cy_cmt_count">0</a>
            </div>
        </div>
    </div>
    <div class="mod-pagination">
        <?php
        $prevLink = !empty($info['prevList'][0]['link']) ? $info['prevList'][0]['link'] : '';
        $lastLink = !empty($info['lastList'][0]['link']) ? $info['lastList'][0]['link'] : '';
        ?>

        <?php if (!empty($prevLink)): ?>
            <a class="btn-prev" href="<?=$prevLink?>">上一页</a>
        <?php else: ?>
            <span class="btn-prev btn-disable">上一页</span>
        <?php endif; ?>

        <?php if (!empty($lastLink)): ?>
            <a class="btn-next" href="<?=$lastLink?>">下一页</a>
        <?php else: ?>
            <span class="btn-next btn-disable">下一页</span>
        <?php endif; ?>
    </div>
    <!-- 通用banner 广告 -->
    <?php if (!empty($banner)): ?>
        <div class="mod-banner-wrap">
            <?php foreach ($banner as $val): ?>
                <a href="<?=$val['url']?>" target="_balnk"><img border="0" src="<?=$val['img']?>" width="100%" height="100px"></a>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <!-- 畅言评论 -->
    <?php
    $p = html_entity_decode(Gionee_Service_Config::getValue('changyan_comment_val'));
    if (!empty($p)):
        ?>
        <div class="mod-discuss">
            <div id="SOHUCS" sid="nav_fun_<?=$info['id']?>"></div>
        </div>
        <script id="changyan_mobile_js" charset="utf-8" type="text/javascript" src="http://changyan.sohu.com/upload/mobile/wap-js/changyan_mobile.js?<?=$p?>">
        </script>
        <script type="text/javascript" src="http://assets.changyan.sohu.com/upload/plugins/plugins.count.js">
        </script>
    <?php endif; ?>
    <!-- 畅言评论 end-->
</div>
<!-- load script -->
<script>
    var require = {
        urlArgs: 'v=<?=$version;?>' // 异步加载文件的版本号
    };
</script>
<?php $changyanappid = Gionee_Service_Config::getValue('changyan_app_id') ?>
<script id="cy_cmt_num" src="http://changyan.sohu.com/upload/plugins/plugins.list.count.js?clientId=<?=$changyanappid?>"></script>
<script data-main="<?=$staticResPath?>/joke/js/detail.min" src="<?=$staticResPath?>/joke/js/require.min.js?v=<?=$version?>"></script>
<!-- /load script -->
</body>
</html>