<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $indexUrl?>">道具兑换</a></li>
        <li class="current"><a href="javascript:;">道具兑换记录</a></li>
	</ul>
</div>
<div class="h_a">
	<span>共<?php echo count($data);?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td width="80">ID</td>
			<td width="150">奖品名称</td>
			<td width="150">总数量</td>
			<td width="80">已兑换用户数</td>
			<td width="80">可兑换用户数</td>
			<td width="150">操作</td>
		</tr>
		<?php foreach ($data as $item):?>
			<tr class = "ct">
		    	<td><?php echo $item['prizeId'];?></td>
				<td><?php echo $item['prizeName'];?></td>
				<td><?php echo $item['prizeTotal'];?></td>
				<td><?php echo $item['exchangeTotal'];?></td>
				<td><?php echo $item['availableTotal'];?></td>
				<td>
				    <a href="<?php echo $exchangeDetailUrl;?>/?festivalId=<?php echo $festivalId;?>&prizeId=<?php echo $item['prizeId'];?>" class="mr10">查看</a>
					<a href="<?php echo $exchangeExportUrl;?>/?festivalId=<?php echo $festivalId;?>&prizeId=<?php echo $item['prizeId'];?>" class="mr10">导出</a>
				</td>
			</tr>
		<?php endforeach;?>
	</table>
</div>
<div class="mr10 cc">
</div>
<?php echo $this->render("layout/footer.phtml");?>
