<?php echo $this->render("layout/header.phtml");?>
<body id="lazyload">
	<div class="module gray-bg webapp">
		<header class="header" id="J_header">
			<div class="wrap">
				<div class="title">
					<a href="<?php echo $webroot;?>" class="back"></a>
					<h1>海淘世界</h1>
				</div>
			</div>
		</header>
		<section class="iScroll layout-center" id="J_scrollWrap">
				<?php 
				$i = 0;
				foreach ($list as $key=>$value) {
                   if($i == 0 || $i % 3 == 0) echo '<div class="brand-list"><ul>';
                ?>
					<li>
						<a title="<?php echo html_entity_decode($value['name']);?>" href="<?php echo html_entity_decode($value['link']);?>">
							<div class="pic">
								<img src="<?php echo $staticRoot;?>/apps/dhm/asset/img/blank.gif" alt="<?php echo html_entity_decode($value['name']);?>" data-src="<?php echo Common::getAttachPath().$value['logo'];?>">
							</div>
							<p class="title"><?php echo html_entity_decode($value['name']);?></p>
						</a>
					</li>
				<?php
				$i++;
				if($i % 3 == 0 || $i == $total) echo '</ul></div>';
                 }
                 ?>
			
		</section>
	</div>


<?php echo $this->render("layout/footer.phtml");?>