<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $listUrl;?>">网游列表</a></li>
		<li><a href="<?php echo $addCtUrl;?>">添加网游</a></li>
		<li class="current"><a href="<?php echo $columnListUrl;?>">编辑网游频道</a></li>
		<li><a href="<?php echo $addColumnUrl;?>">添加网游频道</a></li>
	</ul>
</div>
<div class="h_a">编辑频道</div>
<form method="post" action="<?php echo $editColumnPostUrl;?>" id="editFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<input name="ckey" value="<?php echo $info['ckey'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
	   <tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="<?php echo $info['sort'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="name" value="<?php echo $info['name'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">链接地址</th>
			<td class="td"><input type="text" class="input wc" name="link" value="<?php echo $info['link'];?>"></td>
		</tr>	
		<tr class="tr">
			<th class="th">生效时间</th>
			<td class="td"><input type="text" class="input" name="start_time" value="<?php echo date('Y-m-d H:i:s', $info['start_time']);?>" id="start_time"></td>
		</tr>
		<tr class="tr" >
			<th class="th">状态</th>
			<td class="td">
			<select name="status" class="select">
				<option <?php echo ($info['status'] == 1) ? 'selected' : '';?> value="1">开启</option>
				<option <?php echo ($info['status'] == 0) ? 'selected' : '';?> value="0">关闭</option>
			</select>
			</td>
		</tr>		
</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
	 ajaxForm('editFrom',function(ret){
		 ajaxRedirect(ret, baseurl+'/Admin/Client_Web/columnList');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
