<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $listUrl;?>">客户端按钮导航</a></li>
        <li class="current"><a href="<?php echo $infoUrl;?>">说明</a></li>
	</ul>
</div>
<div class="h_a">
	<p>
		<span style="color: red">该功能由开发人员使用,其他同事尽量不要操作</span>
	</p>
	<p>
		<span>1&emsp;1.5.9版本</span>
	</p>
	<p>
		<span>1.1&emsp;&emsp;网游频道导航的显示窗口只支持: GiftListView、ServiceInfoView、CategoryDetailView</span>
	</p>
	<p>
		<span><br></span>
	</p>
</div>
<?php echo $this->render("layout/footer.phtml");?>
