<header class="hd">
	<nav class="main-nav">
		<ul>
			<li>
				<a href="<?php echo $webroot;?>">
					<span><img src="<?php echo $staticResPath;?>/pic/ico_navHome.png" alt="" /></span>
					<em>首页</em>
				</a>
			</li>
			<li>
				<a href="<?php echo $webroot;?>/product/index">
					<span><img src="<?php echo $staticResPath;?>/pic/ico_navPro.png" alt="" /></span>
					<em>产品</em>
				</a>
			</li>
			<li class="logo"><img src="<?php echo $staticResPath;?>/pic/logo.png" alt="" /></li>
			<li>
				<a href="<?php echo $webroot;?>/services/index">
					<span><img src="<?php echo $staticResPath;?>/pic/ico_navService.png" alt="" /></span>
					<em>服务中心</em>
				</a>
			</li>
			<li>
				<a href="http://wap.easou.com/?cid=bwcn3511_48212_20822_1&q=">
					<span><img src="<?php echo $staticResPath;?>/pic/ico_navSearch.png" alt="" /></span>
					<em>搜索</em>
				</a>
			</li>
		</ul>
	</nav>
</header>