<?php echo $this->render("layout/header2.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">游戏推荐列表</a></li>
    <li class="current"><a href="javascript:;">添加推荐内容</a></li>
	</ul>
</div>

<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<td class="td"><input type="text" class="input wc" id="title" name="title" value="">&nbsp;<button id="searchBtn" onfocus="blur();" type="button">搜索</button>
			</td>
		</tr>
	</table>
</div>

<form method="post" action="<?php echo $gamesPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_list">
	<table width="100%">
        <tr class="tr">
			<td width="200"  valign="top">
                <div class="h_a">游戏列表(<span id="querySize" style="color: red">0</span>条记录)</div>
				<div style="width:100%; height: 500px; border:1px solid #ccc; overflow :auto;">
					<table id="from" width="100%"  border="1" cellpadding="0" cellspacing="0" bordercolor="#ccc" style="border-collapse: collapse">
    					<thead>
    					   <tr class="hd">
        						<td><input id="all_move" type="checkbox"></td>
        						<td>图标</td>
        						<td>标题</td>
        						<td>分类</td>
        						<td>大小</td>
    						</tr>
    					</thead>
    					<tbody>
    					</tbody>
    				</table>
				</div>
			</td>
			<td width="100" style="text-align: center;">
                <div class="mb10 tac"><span><button id="move" onfocus="blur();" type="button"> &nbsp;>&nbsp;>&nbsp; </button></span></div>
                <div class="mb10 tac"><span><button id="delete" onfocus="blur();" type="button"> &nbsp;<&nbsp;<&nbsp; </button></span></div>
			</td>
			<td width="200"  valign="top">
                <div class="h_a">已选择(<span id="selectSize" style="color: red"><?php echo count($games);?></span>条记录)</div>
				<div style="width:100%; height: 500px; border:1px solid #ccc; overflow :auto;">
					<table id="to" width="100%"  border="1" cellpadding="0" cellspacing="0" bordercolor="#ccc" style="border-collapse: collapse">
    					<thead>
    					   <tr class="hd">
        						<td><input id="all_delete" type="checkbox"></td>
        						<td>图标</td>
        						<td>标题</td>
        						<td>分类</td>
        						<td>大小</td>
    						</tr>
    					</thead>
    					<tbody>
		<?php foreach($games as $key => $value) {?>
    					<tr class="ct"><td><input type="checkbox"><input type="hidden" name="games[]" value="<?php echo $value['game_id'];?>"></td>
							<td><img src="<?php echo $value['gameIcon']?>" style="width:70px;height:70px;"/></td>
							<td><?php echo $value['gameName']?></td>
							<td><?php echo $value['gameCategory']?></td>
							<td><?php echo $value['gameSize']?></td>
						</tr>
	   <?php } ?>
    					</tbody>
    				</table>
				</div>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">下一步</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $gamesSortUrl . "?id=" . $info['id'];?>');
	});
    
	$("#all_move").click(function() {
		var checkboxArr = $("#from tbody :checkbox");
		for(var i = 0; i < checkboxArr.length; i++) {
			checkboxArr[i].checked = this.checked;
		}
	});
	
	$("#all_delete").click(function() {
		var checkboxArr = $("#to tbody :checkbox");
		for(var i = 0; i < checkboxArr.length; i++) {
			checkboxArr[i].checked = this.checked;
		}
	});

	$("#move").click(function() {
		var toBody = $("#to tbody");
		var checkboxArr = $("#from tbody :checkbox");
		for(var i = 0; i < checkboxArr.length; i++) {
			if(checkboxArr[i].checked) {
			    var td = checkboxArr[i].parentNode;
			    td.childNodes[1].name="games[]";
				toBody.append(td.parentNode);
			}
		}
	    
		checkboxArr = $("#to tbody :checkbox");
		for(var i = 0; i < checkboxArr.length; i++) {
			checkboxArr[i].checked = false;
		}
	    $("#querySize").text($("#from tbody :checkbox").length);
	    $("#selectSize").text($("#to tbody :checkbox").length);
	    
		$("#all_move").attr("checked",false);
		$("#all_delete").attr("checked",false);
	});
	
	$("#delete").click(function() {
		var toBody = $("#from tbody");
		var checkboxArr = $("#to tbody :checkbox");
		for(var i = 0; i < checkboxArr.length; i++) {
			if(checkboxArr[i].checked) {
			    var td = checkboxArr[i].parentNode;
			    td.childNodes[1].name="game[]";
				toBody.append(td.parentNode);
			}
		}
	    
		checkboxArr = $("#from tbody :checkbox");
		for(var i = 0; i < checkboxArr.length; i++) {
			checkboxArr[i].checked = false;
		}

	    $("#querySize").text($("#from tbody :checkbox").length);
	    $("#selectSize").text($("#to tbody :checkbox").length);
	    	    
		$("#all_move").attr("checked",false);
		$("#all_delete").attr("checked",false);
	});

	$("#searchBtn").click(function(){
		var title = $("#title").val();
		if(title.length==0){
			alert("请输入要查找的游戏名称");
			return false;
		}
		var selectedArr = $("#to tbody input[name='games[]']");
	    var selectedId = [];
		for(var i = 0; i < selectedArr.length; i++) {
			selectedId[i] = selectedArr[i].value;
		}
		$.post("<?php echo $queryGameUrl;?>",
			{
		       token:"<?php echo $token;?>",
		       name: $("#title").val(),
		       selected: selectedId
			},
		    function(data, status){
			       if(data.success) {
				        var size = data.data.length;
			    	    $("#querySize").text(size);
			    	    $("#from tbody").empty();
			    	    var str = "";
			    		for(var i = 0; i < size; i++) {
			    			var info = data.data[i];
				    	    str += '<tr class="ct"><td><input type="checkbox"><input type="hidden" name="game[]" value="'+info['id']+'"></td>'+
							'<td><img src="'+info['gameIcon']+'" style="width:70px;height:70px;"/></td>'+
							'<td>'+info['gameName']+'</td>'+
							'<td>'+info['gameCategory']+'</td>'+
							'<td>'+info['gameSize']+'</td></tr>';
			    		}
			    	    $("#from tbody").append(str);
			    	}else{
			    		showMsg("提示", data.msg);
			    	}
			 });
	});
	
});
</script>
<?php echo $this->render("layout/footer.phtml");?>
