<?php echo $this->render("layout/header.phtml");?>
<div id="detail-page">
	<section class="wrap">
		<div class="detail-field">
			<dl>
				<dt class="icon"><img src="<?php echo $staticResPath; ?>/pic/blank.gif" alt="" data-src="<?php echo  $info['img'];?>"></dt>
				<dd class="desc">
					<p class="name"><?php echo $info['name'];?></p>
					<p class="info">
						<?php $tmp=$from == 'baidu' ? $info['category'] : $info['category_title']; if($tmp){?>
							<span><?php echo $from == 'baidu' ? $info['category'] : $info['category_title'];?></span><em>|</em>
						<?php }?>
						<span><?php echo $info['language'];?></span><em>|</em><span><?php echo $info['size'];?>M</span></p>
					<p class="origin"><?php echo $info['developer'];?></p>
				</dd>
			</dl>
		</div>

		<div class="detail-scrollPic" id="J_screenshot">
			<div class="pic-container">
				<div class="pic-wrap">
					<?php foreach($info['simgs'] as $key=>$value){?>
					<span><img src="<?php echo $staticResPath; ?>/pic/blank.gif" alt="" data-src="<?php echo $value;?>" data-bigpic="<?php echo $info['gimgs'][$key];?>"></span>
					<?php }?>
				</div>
			</div>
		</div>
		<div class="detail-text ui-editor">
			<div class="text-container">
				<p><?php echo html_entity_decode($info['descrip']);?></p>
			</div>
		</div>
	 <?php if(strnatcmp($app_version,'1.4.6') >= 0 && !stristr($intersrc,'gltj') && $games){?>
		<div class="suggest_field">
			<h1>您可能还喜欢</h1>
			<ul class="list">
				<?php $i=0; foreach($games as $key=>$value){
					if($i < 4){
			    $href = $webroot.'/client/index/detail/?id='.$value['id'].'&intersrc=gltj' . $info['id'].'_GID'.$value['id'] . '&t_bi='.$source;
				?>
				<li>
				  <a class="icon"data-infpage="<?php echo  ($checkVer >= 2 ? '游戏详情' : $value['name']).','.$href.','.$value['id'].$value['infpage'];?>">
				   <img src="<?php echo $staticResPath;?>/pic/blank.gif" data-src="<?php echo $value['img'];?>" alt="">
				  </a>
				  <span><?php echo $value['name'];?></span>
				</li>
				<?php } $i++;}?>
			</ul>
		</div>
		<?php }?>
	</section>
</div>
<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>