<?php echo $this->render("layout/header.phtml");?>
<style>
	.ct_01 td{
		padding: 7px 0px 9px;
		color: #666;
	}
	.text{
		border:1px solid gray ;
		background: #fff;
		min-height:40px; 
		margin-bottom: 4px;
	}
	.icon_user{
		background-position: -144px -96px;
		width: 16px;height: 16px;
	}
	
</style>
<div class="nav">
	<ul class="cc">
	    <li class="current"><a href="<?php echo $listUrl;?>">评论审核</a></li>
		<li><a href="<?php echo $manageUrl;?>">评论管理</a></li>
        <li><a href="<?php echo $logUrl;?>">审核记录</a></li>
        <li><a href="<?php echo $slistUrl;?>">敏感词库</a></li>
         <li><a href="<?php echo $plistUrl;?>">词库管理</a></li>
         <li><a href="<?php echo $blistUrl;?>">黑名单</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">	
	   <tr class="tr">
			<th class="th">游戏名称</th>
			<td class="td"><input type="text" class="input" name="name" value="<?php echo $s['name'];?>"></td>
			<th class="th">游戏ID</th>
			<td class="td"><input type="text" class="input" name="id" value="<?php echo $s['id'];?>"></td>
			<th class="th">用户昵称</th>
			<td class="td"><input type="text" class="input" name="nickname" value="<?php echo $s['nickname'];?>"></td>
		</tr>
		<tr class="tr">
		    <th class="th">用户帐号</th>
			<td class="td"><input type="text" class="input" name="uname" value="<?php echo $s['uname'];?>"></td>
			<th class="th">评论状态</th>
			<td class="td">
			 <select name="status" class="select wa">
			    <option  value="0">未审核</option>
				<option <?php if ($s['status'] == 3) echo 'selected';?> value="3">全部</option>
				<option <?php if ($s['status'] == 2) echo 'selected';?> value="2">审核不通过</option>
			 </select>
		   </td>
		   <th class="th">敏感词</th>
		 	<td class="td">
			 <select name=is_sensitive class="select wa">
			      <option  value="0">全部</option>
				<option <?php if ($s['is_sensitive'] == 1) echo 'selected';?> value="1">不包含</option>
				<option <?php if ($s['is_sensitive'] == 2) echo 'selected';?> value="2">包含</option>
			 </select>
			</td>
		</tr>
		<tr class="tr">
		    <th class="th">用户类型</th>
			<td class="td">
			<select name="utype" class="select wa">
			      <option  value="0">全部</option>
				  <?php foreach($utype as $key=>$value) {?>
    			  <option value="<?php echo $key;?>" <?php if($s['utype'] == $key) echo 'selected="selected"';?>><?php echo $value;?></option>
    			<?php }?>
			</select>
			</td>
			<th class="th">黑名单</th>
		 	<td class="td">
			 <select name=is_blacklist class="select wa">
				<option <?php if ($s['is_blacklist'] == 0 || !$s['is_blacklist']) echo 'selected';?> value="0">过滤</option>
				<option <?php if ($s['is_blacklist'] == 2) echo 'selected';?> value="2">不过滤</option>
			 </select>
			</td>
		</tr>
		<tr class="tr">
		    <th class="th">评论时间</th>
			<td class="td" colspan="2"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo $s['start_time'];?>" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="<?php echo $s['end_time'];?>" /></div>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="action" id="action" type="hidden" value="" />
<div class="h_a">
	<span class="btn2"><span><button onclick="$('#action').val('npass');" type="submit">审核不通过</button></span></span>
    <span class="btn2"><span><button onclick="$('#action').val('pass');" type="submit">审核通过</button></span></span>
    <span class="btn2"><span><button type="button" id="extportBtn">导出excel</button></span></span>
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td><input type="checkbox" onclick="checkAll('.checkbox')"></td>
			<td>游戏ID</td>
			<td>游戏名称</td>
			<td>评论时间</td>
			<td>审核时间</td>
			<td>评论状态</td>
			<td>敏感词</td>
			<td></td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct_01">
		    <td><input class="checkbox" name="ids[]" value="<?php echo $value['id'];?>" type="checkbox" style="margin-left:12px;"></td>
			<td><?php echo $value['game_id'];?></td>
			<td><?php echo $game_names[$value['game_id']];?></td>
		    <td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
			<td><?php echo $value['check_time'] ? date('Y-m-d H:i:s', $value['check_time']) : "";?></td>
			<td><?php echo $comment_status[$value['status']];?></td>
			<td><?php echo $value['is_sensitive'] == 1 ? '包含' : '不包含';?></td>
		</tr>
		<tr class="ct">
			<td colspan="7">
				<div class="text">
				    <?php if($value['badwords']) { $badwords = explode(',', $value['badwords']);
				    $temp = array();
				    for($i=1;$i<count($badwords);$i++){
				    	for($j=count($badwords)-1;$j>=$i;$j--){
				    		if(strlen($badwords[$j]) > strlen($badwords[$j-1])) {
				    			$temp = $badwords[$j-1];
				    			$badwords[$j-1] = $badwords[$j];
				    			$badwords[$j] = $temp;
				    		}
				    	}
				    }
				    ?> 
				    <?php  echo Common::filter($badwords, $value['title'], 1); ?>
				    <?php } else {?> 
				    <?php  echo $value['title']; ?> 
				    <?php }?> 
				</div>
				<span class="ui-icon ui-icon-person" style="display:inline-block;margin-bottom:-4px"></span>
				<?php 
				   if($s['utype'] == 1) {
				   	  $uname = $value['uname'];
				   } else if($s['utype'] == 2){
				   	  $uname = "IMEI:".$value['imei'];
				   } else {
				   	 $uname = ($value['utype'] == 1 ? $value['uname'] : "IMEI:".$value['imei']);
				   }
				?>
				<?php echo $value['nickname'];?>/<?php echo $uname;?>/<?php echo $value['model'];?>/<?php echo $value['client_pkg'] == "2" ? "游戏大厅" : "艾米游戏";?>/<?php echo $value['version'];?>/<?php echo $value['sys_version'];?>
			</td>
			<td style="width:110px;">
				<span class="btn2"><span><button  onclick="pass('pass',<?php echo $value['id'];?>)" type="button">通过</button></span></span>
    			<span class="btn2"><span><button  onclick="pass('npass',<?php echo $value['id'];?>)" type="button">不通过</button></span></span>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
</form>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<div class="mr10 cc">
	<form action="<?php echo $exportUrl;?>" method="post" id="exportForm">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	<input type="hidden" name="name" value="<?php echo $s['name'];?>">
	<input type="hidden" name="id" value="<?php echo $s['id'];?>">
	<input type="hidden" name="nickname" value="<?php echo $s['nickname'];?>">
	<input type="hidden" name="uname" value="<?php echo $s['uname'];?>">
	<input type="hidden" name="status" value="<?php echo $s['status'];?>">
	<input type="hidden" name="is_sensitive" value="<?php echo $s['is_sensitive'];?>">
	<input type="hidden" name="utype" value="<?php echo $s['utype'];?>">
	<input type="hidden" name="is_blacklist" value="<?php echo $s['is_blacklist'];?>">
	<input type="hidden" name="start_time" value="<?php echo $s['start_time'];?>">
	<input type="hidden" name="end_time" value="<?php echo $s['end_time'];?>">
	</form>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	 ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Comment/index');
	});
	$("#extportBtn").click(function(){
		$("#exportForm").submit();
    });
})
function pass(flag,id){
	$.ajax({
		url : baseurl + "/Admin/Client_Comment/singleUpdate",
		type : 'POST',
		dataType : 'json',
		data : 'token='+'<?php echo $token;?>'+'&id='+id+'&flag='+flag,
		success : function(ret) {
			 if (ret.success) {
				showMsg('', ret.msg);
			} else {
				showError('', ret.msg);
			}
			setTimeout(function() {
					location.href = baseurl + "/Admin/Client_Comment/index";
			}, 500);
		}
	});
}
</script>
<?php echo $this->render("layout/footer.phtml");?>
