<?php echo $this->render("layout/header.phtml");?>
<style>
	.ct_01 td{
		padding: 7px 0px 9px;
		color: #666;
	}
	.text{
		border:1px solid gray ;
		background: #fff;
		min-height:40px; 
		margin-bottom: 4px;
	}
	.icon_user{
		background-position: -144px -96px;
		width: 16px;height: 16px;
	}
	
</style>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $listUrl;?>">评论审核</a></li>
		<li><a href="<?php echo $manageUrl;?>">评论管理</a></li>
        <li class="current"><a href="<?php echo $logUrl;?>">审核记录</a></li>
        <li><a href="<?php echo $slistUrl;?>">敏感词库</a></li>
         <li><a href="<?php echo $plistUrl;?>">词库管理</a></li>
        <li><a href="<?php echo $blistUrl;?>">黑名单</a></li>
	</ul>
</div>
<form action="<?php echo $logUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">	
	   <tr class="tr">
			<th class="th">游戏名称</th>
			<td class="td"><input type="text" class="input" name="name" value="<?php echo $s['name'];?>"></td>
			<th class="th">游戏ID</th>
			<td class="td"><input type="text" class="input" name="game_id" value="<?php echo $s['game_id'];?>"></td>
			</td>
			<th class="th">用户昵称</th>
			<td class="td"><input type="text" class="input" name="nickname" value="<?php echo $s['nickname'];?>"></td>
			</td>
		</tr>
		<tr class="tr">
		    <th class="th">用户帐号</th>
			<td class="td"><input type="text" class="input" name="uname" value="<?php echo $s['uname'];?>"></td>
			<th class="th">审核状态</th>
			<td class="td">
			<select name="status" class="select wa">
			    <option  value="0">审核通过</option>
			    <option <?php if ($s['status'] == 3) echo 'selected';?> value="3">全部</option>
				<option <?php if ($s['status'] == 2) echo 'selected';?> value="2">审核不通过</option>
			</select>
			</td>
			<th class="th">审核人</th>
			<td class="td"><input type="text" class="input" name="check_name" value="<?php echo $s['check_name'];?>"></td>
			</td>
		</tr>
		<tr class="tr">
		   <th class="th">审核时间</th>
			<td class="td" colspan="2"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo $s['start_time'];?>" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="<?php echo $s['end_time'];?>" /></div>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="h_a">
    <span class="btn2"><span><button type="button" id="lextportBtn">导出excel</button></span></span>
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td>序号</td>
			<td>游戏ID</td>
			<td>游戏名称</td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct_01">
		    <td><?php echo $value['id'];?></td>
			<td><?php echo $value['game_id'];?></td>
			<td><?php echo $game_names[$value['game_id']];?></td>
		</tr>
		<tr class="ct">
			<td colspan="7">
				<div class="text">
					<?php echo $value['title'];?>
				</div>
				<span class="ui-icon ui-icon-person" style="display:inline-block;margin-bottom:-4px"></span>
				<?php 
				   $uname = ($value['utype'] == 1 ? $value['uname'] : "IMEI:".$value['imei']);
				?>
				<?php echo $value['nickname'];?>/<?php echo $uname;?>/<?php echo $value['model'];?>/<?php echo $value['client_pkg'] == "2" ? "游戏大厅" : "艾米游戏";?>/<?php echo $value['version'];?>/<?php echo $value['sys_version'];?><br>
				<span>提交时间:<?php echo date('Y-m-d H:i:s', $value['create_time']);?></span>&nbsp;&nbsp;&nbsp;<br>
				<?php foreach($comments[$value['id']] as $k=>$v){ ?>
				<span>审核时间:<?php echo date('Y-m-d H:i:s', $v['check_time']);?></span>&nbsp;&nbsp;&nbsp;<?php echo $v['check_name'];?>&nbsp;&nbsp;&nbsp;<?php echo $v['operate'] ? "删除" : $comment_status[$v['status']];?><br>
			    <?php } ?>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<div class="mr10 cc">
	<form action="<?php echo $lexportUrl;?>" method="post" id="lexportForm">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	<input type="hidden" name="manage" value="manage">
	<input type="hidden" name="name" value="<?php echo $s['name'];?>">
	<input type="hidden" name="game_id" value="<?php echo $s['game_id'];?>">
	<input type="hidden" name="nickname" value="<?php echo $s['nickname'];?>">
	<input type="hidden" name="uname" value="<?php echo $s['uname'];?>">
	<input type="hidden" name="status" value="<?php echo $s['status'];?>">
	<input type="hidden" name="check_name" value="<?php echo $s['check_name'];?>">
	<input type="hidden" name="start_time" value="<?php echo $s['start_time'];?>">
	<input type="hidden" name="end_time" value="<?php echo $s['end_time'];?>">
	</form>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Comment/log');
	});
	$('#start_time').datetimepicker();
    $('#end_time').datetimepicker();
	$("#lextportBtn").click(function(){
		$("#lexportForm").submit();
    });
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
