<?php echo $this->render("layout/header.phtml"); ?>

	<div class="nav">
		<ul class="cc">
			<li><a href="<?php echo $expuserUrl;; ?>">等级用户数据</a></li>
			<li class="current"><a href="<?php echo $expchannelUrl;; ?>">经验获取途经</a></li>
			<li><a href="<?php echo $exprankUrl; ?>">经验值排名</a></li>
			<li><a href="<?php echo $expusedUrl; ?>">等级特权使用情况</a></li>
		</ul>
	</div>
	<form method="post" action="<?php echo $baseUrl; ?>" id="addFrom">
		<input type="hidden" name="token" value="<?php echo $token; ?>"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">时间范围</th>
					<td class="td">
						<input class="input" type="text" maxlength="30" id="sdate" name="sdate" value="<?php echo $sdate; ?>"> 至
						<input class="input" type="text" id="edate" maxlength="30" name="edate" value="<?php echo $edate; ?>">

					</td>
				</tr>

			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
		<input type="hidden" id="hidden_export" name="export" value="0"/>
	</form>

	<div class="h_a">
		&nbsp; <span id="total" style="color: red;font-size:14px"></span>
		<span style="float:right;"><input type="button" value="导出" id="downLoad"></span>
	</div>

	<div class="table_list">
		<table width="100%">
			<tr class="ct">
				<td class="td2" style="width:62px;">查询日期</td>
				<td class="td2">登陆发放经验数</td>
				<td class="td2">反馈用户获取经验数</td>
				<td class="td2">互动用户获取经验数</td>
				<td class="td2">意见采纳获取经验数</td>
			</tr>
			<?php
			foreach ($data as $k => $v) { ?>
				<tr class="ct">
					<td><?php echo date('Y-m-d', strtotime($k)); ?></td>
					<?php foreach ($types as $s) { ?>
						<td class="td2"><?php echo $v[$s]['points']; ?></td>
					<?php } ?>
				</tr>
			<?php } ?>
		</table>
	</div>

	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>

	<script type="text/javascript">
		$(document).ready(function () {
			$("#sdate").datepicker({dateFormat: 'yy-mm-dd'});
			$("#edate").datepicker({dateFormat: 'yy-mm-dd'});
			$("#total").text('<?php echo $sum;?>');
			$("#downLoad").bind('click', function () {
				$("#hidden_export").val(1);
				$("#addFrom").submit();
				$("#hidden_export").val(0);
			});
		});
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>