<?php echo $this->render("layout/header.phtml"); ?>
	<form method="post" action="<?php echo $baseUrl; ?>" id="addFrom">
		<input type="hidden" name="token" value="<?php echo $token; ?>"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">时间范围</th>
					<td class="td">
						<input class="input" type="text" maxlength="30" id="sdate" name="sdate" value="<?php echo $searchParam['sdate']; ?>"> 至
						<input class="input" type="text" id="edate" maxlength="30" name="edate" value="<?php echo $searchParam['edate']; ?>">

					</td>
				</tr>
				<tr class="tr">
					<th class="th">累计签到天数</th>
					<td class="td">
						<input type="text" class="input_w" name="days" value="<?php echo $searchParam['days']; ?>"/>
					</td>
				</tr>
			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
		<input type="hidden" id="hidden_export" name="export" value="0"/>
	</form>

	<div class="h_a">
		&nbsp; <span id="total" style="color: red;font-size:14px"></span>
		<span style="float:right;"><input type="button" value="导出" id="downLoad"></span>
	</div>

	<div class="table_list">
		<table width="100%">
			<tr class="ct">
				<td class="td2" width="200">用户</td>
				<td class="td2" width="200">用户名</td>
				<td class="td2">累计签到天数</td>
			</tr>
			<?php
			foreach ($dataList as $k => $v) { ?>
				<tr class="ct">
					<td><?php echo $v['name']; ?></td>
					<td><?php echo $v['realname']; ?></td>
					<td class="td2"><?php echo $v['cnt']; ?></td>
				</tr>
			<?php } ?>
		</table>
	</div>
	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>

	<script type="text/javascript">
		$(document).ready(function () {
			$("#sdate").datepicker({dateFormat: 'yy-mm-dd'});
			$("#edate").datepicker({dateFormat: 'yy-mm-dd'});
			$("#total").text('<?php echo $sum;?>');
			$("#downLoad").bind('click', function () {
				$("#hidden_export").val(1);
				$("#addFrom").submit();
				$("#hidden_export").val(0);
			});
		});
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>