<?php echo $this->render("layout/header.phtml"); ?>
	<form method="post" action="<?php echo $baseUrl; ?>" id="addFrom">
		<input type="hidden" name="token" value="<?php echo $token; ?>"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">时间范围</th>
					<td class="td">
						<input class="input" type="text" maxlength="30" id="sdate" name="sdate" value="<?php echo $sdate; ?>"> 至
						<input class="input" type="text" id="edate" maxlength="30" name="edate" value="<?php echo $edate; ?>">

					</td>
				</tr>

			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
		<input type="hidden" id="hidden_export" name="export" value="0"/>
	</form>

	<div class="h_a">
		&nbsp; <span id="total" style="color: red;font-size:14px"></span>
		<span style="float:right;"><input type="button" value="导出" id="downLoad"></span>
	</div>

	<div class="table_list">
		<table width="100%">
			<tr class="ct">
				<td class="td2" style="width:62px;">查询日期</td>
				<td class="td2">页面PV</td>
				<td class="td2">页面UV</td>
				<td class="td2">10金币按钮PV</td>
				<td class="td2">10金币按钮UV</td>
				<td class="td2">20金币按钮PV</td>
				<td class="td2">20金币按钮UV</td>
				<td class="td2">50金币按钮PV</td>
				<td class="td2">50金币按钮UV</td>
				<td class="td2">100金币按钮PV</td>
				<td class="td2">100金币按钮UV</td>
				<td class="td2">完成夺宝总用户数</td>
				<td class="td2">完成夺宝总次数</td>
				<td class="td2">人均夺宝次数</td>
				<td class="td2">金币发放总数</td>
				<td class="td2">金币回收总数</td>
				<td class="td2">访问-夺宝转化率</td>
			</tr>
			<?php
			foreach ($data as $k => $v) { ?>
				<tr class="ct">
					<td><?php echo $k; ?></td>
					<td class="td2"><?php echo $v['index_pv'] ? $v['index_pv'] : 0; ?></td>
					<td class="td2"><?php echo $v['index_uv'] ? $v['index_uv'] : 0; ?></td>
					<td class="td2"><?php echo $v['goods']['10']['snatch_goods_pv'] ? $v['goods']['10']['snatch_goods_pv'] : 0; ?></td>
					<td class="td2"><?php echo $v['goods']['10']['snatch_goods_uv'] ? $v['goods']['10']['snatch_goods_uv'] : 0; ?></td>
					<td class="td2"><?php echo $v['goods']['20']['snatch_goods_pv'] ? $v['goods']['20']['snatch_goods_pv'] : 0; ?></td>
					<td class="td2"><?php echo $v['goods']['20']['snatch_goods_uv'] ? $v['goods']['20']['snatch_goods_uv'] : 0; ?></td>
					<td class="td2"><?php echo $v['goods']['50']['snatch_goods_pv'] ? $v['goods']['50']['snatch_goods_pv'] : 0; ?></td>
					<td class="td2"><?php echo $v['goods']['50']['snatch_goods_uv'] ? $v['goods']['50']['snatch_goods_uv'] : 0; ?></td>
					<td class="td2"><?php echo $v['goods']['100']['snatch_goods_pv'] ? $v['goods']['100']['snatch_goods_pv'] : 0; ?></td>
					<td class="td2"><?php echo $v['goods']['100']['snatch_goods_uv'] ? $v['goods']['100']['snatch_goods_uv'] : 0 ?></td>
					<td class="td2"><?php echo $v['snatch_users'] ? $v['snatch_users'] : 0; ?></td>
					<td class="td2"><?php echo $v['snatch_times'] ? $v['snatch_times'] : 0; ?></td>
					<td class="td2"><?php echo $v['snatch_times'] ? bcdiv($v['snatch_times'], $v['snatch_users'], 2) : 0 ?></td>
					<td class="td2"><?php echo $v['snatch_prize_scores'] ? $v['snatch_prize_scores'] : 0; ?></td>
					<td class="td2"><?php echo $v['snatch_cost_scores'] ? $v['snatch_cost_scores'] : 0; ?></td>
					<td class="td2"><?php echo $v['snatch_users'] ? (bcdiv($v['snatch_users'], $v['index_uv'], 4) * 100) . "%" : 0 ?></td>
				</tr>
			<?php } ?>
		</table>
	</div>

	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>

	<script type="text/javascript">
		$(document).ready(function () {
			$("#sdate").datepicker({dateFormat: 'yy-mm-dd'});
			$("#edate").datepicker({dateFormat: 'yy-mm-dd'});
			$("#total").text('<?php echo $sum;?>');
			$("#downLoad").bind('click', function () {
				$("#hidden_export").val(1);
				$("#addFrom").submit();
				$("#hidden_export").val(0);
			});
		});
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>