<?php echo $this->render("layout/header.phtml"); ?>

	<div class="nav">
		<ul class="cc">
			<li><a href="<?php echo $chatDay; ?>">日报表</a></li>
			<li><a href="<?php echo $chatMonth; ?>">月报表</a></li>
			<li><a href="<?php echo $veDetailUrl; ?>">兑换时长明细表</a>
			<li class="current"><a href="<?php echo $vcenterUrl; ?>">畅聊页统计</a>
		</ul>
	</div>
	<form method="post" action="<?php echo $baseUrl; ?>" id="addFrom">
		<input type="hidden" name="token" value="<?php echo $token; ?>"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">时间</th>
					<td class="td">
						<input class="input" type="text" maxlength="30" id="sdate" name="sdate" value="<?php echo $params['sdate']; ?>">至
						<input class="input" type="text" maxlength="30" id="edate" name="edate" value="<?php echo $params['edate']; ?>">
					</td>
				</tr>
			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
		<input type="hidden" id="hidden_export" name="export" value="0"/>
	</form>
	<p>
		<span style="padding-left:50px;color:blue">兑换率：兑换分钟按键PV / 畅聊账户页面PV;</span>
	</p>
	<p>
		<span style="padding-left:50px;color:blue">兑换成功次数: 兑换成功次数 / 兑换分钟按键PV;</span>
	</p>
	<div class="h_a">
		&nbsp; <span id="total" style="color: red;font-size:14px"></span>
		<span style="float:right;"><input type="button" value="导出" id="downLoad"></span>
	</div>

	<div class="table_list">
		<table width="100%">
			<tr class="ct">
				<td class="td2">日期</td>
				<td class="td2" width="120px">畅聊账户页面PV</td>
				<td class="td2">畅聊账户页面UV</td>
				<td class="td2">兑换分钟按键PV</td>
				<td class="td2">兑换率</td>
				<td class="td2">兑换成功次数</td>
				<td class="td">兑换成功率</td>
			</tr>
			<?php
			foreach ($data as $k => $v) { ?>
				<tr class="ct">
					<td><?php echo $k; ?></td>
					<td class="td2"><?php echo $v['voip_center_pv'] ? $v['voip_center_pv'] : 0; ?></td>
					<td class="td2"><?php echo $v['voip_center_uv'] ? $v['voip_center_uv'] : 0; ?></td>
					<td class="td2"><?php echo $v['voip_exchange_pv'] ? $v['voip_exchange_pv'] : 0; ?></td>
					<td class="td2"><?php echo $v['voip_exchange_ratio']; ?></td>
					<td class="td2"><?php echo $v['voip_exchange_success_times'] ? $v['voip_exchange_success_times'] : 0; ?></td>
					<td class="td2"><?php echo $v['voip_exchange_success_ratio']; ?></td>
				</tr>
			<?php } ?>
		</table>
	</div>

	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>

	<script type="text/javascript">
		$(document).ready(function () {
			$("#sdate").datepicker({dateFormat: 'yymmdd'});
			$("#edate").datepicker({dateFormat: 'yymmdd'});
			$("#downLoad").bind('click', function () {
				$("#hidden_export").val(1);
				$("#addFrom").submit();
				$("#hidden_export").val(0);
			});
		});
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>