<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class="current"><a href="<?php echo $content; ?>">广告位列表</a></li>
			<li><a href="<?php echo $addUrl; ?>">添加广告位</a></li>
		</ul>
	</div>
	<div class="table_list">
		<table style="width: 100%">
			<tr class="hd">
				<th class="th">ID</th>
				<th class="th">名称</th>
				<th class="th">广告位标识</th>
				<th class="th">类型</th>
				<th class="th">状态</th>
				<th class="th">操作</th>
			</tr>
			<?php foreach ($dataList as $v) { ?>
				<tr class="ct">
					<td class="td" align="left"><?=$v['id'];?></td>
					<td class="td" align="left"><?=$v['name'];?></td>
					<td class="td"><?php echo $v['identifier'] ?></td>
					<td class="td"><?php echo $types[$v['type']]; ?></td>
					<td class="td" style='color:blue'><?php echo $v['status'] ? '开启' : '结束'; ?></td>
					<td class="td"><a href="<?php echo $editUrl; ?>/?id=<?php echo $v['id']; ?>">编辑</a>&nbsp;
						<a href="javascript:void(0);" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $v['id']; ?>', '', event);">删除</a>
				</tr>
			<?php } ?>
		</table>
	</div>

	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>
<?php echo $this->render("layout/footer.phtml"); ?>