<?php echo $this->render("layout/header.phtml");?>
	<div id="page">
		<?php echo $this->render("layout/nav.phtml");?>
		<article class="ac contact">
			<div class="services">
				<ul class="service-list">
					<li><a href="<?php echo $webroot,"/services/questions?t_bi=",$t_bi;?>">
							<div class="pic"><img src="<?php echo $staticResPath;?>/pic/services/01.png" alt="" /></div>
							<div class="txt">常见问题</div>
						</a></li>
					<li><a href="<?php echo $webroot,"/services/policy?t_bi=",$t_bi;?>">
							<div class="pic"><img src="<?php echo $staticResPath;?>/pic/services/02.png" alt="" /></div>
							<div class="txt">售后政策</div>
						</a></li>
					<li><a href="<?php echo $webroot,"/services/service?t_bi=",$t_bi;?>">
							<div class="pic"><img src="<?php echo $staticResPath;?>/pic/services/03.png" alt="" /></div>
							<div class="txt">服务网点</div>
						</a></li>
					<li><a href="<?php echo $webroot,"/services/sale?t_bi=",$t_bi;?>">
							<div class="pic"><img src="<?php echo $staticResPath;?>/pic/services/04.png" alt="" /></div>
							<div class="txt">销售网点</div>
						</a></li>
					<li><a href="<?php echo $webroot,"/services/contact?t_bi=",$t_bi;?>">
							<div class="pic"><img src="<?php echo $staticResPath;?>/pic/services/05.png" alt="" /></div>
							<div class="txt">联系我们</div>
						</a></li>
				</ul>
			</div>
		</article>		
	</div>
<?php echo $this->render("layout/tj.phtml");?>
<?php echo $this->render("layout/footer.phtml");?>
