<?php echo $this->render("../../Front/views/layout/header.phtml");?>
<section id="page">
	<header id="header"><!-- HEADER --></header>
	<!-- 主体内容 -->
	<section id="content">
		<section class="pfeedback">
			<h3>欢迎您给我们提出宝贵的意见，让我们一起把金立购变的更好。</h3>
			<div class="pinfo mod-form-list">
				<form action="<?php echo $webroot.$addPostUrl;?>" method="post" id="J_checkForm">
				<input name="token" value="<?php echo $token;?>" type="hidden" />
				<input name="status" value="1" type="hidden" />
					<div class="field tt-input">
						<div class="numTips"></div>
						<textarea placeholder="请输入您的反馈意见（字数500字以内）" name="react"></textarea>
					</div>
					<div class="btm-line00"></div>
					<div class="btm-line01"></div>
					<div class="field button"><button type="button" class="btn orange" id="J_saveForm">确认</button></div>
				</form>
			</div>
		</section>
	</section>
	<!--  /主体内容 -->
	<footer id="footer"><!-- FOOTER --></footer>
</section>
</body>
</html>