<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">闪屏列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加闪屏</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">	
		<tr>
		   <th class="th">状态</th>
			<td class="td">
			<select name="status" class="wa">
			    <option  value="0">全部</option>
				<?php foreach ($status as $key=>$value) { ?>
						<option value="<?php echo $key;?>" <?php if($search['status'] == $key) echo 'selected="selected"';?>><?php echo $value;?></option>
				<?php } ?>
				</select>
			</td>
			<th class="th">渠道</th>
			<td class="td">
			<select name="channel_id" class="wa">
			    <option  value="0">全部</option>
				<?php foreach ($channels as $key=>$value) { ?>
						<option value="<?php echo $key;?>" <?php if($search['channel_id'] == $key) echo 'selected="selected"';?>><?php echo $value;?></option>
				<?php } ?>
				</select>
			</td>
			<th class="th">分辨率</th>
			<td class="td">
			<select name="type_id" class="wa">
			    <option  value="0">全部</option>
				<?php foreach ($types as $key=>$value) { ?>
						<option value="<?php echo $key;?>" <?php if($search['type_id'] == $key) echo 'selected="selected"';?>><?php echo $value;?></option>
				<?php } ?>
				</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="50">排序</td>
			<td width="100">渠道</td>
			<td width="100">分辨率</td>
			<td>图片</td>
			<td>url</td>
			<td>开始时间</td>
            <td>结束时间</td>
            <td width="50">状态</td>
            <td>点击</td>
            <td width="80">操作</td>
		</tr>
<?php foreach($starts as $key => $value) {?>
		<tr class="ct">
		     <td><?php echo $value['sort']; ?></td>
             <td><?php echo $channels[$value['channel_id']]; ?></td>
             <td><?php echo $types[$value['type_id']]; ?></td>
			<td><img src="<?php echo $attachPath.$value['img'];?>" style="width:70px;height:70px;"/></td>
			<td><?php echo $value['url'];?></td>
		    <td><?php echo date('Y-m-d H:i:s', $value['start_time']);?></td>
		    <td><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
			<td><?php echo $value['status'] == 1 ? '开启' : '关闭';?></td>
            <td><a href="/admin/stat/click?type_id=34&item_id=<?php echo $value['id'];?>" target="_blank"><?php echo $value['hits'];?></a></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Start/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
