<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $indexUrl;?>">渠道列表</a></li>
    <li class="current"><a href="javascript:;">添加渠道</a></li>
	</ul>
</div>
<div class="h_a">添加渠道</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input wb" name="sort" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input wc" name="name" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">链接</th>
			<td class="td"><textarea class="input wc" name="link"></textarea></td>
		</tr>
		<tr class="tr">
			<th class="th">图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
				<select class="wa" name="status">
					<option value="1">开启</option>
					<option value="0">关闭</option>
				</select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">描述</th>
			<td class="td"><textarea class="input wc" name="descript"></textarea></td>
		</tr>
		<tr class="tr">
				<th class="th">是否推荐</th>
				<td class="td">
				<input type="hidden" name="is_recommend" id="is_recommend" value="0"/>
				<input type="checkbox" onclick="if(this.checked){$('#is_recommend').val(1);}else{$('#is_recommend').val(0);}">(选中表示设为推荐)
				</td>
			</tr>
		<tr class="tr">
			<th class="th">开始结束时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="" /></div>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Channel/index');
	});
	$('#start_time').datetimepicker();
    $('#end_time').datetimepicker();
})

</script>
<?php echo $this->render("layout/footer.phtml");?>
