<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class="current">webp图片转换</a></li>
		</ul>
	</div>

	<form enctype="multipart/form-data" action="<?php echo $baseUrl; ?>" method="post" id="editForm">
		<input name="token" type="hidden" value="<?php echo $token; ?>">

		<div class="table_full">
			<table width="100%">
				<tbody>
				<tr class="tr">
					<th class="th" style="width: 40px;">图片</th>
					<td>
						<input name="img" type="file" />
					</td>
				</tr>
				</tbody>
			</table>
		</div>
		<div class="mb10 tac">
			<span class="btn"><span><button type="submit">提交</button></span></span>
		</div>
	</form>

<?php echo $this->render("layout/footer.phtml"); ?>