<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="pay_paymsg_changeprice">
        <div class="content">
            <!--res_message start-->
            <div class="res_message">
                <div class="view_admin view_list_admin">
                    <!-- checkClass表示 点击后 哪些class要被选中 -->
                    <button class="btn_check btn_check_all" checkclass="btn_check_list"></button>
                    <label>全选</label>
                    <label><a class="pop_btn del_all btn_txt" openPopId="fixTipView">删除</a></label>
                </div>
                <table class="view_list_tb message">
                    <thead>
                        <tr>
                            <th>发件人</th>
                            <th>主题</th>
                            <th>时间</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($msgInfo as $v) { ?>
                            <tr class="<?php if (!$v["Is_read"]) echo 'on'; ?>">
                                <td><button class="btn_check check_data btn_check_list" val="<?php echo $v['id'] ?>" ></button>
                                    <span>
                                        <?php if ($groupid == 1) { ?>
                                            <?php echo $v["check_name"]; ?>
                                        <?php } ?>
                                        <?php if ($groupid == 2) { ?>
                                            <?php echo $v["auth"]; ?>
                                        <?php } ?>
                                        <?php if ($groupid == 3) { ?>
                                            <?php echo "测试" ?>
                                        <?php } ?>

                                    </span></td>
                                <td><a href="/Admin/fileadmin/fileedit?themeid=<?php echo $v['themeId']; ?>" target="_blank">
                                        <span class="<?php if (!$v["Is_read"]) echo 'A_read'; ?>" val="<?php echo $v['id']; ?>">
                                            <?php if ($groupid == 1) { ?>
                                                将<?php echo $v['name'] ?>的状态改为<?php echo $status[$v['status']]; ?>
                                            <?php } ?>
                                            <?php if ($groupid == 2) { ?>
                                                提交了<?php echo $v['name'] ?>主题  状态<em  class="refuse"><?php echo $status[$v['status']]; ?></em>
                                            <?php } ?>
                                            <?php if ($groupid == 3) { ?>
                                                <i class="num">1</i>把主题<?php echo $v['name'] ?> 状态改为  <?php echo $status[$v['status']]; ?>
                                            <?php } ?>
                                        </span></a>
                                </td>
                                <td>  <?php if ($groupid == 1) { ?>
                                        <?php echo date("Y-m-d :H:i:s", $v['check_time']) ?>
                                    <?php } ?>
                                    <?php if ($groupid == 2) { ?>
                                        <?php echo date("Y-m-d :H:i:s", $v['upload_time']) ?>
                                    <?php } ?>
                                    <?php if ($groupid == 3) { ?>
                                        <?php echo date("Y-m-d :H:i:s", $v['check_time']) ?>
                                    <?php } ?></td>
                            </tr>

                        <?php } ?>
                       <!-- <tr>
                            <td><button class="btn_check check_data btn_check_list" ></button><span>主题公园</span></td>
                            <td><a href="#" target="_blank"><span>《恋爱季主题》已经审核通过</span></a></td>
                            <td>2015.6.11</td>
                        </tr>
                        <tr>
                            <td><button class="btn_check check_data btn_check_list" ></button><span>主题公园</span></td>
                            <td><a href="#" target="_blank"><span>《恋爱季主题》主题审核<em  class="refuse">被拒绝</em></span></a></td>
                            <td>2015.6.11</td>
                        </tr>
                        <tr>
                            <td><button class="btn_check check_data btn_check_list" ></button><span>主题公园</span></td>
                            <td><span><i class="num">2</i>爱之恋主题待上架</span></td>
                            <td>2015.6.11</td>
                        </tr>
                        -->
                    </tbody>
                </table>
            </div><!--res_message end-->
        </div><!-- content end -->
    </div>
</section>

<?php echo $this->render("common/pageshow.phtml"); ?>
<!-- 弹窗 消息+按钮-->
<div class="pop_wraper" id="fixTipView">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_tip">
                    <p class="tip_mes">是否删除已选中的消息</p>
                    <div class="tip_btns"><button class="btn_s2 save_ok " id="upload02ViewList">确定</button>
                        <button class="btn_s2 btnCancel " >取消</button></div>
                    <div class="pop_close"></div>
                </div>

            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->
<script type="text/javascript">
    $(function () {
        $(".A_read").click(function () {
            var id = $(this).attr("val");
            var url = "/Admin/Ucenter/msg_reads";
            var data = "id=" + id + "&token=" + token;
            $.post(url, data, function () {

            });
        })

        $(".save_ok").click(function () {
            $("#fixTipView").removeClass("show");
            var arrval = [];
            $('.btn_check_list').each(function (index) {
                var $this = $(this);
                if ($this.hasClass('on')) {
                    var arr = $(".btn_check_list").eq(index).attr('val');
                    arrval.push(arr);
                }
            })
            var url = "/Admin/Ucenter/msgDel";

            var data = "ids=" + arrval + "&token=" + token;
            $.post(url, data, function () {
            })
        })
        //刷新当前页面
        $('.message tbody td a').on('click', function () {
            window.location.reload();
        })
    })
</script>
</body>
</html>