<form name="personalInfo" id="personalInfo">
    <div class="com_tb_wrap">
        <div class="com_tb">
            <label class="tb_cell tb_title">*真实姓名 :</label>
            <div class="tb_cont tb_cell">
                <input name="real_name" type="text" class="rd_1 w300" value="<?php echo $userDetail['real_name'];?>">
            </div>
        </div>
    </div>

    <div class="com_tb_wrap">
        <div class="com_tb">
            <label class="tb_cell tb_title">*身份证号码 :</label>
            <div class="tb_cont tb_cell">
                <input name="id_number" type="text" class="rd_1 w300" value="<?php echo $userDetail['id_number'];?>">
            </div>
        </div>
    </div>

    <div class="com_tb_wrap">
        <div class="com_tb">
            <label class="tb_cell tb_title">*邮箱 :</label>
            <div class="tb_cont tb_cell">
                <input name="email" type="text" class="rd_1 w300" value="<?php echo $userDetail['email'];?>">
            </div>
        </div>
    </div>

    <div class="com_tb_wrap">
        <div class="com_tb">
            <label class="tb_cell tb_title">*联系电话 :</label>
            <div class="tb_cont tb_cell">
                <input name="tel" type="text" class="rd_1 w300" value="<?php echo $userDetail['tel'];?>">
            </div>
        </div>
    </div>

    <div class="com_tb_wrap">
        <div class="com_tb">
            <label class="tb_cell tb_title">*开户银行名称 :</label>
            <div class="tb_cont tb_cell">
                <div class="select_box" id="bank" style="width:150px;">
                    <label class="select_val check_data" style="background-position: 7.25rem" val="<?php echo $userDetail['bank']; ?>">
                        <?php if(!empty($userDetail[ 'bank'])){ echo $banks[$userDetail[ 'bank']]; } else { echo '请选择'; } ?>
                    </label>
                    <ul class="select_option" style="width:150px;">
                        <?php foreach ($banks as $k=> $v) { ?>
                        <li val="<?php echo $k; ?>">
                            <?php echo $v; ?>
                        </li>
                        <?php } ?>
                    </ul>
                </div>
                <input type="hidden" name="bank" value="" />
            </div>
        </div>
    </div>

    <div class="com_tb_wrap">
        <div class="com_tb">
            <label class="tb_cell tb_title">*开户名称 :</label>
            <div class="tb_cont tb_cell">
                <input name="account_name" id="account_name" type="text" class="rd_1 w300" value="<?php echo $userDetail['account_name'];?>" holder="开户名称必须和真实公司名称一致">
            </div>
        </div>
    </div>

    <div class="com_tb_wrap">
        <div class="com_tb">
            <label class="tb_cell tb_title">*开户支行 :</label>
            <div class="tb_cont tb_cell">
                <input name="branch" id="branch" type="text" class="rd_1 w300" value="<?php echo $userDetail['branch'];?>" holder="如不清楚请联系银行">
            </div>
        </div>
    </div>

    <div class="com_tb_wrap">
        <div class="com_tb">
            <label class="tb_cell tb_title">*银行卡号 :</label>
            <input name="ori_card_number" type="hidden" value="<?php echo $userDetail['card_number'];?>" />
            <div class="tb_cont tb_cell">
                <input name="card_number" id="card_number" type="text" class="rd_1 w300" value="<?php echo $userDetail['card_number'];?>">
            </div>
        </div>
    </div>

    <div class="com_tb_wrap">
        <div class="com_tb">
            <label class="tb_cell tb_title">*再次输入银行卡号 :</label>
            <div class="tb_cont tb_cell">
                <input name="check_card_number" type="text" class="rd_1 w300" value="">
            </div>
        </div>
    </div>

    <div class="com_tb_wrap">
        <div class="com_tb">
            <label class="tb_cell align_middle tb_title">*身份证扫描件 :</label>
            <div class="tb_cont tb_cell">
                <button class="btn_s3" id="uploadIdPic_btn">点击上传</button>
                <input id="uploadIdPic_input" style="display: none" type="file" name="uploadIdPic_input">
                <span class="prompt_txt">税务登记执照扫描件限制为4M</span>
                <input type="hidden" value="<?php echo $userDetail['id_pic'];?>" name="uploadIdPic" />
                <?php if($userDetail['id_pic']){ ?>
                    <p class="prompt_txt clear-fix special_txt" id="uploadIdPic_demo"><a target="_blank" href="<?php echo $iconUrl. '/idcardIcon/' . $userDetail['id_pic'];?>">身份证扫描件.jpg</a></p>
                <?php } else { ?>
                    <p class="prompt_txt clear-fix special_txt" style="display:none" id="uploadIdPic_demo"><a target="_blank" href="#">身份证扫描件.jpg</a></p>
                <?php } ?>
            </div>
        </div>
    </div>

    <div class="com_tb_wrap">
        <div class="com_tb">
            <label class="tb_cell tb_title">示例 :</label>
            <div class="tb_cont tb_cell">
                <img style="width:400px" src="/statics/freetribe/image/id_demo.png" />
            </div>
        </div>
    </div>
</form>