<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="zt_ucenter_edit">
        <div class="content">
            <form name="userInfo" id="userInfo">
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <span class="ucenter_header fl h18">基础资料</span>
                       
                    </div>
                </div>

                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">昵称 :</label>
                        <div class="tb_cont tb_cell">
                            <div class="name"><?php echo $userInfo['nick_name'];?></div>
                        </div>
                    </div>
                </div>

                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">性别 :</label>
                        <div class="tb_cont tb_cell">
                            <div class="sex"><?php if($userInfo['sex'] == 1){ echo '男'; } else { echo '女'; } ?></div>
                        </div>
                    </div>
                </div>

                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell align_middle tb_title">头像 :</label>
                        <div class="tb_cont tb_cell">
                            <div class="account_pic">
                                <img <?php if($userInfo[ 'icon']){?>src="
                                <?php echo $iconUrl. '/userIcon/'.$userInfo[ 'icon']. '?t='.time();?>" uri="<?php echo $userInfo[ 'icon'];?>"
                                <?php } else {?>src="/statics/freetribe/image/default_user_icon.png"
                                <?php } ?> style="width:140px">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <div class="ucenter_header fl h18">支付必备</div>
                        <div class="fl pay_header_desc">&nbsp;&nbsp;(用于获得收入分成)</div>
                    </div>
                </div>

                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">角色：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role"><?php if($userDetail['designer_type'] == 0){?>个人设计师<?php } else { ?>企业设计师<?php } ?></div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">真实姓名：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role"><?php echo $userDetail['real_name'];?></div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">身份证号码：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role"><?php echo $userDetail['id_number'];?></div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">邮箱：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role"><?php echo $userDetail['email'];?></div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">联系电话：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role"><?php echo $userDetail['tel'];?></div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">开户银行名称：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role"><?php echo $userDetail['bank'];?></div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">开户人姓名：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role"><?php echo $userDetail['account_name'];?></div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">开户支行：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role"><?php echo $userDetail['branch'];?></div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">银行卡号：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role"><?php echo $userDetail['card_number'];?></div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <!-- content end -->
    </div>
</section>
</body>

</html>