<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">分类列表</a></li>
    <li class="current"><a href="javascript:;">添加分类</a></li>
	</ul>
</div>
<div class="h_a">添加分类</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">		
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="name" value=""></td>
		</tr>
		<tr class="tr">
				<th class="th">图片</th>
				<td class="td">
					<ul class="uploadImg">
						<li id="AdImg">
							<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
							<input type="hidden" name="image" value="">
						</li>
					</ul>
					<p style="clear:both;">
						  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
					</p>
				</td>
			</tr>
		<tr class="tr">
			<th class="th">一级分类</th>
			<td class="td"><select name="root_id" onchange="setparents(this.value)">
			<option value="0">无</option>
<?php foreach($roots as $key => $value) {?>
                    
                <option value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
<?php }?>
            </select></td>
		</tr>
		<tr class="tr" id="parents_tr">
			<th class="th">二级分类</th>
			<td class="td">
			<select name="parent_id"></select>
            </td>
		</tr>
		
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value=""></td>
		</tr>
		
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Category/add');
	});

	var parents = <?php echo json_encode($parents);?>;
	setparents = function(parent_id) {
		var options = '<option value="0">无</option>';
		$.each(parents, function(index,data){
			var s = '';
			if (data.root_id == parent_id) {
				options += '<option value="'+data.id+'">'+data.name+'</option>';
			}
		});
		$("select[name='parent_id']").html(options);
	}
	setparents(<?php echo $roots[0]['id'];?>);
	if(parents == '') $("#parents_tr").hide();
})

</script>
<?php echo $this->render("layout/footer.phtml");?>
