<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<meta name="format-detection" content="telephone=no" />
	<title><?php echo $notice_title?$notice_title:'';?></title>
	<link rel="stylesheet" type="text/css" href="<?php echo $staticResPath;?>/call/css/style.source.css?ver=<?php echo $version;?>" />
	<style type="text/css">
		.ui-page-blank{
			font-size:12px; color:#333; line-height: 28px;
		}
		.ui-page-blank p{
			text-indent: 24px; margin-bottom: 5px;
		}
		.ui-page-blank strong{
			color:#f00;
		}
		.ui-page-blank .team{
			text-align: right;
		}
	</style>
</head>

<body class="ui-app">
<div class="ui-top-bar">
	<a class="ui-pos link-back" href="/user/index/index"></a>
	<span class="ui-top-txt"><?php echo $notice_title?$notice_title:'';?></span>
</div>

<div class="ui-page ui-page-notice js-active">
	<div class="ui-page-content">
		<div class="ui-page-blank">
			<?=$notice_txt?>

		</div>
	</div>
</div>
</body>
</body>
</html>