<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $listUrl;?>">福利任务</a></li>
		<li class="current"><a href="<?php echo $dlistUrl;?>">连续登录</a></li>
		<li ><a href="<?php echo $dailyTaskUrl;?>">每日任务</a></li>
		<li><a href="<?php echo $taskInfoConfigUrl;?>">任务说明</a></li>
	</ul>
</div>

<form method="post" action="<?php echo $continueLoginActivityAddPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">	
		<tr class="tr">
			<th class="th">活动名称</th>
			<td class="td"><input type="text" class="input wc" name="task_name" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">弹出框图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="simg">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img" value="">
					</li>
				</ul>			
				<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=simg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">活动开始结束时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="" /></div>
			</td>
		</tr>
		<tr class="tr" >
				<th class="th">奖励方式</th>
				<td class="td">
				   <div>
				    <div><input checked name="award_type" value="1" type="radio">登录奖励&nbsp;+&nbsp;&nbsp;
				    <input name="award_1" value=""/> &nbsp;&nbsp;<span><font color="#FF0000">(必须填写正整数)</font></span></div>
				    <div><input name="award_type" value="2" type="radio">登录奖励&nbsp;×&nbsp;&nbsp;
				    <input name="award_2" value=""/> &nbsp;&nbsp;<span><font color="#FF0000">(必须填写正整数)</font></span></div>
				  </div>
				</td>
			</tr>
		<tr class="tr" >
			<th class="th">状态</th>
			<td class="td">
			<select name="status" class="select wa">
				<option "selected" value="1">开启</option>
				<option  value="0">关闭</option>
			</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('#start_time').datetimepicker();
	$('#end_time').datetimepicker();      
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Wealtaskconfig/dindex');
	});
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
