<form method="post" action="" id="edit_form">
	<input name="id" value="<?php echo $info['id']; ?>" type="hidden"/>
	<input name="token" value="<?php echo $token; ?>" type="hidden"/>
	<table class="editTable">
		<tr>
			<th>名称</th>
			<td>
				<input type="text" style="width:250px;" class="easyui-textbox" name="title" required="true" value="<?php echo $info['title']; ?>">
			</td>
		</tr>
		<tr>
			<th>imei外部路径</th>
			<td>
				<input type="text" style="width:250px;" class="easyui-textbox" name="file_url" required="true" value="<?php echo $info['file_url']; ?>">
			</td>
		</tr>
		<tr>
			<th>imei内部路径</th>
			<td><?php echo $info['file_path']; ?></td>
		</tr>
	</table>
</form>