<!DOCTYPE html>
<html lang="en">
    <head>
        <?php
        $this->title = '首页';
        $this->hasSearch = 'true';
        ?>
        <meta charset="UTF-8">
        <title>金立游戏大厅</title>
<?php echo $this->render("layout/cssInc.phtml"); ?>
    </head>
    <body>
        <div id="roll" class="roll index-roll">

        </div>

        <div class="index-search">
            <a href="<?=Util_Statist::geSearchUrl('home')?>">
                <input type="text" placeholder="输入搜索关健字" />
                <div class="absolute-vCenter">
                    <span class="icon-search"></span>
                </div>
            </a>
        </div>

        <div id="menu">	

        </div>
        <div id="container">
        </div>
        <div id="advertisingData">

        </div>
<?php if($indexAd) {?>  
        <div class="prompt-layer" id="prompt">
		<span class="del" name="del">+</span>
			<div class="prompt-layer-bg">
			</div>
			<span class="del" name="del">+</span>
			<?php if($indexAd['button_title']) {?>
                                                        <a href="<?=Util_Statist::getOutLinkUrl($indexAd['button_url'], 'home_tooltip')?>">
                                                        <input type="button"  value="<?=$indexAd['button_title']?>" />
                                                        </a>
                                                        <?php }?>
			<p><?=$indexAd['title']?></p>
	</div>
<?php }?>
        <div id="footer"></div>
<?php echo $this->render("layout/scriptInc.phtml"); ?>
        <script type="text/javascript">
            var pageData = {}
            , rollData = {}
            ;
            pageData.biVar = '&t_bi=<?=$bi?>';
            pageData.biUri = '/index/closeTooltip/?intersrc=home_tooltip_close&t_bi=<?=$bi?>';
            pageData.list = <?= $dataInfoList ?>;
            pageData.picturePath = '<?php echo $appImg ?>';
            rollData.data = <?= $dataBannerList ?>;
            var menuData = {
                list: [
                    {
                        name: '分类'
                        , type: 'category'
                        , href: '/category/index?intersrc=home_NAV_CATGlist'

                    },
                    {
                        name: '排行'
                        , href: '/rank/index?intersrc=home_NAV_ranklist'
                        , type: 'rank'
                    },
                    {
                        name: '新游'
                        , href: '/channel/newGame?intersrc=home_NAV_newglist'
                        , type: 'newGame'
                    },
                    {
                        name: '活动'
                        , href: '/activity/index?intersrc=home_NAV_eventlist'
                        , type: 'activity'
                    },
                    {
                        name: '破解'
                        , href: '/channel/crackGame?intersrc=home_NAV_cracklist'
                        , type: 'crack'
                    },
                    {
                        name: '网游'
                        , href: '/channel/webGame?intersrc=home_NAV_olglist'
                        , type: 'webGame'
                    },
                    {
                        name: '单机'
                        , href: '/channel/singleGame?intersrc=home_NAV_pcglist'
                        , type: 'singleGame'
                    },
                    {
                        name: '论坛'
                        , href: '/index/linkRedirect/?url=<?=urlencode("/client/bbs/index")?>&intersrc=home_NAV_forum'
                        , type: 'forum'
                    }
                ]
            }
            $(function(){
          		 $('#footer').html('<?php echo str_replace(PHP_EOL, '', $this->render("layout/footer.phtml")); ?>');	   
             })
        </script>
        <script src="<?php echo "$appJs/sys/touchSwipe.js$timestamp"; ?>"></script>
        <script src="<?php echo "$appJs/view/menu.js$timestamp"; ?>"></script>
        <script src="<?php echo "$appJs/view/roll.js$timestamp"; ?>"></script>
        <script src="<?php echo "$appJs/index.js$timestamp"; ?>"></script>
<?php echo $this->render("layout/lastscriptInc.phtml"); ?>
    </body>
</html>