<!DOCTYPE HTML>
<?php if($cache) {?>
<html manifest="/api/cache/index?cn=<?php echo $cn;?>">
<?php } else {?>
<html>
<?php }?>
<head>
	<meta charset="UTF-8">
	<title>游戏大厅</title>
	<meta name="keyword" content="金立, 金立游戏, 游戏大厅" />
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<meta name="format-detection" content="email=no" />
<link rel="stylesheet" href="<?php echo $staticroot; ?>??/sys/reset/phonecore.css,/apps/game/channel/assets/css/game.css?v=<?php echo $version;?>" />
<script type="text/javascript"  src="<?php echo $staticroot; ?>/sys/icat/1.1.6/icat.js?v=<?php echo $version;?>" data-main="~apps/game/channel/assets/js/main.js"></script>
<script type="text/javascript">var game_source='<?php echo $game_source?>', t_bi = "<?php echo $t_bi;?>";</script>
</head>






