<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $newUrl;?>">最新发布</a></li>
	    <li><a href="<?php echo $listUrl;?>">下载最多</a></li>
	    <li class="current"><a href="<?php echo $monthUrl;?>">月榜</a></li>
            <li><a href="<?php echo $olrankUrl;?>">网游活跃榜</a></li>
	    <li><a href="<?php echo $soaringUrl;?>">游戏飙升榜</a></li>
        <li><a href="<?php echo $setUrl;?>">排行榜设置</a></li>
        <li><a href="<?php echo $manUrl;?>">排行榜管理</a></li>
        <li><a href="<?php echo $weekUrl;?>">周榜管理</a></li>
	</ul>
</div>
<div class="h_a">编辑月榜默认数据&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="<?php echo $monthUrl;?>">返回</a></div>
<form action="<?php echo $monthEditUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="id" id="id" type="hidden" value="<?php echo $info['id'];?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">游戏ID</th>
			<td class="td"><input type="text" class="input wb" name="id" value="<?php echo $s['id'];?>"></td>
			<th class="th">游戏关键字</th>
			<td class="td"><input type="text" class="input wb" name="name" value="<?php echo $s['name'];?>"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="action" id="action" type="hidden" value="" />
<input name="id" id="id" type="hidden" value="<?php echo $info['id'];?>" />
<div class="h_a">
    <span class="btn2"><span><button onclick="$('#action').val('sort');" type="submit">重新排序</button></span></span>
	<span class="btn2"><span><button onclick="$('#action').val('delete');" type="submit">删除</button></span></span>
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td><input type="checkbox" onclick="checkAll('.checkbox')"></td>
			<td width="30">排序</td>
			<td width="30">ID</td>
			<td>标题</td>
			<td>图标</td>
			<td>大小</td>
			<td>版本号</td>
			<td width="120">下载量</td>
			<td width="120">上线时间</td>
			<td>状态</td>
		</tr>
<?php foreach($games as $key => $value) {?>
		<tr class="ct">
		    <td><input class="checkbox" name="ids[]" value="<?php echo $guess_games[$value['id']]['id'],'|',$value['id'];?>" type="checkbox"></td>
			<td><input type="text" class="input" style="width:30px" name="sort[<?php echo $value['id'];?>]" value="<?php echo $guess_games[$value['id']]['sort'];?>"></td>
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['name'];?></td>
			<td><img src="<?php echo $value['img'];?>" style="width:7.2em;height:7.2em"/></td>
        	<td><?php echo $oline_versions[$value['id']]['size'];?>M</td>
        	<td><?php echo $oline_versions[$value['id']]['version'];?></td>
        	<td><?php echo $value['downloads'];?></td>
        	<td><?php echo date('Y-m-d H:i:s', $value['online_time']);?></td>
        	<td><?php echo $value['status'] ? '已上线' : '已下线';?></td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
</form>
<script>
$(document).ready(function(){
	ajaxForm('batchForm', function(data) {
		ajaxRedirect(data, baseurl+'/Admin/Client_Rank/editCt?id=<?php echo $info['id'];?>&s=1');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
