<?php echo $this->render("layout/singleheader.phtml");?>
	<body data-pagerole="body">
	<div class="module">
		<div class="download-gou">
			<a href="http://goudl.gionee.com/apps/shoppingmall/GN_Gou-I01000.apk" class="btn-soft-upgrade"></a>
			<a href="http://gdown.baidu.com/data/wisegame/877a576bd43d05ff/gouwudating_1120202004.apk" target="_blank" class="btn-soft-update"></a>
		</div>
	</div>	
	
<?php echo $this->render("layout/newfooter.phtml");?>