<?php echo $this->render("layout/header.phtml"); ?>
	<form method="post" action="<?php echo $baseUrl; ?>" id="addFrom">
		<input type="hidden" name="token" value="<?php echo $token; ?>"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">时间范围</th>
					<td class="td">
						<input class="input" type="text" maxlength="30" id="sdate" name="sdate" value="<?=$sdate?>"> 至
						<input class="input" type="text" id="edate" maxlength="30" name="edate" value="<?=$edate?>">
					</td>
				</tr>
				<tr class="tr">
					<th class="th">短链接值</th>
					<td class="td">
						<textarea style="width: 200px;height: 100px;" name="short_val"><?=$shortval?></textarea>
					</td>
				</tr>
			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
		<input type="hidden" id="hidden_export" name="export" value="0"/>
	</form>

	<div class="h_a">
		&nbsp; <span id="total" style="color: red;font-size:14px"></span>
		<span style="float:right;"><input type="button" value="导出" id="downLoad"></span>
	</div>

	<div class="table_list">
		<table width="100%">
			<tr class="ct">
				<td class="td2">日期</td>
				<td class="td2" width="80px">key</td>
				<td class="td2">名称</td>
				<td class="td2">访问PV</td>
				<td class="td2">访问UV</td>
			</tr>
			<?php
			foreach ($lineData as $k => $v) { ?>
				<tr class="ct">
					<td><?php echo $v['date']; ?></td>
					<td class="td2"><?php echo $v['key']; ?></td>
					<td class="td2"><?php echo $v['name']; ?></td>
					<td class="td2"><?php echo $v['pv']; ?></td>
					<td class="td2"><?php echo $v['uv']; ?></td>
				</tr>
			<?php } ?>
		</table>
	</div>


	<script type="text/javascript">
		$(document).ready(function () {
			$("#sdate").datepicker({dateFormat: 'yy-mm-dd'});
			$("#edate").datepicker({dateFormat: 'yy-mm-dd'});
			$("#total").text('<?php echo $sum;?>');
			$("#downLoad").bind('click', function () {
				$("#hidden_export").val(1);
				$("#addFrom").submit();
				$("#hidden_export").val(0);
			});
		});
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>