<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl; ?>">栏目列表</a></li>
		<li class="current"><a href="javascript:;">添加栏目</a></li>
	</ul>
</div>
<div class="h_a">添加栏目</div>
<form method="post" action="<?php echo $addPostUrl; ?>" id="addFrom">
	<input name="token" value="<?php echo $token; ?>" type="hidden"/>

	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">排序</th>
				<td class="td"><input type="text" class="input" name="sort" value="0"></td>
			</tr>
			<tr class="tr">
				<th class="th">标题</th>
				<td class="td"><input type="text" class="input wc" name="title" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">分类</th>
				<td class="td">
					<select class="wa" name="pptype" onchange="change(this.value);">
						<option value="1">接口</option>
						<option value="2">外链</option>
					</select>
				</td>
			</tr>
			<tr class="tr" id="link" style="display:none">
				<th class="th">链接地址</th>
				<td class="td"><input type="text" class="input wc" name="link" value=""></td>
			</tr>
			<tr class="tr" id="ptype">
				<th class="th">内容性质</th>
				<td class="td">
					<select name="ptype" class="wa">
						<?php foreach ($types as $key => $value) { ?>
							<option value="<?php echo $key; ?>"><?php echo $value; ?></option>
						<?php } ?>
					</select>
				</td>
			</tr>
			<tr class="tr" id="source_id">
				<th class="th">内容源</th>
				<td class="td">
					<select name="source_id">
						<?php foreach ($sources as $key => $value) { ?>
							<option value="<?php echo $key; ?>"><?php echo $value['name']; ?></option>
						<?php } ?>
					</select>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">图片</th>
				<td class="td">
					<ul class="uploadImg">
						<li id="AdImg">
							<img src="<?php echo $staticPath; ?>/img/content/nopic.jpg"/>
							<input type="hidden" name="img" value="">
						</li>
					</ul>
					<p style="clear:both;">
						<iframe name="upload" src="<?php echo $uploadUrl . '/?imgId=AdImg'; ?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
					</p>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">颜色</th>
				<td class="td"><input type="text" class="input wa" name="color" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td"><select name="status">
						<option value="1">开启</option>
						<option value="0">关闭</option>
					</select></td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script src="<?php echo $staticPath; ?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
	//栏目表单数据提交
	function change(val) {
		if (val == 1) {
			$("#ptype").show();
			$("#link").hide();
			$("#source_id").show();
		} else {
			$("#link").show();
			$("#ptype").hide();
			$("#source_id").hide();
		}
	}
	$(document).ready(function () {
		$('#start_time').datetimepicker();
		$('#end_time').datetimepicker();

		ajaxForm('addFrom', function (ret) {
			ajaxRedirect(ret, baseurl + '/Admin/Column/index');
		});
	})
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
