<?php echo $this->render("layout/webheader.phtml");?>
<body id="jhnews" data-pagerole="body">
	<div class="module for-browser">
		<header id="iHeader" class="hd">
			<div class="top-wrap">
				<div class="title">
					<a href="<?php echo $webroot;?>" class="back"></a>
					<h1>购物</h1>
				</div>
			</div>
		</header>
		<div id="iScroll">
			<div class="panel"></div>
		</div>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>