<?php echo $this->render("common/navigator.phtml"); ?>
<style>
  .com_tb_wrap .com_tb label{
    width:180px;
  }
</style>
<link rel="stylesheet" href="<?php echo $staticPath ?>jssdk/plugins/uploadify/uploadify.css" type="text/css" />
<!-- 导航栏Ajax加载 指向navagator.html menuOn表示分别需要高亮的菜单栏id
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <!-- wp01-壁纸详情-->
    <div id="other_client_startpage">
        <!-- 页面内容区域 注意：每个页面无论是否有内容 必定有一个content-->
        <div class="content">
            <?php if(!empty($icon)){?>
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell align_middle">当前图片:</label>
                    <div class="tb_cont tb_cell">
                        <img id="startIcon" src="<?php echo $imageurl .'/startIcon/'. $icon['path']; ?>" style="max-width:400px; max-height:400px;">
                    </div>
                </div>
            </div>

            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">上传时间:</label>
                    <div class="tb_cont tb_cell">
                        <?php echo date('Y-m-d H:i:s', $icon['created_time']); ?>
                    </div>
                </div>
            </div>

            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell align_middle">操作:</label>
                    <span class="pop_btn none"  openPopId="show_pic_dialog" id="showDialogBtn"></span>
                    <div class="tb_cont tb_cell">
                        <ul class="radio_wrap" id="show_pic">
                            <li class="radio <?php if($icon['show'] == 1){?>on<?php } ?>" val="1">显示</li>
                            <li class="radio <?php if($icon['show'] == 0){?>on<?php } ?>" val="0" >不显示</li>
                        </ul>
                    </div>
                </div>
            </div>
            <?php } ?>
            <div class="bnts_wrap"><button id="editBtn" class="btn_s2" >上传图片</button></div>
            <input id="fileToUpload" style="display: none" type="file" name="upfile">
        </div><!-- content end -->

    </div>
</section>

<!-- 弹窗 图片 pop_style_img表示是图片 带该class的 点击页面其它区域会关闭该图片-->
<div class="pop_wraper" id="show_pic_dialog">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_tip">
                    <p class="tip_mes">是否隐藏/显示图片？</p>
                    <div class="tip_btns">
                        <button class="btn_s2" id="showPicBtn">确定</button>
                        <button class="btn_s2 btnCancel" id="cancelBtn" >取消</button>
                    </div>
                    <div class="pop_close"></div>
                </div><!-- pop_cont_tip 结束 -->
            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->

<script src="<?php echo $staticPath ?>jssdk/plugins/ajaxfileupload/jquery.ajaxfileupload.js" type="text/javascript"></script>
<script type="text/javascript">
    var token = "<?php echo $token; ?>";
    var upload_icon_url = "/Admin/Client/upload?token=" + token;;
    var show_icon_url = "/Admin/Client/startpage";
    $(function(){
        //点击打开文件选择器  
        $("#editBtn").on('click', function() {  
            $("#fileToUpload").replaceWith('<input id="fileToUpload" style="display: none" type="file" name="upfile">');
            $('#fileToUpload').click();  
        });  
          
        //选择文件之后执行上传
        $('body').delegate('#fileToUpload','change', function() {  
            var allowImgageType = ['jpg', 'jpeg', 'png', 'gif'];
            var file = $("#fileToUpload").val();
            //获取大小
            var byteSize = $("#fileToUpload")[0].files[0].size;
            byteSize = Math.ceil(byteSize / 1024) //KB
            //获取后缀
            if (file.length > 0) {
                if(byteSize > 10240) {
                    alert("上传的附件文件不能超过10M");
                    return;
                }
                var pos = file.lastIndexOf(".");
                //截取点之后的字符串
                var ext = file.substring(pos + 1).toLowerCase();
                //console.log(ext);
                if($.inArray(ext, allowImgageType) != -1) {
                    createUpload();
                }else {
                    alert("请选择jpg,jpeg,png,gif类型的图片");
                }
            }
            else {
                alert("请选择jpg,jpeg,png,gif类型的图片");
            }
        });  

        //显示隐藏开机图片
        $("#show_pic").click(function(){
            $("#showDialogBtn").click();
        });
        $("#showPicBtn").click(function(){
            var url = "/Admin/Client/update";
            var show = $("#show_pic").find('li').filter('.on').attr("val");
            var id = "<?php echo $icon['id'];?>";
            var data = {'id': id, 'show': show, 'token': token};
            $.post(url, data, function (d) {
                window.location.href = "/Admin/Client/startpage";
            });
        });
        $("#cancelBtn").click(function(){
            window.location.href = "/Admin/Client/startpage";
        });

        function createUpload(){
            $.ajaxFileUpload({
                url: upload_icon_url,  
                secureuri:false,  
                fileElementId:'fileToUpload',//file标签的id  
                dataType: 'json',//返回数据的类型  
                data: {'token': token},//一同上传的数据  
                success: function (data, status) {  
                   window.location.href=show_icon_url;
                }, 
                error: function (data, status, e) {  
                    alert(e);  
                }  
            });  
        }
        
    });
</script>
</body>
</html>