<?php echo $this->render("layout/header2.phtml");?>
<?php
$imgUrl = "{$staticPath}/../game/admin/assets/img";
echo <<<HTML
<link rel="stylesheet" href="{$staticPath}/../game/admin/assets/css/home-recommended.css" />
<script type="text/javascript" src="{$staticPath}/../game/admin/assets/js/template-native-debug.js"></script>
<script type="text/javascript" src="{$staticPath}/../game/admin/assets/js/homeRecommended.js"></script>
    

<script id="rollHtml" type="text/html">
			<% 
				var length = supplies.length;
				for(var i=0; i<length; i++) {%>
				   <div class="bg <%= i==0?"on ":"" %>"><img src=<%= supplies[i].href %>></div>

				<% } %>
				<% 
					for(var i =length;i<4;i++ ){%>
					<div class="bg <%= i==0?"on":"" %>">Banner：空</div>
				<%}
			%>
		</script>
		<script id="fileHtml" type="text/html">
			<% 
				var length = supplies.length;
				for(var i=0; i<length; i++) {%>
					<li value="<%= supplies[i].id %>">
						<span style="width: 90px; height: 20px; overflow: hidden;"><%= supplies[i].name?supplies[i].name:"&nbsp;" %></span>
						<div class="bg-file">
							<a href="{$bannerEditUrl}?id=<%= supplies[i].id %>"><img style="width:100%;height:100%" src="<%= supplies[i].href %>" /></a>
						</div>
						<div class="but-del-file">
							<img name="left" src="<%= imgUrl %>/u793.png"/>
							<input type="button" name="del" val="{$bannerDeleteUrl}?id=<%= supplies[i].id %>" value="删除"  >
							<img name="right" src="<%= imgUrl %>/u791.png"/>
						</div>
					</li>
				<% } %>
				<% 
				for(var i =length;i<4;i++ ){%>
					<li value="" class="<%= i==length?"":"no-file" %>">
						<span>&nbsp;</span>
						<% if(i==length){ %>
							<a href="{$bannerAddUrl}?day_id={$day_id}&sort=<%=(4-i)%>">
								<div class="bg-file">点击添加</div>
							</a>
						<%}else{%>
							<div class="bg-file">点击添加</div>
						<%}%>
					</li>
				<%}%>
		</script>
		<script id="listHtmlSet" type="text/html">
			<% 
				var length = supplies.length;
			%>
				<h2 class="mgn-t-10" >推荐列表<%= length?"":"：空" %></h2>
			<%
				for(var i=0; i<length; i++) {
			%>
					<div name="list" value="<%= supplies[i].id%>" class="mgn-t-10 list">
						<div class="sort">
							<img name="top" src="<%= imgUrl  %>/u969.png"/>
							<img name="bottom" src="<%= imgUrl  %>/u781.png"/>
						</div>
						<div class="info">
							<div class="inline-block">
								<h3><%= (i+1)+"."%><span style="color:#e59e53"><%= supplies[i].typeName%>&nbsp;</span> <%=supplies[i].name %></h3>
								<span class="qing-font12"><%= supplies[i].typeName?"类型："+supplies[i].typeName:"" %> </span>
								<% if(supplies[i].type=="activity" || supplies[i].type=="notice"){ %>
									<p class="qing-font12">数量：<%= supplies[i].num %> </p>
									<p class="qing-font12">ID：<%= supplies[i].linkId %> </p>
									<p ><%= supplies[i].names %></p>
								<% } else if(supplies[i].type=="rank"){ %>
								
								<% } else if(supplies[i].type=="active"){ %>
									<p >活动列表：<%= supplies[i].names %></p>
								<% } else if(supplies[i].type=="news"){ %>
									<p >资讯列表：<%= supplies[i].names %></p>
								<% }else  { %>
									<p >游戏列表：<%= supplies[i].names %></p>
								<%}%>
							</div>
							<div class="right">
							<% if(supplies[i].type=="rank"){ %>
								<a href="{$recommendEditRankUrl}?id=<%= supplies[i].id %>"><input type="button" class="gray-button" value="编辑" /></a>
								<input type="button" class="gray-button" val="{$recommendDeleteRankUrl}?id=<%= supplies[i].id %>" name="del" value="删除" />
							<% } else if(supplies[i].type=="active" || supplies[i].type=="news"){ %>
								<a href="{$recommendEditHdAndNew}?id=<%= supplies[i].id %>"><input type="button" class="gray-button" value="编辑" /></a>
								<input type="button" class="gray-button" val="{$recommendDeleteHdAndNewUrl}?id=<%= supplies[i].id %>" name="del" value="删除" />
							<% } else if(supplies[i].type=="gameList") {%>
								<a href="{$recommendEditUrl}?id=<%= supplies[i].id %>"><input type="button" class="gray-button" value="编辑" /></a>
								<input type="button" class="gray-button" val="{$recommendDeleteUrl}?id=<%= supplies[i].id %>" name="del" value="删除" />
 							<% } else { %>
								<a href="{$recommendEditUrl}?id=<%= supplies[i].id %>"><input type="button" class="gray-button" value="编辑" /></a>
								<input type="button" class="gray-button" val="{$recommendDeleteUrl}?id=<%= supplies[i].id %>" name="del" value="删除" />
							<% } %>

							</div>
						</div>
					</div>
				<%}%>
		</script>
		<script id="listHtml" type="text/html">
			<% 
				var length = supplies.length;
				if(!length){%>
					<div name="list" class="download-area mgn-t-b-10">
						<div class="header"><h2>推荐列表：空</h2></div>
					</div>
				<%}%>
				
				<%for(var i=0; i<length; i++) {%>
					<% if(!supplies[i].list){ %>
						<% if(supplies[i].type=="active"){%>
							<div name="list" class="download-area advert activity  mgn-t-b-10">
								<div class="header">
									<span></span>
									<h2><%= supplies[i].name %></h2>
									<hr class="gray-hr" />
								</div>
								<img src="<%= supplies[i].href %>" />
								<div class="info">
									<h2><%= supplies[i].activityName %></h2>
									<div class="date"><%= supplies[i].date %></div>
									<p><%= supplies[i].info %></p>
								</div>
								<hr class="gray-hr" />
								<div class="more" style="padding-top:10px; ">
									更多精彩活动
								</div>
							</div>
						<%  continue;} %>
						<div  name="list" class="advert  mgn-t-10" >
							<img src="<%= supplies[i].href %>" />
						</div>
						<% continue; %>
					<%}%>
					<% var jlength = supplies[i].list.length; %>
					<% var supp = supplies[i].list; %>
					
					<% if(supplies[i].type=="rank"){%>
						<div name="list" class="download-area ranking mgn-t-b-10">
							<div class="header">
								<span></span>
								<h2><%= supplies[i].name %></h2>
								<hr class="gray-hr" />
							</div>
							<ul>
								<%	for(var j=0; j<jlength; j++) {%>
									<li>
										<div>
											<img src="<%= supp[j].href %>" />
											<h3><%= supp[j].name %></h3>
											<div class="type"><%=supp[j].type?supp[j].type+"&nbsp;|&nbsp;":""%><%= supp[j].size%></div>
											<p><%= supp[j].info %></p>
											<input type="button" class="download" value="下载" />
										</div>
									</li>
								<% } %>
							</ul>
							<div class="more" style="padding-bottom:10px">
								更多排行榜
							</div>
						</div>
						<% continue; %>
					<%}%>
					<div name="list" class="download-area <%= jlength>4?"double-deck":"" %> <%= supplies[i].type=="news"?"notice":""%> mgn-t-b-10">
						<div class="header">
							<span></span>
							<h2><%= supplies[i].name %></h2>
							<hr class="gray-hr" />
						</div>
						<ul>

								<% if(supplies[i].type=="news"){%>
									<% for(var j=0; j<jlength; j++) {%>
										<li class="notice">
											<div>
												<img src="<%= supp[j].href %>" />
												<h3><%= supp[j].name %></h3>
												<p><%= supp[j].resume %></p>
											</div>
										</li>
										
									<% } %>
									</ul>
									<div class="more" style="padding-bottom:10px;">
										更多资讯公告
									</div>
									</div>
								<% continue; %>
								<% } %>
							<%	for(var j=0; j<jlength; j++) {%>
								<li>
									<img src="<%= supp[j].href %>" />
									<h3><%= supp[j].name %></h3>
									<p><span class="qing-font12"><%= supp[j].type %><%= supp[j].size?"|"+supp[j].size+"M":"&nbsp;" %></span></p>
									<input type="button" class="download" value="下载" />
								</li>
								
							<% } %>
						</ul>
						<hr class="gray-hr" />
						<div class="more" style="padding-top:10px;">
							查看更多
						</div>
					</div>
					
				<% } %>
		</script>
								    
<script type="text/javascript">

HTML;
    echo 'var pageData = ' . json_encode($data) . ';';
echo <<<HTML
	var imgUrl = '{$imgUrl}';
	var toUrl = baseurl+'{$listUrl}';
</script>
HTML;
?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $listUrl;?>">H5首页推荐日程</a></li>
	    <li class="current"><a href="javascript:;">编辑H5首页推荐</a></li>
	</ul>
</div>

<div class="h_a">编辑H5首页推荐信息</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="saveForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="day_id" value="<?php echo $day_id;?>" type="hidden" />

<?php $date = date("Y年m月d日", $day_id); ?>
<div class="home-deit">
	<header>
		<h1><?=$date?>首页推荐</h1>
		<div>
		<?php if(!$isFalse) {?>
			<input type="button" id="save" class="gray-button" value="保存当前配置" />
		<?php }?>	
			<a href="<?=$editlogUrl?>?day_id=<?=$day_id?>"><input type="button" class="gray-button" value="查看编辑记录" /></a>
		</div>
        <p class='gray-font12'>
<?php 
if($log) {
    $editTime = date("Y-m-d H:i:s", $log['create_time']);
    echo "最后一次编辑由<span>{$log['username']}</span>于<span>{$editTime}</span>";
}
echo <<<HTML
		</p>
	</header>
	<hr class="gray-hr" />
	<div class="content">
					<div id="preview" class="preview">
						<div name="rollContainer" class="roll">
							
						</div>
						<ul name="file" class="roll">
							<li data-value="0">1</li>
							<li data-value="1">2</li>
							<li data-value="2">3</li>
							<li data-value="3">4</li>
						</ul>
						<ul class="classification">
							<li>分类</li>
							<li>排行</li>
							<li>新游</li>
							<li>活动</li>
							<li>破解</li>
							<li>网游</li>
							<li>单机</li>
							<li>论坛</li>
						</ul>
						<div id="previewRecommend" class="mgn-t-30 ">
							
						</div>
					</div>
					<div class="deit">
						<h2>Banner</h2>
						<div class="fild">
							<ul name="file" id="file">
								
							</ul>
						</div>
						<hr class="gray-hr mgn-t-10" />
						<div id="recommend">
							
						</div>
						<div class="add-but">
							<div class="msg">
								<h1>推荐内容</h1>
								<p>不限制数量</p>
							</div>
							<div class="right-but">
								<a href="{$recommendAddUrl}?day_id={$day_id}"><input type="button" class="gray-button" value="添加游戏合辑或图片" /></a>
								<a href="{$recommendAddRankUrl}?day_id={$day_id}"><input type="button" class="gray-button" value="添加排行" /></a>
							</div>
						</div>
						<div class="add-but" id="active">
							<div class="msg">
								<h1>精彩活动</h1>
								<p>最多一条</p>
							</div>
							<div class="right-but">
								<a href="{$recommendAddHdUrl}&day_id={$day_id}"><input type="button" class="gray-button" value="活加活动" /></a>
							</div>
						</div>
						<div class="add-but" id="news">
							<div class="msg">
								<h1>资讯公告</h1>
								<p>最多五条</p>
							</div>
							<div class="right-but">
								<a href="{$recommendAddNewUrl}&day_id={$day_id}"><input type="button" class="gray-button" value="添加资讯" /></a>
							</div>
						</div>
					</div>
				</div>
</div>
HTML;
?>
</form>
<div id="alert">
			<p name="msg" style="text-align: center; padding-top:10px ">删除失败!</p>
</div>
<script type="text/javascript">
<?php if($isFalse) {?>
$('.add-but').hide();
<?php }?>
</script>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<?php echo $this->render("layout/footer.phtml");?>
