<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">push消息列表</a></li>
    <li class="current"><a href="javascript:;">编辑push消息</a></li>
	</ul>
</div>
<div class="h_a">编辑push消息</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="editFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="title" value="<?php echo $info['title'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">描述</th>
			<td class="td"><textarea class="input" name="content" class="textarea wc" style="height:60px;width:600px"><?php echo $info['content'];?></textarea></td>
		</tr>
		<tr class="tr">
			<th class="th">url</th>
			<td class="td"><textarea class="input" name="url" class="textarea wc" style="height:20px;width:400px"><?php echo $info['url'];?></textarea></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	ajaxForm('editFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Msg/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
