<?php echo $this->render("layout/newheader.phtml");?>
<body class="person" data-pagerole="body">
	<?php echo $this->render("layout/top.phtml");?>
	
	<div id="iScroll">
		<article class="ac">
			<?php echo $this->render("layout/face.phtml");?>

			<section class="tab-wrap">
				<?php echo $this->render("layout/nav.phtml");?>
				<div class="main rount-rect">
					<ul>
						<li><b>姓名：</b><?php echo $address['realname'];?></li>
						<li><b>电话：</b><?php echo $address['mobile'];?></li>
						<li><b>邮编：</b><?php echo $address['postcode'];?></li>
						<li><b>地址：</b><?php echo $address['adds'].$address['detail_address'];?></li>
					</ul>
					<div class="edit"><a href="<?php echo $address ? $webroot.$editUrl.'/?id='.$address['id'] : $webroot.$addUrl;?>" class="btn-edit"></a></div>
				</div>
			</section>
		</article>
	</div>
</body>
</html>