<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no"/>
	<title>专题-<?php echo $info['title']; ?></title>
	<link id="linkMain" rel="stylesheet" type="text/css" href="<?php echo $staticResPath;?>/assets/css/fanfan.source.css?v=<?php echo $assetVer;?>" />
	<style type="text/css">
	</style>

	<script src="<?php echo $staticSysPath;?>/lib/zepto/zepto.js"></script>
	<script src="<?php echo $staticSysPath;?>/icat/1.1.6/icat.js" data-main="<?php echo $staticResPath;?>/assets/js/fanfan.source.js"></script>
</head>

<body>
<?php echo $info['content']; ?>
</body>
</html>