<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li><a href="<?php echo $visitUrl; ?>">PV/UV统计</a></li>
			<li><a href="<?php echo $userLogUrl ?>">新增激活用户</a></li>
			<li><a href="<?php echo $newRegisterUrl; ?>">新增注册用户</a></li>
			<li><a href="<?php echo $connectedUrl; ?>">接通统计</a></li>
			<li class="current"><a href="<?php echo $periodUrl ?>">通话时段统计</a></li>
		</ul>
	</div>

	<form action="<?php echo $baseUrl; ?>" method="post" id="addFrom">
		<input name="token" value="<?php echo $token; ?>" type="hidden"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">选择日期</th>
					<td class="td" style="width: 240px">
						<input type="text" class="input " name="date" value="<?php echo date('Y-m-d H:i', strtotime($date)); ?>" id="date">
					</td>
					<td><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></td>
				</tr>
				<tr class="tr">
					<td class="td">有效通话数:</td>
					<td class="td"><span style="color:red; font-size:14px"><?php echo $data['amount']; ?></span></td>
				</tr>
			</table>
		</div>
	</form>
	<div class="table_list">
		<table width="100%">
			<tr class="tr">
				<td class="td">时间(小时)</td>
				<td class="td">通话次数</td>
				<td class="td">占比</td>
			</tr>
			<?php foreach ($data['data'] as $k => $v) { ?>
				<tr class="ct">
					<td class="td"><?php echo $k; ?></td>
					<td class="td"><?php echo $v; ?></td>
					<td class="td"><?php echo bcdiv($v, $data['amount'], 4) * 100; ?>%</td>
				</tr>
			<?php } ?>
		</table>
	</div>
	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>

	<script src="<?php echo $staticPath; ?>/js/common/jquery-ui-timepicker.js"></script>
	<script type="text/javascript">
		//广告表单数据提交
		$(document).ready(function () {
			$('#date').datetimepicker();

		})
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>