<!DOCTYPE html>
<html lang="en">
<head>
        <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="format-detection" content="email=no" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="format-detection" content="email=no" />
        <meta charset="UTF-8">
        <link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/apkv1/assets/css/holidayRule.source.css?v=<?php echo $version;?>">
        <title><?php echo $subTitle;?>-活动说明</title>
</head>
<body>
        <div class="holiday-rule">
                <div class="info">
        		<?php echo html_entity_decode($info);?>

                </div>
        </div>
</body>
</html>
