<?php echo $this->render('layout/header3.phtml'); ?>
	<!-- 顶部区域 -->
	<div data-options="region:'north',border:false" id="ui-head">
		<?php echo $this->render("layout/topbar.phtml"); ?>
	</div>
	<!-- 左边主菜单区域 -->
	<div data-options="region:'west',split:true,title:'主菜单'" id="ui-left">
		<div id="menu-accordion" data-options="fit:true,border:false" style="overflow:auto;"></div>
	</div>
	<!-- 版权信息 -->
	<div data-options="region:'south',border:false" id="ui-foot">Copyright &copy; <?php echo date('Y'); ?></div>
	<!-- 主内容区域 -->
	<div data-options="region:'center'" id="ui-center">
		<div id="admin-tabs" class="easyui-tabs" data-options="fit:true,border:false"></div>
	</div>
	<!-- 右键功能菜单 -->
	<div id="admin-tabs-menu" class="easyui-menu" style="display:none;">
		<div id="refreshCtab" data-options="iconCls:'icon-reload'">刷新</div>
		<div data-options="iconCls:'icon-cancel'" id="closecur">关闭</div>
		<div id="closeall">关闭全部</div>
		<div id="closeother">关闭其他</div>
		<div class="menu-sep"></div>
		<div id="closeright">关闭右侧标签页</div>
		<div id="closeleft">关闭左侧标签页</div>
	</div>
	<script type="text/javascript" src="<?php echo $staticPath; ?>/v2/js/index.js?v=<?php echo $version; ?>"></script>
	<script>var JSON_MENU = <?php echo $jsonmenu;?>;</script>
<?php echo $this->render('layout/footer3.phtml'); ?>