<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">商品列表</a></li>
		<li><a href="<?php echo $step1Url;?>">添加商品</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">专题分类</th>
			<td class="td">
			<select name="subject_id">
				<option value="0">所有分类</option>
<?php foreach($subjects as $key=>$value) {?>
				<option <?php if($search['subject_id'] == $value['id']) echo 'selected';?> value="<?php echo $value['id'];?>"><?php echo $value['title'];?></option>
<?php }?>
			</select>
		</tr>
		<tr class="tr">
			<th class="th">商品分类</th>
			<td class="td">
				<select name="category_id">
				<option value="0">所有商品分类</option>
<?php foreach($category as $key=>$value) {?>				
                	<option <?php if($search['category_id'] == $value['id']) echo 'selected';?> value="<?php echo $value['id'];?>"><?php echo $value['title'];?></option>
<?php }?>
           		</select>
           	</td>
		</tr>
		<tr class="tr">
			<th class="th">商品标签</th>
			<td class="td">
				<select name="label_id">
				<option value="0">所有标签</option>
<?php foreach($list as $key => $value) { ?>
     <?php if($value['id']) { ?>
				<optgroup label='----------<?php echo $value['name'];?>--------'></optgroup>
					<?php foreach($value['items'] as $k => $val) {?>		
							<option <?php if($search['label_id'] == $val['id']) echo 'selected';?> value="<?php echo $val['id'];?>">&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $val['name'];?></option>
					<?php }?>
<?php }}?>
           		</select>
           	</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">排序</td>
			<td>商品ID</td>
			<td>商品名称</td>
			<td>图片</td>
			<td>所属专题</td>
			<td>商品分类</td>
			<td>商品标签</td>
			<td>单价</td>
			<td>预计返利</td>
			<td>想要数</td>
			<td>状态</td>
			<td>操作</td>
		</tr>
<?php  foreach($goods as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><img src="<?php if(strpos($value['img'], 'http://') === false) {echo $attachPath,$value['img'];}else{echo $value['img'],'_120x120.',end(explode(".",  $value['img']));};?>"/></td>
			<td><?php echo $subjects[$value['subject_id']]['title'];?></td>
			<td><?php echo $categorys[$value['category_id']]['title'];?></td>
			<td><?php echo $labels[$value['label_id']]['name'];?></td>
	        <td><?php echo $value['price'];?></td>
	        <td><?php echo $value['commission'];?></td>
	        <td><?php echo $value['default_want'];?></td>
			<td><?php echo $value['status'] == 1 ? '在架上' : '已下架';?></td>
			<td>
				<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
