<?php echo $this->render("layout/header.phtml");?>
    <div class="nav">
        <ul class="cc">
            <li><a href="<?php echo $indexUrl;?>">问贴列表</a></li>
            <li class="current"><a href="javascript:;">添加问贴</a></li>
        </ul>
    </div>
    <div class="h_a">编辑问贴</div>
    <form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
        <input name="token" value="<?php echo $token;?>" type="hidden" />

        <div class="table_full">
            <table width="100%">
                <tr class="tr">
                    <th class="th">问题</th>
                    <td class="td">
                        <textarea name="title" id="title" cols="112" rows="3" placeholder="限制为8-50个字"></textarea>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">描述</th>
                    <td class="td">
                        <textarea name="content" id="content" cols="112" rows="5" placeholder="限制为10-500字"></textarea>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">图片</th>
                    <td class="td">
                        <div id="imgs">
                        </div>
                        <div class="mb10"><button onclick="addupload();" onfocus="blur();" type="button" class="btn">＋添加图片</button></div>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">用户</th>
                    <td class="td">
                        <select name="uid">
                            <?php foreach($authors as $a): ?>
                                <option value="<?php echo $a['uid'] ?>" <?php if($info['uid']==$a['uid']) echo 'select="selected"'; ?>><?php echo $a['nickname'] ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">推荐</th>
                    <td class="td">
                        <select name="recommend">
                            <option value="0" <?php if($info['recommend'] == 0) echo 'select="selected"'; ?>>否</option>
                            <option value="1" <?php if($info['recommend'] == 1) echo 'select="selected"'; ?>>是</option>
                        </select>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">隐藏</th>
                    <td class="td">
                        <select name="is_hidden">
                            <option value="0" <?php if($info['is_hidden'] == 0) echo 'select="selected"'; ?>>否</option>
                            <option value="1" <?php if($info['is_hidden'] == 1) echo 'select="selected"'; ?>>是</option>
                        </select>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">状态</th>
                    <td class="td">
                        <?php foreach($status as $sk=>$sv):?>
                            <input type="radio" name="status" value="<?php echo $sk ?>" <?php if($info['status']==$sk) echo 'checked="checked"'; ?> /><?php echo $sv ?>
                        <?php endforeach; ?>
                    </td>
                </tr>
            </table>
        </div>
        <div class="mb10 tac">
<!--            <span class="btn"><span><button onfocus="blur();" type="button" id="btn_preview">预览</button></span></span>-->
            <span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
        </div>
    </form>
    <script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
    <script src="<?php echo $staticPath;?>/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
    <script type="text/javascript">
        $(function(){
            $('#btn_preview').click(function(){
                var formdata = $('form#addForm').serializeArray();
                var data={};
                $(formdata).each(function(k,v){
                    data[v.name]= v.value
                });
                data.status=-5;
                data.content=editor.html();
                $.ajax({
                    url:'<?php echo $addPostUrl;?>',
                    type:'post',
                    data:data,
                    dataType:'json',
                    success:function(ret){
                        if(ret.success==true){
                            var tmp = '<input name="pre_id[]" value="'+ret.data+'" type="hidden" />'
                            $('form#addForm').prepend(tmp);
                            var url = '<?php echo $webroot.$previewUrl; ?>'+'?preview=1&id='+ret.data;
                            window.open(url,'_newtab');
                        }else{
                            $("#error_msg_box").dialog();
                        }
                    }
                });
            });
        });

        $('#start_time').datetimepicker();
        $(document).ready(function(e){
            ajaxForm('addForm',function(ret){
                var status = $('input[type="radio"]:checked').val();
                if(status!=0){
                    ajaxRedirect(ret, baseurl+'/Admin/Qa_Question/index?s=1');
                }else{
                    ajaxRedirect(ret, baseurl+'/Admin/Qa_Question/index?s=1');
                }
            });

            var imgc = 0;
            addupload  = function() {
                if($('.uploadImg').size() > 2){
                    alert('最多上传3张图片');
                    return false;
                }
                var al = $('<ul class="uploadImg"><li id="Img'+imgc+'"><img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/><input type="hidden" name="simg['+imgc+']" value=""></li></ul><p style="clear:both;"><iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=Img';?>'+imgc+'" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe></p>');
                $('#imgs').append(al);
                imgc++;
            }
        });
    </script>
<?php echo $this->render("layout/footer.phtml");?>