<?php echo $this->render("layout/header.phtml");?>
    <style>
        .uploadImg li img{
            height: 50px;
        }

    </style>
    <form method="post" action="<?php echo $editPostUrl;?>" id="editForm">
        <input name="token" value="<?php echo $token;?>" type="hidden" />
        <div class="h_a">主导航配置</div>
        <div class="table_full">
            <table width="100%">
                <tr class="tr">
                    <th class="th">图标一 (上: 正常 | 下: 按下)</th>
                    <td class="td">
                        <ul class="uploadImg">
                            <li id="nav_mainImg_1_1">
                                <img src="<?php echo empty($configs['nav_main_icon_1_1']) ? $staticPath . '/img/content/nopic.jpg' : $attachPath.$configs['nav_main_icon_1_1']; ?>"/>
                                <input type="hidden" name="nav_main_icon_1_1" value="<?php echo $configs['nav_main_icon_1_1'];?>">
                            </li>
                        </ul>
                        <p style="float:left;">
                            <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=nav_mainImg_1_1';?>" style="height:66px; width:700px;" frameborder="0" scrolling="no"></iframe>
                        </p>
                        <ul class="uploadImg">
                            <li id="nav_mainImg_1_2">
                                <img src="<?php echo empty($configs['nav_main_icon_1_2']) ? $staticPath . '/img/content/nopic.jpg' : $attachPath.$configs['nav_main_icon_1_2']; ?>"/>
                                <input type="hidden" name="nav_main_icon_1_2" value="<?php echo $configs['nav_main_icon_1_2'];?>">
                            </li>
                        </ul>
                        <p style="float:left;">
                            <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=nav_mainImg_1_2';?>" style="height:66px; width:700px;" frameborder="0" scrolling="no"></iframe>
                        </p>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">图标二 (同上)</th>
                    <td class="td">
                        <ul class="uploadImg">
                            <li id="nav_mainImg_2_1">
                                <img src="<?php echo empty($configs['nav_main_icon_2_1']) ? $staticPath . '/img/content/nopic.jpg' : $attachPath.$configs['nav_main_icon_2_1']; ?>"/>
                                <input type="hidden" name="nav_main_icon_2_1" value="<?php echo $configs['nav_main_icon_2_1'];?>">
                            </li>
                        </ul>
                        <p style="float:left;">
                            <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=nav_mainImg_2_1';?>" style="height:66px; width:700px;" frameborder="0" scrolling="no"></iframe>
                        </p>
                        <ul class="uploadImg">
                            <li id="nav_mainImg_2_2">
                                <img src="<?php echo empty($configs['nav_main_icon_2_2']) ? $staticPath . '/img/content/nopic.jpg' : $attachPath.$configs['nav_main_icon_2_2']; ?>"/>
                                <input type="hidden" name="nav_main_icon_2_2" value="<?php echo $configs['nav_main_icon_2_2'];?>">
                            </li>
                        </ul>
                        <p style="float:left;">
                            <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=nav_mainImg_2_2';?>" style="height:66px; width:700px;" frameborder="0" scrolling="no"></iframe>
                        </p>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">活动图标 (同上)</th>
                    <td class="td">
                        <ul class="uploadImg">
                            <li id="nav_mainImg_3_1">
                                <img src="<?php echo empty($configs['nav_main_icon_3_1']) ? $staticPath . '/img/content/nopic.jpg' : $attachPath.$configs['nav_main_icon_3_1']; ?>"/>
                                <input type="hidden" name="nav_main_icon_3_1" value="<?php echo $configs['nav_main_icon_3_1'];?>">
                            </li>
                        </ul>
                        <p style="float:left;">
                            <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=nav_mainImg_3_1';?>" style="height:66px; width:700px;" frameborder="0" scrolling="no"></iframe>
                        </p>
                        <ul class="uploadImg">
                            <li id="nav_mainImg_3_2">
                                <img src="<?php echo empty($configs['nav_main_icon_3_2']) ? $staticPath . '/img/content/nopic.jpg' : $attachPath.$configs['nav_main_icon_3_2']; ?>"/>
                                <input type="hidden" name="nav_main_icon_3_2" value="<?php echo $configs['nav_main_icon_3_2'];?>">
                            </li>
                        </ul>
                        <p style="float:left;">
                            <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=nav_mainImg_3_2';?>" style="height:66px; width:700px;" frameborder="0" scrolling="no"></iframe>
                        </p>
                        <p style="clear: both;">
                            链接: <input class="input wc"  name="nav_main_icon_3_link" value="<?php echo $configs['nav_main_icon_3_link'];?>"/>
                        </p>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">图标三 (同上)</th>
                    <td class="td">
                        <ul class="uploadImg">
                            <li id="nav_mainImg_4_1">
                                <img src="<?php echo empty($configs['nav_main_icon_4_1']) ? $staticPath . '/img/content/nopic.jpg' : $attachPath.$configs['nav_main_icon_4_1']; ?>"/>
                                <input type="hidden" name="nav_main_icon_4_1" value="<?php echo $configs['nav_main_icon_4_1'];?>">
                            </li>
                        </ul>
                        <p style="float:left;">
                            <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=nav_mainImg_4_1';?>" style="height:66px; width:700px;" frameborder="0" scrolling="no"></iframe>
                        </p>
                        <ul class="uploadImg">
                            <li id="nav_mainImg_4_2">
                                <img src="<?php echo empty($configs['nav_main_icon_4_2']) ? $staticPath . '/img/content/nopic.jpg' : $attachPath.$configs['nav_main_icon_4_2']; ?>"/>
                                <input type="hidden" name="nav_main_icon_4_2" value="<?php echo $configs['nav_main_icon_4_2'];?>">
                            </li>
                        </ul>
                        <p style="float:left;">
                            <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=nav_mainImg_4_2';?>" style="height:66px; width:700px;" frameborder="0" scrolling="no"></iframe>
                        </p>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">图标四 (同上)</th>
                    <td class="td">
                        <ul class="uploadImg">
                            <li id="nav_mainImg_5_1">
                                <img src="<?php echo empty($configs['nav_main_icon_5_1']) ? $staticPath . '/img/content/nopic.jpg' : $attachPath.$configs['nav_main_icon_5_1']; ?>"/>
                                <input type="hidden" name="nav_main_icon_5_1" value="<?php echo $configs['nav_main_icon_5_1'];?>">
                            </li>
                        </ul>
                        <p style="float:left;">
                            <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=nav_mainImg_5_1';?>" style="height:66px; width:700px;" frameborder="0" scrolling="no"></iframe>
                        </p>
                        <ul class="uploadImg">
                            <li id="nav_mainImg_5_2">
                                <img src="<?php echo empty($configs['nav_main_icon_5_2']) ? $staticPath . '/img/content/nopic.jpg' : $attachPath.$configs['nav_main_icon_5_2']; ?>"/>
                                <input type="hidden" name="nav_main_icon_5_2" value="<?php echo $configs['nav_main_icon_5_2'];?>">
                            </li>
                        </ul>
                        <p style="float:left;">
                            <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=nav_mainImg_5_2';?>" style="height:66px; width:700px;" frameborder="0" scrolling="no"></iframe>
                        </p>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">文本颜色 (例如: #FFFFFF)</th>
                    <td class="td">
                        正常: <input class="input"  name="nav_main_txt_color_1" value="<?php echo $configs['nav_main_txt_color_1'];?>"/>
                        按下: <input class="input"  name="nav_main_txt_color_2" value="<?php echo $configs['nav_main_txt_color_2'];?>"/>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">背景颜色 (例如: #FFFFFF)</th>
                    <td class="td" style="padding-left: 40px;">
                        <input class="input"  name="nav_main_tab_bg" value="<?php echo $configs['nav_main_tab_bg'];?>"/>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">开关</th>
                    <td class="td">
                        <label class="mr20"><input <?php if($configs['nav_main_switch']) echo 'checked';?> name="nav_main_switch" value="1" type="radio">开启</label>
                        <label class="mr20"><input <?php if(!$configs['nav_main_switch']) echo 'checked';?> name="nav_main_switch" value="0" type="radio">关闭</label>
                    </td>
                </tr>
            </table>
        </div>
        <div class="mb10 tac">
            <span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
        </div>
    </form>
    <script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            ajaxForm('editForm',function(ret){
                ajaxRedirect(ret, baseurl+'/Admin/Config_Navigation/index');
            });
        })
    </script>
<?php echo $this->render("layout/footer.phtml");?>