<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<title>意见反馈</title>
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="appRef" content="<?php echo $staticResPath;?>" />
	<link rel="stylesheet" href="<?php echo $staticSysPath;?>/reset/mpcore.css" />
	<link rel="stylesheet" href="<?php echo $staticResPath;?>/assets/css/3g.pcenter.css" /></head>		
</head>
<body>
<div id="page">
		<div class="pfeedback" id="iscrollWrap">
			<div class="mainWrap">
				<!-- 内容区域 START-->
				<header class="hd">
					<div class="slide banner">
						<img src="<?php echo $staticResPath;?>/pic/feedback_banner.jpg" alt="意见反馈" />
					</div>
				</header>
				<div class="module">
					<section class="ct-form-feedback">
						<h1>感谢您给我们提出宝贵意见，请关注浏览器微信“集砖箱”（微信号：集砖箱或jizhuanxiang)说明问题，我们将在第一时间反馈。</h1>
						<section>
							<form action="javascript:void(0)" data-ajaxUrl="<?php echo $webroot.$postUrl;?>" method="post" id="J_checkForm">
							<input name="token" value="<?php echo $token;?>" type="hidden" />
							<input name="ch" value="<?php echo $ch;?>" type="hidden" />
							<input name="status" value="1" type="hidden" />
							<input name="refurl"  value="<?php echo $refurl;?>"   type="hidden" />
								<div class="field">
									<label>反馈内容</label>
									<textarea cols="60" rows="10" placeholder="请输入您的反馈意见（字数500字以内）" name="react"></textarea>
								</div>
								<div class="field">
									<label>联系方式</label>
									<input type="text" autocomplete="off" placeholder="请留下您的email或手机号码，惊喜不定期送出" value="<?php echo $contact;?>" name="contact"/>
								</div>
								<div class="field button">
									<input type="submit" name="submit" value="提交" class="btn" />
								</div>
							</form>
						</section>
					</section>
				</div>

				<!-- 内容区域 END-->
			</div>
		</div>
	</div>
	<script type="text/javascript" src="<?php echo $staticSysPath;?>/icat/1.1.3/icat.js" corelib="//zepto.js"></script>
	<script type="text/javascript" src="<?php echo $staticResPath;?>/assets/js/3g.pcenter.js?v=<?php echo $version;?>"></script>
	<script type="text/javascript">var token = '<?php echo $token;?>';</script>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>