<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li class="current"><a href="<?php echo $listUrl; ?>">产品列表</a></li>
		<li><a href="<?php echo $addUrl; ?>">添加产品</a></li>
	</ul>
</div>
<form method="post" action="<?php echo $sortPostUrl; ?>" id="sortForm">
	<input name="token" type="hidden" value="<?php echo $token; ?>"/>

	<div class="table_list">
		<table width="100%">
			<tr class="hd">
				<td width="40">选择</td>
				<td width="100">排序</td>
				<td>名称</td>
				<td width="100">状态</td>
				<td width="100">操作</td>
			</tr>
			<?php foreach ($list as $key => $value) { ?>
				<tr class="ct">
					<td>
						<input type="checkbox" name="ids[<?php echo $value['id']; ?>]" value="<?php echo $value['id']; ?>">
					</td>
					<td>
						<input type="text" name="sort[<?php echo $value['id']; ?>]" class="input" value="<?php echo $value['sort']; ?>" style="width:60px;">
					</td>
					<td><?php echo $value['name']; ?></td>
					<td><?php echo $value['status'] == 1 ? '开启' : '关闭'; ?></td>
					<td>
						<a href="<?php echo $editUrl; ?>/?id=<?php echo $value['id']; ?>" class="mr10">编辑</a>
						<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
					</td>
				</tr>
			<?php } ?>
		</table>
	</div>
	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button type="submit">修改排序</button></span></span></div>
</form>
<script type="text/javascript">
	$(document).ready(function () {
		ajaxForm('sortForm', function (ret) {
			ajaxRedirect(ret, baseurl + '/Admin/Elifeserver/index');
		});
	})
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
