<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $indexUrl;?>?cate_id=<?php echo $cate_id;?>">API列表</a></li>
	    <li class="current"><a href="javascript:;">修改API</a></li>
	</ul>
</div>
<div class="h_a">添加渠道</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">名称</th>
				<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title'];?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">分类</th>
				<td class="td">
					<select name="cate_id">
					<?php foreach ($category as $key=>$val):?>
						<option value="<?php echo $val['id'];?>" <?php if ($val['id'] == $info['cate_id']) echo 'selected="selected"';?>><?php echo $val['title'];?></option>
					<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">标识串</th>
				<td class="td"><input type="text" class="input wc" name="sign" value="<?php echo $info['sign'];?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">描述</th>
				<td class="td"><textarea class="input wc" name="remark" rows="3"><?php echo $info['remark'];?></textarea></td>
			</tr>
			<tr class="tr">
				<th class="th">链接</th>
				<td class="td"><textarea class="input wc" name="api_url"><?php echo $info['api_url'];?></textarea></td>
			</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td">
					<select class="wa" name="status">
						<option value="1" <?php echo $info['status'] == 1 ? 'selected="selected"' : '';?>>开启</option>
						<option value="0" <?php echo $info['status'] == 0 ? 'selected="selected"' : '';?>>关闭</option>
					</select>
				</td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Partnerapi/index?cate_id=<?php echo $cate_id;?>');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
