<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class="current"><a href="<?php echo $listUrl; ?>">分类列表</a></li>
			<li><a href="<?php echo $addUrl; ?>">添加分类</a></li>
		</ul>
	</div>
	<form method="post" action="<?php echo $sortPostUrl; ?>" id="sortForm">
		<input name="token" type="hidden" value="<?php echo $token; ?>"/>

		<div class="table_list">
			<table width="100%">
				<tr class="hd">
					<td width="20">选择</td>
					<td width="40">排序</td>
					<td width="50">编号</td>
					<td width="100">名称</td>
					<td width="100">CP来源</td>
					<td width="100">位置</td>
					<td width="100">状态</td>
					<td width="200">操作</td>
				</tr>
				<?php foreach ($list as $key => $value) { ?>
					<tr class="ct <?php if ($value['status']) echo 'blue'; ?>">
						<td>
							<input type="checkbox" name="ids[<?php echo $value['id']; ?>]" value="<?php echo $value['id']; ?>">
						</td>
						<td>
							<input type="text" name="sort[<?php echo $value['id']; ?>]" class="input" value="<?php echo $value['sort']; ?>" style="width:30px;">
						</td>
						<td><?php echo $value['id']; ?></td>
						<td><?php echo $value['name']; ?></td>
						<td><?php echo $types[$value['source_id']]; ?></td>
						<td><?php echo $positions[$value['position']]; ?></td>
						<td><?php echo $value['status'] == 1 ? '开启' : '关闭'; ?></td>
						<td>
							<a href="<?php echo $editUrl; ?>/?id=<?php echo $value['id']; ?>" class="mr10">编辑</a>
							<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);" class="mr10">删除</a>
							<a href="<?php echo $addColumn; ?>/?parent_id=<?php echo $value['id']; ?>" class="mr10">添加栏目</a>
							<a href="<?php echo $listColumn; ?>/?parent_id=<?php echo $value['id']; ?>" class="mr10">查看栏目</a>
						</td>
					</tr>
				<?php } ?>
			</table>
		</div>
		<?php if ($list) { ?>
		<div class="mr10 cc">
			<?php echo $pager; ?>
		</div>
		<div class="mb10 tac">
			<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
	</form>
	<script type="text/javascript">
		$(document).ready(function () {
			ajaxForm('sortForm', function (ret) {
				ajaxRedirect(ret, baseurl + '/Admin/Jhtype/index');
			});
		})
		<?php }?>
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>