<?php echo $this->render("layout/header2.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li class="current"><a href="javascript:;">编辑首页图片</a></li>
	</ul>
</div>
<div class="h_a">添加推荐banner图</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">标题(<span style="color: red">*</span>)</th>
			<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title'];?>"></td>
		</tr>
		
		<tr class="tr">
			<th class="th">链接类型(<span style="color: red">*</span>)</th>
			<td class="td">
				<?php foreach($linkType as $key=>$value) {?>
                <label class="mr20"><input <?php if($info['link_type'] == $key) echo 'checked';?> name="link_type" value="<?php echo $key;?>" type="radio" onclick ="showContent(<?php echo $key;?>)"><?php echo $value;?></label>
			    <?php }?>
				<span style="color: red">(选择分类时，链接ID输入框填写游戏主分类的ID)</span>
			</td>
		</tr>
		<tr class="tr">
			<th class="th" id="th_link">链接参数</th>
			<td class="td"><input type="text" class="input" name="link" value="<?php echo $info['link'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">选择图片</th>
			<td class="td">
                <ul class="uploadImg">
					<li id="img">
						<img src="<?php echo $attachPath.$info['img'];?>"/>
						<input type="hidden" name="img" value="<?php echo $info['img'];?>">
					</li>
				</ul>			
                <p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=img';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p><span style="color:red"></span>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac">
    <span class="btn"><span><a href="javascript:window.history.go(-1);"><button type="button">返回</button></a></span></span>
    <span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
</div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
showContent = function(flag) {
	if (flag != 4) {
    	 $("#th_link").html('链接ID');
    	 $("#link").removeClass('wc');
	} else {
    	 $("#th_link").html('外链接');
    	 $("#link").addClass('wc');
	}
}
$(document).ready(function(){
    showContent(<?php echo $info['link_type'];?>);
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $listEditUrl.'?day_id='.date('Y-m-d', $info['day_id']);?>');
	});
});
</script>
<?php echo $this->render("layout/footer.phtml");?>
