<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class="current"><a href="<?php echo $indexUrl; ?>">商品列表</a></li>
			<li><a href="<?php echo $addUrl; ?>">添加商品</a></li>
			<li><a href="<?php echo $importUrl; ?>">批量导入/出虚拟物品</a></li>
		</ul>
	</div>
	<div class="table_list">
		<table style="width: 100%">
			<tr class="hd">
				<th class="th">ID</th>
				<th class="th">订单号</th>
				<th class="th">用户名</th>
				<th class="th">名称</th>
				<th class="th">单价</th>
				<th class="th">数量</th>
				<th class="th">类别</th>
				<th class="th">消费积分</th>
				<th class="th">交易时间</th>
				<th class="th">状态</th>
				<th class="th">操作</th>
			</tr>
			<?php foreach ($data as $v) { ?>
				<tr class="ct">
					<td class="td" align="left"><?=$v['id'];?></td>
					<td class="td" align="left"><?=$v['order_id'];?></td>
					<td class="td" align="center"><?=$v['username'];?></td>
					<td class="td" align="center"><?=$v['goods_name'];?></td>
					<td class="td"><?php echo $v['price']; ?></td>
					<td class="td"><?php echo $v['number']; ?></td>
					<td class="td"><?php echo $goodsType[$v['goods_type']]; ?></td>
					<td class="td"><?php echo $v['scores']; ?></td>
					<td class="td"><?php echo date('Y-m-d H:i:s', $v['add_time']) ?></td>
					<td class="td" style='color:blue'><?=$status[$v['status']];?></td>
					<td class="td"><a href="<?php echo $editUrl; ?>/?id=<?php echo $v['id']; ?>">编辑</a>&nbsp;
						<a href="javascript:void(0);" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $v['id']; ?>', '', event);">删除</a>
				</tr>
			<?php } ?>
		</table>
	</div>

	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>
<?php echo $this->render("layout/footer.phtml"); ?>