<!DOCTYPE HTML>
<?php if ($cache) {?>
<html manifest="/cache?cn=<?php echo $cn; ?>">
<?php } else { ?>
<html>
<?php } ?>


<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no"/>
	<title>新闻</title>
</head>

<body>
<!-- <iframe border="0" frameborder="no" style="position:absolute; z-index:10000; top:0; left:0;" width="100%" height="100%" src=""></iframe> -->
<script type="text/javascript">
	window.onload = function(){
		setTimeout(_loadifr, 500);

		function _loadifr(){
			var _ifr = document.createElement('iframe');
		   _ifr.name = "ifr_sohu";
		   _ifr.style.cssText = "border:0; width:100%; height:100%; position:absolute; top:0; bottom:0; left:0; right:0; z-index:1000;";
		   _ifr.src = "http://m.sohu.com/c/8315/?v=3&_trans_=000011_jl_qsy";
		   document.body.appendChild(_ifr);
		}
	}
</script>
</body>
</html>