<?php echo $this->render("layout/webheader.phtml");?>
<body data-pagerole="body">
	<div class="module">
	<?php if($hasheader){?>
		<header id="iHeader" class="hd">
			<div class="top-wrap">
				<div class="title">
					<a href="<?php echo $webroot;?>/amigo/service/index" class="back"></a>
					<h1>退/换货</h1>
					<span class="voice"></span>
				</div>
			</div>
		</header>
		<?php }?>

		<section id="iScroll">
			<div class="submit-success">
				<div class="success-text">
					<h3>提交申请成功，请您等待处理。</h3>
					<p>尊敬的用户，商城工作人员将会在1个工作日内联系您。感谢您的支持，我们将用心服务，期待您的十分满意。
					</p>
				</div>
				<div class="web-btn"><a href="<?php echo $webroot;?>/amigo/index/index">逛逛其他商品</a></div>
			</div>
		</section>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>