<?php echo $this->render("layout/header2.phtml");?>
<div data-role="page" data-theme="no" id="page" class="feed">
		<?php if ($hasheader) {?>
		<header class="hdWrap">
			<div class="hd-l"><a href="javascript:history.go(-1);" class="l-arrow">back</a></div>
			<div class="hd-r"><h1><?php echo $ad['title'];?></h1></div>	
		</header>
		<?php }?>
		<article class="ac">
			<section class="free-rule">
				<?php echo html_entity_decode($ad['descrip']);?>
			</section>
		</article>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>