<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">商品列表</a></li>
    <li class="current"><a href="<?php echo $step1Url;?>">添加商品</a></li>
	</ul>
</div>
<div class="step mb10">
		<ul class="cc">
			<li><span class="fl"><em></em></span>第一步：选择商品</li>
			<li class="line"></li>
			<li class="current">第二步：完善商品</li>
		</ul>
</div>
<div class="h_a">添加商品</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="price" value="<?php echo $info['price'];?>" type="hidden" />
<input name="num_iid" value="<?php echo $info['num_iid'];?>" type="hidden" />
<input name="commission" value="<?php echo $info['commission'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input wa" name="sort" value="0"></td>
		</tr>
		<tr class="tr">
			<th class="th">商品名称</th>
			<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">价格</th>
			<td class="td">
				售价：<?php echo $info['price'];?>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">所属专题</th>
			<td class="td">
			<select name="subject_id">
<?php foreach($subjects as $key=>$value) {?>				
                	<option value="<?php echo $value['id'];?>"><?php echo $value['title'];?></option>
<?php }?>
           		</select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">默认想要个数</th>
			<td class="td"><input type="text" class="input wa" name="default_want" value="<?php echo rand(5, 50);?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">商品图标</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="gimg">
						<img src="<?php echo $info['pic_url'],'_120x120.',end(explode(".",  $info['pic_url']));?>"/>
						<input type="hidden" name="img" value="<?php echo $info['pic_url'];?>">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=gimg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		
		<tr class="tr">
			<th class="th">开始结束时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="" /></div>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
				<select name="status">
                	<option value="1">&nbsp;&nbsp;上&nbsp;&nbsp;架&nbsp;&nbsp;</option>
                	<option value="0">&nbsp;&nbsp;下&nbsp;&nbsp;架&nbsp;&nbsp;</option>
           		</select>
           	</td>
		</tr>
		<tr class="tr" id="descrip">
				<th class="th">内容</th>
				<td class="td"><textarea
						style="width: 800px; height: 500px" class="textarea"
						name="descrip"></textarea>
				</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script src="<?php echo $staticPath;?>/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
<script type="text/javascript">
get_subject = function() {
	var subject_name = $("input[name=subject_name]").val();
	$.ajax({
		  url: baseurl + '/Admin/Subject/get/?id='+subject_name,
		  dataType : 'json',
		  success: function(data) {
		    if (data.success) {
		    	$("input[name=subject_id]").val(data.data.id);
		    	$("input[name=subject_name]").val(data.data.title);
		    } else {
			    showError('提示', '查询失败或者信息不存在.');
		    }
		  }
		});
}
var editor;
KindEditor.ready(function(K) {
	K.token = token;
    editor = K.create('textarea[name="descrip"]', {
        resizeType : 1,
        allowPreviewEmoticons : false,
        allowImageUpload : true,
        uploadJson : '<?php echo $adminroot.$uploadImgUrl;?>',
        items : EDITOR_ITEMS
    });
});
//商品表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Goods/index');
	});
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
