<?php echo $this->render("layout/header.phtml");?>
    <div class="nav">
        <ul class="cc">
            <li><a href="<?php echo $indexUrl;?>">问题列表</a></li>
            <li class="current"><a href="javascript:;">添加问题</a></li>
        </ul>
    </div>
    <div class="h_a">编辑问题</div>
    <form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
        <input name="token" value="<?php echo $token;?>" type="hidden" />

        <div class="table_full">
            <table width="100%">
                <tr class="tr">
                    <th class="th">排序</th>
                    <td class="td"><input type="text" placeholder="数值越大越靠前" class="input wa" name="sort" value="0"></td>
                </tr>
                <tr class="tr">
                    <th class="th">问题</th>
                    <td class="td"><input type="text" placeholder="标题不得超过20" class="input wc" name="question"	></td>
                </tr>
                <tr>
                    <th class="th">状态</th>
                    <td class="td">
                        <select name="status">
                            <option value=1 >有效</option>
                            <option value=0 >无效</option>
                        </select>
                    </td>
                </tr>
                <tr class="tr">
                    <th class="th">分类</th>
                    <td class="td">
                        <select name="cat_id">
                            <option value="0">请选择</option>
                            <?php foreach($cats as $c): ?>
                                <option value="<?php echo $c['id'] ?>" ><?php echo $c['name'] ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr class="tr" id="answer">
                    <th class="th">内容</th>
                    <td class="td" style="position:relative;">
                        <script id="editor" type="text/plain" style="width:100%;height:500px;"></script>
                    </td>
                </tr>
            </table>
        </div>
        <div class="mb10 tac">
            <span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
        </div>
    </form>
    <style>div#edui1 {z-index: 0 !important;}</style>
    <script type="text/javascript">
        var ue = UE.getEditor('editor', {'textarea': 'answer'});
        $(document).ready(function () {
            ajaxForm('addForm', function (ret) {
                ajaxRedirect(ret, '<?php echo Util_Http::getServer("HTTP_REFERER"); ?>');
            });
        })
    </script>
<?php echo $this->render("layout/footer.phtml");?>