<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $indexUrl;?>">问题列表</a></li>
		<li class="current"><a href="javascript:;">编辑问题</a></li>
	</ul>
</div>
<div class="h_a">编辑问题</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
	<div class="table_full">
		<table width="100%">

            <tr class="tr">
                <th class="th">排序</th>
                <td class="td"><input type="text" placeholder="数值越大越靠前" class="input wc" name="sort" value="<?php echo $info['sort'];?>"	></td>
            </tr>
            <tr class="tr">
                <th class="th">问题</th>
                <td class="td"><input type="text" class="input wc" name="question"	value="<?php echo $info['question'];?>"></td>
            </tr>
            <tr>
                <th class="th">状态</th>
                <td class="td">
                    <select name="status">
                        <option value=1 <?php echo $info['status']==1?'selected=selected':''; ?>>有效</option>
                        <option value=0 <?php echo $info['status']==0?'selected=selected':''; ?>>无效</option>
                    </select>
                </td>
            </tr>
            <tr class="tr">
                <th class="th">分类</th>
                <td class="td">
                    <select name="cat_id">
                        <option value="0">请选择</option>
                        <?php foreach($cats as $c): ?>
                            <option value="<?php echo $c['id'] ?>" <?php if($info['cat_id']==$c['id']) echo 'selected="selected"'; ?>><?php echo $c['name'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr class="tr" id="answer">
                <th class="th">内容</th>
                <td class="td">
                <script id="editor" type="text/plain" style="width:100%;height:500px;"><?php echo html_entity_decode($info['answer']);?></script>
                </td>
            </tr>
        </table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<style>div#edui1 {z-index: 0 !important;}</style>

<script type="text/javascript">
    var ue = UE.getEditor('editor', {'textarea':'answer'});
    $(document).ready(function(){
        ajaxForm('addForm',function(ret){
            ajaxRedirect(ret, '<?php echo Util_Http::getServer("HTTP_REFERER"); ?>');
        });
    })
</script>
<?php echo $this->render("layout/footer.phtml");?>