<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">阅读币列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加阅读币</a></li>
		<li  style="color:red; line-height:34px;">运营同学请注意：导入或删除阅读币后，请更新对应产品的库存数量！！！</li>
	</ul>
</div>

<form action="<?php echo $indexUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<td class="td">卡号</td>
			<td class="td">
				<input type="text" class="input wa" name="card_number" value="<?php echo $search['card_number'];?>">
			</td>
			<td class="td">订单号</td>
			<td class="td">
				<input type="text" class="input wa" name="order_id" value="<?php echo $search['order_id'];?>">
			</td>
			<td class="td">所属商品</td>
			<td class="td">
				<select name="goods_id" class="wa">
						<option <?php if ($search['goods_id'] == '') echo 'selected = selected';?>  value="">所有商品</option>
					<?php foreach ($goods as $key=>$value) {?>
						<option <?php if ($search['goods_id'] == $value['id']) echo 'selected = selected';?>  value="<?php echo $value['id'];?>"><?php echo $value['title'];?></option>
					<?php }?>
				</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">编号</td>
			<td width="300">所属商品</td>
			<td >卡号</td>
			<td width="300">订单号</td>
			<td width="100">操作</td>
		</tr>
<?php foreach($readcoins as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $goods[$value['goods_id']]['title'];?></td>
			<td><?php echo $value['card_number'];?></td>
			<td><?php echo $value['order_id'];?></td>
			<td>
				<?php if(!$value['order_id']) {?><a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a><?php }?>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>

<?php echo $this->render("layout/footer.phtml");?>
