<?php 
	echo $this->render("layout/header.phtml");
?>
<script>
var token = '<?php echo $token;?>';
</script>
<body>
<div id="rule-page" class="J_rule">
	<div class="rule-top"></div>
	<div class="rule-content">
		<div class="content">
		<!-- content中放后台上传的内容，此次只是示例 -->
		<?php echo html_entity_decode($activity['descrip']);?>
		</div>
	</div>
	<div class="rule-bottom J_bottom"></div>
</div>
</body>
</html>