<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li class="current"><a href="<?php echo $listUrl;?>">栏目列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加栏目</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
	    <tr>
		   <th class="th">状态</th>
			<td class="td">
			<select name="status" class="wa">
			    <option  value="0">全部</option>
				<option <?php if($search['status'] == 1) echo 'selected';?> value="1">开启</option>
				<option <?php if($search['status'] == 2) echo 'selected';?> value="2">关闭</option>
			</select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">关键字</th>
			<td class="td"><input type="text" class="input" name="name" value="<?php echo $search['name'];?>"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>"
	method="post">
	<input name="token" type="hidden" value="<?php echo $token;?>" /> <input
		name="action" id="action" type="hidden" value="" />
	<div class="h_a">
		<span class="btn2"><span><button onclick="$('#action').val('sort');"
					type="submit">重新排序</button></span></span> <span class="btn2"><span><button
					onclick="$('#action').val('open');" type="submit">开启</button></span></span>
		<span class="btn2"><span><button onclick="$('#action').val('close');"
					type="submit">关闭</button></span></span><span>&nbsp;&nbsp;&nbsp;&nbsp;共<?php echo $total;?>条结果</span>
	</div>
	<div class="table_list">
		<table width="100%">
			<tr class="hd">
				<td><input type="checkbox" onclick="checkAll('.checkbox')"></td>
				<td width="50">排序</td>
				<td width="100">栏目名称</td>
				<td width="150">子栏目名称</td>
				<td>添加日期</td>
				<td>最后编辑时间</td>
				<td>状态</td>
				<td>操作</td>
			</tr>
		<?php foreach ($info as $value) {?>
		<tr class="ct">
				<td><input class="checkbox" name="ids[]"
					value="<?php echo $value['id'];?>" type="checkbox"></td>
				<td><input type="text" class="input" style="width: 30px"
					name="sort[<?php echo $value['id'];?>]"
					value="<?php echo $value['sort'];?>"></td>
				<td><?php echo $value['name'];?></td>
				<td>
				<?php if(isset($value['items'])) {
						    foreach($value['items'] as $val) {
								echo $val['name'].'<br/>';
						 	} 
					 	}
				?>
				</td>
				<td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
				<td><?php echo date('Y-m-d H:i:s', $value['update_time']);?></td>
				<td><?php echo ($value['status'] == 1) ? '开启' : '关闭';?></td>
				<td><a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>"
					class="mr10">编辑</a> <a href="javascript:"
					onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
				</td>
			</tr>
		<?php }?>
	</table>
	</div>
	<div class="mr10 cc">
<?php echo $pager;?>
</div>
</form>
<script
	src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script>
$(document).ready(function(){
	ajaxForm('batchForm', function(data) {
		ajaxRedirect(data, baseurl+'/Admin/Client_Column/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>