<?php echo $this->render("layout/header2.phtml");?>
<?php
$imgUrl = "{$staticPath}/game/assets/img";
echo <<<HTML
<script type="text/javascript" src="{$staticPath}/game/assets/js/template-native-debug.js"></script>
<link rel="stylesheet" href="{$staticPath}/game/assets/css/online-rames.css?v=$version" />
<script type="text/javascript" src="{$staticPath}/game/assets/js/onlineRames.js?v=$version"></script>

<script id="rollHtml" type="text/html">
	<% 
		var length = supplies.length;
		for(var i=0; i<length; i++) {%>
		   <div class="bg <%= i==0?"on ":"" %>"><img src=<%= supplies[i].imgUrl %>></div>
		<% } %>
		<% 
			for(var i =length;i<4;i++ ){%>
			<div class="bg <%= i==0?"on":"" %>">Banner：空</div>
		<%}
	%>
</script>
<script id="fileHtml" type="text/html">
	<% 
		var length = supplies.length;
		for(var i=0; i<length; i++) {%>
			<li value="<%= supplies[i].id %>">			
				<span<% if(supplies[i].status==0){ %> style="color:red;"<%}%> ><%= supplies[i].name?supplies[i].name:"&nbsp;" %></span>
				<div class="bg-file">
					<a href="javascript:" name="add" link="<%= supplies[i].editHref %>">
				    	<img style="width:100%;height:100%" src="<%= supplies[i].imgUrl %>" />
					</a>
				</div>
				<div class="but-del-file">
					<img name="left" src="<%= imgUrl %>/u793.png"/>
					<input type="button" name="del"  ajaxUrl="<%= supplies[i].delHref %>" link="<%= supplies[i].link %>" value="删除"/>
					<img name="right" src="<%= imgUrl %>/u791.png"/>
				</div>
			</li>
		<% } %>
		<% 
		for(var i =length;i<4;i++ ){%>
			<li value="" class="<%= i==length?"":"no-file" %>">
				<span>&nbsp;</span>
				<% if(i==length){ %>
    				<a href="javascript:">
    					<div name="add" link="{$bannerAddUrl}?day_id={$day_id}" class="bg-file">点击添加</div>
    				</a>
				<%}else{%>
					<div class="bg-file">点击添加</div>
				<%}%>
			</li>
		<%}%>
</script>
<script id="listHtmlSet" type="text/html">
			<% 
				var length = supplies.length;
			%>
				<h2 class="mgn-t-10" >推荐列表<%= length?"":"：空" %></h2>
			<%
				for(var i=0; i<length; i++) {
			%>
					<div name="list" value="<%= supplies[i].id%>" class="mgn-t-10 list">
						<div class="sort">
							<img name="top" src="<%= imgUrl  %>/u969.png"/>
							<img name="bottom" src="<%= imgUrl  %>/u781.png"/>
						</div>
						<div class="info">
							<div class="inline-block">
								<h3><%= (i+1)+"."%>
								    <span style="color:#e59e53">
								        <%= supplies[i].recType %>&nbsp;
								    </span>
								    <span  style="color:<%= !supplies[i].recType ?"#e59e53":"#000" %>">
								        <% if(supplies[i].status==0){%>
								            <span style="color:red">
								                <%=supplies[i].name %> 
								           </span>
								        <%}else{%>
								            <%=supplies[i].name %>
								        <%}%>
								    </span>
								</h3>
							
							    <span class="qing-font12">
							     <%= supplies[i].template?"显示："+supplies[i].template:"" %> 
							     <%= supplies[i].typeName?"类型："+supplies[i].typeName:"" %> 
							     <%= supplies[i].linkId?"(ID："+supplies[i].linkId+")":"" %>
							    </span>
								<%if(supplies[i].type=="openList"){%>
									<p class="qing-font12">数量：<%= supplies[i].num %> </p>
								<%}%>
								<p ><%= supplies[i].names %></p>
								<p >广告ID：<%= supplies[i].adId %></p>
								<%if(supplies[i].type=="package"){%>
								<p style="color:red;">热门礼包有更新需要手动"保存当前配置"同步到客户端,否则整点同步更新</p>
								<%}%>
							</div>
							<div class="right">
						        <% if(supplies[i].editHref){ %>
				                <input type="button" name="edit" link="<%= supplies[i].editHref %>" class="gray-button" value="编辑" />
					            <%}%>
						        <% if(supplies[i].delHref){ %>
								<input type="button" class="gray-button" ajaxUrl="<%= supplies[i].delHref %>" link="<%=supplies[i].link%>" name="del" value="删除" />
					            <%}%>
							</div>
						</div>
					</div>
				<%}%>
		</script>
<script id="listHtml" type="text/html">
	<% 
		var length = supplies.length;
		if(!length){%>
			<div name="list" class="download-area mgn-t-b-10">
				<div class="header"><h2>推荐列表：空</h2></div>
			</div>
		<%}%>
		
		<%for(var i=0; i<length; i++) {%>
			<% if(supplies[i].type=="image"){%>
				<div  name="list" class="advert  mgn-t-10" >
					<img src="<%= supplies[i].imgUrl %>" />
				</div>
				<% continue; %>
			<%}%>
			<% var jlength = supplies[i].list.length; %>
			<% var supp = supplies[i].list; %>
			<% if(supplies[i].type=="openList"){%>
				<div name="list" class="download-area not-table mgn-t-b-10">
					<div class="header">
						<h2><%= supplies[i].name %><span class="sees">查看全部&gt;</span></h2>
						<hr class="gray-hr" />
					</div>
					<table>
						<tr>
							<th>游戏</th>
							<th>状态</th>
							<th>时间</th>
							<th>礼包</th>
							<th></th>
						</tr>
						<%	for(var j=0; j<jlength; j++) {%>
							<tr>
								<td><%= supp[j].name %></td>
								<td><%= supp[j].type %></td>
								<td><%= supp[j].date %></td>
								<td><%= supp[j].package %></td>
								<td><input type="button" class="download" value="下载" /></td>
							</tr>
						<% } %>
					</table>
				</div>
				<% continue; %>
			<%}%>
			<% if(supplies[i].type=="gameList2"){%>
				<div name="list" class="download-area ranking mgn-t-b-10">
					<div class="header">
						<h2><%= supplies[i].name %><span class="sees">查看全部&gt;</span></h2>
						<hr class="gray-hr" />
					</div>
					<ul>
						<%	for(var j=0; j<jlength; j++) {%>
							<li>
								<div>
									<img src="<%= supp[j].imgUrl %>" />
									<h3><%= supp[j].name %></h3>
    					            <i class="stars stars_<%= supp[j].web_star %>"></i>
    					            <div class="size"> <%= supp[j].size?"|&nbsp;"+supp[j].size+"M":"&nbsp;" %></div>
									<p><%= supp[j].info %></p>
									<input type="button" class="download" value="下载" />
								</div>
							</li>
						<% } %>
					</ul>
				</div>
				<% continue; %>
			<%}%>
			<% if(supplies[i].type=="package"){%>
                <div name="list" class="download-area line <%= jlength>4?"double-deck":"" %> mgn-t-b-10 js-<%= supplies[i].type %>" style="height:267px">
                    <div class="header">
                    <h2>&nbsp;&nbsp;<%= supplies[i].name %><span class="sees">查看全部&gt;</span></h2>
                    </div>
                    <ul>
                        <%	for(var j=0; j<6; j++) {%>
    					    <% supp[j] = supp[j] || {} %>
                            <li style="height: 83px;">
                            <img src="<%= supp[j].imgUrl %>" />
                            <h3><%= supp[j].name %></h3>
                            <p><%= supp[j].info %></p>
                            </li>
                     <% } %>
                    </ul>
                </div>
            <% continue; %>
            <%}%>
			<div name="list" class="download-area <%= jlength>4?"double-deck":"" %> <%= supplies[i].type=="image"?"notice":""%> mgn-t-b-10">
				<div class="header">
					<h2><%= supplies[i].name %><span class="sees">查看全部&gt;</span></h2>
					<hr class="gray-hr" />
				</div>
				<ul>
						<% if(supplies[i].type=="image"){%>
							<% for(var j=0; j<jlength; j++) {%>
								<li class="notice">
									<div>
										<img src="<%= supp[j].imgUrl %>" />
										<h3><%= supp[j].name %></h3>
										<p><%= supp[j].info %></p>
									</div>
								</li>
								
							<% } %>
							</ul>
							</div>
						<% continue; %>
						<% } %>
					<%	for(var j=0; j<jlength; j++) {%>
						<li>
							<img src="<%= supp[j].imgUrl %>" />
							<h3><%= supp[j].name||"&nbsp;" %></h3>
							<p><span class="qing-font12"><%= supp[j].type %><%= supp[j].size?"|"+supp[j].size+"M":"&nbsp;" %></span></p>
							<input type="button" class="download" value="下载" />
						</li>
					<% } %>
				</ul>
			</div>
		<% } %>
</script>
<script type="text/javascript">
HTML;
    echo 'var pageData = ' . json_encode($data) . ';';
echo <<<HTML
	var imgUrl = '{$imgUrl}';
	var toUrl = baseurl+'{$listUrl}';
</script>
HTML;
?>

<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $listUrl;?>">网游推荐日程</a></li>
	    <li class="current"><a href="javascript:;">编辑网游推荐</a></li>
	</ul>
</div>
<div class="h_a">编辑网游推荐信息</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="saveForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="day_id" value="<?php echo $day_id;?>" type="hidden" />
<?php 
$date = date("Y年m月d日", $day_id);
echo <<<HTML
<div class="home-deit">
	<header>
		<h1>{$date}网游推荐</h1>
		<div>
			<input type="button" id="save" class="gray-button" value="保存当前配置" />
			<a href="{$editlogUrl}?day_id={$day_id}"><input type="button" class="gray-button" value="查看编辑记录" /></a>
    		<span style="margin-left:30px;color:red;font-size:18px">“保存当前配置”才会生效,否则退出“编辑网游推荐信息”后数据丢失。同一天的推荐信息同时只能由一个用户编辑!</span>
		</div>
        <p class='gray-font12'>
HTML;
if($log) {
    $editTime = date("Y-m-d H:i:s", $log['create_time']);
    echo "最后一次编辑由<span>{$log['username']}</span>于<span>{$editTime}</span>";
}
echo <<<HTML
		</p>
	</header>
	<hr class="gray-hr" />
	<div class="content">
		<div id="preview" class="preview">
			<div name="rollContainer" class="roll">
			</div>
			<ul name="file" class="roll">
				<li data-value="0">1</li>
				<li data-value="1">2</li>
				<li data-value="2">3</li>
				<li data-value="3">4</li>
			</ul>
			<ul class="classification">
				<li class="left">开服信息</li>
				<li>网游分类</li>
				<li class="right">游戏礼包</li>
			</ul>
			<div id="previewRecommend" class="mgn-t-30 ">
			</div>
		</div>
		<div class="deit">
			<h2>Banner</h2>
			<div class="fild">
				<ul name="file" id="file">
				</ul>
			</div>
			<hr class="gray-hr mgn-t-10" />
			<div id="recommend">
			</div>
			<div class="add-but" id="package">
				<div class="msg">
					<h1>热门礼包</h1>
					<p>开启后调用热门礼包数据</p>
				</div>
				<div class="right-but">
					<input type="button" ajaxUrl="{$hotGiftOpenUrl}?day_id={$day_id}" link="{$editUrl}?dayId={$day_id}" name="open" class="gray-button" value="开启" />
				</div>
			</div>
			<div class="add-but" id="openList">
				<div class="msg">
					<h1>开服信息</h1>
					<p>不会自动复制</p>
				</div>
				<div class="right-but">
				    <input type="button" name="add" link="{$listOpenSelectUrl}?day_id={$day_id}" class="gray-button" value="添加" />
				</div>
			</div>
			<div class="add-but">
				<div class="msg">
					<h1>推荐内容</h1>
					<p>不限制数量</p>
				</div>
				<div class="right-but">
				    <input type="button" name="edit" link="{$listGameAddUrl}?day_id={$day_id}" class="gray-button" value="添加合辑" />
				    <input type="button" name="edit" link="{$listImgAddUrl}?day_id={$day_id}" class="gray-button" value="添加图片" />
				</div>
			</div>
		</div>
	</div>
</div>
HTML;
?>
</form>
<div id="alert">
	<p name="msg" style="text-align: center; padding-top:10px ">删除失败!</p>
</div>
<script type="text/javascript">
var confirmInfo="<?php echo $from == 1 ? "“保存当前配置”才会生效,否则您刚编辑的数据会丢失。" : ""; ?>";
$(window).bind('beforeunload', function(){
    if(!confirmInfo) {
        return;
    }
	return confirmInfo;
});
</script>
<?php echo $this->render("layout/footer.phtml");?>