<?php echo $this->render("layout/header.phtml");?>
	<div id="page">
		<article class="ac">
			<div class="detail-field">
				<dl>
					<dt><img src="<?php echo $attachPath. $info['img'];?>" alt=""></dt>
					<dd>
						<p><span>分类：<?php echo $categorys[$info['category_id']]['title'];?></span><span>资费：<?php echo $prices[$info['price']]['name']?></span></p>
						<p><span>语言：<?php echo $info['language'];?></span><span>版本：<?php echo $info['version'];?></span></p>
						<p><span style="width:8.5rem;">更新：<?php echo date('Y-m-d',$info['create_time']);?></span></p>
						<p><?php echo $info['company'];?></p>
					</dd>
				</dl>
				<div class="download"><a href="<?php echo Common::tjurl($tjUrl, $info['id'], 'GAME', $info['link']);?>" class="btn">安装(<?php echo $info['size'];?>M)</a></div>
			</div>
			<div class="detail-scrollPic" id="J_screenshot">
				<div class="pic-wrap">
					<?php foreach($gimgs as $key=>$value){?>
					<span><img src="<?php echo $attachPath. $value['img'];?>" alt=""></span>
					<?php }?>
				</div>
			</div>
			<div class="detail-text">
			<?php if(Util_String::strlen($info['descrip']) > 100){ ?>
			<p><?php echo Util_String::substr($info['descrip'], 0, 100);?>...</p>
			<p class="hidden"><?php echo $info['descrip'];?></p>
			<div class="open J_openBtnWrap"><span>展开</span></div>
			<?php } else {?>
			<p><?php echo $info['descrip'];?></p>
			<?php }?>
			</div>
		</article>

		<footer class="ft">
			<div class="back-top"><a class="btn" href="#top">返回顶部</a></div>
			<div class="quick-links">
				<a href="<?php echo $webroot.'/contact?t_bi='.$source;?>">联系我们</a>
				<a href="<?php echo $webroot.'/feedback?t_bi='.$source;?>">意见反馈</a>
				<a href="<?php echo strpos($configs['game_link'], '?') == false ? $configs['game_link'].'&t_bi='.$source :$configs['game_link'].'?t_bi='.$source;?>"><?php echo $configs['game_title'];?></a>
			</div>
		</footer>
	</div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>