<!DOCTYPE HTML>
<html>

<head>
    <meta charset="UTF-8">
    <title><?php echo $title;?></title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
	<div id="wx_pic" style="margin:0 auto;display:none;"><img src="<?php echo $staticRoot;?>/apps/olajob/asset/img/pic300.jpg"/></div>

    <link type="text/css" rel="stylesheet" href="<?php echo $staticRoot;?>/sys/reset/phonecore.css?t=<?php echo $version;?>">
    <link type="text/css" rel="stylesheet" href="<?php echo $staticRoot;?>/apps/olajob/asset/build/css/style.css?t=<?php echo $version;?>"></head>
    <script>
    var _hmt = _hmt || [];
    (function() {
      var hm = document.createElement("script");
      hm.src = "//hm.baidu.com/hm.js?d31158b6ee763a280766710139eb3270";
      var s = document.getElementsByTagName("script")[0]; 
      s.parentNode.insertBefore(hm, s);
    })();
    </script>