
<!DOCTYPE HTML>
<html>
<head>
    <title>答题赚金币</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
    <meta name="apple-touch-fullscreen" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="format-detection" content="telephone=no" />
     <link rel="stylesheet" href="<?php echo $staticResPath;?>/events/css/answer.min.css?ver=<?php echo $version;?>" />
</head>
<body>
<div class="app">
    <div class="ans-top-bar">
        <a class="icon-back" href="<?php echo $webroot;?>/user/index/index"></a>
        <span class="ans-top-txt">答题赚金币</span>
    </div>
    <div class="banner">
        <img src="<?php echo $staticResPath;?>/events/pic/ans_banner.jpg" />
        <p><span>当前金币 <?php echo $scoreInfo['remained_score']?$scoreInfo['remained_score']:0;?></span><span class="icon-gold"></span></p>
    </div>
    <div class="main">
             <div class="content-wrap">
             <?php if($rewardFlag == 1){?>
               <div class="ans-list">
                	<div class="ans-done">
	                    <div class="blank">
	                        <p>今天任务已完成，明天继续哦！</p>
	                    </div>
                	</div>
                </div>
               <?php }else if(empty($wrongData) && empty($rewardFlag) && $isExists >0) {?>
            			<div class="ans-list">
                			<div class="ans-success">
                  					 <div class="blank">
                     					 <span class="icon-gold-larage"></span>
                        						<p>恭喜您，全部答对，额外送您<?php echo $config['quiz_all_right_reward_scores'];?>金币</p>
                    				</div>
                    				<div class="button"><a href="<?php echo $webroot?>/user/activity/ajaxGiveRewardScores" >点击领取金币</a></div>
                			</div>
                		</div>
                <?php }else{ ?>
                  <div class="ans-his-done">今天任务已完成，明天继续哦！</div>
            	<div class="ans-his-caption">以下是您今日答错的题目：</div>
             	<?php   foreach($wrongData as $key=>$val){?>
            		<div class="ans-list">
                		<div class="ans-item">
                    		<div class="blank">
	                        <h3><?php echo $val['title'];?></h3>
	                        	<?php foreach($val['options'] as $m=>$n){?>
	                       		 	<p <?php if($val['selected'] == $m) echo 'class="ans-err"';?>><?php echo "{$quizSerial[$m]}、{$n}" ;?></p>
	                       		<?php }?>
	                    </div>
	                    <div class="button"><a href="/user/activity/quizTo?type=find&title=<?=$val['title']?>" target="_blank">找答案</a></div>
	                	</div>
	                  </div>
                <?php } }?>
        </div>
    <?php echo $config['quiz_rule_content'];?>
    </div>
</div>
<script>  var token = "<?php echo $token;?>";</script>
<script src="<?php echo $staticResPath;?>/events/js/zepto.min.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticSysPath;?>/smart/0.0.2/smart.min.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticResPath;?>/events/js/answer.min.js?v=<?php echo $version;?>"></script>
</body>
</html>