<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li class="current"><a href="<?php echo $listUrl;?>">vip图标列表</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">	
		<tr class="tr">
			<th class="th">vip等级</th>
			<td class="td">
			<select name="vip" class="input">
				<?php foreach($vipList as $value) {?>
			    <option value="<?php echo $value;?>" <?php if($search['vip'] == $value) echo 'selected';?>>Vip<?php echo $value;?></option>
			    <?php }?>
		    </select></td>
			<th class="th">icon</th>
			<td class="td"><input type="text" class="input" name="img" value="<?php echo $search['img'];?>"></td>
			<th class="th"></th>
			<td class="td"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="action" id="action" type="hidden" value="" />
<div class="h_a">
    <span class="btn2"><span><button onclick="$('#action').val('delete');" type="submit">批量删除</button></span></span>
	<span class="btn2"><span><a href="<?php echo $addUrl;?>" style="text-decoration:none;color:#ffffff;">添加vip图标</a></span></span>
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td width="30"><input type="checkbox" onclick="checkAll('.checkbox')"></td>
			<td width="50">vip等级</td>
			<td width="50">icon</td>
			<td width="100">操作</td>
		</tr>
		<?php foreach($list as $key => $value) {?>
		<tr class="ct">
			<td><input class="checkbox" name="keys[]" value="<?php echo $value['vip'];?>" type="checkbox"></td>
			<td><?php echo $value['vip'];?></td>
			<td><img src="<?php echo $attachPath.$value['img']?>" style="width:20px;height:20px;"/></td>
			<td>
				<a href="<?php echo $editUrl . "?" . "vip=" . $value['vip'];?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl . "?" . "vip=" . $value['vip'];?>', '', event);">删除</a>
			</td>
		</tr>
	 <?php } ?>
	</table>
</div>
</form>
<div class="mr10 cc"><?php echo $pager;?></div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $listUrl;?>');
	});
});
</script>
<?php echo $this->render("layout/footer.phtml");?>
