<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $listUrl;?>">客户端按钮导航</a></li>
	    <li class="current"><a href="javascript:;">编辑按钮导航</a></li>
	</ul>
</div>
<div class="h_a">编辑客户端按钮导航</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
	   <tr class="tr">
			<th class="th">模块(<span style="color: red">*</span>)</th>
			<td class="td"><select name="module" class="wa">
					<?php foreach($module as $key=>$value) {?>
    			    <option <?php if($info['module'] == $key) echo "selected='true'";?> value="<?php echo $key;?>"><?php echo $value;?></option>
    			    <?php }?>
            </select></td>
		</tr>
		<tr class="tr">
			<th class="th">标题(<span style="color: red">*</span>)</th>
			<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">显示窗口(<span style="color: red">*</span>)</th>
			<td class="td"><input type="text" class="input wc" name="view_type" value="<?php echo $info['view_type'];?>"><span style="color: red">该参数必须由客户端开发同事提供</span></td>
		</tr>
		<tr class="tr">
			<th class="th">图标(<span style="color: red">*</span>)</th>
			<td class="td"><ul class="uploadImg">
					<li id="sicon">
						<img src="<?php echo $attachPath.$info['icon_url'];?>"/>
						<input type="hidden" name="icon_url" value="<?php echo $info['icon_url'];?>">
					</li>
				</ul>
                <p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=sicon';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">客户端参数(<span style="color: red">*</span>)</th>
			<td class="td"><textarea style="width: 450px; height: 100px" class="textarea" name="param"><?php echo $info['param'];?></textarea><span style="color: red">该参数必须由客户端开发同事提供</span></td>
		</tr>
		<tr class="tr">
			<th class="th">排序(<span style="color: red">*</span>)</th>
			<td class="td"><input type="text" class="input" name="sort" value="<?php echo $info['sort'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">状态(<span style="color: red">*</span>)</th>
			<td class="td">
				<select name="status" class="wa">
					<option <?php if(strlen($info['status'])>0 && $info['status'] == 1) echo 'selected';?> value="1">开启</option>
					<option <?php if(strlen($info['status'])>0 && $info['status'] == 0) echo 'selected';?> value="0">关闭</option>
				</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
    	var module = $("select[name='module']").val();
		ajaxRedirect(ret, baseurl+'<?php echo $listUrl;?>'+'?module='+module);
	});
});
</script>
<?php echo $this->render("layout/footer.phtml");?>
