<?php echo $this->render("layout/webheader.phtml");?>
<body>
	<div class="module">
		<header id="iHeader" class="hd">
			<div class="top-wrap">
				<div class="title">
					<a href="<?php echo $refer ? $refer : $webroot;?>" class="back"></a>
					<h1>搜索</h1>
				</div>
			</div>
		</header>
		<div id="iScroll" class="search-wrap">
			<div class="panel">
				<div class="search-bar">
					<form action="<?php echo $action;?>" method="post">
						<input type="text" autocomplete="off" name="keyword" value="<?php echo $keyword;?>" placeholder="<?php echo $keyword;?>"><button></button>
					</form>
				</div>
				<div class="result-list">
					<ul>
						<?php foreach($list as $key=>$value){?>
						<li><a href="<?php echo $action.'&keyword='.$value['keyword'];?>"><span<?php if(($key+1)<4){echo " class=\"num-top\"";}?>><?php echo $key+1;?></span><?php echo Util_String::substr($value['keyword'], 0, 14, '',true)?></a></li>
						<?php }?>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<?php echo $this->render("layout/tj.phtml");?> 
</body>
</html>