<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">规则列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加规则</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="60">编号</td>
			<td>价格(元)</td>
			<td>概率(%)</td>
			<td>次数(次)</td>
			<td>范围(天)</td>
			<td>操作</td>
		</tr>
<?php foreach($rules as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['price'];?></td>
			<td><?php echo $value['rate'];?>%</td>
			<td><?php echo $value['times'];?></td>
			<td><?php echo $value['scope'];?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
