<?php echo $this->render("common/navigator.phtml"); ?>
<style type="text/css">
    .rews{
        background-color: #cf0;
    }
</style>
<!-- 导航栏Ajax加载 指向navagator.html  menuOn表示分别需要高亮的菜单栏id 用下划线_隔开 eg:bz_taotu_taotuPack-->
<section class="navigator" menuOn="sz_szsubject_szsubjectList">

</section>

<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <!-- 页面唯一id标识符  一般情况下id=文件名  eg:bz_admin_taotu02-->
    <div id="bz_operation_seminar_list01">
        <div class="com_tb_wrap">
            <div class="com_tb">
                <label class="tb_cell">状态</label>
                <div class="tb_cont tb_cell">
                    <div class="select_tag">
                        <ul class="tag_list sellect_status">
                            <?php foreach ($status as $k => $v) { ?>
                                <li val="<?php echo $k; ?>" <?php if($status_sel == $k){ echo 'class="on"'; }?>><?php echo $v ?></li>
                            <?php } ?>
                        </ul>
                    </div><!-- select_box -->
                </div>
            </div><!-- com_tb end -->
        </div><!-- com_tb_wrap end -->

        <!-- 列表模式 -->
        <section class="view view_list show" id="viewList">
            <!-- 批量管理内容 默认隐藏 -->
            <div class="view_admin view_list_admin">
                <!-- checkClass表示 点击后 哪些class要被选中 -->
                <!--  <button class="btn_check btn_check_all" checkClass="btn_check_list"></button>
                  <label>全选</label>
                  <span class="btn btn_s1 pack_del">批量删除</span>-->
            </div>
            <table class="view_list_tb">
                <thead>
                    <tr><th>ID</th><th>标题</th><th>类别</th><th>创建时间</th><th>上线时间</th><th>屏序</th><th>操作</th><th>状态</th><th>查看</th></tr>
                </thead>
                <tbody>
                    <?php foreach ($subjectinfo as $v) { ?>
                        <tr class="<?php if ($v['cs_pushlish_time'] > time()) echo "rews"; ?>">
                            <td><?php echo $v['id']; ?></td>
                            <td><button class="btn_check btn_check_list"></button>
                                <span><?php echo $v['cs_name'] ?></span>
                            </td>
                            <td>
                                <?php if ($v['cs_type'] == 9) echo "广告专题"; ?>
                                <?php if ($v['cs_type'] == 1) echo "时钟专题"; ?>
                            </td>
                             <td><?php if ($v['cs_create_time']) echo date("Y-m-d H:i:s", $v['cs_create_time']); ?></td>
                            <td><?php if ($v['cs_pushlish_time']) echo date("Y-m-d H:i:s", $v['cs_pushlish_time']); ?></td>
                            <td><?php echo $v['cs_screenque']; ?></td>
                            <td>
                                <a class="btn_txt" href="/Admin/Clocksubject/subjectedit?sid=<?php echo $v['id'] ?>">编辑</a>
                                <a class="btn_txt pop_btn delBtn" openPopId="fixTipView" val="<?php echo $v['id'] ?>">删除</a>
                            </td>
                            <td>
                                <!-- 有修改权限时输出如下 -->
                                <div class="select_box" >
                                    <label class="select_val" val="<?php echo $v['cs_status'] ?>"><?php echo $status[$v['cs_status']] ?></label>
                                    <ul class="select_option ch_status"
                                        sid="<?php echo $v['id'] ?>"                                    
                                    >
                                        <li val="2">已上线</li>
                                        <li val="1">未上线</li>
                                    </ul>
                                </div><!-- select_box end-->
                            </td>
                            <td>
                                <a class="btn_txt pop_btn prev_btn" openPopId="fixPicView" val="<?php echo $v['url'] ?>">预览</a>
                            </td>
                        </tr>
                    <?php } ?>

                </tbody>
            </table>
        </section>



    </div><!-- content end -->

</section>

<!-- 弹窗 消息+按钮-->
<div class="pop_wraper" id="fixTipView">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_tip">
                    <p class="tip_mes">是否删除<span>该专题</span></p>
                    <div class="tip_btns">
                        <button class="btn_s2 delsub">确定</button>
                        <button class="btn_s2 btnCancel">取消</button></div>
                    <div class="pop_close"></div>
                </div>

            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->

<!-- 弹窗 图片 pop_style_img表示是图片 带该class的 点击页面其它区域会关闭该图片-->
<div class="pop_wraper pop_style_img" id="fixPicView">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_img">
                    <div class="pop_img_src"><img src="image/test_img02.png"></div>
                    <div class="pop_close"></div>
                </div>

            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->
<?php echo $this->render("common/pageshow.phtml"); ?>


<script type="text/javascript">
    $(function () {
        //首页查看->预览
        $(".prev_btn").click(function () {
            var img = $(this).attr("val");
            $(".pop_img_src >img").attr("src", img);
        });
        
        //首页修改状态
        $(".ch_status > li").click(function () {
            var sid = $(this).parent().attr("sid");
            var vals = $(this).attr("val");

            var data = "sid=" + sid + "&status=" + vals + "&token=" + token;
            var url = "/Admin/Clocksubject/update_setStatus";
            if (confirm("确定要改变当前专题的状态?")) {
                $.post(url, data, function (d) {
                    if (d) {
                        window.location.href = "/Admin/Clocksubject/index";
                    }
                });
            }
        });
        //删除主题
        $(".delBtn").click(function () {
            var sid = $(this).attr("val");
            $(".delsub").click(function () {
                var data = "sid=" + sid + "&token=" + token;
                var url = "/Admin/Clocksubject/delsubject";
                $(".pop_wraper").removeClass("show");
                $.post(url, data, function (d) {
                    if (d) {
                        window.location.href = "/Admin/Clocksubject/index"
                    }
                })

            })
        });

        $(".sellect_status >li").click(function () {
            var val = $(this).attr("val");
            var page = "<?php echo $apges ?>"
            window.location.href = "/Admin/Clocksubject/index?status=" + val + "&page=" + page;
        })

    })
</script>
</body>
</html>