<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 导航栏Ajax加载 指向navagator.html  menuOn表示分别需要高亮的菜单栏id 用下划线_隔开 eg:bz_taotu_taotuPack-->
<section class="navigator" menuOn="zt_newArrivals">

</section>

<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <!-- 壁纸详情-wp01-->
    <div id="zt_operation_01">
        <!-- 页面内容区域 注意：每个页面无论是否有内容 必定有一个content-->
        <div class="content">
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">一级标签</label>
                    <div class="tb_cont tb_cell">
                        <ul class="tag_list tag_one"><!-- tag_one 一级标签 只能选中一个 -->
                            <li class="<?php if ($type == 0) echo 'on' ?>"><a href="/Admin/Themenew/index?type=0">
                                    全部
                                </a>
                            </li>
                            <?php foreach ($targ as $v) { ?>
                                <li class="<?php if ($type == $v['id']) echo 'on' ?>"><a href="/Admin/Themenew/spcSort?type=<?php echo $v['id'] ?>">
                                        <?php echo $v["name"] ?>
                                    </a>
                                </li>
                            <?php } ?>

                        </ul>
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->

            <!--  <div class="com_tb_wrap">
                  <div class="com_tb">
                      <label class="tb_cell">二级标签</label>
                      <div class="tb_cont tb_cell">
                          <ul class="tag_list">
                              <li>家具</li>
                              <li>情感</li>
                              <li class="on">分割</li>
                              <li>和风</li>
                              <li>不懂</li>
                              <li>事情</li>

                              <li>抽象</li>
                              <li>风格</li>
                              <li>东东</li>
                              <li class="on">灯光</li>
                              <li>款式</li>
                              <li>帅哥</li>

                              <li>构图</li>
                              <li class="on">光影</li>
                              <li>一图</li>
                              <li>方式</li>
                              <li>美女</li>
                              <li>德萨</li>
                          </ul>
                      </div>
                  </div><!-- com_tb end -->
            <!--         </div><!-- com_tb_wrap end -->
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">搜索:</label>
                    <div class="tb_cont tb_cell">
                        <input type="text" style="width:350px;" class="rd_1 search_name" value="<?php echo $search ?>">
                        <button class="btn_s2 search_btn">搜索主题</button>
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <!-- <label class="tb_cell">状态</label>
                     <div class="tb_cont tb_cell">
                         <div class="select_box">
                             <label class="select_val">默认</label>
                             <ul class="select_option">
                                 <li>默认</li>
                                 <li>序号</li>
                                 <li>上传时间</li>
                             </ul>
                         </div><!-- select_box -->

                    <!-- </div>

                 </div><!-- com_tb end -->
                </div><!-- com_tb_wrap end -->
                <!-- 宫格模式 admin_mode显示各子项目的管理按钮-->
                <section class="view view_pics " id="viewPics">
                    <!-- 批量管理内容 默认隐藏 -->
                    <div class="view_admin view_pics_admin">
                        <!-- checkObj表示 点击后 哪些class要被选中 -->
                        <button class="btn_check btn_check_all" checkClass="btn_check_pics"></button><label>全选</label><span class="btn btn_s1 pack_del">批量删除</span>
                    </div>
                    <h1 class="block_name">全部主题</h1>
                    <ul class="view_pics_wrap "><!--  -->
                        <li class="view_pics_list">
                            <div class="pic_cont">
                                <img src="image/test_img02.png">
                                <button class="btn_check btn_check_pics"></button>
                                <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                            </div>
                            <p class="pic_name">趣味生活</p>
                        </li>

                        <li class="view_pics_list">
                            <div class="pic_cont">
                                <img src="image/test_img02.png">
                                <button class="btn_check btn_check_pics"></button>
                                <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                            </div>
                            <p class="pic_name">趣味生活</p>
                        </li>
                        <li class="view_pics_list">
                            <div class="pic_cont">
                                <img src="image/test_img02.png">
                                <button class="btn_check btn_check_pics"></button>
                                <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                            </div>
                            <p class="pic_name">趣味生活</p>
                        </li>
                        <li class="view_pics_list">
                            <div class="pic_cont">
                                <img src="image/test_img02.png">
                                <button class="btn_check btn_check_pics"></button>
                                <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                            </div>
                            <p class="pic_name">趣味生活</p>
                        </li>
                        <li class="view_pics_list">
                            <div class="pic_cont">
                                <img src="image/test_img02.png">
                                <button class="btn_check btn_check_pics"></button>
                                <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                            </div>
                            <p class="pic_name">趣味生活</p>
                        </li>
                        <li class="view_pics_list">
                            <div class="pic_cont">
                                <img src="image/test_img02.png">
                                <button class="btn_check btn_check_pics"></button>
                                <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                            </div>
                            <p class="pic_name">趣味生活</p>
                        </li>

                    </ul>
                    <div class="clear-fix"></div>
                </section>

                <!-- 列表模式 -->
                <section class="view view_list show" id="viewList">
                    <!-- 批量管理内容 默认隐藏 -->
                    <div class="view_admin view_list_admin">
                        <!-- checkObj表示 点击后 哪些class要被选中 -->
                        <button class="btn_check btn_check_all" checkClass="btn_check_list"></button><label>全选</label><span class="btn btn_s1 pack_approve">批量通过</span><span class="btn btn_s1 pack_del">批量删除</span>
                    </div>
                    <table class="view_list_tb">
                        <thead>
                            <tr><th style="width:12rem">主题</th>
                                <th>名称</th>
                                <th>作者</th>
                                <th>包类型</th>
                                <th>上传时间</th><th>状态</th><th>序号</th>
                            </tr>
                        </thead>
                        <tbody id="newProRecommend">
                            <?php foreach ($theme as $v) { ?>
                                <tr>
                                    <td><button class="btn_check btn_check_list"></button>
                                        <img src="<?php echo $imageurl . $file_imgs_catg[$v['id']][0]['img'] ?>" style="width:5rem;height:auto;">
                                    </td>
                                    <td><?php echo $v['title'] ?></td>
                                    <td><?php echo $v["designer"] ?></td>
                                    <td><?php echo "V" . $v['package_type']; ?></td>
                                    <td><?php echo date("Y-m-d", $v['create_time']) ?></td>
                                    <td><?php echo $status[$v['status']] ?></td>
                                    <td val="<?php echo $v['id'] ?>">
                                        <input class="numSort" type="text" value="<?php echo $v['spc_sort'] ?>">
                                    </td>
                                </tr>
                            <?php } ?>

                        </tbody>
                    </table>
                </section>

                <!--  <div class="bnts_wrap">
                      <button class="btn_s2 pop_btn" openpopid="fixTipView">确定</button>
                  </div>
              </div><!-- content end -->

            </div>
            </section>
            <?php echo $this->render("common/pageshow.phtml"); ?>
            <!-- 弹窗 消息+按钮-->
            <div class="pop_wraper" id="fixTipView">
                <div class="pop_outer">
                    <div class="pop_inner">
                        <div class="pop_content">
                            <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                            <div class="pop_cont_tip">
                                <p class="tip_mes">确定重新排序？</p>
                                <div class="tip_btns"><button class="btn_s2">确定</button><button class="btn_s2 btnCancel">取消</button></div>
                                <div class="pop_close"></div>
                            </div>

                        </div><!-- pop_content 结束 -->
                    </div><!-- pop-inner 结束 -->
                </div><!-- pop-outer 结束 -->
            </div><!-- pop-wraper 结束 -->
            <script type="text/javascript">
                $(function () {
                    $(".numSort").change(function () {
                        var sort = $(this).val();
                        var id = $(this).parent().attr("val");

                        if (isNaN(sort)) {
                            alert("请输入有效的数字");
                            return 0;
                        } else {
                            var data = "sort=" + sort + "&id=" + id + "&token=" + token;
                            var url = "/Admin/Themenew/upsortSpc";
                            $.post(url, data, function () {

                            })
                        }

                    });
                    $(".search_btn").on("click", function () {
                        var name = $(".search_name").val();
                        window.location.href = "/Admin/Themenew/spcSort?search=" + name;
                    });
                })
            </script>
            </body>
            </html>