<?php $page = isset($_GET["page"])? $_GET["page"]:1;?>
{"success":true,"msg":"",
	"data":{
		"list":
		[
			{
				"id":"32",
				"name":"三国杀",
				"resume":"一个非常好玩的游戏,一个非常好玩的游戏",
				"img":"http://18.8.2.98:8899/apps/game/apk/pic/game.jpg",
				"data-infpage":"\u4ed9\u9b54\u5251,detail.php,10,http:\/\/gamedl.gionee.com\/apps\/games\/xianmojian.apk,com.androidbox.xmjjlsj,4.93,Android1.6,240*320-320*480"
			},
			{
				"id":"32",
				"name":"三国杀",
				"resume":"一个非常好玩的游戏",
				"img":"http://assets.3gtest.gionee.com/apps/game/apk/pic/game.jpg",
				"data-infpage":"\u4ed9\u9b54\u5251,detail.php,10,http:\/\/gamedl.gionee.com\/apps\/games\/xianmojian.apk,com.androidbox.xmjjlsj,4.93,Android1.6,240*320-320*480"
			},
			{
				"id":"32",
				"name":"三国杀",
				"resume":"一个非常好玩的游戏",
				"img":"http://assets.3gtest.gionee.com/apps/game/apk/pic/game.jpg",
				"data-infpage":"\u4ed9\u9b54\u5251,detail.php,10,http:\/\/gamedl.gionee.com\/apps\/games\/xianmojian.apk,com.androidbox.xmjjlsj,4.93,Android1.6,240*320-320*480"
			},
			{
				"id":"32",
				"name":"三国杀",
				"resume":"一个非常好玩的游戏",
				"img":"http://assets.3gtest.gionee.com/apps/game/apk/pic/game.jpg",
				"data-infpage":"\u4ed9\u9b54\u5251,detail.php,10,http:\/\/gamedl.gionee.com\/apps\/games\/xianmojian.apk,com.androidbox.xmjjlsj,4.93,Android1.6,240*320-320*480"
			},
			{
				"id":"32",
				"name":"三国杀",
				"resume":"一个非常好玩的游戏",
				"img":"http://assets.3gtest.gionee.com/apps/game/apk/pic/game.jpg",
				"data-infpage":"\u4ed9\u9b54\u5251,detail.php,10,http:\/\/gamedl.gionee.com\/apps\/games\/xianmojian.apk,com.androidbox.xmjjlsj,4.93,Android1.6,240*320-320*480"
			},
			{
				"id":"32",
				"name":"三国杀",
				"resume":"一个非常好玩的游戏",
				"img":"http://assets.3gtest.gionee.com/apps/game/apk/pic/game.jpg",
				"data-infpage":"\u4ed9\u9b54\u5251,detail.php,10,http:\/\/gamedl.gionee.com\/apps\/games\/xianmojian.apk,com.androidbox.xmjjlsj,4.93,Android1.6,240*320-320*480"
			},
			{
				"id":"32",
				"name":"三国杀",
				"resume":"一个非常好玩的游戏",
				"img":"http://assets.3gtest.gionee.com/apps/game/apk/pic/game.jpg",
				"data-infpage":"\u4ed9\u9b54\u5251,detail.php,10,http:\/\/gamedl.gionee.com\/apps\/games\/xianmojian.apk,com.androidbox.xmjjlsj,4.93,Android1.6,240*320-320*480"
			},
			{
				"id":"32",
				"name":"三国杀",
				"resume":"一个非常好玩的游戏",
				"img":"http://assets.3gtest.gionee.com/apps/game/apk/pic/game.jpg",
				"data-infpage":"\u4ed9\u9b54\u5251,detail.php,10,http:\/\/gamedl.gionee.com\/apps\/games\/xianmojian.apk,com.androidbox.xmjjlsj,4.93,Android1.6,240*320-320*480"
			}
		],
	"hasNext":<?php echo ($page==4? "false":"true");?>,"curpage":<?php echo $page;?>}}

