<div class="fixed_head">
    <div id="top_down"></div>
    <div class="header_home"><a href="javascript:;" class="sel_cate" w="topicons" stat="15793"><i></i> 电影 </a> <span
            class="top_icons"><a href="javascript:;" w="topicons" stat="15794" class="ico_user"
                                 style="display: none;">我的</a><a href="javascript:;" w="topicons" stat="15795"
                                                                 class="ico_his" style="display: none;">历史</a><a
                href="/search.php" w="topicons" stat="15796" class="ico_search_home">搜索</a></span> <span
            class="update_tip" style="display: none;"></span>

        <div class="menu_shape"></div>
        <ul class="menu_pannel">
            <li><a href="/" class="ico_list_home" w="nav" stat="15797">首页</a><a
                    href="/category.php?cat_id=1&amp;title=电影&amp;type=recommend" class="ico_list_movie" w="nav"
                    stat="15798">电影</a><a href="/category.php?cat_id=2&amp;title=电视剧&amp;type=recommend"
                                          class="ico_list_tv" w="nav" stat="15799">电视剧</a><a
                    href="/category.php?cat_id=4&amp;title=综艺" class="ico_list_drama" w="nav" stat="15801">综艺</a>
            </li>
            <li><a href="/category.php?&amp;cat_id=3&amp;title=动漫" class="ico_list_comic" w="nav"
                   stat="15800">动漫</a><a href="/news/" class="ico_list_info" w="nav" stat="18925">资讯</a><a
                    href="/ent/" class="ico_list_ent" w="nav" stat="">娱乐</a><a href="/rank.php?title=榜单"
                                                                               class="ico_list_rank" w="nav"
                                                                               stat="15802">榜单</a></li>
        </ul>
    </div>
    <div id="nav" class="news_nav">
        <div class="news_all"><a class="" href="/?c=category&amp;cat_id=1&amp;type=&amp;area=&amp;year=" data-key=""
                                 w="list_menu" stat="全部">全部</a></div>
        <div class="news_nav_tab scroll_wrap"
             style="backface-visibility: hidden; -webkit-backface-visibility: hidden; overflow-x: hidden; transform: translate3d(0px, 0px, 0px); -webkit-transform: translate3d(0px, 0px, 0px);">
            <div class="scroller"
                 style="backface-visibility: hidden; -webkit-backface-visibility: hidden; transform: translate3d(0px, 0px, 0px); -webkit-transform: translate3d(0px, 0px, 0px); transition-property: -webkit-transform; -webkit-transition-property: -webkit-transform; transition-duration: 0s; -webkit-transition-duration: 0s;">
                <a class="cur" href="/?c=category&amp;cat_id=1&amp;type=recommend" data-key="" w="list_menu"
                   stat="精选"><span>精选</span></a> <a class=""
                                                    href="/?c=category&amp;cat_id=1&amp;type=%E5%8A%A8%E4%BD%9C&amp;page=1&amp;size=30"
                                                    data-key="动作" w="list_menu" stat="动作"><span>动作</span></a> <a
                    class="" href="/?c=category&amp;cat_id=1&amp;type=%E5%96%9C%E5%89%A7&amp;page=1&amp;size=30"
                    data-key="喜剧" w="list_menu" stat="喜剧"><span>喜剧</span></a> <a class=""
                                                                                 href="/?c=category&amp;cat_id=1&amp;type=%E7%88%B1%E6%83%85&amp;page=1&amp;size=30"
                                                                                 data-key="爱情" w="list_menu"
                                                                                 stat="爱情"><span>爱情</span></a> <a
                    class="" href="/?c=category&amp;cat_id=1&amp;type=%E6%81%90%E6%80%96&amp;page=1&amp;size=30"
                    data-key="恐怖" w="list_menu" stat="恐怖"><span>恐怖</span></a> <a class=""
                                                                                 href="/?c=category&amp;cat_id=1&amp;type=%E7%A7%91%E5%B9%BB&amp;page=1&amp;size=30"
                                                                                 data-key="科幻" w="list_menu"
                                                                                 stat="科幻"><span>科幻</span></a></div>
        </div>
    </div>
</div>
<div id="main" class="show_rec">
    <div class="list_rec">
        <div class="list_rec"> <!-- 轮播位 -->
            <div class="banner_wrap">
                <ul class="slide_main" id="slider"
                    style="width: 2560px; height: 140px; -webkit-transform: translate3d(-1600px, 0px, 0px); -webkit-transition-duration: 0.6s; transition-duration: 0.6s;">
                    <li style="width: 320px; height: 140px;"><a
                            href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1416194762.html" stat="65814"
                            title="【全网最新】" w="1057"> <img
                                src="http://dh2.kimg.cn/kimg/v/m/upload/20150611/bec19fa8c5bca28a64d80812c2d0ad63.jpg_640x280.jpg?q=60"
                                class=""> <i class="tip_purple" style="background:#FF0066">专题</i>

                            <div class="text_info">【全网最新】<span class="gray">看你漏了哪些精华？</span></div>
                        </a></li>
                    <li style="width: 320px; height: 140px;"><a href="/detail.php?tsid=273231" stat="70421"
                                                                title="【疯狂麦克斯4】" w="1057"> <img
                                src="http://dh2.kimg.cn/kimg/v/m/upload/20150623/3b9742651b4f1b455511d926460a123e.jpg_640x280.jpg?q=60">
                            <i class="tip_purple" style="background:#FF8800">热</i>

                            <div class="text_info">【疯狂麦克斯4】<span class="gray">沙海飙车、激烈枪战、震撼爆破</span></div>
                        </a></li>
                    <li style="width: 320px; height: 140px;"><a
                            href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1434679842.html" stat="70328"
                            title="【周末影院】欲望" w="1057"> <img
                                src="http://dh2.kimg.cn/kimg/v/m/upload/20150619/a78aea1a607d181e8fd06cbfecdf5647.jpg_640x280.jpg?q=60"
                                class=""> <i class="tip_purple" style="background:#FF0066">专题</i>

                            <div class="text_info">【周末影院】欲望<span class="gray">在骚动</span></div>
                        </a></li>
                    <li style="width: 320px; height: 140px;"><a
                            href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1434003777.html" stat="70142"
                            title="【怪兽崛起】" w="1057"> <img
                                src="http://dh2.kimg.cn/kimg/v/m/upload/20150618/84f733efa6737cc8d62cd424937b7532.jpg_640x280.jpg?q=60"
                                class=""> <i class="tip_purple" style="background:#FF0066">专题</i>

                            <div class="text_info">【怪兽崛起】<span class="gray">侏罗纪公园重开 嗜血怪兽的报复</span></div>
                        </a></li>
                    <li style="width: 320px; height: 140px;"><a href="/detail.php?tsid=271324" stat="66414"
                                                                title="【破坏者】" w="1057"> <img
                                src="http://dh2.kimg.cn/kimg/v/m/upload/20150611/63233ab68c8298e3d0c936de8a899a39.jpg_640x280.jpg?q=60"
                                class="">

                            <div class="text_info">【破坏者】<span class="gray">血腥复仇 真实杀戮未删减</span></div>
                        </a></li>
                    <li style="width: 320px; height: 140px;"><a
                            href="http://v.qq.com/prev/g/gwmjlphvhf0mol6.html?vid=n00163p01hf" stat="65813"
                            title="【末日崩塌】" w="1057"> <img
                                src="http://dh2.kimg.cn/kimg/v/m/upload/20150602/274b9d21583488eb1b8e8c1a7d64f342.jpg_640x280.jpg?q=60"
                                class=""> <i class="tip_purple" style="background:#006699">特辑</i>

                            <div class="text_info">【末日崩塌】<span class="gray">洛杉矶全城毁灭镜头曝光</span></div>
                        </a></li>
                    <li style="width: 320px; height: 140px;"><a
                            href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1416194762.html" stat="65814"
                            title="【全网最新】" w="1057"> <img
                                src="http://dh2.kimg.cn/kimg/v/m/upload/20150611/bec19fa8c5bca28a64d80812c2d0ad63.jpg_640x280.jpg?q=60"
                                class=""> <i class="tip_purple" style="background:#FF0066">专题</i>

                            <div class="text_info">【全网最新】<span class="gray">看你漏了哪些精华？</span></div>
                        </a></li>
                    <li style="width: 320px; height: 140px;"><a href="/detail.php?tsid=273231" stat="70421"
                                                                title="【疯狂麦克斯4】" w="1057"> <img
                                src="http://dh2.kimg.cn/kimg/v/m/upload/20150623/3b9742651b4f1b455511d926460a123e.jpg_640x280.jpg?q=60">
                            <i class="tip_purple" style="background:#FF8800">热</i>

                            <div class="text_info">【疯狂麦克斯4】<span class="gray">沙海飙车、激烈枪战、震撼爆破</span></div>
                        </a></li>
                </ul>
                <div class="slide_tab"><i class=""></i><i class=""></i><i class=""></i><i class=" "></i><i
                        class=" cur"></i><i class=""></i></div>
            </div>
                               <!-- 2列运营列表 -->
            <div class="news_title"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1416194762.html" class="block"
                                       stat="more" w="1014"> <span class="title_text">最新热映</span> <span
                        class="link_more">更多<i class="more"></i></span></a></div>
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=100029" stat="70425" w="1014" class="list_cont" title="杀破狼">
                            <div class="pic_info">
                                <div class="img"
                                     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150623/51d9867b406155646e78f5052980c0f4.jpg_320x192.jpg?q=85&amp;mode=1);"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.6</span></div>
                            </div>
                            <div class="title">杀破狼<br><span class="desc">窄巷械斗、血腥打斗，酣畅淋漓又无比压抑</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=265270" stat="70422" w="1014" class="list_cont" title="裸色告白">
                            <div class="pic_info">
                                <div class="img"
                                     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150623/2fbf5994a5b8f50cf0bb5c030a5d7f36.jpg_320x192.jpg?q=85&amp;mode=1);"></div>
                                <div class="img_layer layer_notext"><span class="score_left">6.5</span></div>
                            </div>
                            <div class="title">裸色告白<br><span class="desc">走进援交少女的情欲波澜</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=272781" stat="66261" w="1014" class="list_cont" title="赤道">
                            <div class="pic_info">
                                <div class="img"
                                     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150609/ae6a4864f9007920d6aa555f4f1c682d.jpg_320x192.jpg?q=85&amp;mode=1);"></div>
                                <div class="img_layer layer_notext"><span class="score_left">5.9</span></div>
                            </div>
                            <div class="title">赤道<br><span class="desc">冷艳悍匪上演贴身肉搏，男神齐聚上演终极绝杀</span></div>
                        </a></li>
                    <li><a href="http://www.fun.tv/vplay/g-110174.e-1?alliance=159682" stat="70330" w="1014"
                           class="list_cont" title="山鹰之歌">
                            <div class="pic_info">
                                <div class="img"
                                     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150619/5ecd60d33d805f1f00b9f0e21c743eba.jpg_320x192.jpg?q=85&amp;mode=1);"></div>
                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">山鹰之歌<br><span class="desc">牧师为少女之死身心负罪，惊世骇俗畸恋暗涌</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=273010" stat="70017" w="1014" class="list_cont" title="念念">
                            <div class="pic_info">
                                <div class="img"
                                     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150615/cf0a4b20d4c11ddc52a739739186923c.jpg_320x192.jpg?q=85&amp;mode=1);"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.2</span></div>
                            </div>
                            <div class="title">念念<br><span class="desc">梁洛施痴恋张孝全，李心洁饰小三挑战家暴戏份</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=273080" stat="70141" w="1014" class="list_cont" title="冲锋车">
                            <div class="pic_info">
                                <div class="img"
                                     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150617/02492350020776d2f89f9da48769882b.jpg_320x192.jpg?q=85&amp;mode=1);"></div>
                                <div class="img_layer layer_notext"><span class="score_left">6.8</span></div>
                            </div>
                            <div class="title">冲锋车<br><span class="desc">吴镇宇+任达华+古巨基，那夜我们坐上了去截尸小VAN</span></div>
                        </a></li>
                </ul>
            </div>
                               <!-- 2列运营列表 -->
            <div class="news_title"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1434680162.html" class="block"
                                       stat="more" w="6403"> <span class="title_text">带着逗比去旅行</span> <span
                        class="link_more">更多<i class="more"></i></span></a></div>
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=273164" stat="70317" w="6403" class="list_cont" title="哈拉上路">
                            <div class="pic_info">
                                <div class="img"
                                     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150619/aa70fd02434de5a1dbf29c6a15ba4be9.jpg_320x192.jpg?q=85&amp;mode=1);"></div>
                                <div class="img_layer layer_notext"><span class="score_left">6.8</span></div>
                            </div>
                            <div class="title">哈拉上路<br><span class="desc">一夜情录像被错误寄给女友，快追吧蠢猪</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=273165" stat="70318" w="6403" class="list_cont" title="共产小子西游记">
                            <div class="pic_info">
                                <div class="img"
                                     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150619/36bd8e60f5681be663673cc1cc4ee787.jpg_320x192.jpg?q=85&amp;mode=1);"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.5</span></div>
                            </div>
                            <div class="title">共产小子西游记<br><span class="desc">东德逗比小子的美国之旅，穷逼找爹看大桥</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=246844" stat="70319" w="6403" class="list_cont" title="荒野生存">
                            <div class="pic_info">
                                <div class="img"
                                     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150619/50e12c4cf50e3e647531a0cf22e31ea6.jpg_320x192.jpg?q=85&amp;mode=1);"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.8</span></div>
                            </div>
                            <div class="title">荒野生存<br><span class="desc">乱入一部没有逗比的高分佳作，一个理想主义者的流浪</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=67974" stat="70322" w="6403" class="list_cont" title="落叶归根">
                            <div class="pic_info">
                                <div class="img"
                                     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150619/3f96cd318c99496b9a2726ea357b74da.jpg_320x192.jpg?q=85&amp;mode=1);"></div>
                                <div class="img_layer layer_notext"><span class="score_left">9.3</span></div>
                            </div>
                            <div class="title">落叶归根<br><span class="desc">本山大叔最拿得起公路片，有笑点有泪点</span></div>
                        </a></li>
                </ul>
            </div>
            <div class="adbanner">
                <div id="gdt" data-posid="8030309010338868" data-appid="1102297551">
                    <div style="left: 0px; bottom: 0px; width: 100%; height: 50px;" id="gdt_banner_popup_wrap">
                        <div class="gdth_popup_floater"></div>
                        <div class="gdth_popup_wrap" style="margin:0 auto;position:relative;max-width:1280px;">
                            <iframe id="gdt_banner_ifr"
                                    style="width: 100%; position: static !important; display: block !important; margin: 0px !important; padding: 0px !important; visibility: visible !important; float: none !important; border-width: 0px !important; height: 50px;"
                                    scrolling="no" frameborder="0" marginheight="0" marginwidth="0"
                                    allowtransparency="true"
                                    src="http://qzonestyle.gtimg.cn/qzone/biz/res/tmpl/banner.html#_spoint=1435051634930&amp;posid=8030309010338868&amp;posh=100&amp;posw=640&amp;posdomain=http%3A%2F%2Fv.m.liebao.cn&amp;postnum=0.62557209469378&amp;adtype=banner&amp;ishybrid=false&amp;platform=web&amp;posclass=undefined&amp;appid=1102297551&amp;win_w=320&amp;win_h=7554&amp;conw=320&amp;conh=0&amp;scale=1&amp;conw=320"></iframe>
                        </div>
                    </div>
                </div>
                <!-- <script type="text/javascript" id="gdt-8030309010338868"> var TencentGDT = TencentGDT || []; TencentGDT.push({ posid:'8030309010338868', type:'banner',   filltype:'full', appid: "1102297551" }); (function() { var doc=document, h=doc.getElementsByTagName('head')[0], s=doc.createElement('script'); s.async=true; s.src='http://qzs.qq.com/qzone/biz/res/i.js '; h && h.insertBefore(s,h.firstChild) })() </script> -->
            </div>
                               <!-- 2列运营列表 -->
            <div class="news_title"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1434077615.html" class="block"
                                       stat="more" w="6315"> <span class="title_text">听说有人要盗墓</span> <span
                        class="link_more">更多<i class="more"></i></span></a></div>
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=273242" stat="70467" w="6315" class="list_cont" title="丧尸禁区">
                            <div class="pic_info">
                                <div class="img"
                                     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150623/6c6c452f6de2b29b3c578a6c1051822e.jpg_320x192.jpg?q=85&amp;mode=1);"></div>
                                <div class="img_layer layer_notext"><span class="score_left">5.6</span></div>
                            </div>
                            <div class="title">丧尸禁区<br><span class="desc">病毒侵蚀人类变成嗜血僵尸，爆笑黑色喜剧</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=273241" stat="70466" w="6315" class="list_cont" title="重创">
                            <div class="pic_info">
                                <div class="img"
                                     style="background-image: url(http://dh2.kimg.cn/kimg/v/m/upload/20150623/75e852eb92f7f2cbe74830b9d74f3dbb.jpg_320x192.jpg?q=85&amp;mode=1);"></div>
                                <div class="img_layer layer_notext"><span class="score_left">6.1</span></div>
                            </div>
                            <div class="title">重创<br><span class="desc">少女荒野遭虐杀，咒术还魂后变恐怖魔女</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=273243" stat="70470" w="6315" class="list_cont" title="劫匪与僵尸">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/6197cd985d1c6e3d0f20bc1eaefea768.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">6.2</span></div>
                            </div>
                            <div class="title">劫匪与僵尸<br><span class="desc">当劫匪遇见僵尸，逗比劫匪与逗比僵尸的对抗</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=272940" stat="66560" w="6315" class="list_cont" title="活跳尸3">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150615/c84fd0b301dcf32c86145f87b5fefaaf.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">6.2</span></div>
                            </div>
                            <div class="title">活跳尸3<br><span class="desc">大哥专业点行不，僵尸是咬脖子的你这是演哪出</span></div>
                        </a></li>
                </ul>
            </div>
                               <!-- 2列运营列表 -->
            <div class="news_title"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1433474551.html" class="block"
                                       stat="more" w="6269"> <span class="title_text">苦逼的终点线</span> <span
                        class="link_more">更多<i class="more"></i></span></a></div>
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=195530" stat="66279" w="6269" class="list_cont" title="名扬四海">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150605/befbd313bfcb680a30274cb0495aceb9.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">9.0</span></div>
                            </div>
                            <div class="title">名扬四海<br><span class="desc">努力后不一定就有回报，不过那又能怎样</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=62175" stat="66282" w="6269" class="list_cont" title="国王的演讲">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150605/962a880085694613166ede80d179493d.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">9.4</span></div>
                            </div>
                            <div class="title">国王的演讲<br><span class="desc">便秘一样的表达，你能怎么办？只有拼尽全力！</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=267436" stat="66281" w="6269" class="list_cont" title="黑天鹅">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150605/848af34c028ebfcfd421922f3e03c8ed.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.0</span></div>
                            </div>
                            <div class="title">黑天鹅<br><span class="desc">你需要性魅力？为了梦想，一切都行！</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=249052" stat="66284" w="6269" class="list_cont" title="丑女大翻身">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150605/b4955c568afc181376cfaf9733eaa62a.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.0</span></div>
                            </div>
                            <div class="title">丑女大翻身<br><span class="desc">长得丑就认命了？那你就不仅仅是丑的问题了</span></div>
                        </a></li>
                </ul>
            </div>
                               <!-- 2列运营列表 -->
            <div class="news_title"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1433410609.html" class="block"
                                       stat="more" w="6237"> <span class="title_text">新欢旧爱大作战</span> <span
                        class="link_more">更多<i class="more"></i></span></a></div>
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=64342" stat="66545" w="6237" class="list_cont" title="一夜迷情">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150619/ca07cf7fa47ecc3d0a21a9858bd0608a.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.0</span></div>
                            </div>
                            <div class="title">一夜迷情<br><span class="desc">婚姻本来就是个错误，爱情更不是只对一个人</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=136228" stat="66535" w="6237" class="list_cont" title="苦月亮">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150612/3be0b898e6cf8c9c8151faa93c9725cb.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.1</span></div>
                            </div>
                            <div class="title">苦月亮<br><span class="desc">关系太混乱了，爱情其实就是这么回事</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=272949" stat="66528" w="6237" class="list_cont" title="偷心">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150619/e5493ae295e0a150b9397fdddac37dd0.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.8</span></div>
                            </div>
                            <div class="title">偷心<br><span class="desc">四个男女之间的反复关系，在爱情里追逐和厌倦</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=62195" stat="66081" w="6237" class="list_cont" title="前度">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150619/9ff1002b284d313ff52b6548de8979e6.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">9.0</span></div>
                            </div>
                            <div class="title">前度<br><span class="desc">永远别放EX进你的家门</span></div>
                        </a></li>
                </ul>
            </div>
                               <!-- 腾讯广告2 --> <!-- <div id="qvapp"></div> --> <!-- 2列运营列表 -->
            <div class="news_title"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1432542822.html" class="block"
                                       stat="more" w="6152"> <span class="title_text">封闭空间</span> <span
                        class="link_more">更多<i class="more"></i></span></a></div>
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=241671" stat="70469" w="6152" class="list_cont" title="黑暗楼层">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/385db0972eb61a9a95b2f5291e8b9b73.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.0</span></div>
                            </div>
                            <div class="title">黑暗楼层<br><span class="desc">自闭症的精神世界，永远无法接触到真实世界</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=73288" stat="70269" w="6152" class="list_cont" title="异次元杀阵">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150619/dcaa41de172d14b1544512eb3db99fbb.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.0</span></div>
                            </div>
                            <div class="title">异次元杀阵<br><span class="desc">每个房间6个出口，只有一个是对的，你走哪个？</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=64116" stat="70058" w="6152" class="list_cont" title="死亡实验">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150615/f210ce6f57619926f5fd985cbe63ada1.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.4</span></div>
                            </div>
                            <div class="title">死亡实验<br><span class="desc">在监狱中对人性的实验，身份只是社会给的符号</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=195549" stat="64292" w="6152" class="list_cont" title="九死">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150525/1fa99b7ee820faf7457f3e2e3e02d931.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">9.0</span></div>
                            </div>
                            <div class="title">九死<br><span class="desc">9个被绑架者，每分钟杀死一人，直到找到原因为止</span></div>
                        </a></li>
                </ul>
            </div>
                               <!-- 2列运营列表 -->
            <div class="news_title"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1432096568.html" class="block"
                                       stat="more" w="6053"> <span class="title_text">就是干</span> <span
                        class="link_more">更多<i class="more"></i></span></a></div>
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=62375" stat="70044" w="6053" class="list_cont" title="王者之剑">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150619/315a3730c87fab853735dd45b1dce961.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">9.0</span></div>
                            </div>
                            <div class="title">王者之剑<br><span class="desc">经典奇幻名著，太野蛮太暴力，一场接一场的血腥打斗</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=249562" stat="70064" w="6053" class="list_cont" title="疯狗强尼">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150615/1158c32227f41cbce3d941c7e2096a5c.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.1</span></div>
                            </div>
                            <div class="title">疯狗强尼<br><span class="desc">娃娃兵的残酷人生，烧杀抢掠强奸妇女</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=98904" stat="63661" w="6053" class="list_cont" title="剑鱼行动">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150520/372533f36b35a440e61eaec0e02971d1.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.4</span></div>
                            </div>
                            <div class="title">剑鱼行动<br><span class="desc">亮瞎眼的开场，吸睛的暴露镜头，亮点颇多</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=126531" stat="63660" w="6053" class="list_cont" title="别惹我">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150527/455d5dc3a4501459e8fa5df34b6bf1c7.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.0</span></div>
                            </div>
                            <div class="title">别惹我<br><span class="desc">黑帮家庭的简单暴力，要的就是这种直接</span></div>
                        </a></li>
                </ul>
            </div>
                               <!-- 2列运营列表 -->
            <div class="news_title"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1431605404.html" class="block"
                                       stat="more" w="5973"> <span class="title_text">荒诞派</span> <span
                        class="link_more">更多<i class="more"></i></span></a></div>
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=249934" stat="66550" w="5973" class="list_cont" title="百万杀人游戏">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150612/dc0b8c318067b80879bf54eb3dc70d06.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.4</span></div>
                            </div>
                            <div class="title">百万杀人游戏<br><span class="desc">疯狂野蛮的轮盘赌命游戏，黑白世界的残酷法则</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=66665" stat="63286" w="5973" class="list_cont" title="爱情是狗娘">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150525/d4c8cd85e64f2debac5efaf582b8d3a0.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">6.3</span></div>
                            </div>
                            <div class="title">爱情是狗娘<br><span class="desc">得不到它，就辱骂它吧</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=271862" stat="63287" w="5973" class="list_cont" title="新女友">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150609/63e99d47747c923b9d2c4d712fa81f53.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.5</span></div>
                            </div>
                            <div class="title">新女友<br><span class="desc">流动的欧容，不可能的性关系</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=264291" stat="63289" w="5973" class="list_cont" title="铁皮鼓">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/08569ed840d668f80d5b3943bdd3e29f.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.4</span></div>
                            </div>
                            <div class="title">铁皮鼓<br><span class="desc">畸形男孩，乱伦之家</span></div>
                        </a></li>
                </ul>
            </div>
                               <!-- 2列运营列表 -->
            <div class="news_title"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1432020265.html" class="block"
                                       stat="more" w="6102"> <span class="title_text">精神虐杀</span> <span
                        class="link_more">更多<i class="more"></i></span></a></div>
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=241611" stat="70454" w="6102" class="list_cont" title="大卫·戈尔的一生">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/a35bbccdc18cfe82d9405f656164213c.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.0</span></div>
                            </div>
                            <div class="title">大卫·戈尔的一生<br><span class="desc">一个奸杀犯的故事，一部不能剧透的电影</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=272597" stat="65918" w="6102" class="list_cont" title="美国田园下的罪恶">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150603/4fb9b54c53df1d2ce750a60fa7741044.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.2</span></div>
                            </div>
                            <div class="title">美国田园下的罪恶<br><span class="desc">女孩被囚禁虐待，真实发生的最可怕犯罪事件</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=74709" stat="63958" w="6102" class="list_cont" title="狗镇">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150609/311527b47c221bfb836fabbcfce35ab8.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">9.0</span></div>
                            </div>
                            <div class="title">狗镇<br><span class="desc">逃犯女孩沦为泄欲工具，狗一样的生活触发内心的愤怒</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=272961" stat="66548" w="6102" class="list_cont" title="双面玛莎">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150618/8fe335b39bc99edae5642106a25eacd4.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">6.3</span></div>
                            </div>
                            <div class="title">双面玛莎<br><span class="desc">被邪教洗脑，被教主强奸，分不清现实与幻觉</span></div>
                        </a></li>
                </ul>
            </div>
                               <!-- 图文bannner -->
            <div class="news_title"><span class="title_text">预告·花絮·特辑</span></div>
            <div class="banner_s"><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1435030274.html" stat="70438"
                                     w="1018">
                    <div class="pic_info">
                        <div class="img lazy_bg"
                             data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/a0b80687403dff1afb298bed5ebfed3c.jpg_640x280.jpg?q=60"></div>
                        <i class="tip_purple" style="background:#FF0066">专题</i></div>
                </a>

                <div class="banner_s_desc"><strong style="background:#990033"> 煎饼侠 </strong>
                    <span>&lt;屌丝男士&gt;大电影，爆笑来袭，笑不完的梗，看不完的颜，掉不完的节操，应有尽有</span>
                </div>
            </div>
                               <!-- 2列运营列表 -->
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=270752" stat="63908" w="1056" class="list_cont" title="侏罗纪世界">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150525/eacc6df83e5b600796baf5baa3a5b693.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#006633">预告</i>

                                <div class="img_layer layer_notext"><span class="score_left">8.0</span></div>
                            </div>
                            <div class="title">侏罗纪世界<br><span class="desc">恐龙+灾难=爽翻！星爵加盟全新经典</span></div>
                        </a></li>
                    <li><a href="http://www.56.com/u12/v_MTM3MjgxNDA5.html" stat="63904" w="1056" class="list_cont"
                           title="爱恋3D">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150525/823f02416838e060bc3645cae1edc7f3.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#006633">预告</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">爱恋3D<br><span class="desc">大尺度惊呆世人，与未成年少女的3P戏曝光</span></div>
                        </a></li>
                    <li><a href="http://v.qq.com/cover/d/dogx7k2n03qlqwy.html?vid=q0016ugilwv" stat="65815" w="1056"
                           class="list_cont" title="《发条橙》经典片段">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150602/8ad669dd60d1bf708b3734b68d1a9e68.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#006699">特辑</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">《发条橙》经典片段<br><span class="desc">男孩遭老男人狠锤裆部</span></div>
                        </a></li>
                    <li><a href="http://v.qq.com/page/x/x/g/x0016k20ixg.html" stat="63676" w="1056"
                           class="list_cont" title="道士下山">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150521/fa036becbe40057d534bf5d70454495b.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#006633">预告</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">道士下山<br><span class="desc">范伟玩转娇羞林志玲</span></div>
                        </a></li>
                </ul>
            </div>
                               <!-- 图文bannner -->
            <div class="news_title"><a
                    href="http://v.m.liebao.cn/category.php?cat_id=1&amp;type=&amp;area=%E5%86%85%E5%9C%B0&amp;year="
                    class="block" stat="more" w="1054"> <span class="title_text">国产精选</span> <span
                        class="link_more">更多<i class="more"></i></span></a></div>
            <div class="banner_s"><a href="/detail.php?tsid=62360" stat="70110" w="1054">
                    <div class="pic_info">
                        <div class="img lazy_bg"
                             data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150616/89a4dd8ab626a2dfdaa125c0b47c3a0c.jpg_640x280.jpg?q=60"></div>
                    </div>
                </a>

                <div class="banner_s_desc"><strong style="background:#990033"> 金陵十三钗 </strong>
                    <span>一群妓女和一个小男孩的慷慨赴难，换得女学生和神父的得救，故事就是这么个故事</span>
                </div>
            </div>
                               <!-- 2列运营列表 -->
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=179482" stat="66249" w="1058" class="list_cont" title="美姐">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150608/c92a496a9b4e7d513c3cd30d67940ce6.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.5</span></div>
                            </div>
                            <div class="title">美姐<br><span class="desc">幼年恋上邻家少妇，长大后与少妇女儿结婚</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=272622" stat="70179" w="1058" class="list_cont" title="雏妓">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150618/26e4494e94525cd9de4c77852954f9f2.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">6.4</span></div>
                            </div>
                            <div class="title">雏妓<br><span class="desc">遭继父强暴，被包养，社会道德的撕扯，尺度惊人</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=272894" stat="66423" w="1058" class="list_cont" title="僵尸">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150611/6c590ace396296892f7b4739a8816121.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.7</span></div>
                            </div>
                            <div class="title">僵尸<br><span class="desc">一开始听说是国产恐怖片，其实我是拒绝的</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=65943" stat="66349" w="1058" class="list_cont" title="边境风云">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150611/4e822eb7a1e099f8ddc6e48a20d77bc9.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.8</span></div>
                            </div>
                            <div class="title">边境风云<br><span class="desc">独具一格警匪片，不开三十二场演唱会做杀手</span></div>
                        </a></li>
                </ul>
            </div>
                               <!-- 图文bannner -->
            <div class="news_title"><a
                    href="http://v.m.liebao.cn/category.php?cat_id=1&amp;type=&amp;area=%E9%9F%A9%E5%9B%BD&amp;year="
                    class="block" stat="more" w="1061"> <span class="title_text">日韩佳作</span> <span
                        class="link_more">更多<i class="more"></i></span></a></div>
            <div class="banner_s"><a href="/detail.php?tsid=185611" stat="70295" w="1061">
                    <div class="pic_info">
                        <div class="img lazy_bg"
                             data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150619/94189b70bbd9ea4b31b0cb120e096306.jpg_640x280.jpg?q=60"></div>
                    </div>
                </a>

                <div class="banner_s_desc"><strong style="background:#990033"> 追击者 </strong>
                    <span>当锤子铁钩进入妓女的身体，除了愤怒我们还能做什么</span>
                </div>
            </div>
                               <!-- 2列运营列表 -->
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=272397" stat="70183" w="1062" class="list_cont" title="呼吸">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150618/fe9ceb17bfa26cbd1f5f66221cf5c100.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.2</span></div>
                            </div>
                            <div class="title">呼吸<br><span class="desc">窒息的情欲，伦理的撕扯，张震饰演死囚徒</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=66890" stat="70111" w="1062" class="list_cont" title="七天">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150616/f6bf934f79fac67336c2297c38056951.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">9.0</span></div>
                            </div>
                            <div class="title">七天<br><span class="desc">两位母亲的心碎与复仇，萝莉被虐的心碎</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=64307" stat="66428" w="1062" class="list_cont" title="亲切的金子">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150611/148ce5181b29512dacddb01700964cfc.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">8.0</span></div>
                            </div>
                            <div class="title">亲切的金子<br><span class="desc">朴赞郁复仇三部曲，你一定看过&lt;老男孩&gt;</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=244132" stat="66255" w="1062" class="list_cont" title="医生">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150616/0eec6b3d7feb9ba89f2aca70fd60f89e.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.2</span></div>
                            </div>
                            <div class="title">医生<br><span class="desc">人造妻子家中偷情，丈夫在医院拿病人开刀</span></div>
                        </a></li>
                </ul>
            </div>
                               <!-- 图文bannner -->
            <div class="news_title"><a
                    href="http://v.m.liebao.cn/category.php?cat_id=1&amp;type=&amp;area=%E7%BE%8E%E5%9B%BD&amp;year="
                    class="block" stat="more" w="1059"> <span class="title_text">欧美大片</span> <span
                        class="link_more">更多<i class="more"></i></span></a></div>
            <div class="banner_s"><a href="/detail.php?tsid=251909" stat="70192" w="1059">
                    <div class="pic_info">
                        <div class="img lazy_bg"
                             data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150618/b9ac259aa8ac33643fa62280d4aba182.jpg_640x280.jpg?q=60"></div>
                    </div>
                </a>

                <div class="banner_s_desc"><strong style="background:#990033"> 云图 </strong>
                    <span>少年，我看你骨骼惊奇，看懂这部3个小时神片的重任就交给你了</span>
                </div>
            </div>
                               <!-- 2列运营列表 -->
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="/detail.php?tsid=273173" stat="70272" w="1060" class="list_cont" title="四十而惑">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150619/ff9a16a12d746f920f46c35bf74d3781.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">6.6</span></div>
                            </div>
                            <div class="title">四十而惑<br><span class="desc">父母渐渐衰老，丈夫依赖伟哥，生活真难</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=66556" stat="64211" w="1060" class="list_cont" title="风流老板俏秘书">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/edbdc227a980b89d41126bb169a9408b.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.4</span></div>
                            </div>
                            <div class="title">风流老板俏秘书<br><span class="desc">女孩办公室遭老板虐，事后爱上怪癖老板</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=273035" stat="70057" w="1060" class="list_cont" title="吾栖之肤">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/949d158d42f50396e00a9c28c6924304.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.5</span></div>
                            </div>
                            <div class="title">吾栖之肤<br><span class="desc">无敌重口新奇电影，让植物人怀孕，一部不能剧透的片子</span></div>
                        </a></li>
                    <li><a href="/detail.php?tsid=125559" stat="70062" w="1060" class="list_cont" title="末日侵袭">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150615/89d42d0f34c03ba6754e3b530e2da236.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <div class="img_layer layer_notext"><span class="score_left">7.8</span></div>
                            </div>
                            <div class="title">末日侵袭<br><span class="desc">一部酣畅淋漓的混乱元素流电影，就是什么都有</span></div>
                        </a></li>
                </ul>
            </div>
                               <!-- 2列运营列表 -->
            <div class="news_title"><span class="title_text">专题小分队</span></div>
            <div class="list_wrap">
                <ul class="list list_2col">
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1431000941.html" stat="70092" w="6005"
                           class="list_cont" title="漫改集中营">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150616/191bb588b0b13eb868a310c4dc07c7ab.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">漫改集中营<br><span class="desc">肾上腺爆炸了</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1430372457.html" stat="70088" w="6005"
                           class="list_cont" title="我的青春没那么作">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150616/e9a29e3135510f9c88c139c5140c8bcf.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">我的青春没那么作<br><span class="desc">青春片，求放过</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1428919000.html" stat="66404" w="6005"
                           class="list_cont" title="激燃" 火爆妞""="">
                        <div class="pic_info">
                            <div class="img lazy_bg"
                                 data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150611/cded7e7a4ac8d07cc8f18b2d3800dc88.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                            <i class="tip_purple" style="background:#FF0066">专题</i>

                            <div class="img_layer layer_notext"></div>
                        </div>
                        <div class="title">激燃"火爆妞"<br><span class="desc">悍女集中营，甚狠你妈知否？</span></div>
                        </a> </li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1429787503.html" stat="66399" w="6005"
                           class="list_cont" title="惊你一啪">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150611/48b52e4fb48dcf4399d89931540c8494.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">惊你一啪<br><span class="desc">下巴掉了，啪啪啪，啪啪啪</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1422867227.html" stat="63881" w="6005"
                           class="list_cont" title="不伦禁忌恋">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150525/c04bfd1e6ec51b91debd1f8469f421cc.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">不伦禁忌恋<br><span class="desc">错综复杂的混乱性关系</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1431339935.html" stat="65810" w="6005"
                           class="list_cont" title="聚焦金棕榈">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150602/16ec3fef23464693b65927964a54d479.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">聚焦金棕榈<br><span class="desc">戛纳国际电影节</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1428472751.html" stat="63885" w="6005"
                           class="list_cont" title="一见你就想笑">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150525/0084237eb2ba308428e62756492b3882.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">一见你就想笑<br><span class="desc">恶搞无下限</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1418192379.html" stat="63459" w="6005"
                           class="list_cont" title="所有深爱皆是秘密">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150518/18fd69d54bd6853dba19436a727dded7.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">所有深爱皆是秘密<br><span class="desc">如果爱，请深爱</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1418009875.html" stat="63677" w="6005"
                           class="list_cont" title="青春●怀旧系">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150521/92a387b54bafeaedbd01fac85e446b4e.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">青春●怀旧系<br><span class="desc">胎是一定要打的</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1412820934.html" stat="63679" w="6005"
                           class="list_cont" title="嗜血的梦想与荣耀">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150521/eb2392edc970469612dfdfdd7619ba39.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">嗜血的梦想与荣耀<br><span class="desc">信不信我砍死你？</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1433127422.html" stat="70458" w="6005"
                           class="list_cont" title="哆啦A梦：伴我同行">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/354f05febea09ce8b68bcae237f409a3.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">哆啦A梦：伴我同行<br><span class="desc">学会一个人长大</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1431605404.html" stat="70457" w="6005"
                           class="list_cont" title="诡异怪味道">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/a3473a5a70b339425d3aec054dc63ddb.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">诡异怪味道<br><span class="desc">荒诞到爆炸</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1434077615.html" stat="70456" w="6005"
                           class="list_cont" title="听说有人要盗墓">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/5ed94c931020e2a66796785aabcec7cd.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">听说有人要盗墓<br><span class="desc">作死就成全你</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1434679842.html" stat="70455" w="6005"
                           class="list_cont" title="欲望在骚动">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150623/e0fc3019b5a45c16b62d0cf2f9ea8722.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">欲望在骚动<br><span class="desc">填不平的欲望之沟</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1429612860.html" stat="65808" w="6005"
                           class="list_cont" title="百变一美">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150602/6a77c5f19374408a26deb09f0b469b18.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">百变一美<br><span class="desc"> 詹姆斯·麦卡沃伊专区</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1419473217.html" stat="64054" w="6005"
                           class="list_cont" title="2014大片TOP榜">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150527/1bdad476485a8205f2c27ac3cf294409.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">2014大片TOP榜<br><span class="desc">年度精选佳片</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1426128904.html" stat="63465" w="6005"
                           class="list_cont" title="做个有格调的坏人">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150518/1ea97923baa754e0dfe715315e846377.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">做个有格调的坏人<br><span class="desc">坏也要坏得有腔调</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1425359894.html" stat="63464" w="6005"
                           class="list_cont" title="公主复仇记">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150518/a5a563a2474e8c993fdd67507b03436a.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">公主复仇记<br><span class="desc">化身复仇女王</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1420609914.html" stat="63463" w="6005"
                           class="list_cont" title="天生变态狂">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150527/b065a07bb411f81e5e1c7e6b3c78536e.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">天生变态狂<br><span class="desc">人究竟能有多变态</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1419831571.html" stat="63457" w="6005"
                           class="list_cont" title="历年贺岁片大盘点 ">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150518/6aea8f1fc941b844ef06c7428ab10a74.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">历年贺岁片大盘点 <br><span class="desc">越来越贺岁</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1427422648.html" stat="63466" w="6005"
                           class="list_cont" title="特工合辑">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150518/0a24be31f17d68351b46be7613a39e0d.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">特工合辑<br><span class="desc">带着外挂来坑你</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1427163040.html" stat="64053" w="6005"
                           class="list_cont" title="第39届香港电影节">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150527/1dca4d650fa3be1c959b05ebf9504dae.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">第39届香港电影节<br><span class="desc">精彩相关影片</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1416823738.html" stat="63458" w="6005"
                           class="list_cont" title="菊花残…满腚伤！">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150518/0192ac441b5cb5134573a3eaa25b15d8.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">菊花残…满腚伤！<br><span class="desc">爆菊就是这么任性！</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1418812110.html" stat="63460" w="6005"
                           class="list_cont" title="我穿我穿我穿穿穿">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150518/6fe11b3b6a114a956be55261680b54b8.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">我穿我穿我穿穿穿<br><span class="desc">穿越未来，回到过去</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1420340306.html" stat="63461" w="6005"
                           class="list_cont" title="雷你没商量">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150518/18120cdd8eb7ac7bfc1cc6ca0ae57562.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">雷你没商量<br><span class="desc">劈死你就是目的</span></div>
                        </a></li>
                    <li><a href="http://v.m.liebao.cn/zhuanti/m_zhuanti_1420439467.html" stat="63462" w="6005"
                           class="list_cont" title="我最爱的电影插曲">
                            <div class="pic_info">
                                <div class="img lazy_bg"
                                     data-url="http://dh2.kimg.cn/kimg/v/m/upload/20150518/7f2c74489485a71c8afea263a0da1f2a.jpg_320x192.jpg?q=85&amp;mode=1"></div>
                                <i class="tip_purple" style="background:#FF0066">专题</i>

                                <div class="img_layer layer_notext"></div>
                            </div>
                            <div class="title">我最爱的电影插曲<br><span class="desc">因一首歌，爱上一部电影</span></div>
                        </a></li>
                </ul>
            </div>
        </div>
        <a id="lb_ad" href="http://c.ios.ijinshan.com/liebao.php?i=135" class="btn btn_yellow btn_block text_center"
           style="text-align:center;margin:15px 8px 0;height: 3em;line-height: 3em;white-space: nowrap;">打开猎豹浏览器，离线观看更多精彩大片</a>
    </div>
    <div class="list_box">
        <div class="condition">
            <div class="condition_title"><a href="javascript:;" stat="15804" w="ico_filter"
                                            class="ico_filter">筛选</a><span class="condition_text"> </span></div>
            <div class="condition_shape"></div>
            <div class="condition_con">
                <div class="condition_title"><span stat="15804" w="ico_filter" class="ico_filter">筛选</span><span
                        class="condition_text"> </span></div>
                <ul class="list_condition">
                    <li class="con_type"><a data-key=""
                                            href="category.php?cat_id=1&amp;type=&amp;page=1&amp;size=30&amp;area=&amp;year="
                                            class="">全部</a><a class="" data-key="动作"
                                                              href="category.php?cat_id=1&amp;type=%E5%8A%A8%E4%BD%9C&amp;page=1&amp;size=30&amp;area=&amp;year=">动作</a><a
                            class="" data-key="爱情"
                            href="category.php?cat_id=1&amp;type=%E7%88%B1%E6%83%85&amp;page=1&amp;size=30&amp;area=&amp;year=">爱情</a><a
                            class="" data-key="剧情"
                            href="category.php?cat_id=1&amp;type=%E5%89%A7%E6%83%85&amp;page=1&amp;size=30&amp;area=&amp;year=">剧情</a><a
                            class="" data-key="喜剧"
                            href="category.php?cat_id=1&amp;type=%E5%96%9C%E5%89%A7&amp;page=1&amp;size=30&amp;area=&amp;year=">喜剧</a><a
                            class="" data-key="恐怖"
                            href="category.php?cat_id=1&amp;type=%E6%81%90%E6%80%96&amp;page=1&amp;size=30&amp;area=&amp;year=">恐怖</a><a
                            class="" data-key="悬疑"
                            href="category.php?cat_id=1&amp;type=%E6%82%AC%E7%96%91&amp;page=1&amp;size=30&amp;area=&amp;year=">悬疑</a><a
                            class="" data-key="科幻"
                            href="category.php?cat_id=1&amp;type=%E7%A7%91%E5%B9%BB&amp;page=1&amp;size=30&amp;area=&amp;year=">科幻</a><a
                            class="" data-key="战争"
                            href="category.php?cat_id=1&amp;type=%E6%88%98%E4%BA%89&amp;page=1&amp;size=30&amp;area=&amp;year=">战争</a><a
                            class="" data-key="历史"
                            href="category.php?cat_id=1&amp;type=%E5%8E%86%E5%8F%B2&amp;page=1&amp;size=30&amp;area=&amp;year=">历史</a><a
                            class="" data-key="武侠"
                            href="category.php?cat_id=1&amp;type=%E6%AD%A6%E4%BE%A0&amp;page=1&amp;size=30&amp;area=&amp;year=">武侠</a><a
                            class="" data-key="伦理"
                            href="category.php?cat_id=1&amp;type=%E4%BC%A6%E7%90%86&amp;page=1&amp;size=30&amp;area=&amp;year=">伦理</a><a
                            class="" data-key="偶像"
                            href="category.php?cat_id=1&amp;type=%E5%81%B6%E5%83%8F&amp;page=1&amp;size=30&amp;area=&amp;year=">偶像</a><a
                            class="" data-key="警匪"
                            href="category.php?cat_id=1&amp;type=%E8%AD%A6%E5%8C%AA&amp;page=1&amp;size=30&amp;area=&amp;year=">警匪</a><a
                            class="" data-key="灾难"
                            href="category.php?cat_id=1&amp;type=%E7%81%BE%E9%9A%BE&amp;page=1&amp;size=30&amp;area=&amp;year=">灾难</a><a
                            class="" data-key="神话"
                            href="category.php?cat_id=1&amp;type=%E7%A5%9E%E8%AF%9D&amp;page=1&amp;size=30&amp;area=&amp;year=">神话</a><a
                            class="" data-key="其他"
                            href="category.php?cat_id=1&amp;type=%E5%85%B6%E4%BB%96&amp;page=1&amp;size=30&amp;area=&amp;year=">其他</a>
                    </li>
                    <li class="con_area"><a data-key=""
                                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year="
                                            class="cur">全部</a><a class="" data-key="内地"
                                                                 href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=%E5%86%85%E5%9C%B0&amp;year=">内地</a><a
                            class="" data-key="香港"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=%E9%A6%99%E6%B8%AF&amp;year=">香港</a><a
                            class="" data-key="台湾"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=%E5%8F%B0%E6%B9%BE&amp;year=">台湾</a><a
                            class="" data-key="美国"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=%E7%BE%8E%E5%9B%BD&amp;year=">美国</a><a
                            class="" data-key="日本"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=%E6%97%A5%E6%9C%AC&amp;year=">日本</a><a
                            class="" data-key="韩国"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=%E9%9F%A9%E5%9B%BD&amp;year=">韩国</a><a
                            class="" data-key="印度"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=%E5%8D%B0%E5%BA%A6&amp;year=">印度</a><a
                            class="" data-key="泰国"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=%E6%B3%B0%E5%9B%BD&amp;year=">泰国</a><a
                            class="" data-key="欧洲"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=%E6%AC%A7%E6%B4%B2&amp;year=">欧洲</a><a
                            class="" data-key="其他"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=%E5%85%B6%E4%BB%96&amp;year=">其他</a>
                    </li>
                    <li class="con_year"><a data-key=""
                                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year="
                                            class="cur">不限</a><a class="" data-key="2015"
                                                                 href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2015">2015</a><a
                            class="" data-key="2014"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2014">2014</a><a
                            class="" data-key="2013"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2013">2013</a><a
                            class="" data-key="2012"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2012">2012</a><a
                            class="" data-key="2011"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2011">2011</a><a
                            class="" data-key="2010"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2010">2010</a><a
                            class="" data-key="2009"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2009">2009</a><a
                            class="" data-key="2008"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2008">2008</a><a
                            class="" data-key="2007"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2007">2007</a><a
                            class="" data-key="2006"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2006">2006</a><a
                            class="" data-key="2005"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2005">2005</a><a
                            class="" data-key="2004"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2004">2004</a><a
                            class="" data-key="2003"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2003">2003</a><a
                            class="" data-key="2002"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2002">2002</a><a
                            class="" data-key="2001"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2001">2001</a><a
                            class="" data-key="2000"
                            href="category.php?cat_id=1&amp;type=recommend&amp;page=1&amp;size=30&amp;area=&amp;year=2000">2000</a>
                    </li>
                </ul>
                <div class="condition_btns"><span class="btn_cancel">取消</span><span class="btn_sure" w="filter"
                                                                                    stat="filter_btn">确定</span>
                </div>
            </div>
        </div>
        <div class="blank_tips" style=""><p>没有找到相关视频，请重试！</p></div>
        <div class="list_wrap">
            <div class="rec_title">推荐观看&nbsp;&nbsp;<span class="rec_text"></span></div>
            <ul class="list"></ul>
            <div class="loadmore nomore" id="loadmore">没有更多了</div>
        </div>
    </div>
</div>
