<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">资源列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加资源</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td">
				<input type="text" class="input wb" name="name" value="<?php echo $search['name'];?>"/>
			</td>
			<th class="th">状态</th>
			<td class="td">
				<select class="wa" name="status">
					<option <?php if ($search['status'] != null && $search['status'] == 1) echo 'selected';?> value="1">开启</option>
					<option <?php if ($search['status'] != null && $search['status'] == 0) echo 'selected';?> value="0">关闭</option>
				</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">排序</td>
			<td>名称</td>
			<td>图标</td>
			<td>下载链接</td>
			<td>版本</td>
			<td>状态</td>
			<td>点击量</td>
			<td>操作</td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><?php echo $value['name'];?></td>
			<td><img src="<?php echo $attachPath,$value['icon'];?>" /></td>
			<td><?php echo $value['link'];?></td>
			<td><?php echo $value['version'];?></td>
			<td><?php echo $value['status'] == 1 ? '开启' : '关闭';?></td>
			<td><?php echo $value['hits'];?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
