<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">消息日志列表</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td>消息id</td>
			<td>Rid</td>
			<td>发送时间</td>
			<td width="200">状态</td>
		</tr>
<?php foreach($logs as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['msg_id'];?></td>
			<td><?php echo $value['rid'];?></td>
			<td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
			<td><?php echo $value['status'] == 1 ? '成功' : '失败';?></td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
