
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<title>我的金币</title>
<link rel="stylesheet" type="text/css" href="<?php echo $staticResPath;?>/call/css/style.min.css" />
</head>

<body id="page-order" class="ui-app">

<div class="ui-top-bar">
	<a class="ui-pos icon-back" href="<?php echo empty($refurl) ? $webroot.'/user/index/index':$refurl;?>"></a>
	<span class="ui-top-txt">我的金币</span>
	<!-- <a class="ui-pos icon-menu" href="#"></a> -->
</div>

<div class="ui-page page1 js-active">
	<div class="ui-page-content">
		<div class="ui-box">
			<ul class="ui-box-info">
				<li><span class="span-jifen">当前金币：<b><?php echo $scoreInfo['remained_score'] ?$scoreInfo['remained_score']: 0;?></b><em class="icon-gold"></em></span></li>
				<li>
					<span class="span-jifen">总获取金币：<b><?php echo $scoreInfo['total_score'] ?$scoreInfo['total_score']: 0;?></b><em class="icon-gold"></em></span>
					<span class="span-jifen">总消耗金币：<b><?php echo $scoreInfo['total_score']? ($scoreInfo['total_score']- $scoreInfo['remained_score'] ):0;?></b><em class="icon-gold"></em></span>
				</li>
			</ul>
		</div>
		<div class="ui-box">
			<div class="ui-caption">账单明细</div>
		</div>
		<!-- 看图任务列表 START-->
		<div class="ui-box">
			<div class="ui-box-nav">
				<ul class="ui-groupbutton">
					<li class="ui-button js-active" data-toggle="tab" data-target="#page1-tab1" aria-controls="tab1" data-index="1" role="tab" data-url="<?php echo $weroot;?>/user/center/ajaxscore">金币明细</li>
					<li class="ui-button" data-toggle="tab" data-target="#page1-tab2" aria-controls="tab1" data-index="2" role="tab" data-url="<?php echo $weroot;?>/user/center/ajaxscore?type=1">获取历史</li>
					<li class="ui-button" data-toggle="tab" data-target="#page1-tab3" aria-controls="tab1" data-index="3" role="tab" data-url="<?php echo $weroot;?>/user/center/ajaxscore?type=2">消耗历史</li>
				</ul>
			</div>
			<div id="page1-tab1" class="ui-tab js-active" role="tabpanel">
				<ul class="ui-log-list">
					<?php foreach ($data['mix']['data'] as $k=>$v){?>
					<li>
						<span><?php echo $actions[$v['score_type']];?></span>
						<span><?php echo $v['affected_score'];?></span>
						<span><?php echo date('m月d日',$v['add_time'])?></span>
					</li>
					<?php }?>		
				</ul>
				<?php if($data['mix']['count'] >$pageSize){?>
						<div class="ui-loading">上拉加载</div>
				<?php }?>
			</div>
			<div id="page1-tab2" class="ui-tab" role="tabpanel" >
				<ul class="ui-log-list">
				<?php foreach($data['incre']['data'] as $k=>$v){?>
					<li>
						<span><?php echo $actions[$v['score_type']];?></span>
						<span><?php echo $v['affected_score'];?></span>
						<span><?php echo date('m月d日',$v['add_time'])?></span>
					</li>
					<?php }?>				
				</ul>
				<?php if($data['incre']['count'] >$pageSize){?>
						<div class="ui-loading">上拉加载</div>
				<?php }?>
			</div>
			<div id="page1-tab3" class="ui-tab" role="tabpanel">
				<ul class="ui-log-list">
				<?php foreach ($data['desc']['data'] as $k=>$v){?>
					<li>
						<span><?php echo $actions[$v['score_type']]?$actions[$v['score_type']]:'---';?></span>
						<span><?php echo $v['affected_score'];?></span>
						<span><?php echo date('m月d日',$v['add_time'])?></span>
					</li>
				<?php }?>				
				</ul>
				<?php if($data['desc']['count'] >$pageSize){?>
						<div class="ui-loading">上拉加载</div>
				<?php }?>
			</div>
		</div>
		<!-- 看图任务列表 END-->
	</div>
</div>

<script type="text/javascript">
	var token = "<?php echo $token;?>";
	var url = '<?php echo $webroot?>/user/center/score';
</script>
<script id="main" data-baseurl="<?php echo $staticResPath;?>/call/js" data-version="<?php echo $version;?>" src="<?php echo $staticResPath;?>/call/js/lib/require.js?v=<?php echo $version;?>"></script>
<script>
    require(['<?php echo $staticResPath;?>/call/js/common.js?v=<?php echo $version;?>'],function(){
        require(['page/main']);
    });
</script>

</body>
</html>