<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li class="current"><a href="<?php echo $listUrl; ?>">接口列表</a></li>
		<li><a href="<?php echo $editUrl.'?cp_id='.$cpId; ?>">添加接口</a></li>
		<li><a href="<?php echo $exportUrl; ?>">导出</a></li>
		<li><a href="<?php echo $importUrl; ?>">导入</a></li>
	</ul>
</div>


<div class="table_full">
	<table width="100%">
		<tbody>
		<tr class="tr">
			<th class="th" style="width: 40px;">CP:</th>
			<td>
				<select id="cp_id" name="cp_id" onchange="to_cp_list(this.value)">
					<?php
					foreach ($cpcate as $key => $val){
						$selected = '';
						if ($key == $cpId) {
							$selected = ' selected ';
						}
						echo "<option value=\"{$key}\" {$selected}>{$val[0]}</option>";
					}
					?>
				</select>
			</td>
		</tr>
		</tbody>
	</table>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="40">编号</td>
			<td width="120">CP接口名称</td>
			<td width="100">栏目名称</td>
			<td width="60">分类</td>
			<td>数据抓取地址</td>
			<td width="80">URL_IID</td>
			<td width="100">最后访问时间</td>
			<td width="80">操作</td>
		</tr>
		<?php foreach ($list as $value) { ?>
			<tr class="ct">
				<td><?php echo $value['id']; ?></td>
				<td><?php echo $value['title']; ?></td>
				<td><?php echo $value['resume']; ?></td>
				<td><?php echo $value['type']; ?></td>
				<td><?php echo $value['url'] ?></td>
				<td><?php echo $value['url_iid'] ?><br>数量:<?php echo $value['stats'][0]; ?></td>
				<td>
					<a href="javascript:" onclick="verify(<?php echo $value['id']; ?>)"><?php echo Common::tranTime($value['last_time']); ?></a>
					<br>
					<?php echo Common::tranTime($value['stats'][1]); ?>
				</td>
				<td>
					<a href="javascript:" onclick="parse(<?php echo $value['id']; ?>)">抓取</a>
					<a href="<?php echo $editUrl; ?>/?id=<?php echo $value['id']; ?>" class="mr10">编辑</a>
					<?php if ($value['id'] != 1): ?>
						<a href="javascript:"
						   onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
					<?php endif; ?>
				</td>
			</tr>
		<?php } ?>
	</table>

</div>

<script type="text/javascript">
	function to_cp_list(id) {
		var url = "<?php echo $listUrl;?>?cp_id=" + id;
		window.location.href=url; // 跳转
	}

	function verify(id) {
		$.getJSON(baseurl + "<?php echo $verifyUrl;?>/?id=" + id, function (ret) {
			// alert(ret.msg);
			showMsg('', ret.msg);
		})
	}

	function parse(id) {
		$.getJSON(baseurl + "<?php echo $parseUrl;?>/?id=" + id, function (ret) {
			// alert(ret.msg);
			showMsg('', ret.msg);

		})
	}
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
