<?php echo $this->render("layout/header.phtml"); ?>
	<div class="h_a">规则说明：</div>
	<form method="post" action="/Admin/Uprivilege/ruleEdit" id="addFrom">
		<input name="token" id="token" value="<?php echo $token; ?>" type="hidden"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">文字内容</th>
					<td class="td">
						<textarea rows="6" cols="10" name="user_index_rule" style="width: 600px; height:400px;"><?php echo $content; ?></textarea>
					</td>
				</tr>
			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
	</form>
	<script src="<?php echo $staticPath; ?>/js/admin/kindeditor/kindeditor.js"></script>
	<script type="text/javascript">
		//广告表单数据提交
		$(document).ready(function () {

			var editor;
			KindEditor.ready(function (K) {
				K.token = $('#token').val();
				editor = K.create('textarea[name="user_index_rule"]', {
					resizeType: 1,
					allowPreviewEmoticons: false,
					allowImageUpload: true,
					uploadJson: '<?php echo $uploadImgUrl;?>',
					items: EDITOR_ITEMS
				});
			});

			ajaxForm('addFrom', function (ret) {
				ajaxRedirect(ret, baseurl + '/Admin/Uprivilege/rule');
			}, function () {
				editor.sync();
			});
		})
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>