<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $indexUrl;?>?channel_id=<?php echo $info['channel_id'];?>">渠道列表</a></li>
    <li class="current"><a href="javascript:;">编辑渠道</a></li>
	</ul>
</div>
<div class="h_a">编辑渠道</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="editForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input wb" name="sort" value="<?php echo $info['sort'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">分类</th>
			<td class="td"><select name="type_id">
			<?php foreach ($types as $key=>$value) { ?>
					<option <?php echo ($info['type_id'] == $key) ? 'selected="selected"' : '';?> value="<?php echo $key;?>"><?php echo $value;?></option>
			<?php } ?>
			</select></td>
		</tr>	
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input wc" name="name" value="<?php echo $info['name'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">颜色</th>
			<td class="td">
				<input type="text" class="input" name="color" value="<?php echo $info['color'];?>">(填写颜色值，如:红色（#e54d4b）蓝色(#3851bb), 不填写则显示为默认颜色)
			</td>
		</tr>
		<tr class="tr">
			<th class="th">链接</th>
			<td class="td"><textarea type="text" class="input wc" name="link"><?php echo $info['link'];?></textarea></td>
		</tr>
		<tr class="tr">
			<th class="th">模块-平台</th>
			<td class="td">
				<select name="module_id">
					<option value="">选择模块</option>
					<?php foreach($modules as $key=>$value) { ?>
					<option value="<?php echo $value['id'];?>" <?php if($info['module_id'] == $value['id']) echo  'selected="selected"';?>><?php echo $value['name'];?></option>
					<?php }?>
				</select>
				
				<select name="cid">
					<option value="">选择平台</option>
					<?php foreach($channel_names as $key=>$value) { ?>
					<option value="<?php echo $value['id'];?>" <?php if($info['cid'] == $value['id']) echo  'selected="selected"';?>><?php echo $value['name'];?></option>
					<?php }?>
				</select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">渠道号</th>
			<td class="td"><input type="text" class="input" name="channel_code" value="<?php echo $info['channel_code'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg">
						<img src="<?php echo $attachPath.$info['img'];?>"/>
						<input type="hidden" name="img" value="<?php echo $info['img'];?>">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
				<select class="wa" name="status">
					<option <?php if($info['status'] == 1) echo 'selected';?> value="1">开启</option>
					<option <?php if($info['status'] == 0) echo 'selected';?> value="0">关闭</option>
				</select> 
			</td>
		</tr>
		<tr class="tr">
			<th class="th">开始结束时间</th>
			<td class="td"><div><input class="input" type="text" style="width:143px;" id="start_time" name="start_time" value="<?php echo date('Y-m-d H:i:s', $info['start_time']);?>" /> 至 <input class="input" type="text" style="width:143px;" id="end_time" name="end_time" value="<?php echo date('Y-m-d H:i:s', $info['end_time']);?>" /></div>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	$('#start_time').datetimepicker();
    $('#end_time').datetimepicker();
	ajaxForm('editForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Channel/index?s=1&channel_id=<?php echo $info['$channel_id'];?>');
	});
})

</script>
<?php echo $this->render("layout/footer.phtml");?>
