<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>?channel_id=<?php echo $search['channel_id'];?>">渠道列表</a></li>
		<li><a href="<?php echo $addUrl;?>?channel_id=<?php echo $search['channel_id'];?>">添加渠道</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>?channel_id=<?php echo $search['channel_id'];?>" method="post">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	<div class="table_full">
		<table width="100%">
		<tr class="tr">
				<th class="th">分类</th>
				<td class="td">
				<select name="type_id">
				<option value="">所有分类</option>
<?php foreach($types as $key => $value) {?>
                <option <?php echo ($search['type_id'] == $key) ? 'selected="selected"' : '';?> value="<?php echo $key;?>"><?php echo $value;?></option>
<?php }?>
	            </select>
				</td>
			<th class="th">标题</th>
            <td class="td">
                <input class="input" type="text" name="name" value="<?php echo $search['name'];?>">
            </td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button type="submit">搜 索</button></span></span>
	</div>
</form>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="action" id="action" type="hidden" value="" />
<div class="h_a">
	<span class="btn2"><span><button onclick="$('#action').val('sort');" type="submit">重新排序</button></span></span>
	<span class="btn2"><span><button onclick="$('#action').val('close');" type="submit">关闭</button></span></span>
	<span class="btn2"><span><button onclick="$('#action').val('open');" type="submit">开启</button></span></span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		<td><input type="checkbox" onclick="checkAll('.checkbox')"></td>
			<td width="100">排序</td>
			<td width="200">渠道名称</td>
			<td width="100">分类</td>
			<td width="100">图标</td>
			<td width="100">状态</td>
			<td width="200">开始时间</td>
			<td width="200">结束时间</td>
			<td width="100">渠道号</td>
			<td width="160">操作</td>
		</tr>
<?php foreach($channels as $key => $value) {
list($module_id, $channel_id) = explode("_", $value['module_channel']);
?>
		<tr class="ct">
		    <td><input class="checkbox" name="ids[]" value="<?php echo $value['id'];?>" type="checkbox"></td>
			<td><input type="text" class="input" style="width:30px" name="sort[<?php echo $value['id'];?>]" value="<?php echo $value['sort'];?>"></td>
			<td><a href="<?php echo $value['link'];?>" target="_blank"><?php echo $value['name'];?></a></td>
			<td><?php echo $types[$value['type_id']];?></td>
			<td><img src="<?php echo $attachPath,$value['img'];?>" width=52/></td>
			<td><?php echo $value['status'] ? '开启':'关闭';?></td>
			<td><?php echo date('Y-m-d H:i:s', $value['start_time']);?></td>
	        <td><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
	        <td><?php echo $value['channel_code'];?></td>
            <td>
            <a href="/admin/stat/thirdpart?3&version_id=<?php echo $search['channel_id'];?>&module_id=<?php echo $module_id;?>&channel_id=<?php echo $channel_id;?>&item_id=<?php echo $value['id'];?>" target="_blank">点击量</a>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
		<?php foreach($value['items'] as $k => $val) {?>
		<tr class="ct">
			<td><?php echo $val['sort'];?></td>
			<td><?php echo $value['id'];?></td>
			<td>|—<?php echo $val['name'];?></td>
			<td><?php echo str_replace('=', '', Common::encrypt($val['id']));?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $val['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $val['id'];?>', '', event);">删除</a>
			</td>
		</tr>
		<?php foreach($val['items'] as $keys => $v) {?>
		<tr class="ct">
			<td><?php echo $v['sort'];?></td>
			<td><?php echo $value['id'];?></td>
			<td>|— —<?php echo $v['name'];?></td>
			<td><?php echo str_replace('=', '', Common::encrypt($v['id']));?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $v['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $v['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php }}} ?>
	</table>
</div>
</form>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Channel/index?s=1&channel_id=<?php echo $search['channel_id'];?>');
	});
	
});
</script>
<?php echo $this->render("layout/footer.phtml");?>
