<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class="current">
				<a href="<?php echo $seriesListUrl; ?>">数据列表</a>
			</li>
			<li><a href="<?php echo $seriesEditUrl; ?>">添加数据</a></li>
		</ul>
	</div>

	<div class="table_list">
		<table width="100%">
			<tr class="hd">
				<td width="50">ID</td>
				<td width="100">产品系列</td>
				<td width="200">参数</td>
				<td width="50">品牌</td>
				<td width="100">操作</td>
			</tr>
			<?php foreach ($list as $key => $value) { ?>
				<tr class="ct">
					<td><?php echo $value['id']; ?></td>
					<td><?php echo $value['name']; ?></td>
					<td><?php echo $value['value']; ?></td>
					<td><?php echo $brand[$value['brand_id']]; ?></td>
					<td>
						<a href="<?php echo $seriesEditUrl; ?>/?id=<?php echo $value['id']; ?>" class="mr10">编辑</a>
						<a href="javascript:" onclick="deleteOne('<?php echo $seriesDelUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
					</td>
				</tr>
			<?php } ?>
		</table>
	</div>
	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>
<?php echo $this->render("layout/footer.phtml"); ?>