<?php echo $this->render("common/navigator.phtml"); ?>

<style type="text/css">
    .pre_publish{
        background-color: #E5E5E5;
    }
</style>
<!-- 导航栏Ajax加载 指向navagator.html  menuOn表示分别需要高亮的菜单栏id 用下划线_隔开 eg:bz_taotu_taotuPack-->
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <!-- wp01-壁纸详情-->
    <div id="bz_admin_wp01">
        <!-- 页面内容区域 注意：每个页面无论是否有内容 必定有一个content-->
        <div class="content">
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">一级标签</label>
                    <div class="tb_cont tb_cell">
                        <ul class="tag_list tag_one"><!-- tag_one 一级标签 只能选中一个 -->
                            <a href="/Admin/wallpaperadmin/index">
                                <li value="0" class="<?php if (!$tid) echo 'on'; ?>">全部</li>
                            </a>
                            <?php foreach ($targ as $v) { ?>
                                <a href="/Admin/wallpaperadmin/index?tid=<?php echo $v['w_type_id'] ?>">
                                    <li value="<?php echo $v['w_type_id']; ?>" class="<?php if ($v['w_type_id'] == $tid) echo 'on'; ?>"><?php echo $v["w_type_name"] ?></li>
                                </a>
                            <?php } ?>
                        </ul>

                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">二级标签</label>
                    <div class="tb_cont tb_cell">
                        <ul class="tag_list tag_two">
                            <?php foreach ($sedtype as $v) { ?>
                                <li val="<?php echo $v['w_subtype_id'] ?>"
                                    class="<?php
                                    if (in_array($v['w_subtype_id'], $selectsedIds)) {
                                        echo 'on';
                                    }
                                    ?>"
                                    >
                                        <?php echo $v['w_subtype_name']; ?>
                                </li>
                            <?php } ?>

                        </ul>

                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">搜索:</label>
                    <div class="tb_cont tb_cell">
                        <input type="text" style="width:350px;" class="rd_1 search_name" value="<?php echo $search ?>">
                        <button class="btn_s2 search_btn">搜索壁纸</button>
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">状态</label>
                    <div class="tb_cont tb_cell">
                            <ul class="tag_list select_stu">
                                <?php foreach ($status as $k => $v) { ?>
                                    <li val="<?php echo $k; ?>" <?php if($selectstatus == $k){ echo 'class="on"'; }?>><?php echo $v; ?></li>
                                <?php } ?>
                            </ul>
                    </div>
                    <div class="tb_cell">
                        <ul class="tb_switch">
                            <!-- <li class="txt_switch">批量管理</li>
                             <li class="btn_switch switch_pics" openId="viewPics">宫格</li><!-- openId 表示点击时 显示哪个id下的内容 -->
                            <li class="btn_switch switch_list on" openId="viewList">列表</li>
                        </ul>
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->


            <!-- 宫格模式 admin_mode显示各子项目的管理按钮-->
            <section class="view view_pics " id="viewPics">
                <!-- 批量管理内容 默认隐藏 -->
                <div class="view_admin view_pics_admin">
                    <!-- checkClass表示 点击后 哪些class要被选中 -->
                    <button class="btn_check btn_check_all" checkClass="btn_check_pics"></button><label>全选</label><span class="btn btn_s1 pack_del">批量删除</span>
                </div>
                <h1 class="block_name">全部壁纸</h1>
                <ul class="view_pics_wrap "><!--  -->
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>

                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>


                </ul>
                <div class="clear-fix"></div>
            </section>

            <!-- 列表模式 -->
            <section class="view view_list show" id="viewList">
                <!-- 批量管理内容 默认隐藏 -->
                <div class="view_admin view_list_admin">
                    <!-- checkClass表示 点击后 哪些class要被选中 -->
                    <button class="btn_check btn_check_all" checkClass="btn_check_list"></button><label>全选</label><span class="btn btn_s1 pack_approve">批量通过</span><span class="btn btn_s1 pack_del">批量删除</span>
                </div>
                <table class="view_list_tb">
                    <thead>
                        <tr><th>壁纸</th><th>名称</th>
                            <th>大小</th>
                            <th>作者</th>
                            <th>一级标签</th>
                            <th>二级标签</th><th>上传时间</th>
                            <th>上架时间</th><th>分辨率</th><th>下载量</th><th>操作</th>
                            <th>状态</th>
                            <th>上下架</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php foreach ($wallpaper as $v) { ?>
                            <tr class="<?php if (strtotime($v['wallpaper_online_time']) > time()) echo 'pre_publish'; ?>">
                                <td><button class="btn_check btn_check_list"></button>
                                    <img src="<?php echo $v['url'] ?>" val="<?php echo $v['wallpaper_path'] ?>" class="tb_cell_img pop_btn prev_btn" openPopId="fixPicView" style="height:auto;width:7rem;">
                                </td>
                                <td><?php echo $v['wallpaper_name'] ?></td>
                                <td><?php echo sprintf("%.1f", $v['wallpaper_size'] / 1000) . "KB" ?></td>
                                <td><?php echo $v['user_name'] ?></td>
                                <td><?php echo $linetarg[$v['wallpaper_type']]['w_type_name'] ?></td>
                                <td>

                                    <?php
                                    foreach ($sedidxwallpaper[$v['wallpaper_id']] as $tar) {
                                        echo $sedtype[$tar]['w_subtype_name'] . "<br/>";
                                    }
                                    ?>
                                </td>
                                <td><?php if ($v['wallpaper_updatetime']) echo date("Y-m-d", $v['wallpaper_updatetime']); ?></td>

                                <td><?php if ($v['wallpaper_online_time']) echo $v['wallpaper_online_time']; ?></td>

                                <td><?php echo $v['wallpaper_width'] . "X" . $v["wallpaper_height"] ?></td>
                                <td><?php echo $v['wallpaper_down_count'] ?></td>
                                <td><a class="btn_txt"
                                       href="/Admin/wallpaperadmin/indexedit?wid=<?php echo $v['wallpaper_id'] ?>&page=<?php echo $page ?>">编辑</a>
                                    <a val="<?php echo $v['wallpaper_id'] ?>" class="btn_txt pop_btn delBtn" openPopId="fixTipView">删除</a></td>
                                <td val="<?php echo $v['wallpaper_status'] ?>"><?php echo $status[$v['wallpaper_status']] ?></td>
                                <td>
                                    <div class="select_box">
                                        <label class="select_val" val="<?php echo $v['wallpaper_status'] ?>"><?php echo $status[$v['wallpaper_status']] ?></label>
                                        <ul class="select_option ch_status" sid="<?php echo $v['wallpaper_id'] ?>">

                                            <?php if ($userinfo['groupid'] == 3) { ?>
                                                <li val="4">已上线</li>
                                                <li val="1">已提交</li>
                                                <li val="5">已下线</li>
                                            <?php } if ($userinfo['groupid'] == 2) { ?>
                                                <li val="2">未通过</li>
                                                <li val="3">已通过</li>
                                            <?php } ?>
                                        </ul>
                                    </div><!-- select_box end-->
                                </td>

                            </tr>


                        <?php } ?>


                    </tbody>
                </table>
            </section>

            <!-- 分页模块 -->
            <?php echo $this->render("common/pageshow.phtml"); ?>

        </div><!-- content end -->

    </div>
</section>

<!-- 弹窗 消息+按钮-->
<div class="pop_wraper" id="fixTipView">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_tip">
                    <p class="tip_mes">是否删除壁纸<span></span></p>
                    <div class="tip_btns"><button class="btn_s2 del_ok">确定</button>
                        <button class="btn_s2 btnCancel">取消</button></div>
                    <div class="pop_close"></div>
                </div>
            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->


<div class="pop_wraper pop_style_img" id="fixPicView">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_img">
                    <div class="pop_img_src"><img src=""/></div>
                    <div class="pop_close"></div>
                </div>

            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->

<script type="text/javascript">
    $(function () {
        $(".delBtn").click(function () {
            var wallpaperid = $(this).attr("val");
            $(".del_ok").click(function () {
                var data = "wall_id=" + wallpaperid + "&token=" + token;
                var url = "/Admin/Wallpaperadmin/delwallpaper"

                $(".pop_wraper").removeClass("show");
                $.post(url, data, function (d) {
                    if (d == 1) {
                        // window.location.href = "/Admin/Wallpaperadmin/index";
                        location.reload()
                    }
                });


            })
        });

        $(".prev_btn").click(function () {
            var img = $(this).attr("val");
            $(".pop_img_src >img").attr("src", img);
        });

        $(".search_btn").on("click", function () {
            var name = $(".search_name").val();
            window.location.href = "/Admin/wallpaperadmin/index?search=" + name;
        });

        $(".tag_two >li").click(function () {
            var ids = $(".tag_two>li").filter(".on").map(function () {
                return $(this).attr("val");
            }).get().join("_");

            var id = $(".tag_one>a").find("li.on").attr("value");
            var data = "ids=" + ids + "&tid=" + id + "&token=" + token;
            var url = "/Admin/wallpaperadmin/index?" + data;
            window.location.href = url;
        });

        $(".select_stu >li").click(function () {
            var status = $(this).attr("val");
            var data = "status=" + status;

            window.location.href = "/Admin/wallpaperadmin/index?" + data;
        })

        $(".ch_status >li ").click(function () {
            var liveid = $(this).parent().attr("sid");
            var status = $(this).attr("val");
            var data = "id=" + liveid + "&status=" + status + "&token=" + token


            var url = "/Admin/Wallpaperadmin/updateStatusWallpaper";
            // if (confirm("你确定要修改该资源的状态?")) {
            $.post(url, data, function (res) {
                if (res) {
                    history.go(0);
                }
            })
            // }

        });


    })
</script>
</body>
</html>