<?php echo $this->render("common/navigator.phtml"); ?>
<link href="<?php echo $staticPath ?>jssdk/plugins/datepicker/laydate.css" rel="stylesheet" type="text/css">

<script type="text/javascript"
src="<?php echo $staticPath ?>jssdk/plugins/datepicker/laydate.js"></script>
<!-- 导航栏Ajax加载 指向navagator.html  menuOn表示分别需要高亮的菜单栏id 用下划线_隔开 eg:bz_taotu_taotuPack-->

<section class="navigator" menuOn="bz_zy">

</section>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <!--wp02-壁纸编辑-->
    <div id="bz_admin_wp02">
        <!-- 页面内容区域 注意：每个页面无论是否有内容 必定有一个content-->
        <div class="content">
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">壁纸名称</label>
                    <div class="tb_cont tb_cell">
                        <input type="hidden" class="rd_1 wallpaperid" value="<?php echo $wallpaperinfo['wallpaper_id'] ?>">

                        <input type="text" class="rd_1 wallpapername" value="<?php echo $wallpaperinfo['wallpaper_name'] ?>">
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->

            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">预览图</label>
                    <!-- openPopId表示要打开指定id的弹窗 -->
                    <div class="tb_cont tb_cell">
                        <a>
                            <img src="<?php echo $wallpaperinfo['url'] ?>" class="tb_cell_img pop_btn" openPopId="fixPicView">
                        </a>
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->

            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">一级标签</label>
                    <div class="tb_cont tb_cell">
                        <div class="select_box">
                            <label class="select_val maintarg" val="<?php echo $wallpaperinfo['wallpaper_type'] ?>"><?php echo $linetarg[$wallpaperinfo['wallpaper_type']]["w_type_name"] ?></label>
                            <ul class="select_option">
                                <?php foreach ($targs as $v) { ?>
                                    <li val="<?php echo $v['w_type_id'] ?>"><?php echo $v["w_type_name"] ?></li>
                                <?php } ?>

                            </ul>
                        </div><!-- select_box -->
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->

            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell align_top">二级标签</label>
                    <div class="tb_cont tb_cell">
                        <ul class="tag_add_wrap selected_subtargs">
                            <?php foreach ($wallpaper_sub_targName as $v) { ?>
                                <li class="btn_tag" subid="<?php echo $v['w_subtype_id'] ?>"><span><?php echo $v['w_subtype_name'] ?></span><i class="tag_del"></i></li>
                            <?php } ?>

                           <!-- <li class="btn_tag" ><span>美女</span><i class="tag_del"></i></li>-->


                            <li class="btn_tag_add pop_btn" openPopId="fixTagView"><span>+</span></li>
                        </ul>
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->

            <div class="com_tb_wrap no_border">
                <div class="com_tb">
                    <label class="tb_cell">审核结果</label>
                    <div class="tb_cont tb_cell">
                        <div class="select_box">
                            <label class="select_val check_data" val="<?php echo $wallpaperinfo['wallpaper_status'] ?>"><?php echo $status[$wallpaperinfo['wallpaper_status']] ?></label>
                            <ul class="select_option" id="wp02Approve">
                                <?php foreach ($selstatus as $k => $v) { ?>
                                    <li val="<?php echo $k; ?>"><?php echo $v; ?></li>
                                <?php } ?>
                            </ul>
                        </div><!-- select_box -->
                    </div>

                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->


            <div class="com_tb_wrap">
                <?php if ($groupid == 3) { ?>
                    <div class="com_tb">
                        <label class="tb_cell">上线时间</label>
                        <div class="tb_cont tb_cell">

                            <input type="text"  value='<?php echo $datatimes ?>'  readonly  class="laydate-icon linetime" onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})"  >

                        </div><br/>


                    </div><!-- com_tb_wrap end -->
                <?php } ?>
                <!-- 富文本编辑器 -->
                <div class="txt_editor_wrap " id="wp02Editor">
                    <textarea class="txt_editor"><?php echo $wallpaperinfo['wallpaper_note'];?></textarea>
                </div>
                <div class="bnts_wrap"><button class="btn_s2 pop_btn" openPopId="fixTipView">保存</button><button class="btn_s2" id="bzAdminWp02Cancel">取消</button></div>
            </div><!-- content end -->

        </div>
</section>

<!-- 弹窗 消息+按钮-->
<div class="pop_wraper" id="fixTipView">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_tip">
                    <p class="tip_mes">壁纸详情已修改，是否保存</p>
                    <div class="tip_btns">
                        <button class="btn_s2 save_ok">确定</button>
                        <button class="btn_s2 btnCancel">取消</button></div>
                    <div class="pop_close"></div>
                </div>

            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->

<!-- 弹窗 图片 pop_style_img表示是图片 带该class的 点击页面其它区域会关闭该图片-->
<div class="pop_wraper pop_style_img" id="fixPicView">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_img">
                    <div class="pop_img_src"><img src="<?php echo $wallpaperinfo["wallpaper_path"] ?>"></div>
                    <div class="pop_close"></div>
                </div>

            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->

<!-- 弹窗 添加标签-->
<div class="pop_wraper" id="fixTagView">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_tags">

                    <ul class="tag_add_wrap tag_list">

                        <?php foreach ($subtargs as $v) { ?>
                            <li class="btn_tag" subid="<?php echo $v['w_subtype_id'] ?>"><?php echo $v['w_subtype_name'] ?></li>
                        <?php } ?>
                        <!--<li class="btn_tag">风景</li>-->
                    </ul>
                    <div class="tag_btns"><button class="btn_s2 btn_tag_add_confirm">确定</button><button class="btn_s2 btn_tag_add_cancel">取消</button></div>
                    <div class="pop_close"></div>

                </div>


            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->

<script type="text/javascript">
    $(function () {

        $(".save_ok").click(function () {
            $(".pop_wraper").removeClass("show");
            var subids = $(".selected_subtargs >li").map(function () {
                return $(this).attr("subid");
            }).get().join("_");

            var wid = $(".wallpaperid").val();
            var wName = $(".wallpapername").val();
            var wtarg = $(".maintarg").attr("val");

            var pubtime = $(".linetime").val();

            var conns = $(".txt_editor").val();

            var check = $(".check_data").attr("val");
            if (check == 2 && conns == '') {
                alert("请填写不通过原因");
                return 0;
            }
            var data = "wid=" + wid + "&wName=" + wName + "&pubtime=" + pubtime + "&wtarg="
                    + wtarg + "&subids=" + subids + "&check=" + check + "&conns=" + conns + "&token=" + token;


            //alert(data);
            url = "/Admin/wallpaperadmin/editPost";
            $.post(url, data, function (d) {
                if (d) {
                    history.go(-1);
                }
            })
        })
    })

</script>

</body>
</html>