<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">报名列表</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="60">ID</td>
			<td width="60">用户id</td>
			<td width="60">手机号</td>
			<td width="60">职位</td>
			<td width="60">状态</td>
			<td>描述</td>
			<td width="120">报名时间</td>
		</tr>
<?php foreach($signup as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['user_id'];?></td>
			<td><?php echo $users[$value['user_id']]['phone'];?></td>
			<td><?php echo $jobs[$value['job_id']]['title'];?></td>
			<td><?php echo Ola_Service_Signup::status($value['status']);?></td>
			<td><?php echo html_entity_decode($value['description']);?></td>
            <td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
