<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
    <ul class="cc">
        <li class="current"><a href="<?php echo $indexUrl;?>">日志列表</a></li>
    </ul>
</div>
<form action="<?php echo $indexUrl;?>" method="get" id="logForm">
    <input name="token" type="hidden" value="<?php echo $token;?>" />
    <div class="table_full">
        <table width="100%">
            <tr class="tr">
                <th class="th">日志类型</th>
                <td class="td">
                    <select name="type" class="" id="type">
                        <option value="">所有类型</option>
                        <?php foreach($error_level as $val=>$title): ?>
                        <option <?php echo ($param['type'] == $val) ? 'selected="selected"' :''; ?> value="<?php echo $val;?>"><?php echo $title; ?></option>
                        <?php endforeach;?>
                    </select>
                </td>
                <th class="th">日志时间</th>
                <td class="td">
                    <input class="input" type="text"  id="from_time" name="from_time" value="<?php echo $param['from_time'];?>">-
                    <input class="input" type="text"  id="to_time" name="to_time" value="<?php echo $param['to_time'];?>">
                </td>
           </tr>
            <tr class="tr">
                <th class="th">&nbsp;</th>
                <td class="td" colspan="3">
                    <span class="btn"><span><button type="submit">搜 索</button></span></span>
                    <span class="btn"><span><button type="button" onclick="deleteLog();">删 除</button></span></span>
                </td>
            </tr>
        </table>
    </div>
</form>
<div class="table_list">
    <table width="100%">
        <tr class="hd">
            <td width="12%">Type</td>
            <td width="45%">Msg</td>
            <td width="20%">File</td>
            <td width="5%">Line</td>
            <td width="8%">Time</td>
            <td width="10%">IP</td>
        </tr>
        <?php foreach($logs as $key => $value) {?>
            <tr class="ct">
                <td><?php echo isset($error_level[$value['type']])?$error_level[$value['type']]:$value['type'];?></td>
                <td><?php echo $value['msg'];?></td>
                <td><?php echo $value['file'];?></td>
                <td><?php echo $value['line'];?></td>
                <td><?php echo date('Y-m-d H:i:s', $value['time']);?></td>
                <td><?php echo $value['ip'];?></td>
            </tr>
        <?php } ?>
    </table>
</div>
<div class="mr10 cc">
    <?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script>
    $(document).ready(function() {
        $("#to_time").datetimepicker();
        $("#from_time").datetimepicker();
    });

    deleteLog = function(e){
        showConfirm("确认批量删除日志？", function() {
            ajaxLoader.show();
            var type = $('#type').val();
            var from_time = $('#from_time').val();
            var to_time = $('#to_time').val();
            $.ajax({
                url	:'<?php echo $patchDeleteUrl; ?>',
                type:'post',
                dataType: 'json',
                data:'token=<?php echo $token;?>&type='+type+'&from_time='+from_time+'&to_time='+to_time,
                success : function(ret) {
                    ajaxLoader.hide();
                    if (ret.success) {
                        alert(ret.msg);
                        location.reload();
                    } else {
                        showError('', ret.msg);
                    }
                }
            });
        }, e);
    };

</script>
<?php echo $this->render("layout/footer.phtml");?>
