<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">推送列表</a></li>
    <li class="current"><a href="javascript:;">发送</a></li>
	</ul>
</div>
<div class="h_a">发送</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="editResourceForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">标题</th>
			<td class="td"><input type="text" class="input wc" name="title" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">内容</th>
			<td class="td"><textarea class="input" name="content" class="textarea wc" style="height:60px;width:300px"></textarea></td>
		</tr>
		<tr class="tr">
			<th class="th">类型</th>
			<td class="td">
				<select name="type">
					<option	value="cp">cp</option>
					<option	value="subscribe">subscribe</option>
					<option	value="update">update</option>
					<option	value="site">site</option>
				</select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">消息数据</th>
			<td class="td"><textarea class="input" name="msg_body" class="textarea wc" style="height:60px;width:300px"></textarea></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('editResourceForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Widget_Push/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
