<?php echo $this->render("layout/header.phtml"); ?>
<script type="text/javascript"
src="<?php echo $staticroot . 'jquery.min.js' ?>"></script>
<script type="text/javascript"
src="<?php echo $staticroot . 'layer/layer.min.js' ?>"></script>


<script type="text/javascript">
    var res = '<?php echo "$res"; ?>';
    $(function() {
        if (res) {
            alert("添加成功");
            var index = parent.layer.getFrameIndex(window.name);
            parent.layer.close(index);
        }
    })
</script>


<?php echo $this->render("layout/footer.phtml"); ?>