<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<title>游戏大厅</title>
	<meta name="keyword" content="金立, 金立游戏, 游戏大厅" />
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<meta name="format-detection" content="email=no" />
<meta name="appRef" content="<?php echo $staticResPath;?>" />
<link rel="stylesheet" href="<?php echo $staticSysPath; ?>/reset/mpcore.css?v=<?php echo $version;?>" />
<link rel="stylesheet" href="<?php echo $staticResPath; ?>/assets/css/game.css?v=<?php echo $version;?>" />
<script type="text/javascript" src="<?php echo $staticSysPath;?>/icat/1.1.5/icat.js?v=<?php echo $version;?>" ></script>
<script type="text/javascript" src="<?php echo $staticResPath;?>/assets/js/game.source.js?v=<?php echo $version;?>" ></script>
<link rel="shortcut icon" href="<?php echo $staticResPath; ?>/pic/game.ico" type="image/ico" mce_href="<?php echo $staticResPath; ?>/apps/game/3g/pic/game.ico" />
<script type="text/javascript">var game_source='<?php echo $game_source?>';</script>
</head>
<body dt-cr="<?php echo $crUrl;?>">