<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">分类列表</a></li>
    <li class="current"><a href="javascript:;">添加分类</a></li>
	</ul>
</div>
<div class="h_a">添加分类</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="0"></td>
		</tr>
		<tr class="tr">
			<th class="th">标题</th>
			<td class="td"><input type="text" class="input wc" name="title" value=""></td>
		</tr>
        <tr class="tr">
            <th class="th">分类</th>
            <td class="td">
                <select name="parent_id"  id="select">
                    <?php foreach($categorys as $key=>$value) { ?>
                        <option value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
                    <?php }?>
                </select>
            </td>
        </tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td"><select name="status">
                	<option value="1">开启</option>
                	<option value="0">关闭</option>
            </select></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
    $(document).ready(function() {

        ajaxForm('addFrom', function (ret) {
            ajaxRedirect(ret, baseurl + '/Admin/Craw_Category/index?s=1');
        });
    })
</script>

<?php echo $this->render("layout/footer.phtml");?>
