<?php echo $this->render("layout/header.phtml");?>
<script>
var token = '<?php echo $token;?>';
</script>
<div id="list-page">
	<section class="wrap">
		<div class="item-list J_gameItem">
			<ul>
				<?php foreach($resource_games as $key=>$value) {?>
				<?php 
				     $location = '';
				     $intersrc = 'CATEGORY'.$id.'_GID'.$value['id'];
				     if($key <=2) $location = '&location='.($key + 1);
				     $href = $webroot.'/channel/index/detail/?id='.$value['id'].'&intersrc='.$intersrc.'&t_bi='.$source.$location;
				?>
				<li>
					<a data-infpage="<?php echo $value['name'].','.$href.','.$value['id'].','.$value['link'].','.$value['package'].','.$value['size'].','.'Android'.$value['min_sys_version_title'].','.$value['min_resolution_title'].'-'.$value['max_resolution_title'];?>">
						<span class="icon"><img src="<?php echo $staticResPath; ?>/pic/blank.gif" alt="" data-src="<?php echo $value['img'];?>"></span>
						<span class="desc">
							<em><?php echo $value['name'];?></em>
							<p><em>大小：<?php echo $value['size'].'M';?></em></p>
							<b><?php echo $value['resume'];?></b>
						</span>
					</a>
				</li>
				<?php }?>
			</ul>
		</div>
	</section>
   <?php if($hasnext){ ?>
		<div class="loading J_loadMore" style="display:none" data-ajaxUrl="<?php echo $webroot.'/channel/category/moreCt/?id='.$id.'&intersrc='.$intersrc.'&t_bi='.$source;?>" data-hasnext="<?php echo $hasnext;?>" data-curpage="<?php echo $page;?>">
		<span class="load"></span>
		</div>
  <?php } ?>
</div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>