<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl;?>">评论审核</a></li>
		<li><a href="<?php echo $manageUrl;?>">评论管理</a></li>
        <li><a href="<?php echo $logUrl;?>">审核记录</a></li>
        <li><a href="<?php echo $slistUrl;?>">敏感词库</a></li>
        <li><a href="<?php echo $plistUrl;?>">词库管理</a></li>
        <li class="current"><a href="<?php echo $blistUrl;?>">黑名单</a></li>
	</ul>
</div>
<form action="<?php echo $blistUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
	    <tr>
	        <th class="th">号码</th>
			<td class="td"><input type="text" class="input" name="name" value="<?php echo $s['name'];?>"></td>
		    <th class="th">状态</th>
			<td class="td">
			<select name="status" class="select wa">
			    <option  value="0">全部</option>
				<option <?php if($s['status'] == 2) echo 'selected';?> value="2">开启</option>
				<option <?php if($s['status'] == 1) echo 'selected';?> value="1">关闭</option>
			</select>
			</td>
		</tr>
	    <tr class="tr">
			<th class="th">维护人</th>
			<td class="td"><input type="text" class="input" name="uname" value="<?php echo $s['uname'];?>"></td>
			<th class="th">类型</th>
			<td class="td">
			<select name="utype" class="select wa">
			      <option  value="0">全部</option>
				  <?php foreach($utype as $key=>$value) {?>
    			  <option value="<?php echo $key;?>" <?php if($s['utype'] == $key) echo 'selected="selected"';?>><?php echo $value;?></option>
    			<?php }?>
			</select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">添加时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo $s['start_time'];?>" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="<?php echo $s['end_time'];?>" /></div>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="h_a">
    <span class="btn2"><span><button><a href="<?php echo $baddUrl;?>" class="mr10" style="color:white;">添加黑名单</a></button></span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <span class="btn2"><span><button type="button" id="extportBtn">导出excel</button></span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <span>&nbsp;&nbsp;&nbsp;&nbsp;共<?php echo $total;?>条结果</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="50">类型</td>
			<td width="100">号码</td>
			<td width="150">添加时间</td>
			<td width="80">状态</td>
			<td width="50">维护人</td>
			<td width="120">操作</td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $utype[$value['utype']];?></td>
			<td><?php echo $value['utype'] == 1 ? $value['name'] : $value['imei'];?></td>
			<td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
			<td><?php echo $value['status'] ? '开启' : '关闭';?></td>		
			<td><?php echo $value['uname'];?></td>
			<td>
			<a href="<?php echo $beditUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<div class="mr10 cc">
	<form action="<?php echo $bexportUrl;?>" method="post" id="exportForm">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	<input type="hidden" name="start_time" value="<?php echo $s['start_time'];?>">
	<input type="hidden" name="end_time" value="<?php echo $s['end_time'];?>">
	<input type="hidden" name="uname" value="<?php echo $s['uname'];?>">
	<input type="hidden" name="status" value="<?php echo $s['status'];?>">
	<input type="hidden" name="name" value="<?php echo $s['name'];?>">
	<input type="hidden" name="utype" value="<?php echo $s['utype'];?>">
	</form>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('batchForm', function(data) {
		ajaxRedirect(data, baseurl+'/Admin/Client_Comment/bindex');
	});
	$('#start_time').datetimepicker();
    $('#end_time').datetimepicker();
	$("#extportBtn").click(function(){
		$("#exportForm").submit();
    });
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
