<?php echo $this->render("layout/header.phtml");?>
<div class="step mb10">
		<ul class="cc">
			<li>添加活动</li>
			<li class="line"></li>
			<li class="current"><span class="fl"><em></em></span>添加奖项</li>
		</ul>
</div>
<form method="post" action="<?php echo $addLotteryPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="activity_id" value="<?php echo $activity_id;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
	    <tr class="tr"><th class="th"><strong>一等奖配置</strong></th></tr>
		<tr class="tr">
			<th class="th">奖品名称</th>
			<td class="td"><input type="text" class="input wc" name="award_name[]" value=""></td>
		</tr>
		<th class="th">图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg0">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img[]" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg0';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<th class="th">图标</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg1">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="icon[]" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg1';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">中奖概率</th>
			<td class="td"><input type="text" class="input" name="probability[]" value=""><span><font color="#FF0000">此处填写【0-<?php echo $maxRate; ?>】的整数。</font></span></td>
		</tr>
		<tr class="tr">
			<th class="th">发放最小间隔</th>
			<td class="td"><input type="text" name="space_time[]" class="input"><span><font color="#FF0000">统一为整数秒，如填60即60秒</font></span></td>
		</tr>
		<tr class="tr">
			<th class="th">最大数量</th>
			<td class="td"><input type="text" name="num[]" class="input"><span><font color="#FF0000">当前奖项每天发放的最大数量</span></td>
		</tr>
		<tr class="tr"><th class="th">二等奖配置</th></tr>
		<tr class="tr">
			<th class="th">奖品名称</th>
			<td class="td"><input type="text" class="input wc" name="award_name[]" value=""></td>
		</tr>
		<th class="th">图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg2">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img[]" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg2';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<th class="th">图标</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg3">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="icon[]" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg3';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">中奖概率</th>
			<td class="td"><input type="text" class="input" name="probability[]" value=""><span><font color="#FF0000">此处填写【0-<?php echo $maxRate; ?>】的整数。</font></span></td>
		</tr>
		<tr class="tr">
			<th class="th">发放最小间隔</th>
			<td class="td"><input type="text" name="space_time[]" class="input"><span><font color="#FF0000">统一为整数秒，如填60即60秒</font></span></td>
		</tr>
		<tr class="tr">
			<th class="th">最大数量</th>
			<td class="td"><input type="text" name="num[]" class="input"><span><font color="#FF0000">当前奖项每天发放的最大数量</span></td>
		</tr>
		<tr class="tr"><th class="th">三等奖配置</th></tr>
		<tr class="tr">
			<th class="th">奖品名称</th>
			<td class="td"><input type="text" class="input wc" name="award_name[]" value=""></td>
		</tr>
		<th class="th">图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg4">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img[]" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg4';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<th class="th">图标</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg5">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="icon[]" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg5';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">中奖概率</th>
			<td class="td"><input type="text" class="input" name="probability[]" value=""><span><font color="#FF0000">此处填写【0-<?php echo $maxRate; ?>】的整数。</font></span></td>
		</tr>
		<tr class="tr">
			<th class="th">发放最小间隔</th>
			<td class="td"><input type="text" name="space_time[]" class="input"><span><font color="#FF0000">统一为整数秒，如填60即60秒</font></span></td>
		</tr>
		<tr class="tr">
			<th class="th">最大数量</th>
			<td class="td"><input type="text" name="num[]" class="input"><span><font color="#FF0000">当前奖项每天发放的最大数量</span></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	 ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Activity/index');
	 });
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
