<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl; ?>">用户列表</a></li>
		<li class="current"><a href="javascript:;">统计报表</a></li>
	</ul>
</div>
<div class="h_a">统计报表</div>

<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">选项1</th>
			<td class="td"></td>
		</tr>
		<tr class="tr">
			<th class="th">选项2</th>
			<td class="td"></td>
		</tr>
		<tr class="tr">
			<th class="th">选项3</th>
			<td class="td"></td>
		</tr>
		<tr class="tr">
			<th class="th">选项4</th>
			<td class="td"></td>
		</tr>
	</table>
</div>

<?php echo $this->render("layout/footer.phtml"); ?>
