<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $indexUrl;?>">资讯列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加资讯</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>" method="get">
    <input name="token" type="hidden" value="<?php echo $token;?>" />
    <div class="table_full">
        <table width="100%">
            <tr class="tr">
                <th class="th">标题</th>
                <td class="td">
                    <input class="input" type="text"   name="title"  value="<?php echo $param['title'];?>" >
                </td>
                <th class="th">开始时间</th>
                <td class="td">
                    <input class="input" type="text" maxlength="30" id="start_time" name="start_time" value="<?php echo $param['start_time'];?>">
                </td>

            <tr class="tr">
                <th class="th">分类</th>
                <td class="td">
                    <select name="type">
                        <option value="-1">不限</option>
                        <?php foreach($type as $k => $v): ?>
                            <option value="<?php echo $k; ?>" <?php echo $k==$param['type']?'selected':""; ?> ><?php echo $v; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <th class="th" width="60">状态</th>
                <td class="td">
                    <select name="status">
                        <option value="0" <?php if ($param['status'] == 0) echo 'selected="selected"';?>>所有</option>
                        <option value="1" <?php if ($param['status'] == 1) echo 'selected="selected"';?>>开启</option>
                        <option value="2" <?php if ($param['status'] == 2) echo 'selected="selected"';?>>关闭</option>
                    </select>
                </td>
            </tr>
            </tr>
        </table>
    </div>
    <div class="mb10 tac">
		<span class="btn">
			<span>
				<button type="submit">搜 索</button>
			</span>
		</span>
    </div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
            <td width="40">排序</td>
            <td width="40">ID</td>
			<td width="100">标题</td>
            <td width="80">分类</td>
            <td width="80">底部格式</td>
            <td width="160">封面图</td>
            <td width="80">状态</td>
			<td width="120">发布时间</td>
			<td width="120">创建时间</td>
			<td width="100">点击量</td>
            <td width="240">操作</td>
		</tr>
<?php foreach($data as $key => $value) {?>
		<tr class="ct <?php if($value['status']) echo 'blue';?>">
            <td><?php echo $value['sort'];?></td>
            <td><?php echo $value['id'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><?php echo $type[$value['type']];?></td>
			<td><?php echo $footer[$value['footer_id']]['name'];?></td>
			<td><?php if($value['images']): ?><?php foreach(array_slice(explode(',', $value['images']), 0, 3) as $img): ?><img src="<?php echo $attachPath.$img; ?>" height="16" /><?php endforeach;endif; ?></td>
            <td><?php echo $status[$value['status']];?></td>
            <td><?php echo date('Y-m-d H:i:s', $value['start_time']);?></td>
            <td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
            <td><?php echo $value['hits'];?></td>
			<td>
				<a href="<?php echo $editUrl;?>/?backurl=index&id=<?php echo $value['id'];?>" class="mr10">编辑</a>
                <a href="<?php echo $webroot;?>/info/detail?id=<?php echo $value['id'];?>" class="mr10" target="_blank">预览</a>
                <?php if($value['is_recommend'] == 0){?>
                <a href="javascript:;" data-type="1"  data-id="<?php echo $value['id']; ?>" class="mr10 top_btn" target="_blank">置顶</a>
                <?php }else{ ?>
                    <?php $topUrl ?>
                <a href="javascript:;" class="mr10 top_btn" data-type="0" data-id="<?php echo $value['id']; ?>" target="_blank">取消置顶</a>
                <?php } ?>
                <a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>?id=<?php echo $value['id'];?>', '', event);" class="mr10">删除</a>
            </td>
		</tr>
<?php } ?>
	</table>
</div>

<div class="mr10 cc">
<?php echo $pager;?>
</div>

<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script>
$(function(){
   $('a.top_btn').click(function(){
       var data = {};
       data.id  = $(this).data('id');
       data.token  = '<?php echo $token; ?>';
       data.type  = $(this).data('type');
       $.ajax({
           url:'<?php echo $topUrl ?>',
           type:'post',
           data:data,
           dataType:'json',
           success:function(res){
               if(res.success==true){
                    window.location.reload();
               }
           }
       });
   });

});
$(document).ready(function() {
	$("#start_time").datepicker({
				dateFormat : 'yy-mm-dd'
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>

