<?php echo $this->render("layout/webheader.phtml");?>
<div id="page">
		<div id="iscrollWrap">
			<div class="mainWrap">
				<!-- 内容区域 START-->
				<section class="for-newyear">
					<div class="item-box">
						<h3>如何使用积分</h3>
						<p>1.会员可凭积分在购物大厅积分换购专区兑换不同额度的商品，兑换额度为1积分可抵现1元人民币。</p>
						<div class="nav-pic"><img src="<?php echo $staticResPath;?>/pic/nav_scorePic.png" alt=""></div>
						<p>2. 购物积分仅限于积分专区商品的换购，不可提现。</p>
						<p>3.积分信息可在您的购物大厅个人中心查看。</p>
						<div class="nav-pic"><img src="<?php echo $staticResPath;?>/pic/nav_coinPic.png" alt=""></div>
					</div>

					<div class="item-box">
						<h3>注意事项</h3>
						<p>1.每天换购商品，抢完为止。</p>
						<p>2.积分换购商品，售出后将不予退换。</p>
					</div>
				</section>
				<!-- 内容区域 END-->
			</div>
		</div>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>