<?php echo $this->render("layout/webheader.phtml");?>
<div id="page">
		<div id="iscrollWrap">
			<div class="mainWrap">
				<!-- 内容区域 START-->
				<section class="for-newyear">

					<div class="item-box">
						<h3>积分返利</h3>
						<p>在赚取积分专区中购物，可获得一定的积分奖励，在确认收货后，奖励积分会进入到您的账户中。</p>
						<div class="nav-pic"><img src="<?php echo $staticResPath;?>/pic/nav_detailPic.png" alt=""></div>
						<div class="nav-pic"><img src="<?php echo $staticResPath;?>/pic/nav_pagePic.png" alt=""></div>
					</div>

					<div class="item-box">
						<h3>注意事项</h3>
						<p>预计返利为预计数额。</p>
					</div>
				</section>
				<!-- 内容区域 END-->
			</div>
		</div>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>