<?php echo $this->render("layout/header.phtml");?>
<div class="wrap rotate_wrap">
	<div class="content">
		<div class="main">
			<!-- 防沉迷介绍 s-->
			<div class="mod_box declaration_box">
				<div class="hd"><i class="hd_ico"></i><h2 class="title">商务合作</h2></div>
				<div class="bd">
					<div class="first_box">
						<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;金立游戏大厅致力于为广大安卓智能手机用户提供精彩的游戏体验，我们拥有优质稳定的用户来源， 强大联运能力的支撑队伍，我们希通过合作将更好的游戏带给用户，同时也帮您找到游戏适合的用户实现共赢。</p>
						<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 您可以前往开发者平台自主注册开发者帐号，并上传内容。如果您有其他疑问或者深度合作的意向，请联系我们的商务负责人。</p>
						<p>开发者平台：<a style="color: #85be3b;" target="_blank" href="<?php echo Common::aimiTjUrl($tjUrl, $tj_channel, $tj_cku, 'visit', 'devgame', $tj_intersrc , 'http://dev.game.gionee.com/');?>">http://dev.game.gionee.com/</a></p>
					</div>
					<div class="business_contact">
						<h3>商务联系:</h3>
						<ul class="clearfix">
							<li>
								<h4>华北区(网游和单机)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;康博宇</h4>
								<p>QQ ：1900856469</p>
								<p>电话：15810086508</p>
								<p>邮箱：kangby@gionee.com</p>
							</li>
							<li class="end">
								<h4>华南区(网游和单机)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;裘捷 </h4>
								<p>QQ ：155207860</p>
								<p>电话：18676720261</p>
								<p>邮箱：qiujie@gionee.com</p>
							</li>
						</ul>
						<ul class="clearfix">
							<li >
								<h4>华东区(网游和单机)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;柯娟</h4>
								<p>QQ ：582487217</p>
								<p>电话：13928492976</p>
								<p>邮箱：kejuan@gionee.com</p>
							</li>
							<li class="end">
								<h4>华中区(网游和单机)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;吴静</h4>
								<p>QQ ：805682612</p>
								<p>电话：13798552358</p>
								<p>邮箱：wujing@gionee.com</p>
							</li>
						</ul>
					</div>

				</div>
			</div>
		</div>
        <div class="aside">
		    <?php echo $this->render("layout/right_nav.phtml");?>
		</div>
		<?php echo $this->render("layout/right.phtml");?>
	</div>
</div>
<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>