<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li style="display:none;"><a href="<?php echo $listUrl;?>">积分概况</a></li>
        <li class="current"><a href="<?php echo $pointShopIndexUrl;?>">积分商城</a></li>
        <li><a href="<?php echo $pointCJIndexUrl;?>">积分抽奖</a></li>
        <li><a href="<?php echo $presendIndexUrl;?>">人工发放</a></li>
        <li><a href="<?php echo $pointDescIndexUrl;?>">积分说明管理</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">	
	   <tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="title" value="<?php echo $s['title'];?>"></td>
			<th class="th">状态</th>
			<td class="td">
			 <select name="status" class="select wa">
			    <option  value="0">全部</option>
				<option <?php if ($s['status'] == 2) echo 'selected';?> value="2">进行中</option>
				<option <?php if ($s['status'] == 1) echo 'selected';?> value="1">已关闭</option>
			 </select>
		   </td>
		</tr>
		<tr class="tr">
		   <th class="th">类型</th>
			<td class="td">
			 <select name="type" class="select wa">
			    <option  value="0">全部</option>
				<option <?php if ($s['type'] == 1) echo 'selected';?> value="1">实体</option>
				<option <?php if ($s['type'] == 2) echo 'selected';?> value="2">A券</option>
			 </select>
		    </td>
		    <th class="th">时间</th>
			<td class="td" colspan="2"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo $s['start_time'];?>" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="<?php echo $s['end_time'];?>" /></div>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="h_a">
	<span class="btn2"><span><button><a href="<?php echo $addGoodUrl;?>" class="mr10" style="color:white;">添加活动</a></button></span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td width="80">ID</td>
			<td width="50">商品名称</td>
			<td width="50">图片</td>
			<td width="50">数量</td>
			<td width="200">生效时间</td>
			<td width="80">类型</td>
			<td width="50">状态</td>
			<td width="120">操作</td>
		</tr>
<?php foreach($goods as $key => $value) {?>
		<tr class="ct">
		    <td><?php echo $value['id'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><img src="<?php echo $attachPath.$value['img'];?>" style="width:7.2em;height:7.2em"/></td>
			<td>剩余: <?php echo $value['remaind_num'];?><br> 总共: <?php echo $value['total_num'];?></td>
			<td><?php echo date('Y-m-d H:i:s', $value['start_time']);?><br><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
			<td><?php echo $type[$value['type']];?></td>
			<td><?php echo $value['status'] ? '开启' : '关闭';?></td>		
			<td>
			<a href="<?php echo $editGoodUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			&nbsp;&nbsp;<a href="<?php echo $exchangeDetailUrl;?>/?mall_id=<?php echo $value['id'];?>">兑换记录</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	 ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Mall_Goods/pointDescIndex');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
