<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li ><a href="<?php echo $listUrl;?>">栏目管理</a></li>
		<li class="current"><a href="<?php echo $listChannelUrl;?>">频道管理</a></li>
	</ul>
</div>
<form action="<?php echo $listChannelUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
	    <tr>
		   <th class="th">状态</th>
			<td class="td">
			<select name="status" class="wa">
			    <option  value="0">全部</option>
				<option <?php if($search['status'] == 1) echo 'selected';?> value="1">开启</option>
				<option <?php if($search['status'] == 2) echo 'selected';?> value="2">关闭</option>
			</select>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">关键字</th>
			<td class="td"><input type="text" class="input" name="name" value="<?php echo $search['name'];?>"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>"
	method="post">
	<input name="token" type="hidden" value="<?php echo $token;?>" /> 
	<input name="action" id="action" type="hidden" value="" />
	<div class="h_a">
		<span class="btn2"><span><a href="<?php echo $editChanneAllUrl;?>" style="text-decoration:none;color:#ffffff;">编辑频道位置</a></span></span>
		&nbsp;&nbsp;&nbsp;&nbsp;<span class="btn2"><span><a href="<?php echo $addChanneUrl;?>" style="text-decoration:none;color:#ffffff;">添加扩展频道</a></span></span>
		<span>&nbsp;&nbsp;&nbsp;&nbsp;共<?php echo $total;?>条结果</span>
	</div>
	<div class="table_list">
		<table width="100%">
			<tr class="hd">
				<td width="50">位置</td>
				<td width="100">频道名称</td>
				<td width="150">所属栏目</td>
				<td>类型</td>
				<td>添加日期</td>
				<td>最后编辑时间</td>
				<td>状态</td>
				<td>操作</td>
			</tr>
		<?php foreach ($info as $value) {
		?>
		<tr class="ct">
		        <td><?php echo $value['pid'].'-'.$value['position'];?></td>
				<td><?php echo $value['name'];?></td>
				<td><?php echo $parent_list[$value['pid']]['name'];?></td>
				<td><?php echo $channel_type[$value['channel_type']] ;?></td>
				<td><?php echo date('Y-m-d ', $value['create_time']);?></td>
				<td><?php echo date('Y-m-d H:i:s', $value['update_time']);?></td>
				<td><?php echo ($value['status'] == 1) ? '开启' : '<font style="color:red">关闭</font>';?></td>
				<td><a href="<?php echo $editChanneUrl.'/?id='.$value['id'].'&channel_type='.$value['channel_type'];?>" class="mr10">编辑</a> 
				</td>
			</tr>
		<?php }?>
	</table>
	</div>
	<div class="mr10 cc">
<?php echo $pager;?>
</div>
</form>
<script
	src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script>
$(document).ready(function(){
	ajaxForm('batchForm', function(data) {
		ajaxRedirect(data, baseurl+'/Admin/Client_Columnnew/channel_index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>