<?php echo $this->render("layout/header.phtml");?>
<style>
	.ct_01 td{
		padding: 7px 10px 9px;
		color: #666;
	}
	.text{
		border:1px solid gray ;
		background: #fff;
		min-height:40px; 
		margin-bottom: 4px;
	}
	.icon_user{
		background-position: -144px -96px;
		width: 16px;height: 16px;
	}
	
</style>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $listUrl;?>">免流量活动</a></li>
		<li><a href="<?php echo $ulistUrl;?>">用户统计</a></li>
        <li><a href="<?php echo $flistUrl;?>">流量统计</a></li>
        <li><a href="<?php echo $blistUrl;?>">黑名单</a></li>
        <li class="current"><a href="<?php echo $hdetailUrl.'?activity_id='.$s['activity_id'];?>">活动明细</a></li>
	</ul>
</div>
<div class="h_a"><a href="<?php echo $listUrl;?>">返回活动明细</a></div>
<div class="table_full">
<dl style="display:-webkit-box">
	<dd style="padding-left: 4px">
		<p><span class="name" style="margin-left:10px">活动ID: <?php echo $info['id'];?> 活动名称: <?php echo $info['title'];?> 活动时间: <?php echo date('Y-m-d H:i:s', $info['start_time']);?>  至 <?php echo date('Y-m-d H:i:s', $info['end_time']);?></span></p>
	    <p><span class="name" style="margin-left:10px">流量消耗: <?php echo $info['phone_consume'];?>M&nbsp;&nbsp;&nbsp;&nbsp;WIFI流量:　<?php echo $info['wifi_consume'];?>M &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;数据截止: <?php echo $info['refresh_time'] ? date('Y-m-d H:i:s', $info['refresh_time']) : '无';?></span></p>
	</dd>
</dl>
</div>
<form action="<?php echo $hdetailUrl.'?activity_id='.$s['activity_id'];?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="activity_id" type="hidden" value="<?php echo $s['activity_id'];?>" />
<div class="table_full">
	<table width="100%">
	    <tr>
	        <th class="th">游戏名称</th>
			<td class="td"><input type="text" class="input" name="game_name" value="<?php echo $s['game_name'];?>"></td>
			<th class="th">游戏ID</th>
			<td class="td"><input type="text" class="input" name="game_id" value="<?php echo $s['game_id'];?>"></td>
			<th class="th">IMSI</th>
			<td class="td"><input type="text" class="input" name="imsi" value="<?php echo $s['imsi'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
			<select name="status" class="select wa">
			      <option  value="0">全部</option>
				  <?php foreach($ustatu as $key=>$value) {?>
    			  <option value="<?php echo $key;?>" <?php if($s['status'] == $key) echo 'selected="selected"';?>><?php echo $value;?></option>
    			<?php }?>
			</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="h_a">
    <span class="btn2"><span><button type="button" id="extportBtn">导出数据</button></span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <span>&nbsp;&nbsp;&nbsp;&nbsp;共<?php echo $total;?>条结果, 消耗 <?php echo $consum;?> M 流量</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">序号</td>
			<td width="120">IMSI</td>
			<td width="200">游戏名称</td>
			<td>游戏ID</td>
			<td width="130">下载时间</td>
			<td>状态</td>
			<td>游戏大小</td>
			<td>消耗流量</td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct_01">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['imsi'];?></td>
			<td><?php echo $value['game_name'];?></td>
			<td><?php echo $value['game_id'];?></td>
			<td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
			<td><?php echo $ustatu[$value['status']];?></td>
			<td><?php echo $value['size'];?>M</td>
			<td><?php echo $value['consume'];?>M</td>
		</tr>
		<tr class="ct">
			<td colspan="6">
			<span class="ui-icon ui-icon-person" style="display:inline-block;margin-bottom:-4px"></span>
				<?php 
				   $imei = "IMEI:".$value['imei'];
				?>
				<?php echo $value['nickname'];?>/<?php echo $value['uname'];?>/<?php echo $imei;?>/<?php echo $value['model'];?>/<?php echo $value['client_pkg'] == "gn.com.android.gamehall" ? "游戏大厅" : "艾米游戏";?>/<?php echo $value['version'];?>/<?php echo $value['sys_version'];?>
				</td>
			</tr>
		</tr>
		<tr></tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<div class="mr10 cc">
	<form action="<?php echo $hdexportUrl;?>" method="post" id="exportForm">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	<input type="hidden" name="activity_id" value="<?php echo $s['activity_id'];?>">
	<input type="hidden" name="game_name" value="<?php echo $s['game_name'];?>">
	<input type="hidden" name="game_id" value="<?php echo $s['game_id'];?>">
	<input type="hidden" name="status" value="<?php echo $s['status'];?>">
	<input type="hidden" name="imsi" value="<?php echo $s['imsi'];?>">
	</form>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('#year_month').datetimepicker();
	ajaxForm('batchForm', function(data) {
		ajaxRedirect(data, baseurl+'/Admin/Freedl_Hd/hdetail');
	});
	$("#extportBtn").click(function(){
		$("#exportForm").submit();
    });
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
