<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $listUrl;?>">免流量活动</a></li>
		<li><a href="<?php echo $ulistUrl;?>">用户统计</a></li>
        <li><a href="<?php echo $flistUrl;?>">流量统计</a></li>
        <li><a href="<?php echo $blistUrl;?>">黑名单</a></li>
        <li class="current"><a href="<?php echo $udetailUrl.'?id='.$s['id'].'&imsi='.$s['imsi'];?>">用户明细</a></li>
	</ul>
</div>
<div class="h_a"><a href="<?php echo $ulistUrl;?>">返回用户统计</a></div>
<div class="table_full">
<dl style="display:-webkit-box">
	<dd style="padding-left: 4px">
		<p><span class="name" style="margin-left:10px">IMSI:<?php echo $info['imsi'];?> 累计消耗 <?php echo $consum;?>M 流量</span></p>
		<span class="ui-icon ui-icon-person" style="display:inline-block;margin-bottom:-4px"></span>
		<?php echo $info['nickname'];?>/<?php echo $info['uname'];?>/IMEI:<?php echo $info['imei'];?>/<?php echo $info['model'];?>/<?php echo $info['client_pkg'] == "gn.com.android.gamehall" ? "游戏大厅" : "艾米游戏";?>/<?php echo $info['version'];?>/<?php echo $info['sys_version'];?>
	    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;数据截止: <?php echo $uinfo['refresh_time'] ? date('Y-m-d H:i:s', $uinfo['refresh_time']) : '无';?>
	</dd>
</dl>
</div>
<form action="<?php echo $udetailUrl.'?id='.$s['id'].'&imsi='.$s['imsi'];?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="imsi" type="hidden" value="<?php echo $s['imsi'];?>" />
<input name="id" type="hidden" value="<?php echo $s['id'];?>" />
<div class="table_full">
	<table width="100%">
	    <tr>
	        <th class="th">游戏名称</th>
			<td class="td"><input type="text" class="input" name="game_name" value="<?php echo $s['game_name'];?>"></td>
			<th class="th">游戏ID</th>
			<td class="td"><input type="text" class="input" name="game_id" value="<?php echo $s['game_id'];?>"></td>
			<th class="th">活动ID</th>
			<td class="td"><input type="text" class="input" name="activity_id" value="<?php echo $s['activity_id'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">月份</th>
			<td class="td">
			<?php /*?><select name="year_month" class="select wa">
				  <?php foreach($stype as $key=>$value) {?>
    			  <option value="<?php echo $key;?>" <?php if($s['sort'] == $key) echo 'selected="selected"';?>><?php echo $value;?></option>
    			<?php }?>
			</select><?php */?>
			<input class="input" type="text" maxlength="30" style="width:143px;" id="year_month" name="year_month" value="<?php echo $s['year_month'];?>" />
			</td>
			<th class="th">状态</th>
			<td class="td">
			<select name="status" class="select wa">
			      <option  value="0">全部</option>
				  <?php foreach($ustatu as $key=>$value) {?>
    			  <option value="<?php echo $key;?>" <?php if($s['status'] == $key) echo 'selected="selected"';?>><?php echo $value;?></option>
    			<?php }?>
			</select>
			</td>
			<th class="th">活动名称</th>
			<td class="td"><input type="text" class="input" name="activity_name" value="<?php echo $s['activity_name'];?>"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="h_a">
    <span class="btn2"><span><button type="button" id="extportBtn">导出数据</button></span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <span>&nbsp;&nbsp;&nbsp;&nbsp;共<?php echo $total;?>条结果, 消耗 <?php echo $consum;?>M 流量</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">月份</td>
			<td width="100">游戏名称</td>
			<td>游戏ID</td>
			<td>活动ID</td>
			<td width="180">活动名称</td>
			<td width="120">下载时间</td>
			<td>状态</td>
			<td>游戏大小</td>
			<td>消耗流量</td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['year_month'];?></td>
			<td><?php echo $value['game_name'];?></td>
			<td><?php echo $value['game_id'];?></td>
			<td><?php echo $value['activity_id'];?></td>
			<td><?php echo $value['activity_name'];?></td>
			<td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
			<td><?php echo $ustatu[$value['status']];?></td>
			<td><?php echo $value['size'];?>M</td>
			<td><?php echo $value['consume'];?>M</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<div class="mr10 cc">
	<form action="<?php echo $udexportUrl;?>" method="post" id="exportForm">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	<input type="hidden" name="id" value="<?php echo $s['id'];?>">
	<input type="hidden" name="imsi" value="<?php echo $s['imsi'];?>">
	<input type="hidden" name="game_name" value="<?php echo $s['game_name'];?>">
	<input type="hidden" name="game_id" value="<?php echo $s['game_id'];?>">
	<input type="hidden" name="activity_id" value="<?php echo $s['activity_id'];?>">
	<input type="hidden" name="year_month" value="<?php echo $s['year_month'];?>">
	<input type="hidden" name="status" value="<?php echo $s['status'];?>">
	<input type="hidden" name="activity_name" value="<?php echo $s['activity_name'];?>">
	</form>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('#year_month').datetimepicker();
	ajaxForm('batchForm', function(data) {
		ajaxRedirect(data, baseurl+'/Admin/Freedl_Hd/udetail');
	});
	$("#extportBtn").click(function(){
		$("#exportForm").submit();
    });
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
