<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">token列表</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<td class="td">token</td>
			<td class="td">
				<input type="text" class="input wa" name="_token" value="<?php echo $search['token'];?>">
			</td>
			<td class="td">uid</td>
			<td class="td">
				<input type="text" class="input wa" name="uid" value="<?php echo $search['uid'];?>">
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td>token</td>
			<td>uid</td>
			<td width="200">时间</td>
		</tr>
<?php foreach($rids as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['token'];?></td>
			<td><?php echo $value['uid'];?></td>
			<td><?php echo date('Y-m-d H:i:s',$value['create_time']);?></td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
