<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">文件列表</a></li>
    <li class="current"><a href="javascript:;">预览文件</a></li>
	</ul>
</div>
<div class="h_a">预览文件</div>
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">标题</th>
			<td class="td"><?php echo $info['title'];?></td>
		</tr>
		<tr class="tr">
			<th class="th">缩略图</th>
			<td class="td"><img src="<?php echo $info['icon'];?>" /></td>
		</tr>
		<tr class="tr">
			<th class="th">预览图</th>
			<td class="td"><img src="<?php echo $info['icon_hd'];?>" />&nbsp;<img src="<?php echo $info['icon_micro'];?>" /></td>
		</tr>
		<tr class="tr">
			<th class="th">分类</th>
			<td class="td"><?php echo $info['labels'];?></td>
		</tr>
		<tr class="tr">
			<th class="th">场景描述</th>
			<td class="td"><?php echo $info['summary'];?></td>
		</tr>
	</table>
</div>
<span class="btn"><span><button onclick="javascript:history.back(-1);" type="button">返回</button></span></span></div>
<?php echo $this->render("layout/footer.phtml");?>
