<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="pay_paydesigner_paycheckcompany">
        <div class="content">
        	<div class="desginer_detail">
        		<div class="com_tb_wrap">
        			<div class="com_tb">
	        			<label class="tb_cell">昵称</label>
	        			<div class="tb_cont tb_cell">
	        				<p><?php echo $designer['nick_name']; ?></p>
	        			</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">性别</label>
        				<div class="tb_cont tb_cell">
        					<p><?php echo ($designer['sex']==1)?'男':'女'; ?></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">头像</label>
        				<div class="tb_cont ">
        					<div class="account"><img src='<?php echo '/themeicon/data/userIcon/'.$designer['icon'] ?>'></div>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">姓名</label>
        				<div class="tb_cont te_cell">
        					<p><?php echo $detail['real_name']; ?></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">手机号</label>
        				<div class="tb_cont te_cell">
        					<p><?php echo $detail['tel']; ?></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">邮箱</label>
        				<div class="tb_cont te_cell">
        					<p><?php echo $detail['email']; ?></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">QQ</label>
        				<div class="tb_cont te_cell">
        					<p><?php echo $detail['qq']; ?></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">公司名称</label>
        				<div class="tb_cont te_cell">
        					<p><?php echo $detail['company_name']; ?></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">营业执照注册号</label>
        				<div class="tb_cont te_cell">
        					<p><?php echo $detail['license']; ?></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">营业执照扫描</label>
        				<div class="tb_cont te_cell">
        					<div class="account"><img src='<?php echo '/themeicon/data/licenseIcon/'.$detail['license_pic'] ?>'></div>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">税务登记证号</label>
        				<div class="tb_cont te_cell">
        					<p><?php echo $detail['tax_number']; ?></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">税务登记证扫描</label>
        				<div class="tb_cont te_cell">
        					<div class="account"><img src='<?php echo '/themeicon/data/taxIcon/'.$detail['tax_pic'] ?>'></div>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">开户银行名称</label>
        				<div class="tb_cont te_cell">
        					<p><?php echo $detail['bank']; ?></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">开户名称</label>
        				<div class="tb_cont te_cell">
        					<p><?php echo $detail['account_name']; ?></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">开户支行</label>
        				<div class="tb_cont te_cell">
        					<p><?php echo $detail['branch']; ?></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">银行卡号</label>
        				<div class="tb_cont te_cell">
        					<p><?php echo $detail['card_number']; ?></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        	</div>
        	<div class="bnts_wrap"><button class="btn_s2" id="comeBack" onclick="history.go(-1);">返回</button></div>
        </div><!-- content end -->
    </div>
</section>
</body>
</html>