<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Insert title here</title>
        <link href="<?php echo $staticPath ?>/css/default.css" rel="stylesheet">
        <script type="text/javascript" src="<?php echo $staticPath ?>/jssdk/jquery-1.10.2.min.js"></script>

    </head>

    <body>
        <script type="text/javascript">
            $(function () {
                $("#btnLogIn").on("click", function () {
                    window.location.href = "/Admin/Login/login";
                });
            });

        </script>
        <div class="loginBG"></div><!-- body背景层 -->

        <form action="<?php echo $loginUrl ?>" method="post">
            <div class="loginMain" id="webg_login">
                <div class="loginDov icon_login01">
                    <span><input type="text" placeholder="用户名" name="username"></span>
                </div>
                <div class="loginDov icon_login02">
                    <span><input type="password" placeholder="密码" name="password"></span>
                    <input name="token" type="hidden" value="<?php echo $token ?>"/>
                </div>
                <div class="loginBtnDov">
                    <button class="btn_login" id="btnLogIn" type="submit"> 登录</button>
                </div>
            </div>
        </form>




    </body>
</html>