<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class="current"><a href="<?php echo $listUrl; ?>">属性列表</a></li>
			<li><a href="<?php echo $addUrl; ?>">添加属性</a></li>
		</ul>
	</div>
	<div class="table_list">
		<table style="width: 100%">
			<tr class="hd">
				<th class="th">ID</th>
				<th class="th">名称</th>
				<th class="th">操作</th>
			</tr>
			<?php foreach ($dataList as $v) { ?>
				<tr class="ct">
					<td class="td"><?=$v['id'];?></td>
					<td class="td"><?=$v['name'];?></td>
					<td class="td">
						<a href="javascript:void(0);" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $v['id']; ?>', '', event);">删除</a>
				</tr>
			<?php } ?>
		</table>
	</div>

	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>
<?php echo $this->render("layout/footer.phtml"); ?>