<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $lotterylogUrl;?>">抽奖记录</a></li>
		<li><a href="<?php echo $lotterylogUrl;?>">奖品管理</a></li>
        <li><a href="<?php echo $listUrl;?>">活动列表</a></li>
        <li class="current"><a href="javascript:;">添加活动</a></li>
	</ul>
</div>
<div class="step mb10">
		<ul class="cc">
			<li class="current">添加活动</li>
			<li class="line"></li>
			<li><span class="fl"><em></em></span>添加奖项</li>
		</ul>
</div>
<div class="h_a">添加活动</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr" style="display: none;">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="0"></td>
		</tr>
		<tr class="tr">
			<th class="th">活动名称</th>
			<td class="td"><input type="text" class="input wc" name="name" value=""></td>
		</tr>
		<tr class="tr" style="display: none;">
			<th class="th">活动上线下线时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="online_start_time" name="online_start_time" value="" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="online_end_time" name="online_end_time" value="" /></div>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">抽奖开始时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="" />  <!-- <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="" /> --></div>
			</td>
		</tr>
		<tr class="tr" style="display: none;">
			<th class="th">兑奖截止时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="award_time" name="award_time" value="" /> </div>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">活动图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="simg">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=simg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">最低版本</th>
			<td class="td"><input type="text" name="min_version" class="input"><span>不填写，默认大于等于1.5.0版本皆可参与</span></td>
		</tr>
		<tr class="tr">
			<th class="th">抽奖次数</th>
			<td class="td"><input type="text" class="input" name="number" value=""><span>每个用户每天的抽奖机会</span></td>
		</tr>
		<tr class="tr">
			<th class="th">活动说明</th>
			<td class="td"><textarea style="width: 800px; height: 500px" class="textarea" name="descrip" value=""></textarea>
		    </td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td"><select name="status">
                	<option value="1">开启</option>
                	<option value="0">关闭</option>
            </select></td>
		</tr>
		<tr class="tr">
				<th class="th">客户端是否弹出窗口</th>
				<td class="td">
					<label class="mr20"><input onclick ="showContent(1)" name="popup_status" value="1" type="radio">开启</label>
					<label class="mr20"><input onclick ="showContent(0)" checked name="popup_status" value="0" type="radio">关闭</label>
				</td>
		</tr>
		<tr class="tr">
			<th class="th">客户端弹出窗口信息</th>
			<td class="td"><textarea style="width: 500px; height: 200px" class="textarea" name="message" disabled="disabled" id="message"></textarea>
		    </td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">下一步</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
showContent = function(flag) {
	if (flag) {
	 $("#message").removeAttr("disabled");
	} else {
	 $("#message").attr('disabled',true);
	}
}
$(document).ready(function(){
	var editor;
	KindEditor.ready(function(K) {
		K.token = '<?php echo $token;?>';
	    editor = K.create('textarea[name="descrip"]', {
	        resizeType : 1,
	        allowPreviewEmoticons : false,
	        allowImageUpload : true,
	        uploadJson : '<?php echo $uploadImgUrl;?>',
	        items : EDITOR_ITEMS
	    });
	});
	 $('#start_time').datetimepicker();
     $('#award_time').datetimepicker();
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Activity/addlottery?id='+ret.data);
	},function(){
		editor.sync();
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
