<?php echo $this->render("layout/header2.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="javascript:;">编辑合辑或图片</a></li>
	</ul>
</div>
<div class="h_a">编辑游戏合辑或图片</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
    <table width="100%">
		<tr class="tr">
			<th class="th">推荐方式(<span style="color: red">*</span>)</th>
			<td class="td"><?php echo $rec_type[$info['rec_type']];?></td>
		</tr>
		<tr class="tr">
			<th class="th">标题(<span style="color: red">*</span>)</th>
			<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">描述</th>
			<td class="td"><textarea rows="3" cols="30" class="input" name="content"><?php echo $info['content'];?></textarea></td>
		</tr>
	</table>
</div>
<div class="mb10 tac">
    <span class="btn"><span><a href="javascript:window.history.go(-1);"><button type="button">返回</button></a></span></span>
    <span class="btn"><span><button onfocus="blur();" type="submit">下一步</button></span></span>
</div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	 $('#start_time').datetimepicker({
         timeFormat: "hh:00:00",
         dateFormat: "yy-mm-dd"
     });
     $('#end_time').datetimepicker({
         timeFormat: "hh:00:00",
         dateFormat: "yy-mm-dd"
     });
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $gamesUrl . "?id=";?>' + ret.data);
	});
});
</script>
<?php echo $this->render("layout/footer.phtml");?>
