<?php echo $this->render("layout/webheader.phtml");?>
<body data-pagerole="body">
	<div class="module">
		<header id="iHeader" class="hd">
		<?php if($hasheader){?>
			<div class="top-wrap">
				<div class="title">
					<a href="<?php echo $webroot;?>" class="back"></a>
					<h1>热门活动</h1>
				</div>
			</div>
		<?php }?>
			<wrapsubnav>
				<nav>
					<ul>
						<li><a href="<?php echo $webroot?>/amigo/index/index">商品</a></li>
						<li><a href="<?php echo $webroot?>/amigo/activity/index">活动</a></li>
						<li class="selected"><span>服务</span></li>
					</ul>
				</nav>
			</wrapsubnav>
		</header>

		<section id="iScroll">
			<div class="service-list">
				<ul>
					<li><a href="<?php echo $webroot?>/amigo/order/search">我要查询订单</a></li>
					<li><a href="<?php echo $webroot?>/amigo/orderreturn/search">我要退/换货</a></li>
					<li><a href="tel:0755-82583525">我要联系客服</a></li>
				</ul>
			</div>
		</section>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>