<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li class="current"><a href="<?php echo $listUrl;?>">积分商城</a></li>
        <li><a href="<?php echo $pointPrizeIndexUrl;?>">积分抽奖</a></li>
        <li><a href="<?php echo $presendIndexUrl;?>">人工发放</a></li>
        <li><a href="<?php echo $pointDescIndexUrl;?>">积分说明管理</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="category_id" type="hidden" value="<?php echo $s['category_id'];?>" />
<div class="table_full">
	<table width="100%">	
	   <tr class="tr">
			<th class="th">商品名称</th>
			<td class="td"><input type="text" class="input" name="title" value="<?php echo $s['title'];?>"></td>
			<th class="th">状态</th>
			<td class="td">
			 <select name="status" class="select wa">
			    <option  value="0">全部</option>
				<option <?php if ($s['status'] == 2) echo 'selected';?> value="2">开启</option>
				<option <?php if ($s['status'] == 1) echo 'selected';?> value="1">关闭</option>
			 </select>
		   </td>
		</tr>
		<tr class="tr">
		   <th class="th">商品类型</th>
			<td class="td">
			 <select name="type" class="select wa">
			    <option  value="0">全部</option>
				<option <?php if ($s['type'] == Mall_Service_Goods::ACOUPON) echo 'selected';?> value="2">A券,游戏券</option>
				<option <?php if ($s['type'] == Mall_Service_Goods::ENTITY) echo 'selected';?> value="1">实物奖品</option>
				<option <?php if ($s['type'] == Mall_Service_Goods::GIFT) echo 'selected';?> value="3">游戏礼包</option>
				<option <?php if ($s['type'] == Mall_Service_Goods::DISCOUNT_COUPON) echo 'selected';?> value="4">优惠券</option>
				<option <?php if ($s['type'] == Mall_Service_Goods::PHONE_RECHARGE_CARD) echo 'selected';?> value="5">话费,充值卡</option>
			 </select>
		    </td>
		    <th class="th">时间</th>
			<td class="td" colspan="2"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo $s['start_time'];?>" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="<?php echo $s['end_time'];?>" /></div>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="action" id="action" type="hidden" value="" />
<div class="h_a">
    <span class="btn2"><span><button onclick="$('#action').val('sort');" type="submit">重新排序</button></span></span>
	<span class="btn2" style="display:none;"><span><button><a href="<?php echo $addGoodUrl;?>?category_id=<?php echo $s['category_id'];?>" class="mr10" style="color:white;">添加商品</a></button></span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<span>商品分类名称 ：<?php echo $goodsCategory['title'];?></span>&nbsp;&nbsp;&nbsp;
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td><input type="checkbox" onclick="checkAll('.checkbox')"></td>
		    <td width="80">ID</td>
		    <td width="50">排序</td>
			<td width="120">商品名称</td>
			<td width="50">图片</td>
			<td width="150">数量</td>
			<td width="200">生效时间</td>
			<?php if($goodsCategory['goods_type'] == Mall_Service_Goods::GIFT || $goodsCategory['goods_type'] == Mall_Service_Goods::DISCOUNT_COUPON){?>
			<td width="80">礼包类型</td>
			<?php } else {?>
			<td width="80">商品类型</td>
			<?php } ?>
			<td width="50">状态</td>
			<td>操作</td>
		</tr>
<?php foreach($goods as $key => $value) {?>
		<tr class="ct">
		    <td><input class="checkbox" name="ids[]" value="<?php echo $value['id'];?>" type="checkbox"></td>
		    <td><?php echo $value['id'];?></td>
		    <td><input type="text" class="input" style="width:30px" name="sort[<?php echo $value['id'];?>]" value="<?php echo $value['sort'];?>"></td>
			<td><?php echo $value['title'];?></td>
			<td><img src="<?php echo $attachPath.$value['img'];?>" style="width:7.2em;height:7.2em"/></td>
			<td>剩余: <?php echo $value['remaind_num'];?><br> 总共: <?php echo $value['total_num'];?></td>
			<td><?php echo date('Y-m-d H:i:s', $value['start_time']);?><br><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
			<?php if($goodsCategory['goods_type'] == Mall_Service_Goods::GIFT || $goodsCategory['goods_type'] == Mall_Service_Goods::DISCOUNT_COUPON){?>
			<td><?php echo $giftNumType[$value['gift_num_type']];?></td>
			<?php } else {?>
			<td><?php echo $type[$value['type']];?></td>
			<?php } ?>
			<td><?php echo $value['status'] ? '开启' : '关闭';?></td>		
			<td>
			<a href="<?php echo $editGoodUrl;?>/?id=<?php echo $value['id'];?>&category_id=<?php echo $s['category_id'];?>" class="mr10">编辑</a>
			<?php if($value['type'] == 3 || $value['type'] == 4){?>
			&nbsp;&nbsp;<a href="<?php echo $logUrl;?>/?mall_id=<?php echo $value['id'];?>&category_id=<?php echo $s['category_id'];?>">兑换记录</a>
			<?php } else {?>
			&nbsp;&nbsp;<a href="<?php echo $exchangeDetailUrl;?>/?mall_id=<?php echo $value['id'];?>&category_id=<?php echo $s['category_id'];?>">兑换记录</a>
			<?php } ?>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	 ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Mall_Goods/index?category_id=<?php echo $s['category_id'];?>');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
