<?php echo $this->render("layout/header.phtml");?>
	<div data-role="page" id="page" class="intro-about" data-theme="no">
		<div data-role="page" id="page" class="intro-about" data-theme="no">
		<?php echo $this->render("layout/nav.phtml");?>
		<h1 class="inner-title"><strong>金立大事</strong></h1>
		<div class="ct text">
			<p>2012年</p>
			<p>2012年2月，金立被评为2011年“深圳市和谐劳动关系先进企业”。</p>
			<p>2012年2月，金铭公司被评为“2011年度大岭山镇民营企业十大纳税户”。</p>
			<p>2012年2月27日至3月1日，金立手机现身巴塞罗那世界移动通信大会。</p>
			<p>2012年3月，“GIONEE金立手机”被评为“全国市场放心消费品牌”和“2011年度中国手机行业十大品牌”。</p>
			<p>2012年4月，金立手机参加博鳌亚洲论坛2012年年会。</p>
			<p>2012年5月，中国航天基金会理事长张建启一行莅临金立参观指导。</p>
			<p>2012年5月，中国航天基金会授予金立“中国航天事业合作伙伴”称号。</p>
		</div>
	</div>
<?php echo $this->render("layout/footer.phtml");?>
