<?php
$str = '<ul class="ui-fun-list">';
foreach ($list as $val) {
	$str .= sprintf('<li><a href="%s" class="ui-fun-item"><div class="l"><img class="pic" src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==" data-src="%s" /></div><div class="r" ><p>%s</p><p>%s</p></div></a></li>', $val['link'], $val['img'], $val['name'], $val['ext']);
}
$str .= '</ul>';
echo $str;