<!DOCTYPE html>
<html lang="en">
<head>
<?php $this->title='常见问题';$this->hasSearch=false;?>
<meta charset="UTF-8">
<title>常见问题</title>
	<?php echo $this->render("layout/cssInc.phtml");?>
</head>
<body>
<?php echo $this->render("layout/header.phtml");?>
	<div class="faq-content ui-editor">
		<?php echo html_entity_decode($aqContent);?>
	</div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>