<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $oldListUrl;?>">旧版本说明</a></li>
		<li class="current"><a href="<?php echo $bannerUrl;?>">单机网游图片</a></li>
		<li><a href="<?php echo $recListUrl;?>">推荐列表</a></li>
		<li><a href="<?php echo $recImgUrl;?>">推荐图片</a></li>
		<li><a href="<?php echo $imgUrl;?>">图片广告</a></li>
		<li><a href="<?php echo $imgLogUrl;?>">历史列表图片</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="ad_type" type="hidden" value="<?php echo $ad_type;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr" style="display:none">
			<th class="th">时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo $search['start_time'];?>" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="<?php echo $search['end_time'];?>" /></div>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">关键字</th>
			<td class="td"><input type="text" class="input" name="title" value="<?php echo empty($search['title'])?'':$search['title'];?>"></td>
		</tr>	
		<tr>
		   <th class="th">状态</th>
			<td class="td">
			<select name="status" class="wa">
			    <option  value="0">全部</option>
				<option <?php if($search['status'] == 2) echo 'selected';?> value="2">开启</option>
				<option <?php if($search['status'] == 1) echo 'selected';?> value="1">关闭</option>
			</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="h_a">
	<span>共<?php echo $total;?>条结果</span>
	<span class="btn2"><span><a href="<?php echo $addUrl;?>"><button type="button">添加图片</button></a></span></span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="60">排序</td>
			<td>标题</td>
			<td>链接ID</td>
			<td>位置</td>
			<td>链接类型</td>
			<td>图片</td>
			<td width="120">开始时间</td>
			<td width="120">结束时间</td>
			<td width="60">状态</td>
			<td width="100">操作</td>
		</tr>
<?php foreach($ads as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><?php echo $value['link'];?></td>
			<td><?php echo $postion[$value['hits']];?></td>
			<td><?php echo $ad_ptype[$value['ad_ptype']];?></td>
			<td><img src="<?php echo $attachPath.$value['img'];?>" style="width:70px;height:70px;"/></td>
			
	        <td><?php echo date('Y-m-d H:i:s', $value['start_time']);?></td>
	        <td><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
			<td><?php echo $value['status'] == 1 ? '开启' : '关闭';?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Ad_Turn/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
