<!DOCTYPE html>
<html lang="en">
<head>
	<?php $this->title='关于我们';$this->hasSearch=false;?>
	<meta charset="UTF-8">
	<title>游戏大厅</title>
	<?php echo $this->render("layout/cssInc.phtml");?>
</head>
<body>
	<?php echo $this->render("layout/header.phtml");?>
	<div id="container">
		<div class="about-us">
			<img src="http://dev.repos.com:80/apps/game/h5/assets/img/photo.png" />
			<div class="contact">
				<div class="private">
					<h3>商务合作</h3>
					<div class="row">
						<div>白勇</div>
						<div>手机：xxxxxx</div>
						<div>邮箱：xxxxxx</div>
						<div>QQ：xxxxxxx</div>
					</div>
					<div class="row">
						<div>白勇</div>
						<div>手机：xxxxxx</div>
						<div>邮箱：xxxxxx</div>
						<div>QQ：xxxxxxx</div>
					</div>
				</div>
				<div class="official">
					<h3>官方联系方式及地扯</h3>
					<div>邮箱：xxxxxx</div>
					<div>QQ：xxxxxx</div>
					<div>微信：xxxxxxx</div>
					<div>地址：xxxxxx</div>
					<div>邮编：xxxxxxx</div>
				</div>
				<div class="developers">
					开发者平台：<a href="<?php echo "";?>">dev.gionee.com</a>
				</div>
			</div>
		</div>
    </div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>