<!DOCTYPE html>
<html lang="en">
<head>
	<?php $this->title='关于我们';$this->hasSearch=false;?>
	<meta charset="UTF-8">
	<title>游戏大厅</title>
	<?php echo $this->render("layout/cssInc.phtml");?>
</head>
<body>
	<?php echo $this->render("layout/header.phtml");?>
	<div id="container">
		<div class="client-downloads">
			<img src="<?php echo $game['big_img'];?>" class="poster" />
			<div class="row">
				<a href=<?php echo $game['link'];?>><input type="button" value="立即下载" class="dow-but"  /></a>
				<div class="release-size">片本号：<?php echo $game['version']?>&nbsp;&nbsp;&nbsp;&nbsp;大小：<?php echo $game['size']?>M</div>
			</div>
			<div class="row">
				<div class="left">
					<div class="massive-game">
						<img src="<?php echo $appImg ?>/icon-massive-game.png" />
					</div>
				</div>
				<div class="right">
					<h3>海量游戏</h3>
					<p>市场上所有游戏一网打尽</p>
				</div>
				</div>
			<div class="row">
					<div class="left">
						<div class="fast-downloads">
							<img src="<?php echo $appImg ?>/icon-fast-downloads.png" />
						</div>
					</div>
					<div class="right">
						<h3>极速下载</h3>
						<p>市场上所有游戏一网打尽</p>
					</div>
				</div>
			<div class="row">
				<div class="left">
					<div class="rich-package">
						<img src="<?php echo $appImg ?>/icon-rich-package.png" />
					</div>
				</div>
				<div class="right">
					<h3>丰富礼包</h3>
					<p>市场上所有游戏一网打尽</p>
				</div>
			</div>
		</div>
		
    </div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
<?php echo $this->render("layout/scriptInc.phtml");?>
<script type="text/javascript">
	
</script>
</html>