<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $listUrl;?>">免流量活动</a></li>
		<li><a href="<?php echo $ulistUrl;?>">用户统计</a></li>
        <li><a href="<?php echo $flistUrl;?>">流量统计</a></li>
        <li><a href="<?php echo $blistUrl;?>">黑名单</a></li>
        <li class="current"><a href="<?php echo $ualistUrl;?>">全部用户</a></li>
	</ul>
</div>
<div class="h_a"><a href="<?php echo $ulistUrl;?>">返回用户统计</a></div>
<div class="h_a">
    <span class="btn2"><span><button type="button" id="extportBtn">导出数据</button></span></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <span>&nbsp;&nbsp;&nbsp;&nbsp;共<?php echo $total;?>条结果</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td width="180">地区</td>
			<td width="50">人数</td>
			<td width="600"></td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
		    <td><?php echo $regions[$value['region']].' '.$operator[$value['operator']];?></td>
			<td><?php echo $value['num'];?></td>
			<td></td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<div class="mr10 cc">
	<form action="<?php echo $uaexportUrl;?>" method="post" id="exportForm">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	</form>
</div>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
     $("#extportBtn").click(function(){
  		$("#exportForm").submit();
     });
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
