<?php echo $this->render("layout/header.phtml");?>
<body module-id="myPublish">
<div class="module">
    <section class="layout-center">
        <ul class="list-wrap" id="J_listWrap" data-ajax="<?php echo $webroot?>/api/user/published"></ul>
    </section>
</div>

<script type="text/template" id="J_template">
<%if(list.length) {%>
    <%for(var i=0, len=list.length; i<len; i++) {%>
        <li>
            <a class="side" href="<%=list[i].link%>">
                <div class="pic">
                    <img src="<%=list[i].category_img%>"/>
                </div>
            </a>
            <a class="main" href="<%=list[i].link%>">
                <div class="title"><%=list[i].title%></div>
                <ul class="detail">
                    <li class="price"><em><%=list[i].money%></em>元/<%=list[i].money_type%></li>
                    <li class="flex"><i class="icon-time"></i><%=list[i].create_time%></li>
                </ul>
            </a>
            <div class="side-right">
                <div class="signup-wrap">
                    <%if(list[i].status == "1"){%>
                    <a href="<%=list[i].users_link%>" class="passed">
                        <div class="count"><%=list[i].signup_count%></div>
                        <span>人报名</span>
                    </a>
                    <%} else if (list[i].status == "2") {%>
                        <div class="pending"></div>
                    <%} else if (list[i].status == "3") {%>
                        <div class="rejected"></div>
                    <%}%>
                </div>
            </div>
        </li>
    <%}%>
<%} else {%>
    <div class="no-result">暂无数据</div>
<%}%>
</script>
<?php echo $this->render("layout/footer.phtml");?>
