<?php echo $this->render("layout/header.phtml");?>
	<div data-role="page" id="page" class="intro" data-theme="no">		
		<?php echo $this->render("layout/nav.phtml");?>
		<h1 class="inner-title"><strong>金立大事</strong></h1>
		<div class="ct">
			<div class="list sub-link">
				<ul>
					<li>
						<a href="/index/about_events_2012">
							<span class="ico"><img src="<?php echo $staticResPath;?>//pic/events/2012.png" alt="" /></span>
							<em>2012年</em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					<li>
						<a href="/index/about_events_2011">
							<span class="ico"><img src="<?php echo $staticResPath;?>//pic/events/2011.png" alt="" /></span>
							<em>2011年</em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					<li>
						<a href="/index/about_events_2010">
							<span class="ico"><img src="<?php echo $staticResPath;?>//pic/events/2010.png" alt="" /></span>
							<em>2010年</em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					<li>
						<a href="/index/about_events_2009">
							<span class="ico"><img src="<?php echo $staticResPath;?>//pic/events/2009.png" alt="" /></span>
							<em>2009年</em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					<li>
						<a href="/index/about_events_2008">
							<span class="ico"><img src="<?php echo $staticResPath;?>//pic/events/2008.png" alt="" /></span>
							<em>2008年</em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					<li>
						<a href="/index/about_events_2007">
							<span class="ico"><img src="<?php echo $staticResPath;?>//pic/events/2007.png" alt="" /></span>
							<em>2007年</em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					<li>
						<a href="/index/about_events_2006">
							<span class="ico"><img src="<?php echo $staticResPath;?>//pic/events/2006.png" alt="" /></span>
							<em>2006年</em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					<li>
						<a href="/index/about_events_2005">
							<span class="ico"><img src="<?php echo $staticResPath;?>//pic/events/2005.png" alt="" /></span>
							<em>2005年以前</em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
<?php echo $this->render("layout/footer.phtml");?>