<?php echo $this->render("layout/header.phtml");?>
	<div data-role="page" id="page" class="news" data-theme="no">		
		<?php echo $this->render("layout/nav.phtml");?>
		<h1 class="inner-title"><strong>企业荣誉</strong></h1>
		<div class="ct">
			<div class="list news-title">
				<ul>
					
					<li>
						<a href="/index/about_honor_1">
							<i class="ico"><img src="<?php echo $staticResPath;?>//pic/honor/1.gif" alt="" /></i>
							<em>“GiONEE金立”被评为“2011年度中国手机行业十大品牌”<br /><span>2012年4月23日</span></em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					<li>
						<a href="/index/about_honor_2">
							<i class="ico"><img src="<?php echo $staticResPath;?>//pic/honor/2.gif" alt="" /></i>
							<em>“GiONEE金立手机”被评为“全国市场放心消费品牌”<br /><span>2012年3月14日</span></em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					<li>
						<a href="/index/about_honor_3">
							<i class="ico"><img src="<?php echo $staticResPath;?>//pic/honor/3.gif" alt="" /></i>
							<em>金立获2011年度“优秀会员单位”和2011年-2015年“常务副会长单位”荣誉称号<br /><span>2012年3月13日</span></em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					<li>
						<a href="/index/about_honor_4">
							<i class="ico"><img src="<?php echo $staticResPath;?>//pic/honor/4.gif" alt="" /></i>
							<em>金立荣获“2011感动福田十佳企业”称号<br /><span>2012年2月24日</span></em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					<li>
						<a href="/index/about_honor_5">
							<i class="ico"><img src="<?php echo $staticResPath;?>//pic/honor/5.gif" alt="" /></i>
							<em>金立荣获2011年“深圳市和谐劳动关系先进企业”称号<br /><span>2012年3月13日</span></em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					<li>
						<a href="/index/about_honor_6">
							<i class="ico"><img src="<?php echo $staticResPath;?>//pic/honor/6.gif" alt="" /></i>
							<em>金立荣获深圳“福田区自主创新龙头企业”称号<br /><span>2012年2月24日</span></em>
							<s><img src="<?php echo $staticResPath;?>//pic/jt.png" alt="" /></s>
						</a>
					</li>
					
				</ul>
			</div>
		</div>
	</div>
<?php echo $this->render("layout/footer.phtml");?>
