<!DOCTYPE html>
<head>
<meta charset="UTF-8">
<title>详细说明</title>
<meta name="keyword" content="金立, 金立游戏, 游戏大厅" />
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<meta name="format-detection" content="email=no" />
<link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/apkv1/assets/css/activity.css?v=<?php echo $version;?>"/>
</head>
<body>
<div class="coin-content ui-editor">
<?php echo html_entity_decode($info['hdinfo']);?>
</div>
</body>
</html>