
<!DOCTYPE HTML>
<html>
<head>
	<title>历史今天</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
	<meta name="apple-touch-fullscreen" content="yes" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="sige-full-screen" content="true" />
	<link rel="stylesheet" href="<?php echo $staticResPath;?>/calendar/css/style.min.css?v=<?=$version?>" />
</head>
<body class="ui-pg-app">
<!--<div class="ui-pg-toolbar">
	<a class="btn-back" href="index.php"></a>
	<span class="txt">历史今天</span>
</div>-->

<?php if (!empty($banner)): ?>
	<div class="mod-banner-wrap">
		<?php foreach($banner as $val):?>
			<a href="<?=$val['url']?>" target="_balnk"><img border="0" src="<?=$val['img']?>" width="100%" height="100px"></a>
		<?php endforeach;?>
		<span id="btn-close" class="close"></span>
	</div>
<?php endif;?>

<div class="mod-rili-wrap">
	<h2 class="date"><?=$showDate?></h2>
</div>
<!-- 分类栏目Tab -->
<div class="mod-card-tab">
	<div class="mod-card-nav">
		<ul class="nav">
			<li class="active">事件</li>
			<li>人物</li>
		</ul>
	</div>

	<div id="J_scroll_main" class="mod-scroll-root">
        <div class="mod-scroll-wrapper">
            <div class="mod-scroll-list">
				<div class="mod-scroll-item">
					<div class="mod-card-list">
						<?php foreach($adstxt as $val):?>
							<div class="list-item">
								<a href="<?=$val['url']?>">
									<figure class="thumb"><i class="icon-event"></i></figure>
									<div class="text">
										<h3><?=$val['title']?></h3>
										<p></p>
									</div>
								</a>
							</div>
						<?php endforeach;?>
						<?php foreach($list1 as $val):?>
						<div class="list-item">
							<a href="<?=$val['link']?>">
								<figure class="thumb"><i class="icon-clock"></i></figure>
								<div class="text">
									<h3><?=$val['title']?></h3>
									<p><?=$val['desc']?></p>
								</div>
							</a>
						</div>
						<?php endforeach;?>
					</div>
				</div>
				<div class="mod-scroll-item">
					<div class="mod-card-list">
						<?php foreach($adstxt as $val):?>
							<div class="list-item">
								<a href="<?=$val['url']?>">
									<figure class="thumb"><i class="icon-event"></i></figure>
									<div class="text">
										<h3><?=$val['title']?></h3>
										<p></p>
									</div>
								</a>
							</div>
						<?php endforeach;?>
						<?php foreach($list2 as $val):?>
						<div class="list-item">
							<a href="<?=$val['link']?>">
								<figure class="thumb"><i class="icon-clock"></i></figure>
								<div class="text">
									<h3><?=$val['title']?></h3>
									<p><?=$val['desc']?></p>
								</div>
							</a>
						</div>
						<?php endforeach;?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- load script -->
<script>
	var require = {
		urlArgs: 'v=<?=$version?>' // 异步加载文件的版本号
	};
</script>
<script data-main="<?php echo $staticResPath?>/calendar/js/main.min" src="<?php echo $staticResPath?>/calendar/js/require.min.js?v=<?=$version?>"></script>
<!-- /load script -->
</body>
</html>