<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	    <li class="current"><a href="javascript:;">编辑首页图片</a></li>
	</ul>
</div>
<div class="h_a">添加推荐banner图</div>
<form method="post" action="<?php echo $bannerEditPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="day_id" value="<?php echo $day_id;?>" type="hidden" />
<input name="id" value="<?php echo $id;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">标题(<span style="color: red">*</span>)</th>
			<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">链接类型(<span style="color: red">*</span>)</th>
			<td class="td">
				<?php foreach($linkType as $key=>$value) {?>
                <label class="mr20"><input <?php if($info['link_type'] == $key) echo 'checked';?> name="link_type" value="<?php echo $key;?>" type="radio" onclick ="showContent(<?php echo $key;?>)"><?php echo $value;?></label>
			    <?php }?>
				<span style="color: red">(选择分类时，链接ID输入框填写游戏主分类的ID)</span>
			</td>
		</tr>
		<tr class="tr">
			<th class="th" id="th_link">链接参数</th>
			<td class="td"><input type="text" class="input" name="link" id="link" value="<?php echo $info['link'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">1.5.5版本尺寸(<span style="color: red">*</span>)</th>
			<td class="td">
                <ul class="uploadImg">
					<li id="img1">
						<img src="<?php echo $attachPath.$info['img1'];?>"/>
						<input type="hidden" name="img1" value="<?php echo $info['img1'];?>">
					</li>
				</ul>			
                <p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=img1';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p><span style="color:red">客户端1.5.5及以下版本尺寸：480*209</span>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">1.5.6版本尺寸(<span style="color: red">*</span>)</th>
			<td class="td">
                <ul class="uploadImg">
					<li id="img2">
						<img src="<?php echo $attachPath,$info['img2'];?>"/>
						<input type="hidden" name="img2" value="<?php echo $info['img2'];?>">
					</li>
				</ul>			
                <p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=img2';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p><span style="color:red">客户端1.5.6尺寸：1026*450</span>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">1.5.7版本尺寸(<span style="color: red">*</span>)</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="img3">
						<img src="<?php echo $attachPath,$info['img3'];?>"/>
						<input type="hidden" name="img3" value="<?php echo $info['img3'];?>">
					</li>
				</ul>
                <p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=img3';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p><span style="color:red">客户端1.5.7及以上版本尺寸：1080*600</span>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">状态(<span style="color: red">*</span>)</th>
			<td class="td"><select name="status">
                	<option <?php if($info['status'] == 1) echo 'selected';?> value="1">开启</option>
                	<option <?php if($info['status'] == 0) echo 'selected';?> value="0">关闭</option>
            </select></td>
		</tr>
	</table>
</div>
<div class="mb10 tac">
    <span class="btn"><span><a href="<?php echo $editUrl.'?dayId='.$day_id;?>"><button type="button">返回</button></a></span></span>
    <span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
</div>
</form>
<script type="text/javascript">
showContent = function(flag) {
	if (flag != 4) {
    	 $("#th_link").html('链接ID');
    	 $("#link").removeClass('wc');
	} else {
    	 $("#th_link").html('外链接');
    	 $("#link").addClass('wc');
	}
}
$(document).ready(function(){
    showContent(<?php echo $info['link_type'];?>);
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $editUrl.'?dayId='.$day_id;?>');
	});
});
</script>
<?php echo $this->render("layout/footer.phtml");?>
