<!DOCTYPE html>
<html lang="en">
<head>
	<?php $this->title='关于我们';$this->hasSearch=false;?>
	<meta charset="UTF-8">
	<title>游戏大厅</title>
	<?php echo $this->render("layout/cssInc.phtml");?>
</head>
<body>
	<?php echo $this->render("layout/header.phtml");?>
	<div id="container">
		<div class="about-us">
			<img class="photo" src="<?php echo $appImg ?>/about-us-activity.png" />
			<div class="contact">
				<div class="private" style="padding-bottom: 40px;">
					<h3>商务合作</h3>
					    <div   class="name"> <h3>杨东</h3><span>华北区(网游和单机) </span></div>
						<div>
					       	<div  class="row">手机：18600212028</div>
						    <div  class="row">QQ：1933008049</div>
						</div>
						<div>邮箱：yangdong@gionee.com</div>
			 </div>
		     <div  class="private">
					          <div   class="name"> <h3>裘捷</h3><span>华南区(网游和单机)</span></div>
					  <div>
					          <div   class="row"> 手机：18676720261</div>
						      <div   class="row">QQ：155207860 </div>
						</div>
						<div>邮箱：qiujie@gionee.com</div>
		        </div>
				<div class="private">
					   <div   class="name"> <h3>柯娟</h3><span>华东区(网游和单机)</span></div>
					   <div>
					          <div   class="row"> 手机：13928492976</div>
						      <div   class="row">QQ：582487217 </div>
						</div>
						<div>邮箱：kejuan@gionee.com</div>
				   </div>
				<div class="private">
				    <div   class="name"> <h3>吴静</h3><span>华中区(网游和单机)  </span></div>
				    <div>
				          <div   class="row">手机：13798552358</div>
					      <div   class="row">QQ：805682612 </div>
					</div>
				    <div>邮箱：wujing@gionee.com</div>
				</div>
				<div class="official">
					<h3>官方联系方式及地扯</h3>
					<div>邮箱：game@gionee.com</div>
					<div>QQ：4006286618</div>
					<div>微信：金立游戏大厅</div>
					<div>地址：深圳市福田区深南大道7008号阳光高尔夫大厦15楼</div>
					<div>邮编：518040</div>
				</div>
				<div class="developers">
					开发者平台：<a href="http://dev.game.gionee.com/">dev.game.gionee.com</a>
				</div>
			</div>
		</div>
    </div>
    </div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>