<?php echo $this->render("layout/singleheader.phtml");?>
<body id="recruit" data-pagerole="body">
	<div class="module sec">
		<header>
			<div class="top-banner">
				<img src="<?php echo $staticResPath;?>/pic/recruit2_pic_banner.jpg">
			</div>
		</header>
		<section>
			<div class="item">
				<h2><img src="<?php echo $staticResPath;?>/pic/recruit2_pic_title1.jpg"></h2>
				<div class="main">
					<ol>
						<li><i>1</i>活动时间：<span class="f-red">3.18-3.24</span></li>
						<li>
							<em><i>2</i>报名方式：</em>
							<div class="box">
								<span class="f-red">第一步：</span>微信添加购物大厅微信号：shopping8019；<br>
								<span class="f-red">第二步：</span>微信发送“您的手机号+粉丝报名”给购物大厅小惠，例：186****9255粉丝报名；
							</div>
						</li>
						<li><i>3</i>活动结束后7个工作日内由购物大厅为报名成功的粉丝发放第二期福利：<span class="f-red">10元话费</span>；</li>
						<li><i>4</i>此次活动最终解释权归购物大厅所有；</li>
					</ol>
				</div>
			</div>
			<div class="item">
				<h2><img src="<?php echo $staticResPath;?>/pic/recruit2_pic_title2.jpg"></h2>
				<div class="main">
					<ol>
						<li>
							<em>粉丝权利：</em>
							<div class="box">
								1) 粉丝享有定期领取<span class="f-red">福利（话费、实物礼品等）</span>的权利；<br>
								2) 粉丝享有提前试用购物大厅<span class="f-red">新版本、新功能</span>的权利；<br>
								3) 粉丝享有优先参与购物大厅<span class="f-red">各种优惠活动</span>的权利；<br>
								4) 权利待补充增加~
							</div>
						</li>
						<li>
							<em>粉丝义务：</em>
							<div class="box">
								1) 粉丝有试用购物大厅新版本，<span class="f-red">提出意见和建议</span>的义务；<br>
								2) 义务待补充增加~
							</div>
						</li>
					</ol>
				</div>
			</div>
		</section>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>