<?php echo $this->render("layout/header.phtml");?>
<body id="prize" data-pagerole="body">
	<div class="module">
		<div id="iHeader" class="hd">
			<div class="title-back">
				<h1>邀请好友送话费</h1>
				<div class="back"><a href="<?php echo $webroot;?>"></a></div>
			</div>
		</div>
		
		<div id="iScroll" class="prize-wrap">
			<div class="steps">
				<div class="text-box">
					<h3>第一步：输入手机号码生成专属链接</h3>
					<div id="J_createLink" class="option">
						<input type="text" maxlength="11" placeholder="请输入您的手机号码" data-ajaxurl="<?php echo $webroot;?>/api/activity/getShareUrl" />
						<button>生成链接</button>
						<span class="t-red">请正确填写您的手机号码，将作为您获得话费的唯一凭证</span>
					</div>
					<div id="J_linkResult" class="result hidden">您的链接是：<span><?php echo $webroot;?>/activity/apkDownload</span></div>
				</div>
				<div class="text-box">
					<h3>第二步：分享链接给好友立即赚话费：</h3>
					<div class="share-list">
 						<p><a class="bshare-sinaminiblog gshare-sinaminiblog"><span class="bshare-sinaminiblog">新浪微博</span></a></p>
 						<p><a class="bshare-qqmb gshare-qqmb"><span class="bshare-qqmb">腾讯微博</span></a></p>
					</div>
					<div class="share-list bshare-custom">
					 	<p><a class="bshare-sinaminiblog gshare-sinaminiblog"><span class="bshare-sinaminiblog">新浪微博</span></a></p>
					 	<p><a class="bshare-qqmb gshare-qqmb"><span class="bshare-qqmb">腾讯微博</span></a></p>
					 </div>
					<script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/buttonLite.js#style=-1&amp;uuid=&amp;pophcol=2&amp;lang=zh"></script>
					<script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/bshareC0.js"></script>
				</div>
			</div>

			<div class="related">
				<div class="text-box">
					<h3>活动规则</h3>
					<p>按照邀请好友数量的多少进行排序,从高到低评出<em class="t-red">前100名</em>;</p>
					<div class="table-list">
						<table>
							<tr>
								<td>第<em class="t-red">1-10</em>名</td>
								<td><em class="t-red">100元</em>话费 + 时尚<em class="t-red">T恤</em>1件</td>
							</tr>
							<tr>
								<td>第<em class="t-red">11-30</em>名</td>
								<td><em class="t-red">100元</em>话费</td>
							</tr>
							<tr>
								<td>第<em class="t-red">31-50</em>名</td>
								<td><em class="t-red">50元</em>话费</td>
							</tr>
							<tr>
								<td>第<em class="t-red">51-70</em>名</td>
								<td><em class="t-red">30元</em>话费</td>
							</tr>
							<tr>
								<td>第<em class="t-red">71-100</em>名</td>
								<td><em class="t-red">10元</em>话费</td>
							</tr>
						</table>
					</div>
					<p>温馨提示: 每位<em class="t-red">被邀请</em>成功的好友均可参与抽奖,抽奖规则如下:</p>
					<div class="table-list">
						<table>
							<tr>
								<td><em class="t-red">一等奖</em>（3名）</td>
								<td><em class="t-red">100元</em>话费</td>
							</tr>
							<tr>
								<td><em class="t-red">二等奖</em>（8名）</td>
								<td><em class="t-red">50元</em>话费</td>
							</tr>
							<tr>
								<td><em class="t-red">三等奖</em>（15名）</td>
								<td><em class="t-red">20元</em>话费</td>
							</tr>
							<tr>
								<td><em class="t-red">幸运奖</em>（3名）</td>
								<td><em class="t-red">金立旅行包一个</em></td>
							</tr>
						</table>
					</div>
				</div>
				<div class="text-box">
					<h3>活动说明</h3>
					<p>1、活动时间：<em class="t-red">10月29日-11月4日</em><br />
					   2、奖品将在活动结束后10个工作日内发放；<br />
					   3、咨询QQ群[购物大厅]：<em class="t-red">237057997</em>，中奖名单将在QQ群中公布；<br />
					   4、本次活动最终解释权归购物大厅所有；<br /><br />
					</p>
				</div>
			</div>
		</div>
	</div>
<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>