<?php echo $this->render("../../Front/views/layout/header.phtml");?>
	<div id="page">
		<header class="hd">
			<h1>注册</h1>
			<div class="back">
				<a href="<?php echo $webroot?>"><span class="left-arrow"><i></i></span></a>
			</div>
		</header>
		
		<article class="ac reg-login">
			<div class="form-box">
				<form class="form-box" method="post"   id="J_login" action="<?php echo $webroot.$postUrl; ?>">
				<input type="hidden" name="token" value="<?php echo $token?>"/>
					<ul>
						<li>
							<label for="">用户名：</label>
							<input type="text" name="username" id="J_UserNameTxt" required="required" vaule="" autocomplete="off" placeholder="您的手机号" pattern="((\+86)|86|0)?(13\d|15[012356789]|18[012356789]|14[57])\d{8}$" />
						</li>
						<li>
							<label for="">密码：</label>
							<input type="password" name="password" maxLength="16" id="J_PassWordTxt" autocomplete="off" required="required" value="" placeholder="至少6位"  />
							<input type="text" name="passwd" autocomplete="off"  class="J_showText" />
						</li>
						<li class="tips">
							<span><input type="checkbox" id="checkbox_pwd" name="tips" class="J_ctrlShow"  /></span>
							<span><label for="checkbox_pwd">密码显示明文</label></span>
						</li>
						<li class="tips">已有账号？ <a href="<?php echo $webroot;?>/user/login/index?refer=<?php echo $refer;?>">立即登录</a></li>
						<li><input type="submit" name="submit" class="btn" value="注册" /></li>						
					</ul>
				</form>
			</div>
		</article>
	</div>
	
	<div class="JS-dbMask"></div>
    <div class="dialog-box J_dialogBox">
    	<p></p>
    	<div class="btn-wrap"><span class="btn">确定</span></div>
	</div>
	
<?php echo $this->render("../../Front/views/layout/footer.phtml");?>