<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    	<li class="current"><a href="<?php echo $indexUrl;?>">价格列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加价格</a></li>
	</ul>
</div>

<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">排序</td>
			<td width="30">ID</td>
			<td width="100">价格</td>
			<td width="100">显示价格范围</td>
			<td width="30">状态</td>
			<td width="120">操作</td>
		</tr>
		<?php if(!empty($list)): foreach ($list as $val):?>
		<tr class="ct">
			<td><?php echo $val['sort'];?></td>
			<td><?php echo $val['id'];?></td>
			<td><?php echo $val['price'];?></td>
			<td><?php echo $val['range'];?></td>
			<td><?php echo $val['status'] == 1 ? '开启' : '关闭';?></td>
			<td>
				<a href="<?php echo $editUrl;?>/?id=<?php echo $val['id'];?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $val['id'];?>', '', event);">删除</a>
			</td>
		</tr>
		<?php endforeach; endif;?>
	</table>
</div>

<?php echo $this->render("layout/footer.phtml");?>