<?php echo $this->render("layout/singleheader.phtml");?>
	<body data-pagerole="body">
	<div class="module">
		
		<section id="iScroll" class="about-wrap">
			<div class="avatar-wrap">
				<div class="pic">
					<img src="<?php echo "$staticResPath/assets/img/avatar.jpg";?>" alt="">
				</div>
			</div>
			<ul class="service">
				<li>
					<h3 class="settle">商家入驻</h3>
					<p>卖家/商家合作，电商平台合作，购物电商平台联盟合作，请Email: bd@gouwudating.com</p>
				</li>
				<li>
					<h3 class="prom">推广合作</h3>
					<p>如果您有关于广告投放、商务合作、渠道合作、资源互换等多种形式合作的问题，请Email: bd@gouwudating.com，或联系QQ:1754626171，并简要介绍合作需求</p>
				</li>
			</ul>
			<div class="footer">
				<div class="contact">官方QQ群：237057997</div>
				<div class="copyright">copyright © 2012 粤ICP备05087105号</div>
			</div>
		</section>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
<?php echo $this->render("layout/newfooter.phtml");?>