<?php echo $this->render("layout/header.phtml");?>
    <div class="nav">
        <ul class="cc">
            <li><a href="<?php echo $indexUrl;?>">虚拟用户列表</a></li>
            <li class="current"><a href="javascript:;">添加虚拟用户</a></li>
        </ul>
    </div>
    <div class="h_a">编辑虚拟用户</div>
    <form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
        <input name="token" value="<?php echo $token;?>" type="hidden" />
        <div class="table_full">
            <table width="100%">
                <tr class="tr">
                    <th class="th">昵称</th>
                    <td class="td"><input type="text" placeholder="显示昵称" class="input wc" name="nickname"	></td>
                </tr>
                <tr class="tr">
                    <th class="th">联系电话</th>
                    <td class="td"><input type="text" class="input wc" name="mobile" /></td>
                </tr>
                <tr class="tr">
                    <th class="th">头像</th>
                    <td class="td">
                        <ul class="uploadImg">
                            <li id="UserAuthorImg">
                                <img src="<?php echo empty($info['avatar']) ? $staticPath . '/img/content/nopic.jpg' : $attachPath.$info['img']; ?>"/>
                                <input type="hidden" name="avatar" value="<?php echo $info['avatar'];?>">
                            </li>
                        </ul>
                        <p style="clear:both;">
                            <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=UserAuthorImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
                        </p></td>
                </tr>
            </table>
        </div>
        <div class="mb10 tac">
            <span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
        </div>
    </form>
    <script type="text/javascript">
        //用户表单数据提交
        $(document).ready(function(){
            ajaxForm('addForm',function(ret){
                ajaxRedirect(ret, baseurl+'/Admin/User_Virtual/index?s=1');
            });
        })

    </script>
<?php echo $this->render("layout/footer.phtml");?>