<?php
echo $this->render("layout/header4.phtml");
echo <<<HTML
<table class="editTable">
    <tr>
		<th class="th">UID</th>
		<td class="td">$uid</td>
    </tr>
    <tr>
		<th class="th">用户名</th>
		<td class="td">$username</td>
    </tr>
	<tr>
		<th class="th">欧飞账户余额</th>
		<td class="td"><span style="color:red ">$ofpayRemained 元</span></td>
	</tr>
	<tr>
		<th class="th">畅聊账户余额</th>
		<td class="td"><span style="color:red">$voipRemained 元</span></td>
	</tr>
</table>
HTML;
echo $this->render("layout/footer.phtml");
?>