<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl; ?>">新闻列表</a></li>
		<li class="current"><a href="javascript:;">添加新闻</a></li>
	</ul>
</div>
<div class="h_a">添加新闻</div>
<form method="post" action="<?php echo $addPostUrl; ?>" id="addForm">
	<input name="token" value="<?php echo $token; ?>" type="hidden"/>

	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">排序</th>
				<td class="td"><input type="text" class="input" name="sort" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">分类</th>
				<td class="td"><select name="type_id">
						<?php foreach ($newstype as $key => $value) { ?>
							<option value="<?php echo $key; ?>"><?php echo $value['name']; ?></option>
						<?php } ?>
					</select></td>
			</tr>
			<tr class="tr">
				<th class="th">标题</th>
				<td class="td"><input type="text" class="input wc" name="title" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">颜色</th>
				<td class="td">
					<input type="text" class="input" name="color" value="">(填写颜色值，如:#1459A3,#0F8755, 不填写则显示为默认颜色)
				</td>
			</tr>

			<tr class="tr">
				<th class="th">合作商</th>
				<td class="td"><select name="parter_id" id="parter_id">
						<?php foreach ($cooperators as $k => $v) { ?>
							<option value="<?php echo $v['id'] ?>"  <?php if ($v['id'] == $urlInfo['pid']) echo 'selected'; ?>><?php echo $v['name']; ?></option>
						<?php } ?>
					</select></td>
			</tr>
			<tr class="tr" id="tr_business" style="display: <?php echo empty($blist) ? 'none' : '' ?>">
				<th class="th">业务列表</th>
				<td class="td">
					<select id="bid" name="bid">
						<option value="0">请选择</option>
						<?php foreach ($blist as $k => $v) { ?>
							<option value="<?php echo $v['id']; ?>"  <?php if ($v['id'] == $urlInfo['bid']) echo 'selected'; ?>><?php echo $v['name']; ?></option>
						<?php } ?>
					</select>
				</td>
			</tr>
			<tr class="tr" id="tr_url" style="display:<?php echo empty($urlList) ? 'none' : '' ?>">
				<th class="th">合作商链接</th>
				<td class="td">
					<select name="cp_id" id="cp_id">
						<option value="0">请选择</option>
						<?php foreach ($urlList as $k => $v) { ?>
							<option value="<?php echo $v['id']; ?>"  <?php if ($v['id'] == $urlInfo['id']) echo 'selected'; ?>><?php echo "{$v['url_name']}:{$v['url']}"; ?></option>
						<?php } ?>
					</select></td>
			</tr>

			<tr class="tr" id="tr_link">
				<th class="th">链接地址</th>
				<td class="td"><input type="text" class="input wc" name="url" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">是否广告</th>
				<td class="td">
					<input type="hidden" name="is_ad" id="is_ad" value="0"/>
					<input type="checkbox" onclick="if(this.checked){$('#is_ad').val(1);}else{$('#is_ad').val(0);}">(选中表示设置为广告)
				</td>
			</tr>
			<tr class="tr">
				<th class="th">是否置顶</th>
				<td class="td">
					<input type="hidden" name="istop" id="istop" value="0"/>
					<input type="checkbox" onclick="if(this.checked){$('#istop').val(1);}else{$('#istop').val(0);}">(选中表示设置为置顶)
				</td>
			</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td"><select name="status" class="select">
						<option value="1">开启</option>
						<option value="0">关闭</option>
					</select></td>
			</tr>
			<tr class="tr">
				<th class="th">发布时间</th>
				<td class="td"><input type="text" class="input" id="ontime"
				                      name="ontime" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">开始时间</th>
				<td class="td"><input type="text" class="input" id="start_time"
				                      name="start_time" value=""></td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script
	src="<?php echo $staticPath; ?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script
	src="<?php echo $staticPath; ?>/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
<script type="text/javascript">
	//用户表单数据提交
	$('#ontime').datetimepicker();
	$('#start_time').datetimepicker();
	$(document).ready(function () {
		ajaxForm('addForm', function (ret) {
			ajaxRedirect(ret, baseurl + '/Admin/Jhnews/index');
		});
	})


	$("#parter_id").bind('change', function () {
		var pid = $("#parter_id option:selected").val();
		if (pid > 0) {
			$.ajax({
				'type': 'post',
				'dataType': 'json',
				'data': {'token': '<?php echo $token;?>', 'pid': pid},
				'url': '/Admin/Parter/ajaxGetBussinessList',
				'success': function (e) {
					var html = "<option value='0'>请选择</option>";
					$.each(e.data, function (i, m) {
						html += "<option value='" + m.id + "'>" + m.name + "</option>";
					});
					$("#bid").html(html);
					$("#tr_business").show();
				}
			});
		} else {
			$("#tr_business").hide();
			$("#tr_url").hide();
		}
	});

	$("#bid").bind('change', function () {
		var bid = $("#bid option:selected").val();
		if (bid > 0) {
			$.ajax({
				'type': 'post',
				'dataType': 'json',
				'data': {'token': '<?php echo $token;?>', 'bid': bid},
				'url': '/Admin/Parter/ajaxGetUrlByBid',
				'success': function (e) {
					var html = "<option value='0'>请选择</option>";
					$.each(e.data, function (i, m) {
						html += "<option value='" + m.id + "'>" + m.url_name + " : " + m.url + "</option>";
					});
					//alert(html);
					$("#cp_id").html(html);
					$("#tr_url").show();
				}
			});
		} else {
			$("#tr_url").hide();
		}
	});

	$("#cp_id").bind('change', function () {
		var id = $("#cp_id option:selected").val();
		if (id > 0) {
			$("#tr_link").hide();
		} else {
			$("#tr_link").show();
		}
	})
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
