<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class="current"><a href="<?php echo $indexUrl; ?>">标签列表</a></li>
			<li class=""><a href="<?php echo $editUrl; ?>">添加标签</a></li>
			<li class=""><a href="<?php echo $importUrl; ?>">数据导入</a></li>
		</ul>
	</div>
	<div class="table_full">
		<form action="<?php echo $indexUrl; ?>" method="POST" id="form">
			<input type="hidden" name="token" value="<?php echo $token; ?>"/>
			<table width="100%" cellspacing="0" cellpadding="0">
			<?php if(empty($preData)){ ?>
				<tr class="tr"  id="tr_label_first">
					<th class="th">一级分类：</th>
					<td class="td">
						<select name="label[1]" id="label_first">
							<option value="0">请选择</option>
							<?php foreach ($fristLevel as $k => $v) { ?>
								<option <?php echo ($v['id'] == $params['first_level']) ? 'selected="selected"' : ''; ?> value="<?php echo $v['id']; ?>"><?php echo $v['name']; ?></option>
							<?php } ?>
						</select>
					</td>
				</tr>
			<?php }else { 
				$i = 1;
				 foreach ( $preData  as $key=>$val ){?>
						<tr class="tr"  id="tr_<?php  echo $trNames[$i]; ?>">
						<th class="th"><?php echo $labelNames[$i];  ?>：</th>
						<td class="td">
							<select name="label[<?php echo $i;?>]"  id="label_first">
								<option value="0">请选择</option>
								<?php foreach ($val as $m => $n) { ?>
									<option   value="<?php echo $n['id']; ?>"  <?php if($key == $n['id']) echo 'selected';?>><?php echo $n['name']; ?></option>
								<?php } ?>
							</select>
						</td>
					</tr>
				<?php 
				$i++;
			} 
			}?>
			</table>
			<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
			</div>
		</form>
	</div>

	<div class="table_list">
		<table width="100%">
			<tr class="hd">
				<td width="5%">序号</td>
				<td width="10%">名称</td>
				<td width="10%">上一级分类</td>
				<td width="8%">状态</td>
				<td width="12%">添加时间</td>
				<td width="10%">操作</td>
			</tr> 
			<?php foreach ($dataList as $key => $value) {?>
				<tr class="ct">
					<td><?php echo $value['id']; ?></td>
					<td><?php echo $value['name']; ?></td>
					<td><?php echo $value['parent_name']; ?></td>
					<td><?php echo $value['status'] == 1 ? '开启' : "关闭" ?></td>
					<td><?php echo date('Y-m-d H:i:s', $value['add_time']); ?></td>
					<td><a href="<?php webroot; ?>/Admin/Label/edit?id=<?php echo $value['id']; ?>">编辑</a>
						<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id= <?php echo $value['id']; ?>', '', event);">删除</a>
					</td>
				</tr>
			<?php } ?>
		</table>
	</div>
	<div class="mr10 cc"><?php echo $pager; ?></div>

	<script src="<?php echo $staticPath; ?>/js/common/jquery-ui-timepicker.js"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			$('#start_time').datetimepicker();
			$('#end_time').datetimepicker();
		});

		$("#label_first").bind('change', function () {
			var pid = $("#label_first").val();
			parseData(pid,'label_second',  'label[2]', 'label_first','二级分类');
		});

		$("#label_second").live('change', function () {
			var pid = $("#label_second  option:selected").val();
			parseData(pid,'label_three',  'label[3]', 'label_second','三级分类');
		});

		$("#label_three").live('change', function () {
			var pid = $("#label_three option:selected").val();
			parseData( pid,'label_four',  'label[4]', 'label_three','四级分类');
		});

		$("#label_four").live('change', function () {
			var pid = $("#label_four option:selected").val();
			parseData(pid,'label_five',  'label[5]', 'label_four','五级分类');
		});

		function parseData( pid, label,selected_name, pre_label,name) {
			if(pid <=0) return false;
			$.ajax({
				'type': 'post',
				'dataType': 'json',
				'url': '/Admin/Label/ajaxGetCategoryData',
				'data': {'token': '<?php echo $token;?>', 'pid': pid},
				'success': function (e) {
					if (e.data) {
						var html = '<tr class="tr"  id="tr_' + label + '"><th class="th">'+name+'</th><td class="td"><select name="' + selected_name + '" id="' + label + '"><option value="0">请选择</option><option value="-1">全部子标签</option>';
						$.each(e.data, function (i, m) {
							html += '<option value="' + m.id + '">' + m.name + '</option>';
						})
						html += '</select></td></tr>';
						console.log(html);
						if ($("#tr_" + label)[0]) {
							$("#tr_" + label).html(html);
						} else {
							$("#tr_" + pre_label).after(html);
						}
					}
				}
			});
		}
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>