<?php echo $this->render("layout/header.phtml");?>
<body id="brandIntro">
	<div class="gotop">
		<span>返回顶部</span>
	</div>
	<div class="module gray-bg webapp">
		<header class="header" id="J_header">
			<div class="wrap">
				<div class="title">
					<a href="<?php echo $webroot;?>" class="back"></a>
					<a href="/" class="back-home" onclick="baiduStatic('品牌汇', '品牌汇-返回首页', '品牌汇-返回首页点击次数')"></a>
					<h1><?php echo html_entity_decode($brand['name']);?></h1>
				</div>
			</div>
		</header>
		<div class="iScroll" id="J_scrollWrap">
			<div class="layout-center">
				<div class="brand-intro">
					<div class="banner-pic">
						<img src="<?php echo $staticRoot;?>/apps/dhm/asset/img/blank.gif" data-src="<?php echo Common::getAttachPath().$brand['image'];?>">
					</div>
					<article class="article">
						<h1><?php echo html_entity_decode($brand['name']);?></h1>
						<?php echo html_entity_decode($brand['brand_desc']);?>
					</article>
				</div>
			</div>
			<div class="divide-section"></div>
			<section class="layout-center">
				<ul id="J_listWrap" data-ajaxUrl="<?php echo $webroot;?>/api/goods/index?is_recommend=1&brand_id=<?php echo $id;?>&refer=<?php echo urlencode($webroot.'/brand/detail?id='.$id);?>"></ul>
			</section>
		</div>

		<script type="text/template" id="J_template">
		<%for(var i=0, len=list.length; i<len; i++) {%>
			<li class="goods-list">
				<a class="list-wrap" href="<%=list[i].link%>">
					<div class="pic">
						<img src="<?php echo $staticRoot;?>/apps/dhm/asset/img/blank.gif" data-src="<%=list[i].img%>" alt="<%=list[i].title%>">
					</div>
					<div class="content">
						<h3><%=list[i].title%></h3>
						<p class="price">海淘价：<i class="dollar">￥</i><em><%=(list[i].min_price == list[i].max_price) ? list[i].min_price : (list[i].min_price + '-' + list[i].max_price)%></em></p>
						<p class="origin-info">
							<span class="country-pic">
								<img src="<?php echo $staticRoot;?>/apps/dhm/asset/img/blank.gif" data-src="<%=list[i].logo ? list[i].logo : '<?php echo $staticRoot;?>/apps/dhm/asset/img/icon-country-default.png'%>">
							</span>
							<span class="country"><%=list[i].country%></span>
							<span><%=list[i].brand%></span>
						</p>
					</div>
				</a>
			</li>
		<%}%>
		</script>
	</div>


<?php echo $this->render("layout/footer.phtml");?>