<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">地址列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加地址</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">id</th>
			<td class="td">
			<input type="text" class="input" name="id" value="<?php echo $search['id'];?>">	
			</td>
			<th class="th">名称</th>
            <td class="td">
                <input class="input" type="text" name="name" value="<?php echo $search['name'][1];?>">
            </td>		
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">ID</td>
			<td width="100">名称</td>
			<td>地址</td>
			<td width="400">外链地址</td>
			<td width="40">点击量</td>
			<td width="40">渠道号</td>
			<td width="80">操作</td>
		</tr>
<?php foreach($suppliers as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['name'];?></td>
			<td><?php echo $value['url'];?></td>
			<td><?php echo 'http://gou.gionee.com/index/redirect?url_id='.$value['id'];?></td>
			<td><a href="/admin/stat/click?type_id=1&item_id=<?php echo $value['id'];?>" target="_blank"><?php echo $value['hits'];?></a></td>
			<td><?php echo $value['channel_code'];?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
