<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">论坛管理</a></li>
		<li><a href="<?php echo $addGameUrl;?>">添加论坛</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
		    <th class="th">游戏id</th>
		    <td class="td"><input type="text" class="input" name="game_id" value="<?php echo empty($search['game_id'])?'':$search['game_id'];?>" maxlength="10"></td>
			 <th class="th">游戏名称</th>
		  <td class="td"><input type="text" class="input" name="name" value="<?php echo empty($search['name'])?'':$search['name'];?>" maxlength="20"></td>
		</tr>
		<tr class="tr">
		  <th class="th">状态</th>
			<td class="td">
			<select name="status" class="wa">
			    <option  value="0">全部</option>
				<option <?php if($search['status'] == 2) echo 'selected';?> value="2">开启</option>
				<option <?php if($search['status'] == 1) echo 'selected';?> value="1">关闭</option>
			</select>
			</td>
			<th class="th">开始结束时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo $search['start_time']?>" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="<?php echo $search['end_time']?>" /></div>
			</td>
			
		</tr>
	
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="action" id="action" type="hidden" value="" />
<div class="h_a">
	<span class="btn2">
	   <span><button onclick="$('#action').val('open');" type="submit">开启</button></span>
	</span>
	<span class="btn2">
	   <span><button onclick="$('#action').val('close');" type="submit">关闭</button></span>
	</span>
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td><input type="checkbox" onclick="checkAll('.checkbox')"></td> 
		    <td >游戏ID</td>	
		    <td>图标</td> 
		    <td>名称</td>   
			<td>有效时间</td>
			<td>失效时间</td>
			<td>论坛地址</td>
			<td>状态</td>
			<td>操作</td>
		</tr>
<?php foreach($bbs as $key => $value) {?>
		<tr class="ct">
		    <td><input class="checkbox" name="ids[]" value="<?php echo $value['id'];?>" type="checkbox"></td>		
			<td><?php echo $value['game_id'];?></td>
			<td><img src="<?php echo $game_info[$value['game_id']]['img']; ?>" style="width:7.2em;height:7.2em" /></td>	
			<td><?php echo $game_info[$value['game_id']]['name']; ?></td>	
		    <td><?php echo date('Y-m-d H:i:s', $value['start_time']);?></td>
		    <td><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
		    <td><?php echo $value['url'];?></td>
			<td><?php echo $value['status'] == 1 ? '<font color="red">开启</font>' : '关闭';?></td>
			<td>
				<a href="<?php echo $editSetUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
</form>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Bbs_Manage/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
