<?php echo $this->render("layout/admin_header.phtml");?>

	<div class="body">
	<h1 class="page-title" >添加关键词</h1>
		<?php echo $this->render("layout/side.phtml");?>
		<div class="col-main">
			<div class="J_gift_error_tips error-pop-tips hidden">
			</div>
			<div class="keyword-body">
				<h2 class="title">添加(编辑)关键词</h2>
				<div class="keyword-edit-container">
					<div class="keyword-column-container">
						<span class="text">关键词:</span>
						<div class="keyword-container">
							<input id="keyword" class="input" />
							<span class="tips dark">多个关键词注意使用分号间隔，如李白;杜甫</span>
						</div>
					</div>
					<div class="keyword-column-container">
						<span class="text">类型:</span>
						<div class="type-container">
							<input id="fullMatch" type="radio" name="type" checked value="full" ><label for="fullMatch">&nbsp;完全匹配&nbsp;&nbsp;（用户输入完全一样的词才会触发）</label><br/>
							<input id="blurMatch" type="radio" name="type" value="blur" ><label for="blurMatch">&nbsp;模糊匹配&nbsp;&nbsp;（只要用户输入的词包含本关键词才会触发）</label>
						</div>
					</div>
					<div class="keyword-column-container">
						<span class="text">触发事件:</span>
						<div class="event-container">
							<input id="textEvent" type="radio" name="event" checked="checked" value="text" ><label for="textEvent">&nbsp;文本消息&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
							<input id="appMsg" type="radio" name="event"  value="appMsg" ><label for="appMsg">&nbsp;图文消息&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
							<input id="systemReply" type="radio" name="event" value="sysReply" ><label for="systemReply">&nbsp;系统回复</label>
							<textarea id="textTypeArea" val="" class=""></textarea>
							<div class="J_appMsg appMsg-container hidden">
								<a id="chooseMsg" class="btn-upload">选择图文</a>&nbsp;&nbsp;&nbsp;
								<span id="appMsgName" class="name dark">已选择: </span>
							</div>
							<div class="J_sysReply sysReply-container hidden">
								<select id="reply">
									<option value="acoin">A币查询</option>
									<option value="gift">礼包查询</option>
								</select>
							</div>
						</div>
					</div>

					<div class="btn-container">
						<button id="keywordSave" class="btn" data-id="" data-ajaxUrl="<?php echo $addPostUrl;?>" >保存</button>
						<a href="<?php echo $listUrl?>" class="btn">取消</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="J_dialog hidden">
		<div id="mask" ></div>
		<div id="appMsg_Dialog" >
			<div class="title-container">
				<span>选择素材</span>
				<i class="J_close icon-close">X</i>
			</div>
			<iframe width="800" height="512" frameborder="0" name="appMsg_Iframe"  src="<?php echo $materialDialogUrl;?>"></iframe>
			<div class="btn-container iframe-Dialog-btn no-topborder">
				<button id="chooseAppMsg" class="btn">确定</button>
				<button  class="J_close btn">取消</button>
			</div>
		</div>
	</div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>