<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $hdListUrl;?>">活动信息</a></li>
		<li class="current"><a href="<?php echo $listUrl;?>">送礼包</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
	    <tr>
		   <th class="th">活动类型</th>
			<td class="td">
			<select name="activity_type" class="select wa">
			        <option selected="" value="0">全部</option>
				    <?php foreach($activityType as $key=>$val) {?>   
					<option value="<?php echo $key;?>" <?php if($search['activity_type'] == $key) echo 'selected';?>><?php echo $val;?></option>					
					<?php }?> 
			</select>
			</td>
			<th class="th">状态</th>
			<td class="td">
			<select name="status" class="wa">
					<option selected="" value="0">全部</option>
    			    <option value="2" <?php if ($search['status'] == 2) echo 'selected="selected"';?>>开启</option>
    			    <option value="1" <?php if ($search['status'] == 1) echo 'selected="selected"';?>>关闭</option>
			    </select>
			</td>
		</tr>
	    <tr class="tr">
			<th class="th">活动时间</th>
			<td class="td" colspan="4"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="effect_start_time" name="effect_start_time" value="<?php echo $search['effect_start_time'];?>" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="effect_end_time" name="effect_end_time" value="<?php echo $search['effect_end_time'];?>" /></div>
			</td>
		</tr>
		 <tr class="tr">
			<th class="th">活动名称关键字</th>
			<td class="td"><input type="text" class="input" name="title" value="<?php echo $search['title'];?>"></td>
			<th class="th">游戏名称关键字</th>
			<td class="td"><input type="text" class="input" name="name" value="<?php echo $search['name'];?>"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="action" id="action" type="hidden" value="" />
<div class="h_a">
	<span class="btn2"><span><button onclick="$('#action').val('sort');" type="submit">重新排序</button></span></span>
    <span class="btn2"><span><a href="<?php echo $addUrl;?>" style="text-decoration:none;color:#ffffff;height: 21px;margin: 0 -9px;padding: 0 10px;line-height: 21px;padding-bottom: 2px;">添加礼包活动</a></span></span>
    <span>&nbsp;&nbsp;&nbsp;&nbsp;共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td><input type="checkbox" onclick="checkAll('.checkbox')"></td>
			<td width="50">排序</td>
			<td width="50">活动ID</td>
			<td width="200">活动名称</td>
			<td width="50">游戏ID</td>
			<td width="100">游戏名称</td>
			<td>活动开始/结束时间</td>
			<td>活动类型</td>
			<td>礼包类型</td>
			<td>进度</td>
			<td width="30">活动状态</td>
			<td width="120">操作</td>
		</tr>
<?php foreach($activities as $key => $value) {?>
		<tr class="ct">
		    <td><input class="checkbox" name="ids[]" value="<?php echo $value['id'];?>" type="checkbox"></td>
			<td><input type="text" class="input" style="width:30px" name="sort[<?php echo $value['id'];?>]" value="<?php echo $value['sort'];?>"></td>
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><?php echo $value['game_id'] ? $value['game_id'] : '';?></td>
			<td><?php echo $gameNames[$value['game_id']];?></td>
			<td><?php echo date('Y-m-d H:i:s', $value['effect_start_time']);?><br><?php echo date('Y-m-d H:i:s', $value['effect_end_time']);?></td>
			<td><?php echo $activityType[$value['activity_type']];?></td>
			<td><?php echo $giftNumType[$value['gift_num_type']];?></td>
			<td><?php echo $giftRemain[$value['id']].'/'.$value['gift_number'];?></td>
			<td><?php echo $value['status'] ? '开启' : '关闭';?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="<?php echo $logUrl.'?id='.$value['id'];?>" class="mr10">激活码管理</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script>
$(document).ready(function(){
	$('#effect_start_time').datetimepicker();
    $('#effect_end_time').datetimepicker();    
	ajaxForm('batchForm', function(data) {
		ajaxRedirect(data, baseurl+'/Admin/Client_Giftactivity/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
