<!DOCTYPE HTML>
<html>
<head>
	<title>今日看点</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
	<meta name="apple-touch-fullscreen" content="yes" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<meta name="format-detection" content="telephone=no" />
	<meta id="gn-meta-fullscreen" name="full-screen" content="yes" />
	<link rel="stylesheet" href="<?php echo $staticResPath;?>/read/css/style.min.css?v=<?=$version?>" />
</head>
<body class="ui-pg-app">

<!-- 分类栏目Tab -->
<div class="mod-card-tab">
	<div class="mod-card-nav">
		<div id="J_scroll_tap" class="wrapper">
			<div class="scroller">
				<ul class="nav"></ul>
			</div>
		</div>
		<span id="plus" class="icon-plus active"></span>
	</div>

	<div id="J_scroll_wrap" class="mod-scroll-wrap">
		<div class="mod-card-scroll">
			<div class="wrapper">
				<div id="pullDown" style="display: none;">
					<span class="pullDownIcon"></span><span class="pullDownLabel">下拉加载聊天记录...</span>
				</div>
				<div class="mod-card-list">

				</div>
				<div id="pullUp" style="display: none;">
					<span class="pullUpIcon"></span><span class="pullUpLabel">上滑加载</span>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- 弹窗的栏目分类 -->
<div id="J_pop_mask" class="ui-pg-mask" style="display:none;"></div>
<div id="J_pop_cate" class="ui-pg-cate" style="display:none;">
	<div class="hd">
		<h2>频道管理</h2>
		<span id="done">完成</span>
	</div>
	<div class="bd">
		<h3>已添加</h3>
		<div id="J_had_add" class="had-add">
			<p data-lock="true" data-num="1"><span><i></i>头条</span></p>

		</div>
		<h3 id="J_non_tit">点击添加更多栏目</h3>
		<div id="J_non_add" class="had-add non-add">

		</div>
	</div>
</div>
<!-- 正在加载中 -->
<div id="J_net_loading" class="G-animate-load-wrap layout-fixed" style="display:none;">
	<div>
		<span class="loading"></span>
		<span class="txt">正在加载…</span>
	</div>
</div>
<!-- 无网络连接 -->
<div id="J_net_error" class="net-pg-df" style="display: none;">
	<img src="<?php echo $staticResPath;?>/read/pic/unnetwork.png" />
	<p>数据获取失败，请检查网络连接并重试</p>
</div>

<!-- load script -->
<script>
    var require = {
        urlArgs: 'v=<?=$version?>' // 修改这里的版本号
    };
</script>
<script data-main="<?php echo $staticResPath;?>/read/js/main.min.js" src="<?php echo $staticResPath;?>/read/js/require.min.js?v=<?=$version?>"></script>
<!-- /load script -->
</body>
</html>