<?php echo $this->render("layout/header3.phtml"); ?>

	<div data-options="region:'center',split:true,border:false" style="overflow: hidden;">

		<div id="datagrid_toolbar" style="padding:5px;">
			<div style="float: left;">
				<form method="post" id="search_form" style="padding: 0px;" >
				    标签:<input name="filter[content]" style="width: 60px" value=""/>
					渠道:
					<select id="type" name="filter[type]">
					   <option value="">全部</option>
						<?php
						//$types[''] = '全部';
						foreach ($types as $k => $v) {
							echo sprintf('<option value="%s">%s</option>', $k, $v);
						}
						?>
					</select>
					<input name="token" value="<?php echo $token; ?>" type="hidden"/>
					<input name="togrid" value="1" type="hidden"/>
					导出:<input name="export" value="1" type="radio"/>是<input name="export" value="0" type="radio"/>否
					<button name="export1" type="submit">导出</button>
					<a href="javascript:search(datagrid,'#search_form');" class="easyui-linkbutton" iconCls="icon-search" plain="true">查 询</a>
				</form>
			</div>
			<div align="left">
				<a href="#" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="add()">新增</a>
				<span class="toolbar-btn-separator"></span>
				<a href="#" class="easyui-linkbutton" iconCls="icon-edit" plain="true" onclick="edit()">编辑</a>
				<span class="toolbar-btn-separator"></span>
				<a href="#" class="easyui-linkbutton" iconCls="icon-remove" plain="true" onclick="del()">删除</a>

				<span class="toolbar-btn-separator"></span>
				<a href="#" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="importdata()">导入</a>
				<block name="button"></block>
				<a href="#"></a>
			</div>
		</div>
		<table id="datagrid" toolbar="#datagrid_toolbar" border="false"></table>
	</div>


	<script>
		var token = "<?php echo $token;?>";
		var edit_W = 500;
		var edit_H = 400;
		var datagrid;
		$(function () {
			//数据列表
			datagrid = $("#datagrid").datagrid({
				url: '<?=$keylistUrl;?>',
				queryParams: {'togrid': 1, 'token': token},
				fit: true,
				autoRowHeight: false, //自动行高
				border: false,
				pagination: true, //分页栏
				pagePosition: 'bottom', //分页栏位置
				rownumbers: true,//显示行数
				striped: true,//显示条纹
				showFooter: true, //显示统计行
				pageSize: 20,//每页记录数
				remoteSort: true,//是否通过远程服务器对数据排序
				singleSelect: false,//只允许选择单行
				// main content

				sortName: 'id',//默认排序字段
				sortOrder: 'desc',//默认排序方式 'desc' 'asc'
				idField: 'id',
				columns: [[
					{field: 'id', title: 'ID', sortable: false, align: 'center', width: 60},
					{field: 'name', title: '名称', sortable: false, width: 100},
					{field: 'content', title: '内容', sortable: false, width: 200},
					{field: 'key_tag', title: '标签', sortable: true, width: 150},
					{field: 'type', title: '渠道', sortable: false, align: 'center', width: 100},
					{field: 'status', title: '状态', sortable: false, width: 60},
					{field: 'created_at', title: '建立时间', sortable: false, align: 'center', width: 120},
					{field: 'updated_at', title: '更新时间', sortable: false, align: 'center', width: 120},
				]],

				onLoadSuccess: function () {
					$(this).datagrid('clearSelections');//取消所有的已选择项
					$(this).datagrid('unselectAll');//取消全选按钮为全选状态
				},
				onRowContextMenu: function (e, rowIndex, rowData) {
					e.preventDefault();
					$(this).datagrid('unselectAll');
					$(this).datagrid('selectRow', rowIndex);
					$('#datagrid_menu').menu('show', {
						left: e.pageX,
						top: e.pageY
					});
				},
				onDblClickRow: function (rowIndex, rowData) {
					edit(rowIndex, rowData);
				}
			});

		});


		function add() {
			addData("添加", "#edit_form", datagrid, "<?=$keyeditUrl;?>", edit_W, edit_H);
		}
		function importdata() {
			addData("导入", "#edit_form", datagrid, "<?=$keyimportUrl;?>", edit_W, edit_H);
		}
		function edit(rowIndex, rowData) {
			editData(rowIndex, rowData, "编辑", '#edit_form', datagrid, "<?=$keyeditUrl;?>", edit_W, edit_H, 'id');
		}
		function del() {
			delData(datagrid, "<?=$keydelUrl;?>");
		}
	</script>
<?php echo $this->render("layout/footer3.phtml"); ?>