<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li class=""><a href="<?php echo $scoreUrl; ?>">积分总表</a></li>
			<li class="current"><a href="<?php echo $addUrl; ?>">添加积分</a></li>
		</ul>
	</div>
	<div class="table_full">
		<table width="100%">
		
			<tr class="tr">
				<td class="th">赠送金币原因：</td>
				<td class="td">
					<input id="reason" name="reason" class="input" type="text" width="100px;" value="<?php echo $reason; ?>">
				</td>
			</tr>
			
			<tr class="tr">
				<td class="th">手机号：</td>
				<td class="td">
					<input id="tel" name="tel" class="input" type="text" width="100px;" value="<?php echo $phoneNumber; ?>">
				</td>
			</tr>
			<tr class="tr">
				<td class="th">添加积分数:</td>
				<td class="td"><input id="scores" name="scores" class="input"></td>
			</tr>
		</table>
		<div class="mb10 tac" style="width: 500px;"><span class="btn"><span><button onfocus="blur();" type="button" id="submitBt">提交</button></span></span>
		</div>
		<input type="hidden" name="export" id="export" value="0">
	</div>
	<script>
		$("#submitBt").bind('click', function () {
			var tel = $("#tel").val();
			var score = $("#scores").val();
			var reason = $("#reason").val();
			var pattern = /^0?1[3|4|5|7|8][0-9]\d{8}$/;
			if (!pattern.test(tel)) {
				alert('请测查手机号是否正确！');
				return false;
			}
		
			if (confirm('确定要给' + tel + '的用户增加' + score + '的积分?')) {
				$.ajax({
					'url': '/Admin/Logs/ajaxAddScore',
					'type': 'post',
					'dataType': 'json',
					'data': {'token': '<?php echo $token;?>', 'username': tel, 'score': score,'reason':reason},
					'success': function (e) {
						if (!e.success) {
							alert(e.msg);
						} else {
							alert(e.msg);
							location.reload();
						}
					}
				});
			}
		});
	</script>
	<style>
		.th {
			width: 120px;
		}

	</style>
<?php echo $this->render("layout/footer.phtml"); ?>