<?php echo $this->render("layout/header3.phtml"); ?>

	<div data-options="region:'center',split:true,border:false" style="overflow: hidden;">

		<div id="datagrid_toolbar" style="padding:5px;">
			<div style="float: left;">

			</div>

		</div>
		<table id="datagrid" toolbar="#datagrid_toolbar" border="false"></table>
	</div>


	<script>
		var token = "<?php echo $token;?>";
		var edit_W = 500;
		var edit_H = 400;
		var datagrid;
		$(function () {
			//数据列表
			datagrid = $("#datagrid").datagrid({
				url: '<?php echo $feedbackUrl;?>',
				queryParams: {'togrid': 1, 'token': token},
				fit: true,
				autoRowHeight: false, //自动行高
				border: false,
				pagination: true, //分页栏
				pagePosition: 'bottom', //分页栏位置
				rownumbers: true,//显示行数
				striped: true,//显示条纹
				showFooter: true, //显示统计行
				pageSize: 20,//每页记录数
				remoteSort: true,//是否通过远程服务器对数据排序
				singleSelect: false,//只允许选择单行
				// main content

				sortName: 'id',//默认排序字段
				sortOrder: 'desc',//默认排序方式 'desc' 'asc'
				idField: 'id',
				columns: [[
					{field: 'id', title: 'ID', sortable: false, align: 'center', width: 60},
					{field: 'key', title: '类型', sortable: false, width: 80},
					{field: 'content', title: '内容', sortable: false, width: 200},
					{field: 'openid', title: '用户', sortable: false, align: 'center', width: 200},
					{field: 'created_at', title: '添加时间', sortable: false, align: 'center', width: 120},
				]],

				onLoadSuccess: function () {
					$(this).datagrid('clearSelections');//取消所有的已选择项
					$(this).datagrid('unselectAll');//取消全选按钮为全选状态
				}
			});

		});


		function del() {
			delData(datagrid, "<?php echo $feedbackdelUrl;?>");
		}
	</script>
<?php echo $this->render("layout/footer3.phtml"); ?>