<?php echo $this->render("layout/header.phtml");?>
<style type="text/css">
.block {
	width:95%;
 	height:20px; 
 	line-height:20px; 
	margin:2px;
 	border:1px solid #e5e3e3;
	text-align:center;
}
.block2{
	color:red;
}
#prize_layout td{
	background: #f9f9f9;
}
</style>
<div class="nav">
	<ul class="cc">
	     <li><a href="<?php echo $indexUrl;?>">积分抽奖</a></li>
        <li class="current"><a href="javascript:void();">编辑抽奖活动</a></li>
	</ul>
</div>
<?php $flag = ($prize["end_time"] < time()) ? 3 : (($prize["start_time"] < time()) ? 2 : 1); ?>
<form action="<?php echo $editPostUrl;?>/?id=<?php echo $prize['id'];?> " method="post" id="editForm">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">	
	   <tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="title" value="<?php echo $prize['title'];?>"></td>
		</tr>
		<tr class="tr">
		    <th class="th">抽奖时间</th>
			<td class="td" colspan="2">
			<div>
				<input class="input" type="text" maxlength="30" style="width:143px;" id="<?php echo ($flag > 1 && $prize['status'] == 1)? '' :'start_time'?>" name="start_time" value="<?php echo date('Y-m-d H:i:s', $prize['start_time']);?>" readonly="<?php echo ($flag > 1 && $prize['status'] == 1)? 'true' :''?>" /> 
				至 
				<input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="<?php echo date('Y-m-d H:i:s', $prize['end_time']);?>" />
			</div>
			</td>
		</tr>
		<tr class="tr">
		    <th class="th">活动图片</th>
			<td class="td" colspan="2">
			<ul class="uploadImg">
					<li id="AdImg">
						<img src="<?php echo $attachPath.$prize['img'];?>"/>
						<input type="hidden" name="img" value="<?php echo $prize['img'];?>">
					</li>
				</ul>			
				<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">最低版本</th>
			<td class="td"><input type="text" class="input" name="version" value="<?php echo $prize['version'];?>"> 默认1.5.5以上版本皆可参与</td>
		</tr>
		<tr class="tr">
			<th class="th">消耗积分</th>
			<td class="td"><input type="text" class="input" name="point" value="<?php echo $prize['point'];?>"> <span><font color="#FF0000">请填写大于0的正整数。</font></span> </td>
		</tr>
		<tr class="tr">
			<th class="th">活动说明</th>
			<td class="td"><textarea style="width: 800px; height: 300px" class="textarea" name="descript"><?php echo $prize['descript'];?></textarea>
			</td>
		</tr> 
		</table>
		<div id ="prize_config">
		<table width="100%">
		<tr class="tr">
			<td colspan="2"><div class="h_a">配置奖项</div></td>
		</tr> 
		<?php foreach ($config as $item):?>
		<tr class="tr">
			    <th class="th">
				 <table width ="100px;" id="prize_layout">
					<tr>
					 <td width ="33%"><div class="block <?php echo ($item['pos'] == '1') ? 'block2' : '';?>"><span><?php echo ($item['pos'] == '1') ? '添加' : '1';?></span></div></td>
					 <td width ="33%"><div class="block <?php echo ($item['pos'] == '2') ? 'block2' : '';?>"><span><?php echo ($item['pos'] == '2') ? '添加' : '2';?></span></div></td>
					 <td width ="33%"><div class="block <?php echo ($item['pos'] == '3') ? 'block2' : '';?>"><span><?php echo ($item['pos'] == '3') ? '添加' : '3';?></span></div></td>
					</tr>
					<tr>
					 <td width ="33%"><div class="block <?php echo ($item['pos'] == '8') ? 'block2' : '';?>"><span><?php echo ($item['pos'] == '8') ? '添加' : '8';?></span></div></td>
					 <td width ="33%"><div class="block"><span></span></div></td>
					 <td width ="33%"><div class="block <?php echo ($item['pos'] == '4') ? 'block2' : '';?>"><span><?php echo ($item['pos'] == '4') ? '添加' : '4';?></span></div></td>
					</tr>
					<tr>
					 <td width ="33%"><div class="block <?php echo ($item['pos'] == '7') ? 'block2' : '';?>"><span><?php echo ($item['pos'] == '7') ? '添加' : '7';?></span></div></td>
					 <td width ="33%"><div class="block <?php echo ($item['pos'] == '6') ? 'block2' : '';?>"><span><?php echo ($item['pos'] == '6') ? '添加' : '6';?></span></div></td>
					 <td width ="33%"><div class="block <?php echo ($item['pos'] == '5') ? 'block2' : '';?>"><span><?php echo ($item['pos'] == '5') ? '添加' : '5'?></span></div></td>
					</tr>
			    </table>
			   </th>
			   <td class="td">
				<div class="table_full" width ="500px;">
					<table width="100%">	
	   					<tr class="tr">
							<th class="th">奖品类型</th>
							<td class="td">
								<input type="hidden" name="prize_cid_<?php echo $item['pos']?>" value="<?php echo $item['id']?>"/>
								<input type="hidden" name="prize_pos_<?php echo $item['pos']?>" value="<?php echo $item['pos']?>"/>
								<select name="prize_type_<?php echo $item['pos']?>" class="select wa" pos="<?php echo $item['pos']?>" readonly="<?php echo ($flag > 1)? 'true' :''?>" >
  									<option <?php echo ($item['type'] == '1') ? 'selected':'';?> value="1">实体</option>
  									<option <?php echo ($item['type'] == '2') ? 'selected':'';?> value="2">A券</option>
  									<option <?php echo ($item['type'] == '3') ? 'selected':'';?> value="3">积分</option>
  									<option <?php echo ($item['type'] == '0') ? 'selected':'';?> value="0">不中</option>
								</select>
								&nbsp;&nbsp;&nbsp;&nbsp;
								<input type="text" class="input" name="prize_amount_<?php echo $item['pos']?>" value="<?php echo $item['amount']?>" <?php echo ($flag > 1)? 'readonly' :''?> style="display: none;">
								<span id="prize_tips_<?php echo $item['pos']?>"></span>
			 				</td>
						</tr>
						<tr class ="tr input_<?php echo $item['pos']?> day_<?php echo $item['pos']?>" style="display: none;">
							<th class="th">有效期</th>
							<td class="td">
								<input type="text" class="input" name="prize_day_<?php echo $item['pos']?>" value="<?php echo $item['day']?>"  <?php echo ($flag > 1)? 'readonly' :''?> > 天 请填写大于0的正整数
							</td>
						</tr>
						<tr class="tr input_<?php echo $item['pos']?>">
							<th class="th">奖品名称</th>
							<td class="td"><input type="text" class="input" name="prize_title_<?php echo $item['pos']?>" value="<?php echo $item['title']?>" ></td>
						</tr>
						<tr class="tr">
		   					 <th class="th">奖品图片</th>
								<td class="td" colspan="2">
									<ul class="uploadImg">
										<li id="AdImg<?php echo $item['pos']?>">
											<img src="<?php echo $attachPath.$item['img'];?>"/>
											<input type="hidden" name="prize_img_<?php echo $item['pos']?>" value="<?php echo $item['img']?>">
										</li>
									</ul>			
									<p style="clear:both;">
	                  					<iframe name="upload" src="<?php echo $uploadUrl?>/?imgId=AdImg<?php echo $item['pos']?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
									</p>
								</td>
						</tr>
						<tr class="tr input_<?php echo $item['pos']?>">
							<th class="th">中奖概率</th>
							<td class="td"><span><input type="text" class="input" name="prize_probability_<?php echo $item['pos']?>" value="<?php echo $item['probability']?>" > <span><font color="#FF0000">此处填写【0-1000000】的整数。</font></span> </span></td>
						</tr>
						<tr class="tr input_<?php echo $item['pos']?>">
							<th class="th">发放最小间隔</th>
							<td class="td"><span><input type="text" class="input" name="prize_min_space_<?php echo $item['pos']?>" value="<?php echo $item['min_space']?>" > 秒 <span><font color="#FF0000">请填写大于等于0的整数。</font></span> </span></td>
						</tr>
						<tr class="tr input_<?php echo $item['pos']?>">
							<th class="th">每日发放最大数量</th>
							<td class="td"><span><input type="text" class="input" name="prize_max_win_<?php echo $item['pos']?>" value="<?php echo $item['max_win']?>" > 个/天 <span><font color="#FF0000">请填写大于等于0的整数。</font></span> </span></td>
						</tr>
					</table>
				  </div>
			     </td>
		         </tr> 
		      <?php endforeach;?>   
		    </table>
  		</div>
  		<table width="100%">
  			 <tr class="tr">
			    <th class="th">
				 <table width ="100px;" id="prize_layout">
					<tr>
					 <td width ="33%"><div class="block"><span>1</span></div></td>
					 <td width ="33%"><div class="block"><span>2</span></div></td>
					 <td width ="33%"><div class="block"><span>3</span></div></td>
					</tr>
					<tr>
					 <td width ="33%"><div class="block"><span>8</span></div></td>
					 <td width ="33%"><div class="block block2"><span>添加</span></div></td>
					 <td width ="33%"><div class="block"><span>4</span></div></td>
					</tr>
					<tr>
					 <td width ="33%"><div class="block"><span>7</span></div></td>
					 <td width ="33%"><div class="block"><span>6</span></div></td>
					 <td width ="33%"><div class="block"><span>5</span></div></td>
					</tr>
			    </table>
			   </th>
			   <td class="td">
				<div class="table_full" width ="500px;">
					<table width="100%">	
	   					<tr class="tr">
							<th class="th">开关</th>
							<td class="td">
								<select name="status" class="select wa">
  									<option <?php if($prize['status'] == 1) echo 'selected';?> value="1">开启</option>
                					<option <?php if($prize['status'] == 0) echo 'selected';?> value="0">关闭</option>
								</select>
			 				</td>
						<tr/>	
					</table>
				  </div>
			 </td>
		  </tr> 
		</table>
  </div>
  
<div class="mb10 tac"><span class="btn"><span><button type="submit">完成</button></span></span></div>
</form>

<script src="<?php echo $staticPath;?>/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
var editor;
KindEditor.ready(function(K) {
	K.token = '<?php echo $token;?>';
    editor = K.create('textarea[name="descript"]', {
        resizeType : 1,
        allowPreviewEmoticons : false,
        allowImageUpload : true,
        uploadJson : '<?php echo $uploadUrl;?>',
        items : EDITOR_ITEMS
    });
});

$(document).ready(function(){
	$('#start_time').datetimepicker();
    $('#end_time').datetimepicker();
	ajaxForm('editForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Point_Prize/index');
	},function(){
		editor.sync();
	});

	//select只读处理
	$.fn.selectReadOnly=function(){
	    var select=$(this).find("option:selected");
	    $(this).find("option").not(select).remove();
	 }
	$("select:[readonly='true']").selectReadOnly();
	
	//初始化奖项数据
	$("#prize_config select").each(function(){
		var check = $(this).val();
		var pos = $(this).attr('pos');
		 switch (check) {
			 case '1' :
				 $("#prize_config tr.input_"+pos+"").show();
				 $("#prize_config tr.day_"+pos+"").hide();
				 $("input[name='prize_amount_"+pos+"']").hide().attr('tips', '');
				 $("#prize_tips_"+pos).html('');
				 break;
			 case '2' :
				 $("#prize_config tr.input_"+pos+"").show();
				 $("input[name='prize_amount_"+pos+"']").show();
				 var tips = $(this).find("option:selected").text();
				 tips += ' 请填写大于0的正整数';
				 $("input[name='prize_amount_"+pos+"']").attr('tips', tips);
				 $("#prize_tips_"+pos).html(tips);
				 break;
			 case '3' :
				 $("#prize_config tr.input_"+pos+"").show();
				 $("#prize_config tr.day_"+pos+"").hide();
				 $("input[name='prize_amount_"+pos+"']").show();
				 var tips = $(this).find("option:selected").text();
				 tips += ' 请填写大于0的正整数';
				 $("input[name='prize_amount_"+pos+"']").attr('tips', tips);
				 $("#prize_tips_"+pos).html(tips);
				 break;
			 case '0' :
				 $("input[name='prize_amount_"+pos+"']").hide().attr('tips', '');
				 $("#prize_config tr.input_"+pos+"").hide();
				 $("#prize_tips_"+pos).html('');
				 break;
		 }
	});
	
	/*
	* 奖项配置选项事件联动处理
	*/
	$("#prize_config select").each(function(){
		var pos = $(this).attr('pos');
		$(this).bind('change', function(){
			 var check=$(this).val();
			 switch (check) {
				 case '1' :
					 $("#prize_config tr.input_"+pos+"").show();
					 $("input[name='prize_amount_"+pos+"']").hide().attr('tips', '');
					 $("#prize_tips_"+pos).html('');
					 break;
				 case '2' :
					 $("#prize_config tr.input_"+pos+"").show();
					 $("input[name='prize_amount_"+pos+"']").show();
					 var tips = $(this).find("option:selected").text();
					 $("input[name='prize_amount_"+pos+"']").attr('tips', tips);
					 $("#prize_tips_"+pos).html(tips);
					 break;
				 case '3' :
					 $("#prize_config tr.input_"+pos+"").show();
					 $("input[name='prize_amount_"+pos+"']").show();
					 var tips = $(this).find("option:selected").text();
					 $("input[name='prize_amount_"+pos+"']").attr('tips', tips);
					 $("#prize_tips_"+pos).html(tips);
					 break;
				 case '0' :
					 $("input[name='prize_amount_"+pos+"']").hide().attr('tips', '');
					 $("#prize_config tr.input_"+pos+"").hide();
					 $("#prize_tips_"+pos).html('');
					 break;
			 }	 
		});	
	});

//	console.log($(this).text());	
});
</script>
<?php echo $this->render("layout/footer.phtml");?>
