<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl . '?show_type=' . $show_type;?>">订单列表</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>" method="post" id="searchForm" >
<input name="token" type="hidden" value="<?php echo $token;?>"/>
<input name="show_type" type="hidden" value="<?php echo $show_type;?>"/>
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">收货人</th>
			<td class="td"><input class="input wb" type="text" name="buyer_name" value="<?php echo $params['buyer_name'];?>"></td>
			<th class="th">订单号</th>
			<td class="td"><input class="input wb" type="text" name="trade_no" value="<?php echo $params['trade_no'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">电话</th>
			<td class="td"><input class="input wb" type="text" name="phone" value="<?php echo $params['phone'];?>"></td>
			<th class="th">订单状态</th>
			<td class="td">
				<select name="status" class="select wb">
				<option value="0">所有状态</option>
				<?php foreach ($orderStatus as $key=>$value) {?>
					<option <?php if($params['status'] == $key) echo 'selected';?> value="<?php echo $key;?>"><?php echo $value;?></option>
				<?php }?>
				</select>
			</td>
		</tr>
		<tr class="tr">
			<td class="td">开始结束时间</td>
			<td class="td"><div><input class="input" type="text" style="width:143px;" id="start_time" name="start_time" value="<?php echo $params['start_time'];?>" /> 至 <input class="input" type="text" style="width:143px;" id="end_time" name="end_time" value="<?php echo $params['end_time'];?>" /></div>
			</td>
			<td class="td">商品ID</td>
			<td class="td"><input class="input wb" type="text" name="goods_id" value="<?php echo $params['goods_id'];?>">
			</td>
		</tr>
		<tr class="tr">
			<td class="td">订单类型</td>
			<td class="td">
			<select name="order_type" class="select wb">
						<option <?php if($params['order_type'] == 0) echo 'selected';?> value="0">全部</option>
						<option <?php if($params['order_type'] == 1) echo 'selected';?> value="1">话费</option>
						<option <?php if($params['order_type'] == 2) echo 'selected';?> value="2">实物商品</option>
						<option <?php if($params['order_type'] == 3) echo 'selected';?> value="3">阅读币</option>
				</select>
			</td>
			<td class="td"></td>
			<td class="td"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>


<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="mb10">
<span class="btn"><span><button type="button" id="sync">同步订单</button></span></span>
<span class="btn"><span><button type="button" id="extportBtn">导出订单</button></span>

</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td>订单ID</td>
			<td width="20%">商品名称</td>
			<td>手机号</td>
			<td>收货人</td>
			<td>下单时间</td>
			<td>订单状态</td>
			<td>支付方式</td>
			<td>商品数量</td>
			<td>实付款</td>
			<td>优惠额(元)</td>
			<td>
			<span style="float:right">
					<select name="order_by" onchange="submitForm(this.value)">
						<option value="">排序方式</option>
	                	<option <?php echo ($params['order_by'] == 'pay_time') ? 'selected="selected"' : '';?> value="pay_time">支付时间</option>
	                	<option <?php echo ($params['order_by'] == 'create_time') ? 'selected="selected"' : '';?> value="create_time">下单时间</option>
		        	</select></span>操作</td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['trade_no'];?></td>
			<td><?php echo $goods[$value['goods_id']]['title'];?></td>
			<td><?php echo $value['phone'];?></td>
			<td><?php echo $value['buyer_name'];?></td>
			<td><?php echo $value['create_time']?date('Y-m-d H:i:s',$value['create_time']) : '';?></td>
			<td><?php echo Gou_Service_Order::orderStatus($value['status']);?></td>
			<td><?php echo $value['pay_type'] == 1 ? '在线支付' : '货到付款';?></td>
			<td><?php echo $value['number'];?></td>
	        <td><?php echo $value['real_price'];?></td>
	        <td><?php echo Common::money($value['deal_price'] - $value['real_price']);?></td>
			<td>
				<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">查看</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
</form>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<div class="mr10 cc">
	<form action="<?php echo $exportUrl;?>" method="post" id="exportForm">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	<input type="hidden" name="username" value="<?php echo $params['username'];?>">
	<input type="hidden" name="username" value="<?php echo $params['username'];?>">
	<input type="hidden" name="trade_no" value="<?php echo $params['trade_no'];?>">
	<input type="hidden" name="out_trade_no" value="<?php echo $params['out_trade_no'];?>">
	<input type="hidden" name="status" value="<?php echo $params['status'];?>">
	<input type="hidden" name="start_time" value="<?php echo $params['start_time'];?>" />
	<input type="hidden" name="end_time" value="<?php echo $params['end_time'];?>" />
	<input type="hidden" name="goods_id" value="<?php echo $params['goods_id'];?>">
	<input type="hidden" name="order_type" value="<?php echo $params['order_type'];?>">
	<input type="hidden" name="order_by" value="<?php echo $params['order_by'];?>">
	<input name="show_type" type="hidden" value="<?php echo $show_type;?>"/>
	</form>
</div>

<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//导购表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
     $("#extportBtn").click(function(){
			$("#exportForm").submit();
         });
     $("#sync").click(function(){
    	 ajaxLoader.show();
    	 $.ajax({
				url : "<?php echo $syncUrl;?>",
				type : 'POST',
				dataType : 'json',
				data : 'token='+token,
				success : function(ret) {
					ajaxLoader.hide();
					if (ret.success) {
						showMsg('提示', ret.msg);
					} else {
						showError('提示', ret.msg);
					}
				}
			});
     });
     submitForm = function() {
  		$("#searchForm").submit();
  	};
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
