<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">链接列表</a></li>
    <li class="current"><a href="javascript:;">编辑链接</a></li>
	</ul>
</div>
<div class="h_a">编辑链接</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="<?php echo $info['sort']?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td">
				<select name="ptype">
<?php foreach($types as $key=>$value) {?>
				<option <?php if($info['ptype'] == $key) echo 'selected';?> value="<?php echo $key;?>"><?php echo $value;?></option>
<?php }?>
			</select>
			</td>
		</tr>
		
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title']?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">链接</th>
			<td class="td">
			   <textarea class="input" name="link" class="textarea wc" style="height:60px;width:900px"><?php echo $info['link']?></textarea>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//链接表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Links/index');
	});
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
