<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">导航列表</a></li>
    <li class="current"><a href="javascript:;">添加导航</a></li>
	</ul>
</div>
<div class="h_a">添加导航</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value=""></td>
		</tr>

		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="name" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">一级分类</th>
			<td class="td">
		<select name="type" id="type">
<?php foreach($types as $key => $value) {?>
                <option value="<?php echo $key;?>"><?php echo $value;?></option>
<?php }?>
                </select></td>
		</tr>
<?php foreach($types as $k=>$type){?>
		<tr class="tr" id="navtype<?php echo $k;?>" style="display:none">
			<th class="th">二级分类</th>
			<td class="td">
		<select name="">
<?php 
foreach($navtypes as $key => $value) {
if($k == $value['type']) {
?>
                <option value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
<?php 
}
}
?>
                </select>
		</td>
		</tr>

<?php }?>
	<tr class="tr">
			<th class="th">链接</th>
			<td class="td"><textarea class="textarea" name="link" value=""></textarea></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Nav/index');
	});
})

var sel = $("#type").val(); 
$("#type").change(function() {
	showNavTypes($(this).val());	
})
showNavTypes = function (value) {
	$("#navtype" + sel).hide();
	$("#navtype" + sel).find('select').attr('name', '');
	$("#navtype" + value).find('select').attr('name', 'navtype');
	$("#navtype" + value).show();
	sel = value;	
}
showNavTypes(sel);
</script>
<?php echo $this->render("layout/footer.phtml");?>
