<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li class="current"></li>

	</ul>
</div>
<div class="table_full">
	<form method="post" action="<?php echo $baseUrl; ?>" id="addFrom">
		<input type="hidden" name="token" value="<?php echo $token; ?>"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">时间范围</th>
					<td class="td">
						<input class="input" type="text" maxlength="30" id="sdate" name="sdate"
						       value="<?php echo $searchParam['sdate']; ?>"> 至
						<input class="input" type="text" id="edate" maxlength="30" name="edate"
						       value="<?php echo $searchParam['edate']; ?>">

					</td>
				</tr>
				<tr class="tr">
					<th class="th">活动名称</th>
					<td class="td">
						<select name="event_id">
							<?php
							foreach ($list as $v) {
								$checked = ($v['id'] == $searchParam['event_id']) ? 'selected="selected"' : '';
								echo sprintf('<option value="%s" %s>%s</option>', $v['id'], $checked, $v['title']);
							}
							?>
						</select>

					</td>
				</tr>

			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
		<input type="hidden" id="hidden_export" name="export" value="0"/>

		<div class="h_a">
			&nbsp; <span id="total" style="color: red;font-size:14px"></span>
			<span style="float:left;"><input type="button" value="导出" id="downLoad"></span>
		</div>
	</form>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="tr">
			<td class="td">日期</td>
			<td class="td">首页</td>
			<td class="td">结果页pv</td>
			<td class="td">结果页uv</td>
			<td class="td">自己分享pv</td>
			<td class="td">自己分享uv</td>
			<td class="td">朋友分享pv</td>
			<td class="td">朋友分享uv</td>
			<td class="td">帮自己pv</td>
			<td class="td">帮自己uv</td>
			<td class="td">帮朋友pv</td>
			<td class="td">帮朋友uv</td>
		</tr>
		<?php foreach ($dataList as $k => $v) { ?>
			<tr class="ct">
				<td class="td"><?php echo date('Y-m-d', strtotime($k)); ?></td>
				<td class="td"><?php echo $v['wxhelp_pv']['index'] ? $v['wxhelp_pv']['index'] : 0; ?></td>
				<td class="td"><?php echo $v['wxhelp_pv']['result'] ? $v['wxhelp_pv']['result'] : 0; ?></td>
				<td class="td"><?php echo $v['wxhelp_uv']['result'] ? $v['wxhelp_uv']['result'] : 0; ?></td>
				<td class="td"><?php echo $v['wxhelp_pv']['share_self'] ? $v['wxhelp_pv']['share_self'] : 0; ?></td>
				<td class="td"><?php echo $v['wxhelp_uv']['share_self'] ? $v['wxhelp_uv']['share_self'] : 0; ?></td>
				<td class="td"><?php echo $v['wxhelp_pv']['share_friend'] ? $v['wxhelp_pv']['share_friend'] : 0; ?></td>
				<td class="td"><?php echo $v['wxhelp_uv']['share_friend'] ? $v['wxhelp_uv']['share_friend'] : 0; ?></td>
				<td class="td"><?php echo $v['wxhelp_pv']['apply_self'] ? $v['wxhelp_pv']['apply_self'] : 0; ?></td>
				<td class="td"><?php echo $v['wxhelp_uv']['apply_self'] ? $v['wxhelp_uv']['apply_self'] : 0; ?></td>
				<td class="td"><?php echo $v['wxhelp_pv']['apply_friend'] ? $v['wxhelp_pv']['apply_friend'] : 0; ?></td>
				<td class="td"><?php echo $v['wxhelp_uv']['apply_friend'] ? $v['wxhelp_uv']['apply_friend'] : 0; ?></td>

			</tr>
		<?php } ?>
	</table>
</div>
<div class="mr10 cc">
	<?php echo $pager; ?>
</div>
<script type="text/javascript">
	$(document).ready(function () {
		$("#sdate").datepicker({dateFormat: 'yy-mm-dd'});
		$("#edate").datepicker({dateFormat: 'yy-mm-dd'});

		$("#downLoad").bind('click', function () {
			$("#hidden_export").val(1);
			$("#addFrom").submit();
			$("#hidden_export").val(0);
		});
	});
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
	
	