<?php echo $this->render("layout/header3.phtml");
$_listUrl = $this->userlistUrl;
$_editUrl = $this->usereditUrl;
?>

	<div data-options="region:'center',split:true,border:false" style="overflow: hidden;">

		<div id="datagrid_toolbar" style="padding:5px;">
			<div align="left">
				<form method="post" id="search_form" style="padding: 0px;">
					活动名称:
					<select id="event_id" name="filter[event_id]">
						<?php
						foreach ($list as $v) {
							echo sprintf('<option value="%s">%s</option>', $v['id'], $v['title']);
						}
						?>
					</select>
					导出:
					<select id="export" name="export">
						<?php
						$marks = array(1 => '是', 0 => '否');
						foreach ($marks as $k => $v) {
							echo sprintf('<option value="%s">%s</option>', $k, $v);
						}
						?>
					</select>
					<input name="token" value="<?php echo $token; ?>" type="hidden"/>
					<input name="togrid" value="1" type="hidden"/>
					<button name="export1" type="submit">提交</button>
					<a href="javascript:search(datagrid,'#search_form');" class="easyui-linkbutton"
					   iconCls="icon-search" plain="true">查 询</a>
				</form>

			</div>
			<div align="left">
				<a href="#" class="easyui-linkbutton" iconCls="icon-edit" plain="true" onclick="edit()">查看</a>
				<span class="toolbar-btn-separator"></span>
				<block name="button"></block>
				<a href="#"></a>
			</div>
		</div>
		<table id="datagrid" toolbar="#datagrid_toolbar" border="false"></table>
	</div>


	<script>
		var token = "<?php echo $token;?>";
		var edit_W = 400;
		var edit_H = 300;
		var datagrid;
		$(function () {

			//数据列表
			datagrid = $("#datagrid").datagrid({
				url: '<?php echo $_listUrl;?>',
				queryParams: {'togrid': 1, 'token': token},
				fit: true,
				autoRowHeight: false, //自动行高
				border: false,
				pagination: true, //分页栏
				pagePosition: 'bottom', //分页栏位置
				rownumbers: true,//显示行数
				striped: true,//显示条纹
				showFooter: true, //显示统计行
				pageSize: 20,//每页记录数
				remoteSort: true,//是否通过远程服务器对数据排序
				singleSelect: false,//只允许选择单行
				// main content

				sortName: 'id',//默认排序字段
				sortOrder: 'desc',//默认排序方式 'desc' 'asc'
				idField: 'id',
				columns: [[
					{field: 'ck', checkbox: true},
					{field: 'id', title: 'ID', sortable: true, align: 'center', width: 60},
					{field: 'openid', title: 'openid', sortable: false, width: 160},
					{field: 'nickname', title: '名称', sortable: false, width: 100},
					{field: 'province', title: '省份', sortable: false, width: 60},
					{field: 'city', title: '城市', sortable: false, width: 60},
					{field: 'total_amount', title: '总数量', sortable: false, align: 'center', width: 80},
					{field: 'total_times', title: '被帮助次数', sortable: false, align: 'center', width: 80},
					{field: 'total_times_f', title: '帮助他人次数', sortable: false, align: 'center', width: 80},
					{field: 'visit_num', title: '首访次数', sortable: false, align: 'center', width: 100},
					{field: 'created_at', title: '参加时间', sortable: false, align: 'center', width: 100},
				]],

				onLoadSuccess: function () {
					$(this).datagrid('clearSelections');//取消所有的已选择项
					$(this).datagrid('unselectAll');//取消全选按钮为全选状态
				},
				onRowContextMenu: function (e, rowIndex, rowData) {
					e.preventDefault();
					$(this).datagrid('unselectAll');
					$(this).datagrid('selectRow', rowIndex);
					$('#datagrid_menu').menu('show', {
						left: e.pageX,
						top: e.pageY
					});
				},
				onDblClickRow: function (rowIndex, rowData) {
					edit(rowIndex, rowData);
				}
			});

		});


		function add() {
			addData("添加", "#edit_form", datagrid, "<?php echo $_editUrl;?>", edit_W, edit_H);
		}
		function edit(rowIndex, rowData) {
			editData(rowIndex, rowData, "编辑", '#edit_form', datagrid, "<?php echo $_editUrl;?>", edit_W, edit_H, 'id');
		}
		function del() {
			delData(datagrid, "<?php echo $_delUrl;?>");
		}
	</script>
<?php echo $this->render("layout/footer3.phtml"); ?>