<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $indexUrl;?>">免单日志列表</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
	<tr class="tr">
			<th class="th">会员账号</th>
			<td class="td"><input class="input " type="text" name="username" value="<?php echo $param['username'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">商品ID</th>
			<td class="td"><input class="input " type="text" name="goods_id" value="<?php echo $param['goods_id'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
			<select name="status">
			<option value="">所有状态</option>
<?php foreach($status as $key=>$value){?>
				<option <?php echo ($param['status'] == $key) ? 'selected="selected"' :''; ?> value="<?php echo $key;?>"><?php echo $value;?></option>
<?php }?>
			</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>

</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="80">期数</td>
			<td width="100">账号</td>
			<td width="80">商品id</td>
			<td>商品名称</td>
			<td width="80">商品单价</td>
			<td width="120">开奖时间</td>
			<td width="80">状态</td>
			<td width="80">操作</td>
		</tr>
<?php foreach($logs as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['number'];?></td>
			<td><?php echo $value['username'];?></td>
			<td><?php echo $value['goods_id'];?></td>
            <td><?php echo $value['goods_title'];?></td>
            <td><?php echo $value['goods_price'];?></td>
			<td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
			<td><?php echo $status[$value['status']];?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
