<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li><a href="<?php echo $listUrl; ?>">应用列表</a></li>
		</ul>
	</div>
	<div class="h_a">导入应用</div>
	<form method="post" action="<?php echo $importUrl; ?>" id="addFrom" enctype="multipart/form-data">
		<input name="token" value="<?php echo $token; ?>" type="hidden"/>

		<div class="table_full">
			<table width="100%">

				<tr class="tr">
					<th class="th">csv文件</th>
					<td class="td"><input type="file" class="input" name="webappcsv" value=""></td>
				</tr>
			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
	</form>
	<script src="<?php echo $staticPath; ?>/js/common/jquery-ui-timepicker.js"></script>
	<script type="text/javascript">
		//广告表单数据提交
		$(document).ready(function () {
			$('#sub_time').datetimepicker();
			ajaxForm('addFrom', function (ret) {
				ajaxRedirect(ret, baseurl + '/Admin/Webapp/index');
			});
		})
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>