<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>微信管理系统</title>
	<?php echo $this->render("layout/header.phtml");?>
</head>
<body>
	<div class="header">
		<h1 class="logo"><i class="icon-logo"></i>微信管理系统</h1>
		<div class="account">
			<div class="account-info"><?php echo $adminUserName;?></div>
			<div class="account-changePwd"><a href="/Admin/Index/editPassword">修改密码</a></div>
			<div class="account-logout"><a href="<?php echo '/Admin/Login/logout';?>">退出</a></div>
		</div>
	</div>