<div class="col-side">
    <?php foreach ($menuConfig as $menu) {  ?>
          <dl class="menu">
              <dt class="menu-title"><?php echo $menu['name'];?></dt>
              <?php foreach ($menu['items'] as $item) {?>
                  <dd class="menu-item"><a href="<?php echo $menuViews[$item][1];?>" ><?php echo $menuViews[$item][0];?></a></dd>
              <?php }?>
           </dl>
    <?php }?>
</div>