<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl; ?>">资源列表</a></li>
		<li class="current"><a href="javascript:;">添加资源</a></li>
	</ul>
</div>
<div class="h_a">添加资源</div>
<form method="post" action="<?php echo $addPostUrl; ?>" id="addResourceForm">
	<input name="token" value="<?php echo $token; ?>" type="hidden"/>

	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">排序</th>
				<td class="td"><input type="text" class="input" name="sort" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">名称</th>
				<td class="td"><input type="text" class="input wc" name="name" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">简述</th>
				<td class="td">
					<textarea class="input" name="summary" class="textarea wc" style="height:60px;width:900px"></textarea>(用于首页显示)
				</td>
			</tr>
			<tr class="tr">
				<th class="th">下载地址</th>
				<td class="td"><input type="text" class="input wc" name="down_url" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">公司名称</th>
				<td class="td"><input type="text" class="input" name="company" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">星级</th>
				<td class="td"><input type="text" class="input" name="star" value="">(填写数字，1-5之间)</td>
			</tr>
			<tr class="tr">
				<th class="th">资源大小</th>
				<td class="td"><input type="text" class="input" name="size" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td"><select name="status">
						<option value="1">开启</option>
						<option value="0">关闭</option>
					</select></td>
			</tr>
			<tr class="tr">
				<th class="th">图标</th>
				<td class="td">
					<ul class="uploadImg">
						<li id="ResourceImg"><img
								src="<?php echo $staticPath; ?>/img/content/nopic.jpg"/> <input
								type="hidden" name="icon" value=""> <br/>
							<a href="javascript:;" class="delMealImages">删除</a></li>
					</ul>
					<p style="clear: both;">
						<iframe name="upload"
						        src="<?php echo $uploadUrl . '/?imgId=ResourceImg'; ?>"
						        style="height: 50px; width: 100%;" frameborder="0" scrolling="no"></iframe>
					</p>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">预览图片</th>
				<td class="td">
					<div id="imgs">
					</div>
					<div class="mb10">
						<button onclick="addupload();" onfocus="blur();" type="button" 　class="btn">＋添加预览图片</button>
					</div>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">详情介绍</th>
				<td class="td">
					<textarea name="description" style="width: 800px; height: 400px;"></textarea>
				</td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script type="text/javascript">
	$(document).ready(function () {
		ajaxForm('addResourceForm', function (ret) {
			ajaxRedirect(ret, baseurl + '/Admin/Resource/index');
		});

		var imgc = 1;
		addupload = function () {
			var al = $('<ul class="uploadImg"><li id="Img' + imgc + '"><img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/><input type="hidden" name="simg[' + imgc + ']" value=""></li></ul><p style="clear:both;"><iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=Img';?>' + imgc + '" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe></p>');
			$('#imgs').append(al);
			imgc++;
		}
	})
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
