<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">机型列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加机型</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	<div class="table_full">
		<table width="100%">
		<tr class="tr">
				<th class="th">系列</th>
				<td class="td">
				<select name="series_id">
				<option value="">所有系列</option>
<?php foreach($series as $key => $value) {?>
                <option <?php echo ($param['series_id'] == $value['id']) ? 'selected="selected"' : '';?> value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
<?php }?>
	            </select>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">机型名称</th>
				<td class="td">
				<input type="text" class="input" name="name" value="<?php echo $param['name'];?>">
				</td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button type="submit">搜 索</button></span></span>
	</div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">编号</td>
			<td>名称</td>
			<td>系列</td>
			<td width="120">操作</td>
		</tr>
<?php foreach($models as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['name'];?></td>
			<td><?php echo $series[$value['series_id']]['name'];?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
