<?php echo $this->render("layout/header.phtml");?>
<body module-id="typeIndex">
<a href="<?php echo $webroot.$userCenter;?>" class="fixed-avator"></a>
<div class="module">
    <section class="layout-center type-header-fixed">
        <div class="type-header" id="J_headerWrap">
            <ul class="type" id="J_type" data-ajax="<?php echo $webroot;?>/api/job/params">
                <li data-type="category">分类<i class="icon-put"></i></li>
                <li data-type="area">区域<i class="icon-put"></i></li>
                <li data-type="sort">排序<i class="icon-put"></i></li>
            </ul>
            <div class="type-item-wrap" id="J_typeList" style="display:none;"></div>
        </div>
        <div id="J_carouselWrap" data-ajax="<?php echo $webroot;?>/api/job/ad"></div>
    </section>
    <div class="type-list layout-center" id="J_listWrap" data-ajax="<?php echo $webroot,$listUrl;?>"></div>
</div>

<script type="text/template" id="J_typeListTemplate">
    <%for(type in data) {%>
    <ul class="list" data-type="<%=type%>" style="display:none;">
        <%if (type === 'sort') {%>
            <li class="<%=sort==''?'active':''%>" data-sort="">不限</li>
            <%for(var i=0, len=data[type].length; i<len; i++) {%>
            <li class="<%=sort==data[type][i].sort?'active':''%>" data-sort="<%=data[type][i].sort%>"><%=data[type][i].name%></li>
            <%}%>
        <%} else if (type === 'category'){%>
            <li class="<%=category==''?'active':''%>" data-id="">不限</li>
            <%for(var j=0, len=data[type].length; j<len; j++) {%>
            <li class="<%=category==data[type][j].id?'active':''%>" data-id="<%=data[type][j].id%>"><%=data[type][j].title || data[type][j].name%></li>
            <%}%>
        <%} else if (type === 'area'){%>
            <li class="<%=area==''?'active':''%>" data-id="">不限</li>
            <%for(var k=0, len=data[type].length; k<len; k++) {%>
            <li class="<%=area==data[type][k].id?'active':''%>" data-id="<%=data[type][k].id%>"><%=data[type][k].title || data[type][k].name%></li>
            <%}%>
        <%}%>
    </ul>   
    <%}%>
    
</script>

<script type="text/template" id="J_template">
    <%for(var i=0, len=list.length; i<len; i++){%>
    <a class="item" href="<%=list[i].link%>">
        <div class="side">
            <div class="img-wrap">
                <img src="<%=list[i].category_img%>"/>
            </div>
        </div>
        <div class="main">
            <div class="title"><%=list[i].title%></div>
            <ul class="detail">
                <li class="pay"><em><%=list[i].money%></em>元/<%=list[i].money_type%></li>
                <li class="address"><i class="icon-address"></i><%=list[i].area%></li>
                <li class="flex"><i class="icon-time"></i><%=list[i].dayfmt%></li>
            </ul>
        </div>
    </a>
    <%}%>
</script>
<?php echo $this->render("layout/footer.phtml");?>