<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">分类列表</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">id</td>
			<td width="100">名称</td>
		</tr>
<?php foreach($labels as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['out_id'];?></td>
			<td><?php echo $value['name'];?></td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
