<?php echo $this->render("layout/admin_header.phtml");?>
	<div class="body">
		<h1 class="page-title">用户管理</h1>
		<?php echo $this->render("layout/side.phtml");?>
		<div class="col-main">
			<div class="user-body">
				<div class="search-bar">				
					<form action="<?php echo $listUrl?>" method="get">
						<label>昵称</label><input class="input" name="keyword" value="<?php echo $inputVars['keyword']?>"/>
						<label>uuid</label><input class="input" name="uuid" value="<?php echo $inputVars['uuid']?>"/>
						<button type="submit" class="btn">查询</button>
						<span class="result">当前共有<em id="result"><?php echo $total?></em>条结果</span>
					</form>
				</div>
				<div class="table-left">
					<table class="J_table table" data-ajaxUrl="#">
						<tbody>
							<?php 
							$format = 'Y-m-d H:i:s';
							foreach ($list as $user){
							?>
									<tr>
										<td>
											<div class="user-info-container">
												<div class="avator tooltips">
													<img src="<?php echo $user['headimgurl'];?>" alt=""/>
													<div class="popover" >
														<div class="basic-info">
															<h2>详细资料</h2>
															<p>昵称：<?php echo $user['nickname'];?></p>
															<p>性别：<?php echo $user['sex']==1?"男":($user['sex']==2?"女":"未知");?></p>
															<p>地区：<?php echo $user['country'].$user['province'].$user['city'];?></p>
															<p>分组：<?php echo $user['groupId'];?></p>
														</div>		
												<?php 
												if($user['is_binded']) {
												     $gameInfo = $gameInfoList[$user['id']];
												?>
														<div class="bind-info">
															<p>绑定帐号信息</p>
															<p>昵称：<?php echo $gameInfo['nickName'];?></p>
															<p>A币：<?php echo $gameInfo['coin'];?></p>
															<p>A券：<?php echo $gameInfo['tick'];?></p>
															<p>礼包数量：<?php echo $gameInfo['bagNums'];?></p>
														</div>
												<?php }?>
													</div>
												</div>
												<div class="info">
													<span class="name"><?php echo $user['nickname'];?></span>
													<span class="date"><?php echo date($format, $user['subscribe_time']);?></span>
												</div>
											</div>
										</td>
										<td class="sex"><?php echo $user['sex']==1?"男":($user['sex']==2?"女":"未知");?></td>
										<td class="type"><?php echo $user['groupId'];?></td>	
									</tr>
							<?php }?>
						</tbody>
					</table>
                    <?php echo $pager;?>
				</div>
				<div class="group-right">
					<ul class="group-list">
						<li>系统分组</li>
						<li><a href="<?php echo $listUrl;?>" <?php if($inputVars['group'] != 1) echo 'class="active"'?>>全部(<?php echo $allNums?>)</a></li>
						<li><a href="<?php echo $listUrl.'?group=1';?>" <?php if($inputVars['group'] == 1) echo 'class="active"'?>>已绑定(<?php echo $bindNums?>)</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>