<?php echo $this->render("layout/singleheader.phtml");?>
	<body data-pagerole="body">
	<div class="module">
		
		<section id="iScroll" class="about-wrap">
			<div class="avatar-wrap">
				<div class="pic">
					<img src="<?php echo "$staticResPath/assets/img/avatar.jpg";?>" alt="">
					<!-- <img src="<?php echo "$staticResPath/assets/img/avatar.jpg";?>" alt="" usemap="#avatar-map">
					<map name="avatar-map" id="avatar-map">
						<area shape="rect" coords="120, 40, 160, 90" href="javascript:;" alt="boss">
						<area shape="rect" coords="170, 40, 210, 90" href="javascript:;" alt="boss">
						
						<area shape="rect" coords="10, 90, 55, 140" href="javascript:;" alt="boss">
						<area shape="rect" coords="10, 140, 55, 190" href="javascript:;" alt="boss">
						<area shape="rect" coords="10, 190, 55, 240" href="javascript:;" alt="boss">
						<area shape="rect" coords="10, 240, 55, 290" href="javascript:;" alt="boss">
						
						<area shape="rect" coords="60, 90, 95, 140" href="javascript:;" alt="boss">
						<area shape="rect" coords="60, 140, 95, 190" href="javascript:;" alt="boss">
						<area shape="rect" coords="60, 190, 95, 240" href="javascript:;" alt="boss">
						<area shape="rect" coords="60, 240, 95, 290" href="javascript:;" alt="boss">
						
						<area shape="rect" coords="125, 90, 155, 140" href="javascript:;" alt="boss">
						<area shape="rect" coords="125, 140, 155, 190" href="javascript:;" alt="boss">
						<area shape="rect" coords="125, 190, 155, 240" href="javascript:;" alt="boss">
						<area shape="rect" coords="125, 240, 155, 290" href="javascript:;" alt="boss">
						
						<area shape="rect" coords="170, 90, 205, 140" href="javascript:;" alt="boss">
						<area shape="rect" coords="170, 140, 205, 190" href="javascript:;" alt="boss">
						<area shape="rect" coords="170, 190, 205, 240" href="javascript:;" alt="boss">
						<area shape="rect" coords="170, 240, 205, 290" href="javascript:;" alt="boss">
						
						<area shape="rect" coords="225, 90, 260, 140" href="javascript:;" alt="boss">
						<area shape="rect" coords="225, 140, 260, 190" href="javascript:;" alt="boss">
						<area shape="rect" coords="225, 190, 260, 240" href="javascript:;" alt="boss">
						<area shape="rect" coords="225, 240, 260, 290" href="javascript:;" alt="boss">
						
						<area shape="rect" coords="270, 90, 305, 140" href="javascript:;" alt="boss">
						<area shape="rect" coords="270, 140, 305, 190" href="javascript:;" alt="boss">
						<area shape="rect" coords="270, 190, 305, 240" href="javascript:;" alt="boss">
						<area shape="rect" coords="270, 240, 305, 290" href="javascript:;" alt="boss">
					</map> -->
				</div>
			</div>
			<ul class="service">
				<li>
					<h3 class="settle">商家入驻</h3>
					<p>卖家/商家合作，电商平台合作，购物电商平台联盟合作，请Email: bd@gouwudating.com</p>
				</li>
				<li>
					<h3 class="prom">推广合作</h3>
					<p>如果您有关于广告投放、商务合作、渠道合作、资源互换等多种形式合作的问题，请Email: bd@gouwudating.com，或联系QQ:1754626171，并简要介绍合作需求</p>
				</li>
			</ul>
			<div class="footer">
				<div class="contact">官方QQ群：237057997</div>
				<div class="copyright">copyright © 2012 粤ICP备05087105号</div>
			</div>
		</section>
	</div>
	
	<?php echo $this->render("layout/tj.phtml");?>
<?php echo $this->render("layout/newfooter.phtml");?>