<!DOCTYPE HTML>
<?php
$ua = Util_Http::getServer('HTTP_USER_AGENT');
$is_uc = (strpos($ua, 'UC AppleWebKit') || strpos($ua, 'UCWEB')) ? true : false;
?>
<html <?php if($is_uc) echo 'class="uc-hack"'?>>
<head>
	<meta charset="UTF-8">
	<title><?php echo $title;?></title>
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="format-detection" content="email=no" />
	
	<meta name="appRef" content="<?php echo $staticResPath;?>" />
	<link rel="stylesheet" href="<?php echo $staticRoot;?>/sys/reset/mpcore.css?v=<?php echo $version;?>" />
	<link rel="stylesheet" href="<?php echo $staticRoot;?>/apps/gou/h5/assets/css/gngou.css?v=<?php echo $version;?>" />
    <link rel="shortcut icon" href="/favicon.ico" />
	<script type="text/javascript" src="<?php echo $staticRoot;?>/??/sys/icat/1.1.3/icat.js,/sys/lib/jquery/jquery.js,/sys/lib/zepto/zepto.js,/apps/gou/h5/assets/js/gngou.new.js,/apps/gou/h5/assets/js/gngou.js?v=<?php echo $version;?>"></script>
	<script type="text/javascript">var token= '<?php echo $token;?>';</script>
</head>