	<nav>
					<ul>
						<li><a <?php echo $nav[1]['href'];?> class="<?php echo $nav[1]['selected'];?> rount-rect"><em><?php echo $user_info['silver_coin'] > 0 ? $user_info['silver_coin'] : '0.00';?></em>我的积分</a></li>
						<?php if(strpos($webroot, 'client') === false && strpos($webroot, 'apk') === false) {?>
						<li><a <?php echo $nav[2]['href'];?> class="<?php echo $nav[2]['selected'];?> rount-rect"><em><?php echo $user_info['order_num'];?></em>我的订单</a></li>
						<?php }?>
						<li><a <?php echo $nav[3]['href'];?> class="<?php echo $nav[3]['selected'];?> rount-rect"><em><?php echo $user_info['want_num'];?></em>心愿清单</a></li>
						<li><a <?php echo $nav[4]['href'];?> class="<?php echo $nav[4]['selected'];?> rount-rect"><em>收货地址</em></a></li>
					</ul>
				</nav>
