<?php
if($hasheader) {
$noheader = !in_array($webroot, array('http://client.gou.gionee.com', 'http://client.gou.3gtest.gionee.com','http://apk.gou.gionee.com', 'http://apk.gou.3gtest.gionee.com'));
if($noheader) {
?>
	<header id="iHeader" class="hd">
		<div class="top-wrap">
			<div class="logo">
				<h1>购物大厅</h1>
				<a class="search" href="<?php echo $webroot;?>/search?refer=<?php echo urlencode($webroot.'/user/account/index'); ?>"><em>请输入商品名</em><i></i></a>
	  		</div>  		
  		</div>
		<nav class="main-nav">
			<ul>
				<li><a href="<?php echo $webroot;?>">推 荐</a></li>
				<li><a href="<?php echo $webroot;?>/cod">货到付款</a></li>
				<li class="selected"><span>个人中心</span></li>
			</ul>
		</nav>
	</header>
<?php } } ?>
