<!DOCTYPE html>
<html lang="en">
<head>
	<?php $this->title="新游尝鲜";$this->hasSearch="true"; ?>
	<meta charset="UTF-8">
	<title>游戏大厅</title>
	<?php echo $this->render("layout/cssInc.phtml");?>
</head>
<body>
	<?php echo $this->render("layout/header.phtml");?>
	<div id="container">
		
    </div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
<?php echo $this->render("layout/scriptInc.phtml");?>
<script type="text/javascript">
	var rankingData = <?php echo $data?>;

	
	React.render(
		React.createElement(DateRanking, {items: rankingData})
	  , document.getElementById('container')
	);
	

</script>
<script src="<?php echo "$appJs/loadImg.js$timestamp";?>" type="text/javascript"></script>
</html>