<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $indexUrl;?>">商品标签列表</a></li>
    <li class="current"><a href="javascript:;">添加商品标签</a></li>
	</ul>
</div>
<div class="h_a">添加商品标签</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="0"></td>
		</tr>		
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input" name="name" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">父级标签</th>
			<td class="td">
		<select name="parent_id" id="label_id">
		<option value="0">父级标签</option>
<?php foreach($parents as $key => $value) {?>
                <option value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
<?php }?>
                </select></td>
		</tr>
		<tr class="tr" id="label_img">
			<th class="th">商品图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	$("#label_id").bind("change", function(e) {
		var v = $(this).val();
		if (v == 0) {
			$("#label_img").show();
		}else {
			$("#label_img").hide();
		}
	})
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Goodslabel/index');
	});
})

</script>
<?php echo $this->render("layout/footer.phtml");?>
