<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">商品标签列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加商品标签</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">排序</td>
			<td>标签名称</td>
			<td width="120">操作</td>
		</tr>
<?php foreach($list as $key => $value) { ?>
        <?php if($value['id']) { ?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><?php echo $value['name'];?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
		<?php foreach($value['items'] as $k => $val) {?>
		<tr class="ct">
			<td><?php echo $val['sort'];?></td>
			<td>|—<?php echo $val['name'];?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $val['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $val['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php }}}?>
	</table>
</div>
<?php echo $this->render("layout/footer.phtml");?>
