apc.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc.c -o apc.lo 
apc_lock.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_lock.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_lock.c -o apc_lock.lo 
php_apc.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/php_apc.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/php_apc.c -o php_apc.lo 
apc_cache.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_cache.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_cache.c -o apc_cache.lo 
apc_mmap.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_mmap.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_mmap.c -o apc_mmap.lo 
apc_shm.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_shm.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_shm.c -o apc_shm.lo 
apc_sma.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_sma.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_sma.c -o apc_sma.lo 
apc_stack.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_stack.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_stack.c -o apc_stack.lo 
apc_rfc1867.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_rfc1867.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_rfc1867.c -o apc_rfc1867.lo 
apc_signal.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_signal.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_signal.c -o apc_signal.lo 
apc_pool.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_pool.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_pool.c -o apc_pool.lo 
apc_iterator.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_iterator.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_iterator.c -o apc_iterator.lo 
apc_bin.lo: /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_bin.c
	$(LIBTOOL) --mode=compile $(CC) $(APCU_CFLAGS) -I. -I/data/www/trunk/gamehall/game/tests/apcu-4.0.7 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /data/www/trunk/gamehall/game/tests/apcu-4.0.7/apc_bin.c -o apc_bin.lo 
$(phplibdir)/apcu.la: ./apcu.la
	$(LIBTOOL) --mode=install cp ./apcu.la $(phplibdir)

./apcu.la: $(shared_objects_apcu) $(APCU_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_apcu) $(APCU_SHARED_LIBADD)

