<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">游戏列表</a></li>
    <li class="current"><a href="javascript:;">添加游戏</a></li>
	</ul>
</div>
<div class="h_a">添加游戏</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
	<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="0"></td>
		</tr>
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input wc" name="name" value=""></td>
		</tr>
		<tr class="tr">
			<th class="th">简述</th>
			<td class="td"><input type="text" class="input wc" name="resume" value=""></td>
		</tr>
			<th class="th">下载地址</th>
			<td class="td"><input type="text" name="link" class="input wc"></td>
		</tr>
		<tr class="tr">
			<th class="th">公司</th>
			<td class="td"><input type="text" name="company" class="input wc"></td>
		</tr>
		<tr class="tr">
			<th class="th">大小</th>
			<td class="td"><input type="text" name="size" class="input"></td>
		</tr>
		<tr class="tr">
			<th class="th">图标</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="Img">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img" value="">
					</li>
				</ul>			
<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=Img';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
				<select name="status" class="wa">
                	<option value="1">开启</option>
                	<option value="0">关闭</option>
           		</select>
            </td>
		</tr>
		<tr class="tr">
			<th class="th">游戏预览</th>
			<td class="td">
				<div id="imgs">
				
				</div>
				<div class="mb10"><button onclick="addupload();" onfocus="blur();" type="button"　class="btn">＋添加预览图片</button></div>
			</td>
		</tr>
		<tr class="tr">
				<th class="th">内容</th>
				<td class="td"><textarea style="width: 800px; height: 500px" class="textarea"
						name="descrip"></textarea>
				</td>
			</tr>             
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//游戏表单数据提交
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Game/index');
	});

	var imgc = 1;
	addupload  = function() {
		var al = $('<ul class="uploadImg"><li id="Img'+imgc+'"><img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/><input type="hidden" name="simg['+imgc+']" value=""></li></ul><p style="clear:both;"><iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=Img';?>'+imgc+'" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe></p>');
		$('#imgs').append(al);
		imgc++;
	}
	
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
