<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">游戏列表</a></li>
    <li class="current"><a href="javascript:;">编辑游戏</a></li>
	</ul>
</div>
<div class="h_a">编辑游戏</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
	<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="<?php echo $info['sort'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input wc" name="name" value="<?php echo $info['name'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">简述</th>
			<td class="td"><input type="text" class="input wc" name="resume" value="<?php echo $info['resume'];?>"></td>
		</tr>
			<th class="th">下载地址</th>
			<td class="td"><input type="text" name="link" class="input wc" value="<?php echo $info['link'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">公司</th>
			<td class="td"><input type="text" name="company" class="input wc" value="<?php echo $info['company'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">大小</th>
			<td class="td"><input type="text" name="size" class="input" value="<?php echo $info['size'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">图标</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="Img">
						<img src="<?php echo $attachPath.$info['img'];?>"/>
						<input type="hidden" name="img" value="<?php echo $info['img'];?>">
					</li>
				</ul>			
				<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=Img';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td">
				<select name="status" class="wa">
                	<option value="1" <?php if($info['status'] == 1) echo 'selected';?>>开启</option>
                	<option value="0" <?php if($info['status'] == 0) echo 'selected';?>>关闭</option>
            	</select>
            </td>
		</tr>
		<tr class="tr">
			<th class="th">游戏预览</th>
			<td class="td">
					<?php foreach($gimgs as $key=>$value) {?>
						<div id="upimg<?php echo $value['id'];?>">
							<ul class="uploadImg">
								<li id="upImg<?php echo $value['id'];?>">
									<img src="<?php echo $attachPath,$value['img'];?>"/>
									<input type="hidden" name="upImg[<?php echo $value['id'];?>]" value="">
								</li>
								<li><a href="javascript:void(0)" onclick="deleteImg('<?php echo $deleteImgUrl;?>?id=<?php echo $value['id'];?>', 'upimg<?php echo $value['id'];?>', event);">删　除</a></li>
							</ul>
							<p style="clear:both;"><iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=upImg',$value['id'];?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe></p>
						</div>
					<?php }?>
				<div id="imgs"></div>
				<div class="mb10"><button onclick="addupload();" onfocus="blur();" type="button"　class="btn">＋添加预览图片</button></div>				 
			</td>
		</tr>
		<tr class="tr">
				<th class="th">内容</th>
				<td class="td"><textarea style="width: 800px; height: 500px" class="textarea" name="descrip"><?php echo $info['descrip'];?></textarea>
				</td>
			</tr>             
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//游戏表单数据提交
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Game/index');
	});

	var imgc = 0;
	addupload  = function() {
		var al = $('<ul class="uploadImg"><li id="Img'+imgc+'"><img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/><input type="hidden" name="simg['+imgc+']" value=""></li></ul><p style="clear:both;"><iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=Img';?>'+imgc+'" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe></p>');
		$('#imgs').append(al);
		imgc++;
	}
	deleteImg = function(url, elid, e) {
		showConfirm("确认删除该条信息？", function() {
			$.ajax({
						url : url,
						type : 'POST',
						dataType : 'json',
						data : 'token='+token,
						success : function(ret) {
							if (ret.success) {
								$('#'+elid).remove();
							} else {
								showError('', ret.msg);
							}
						}
					});
		}, e);
	}
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
