<div class="mod_box app_box">
	<div class="hd"><i class="hd_ico"></i><h2 class="title">下载</h2></div>
	<div class="bd">
		<?php $tj_intersrc_down = (($tj_intersrc == 'category')?($tj_intersrc.$category_id):$tj_intersrc);?>
		<a class="download_app" href="<?php echo Common::aimiTjUrl($tjUrl, $tj_channel, $tj_cku, 'startdl', $ami_web_info['package'], $tj_intersrc_down.'_dlami', $webroot.'/Front/Android/index/');?>">金立游戏大厅客户端</a>
	</div>
</div>