<?php echo $this->render("layout/header2.phtml");?>
	<div id="page">
		<?php if ($hasheader) {?>
		<header class="hdWrap">
			<div class="hd-l"><a href="<?php echo $webroot;?>" class="l-arrow">back</a></div>
			<div class="hd-r"><h1>往期免单名单</h1></div>	
			<div class="hd-m"><a href="<?php echo $webroot,$ruleUrl;?>">免单规则</a></div>
		</header>
		<?php }?>
		<?php if($total) {?>
		<article class="ac">
			<div class="free-order-box J_slideAjax" data-ajaxUrl="<?php echo $webroot.'/orderfree/freelog';?>"></div>
		</article>
		<?php }?>
	</div>
	<script id="J_itemView" type="template">
		<div class="J_slideItem" pid="{data.curpage}" hasnext="{data.hasnext}" style="position:absolute; width:100%; left:100%;">
	    	<div class="free-period">
				<div class="title">
					<h3>免单{data.list.number}期</h3>
					<time>{data.list.create_time_1}<i></i>{data.list.create_time_2}更新</time>
				</div>
				<div class="main">
					<span class="handle"></span>
					<span class="handle r"></span>
					<div class="pic">
						<a href="{data.list.link}">
							<span><img src="{data.list.img}" alt="" /></span>
							<em>{data.list.title}</em>
						</a>
					</div>
					<div class="desc">
						<span class="price">￥{data.list.price}</span>
						<span class="sale">{data.list.want_count}人想要</span>
						<a href="{data.list.link}">查看商品详情</a>
					</div>
				</div>
			</div>
			<section class="free-list">
				<h3>成功免单用户（{data.list.order_free_num}名）</h3>
				<ul>
					{each data.list.order_free}
					<li>
						会员:<em>{$value.username}</em><br />
						想要{!$value.want_num? 0:$value.want_num}件商品，已免单{!$value.free_num? 0:$value.free_num}件商品
					</li>
					{/each}
				</ul>
			</section>
	    </div>
	</script>
</body>
</html>