<?php echo $this->render("layout/header.phtml");?>
	<div data-role="page" id="page" class="intro-about" data-theme="no">
		<?php echo $this->render("layout/nav.phtml");?>
		<h1 class="inner-title"><strong>企业荣誉</strong></h1>
		<div class="ct text">
		<h2>“GiONEE金立”被评为“2011年度中国手机行业十大品牌”</h2>
			<p>3月24日，由中国工业报社、深圳市手机行业协会、国际移动通信联合会等单位联合主办的2012中国手机产业年会在深圳会展中心隆重举行。深圳市副市长唐杰、中国通信工业协会会长王秉科、中国移动通信联合会执行副会长谢麟振、金立集团副总裁兼总裁办主任杨立等领导及手机行业近1000位精英参与盛会。</p>
<p>此次年会主题为“智能手机时代与我们”，是一个代表中国水平、高规格、行业思想的年度品牌会议。会上发布了“2011年度中国手机风云榜”，金立手机、HTC手机等荣膺“2011年度中国手机行业十大品牌”。</p>
		</div>
	</div>
<?php echo $this->render("layout/footer.phtml");?>