<?php echo $this->render("layout/header.phtml");?>
	<div data-role="page" id="page" class="intro-about" data-theme="no">
		<?php echo $this->render("layout/nav.phtml");?>
		<h1 class="inner-title"><strong>企业荣誉</strong></h1>
		<div class="ct text">
		<h2>“GiONEE金立”被评为“2011年度中国手机行业十大品牌”</h2>
			<p> 3月，金立手机因认真贯彻执行《消法》、《产品质量法》，严格按照国家的行业规定与质量标准组织生产，被中国保护消费者基金会评为2011年度“全国市场放心消费品牌”。</p>
		</div>
	</div>
<?php echo $this->render("layout/footer.phtml");?>