<?php echo $this->render("layout/header.phtml");?>
	<div data-role="page" id="page" class="intro-about" data-theme="no">
		<?php echo $this->render("layout/nav.phtml");?>
		<h1 class="inner-title"><strong>企业荣誉</strong></h1>
		<div class="ct text">
		<h2>金立荣获“2011感动福田十佳企业”称号</h2>
			<p>2011年12月28日下午，深圳市福田区企业联合会、企业家协会第八届会员联谊会在深圳会展中心举行，金立集团副总裁兼总裁办主任杨立出席会议。</p><p>
会上，金立以其良好的成长性和高度的社会责任感，被深圳市福田区企业联合会、深圳市福田区企业家协会授予“2011感动福田十佳企业”荣誉，并颁发奖牌。
</p>
		</div>
	</div>
<?php echo $this->render("layout/footer.phtml");?>