<?php echo $this->render("layout/header.phtml");?>
	<div data-role="page" id="page" class="intro-about" data-theme="no">
		<?php echo $this->render("layout/nav.phtml");?>
		<h1 class="inner-title"><strong>企业荣誉</strong></h1>
		<div class="ct text">
		<h2>金立荣获2011年“深圳市和谐劳动关系先进企业”称号</h2>
			<p>2月，经深圳市劳动关系协调委员会评审，金立被授予2011年"深圳市和谐劳动关系先进企业"荣誉称号，肯定了公司在遵守国家劳动法律法规、热心关爱员工、创新企业文化、和谐劳动关系方面取得的突出成绩。
</p>
		</div>
	</div>
<?php echo $this->render("layout/footer.phtml");?>