<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">订单列表</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">用户名</th>
			<td class="td"><input class="input wb" type="text" name="username" value="<?php echo $params['username'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">订单号</th>
			<td class="td"><input class="input wb" type="text" name="trade_no" value="<?php echo $params['trade_no'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">外部订单号</th>
			<td class="td"><input class="input wb" type="text" name="out_trade_no" value="<?php echo $params['out_trade_no'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">订单状态</th>
			<td class="td">
				<select name="status" class="select wb">
						<option <?php if($params['status'] == 0) echo 'selected';?> value="0">全部</option>
						<option <?php if($params['status'] == 1) echo 'selected';?> value="1">未支付</option>
						<option <?php if($params['status'] == 2) echo 'selected';?> value="2">已支付</option>
						<option <?php if($params['status'] == 3) echo 'selected';?> value="3">买家已付款，卖家未发货</option>
						<option <?php if($params['status'] == 4) echo 'selected';?> value="4">卖家已发货，买家未收货</option>
						<option <?php if($params['status'] == 5) echo 'selected';?> value="5">订单成功</option>
						<option <?php if($params['status'] == 6) echo 'selected';?> value="6">订单关闭</option>
				</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td>订单ID</td>
			<td>外部订单号</td>
			<td>用户名</td>
			<td>手机号</td>
			<td>收货人</td>
			<td>成交时间</td>
			<td>订单状态</td>
			<td>实付款</td>
			<td>优惠额(元)</td>
			<td>操作</td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['trade_no'];?></td>
			<td><?php echo $value['out_trade_no'];?></td>
			<td><?php echo $value['username'];?></td>
			<td><?php echo $address[$value['id']]['mobile'];?></td>
			<td><?php echo $address[$value['id']]['buyer_name'];?></td>
			<td><?php echo $value['create_time']?date('Y-m-d H:i:s',$value['create_time']) : '';?></td>
			<td><?php echo Gc_Service_Order::orderStatus($value['status']);?></td>
	        <td><?php echo $value['real_price'];?></td>
	        <td><?php echo Common::money($value['deal_price'] - $value['real_price']);?></td>
			<td>
				<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">查看</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
