<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">用户反馈列表</a></li>
    <li class="current"><a href="javascript:;">用户反馈审核</a></li>
	</ul>
</div>
<div class="h_a">编辑日志</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
		<table width="100%">
		<tr class="tr">
			<th class="th">手机号码</th>
			<td class="td"><input type="text" class="input" name="mobile" value="<?php echo $info['mobile'];?>"></td>
		</tr>
	
		<tr class="tr">
			<th class="th">QQ号码</th>
			<td class="td"><input type="text" class="input" name="qq" value="<?php echo $info['qq'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">email</th>
			<td class="td"><input type="text" class="input" name="email" value="<?php echo $info['email'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">反馈内容</th>
			<td class="td"><textarea style="width:600px" class="textarea" name="react"><?php echo $info['react'];?></textarea></td>
		</tr>
		<tr class="tr">
			<th class="th">回复内容</th>
			<td class="td"><textarea style="width:600px" class="textarea" name="reply"><?php echo $info['reply'];?></textarea></td>
		</tr>
		<tr class="tr">
			<th class="th">结论</th>
			<td class="td">
			  <select name="result">
				<option <?php if($search['result'] == 1) echo 'selected';?> value="1">采纳</option>
				<option <?php if($search['result'] == 0) echo 'selected';?> value="0">未采纳</option>
			</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/React/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
