<?php echo $this->render("layout/header.phtml"); ?>
	<form method="post" action="<?php echo $monthUrl; ?>" id="addFrom">
		<input type="hidden" name="token" value="<?php echo $token; ?>"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">选择月份</th>
					<td class="td">
						<input class="input" type="text" maxlength="30" id="date" name="date"
						       value="<?php echo $params['date']; ?>">
					</td>
				</tr>

				<tr class="tr">
					<th class="th">选择充值类型</th>
					<td class="td">
						<select name="group_type">
							<?php foreach ($groupTypes as $k => $v) { ?>
								<option value="<?php echo $k; ?>" <?php if ($k == $params['group_type']) echo 'selected'; ?>><?php echo $v; ?></option>
							<?php } ?>
						</select>
					</td>
				</tr>

				<tr class="tr">
					<th class="th">最小充值次数</th>
					<td class="td">
						<input class="input" type="text" value="<?php echo $params['num'] ?>" name="num">
					</td>
				</tr>
				<tr class="tr">
					<th class="th">被充值号码</th>
					<td class="td">
						<input class="input" type="text" value="<?php echo $params['recharge_number'] ?>" name="recharge_number">
					</td>
				</tr>
			</table>
		</div>
		<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
		</div>
		<input type="hidden" id="hidden_export" name="export" value="0"/>
	</form>

	<div class="h_a">充值次数合计
	                 &nbsp; <span id="total" style="color: red;font-size:14px"></span> &nbsp;&nbsp;被充值账号数:
		<span id="account_number" style="color: red; font-size:14px"></span>
		<span style="float:right;"><input type="button" value="导出" id="downLoad"></span>
	</div>
	<style type="text/css">
		table {
			empty-cells: show;
			border-collapse: collapse;
		}

		table th {
			white-space: nowrap;
		}

		table td {
			white-space: nowrap;
		}
	</style>
	<div class="table_list">
		<table width="100%">
			<tr class="ct">
				<td class="td2">被充值号码</td>
				<td class="td2">充值次数</td>
				<th class="td2">详情</th>
				<td class="td2" align="center">操作</td>
			</tr>
			<?php
			$sum = 0;
			foreach ($list as $m => $n) {
				$sum += $n['total_times'];
				?>
				<tr class="ct">
					<td class="td2"  width="20%"><?php echo $n['recharge_number'];?></td>
					<td class="td2" width="20%"><?php echo $n['total_times']; ?></td>
					<td class="td2" width="20%">
						<a href="<?php echo $detailUrl;?>?date=<?php echo $params['date'];?>&recharge_number=<?php echo $n['recharge_number'];?>&group_type=<?php echo $params['group_type'];?>&num=<?php echo $params['num'];?>">查看</a>
					</td>
					<td class="td2" width="20%">
						<a href="javascript:void(0);"  onclick="operation(1,<?php echo $n['recharge_number']?>)" >一键加入黑名单</a>|
						<a href="javascript:void(0);"  onclick="operation(2,<?php echo $n['recharge_number']?>)" >一键金币冻结</a> |
						<a href="javascript:void(0);"  onclick="operation(3,<?php echo $n['recharge_number']?>)">一键清零</a>
					</td>
				</tr>
			<?php }; ?>
		</table>
	</div>
	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>
	<script type="text/javascript">
		$(document).ready(function () {
			$("#date").datepicker({dateFormat: 'yy-mm'});
			$("#total").html(' <?php echo $sum;?> ');
			$("#account_number").html('<?php echo $totalAcounts;?>');


			$("#downLoad").bind('click', function () {
				$("#hidden_export").val(1);
				$("#addFrom").submit();
				$("#hidden_export").val(0);
			});
		});

		function operation(type,number){
				if(confirm("确定要把给"+number+"充值的账号都处理吗?")){
					$.ajax({
						'type':'post',
						'dataType':'json',
						'url':'/Admin/uaccount/ajaxAddUsersToBlackList',
						'data':{"token":'<?php echo $token;?>','type':type,'recharge':number,'group_type':'<?php echo $params["group_type"];?>', 'month':'<?php echo $params["date"];?>'},
						'success':function(e){
									alert('操作成功');
						}
					});
				}else{
					return false;
				}
			}
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>