<?php echo $this->render("layout/header.phtml");?>
<script>
var token = '<?php echo $token;?>';
</script>
<div id="page">
		<article class="ac">
			<div class="item-list J_gameItem">
				<ul>
					 <?php if(count($games)){?>
					<?php foreach($games as $key=>$value) {?>
					<?php 
					     if(!$intersrc){
                            $intersrc = 'CATEGORY';
					     } 
					     $href = $webroot.'/super/game/detail/?id='.$value['id'].'&intersrc='.$intersrc.'&t_bi='.$source;
					?>
					<li>
						<a class="detail" href="<?php echo $href;?>">
							<div class="pic"><img src="<?php echo $attachPath. $value['img'];?>" alt="<?php echo $value['name'];?>"></div>
							<div class="desc">
								<h3><?php echo $value['name'];?></h3>
								<p><?php echo $value['resume'];?></p>
							</div>
						</a>
						<div class="download"><a class="btn" href="<?php echo Common::tjurl($tjUrl, $value['id'], 'GAME', $value['link']);?>">安装</a></div>
					</li>
					<?php }?>
					<?php }?>
				</ul>
			</div>
			<?php if($hasnext){ ?>
			<div class="load-more J_loadMore" data-ajaxUrl="<?php echo $webroot.'/super/category/moreCt/?id='.$id.'&intersrc='.$intersrc.'&t_bi='.$source;?>" data-hasnext="<?php echo $hasnext;?>" data-curpage="<?php echo $page;?>">
				<span>加载更多</span>
			</div>
			<?php } ?>
		</article>

		<footer class="ft">
			<div class="back-top"><a class="btn" href="#top">返回顶部</a></div>
			<div class="quick-links">
				<a href="<?php echo $webroot.'/contact?t_bi='.$source;?>">联系我们</a>
				<a href="<?php echo $webroot.'/feedback?t_bi='.$source;?>">意见反馈</a>
				<a href="<?php echo strpos($configs['game_link'], '?') == false ? $configs['game_link'].'&t_bi='.$source :$configs['game_link'].'?t_bi='.$source;?>"><?php echo $configs['game_title'];?></a>
			</div>
		</footer>
	</div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>