<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li><a href="<?php echo $configUrl; ?>">基本配置</a></li>
			<li class="current"><a href="<?php echo $indexUrl; ?>">信息列表</a></li>
			<li><a href="<?php echo $addUrl; ?>">添加活动内容</a></li>
			<li><a href="<?php echo $userUrl ?>">用户列表</a>
			<li><a href="<?php echo $logUrl ?>">通话记录</a>
			<li><a href="<?php echo $service; ?>">添加客服信息</a>
			<li><a href="<?php echo $serviceList; ?>">客服信息列表</a>
			<li><a href="<?php echo $tipsListUrl ?>">规则说明</a>
		</ul>
	</div>
	<div class="table_list">
		<table width="100%">
			<tr class="hd">
				<td width="20">ID</td>
				<td width="140">开始时间</td>
				<td width="200">结束时间</td>
				<td width="200">通话结束时间</td>
				<td width="200">总数</td>
				<td width="200">剩余数</td>
				<td width="60">状态</td>
				<td width="120">操作</td>
			</tr>
			<?php foreach ($data as $key => $value) {
				?>
				<tr class="ct">
					<td><?php echo $value['id']; ?></td>
					<td><?php echo date('Y-m-d H:i:s', $value['start_time']); ?></td>
					<td><?php echo date('Y-m-d H:i:s', $value['end_time']); ?></td>
					<td><?php echo date('Y-m-d H:i:s', $value['valid_time']); ?></td>
					<td><?php echo $value['number']; ?></td>
					<td><?php echo $value['remined'] ?></td>
					<td><?php echo $value['sta'] ? '开启' : '关闭'; ?></td>
					<td>
						<a href="/Admin/Voip/edit/?id=<?php echo $value['id']; ?>" class="mr10">编辑</a>
						<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
					</td>
				</tr>
			<?php } ?>
		</table>
	</div>
	<div class="mr10 cc">
		<?php echo $pager; ?></div>
<?php echo $this->render("layout/footer.phtml"); ?>