<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li><a href="<?php echo $configUrl; ?>">基本配置</a></li>
			<li><a href="<?php echo $indexUrl; ?>">活动列表</a></li>
			<li><a href="<?php echo $addUrl; ?>">添加活动内容</a></li>
			<li class="current"><a href="<?php echo $userUrl ?>">用户列表</a>
			<li><a href="<?php echo $logUrl ?>">通话记录</a>
			<li><a href="<?php echo $service; ?>">添加客服信息</a>
			<li><a href="<?php echo $serviceList; ?>">客服列表</a>
			<li><a href="<?php echo $tipsListUrl ?>">规则说明</a>
		</ul>
	</div>
	<div class="table_list">
		<table width="100%">
			<tr class="hd">
				<td width="100">ID</td>
				<td width="140">期号</td>
				<td width="200">用户手机号</td>
				<td width="200">本月剩余时间(秒)</td>
				<td width="200">总通话时长(秒)</td>
			</tr>
			<?php foreach ($data as $key => $value) {
				?>
				<tr class="ct">
					<td><?php echo $value['id']; ?></td>
					<td><?php echo $value['pid']; ?></td>
					<td><?php echo $value['user_phone']; ?></td>
					<td><?php echo $value['left_time']; ?></td>
					<td><?php echo $value['total_time']; ?></td>
					<td><?php echo date('Y-m-d H:i:s', $value['get_time']); ?></td>
				</tr>
			<?php } ?>
		</table>
	</div>
	<div class="mr10 cc">
		<?php echo $pager; ?></div>
<?php echo $this->render("layout/footer.phtml"); ?>