<?php echo $this->render("layout/header.phtml");?>
<?php print_r($info);?>
<div class="nav">
	<ul class="cc">
	    <li><a href="<?php echo $indexUrl;?>?topic_id=<?php echo $topic_id;?>">商品专题列表</a></li>
	    <li class="current"><a href="javascript:;">添加商品专题</a></li>
	</ul>
</div>
<div class="h_a">添加主题</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<input name="topic_id" value="<?php echo $topic_id;?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">名称</th>
				<td class="td"><input type="text" class="input wc" name="title" value=""><?php echo $info['title'];?></td>
			</tr>
            <tr class="tr">
				<th class="th">商品ID</th>
				<td class="td"><input type="text" class="input wc" name="goods_id" value=""></td>
			</tr>
            <tr class="tr">
                <th class="th">促销价(元)</th>
                <td class="td"><input type="text" class="input wb" name="pro_price" placeholder="0.00" value=""></td>
            </tr>
            <tr class="tr">
				<th class="th">原价(元)</th>
				<td class="td"><input type="text" class="input wb" name="price" placeholder="0.00" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">链接地址</th>
				<td class="td"><textarea class="input wc" name="link" rows="5"><?php echo $info['link'];?></textarea></td>
			</tr>
			<tr class="tr">
				<th class="th">图片</th>
				<td class="td">
					<ul class="uploadImg">
						<li id="AdImg">
							<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
							<input type="hidden" name="img" value="">
						</li>
					</ul>			
					<p style="clear:both;">
		                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
					</p></td>
			</tr>
			<tr class="tr">
				<th class="th">排序</th>
				<td class="td"><input type="text" class="input" name="sort" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td">
					<select class="wa" name="status">
						<option value="1">开启</option>
						<option value="0">关闭</option>
					</select>
				</td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script type="text/javascript">
//商品表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $indexUrl;?>?topic_id=<?php echo $topic_id;?>');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
