<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    	<li class="current"><a href="<?php echo $indexUrl;?>?topic_id=<?php echo $topic_id;?>">商品专题列表</a></li>
		<?php if (!empty($topic_id)):?><li><a href="<?php echo $addUrl;?>?topic_id=<?php echo $topic_id;?>">添加商品专题</a></li><?php endif;?>
	</ul>
</div>
<div class="h_a">主题<?php if (!empty($topic_id)):?>(<?php echo $topic_title;?>)<?php endif;?>商品列表</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">排序</td>
			<td width="30">ID</td>
			<td width="150">名称</td>
			<td width="100">图片</td>
			<td width="50">总点击量</td>
			<td width="30">状态</td>
			<td width="120">操作</td>
		</tr>
		<?php if(!empty($list)): foreach ($list as $val):?>
		<tr class="ct">
			<td><?php echo $val['sort'];?></td>
			<td><?php echo $val['id'];?></td>
			<td><?php echo $val['title'];?></td>
			<td><img src="<?php echo $attachPath . $val['img'];?>" width=52/></td>
			<td><?php echo $val['hits'];?></td>
			<td><?php echo $val['status'] == 1 ? '开启' : '关闭';?></td>
			<td>
				<a href="<?php echo $editUrl;?>/?topic_id=<?php echo $val['topic_id'];?>&id=<?php echo $val['id'];?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $val['id'];?>', '', event);">删除</a>
			</td>
		</tr>
		<?php endforeach; endif;?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>