<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">导购列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加导购</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">分类</th>
			<td class="td">
			<select name="ptype">
			<option value="">所有分类</option>
<?php foreach($guide_types as $key=>$value) {?>
				<option <?php if($search['ptype'] == $value['id']) echo 'selected';?> value="<?php echo $value['id'];?>"><?php echo $value['title'];?></option>
<?php }?>
			</select>
			</td>
			<th class="th">渠道</th>
			<td class="td">
				<input type="text" class="input" name="channel"	value="<?php echo $search['channel'][1];?>">
			</td>
            <th class="th">开始日期</th>
            <td class="td">
                <input class="input" type="text" maxlength="30" id="start_time" name="start_time" value="<?php echo $search['start_time'];?>">
            </td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">排序</td>
			<td>标题</td>
			<td>分类</td>
			<td>开始时间</td>
			<td>结束时间</td>
			<td>状态</td>
			<td>点击量</td>
			<td>操作</td>
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><a href="<?php echo $value['link'];?>" <?php if($value['color']) echo 'style="color:'.$value['color'].'"'?> target="_blank"><?php echo $value['title'];?><?php if($value['channel']) echo '('.$value['channel'].')';?></a></td>
			<td><?php echo $guide_types[$value['ptype']]['title'];?></td>
		        <td><?php echo date('Y-m-d H:i:s', $value['start_time']);?></td>
		        <td><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
			<td><?php echo $value['status'] == 1 ? '开启' : '关闭';?></td>
			<td><a href="/admin/stat/click?type_id=9&item_id=<?php echo $value['id'];?>" target="_blank"><?php echo $value['hits'];?></a></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script type="text/javascript">
    $(function(){
        $("#start_time").datepicker({
            dateFormat : 'yy-mm-dd'
        });
    });
</script>
<?php echo $this->render("layout/footer.phtml");?>
