<?php echo $this->render("layout/header.phtml");?>
<body>
	<div class="module dhm-orders-list">
		<div class="iScroll">
			<ul class="layout-center orders-list" id="J_ordersList" data-ajaxurl="<?php echo $webroot;?>/api/order/orderList?id=<?php echo $id;?>"></ul>
		</div>
	</div>

	<script type="text/tempalte" id="J_ordersListTemplate">
		<%for(var i=0, len=data.length; i<len; i++) {%>
		<li>
			<a href="<%=data[i].link%>" class="orders-item">
				<p class="number">订单号：<%=data[i].trade_no%></p>
				<p class="status">订单状态：<em class="<%=(data[i].status == '1' ||data[i].status == '3')? 'hint':''%>"><%=data[i].status_text%></em></p>
				<p class="date-and-price">生成日期：<%=data[i].create_time%>
					<em class="total">总金额：￥<%=data[i].price%></em>
				</p>
			</a>
			<i class="icon-arrow-right"></i>
		</li>
		<%}%>
	</script>
	<!--  订单列表为空 -->
	<script type="text/template" id="noResultTemplate">
		<div class="page-no-result">
			<div class="tip-wrap">
				<div class="pic order"></div>
				<p class="tip">没有相关订单，快去逛逛吧</p>
				<a href="<?php echo $webroot;?>" class="btn btn-submit">去逛逛</a>
			</div>
		</div>
	</script>

	<?php echo $this->render("layout/footer.phtml");?>

	<script>
		(function(){
			require(['ordersList']); 
		}())
	</script>	
</body>
</html>