<?php echo $this->render("layout/header.phtml");?>
<script>
var token = '<?php echo $token;?>';
</script>
<div  id="page">
		<header class="hd">
		    <?php if($bannel) {
		       if( $bannel['ad_ptype'] == 1){
		       	  $tid ='GID';
		       } else if($bannel['ad_ptype'] == 2){
		       	  $tid ='CID';
		       } else if($bannel['ad_ptype'] == 3){
		       	  $tid ='SID';
		       }
		    ?>
		    <a style="display:none;" href="<?php echo Common::tjurl($tjUrl, $bannel['id'], 'AD11', $bannel['link'], '');?>&t_bi=<?php echo $source;?>"><img src="<?php echo $attachPath.$bannel['img'];?>" alt="">
		    <?php } ?>
		    <div class="top-banner">
		    <a class="search" href="<?php echo $webroot.'/search/index?stype=9&t_bi='.$source;?>"></a>
		    </div>
		    
			<nav>
				<ul>
					<li><a href="<?php echo $webroot.'?t_bi='.$source;?>">首页</a></li>
					<li class="selected"><a href="<?php echo $webroot.'/category/?t_bi='.$source;?>">分类</a></li>
					<li><a href="<?php echo $webroot.'/subject/?t_bi='.$source;?>">专题</a></li>
					<li><a href="<?php echo $webroot.'/rank/?flag='.$configs['game_client_rank'].'&t_bi='.$source;?>">排行</a></li>
				</ul>
			</nav>
		</header>

		<section class="wrap">
			<div class="category-list J_classItem">
				<ul>
					<?php 
					 foreach($categorys as $key=>$value){
                     $t_id = 'CATEGORY'.$value['id'];
  ?>
					<li>
						<a href="<?php echo $webroot.'/category/detail/?id='.$value['id'].'&intersrc='.$t_id.'&t_bi='.$source;?>">
							<span class="pic">
								<img data-src="<?php echo $attachPath. $value['img'];?>" src="<?php echo $staticResPath; ?>/pic/blank.gif" alt="">
							</span>
							<span class="desc">
								<b><?php echo $value['title'];?></b>
								<em><?php echo $value['game_title'];?></em>
							</span>
						</a>
					</li>
					<?php }?>
				</ul>
				<?php if($hasnext) {?>
				<div class="load-more J_loadMore"data-ajaxUrl="<?php echo $webroot.'/category/more/?t_bi='.$source;?>" data-hasnext="<?php echo $hasnext;?>" data-curpage="<?php echo $page;?>" data-curClass="<?php echo $tid;?>">
					<span>加载更多</span>
				</div>
				<?php } ?>
			</div>
		</section>

		<div class="goTop J_gotoTop">
			<a ></a>
		</div>
		<footer class="ft">
			<div class="wchat" >
				<img src="<?php echo $staticResPath;?>/pic/wechat.png" alt="" />
				<div>
				<p>欢迎关注我们的微信公众帐号！</p>
				<p>微信号：JXH-20121220</p>
			    </div>
			</div>
			<div class="quick-links">
				<a href="<?php echo $webroot.'/contact?t_bi='.$source;?>">联系我们</a>
				<a href="<?php echo $webroot.'/feedback?t_bi='.$source;?>">意见反馈</a>
				<a href="<?php echo strpos($configs['game_link'], '?') == false ? $configs['game_link'].'&t_bi='.$source :$configs['game_link'].'?t_bi='.$source;?>"><?php echo $configs['game_title'];?></a>
			</div>
		</footer>
	</div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>