<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $listUrl;?>">首页推荐日程</a></li>
        <li class="current"><a href="javascript:;">设置</a></li>
	</ul>
</div>
<div class="h_a">公告设置</div>
<form method="post" action="<?php echo $settingUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">福利任务提示</th>
			<td class="td">
			<select name="switch">
				<option value="0" <?php if($config == 0) echo 'selected';?>>关闭</option>
				<option value="1" <?php if($config == 1) echo 'selected';?>>开启</option>				
			</select>
			</td>
		</tr>		
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $textSetUrl;?>');
	});
})
</script>

<?php echo $this->render("layout/footer.phtml");?>