<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl;?>">新闻列表</a></li>
		<li class="current"><a href="javascript:;">添加新闻</a></li>
	</ul>
</div>
<div class="h_a">添加新闻</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">排序</th>
				<td class="td"><input type="text" class="input" name="sort" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">分类</th>
				<td class="td"><select name="type_id">
				<?php foreach ($newstype as $key=>$value) { ?>
						<option value="<?php echo $key;?>"><?php echo $value['name'];?></option>
				<?php } ?>
				</select></td>
			</tr>
			<tr class="tr">
				<th class="th">标题</th>
				<td class="td"><input type="text" class="input wc" name="title"	value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">链接地址</th>
				<td class="td"><input type="text" class="input wc" name="url"	value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">是否置顶</th>
				<td class="td">
				<input type="hidden" name="istop" id="istop" value="0"/>
				<input type="checkbox" onclick="if(this.checked){$('#istop').val(1);}else{$('#istop').val(0);}">(选中表示设置为置顶)
				</td>
			</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td"><select name="status" class="select">
						<option value="1">开启</option>
						<option value="0">关闭</option>
				</select></td>
			</tr>
			<tr class="tr">
				<th class="th">发布时间</th>
				<td class="td"><input type="text" class="input" id="ontime"
					name="ontime" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">开始时间</th>
				<td class="td"><input type="text" class="input" id="start_time"
					name="start_time" value=""></td>
			</tr>
			<tr class="tr">
				<th class="th">图片</th>
				<td class="td">
					<ul class="uploadImg">
						<li id="NewsImg"><img
							src="<?php echo $staticPath;?>/admin/img/content/nopic.jpg" /> <input
							type="hidden" name="img" value=""> <br />
						<a href="javascript:;" class="delMealImages">删除</a></li>
					</ul>
					<p style="clear: both;">
						<iframe name="upload"
							src="<?php echo $uploadUrl.'/?imgId=NewsImg';?>"
							style="height: 50px; width: 100%;" frameborder="0" scrolling="no"></iframe>
					</p>
				</td>
			</tr>

			<tr class="tr">
				<th class="th">内容</th>
				<td class="td"><textarea id="desc"
						style="width: 800px; height: 200px" class="textarea"
						name="content"></textarea></td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script
	src="<?php echo $staticPath;?>/admin/js/common/jquery-ui-timepicker.js?v=<?=$version?>"></script>
<script
	src="<?php echo $staticPath;?>/admin/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
<script type="text/javascript">
//用户表单数据提交
$('#ontime').datetimepicker();
$('#start_time').datetimepicker();
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/News/index');
	});
})

</script>
<?php echo $this->render("layout/footer.phtml");?>
