<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">日志列表</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>" method="get">
    <input name="token" type="hidden" value="<?php echo $token;?>" />
    <div class="table_full">
        <table width="100%">
            <tr class="tr">
                <th class="th" style="width:10%">UID</th>
                <td class="td">
                    <input type="text" name="uid" value="<?php echo $search['uid']; ?>"/>
                </td>
                <th class="th" class="th" style="width:10%">商品ID</th>
                <td class="td">
                    <input type="text" name="goods_id" value="<?php echo $search['goods_id']; ?>"/>
                </td>
                <th class="th" class="th" style="width:10%">时间</th>
    			<td class="td"><div><input class="input" type="text" style="width:143px;" id="start_time" name="start_time" value="<?php echo $search['start_time'];?>" /> 至 <input class="input" type="text" style="width:143px;" id="end_time" name="end_time" value="<?php echo $search['end_time'];?>" /></div>
    			</td>
            </tr>            
        </table>
    </div>
    <div class="mb10 tac">
		<span class="btn">
			<span>
				<button type="submit">搜 索</button>
			</span>
		</span>
    </div>
    
    <div class="mb10">
        <span class="btn"><span><button type="button" id="extportBtn">导出日志</button></span>
    </div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
            <td width="30">ID</td>
            <td width="300">UID</td>
			<td>商品ID</td>
			<td>商品名称</td>
            <td>商品价格</td>
            <td>起拍价格</td>
			<td>创建时间</td>
			<td>操作</td>
		</tr>
        <?php foreach($data as $key => $value) {?>
        <tr class="ct">
            <td><?php echo $value['id']; ?></td>
            <td><?php echo $value['uid']; ?></td>
            <td><?php echo $value['goods_id']; ?></td>
            <td><?php echo $goods[$value['goods_id']]['title']; ?></td>
            <td><?php echo $value['price']; ?></td>
            <td><?php echo $goods[$value['goods_id']]['price']; ?></td>
            <td><?php echo date('Y-m-d H:i:s',$value['create_time']); ?></td>
            <td>
                <a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $value['id']; ?>', '', event);">删除</a>
            </td>
        </tr>
        <?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>

<div class="mr10 cc">
	<form action="<?php echo $downloadUrl;?>" method="post" id="exportForm">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	<input type="hidden" name="uid" value="<?php echo $search['uid'];?>">
	<input type="hidden" name="goods_id" value="<?php echo $search['goods_id'];?>">
	<input type="hidden" name="start_time" value="<?php echo $search['start_time'];?>">
	<input type="hidden" name="end_time" value="<?php echo $search['end_time'];?>">
	</form>
</div>

<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//导购表单数据提交
$(document).ready(function(){
	$("#start_time").datepicker({
        dateFormat : 'yy-mm-dd'
    });
    $("#end_time").datepicker({
        dateFormat : 'yy-mm-dd'
    });
     $("#extportBtn").click(function(){
			$("#exportForm").submit();
         });
     submitForm = function() {
  		$("#searchForm").submit();
  	};
})
</script>

<?php echo $this->render("layout/footer.phtml");?>
