<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
      <li ><a href="<?php echo $indexUrl;?>">游戏分类列表</a></li>
      <li class="current"><a href="javascript:;">管理子分类</a></li>
	</ul>
</div>
<style>
.btn3 a{
	color: #ffffff;
	height: 21px;
	margin: 0 -9px;
	padding: 0 10px;
	line-height: 21px;
	padding-bottom: 2px;
	text-decoration: none;
}
</style>
<form id="batchForm" action="<?php echo $batchUpdateCategoryUrl;?>" method="post">
	<input name="token" type="hidden" value="<?php echo $token;?>"/>
	<div class="h_a">
		<span >主分类名称：<?php echo $parentCategory['title'];?></span>
		<br/><br/>
		<div>
			<div style="float: left">
				<span class="btn2"><span><button type="submit">批量排序</button></span></span>
			</div>
			<div style="float: right">
				<span class="btn2 btn3"><span><a href="<?php echo $addSubUrl.'?id='. $parentCategory["id"];?>">添加子分类</a></span></span>	
			</div>
		</div>
		<div style="clear:both;"></div>
	</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td width="20"><input type="checkbox" onclick="checkAll('.checkbox')"></td>
		    <td width="20">ID</td>
			<td width="50">排序</td>
			<td width="100">子分类名称</td>
			<td width="20">状态</td>
			<td width="100">操作</td>
		</tr>
		<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><input class="checkbox" name="ids[]" value="<?php echo $value['id'];?>" type="checkbox"></td>
			<td><?php echo $value['id'];?></td>
			<td><input type="text" class="input" style="width:30px" name="sort[<?php echo $value['id'];?>]" value="<?php echo $value['sort'];?>"></td>
			<td><?php echo $value['title'];?></td>
			<td><?php echo $value['status'] ? '开启' : '关闭';?></td>
			<td>
				<a href="<?php echo $editSubUrl;?>/?id=<?php echo $value['id'];?>">编辑</a>
			</td>
		</tr>
		<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
</form>
<script>
$(document).ready(function(){
	ajaxForm('batchForm', function(data) {
		ajaxRedirect(data, baseurl+'/Admin/Resource_Category/subList?id=<?php echo $parentCategory["id"];?>');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
