<?php echo $this->render("layout/header.phtml");?>
<div class="wrap">
	<div class="content">
		<!-- 搜索结果 s-->
		<div class="mod_box error_box">
			<div class="errorTips_con">
				很遗憾，您访问的内容不存在或已过期！ <br />
				<strong class="high">5</strong>秒钟后返回首页
				<p class="btn_area"><a class="get_btn" href="<?php echo $webroot;?>/Front/Index/index">立即返回</a></p>
			</div>
		</div>
		 <!-- 右侧的悬浮框 -->
	    <?php echo $this->render("layout/right.phtml");?>
	</div>
</div>
<?php echo $this->render("layout/footer.phtml");?>
<script language="javascript" type="text/javascript">
setTimeout("javascript:location.href='/Front/Index/index'", 5000);
</script>
</body>
</html>