<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="pay_payindex_index">
        <div class="content">
            <div class="desginer apply">
        	    <div class="com_tb_wrap desginer_tb">
        			<ul>
        				<li >个人设计师</li>
        				<li class="hover">企业设计师</li>
        			</ul>
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
				    <div class="com_tb">
				        <label class="tb_cell">搜索:</label>
				        <div class="tb_cont tb_cell">
				            <input type="text" style="width:350px;" class="rd_1 search_name" value="">
				            <button class="btn_s2 detial_search_btn" id="search_btn">搜索</button>
				            <span class="checkout fr">导出EXCEL</span>
				        </div>
				    </div><!-- com_tb end -->
				</div><!--com_tb_wrap end-->
				<div class="company_apply">
					<table class="view_list_tb">
						<thead>
							<tr>
								<th>姓名</th>
								<th>开户银行及支行</th>
								<th>卡号</th>
								<th>销售额</th>
								<th>平台分成</th>
								<th>个人分成</th>
								<th>本期提现</th>
								<th>前期可提现</th>
								<th>剩余可提现</th>
								<th>备注</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>jerry</td>
								<td>招商银行（车公庙支行）</td>
								<td>123456789</td>
								<td>50</td>
								<td>10</td>
								<td>90</td>
								<td>100</td>
								<td>150</td>
								<td>135</td>
								<td></td>
							</tr>
						</tbody>
					</table>
				</div>
        </div><!-- content end -->
    </div>
</section>
</body>
</html>