<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="pay_payindex_index">
        <div class="content">
        	<div class="desginer_detail">
        		<div class="com_tb_wrap">
        			<div class="com_tb">
	        			<label class="tb_cell">昵称</label>
	        			<div class="tb_cont tb_cell">
	        				<p>jerry</p>
	        			</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">性别</label>
        				<div class="tb_cont tb_cell">
        					<p>男</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">头像</label>
        				<div class="tb_cont ">
        					<div class="account"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">姓名</label>
        				<div class="tb_cont te_cell">
        					<p>小天</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">手机号</label>
        				<div class="tb_cont te_cell">
        					<p>13111111111</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">邮箱</label>
        				<div class="tb_cont te_cell">
        					<p>123456@163.com</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">QQ</label>
        				<div class="tb_cont te_cell">
        					<p>888888888</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">公司名称</label>
        				<div class="tb_cont te_cell">
        					<p>金立移动通信设备有限公司</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">营业执照注册号</label>
        				<div class="tb_cont te_cell">
        					<p>151511165151651651</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">营业执照扫描</label>
        				<div class="tb_cont te_cell">
        					<div class="account"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">税务登记证号</label>
        				<div class="tb_cont te_cell">
        					<p>15165165165</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">税务登记证扫描</label>
        				<div class="tb_cont te_cell">
        					<div class="account"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">开户银行名称</label>
        				<div class="tb_cont te_cell">
        					<p>招商银行</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">开户名称</label>
        				<div class="tb_cont te_cell">
        					<p>金立移动通信有限公司</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">开户支行</label>
        				<div class="tb_cont te_cell">
        					<p>车公庙支行</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">银行卡号</label>
        				<div class="tb_cont te_cell">
        					<p>123456789</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        	</div>
        	<div class="bnts_wrap"><button class="btn_s2" id="comeBack">返回</button></div>
        </div><!-- content end -->
    </div>
</section>
</body>
</html>