<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="pay_payindex_index">
        <div class="content">	
            <div class="desginer detail">
        	    <div class="com_tb_wrap desginer_tb">
        			<ul>
        				<li >个人设计师</li>
        				<li class="hover">企业设计师</li>
        			</ul>
        		</div><!--com_tb_wrap end-->
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">搜索:</label>
                        <div class="tb_cont tb_cell">
                            <input type="text" style="width:350px;" class="rd_1 search_name" value="">
                            <button class="btn_s2 detial_search_btn" id="search_btn">搜索</button>
                            <span class="checkout fr">导出EXCEL</span>
                            <span class="checkout_exc fr">导出并生成报表</span>
                            
                        </div>
                    </div><!-- com_tb end -->
                </div><!--com_tb_wrap end-->
                <div class="desginer_apply">
                    <table class="view_list_tb">
                        <thead>
                            <tr>
                                <th>公司名称</td>
                                <th>开户银行及支行</td>
                                <th>卡号</td>
                                <th>销售额</td>
                                <th>平台分成</th>
                                <th>个人分成</th>
                                <th>本期提现</th>
                                <th>前期可提现</th>
                                <th>剩余可提现</th>
                                <td>状态</td>
                                <th>备注</th>
                            </tr>
                        </thead>
                        <tbody class="add_bg">
                            <tr class="bg_orange">
                                <td>金立通信设备有限公司</td>
                                <td>招商银行（车公庙支行）</td>
                                <td>123456789</td>
                                <td>50</td>
                                <td>10</td>
                                <td>90</td>
                                <td>100</td>
                                <td>150</td>
                                <td>135</td>
                                <td>
                                    <div class="select_box">
                                        <label class="select_val">已通过</label>
                                        <ul class="select_option">
                                            <li>已付款</li>
                                            <li>未通过</li>
                                        </ul>
                                    </div><!-- select_box -->
                                </td>
                                <td></td>
                            </tr>
                            <tr class="bg_gray">
                                <td>金立通信设备有限公司</td>
                                <td>招商银行（车公庙支行）</td>
                                <td>123456789</td>
                                <td>50</td>
                                <td>10</td>
                                <td>90</td>
                                <td>100</td>
                                <td>150</td>
                                <td>135</td>
                                <td>
                                    <div class="select_box">
                                        <label class="select_val">未通过</label>
                                        <ul class="select_option">
                                            <li>已付款</li>
                                            <li>未通过</li>
                                        </ul>
                                    </div><!-- select_box -->
                                </td>
                                <td></td>
                            </tr>
                            <tr class="bg_green">
                                <td>金立通信设备有限公司</td>
                                <td>招商银行（车公庙支行）</td>
                                <td>123456789</td>
                                <td>50</td>
                                <td>10</td>
                                <td>90</td>
                                <td>100</td>
                                <td>150</td>
                                <td>135</td>
                                <td>
                                    <div class="select_box">
                                        <label class="select_val">已付款</label>
                                        <ul class="select_option">
                                            <li>已付款</li>
                                            <li>未通过</li>
                                        </ul>
                                    </div><!-- select_box -->
                                </td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>金立通信设备有限公司</td>
                                <td>招商银行（车公庙支行）</td>
                                <td>123456789</td>
                                <td>50</td>
                                <td>10</td>
                                <td>90</td>
                                <td>100</td>
                                <td>150</td>
                                <td>135</td>
                                <td>
                                </td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
        	</div>
        <!-- content end -->
        </div>
	</div>
</section>

</body>
<script type="text/javascript">
        $(function(){
            $('.add_bg tr').each(function(){
                var $this = $(this);
                if($this.hasClass('bg_orange')){
                    $this.css({background: "orange"});
                }else
                if($this.hasClass('bg_green')){
                    $this.css({background: "green"});
                }else
                if($this.hasClass('bg_gray')){
                    $this.css({background: "gray"});
                }
            })
        })
</script>
</html>