<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="zt_ucenter_edit">
        <div class="content">
        	<div class="change_price_detail">
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">名称</label>
        				<div class="tb_cont tb_cell">
        					<p>特仑苏</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">英文名称</label>
        				<div class="tb_cont tb_cell">
        					<p>Jerry</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">缩略图</label>
        				<div class="tb_cont tb_cell">
        					<div class="pic_small"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">缩略图</label>
        				<div class="tb_cont tb_cell">
        					<div class="pic">
	        					<ul>
	        					<li><img src='<?php echo $staticPath ?>image/t_img03.jpg'></li>
	        					<li><img src='<?php echo $staticPath ?>image/t_img03.jpg'></li>
								<li><img src='<?php echo $staticPath ?>image/t_img03.jpg'></li>
								<li><img src='<?php echo $staticPath ?>image/t_img03.jpg'></li>
	        					</ul>
        					</div>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">一级标签</label>
        				<div class="tb_cont tb_cell">
        					<div class="select_box">
								<label class="select_val">清新文艺</label>
								<ul class="select_option">
									<li>卡通动漫</li>
									<li>卡通动漫</li>
								</ul>
							</div><!-- select_box -->
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
					<div class="com_tb">
						<label class="tb_cell align_top">二级标签</label>
						<div class="tb_cont tb_cell">
							<ul class="tag_add_wrap">
								<li class="btn_tag"><span>风景</span><i class="tag_del"></i></li>
								<li class="btn_tag"><span>美女</span><i class="tag_del"></i></li>
								<li class="btn_tag"><span>室外</span><i class="tag_del"></i></li>
								<li class="btn_tag_add pop_btn" openPopId="fixTagView"><span>+</span></li>
							</ul>
						</div>
					</div><!-- com_tb end -->
				</div><!-- com_tb_wrap end -->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">定价</label>
        				<div class="tb_cont tb_cell">
        					<p></p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">包类</label>
        				<div class="tb_cont tb_cell">
        					<p>V2</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">下载量</label>
        				<div class="tb_cont tb_cell">
        					<p>120</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">介绍</label>
        				<div class="tb_cont tb_cell">
        					<p>1213213215561561</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell top">状态</label>
                        <div class="tb_cont fl">
                            <div class="select_box">
                                <label class="select_val">通过</label>
                                <ul class="select_option">
                                    <li>不通过</li>
                                    <li>未审批</li>
                                </ul>
                            </div><!-- select_box -->
                        </div>
                        <div class="tb_cont fl" style="width:80%;">
                             <textarea class="txt_editor" placeholder="请填写修改的理由及原因"></textarea>
                        </div>
                    </div><!-- com_tb end -->
                </div><!-- com_tb_wrap end -->
                <div class="bnts_wrap">
                <button class="btn_s2 pop_btn" openPopId="fixTipView" id="ztUsrUploadDone">完成</button>
                <button class="btn_s2 pop_btn"  id="cancelDone">取消</button>
            	</div>
        	</div>
        </div><!-- content end -->
    </div>
</section>
	<!-- 弹窗 消息+按钮-->
	<div class="pop_wraper" id="fixTipView">
		<div class="pop_outer">
			<div class="pop_inner">
				<div class="pop_content">
					<!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
					<div class="pop_cont_tip">
						<p class="tip_mes">是否保存当前操作？</p>
						<div class="tip_btns"><button class="btn_s2">确定</button><button class="btn_s2 btnCancel">取消</button></div>
						<div class="pop_close"></div>
					</div>

				</div><!-- pop_content 结束 -->
			</div><!-- pop-inner 结束 -->
		</div><!-- pop-outer 结束 -->
	</div><!-- pop-wraper 结束 -->	

	<!-- 弹窗 添加标签-->
	<div class="pop_wraper" id="fixTagView">
		<div class="pop_outer">
			<div class="pop_inner">
				<div class="pop_content">
					<!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
					<div class="pop_cont_tags">
						
						<ul class="tag_add_wrap tag_list">
							<li class="btn_tag">风景</li>
							<li class="btn_tag">美女</li>
							<li class="btn_tag">室外</li>
							<li class="btn_tag">风景</li>
							<li class="btn_tag">美女</li>
							<li class="btn_tag">室外</li>

							<li class="btn_tag">风景</li>
							<li class="btn_tag">美女</li>
							<li class="btn_tag">室外</li>
							<li class="btn_tag">风景</li>
							<li class="btn_tag">美女</li>
							<li class="btn_tag">室外</li>

							<li class="btn_tag">风景</li>
							<li class="btn_tag">美女</li>
							<li class="btn_tag">室外</li>
							<li class="btn_tag">风景</li>
							<li class="btn_tag">美女</li>
							<li class="btn_tag">室外</li>

							<li class="btn_tag">风景</li>
							<li class="btn_tag">美女</li>
							<li class="btn_tag">室外</li>
							<li class="btn_tag">风景</li>
							<li class="btn_tag">美女</li>
							<li class="btn_tag">室外</li>

							<li class="btn_tag">风景</li>
							<li class="btn_tag">美女</li>
							<li class="btn_tag">室外</li>
							<li class="btn_tag">风景</li>
							<li class="btn_tag">美女</li>
							<li class="btn_tag">室外</li>

							<li class="btn_tag">风景</li>
							<li class="btn_tag">美女</li>
							<li class="btn_tag">室外</li>
							<li class="btn_tag">风景</li>
							<li class="btn_tag">美女</li>
							<li class="btn_tag">室外</li>
							
						</ul>	
						<div class="tag_btns"><button class="btn_s2 btn_tag_add_confirm">确定</button><button class="btn_s2 btn_tag_add_cancel">取消</button></div>
					
						<div class="pop_close"></div>
						
					</div>
						
				</div><!-- pop_content 结束 -->
			</div><!-- pop-inner 结束 -->
		</div><!-- pop-outer 结束 -->
	</div><!-- pop-wraper 结束 -->
</body>
</html>