<?php echo $this->render("common/navigator.phtml"); ?>
<script type="text/javascript" src="<?php echo $staticPath ?>appjs/payment/paylist.js"></script>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="zt_ucenter_edit">
        <div class="content">
        	<div class="message_apply desginer">
        		<div class="com_tb_wrap desginer_tb">
        			<ul>
        				<li class="hover">个人设计师</li>
        				<li >企业设计师</li>
        			</ul>
        		</div><!--com_tb_wrap end-->
        	    <div class="com_tb_wrap">
	                <div class="com_tb">
	                    <label class="tb_cell">搜索:</label>
	                    <div class="tb_cont tb_cell">
	                        <input type="text" style="width:350px;" class="rd_1 search_name" value="">
	                        <button class="btn_s2 detial_search_btn">搜索</button>
	                    </div>
	                </div><!-- com_tb end -->
            	</div>
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell" style="vertical-align:middle">时间范围</label>
        				<div class="tb_cont tb_cell">
        					<div class="time_about">
        						<ul>
        							<li class="hover">近一周</li>
        							<li>近一个月</li>
        							<li>近半年</li>
        							<li>近一年</li>
        						</ul>
        					</div>
        					<div class="time_search">
        						<input name="from" type="text" onClick="laydate({istime:   true, format: 'YYYY-MM-DD hh:mm:ss'})" readonly class="time_start laydate-icon datepicker" style="margin-right:0.2rem" value="<?php echo $from;?>">
								<label class="end_time">至</label>
								<input name="to" type="text" onClick="laydate({istime:   true, format: 'YYYY-MM-DD hh:mm:ss'})" readonly class="time_end laydate-icon datepicker" value="<?php echo $to;?>">
								<button class="btn_s2 search_time" >查询</button>
        					</div>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
					<div class="com_tb">
						<label class="tb_cell" style="vertical-align:middle">排序</label>
						<div class="tb_cont tb_cell">
							<ul class="rank apply_money">
								<li class="first-child hover">申请时间</li>
								<li class="on arrow_up"><a>提现金额</a>
									<ul class="none">
										<li>价格从高到低</li>
										<li>价格从低到到</li>
									</ul>
								</li>
								<li class="on arrow_up last-child"><a>实际提现金额</a></li>
							</ul>
							<div class="change_txt fr">
        						<span><a class="btn_txt">EXCEL</a></span>
        					</div>
						</div>
					</div>
				</div>
				<!-- com_tb_wrap end -->
				<section class="apply_money_List">
					<div class="user_view_list">
						<table class="view_list_tb">
							<thead>
								<tr>
									<th>设计师</th>
									<th>提现金额</th>
									<th>个税（元）</th>
									<th>实际提现金额（元）</th>
									<th>申请时间</th>
									<th>状态</th>
									<th>备注</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>设计师A</td>
									<td>1200</td>
									<td>200</td>
									<td>140</td>
									<td>2015.5.12</td>
									<td>
									 	<div class="select_box">
                                        	<label class="select_val" val="4">已提交</label>
                                        	<ul class="select_option ch_status">
	                                        	<li val="2">已提交</li>
	                                            <li val="3">已提交</li>
                                            </ul>
                                    </div><!-- select_box end-->
									</td>
									<td></td>
								</tr>
								<tr>
									<td>设计师A</td>
									<td>1200</td>
									<td>200</td>
									<td>140</td>
									<td>2015.5.12</td>
									<td>
									 	<div class="select_box">
                                        	<label class="select_val" val="4">已提交</label>
                                        	<ul class="select_option ch_status">
	                                        	<li val="2">已提交</li>
	                                            <li val="3">已提交</li>
                                            </ul>
                                    </div><!-- select_box end-->
									</td>
									<td></td>
								</tr>
							</tbody>
						</table>
					</div>
				</section>
        	</div>
        </div><!-- content end -->
    </div>
</section>
<script type="text/javascript">
	$(function(){

})
</script>
</body>
</html>