<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="pay_payindex_index">
        <div class="content">	
            <div class="desginer detail">
        	    <div class="com_tb_wrap desginer_tb ">
        			<ul>
        				<li >个人设计师</li>
        				<li class="hover">企业设计师</li>
        			</ul>
        		</div><!--com_tb_wrap end-->
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">搜索:</label>
                        <div class="tb_cont tb_cell">
                            <input type="text" style="width:350px;" class="rd_1 search_name" value="">
                            <button class="btn_s2 detial_search_btn" id="search_btn">搜索</button>
                        </div>
                    </div><!-- com_tb end -->
                </div><!--com_tb_wrap end-->
                <div class="desginer_count">
                    <table class="view_list_tb">
                        <thead>
                            <tr>
                                <td>头像</td>
                                <td>昵称</td>
                                <td>姓名</td>
                                <td>公司名称</td>
                                <td>操作</td>
                                <th>备注</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><img src='<?php echo $staticPath ?>image/t_img03.jpg'></td>
                                <td>jerry</td>
                                <td>呵呵哒</td>
                                <td>金立通信设备有限公司</td>
                                <td><a class="btn_txt">详情</a></td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
        	</div>
        <!-- content end -->
        </div>
	</div>
</section>

</body>
<script type="text/javascript">

</script>
</html>