<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="pay_payindex_index">
        <div class="content">	
            <div class="desginer detail">
        	    <div class="com_tb_wrap desginer_tb">
        			<ul>
        				<li class="hover">个人设计师</li>
        				<li >企业设计师</li>
        			</ul>
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">搜索:</label>
                        <div class="tb_cont tb_cell">
                            <input type="text" style="width:350px;" class="rd_1 search_name" value="">
                            <button class="btn_s2 detial_search_btn" id="search_btn">搜索</button>
                        </div>
                    </div><!-- com_tb end -->
                </div><!--com_tb_wrap end-->
                <div class="histroyExcel">
                	<table class="view_list_tb">
                		<thead>
                			<tr>
                				<th>起始日期</th>
                				<th>结束日期</th>
                				<th>生成时间</th>
                				<th>操作</th>
                			</tr>
                		</thead>
                		<tbody>
                			<tr>
                				<td>2015.06.01</td>
                				<td>2015.07.01</td>
                				<td>2015.07.06</td>
                				<td><a class="btn_txt">操作</a></td>
                			</tr>
                			<tr>
                				<td>2015.06.01</td>
                				<td>2015.07.01</td>
                				<td>2015.07.06</td>
                				<td><a class="btn_txt">操作</a></td>
                			</tr>
                		</tbody>
                	</table>
                </div>
        	</div>
        	<!-- content end -->
        </div>
	</div>
</section>

</body>
</html>