<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="zt_ucenter_edit">
        <div class="content">
        	<div class="message_apply">
        	    <div class="com_tb_wrap">
	                <div class="com_tb">
	                    <label class="tb_cell">搜索:</label>
	                    <div class="tb_cont tb_cell">
	                        <input type="text" style="width:350px;" class="rd_1 search_name" value="">
	                        <button class="btn_s2 detial_search_btn">搜索</button>
	                    </div>
	                </div><!-- com_tb end -->
            	</div>
            	<div class="com_tb_wrap" style="border-bottom:0px;">
					<div class="com_tb">
						<label class="tb_cell">状态</label>
						<div class="tb_cont tb_cell">
							<div class="select_box">
								<label class="select_val">全部</label>
								<ul class="select_option">
									<li>美女</li>
									<li>帅哥</li>
								</ul>
							</div><!-- select_box -->
						</div>
						<div class="tb_cell">
							<ul class="tb_switch">
								<li class="btn_switch switch_list on" openId="viewList">列表</li>
							</ul>
						</div>
					</div><!-- com_tb end -->
				</div><!-- com_tb_wrap end -->	
				<section class="apply_money_List">
					<div class="user_view_list">
						<table class="view_list_tb">
							<thead>
								<tr>
									<th>用户名</th>
									<th>营业额(A币)</th>
									<th>销售个数</th>
									<th>增值税(元)</th>
									<th>渠道成本(元)</th>
									<th>分成(元)</th>
									<th>申请时间</th>
									<th>操作</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>用户一</td>
									<td>12</td>
									<td>6</td>
									<td>20</td>
									<td>40</td>
									<td>140</td>
									<td>2015.5.12</td>
									<td><a class="btn_txt">详情</a></td>
								</tr>
								<tr>
									<td>用户二</td>
									<td>15</td>
									<td>8</td>
									<td>20</td>
									<td>40</td>
									<td>180</td>
									<td>2015.5.22</td>
									<td><a class="btn_txt">详情</a></td>
								</tr>
							</tbody>
						</table>
					</div>
				</section>
        	</div>
        </div><!-- content end -->
    </div>
</section>
<script type="text/javascript">
	$(function(){

})
</script>
</body>
</html>