<?php echo $this->render("common/navigator.phtml"); ?>
<link href="<?php echo $staticPath ?>jssdk/plugins/datepicker/laydate.css" rel="stylesheet" type="text/css">
<script type="text/javascript"src="<?php echo $staticPath ?>jssdk/plugins/datepicker/laydate.js"></script>
<script type="text/javascript" src="<?php echo $staticPath ?>appjs/payment/paylist.js"></script>

<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="zt_ucenter_edit">
        <div class="content">
           <div class="operater_list">
           	    <div class="com_tb_wrap">
	                <div class="com_tb">
	                    <label class="tb_cell">搜索:</label>
	                    <div class="tb_cont tb_cell">
	                        <input type="text" style="width:350px;" class="rd_1 search_name" value="">
	                        <button class="btn_s2 detial_search_btn">搜索</button>
	                    </div>
	                </div><!-- com_tb end -->
            	</div><!--com_tb_wrap end-->
            	<div class="pay_content_mid">
        			<div class="pay_view_tab">
        				<ul>
        					<li class="firstWeek hover">一周</li>
        					<li>一个月</li>
        					<li>半年</li>
        					<li>一年</li>
        				</ul>
        			</div>
        			<div class="clear-fix"></div>
        			<div class="pay_time">
        					<label class="strat_time">起始时间</label>
        					<input type="text" onClick="laydate({istime:   true, format: 'YYYY-MM-DD hh:mm:ss'})" readonly class="laydate-icon datepicker" style="margin-right:3rem">
        					<label class="end_time">终止时间</label>
        					<input type="text" onClick="laydate({istime:   true, format: 'YYYY-MM-DD hh:mm:ss'})" readonly class="laydate-icon datepicker">
        					<button class="btn_s2 search_btn">查询</button>
        			</div>
        			<div class="clear-fix"></div>
        		</div>
           </div><!--pay_content_mid end-->
            <div class="com_tb_wrap" style="border-bottom:0px;">
				<div class="com_tb">
					<div class="tb_cell">
						<ul class="tb_switch">
							<li class="btn_txt">导出Excel</li>
						</ul>
					</div>
				</div><!-- com_tb end -->
			</div><!-- com_tb_wrap end -->	
           <div class="pay_veiw_list">
           		<table class="view_list_tb toggle_icon">
           			<thead>
           				<tr>
	           				<th>名称</th>
	           				<th class="on">主题个数</th>
	           				<th class="on">下载个数</th>
	           				<th class="on">销售个数</th>
	           				<th class="on">销售营业额（A币）</th>
	           				<th class="on">可提现金额（元）</th>
	           				<th>操作</th>
	           			</tr>
           			</thead>
           			<tbody>
           				<tr>
           					<td>设计师一</td>
           					<td>12</td>
           					<td>12</td>
           					<td>6</td>
           					<td>200</td>
           					<td>200</td>
           					<td><a class="btn_txt" href="#">操作</a></td>
           				</tr>
           				<tr>
           					<td>设计师二</td>
           					<td>341</td>
           					<td>341</td>
           					<td>221</td>
           					<td>3562</td>
           					<td>3562</td>
           					<td><a class="btn_txt" href="#">操作</a></td>
           				</tr>
           			</tbody>
           		</table>
           </div>
        </div><!-- content end -->
    </div>
</section>

<script type="text/javascript">

</script>
</body>
</html>