<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="zt_ucenter_edit">
        <div class="content">
            <div class="opertaer_detail">
            	<div class="com_tb_wrap">
            		<div class="com_tb">
            			<label class="tb_cell">名称</label>
            			<div class="tb_cont tb_cell">
            				<p>设计师</p>
            			</div>
            		</div><!--com_tb end-->
            	</div><!--com_tb_wrap end-->
            	<div class="com_tb_wrap">
            		<div class="com_tb">
            			<label class="tb_cell">注册日期</label>
            			<div class="tb_cont tb_cell">
            				<p class="regist_time">2015.06.16</p>
            			</div>
            		</div><!--com_tb end-->
            	</div><!--com_tb_wrap end-->
            	<div class="com_tb_wrap">
            		<div class="com_tb">
            			<label class="tb_cell">主题资源</label>
            			<div class="tb_cont tb_cell">
            				<div class="down_num bottom_icon"><span>6</span></div>
                            <div class="showdetail none"><p>显示购买次数的内容</p></div>
                            <div class="desginer_pro">
                            	<ul>
                            		<li>
                            			<div class="li_img"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
                            			<div class="li_intro">
                            				<p class="li_intro_name">主题名称</p>
                            				<p class="li_intro_price">60A</p>
                            				<p class="li_intro_time">2014.6.8</p>
                            			</div>
                            		</li>
                            		<li>
                            			<div class="li_img"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
                            			<div class="li_intro">
                            				<p class="li_intro_name">主题名称</p>
                            				<p class="li_intro_price">60A</p>
                            				<p class="li_intro_time">2014.6.8</p>
                            			</div>
                            		</li>
                            		<li>
                            			<div class="li_img"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
                            			<div class="li_intro">
                            				<p class="li_intro_name">主题名称</p>
                            				<p class="li_intro_price">60A</p>
                            				<p class="li_intro_time">2014.6.8</p>
                            			</div>
                            		</li>
                            		<li>
                            			<div class="li_img"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
                            			<div class="li_intro">
                            				<p class="li_intro_name">主题名称</p>
                            				<p class="li_intro_price">60A</p>
                            				<p class="li_intro_time">2014.6.8</p>
                            			</div>
                            		</li>
                            	</ul>
                            </div>
            			</div>
            		</div><!--com_tb end-->
            	</div><!--com_tb_wrap end-->
            	<div class="com_tb_wrap">
            		<div class="com_tb">
            			<label class="tb_cell" style="width:6rem;">总下载次数</label>
            			<div class="tb_cont tb_cell">
            				<p class="regist_time">120151</p>
            			</div>
            		</div><!--com_tb end-->
            	</div><!--com_tb_wrap end-->
            	<div class="com_tb_wrap">
            		<div class="com_tb">
            			<label class="tb_cell">总营业额</label>
            			<div class="tb_cont tb_cell">
            				<p class="regist_time">120151</p>
            			</div>
            		</div><!--com_tb end-->
            	</div><!--com_tb_wrap end-->
            	<div class="bnts_wrap"><button class="btn_s2 " id="comeBack" openPopId="desginerTruePrice">返回</button></div>
            </div>
        </div><!-- content end -->
    </div>
</section>

<script type="text/javascript">
	$(function(){
		$('.down_num').on('click',function(){
            if($(this).hasClass('bottom_icon')){
                $(this).removeClass('bottom_icon').addClass('top_icon');
                $('.showdetail').removeClass('none');

            }else
            if($(this).hasClass('top_icon')){
                $(this).removeClass('top_icon').addClass('bottom_icon');
                $('.showdetail').addClass('none');
            }
        });
	})
</script>
</body>
</html>