<?php echo $this->render("common/navigator.phtml"); ?>
<link href="<?php echo $staticPath ?>jssdk/plugins/datepicker/laydate.css" rel="stylesheet" type="text/css">

<script type="text/javascript"
src="<?php echo $staticPath ?>jssdk/plugins/datepicker/laydate.js"></script>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="zt_ucenter_edit">
        <div class="content">
        	<!--支付详情开始-->
        	<div class="pay_detail">
        		<div class="com_tb_wrap">
	                <div class="com_tb">
	                    <label class="tb_cell">搜索:</label>
	                    <div class="tb_cont tb_cell">
	                        <input type="text" style="width:350px;" class="rd_1 search_name" value="">
	                        <button class="btn_s2 detial_search_btn">搜索</button>
	                    </div>
	                </div><!-- com_tb end -->
            	</div>
        		<div class="pay_content_mid">
        			<div class="pay_view_tab">
        				<ul>
        					<li class="firstWeek hover">一周</li>
        					<li>一个月</li>
        					<li>半年</li>
        					<li>一年</li>
        				</ul>
        			</div>
        			<div class="clear-fix"></div>
        			<div class="pay_time">
        					<label class="strat_time">起始时间</label>
        					<input type="text" onClick="laydate({istime:   true, format: 'YYYY-MM-DD hh:mm:ss'})" readonly class="laydate-icon datepicker" style="margin-right:3rem">
        					<label class="end_time">终止时间</label>
        					<input type="text" onClick="laydate({istime:   true, format: 'YYYY-MM-DD hh:mm:ss'})" readonly class="laydate-icon datepicker">
        					<button class="btn_s2 search_btn">查询</button>
        			</div>
        			<div class="clear-fix"></div>
        		</div>
        		<div class="com_tb_wrap" style="border-bottom:0px;">
					<div class="com_tb">
						<label class="tb_cell">状态</label>
						<div class="tb_cont tb_cell">
							<div class="select_box">
								<label class="select_val">全部</label>
								<ul class="select_option">
									<li>美女</li>
									<li>帅哥</li>
								</ul>
							</div><!-- select_box -->
						</div>
						<div class="tb_cell">
							<ul class="tb_switch">
								<li class="btn_switch switch_list on" openId="viewList">列表</li>
							</ul>
						</div>
					</div><!-- com_tb end -->
				</div><!-- com_tb_wrap end -->
				<section>
					<div class="pay_veiw_list">
						<table class="view_list_tb">
							<thead>
								<tr>
									<th>主题</th>
									<th>名称</th>
									<th>价格</th>
									<th>下载次数</th>
									<th>购买次数</th>
									<th>购买营业额</th>
									<th>操作</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td><img src='<?php echo $staticPath ?>image/t_img03.jpg'></td>
									<td>特仑苏</td>
									<td>20A</td>
									<td>12</td>
									<td>6</td>
									<td>200</td>
									<td><a class="btn_txt" href="#">详情</a></td>
								</tr>
								<tr>
									<td><img src='<?php echo $staticPath ?>image/t_img03.jpg'></td>
									<td>特仑苏</td>
									<td>20A</td>
									<td>12</td>
									<td>6</td>
									<td>200</td>
									<td><a class="btn_txt" href="#">详情</a></td>
								</tr>
							</tbody>
						</table>
					</div>
				</section>
        	</div><!--支付详情结束-->
        </div><!-- content end -->
    </div>
</section>

<script type="text/javascript">
	$(function(){
	$('.pay_view_tab li').each(function(index){
			var $this = $(this);
			$this.click(function(){
				$this.siblings().removeClass('hover');
				$this.addClass('hover');	
				});

	   });
})
</script>
</body>
</html>