<?php echo $this->render("common/navigator.phtml"); ?>
<link rel="stylesheet" href="<?php echo $staticPath ?>jssdk/plugins/jcrop/jquery.Jcrop.css" type="text/css" />
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="zt_ucenter_edit">
        <div class="content">
            <form name="userInfo" id="userInfo">
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <span class="ucenter_header fl h18">基础资料</span>
                       
                    </div>
                </div>

                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">昵称 :</label>
                        <div class="tb_cont tb_cell">
                            <div class="name">jerry</div>
                        </div>
                    </div>
                </div>

                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">性别 :</label>
                        <div class="tb_cont tb_cell">
                            <div class="sex">男</div>
                        </div>
                    </div>
                </div>

                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell align_middle tb_title">头像 :</label>
                        <div class="tb_cont tb_cell">
                            <div class="account_pic">
                                <img src='<?php echo $staticPath ?>image/t_img03.jpg' style="width:140px">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <div class="ucenter_header fl h18">支付必备</div>
                        <div class="fl pay_header_desc">&nbsp;&nbsp;(用于获得收入分成)</div>
                    </div>
                </div>

                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">角色：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role">个人设计师</div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">真实姓名：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role">Jerry</div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">身份证号码：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role">420222201506075566</div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">邮箱：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role">123456@163.com</div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">联系电话：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role">123456789</div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">开户银行名称：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role">招商银行</div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">开户人姓名：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role">Jerry</div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">开户支行：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role">车公庙支行</div>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell tb_title">银行卡号：</label>
                        <div class="tb_cont tb_cell">
                            <div class="role">123456789</div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <!-- content end -->
    </div>
</section>
</body>

</html>