<?php echo $this->render("common/navigator.phtml"); ?>
<section class="ajax_wrap">
    <div id="pay_paylist_list">
        <div class="content">
        	<div class="salerlist_detail">
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">名称</label>
        				<div class="tb_cont tb_cell">
        					<p>设计师1</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">注册日期</label>
        				<div class="tb_cont tb_cell">
        					<p>2015-07-03</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">主题资源</label>
        				<div class="tb_cont tb_cell">
        					<div class="zt_account arrow_down">30</div>
        					<div class="zt_account_list ">
        						<ul>
        							<li>
        								<div class="li_img"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
        								<div class="li_intro">
        									<p class="li_intro_name">主题名称</p>
        									<p class="li_intro_price">60A币</p>
        									<p class="li_intro_time">2015.05.28</p>
        								</div>
        							</li>
        							<li>
        								<div class="li_img"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
        								<div class="li_intro">
        									<p class="li_intro_name">主题名称</p>
        									<p class="li_intro_price">60A币</p>
        									<p class="li_intro_time">2015.05.28</p>
        								</div>
        							</li>
        							<li>
        								<div class="li_img"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
        								<div class="li_intro">
        									<p class="li_intro_name">主题名称</p>
        									<p class="li_intro_price">60A币</p>
        									<p class="li_intro_time">2015.05.28</p>
        								</div>
        							</li>
        							<li>
        								<div class="li_img"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
        								<div class="li_intro">
        									<p class="li_intro_name">主题名称</p>
        									<p class="li_intro_price">60A币</p>
        									<p class="li_intro_time">2015.05.28</p>
        								</div>
        							</li>
        							<li>
        								<div class="li_img"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
        								<div class="li_intro">
        									<p class="li_intro_name">主题名称</p>
        									<p class="li_intro_price">60A币</p>
        									<p class="li_intro_time">2015.05.28</p>
        								</div>
        							</li>
        							<li>
        								<div class="li_img"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
        								<div class="li_intro">
        									<p class="li_intro_name">主题名称</p>
        									<p class="li_intro_price">60A币</p>
        									<p class="li_intro_time">2015.05.28</p>
        								</div>
        							</li>
        							<li>
        								<div class="li_img"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
        								<div class="li_intro">
        									<p class="li_intro_name">主题名称</p>
        									<p class="li_intro_price">60A币</p>
        									<p class="li_intro_time">2015.05.28</p>
        								</div>
        							</li>
        							<li>
        								<div class="li_img"><img src='<?php echo $staticPath ?>image/t_img03.jpg'></div>
        								<div class="li_intro">
        									<p class="li_intro_name">主题名称</p>
        									<p class="li_intro_price">60A币</p>
        									<p class="li_intro_time">2015.05.28</p>
        								</div>
        							</li>
        						</ul>
        					</div>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">总下载次数</label>
        				<div class="tb_cont tb_cell">
        					<p>120151</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="com_tb_wrap">
        			<div class="com_tb">
        				<label class="tb_cell">总营业额</label>
        				<div class="tb_cont tb_cell">
        					<p>120151</p>
        				</div>
        			</div><!--com_tb end-->
        		</div><!--com_tb_wrap end-->
        		<div class="bnts_wrap"><button class="btn_s2" id="comeBack">返回</button></div>
        	</div>
        <!-- content end -->
        </div>
	</div>
</section>
</body>
<script type="text/javascript">
	$(function(){
		$('.zt_account').on('click',function(){
			var $this = $(this);
			if($this.hasClass('arrow_down')){
				$this.removeClass('arrow_down').addClass('arrow_up');
				$('.zt_account_list').addClass('none');
			}else
			if($this.hasClass('arrow_up')){
				$this.removeClass('arrow_up').addClass('arrow_down');
				$('.zt_account_list').removeClass('none');
			}
		});
	})
</script>
</html>