<?php echo $this->render("common/navigator.phtml"); ?>
<link href="<?php echo $staticPath ?>jssdk/plugins/datepicker/laydate.css" rel="stylesheet" type="text/css">

<script type="text/javascript"
src="<?php echo $staticPath ?>jssdk/plugins/datepicker/laydate.js"></script>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="zt_ucenter_edit">
        <div class="content">
        	<div class="upload_zt_detail">
        		<div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">名称</label>
                        <div class="tb_cont tb_cell">
                            <input type="hidden" class="rd_1 detail_name" value="">

                            <input type="text" class="rd_1 " value="可爱淘">
                        </div>
                    </div><!-- com_tb end -->
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">作者</label>
                        <div class="tb_cont tb_cell">
                            <input type="hidden" class="rd_1 detail_author" value="">

                            <input type="text" class="rd_1 " value="MM">
                        </div>
                    </div><!-- com_tb end -->
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">预览图</label>
                            <div class="cell_img_detial" id="cell_img_detial">
                                <!-- 已经存在了的预览图 start-->
                                <a><img src='<?php echo $staticPath ?>image/t_img03.jpg'></a>
                                <a><img src='<?php echo $staticPath ?>image/t_img03.jpg'></a>
                                <a><img src='<?php echo $staticPath ?>image/t_img03.jpg'></a>
                                <!-- 已经存在了的预览图 end-->
                            </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">一级标签</label>
                         <div class="tb_cont tb_cell">
                            <div class="select_box">
                                <label class="select_val">全部</label>
                                <ul class="select_option">
                                    <li>美女</li>
                                    <li>帅哥</li>
                                </ul>
                            </div><!-- select_box -->
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell align_top">二级标签</label>
                        <div class="tb_cont tb_cell">
                            <ul class="tag_add_wrap">
                                <li class="btn_tag"><span>风景</span><i class="tag_del"></i></li>
                                <li class="btn_tag"><span>美女</span><i class="tag_del"></i></li>
                                <li class="btn_tag"><span>室外</span><i class="tag_del"></i></li>
                                <li class="btn_tag_add pop_btn" openPopId="DetialTagView"><span>+</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell align_middle">主题介绍</label>
                        <div class="tb_cont tb_cell txt_editor_wrap"><textarea class="txt_editor" placeholder="填写主题介绍"></textarea></div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">状态</label>
                        <div class="tb_cont tb_cell">
                            <div class="select_box">
                                <label class="select_val">通过</label>
                                <ul class="select_option">
                                    <li>不通过</li>
                                    <li>未审批</li>
                                </ul>
                            </div><!-- select_box -->
                        </div>
                    </div>
                </div>
                <div class="com_tb_wrap">
                    <div class="com_tb">
                        <label class="tb_cell">上线时间</label>
                        <div  class="tb_cont tb_cell">
                            <input type="text"  value='<?php echo $datatimes ?>'  readonly  class="laydate-icon linetime" onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})"  >
                        </div>
                    </div>
                </div>
            <div class="com_tb_wrap fix_price">
                <div class="com_tb">
                    <label class="tb_cell">定价</label>
                    <div class="tb_cont tb_cell">
                        <ul class="radio_wrap" id="sex">
                            <li class="radio"  val="1" >免费主题</li>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <li class="radio on" val="0" >收费主题</li>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                           	<li style="display:inline-block">
                           		<div class="tb_cont tb_cell">
                            		<div class="select_box">
                               		<label class="select_val">1</label>
                                	<ul class="select_option">
	                                    <li>2</li>
	                                    <li>3</li>
                                    </ul>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->
            <div class="com_tb_wrap">
            	<div class="com_tb">
            		<label class="tb_cell">下载次数</label>
            		<div class="tb_cont tb_cell">
            			<div class="down_time"><span class="time_num">6</span></div>
            		</div>
            	</div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->
            <div class="com_tb_wrap">
            	<div class="com_tb">
            		<label class="tb_cell">购买次数</label>
            		<div class="tb_cont tb_cell">
            			<div class="buy_time"><span class="time_num">12</span></div>
            		</div>
            	</div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->
            <div class="com_tb_wrap">
            	<div class="com_tb">
            		<label class="tb_cell purchase">购买营业额</label>
            		<div class="tb_cont tb_cell">
            			<div class="buy_account"><span class="time_num">200</span></div>
            		</div>
            	</div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->
            <div class="bnts_wrap"><button class="btn_s2" id="saveBtn">保存</button></div>
        </div><!-- content end -->
    </div>
<!-- 弹窗 添加标签-->
    <div class="pop_wraper" id="DetialTagView">
        <div class="pop_outer">
            <div class="pop_inner">
                <div class="pop_content">
                    <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                    <div class="pop_cont_tags">   
                        <ul class="tag_add_wrap tag_list">
                            <li class="btn_tag">风景</li>
                            <li class="btn_tag">美女</li>
                            <li class="btn_tag">室外</li>
                            <li class="btn_tag">风景</li>
                            <li class="btn_tag">美女</li>
                            <li class="btn_tag">室外</li>    
                        </ul>   
                        <div class="tag_btns"><button class="btn_s2 btn_tag_add_confirm">确定</button><button class="btn_s2 btn_tag_add_cancel">取消</button></div>
                        <div class="pop_close"></div>
                        
                    </div>
                        
                </div><!-- pop_content 结束 -->
            </div><!-- pop-inner 结束 -->
        </div><!-- pop-outer 结束 -->
    </div><!-- pop-wraper 结束 -->
</section>
<script type="text/javascript">
	$(function(){

})
</script>
</body>
</html>