<?php echo $this->render("common/navigator.phtml"); ?>
<script type="text/javascript" src="<?php echo $staticPath ?>appjs/payment/paylist.js"></script>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="zt_ucenter_edit">
        <div class="content">
        	<div class="userlist">
        	    <div class="com_tb_wrap">
	                <div class="com_tb">
	                    <label class="tb_cell">搜索:</label>
	                    <div class="tb_cont tb_cell">
	                        <input type="text" style="width:350px;" class="rd_1 search_name" value="">
	                        <button class="btn_s2 detial_search_btn">搜索</button>
	                    </div>
	                </div><!-- com_tb end -->
            	</div>
            	<div class="com_tb_wrap">
					<div class="com_tb">
						<label class="tb_cell" style="vertical-align:middle">排序</label>
						<div class="tb_cont tb_cell">
							<ul class="rank rank_list">
								<li class="first-child hover">申请时间</li>
								<li class="on arrow_up"><a>下载总量</a>
									<ul class="none">
										<li>价格从高到低</li>
										<li>价格从低到到</li>
									</ul>
								</li>
								<li class="on arrow_up "><a>购买总量</a></li>
								<li class="on arrow_up "><a>购买营业额</a></li>
								<li class="on arrow_up last-child"><a>消费金额</a></li>
							</ul>
						</div>
					</div>
				</div><!-- com_tb_wrap end -->
            	<section>
					<div class="user_veiw_list">
						<table class="view_list_tb">
							<thead>
								<tr>
									<th>名称</th>
									<th>下载个数</th>
									<th>购买个数</th>
									<th>购买营业额(A币)</th>
									<th>充值金额(A币)</th>
									<th>操作</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>用户一</td>
									<td>12</td>
									<td>6</td>
									<td>200</td>
									<td>1200</td>
									<td><a class="btn_txt" href="#">详情</a></td>
								</tr>
								<tr>
									<td>用户二</td>
									<td>122</td>
									<td>46</td>
									<td>3562</td>
									<td>6000</td>
									<td><a class="btn_txt" href="#">详情</a></td>
								</tr>
							</tbody>
						</table>
					</div>
				</section>
        	</div>
        </div><!-- content end -->
    </div>
</section>
<script type="text/javascript">
	$(function(){

})
</script>
</body>
</html>