<?php echo $this->render("common/navigator.phtml"); ?>
<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <div id="zt_ucenter_edit">
        <div class="content">
        	<div class="user_apply_detial">

        		<div class="com_tb_wrap view_list_app">
        			<ul>
        				<li class="hover">申请</li>
        				<li>历史</li>
        			</ul>
        		</div>
        		<div class="apply_cont">
	        		<div class="com_tb_wrap" style="border-bottom:0px;">
	        			<div class="tb_cont">
	        				<p>本次可提现金额100元</p>
	        				<p>收入情况：</p>
	        				<table>
	        					<thead>
	        						<tr>
	        							<td>订单状态</td>
	        							<td>营业额（A币）</td>
	        							<td>销售个数</td>
	        							<td>销售金额（）</td>
	        							<td>增值税</td>
	        							<td>渠道成本（元）</td>
	        							<td>分成（元）</td>
	        						</tr>
	        					</thead>
	        					<tbody>
	        						<tr>
	        							<td>普通订单</td>
	        							<td>130</td>
	        							<td>1320</td>
	        							<td>10</td>
	        							<td>22</td>
	        							<td>1255</td>
	        							<td>10000</td>
	        						</tr>
	        					</tbody>
	        				</table>
	        				 <div class="bnts_wrap"><button class="btn_s2" id="saveBtn">保存</button></div>
	        				 <p>提醒:</p>
	        				 <p>1.申请提现时间为每月的1-10号，逾期无法提交申请</p>
	        				 <p>2.单次分成>100元，才可提现</p>
	        			</div>
	        		</div>
        		</div>
        		<div class="apply_cont none">
	        		<div class="com_tb_wrap history">
	        			<div class="tb_cont">
	        				<p>本次可提现金额100元</p>
	        				<p>收入情况：</p>
	        				<table>
	        					<thead>
	        						<tr>
	        							<td>提现单号</td>
	        							<td>提取金额（元）</td>
	        							<td>扣税（元）</td>
	        							<td>实际提现（元）</td>
	        							<td>状态</td>
	        							<td>申请时间</td>
	        						</tr>
	        					</thead>
	        					<tbody>
	        						<tr>
	        							<td>12562</td>
	        							<td>130</td>
	        							<td>20</td>
	        							<td>130</td>
	        							<td>已付款</td>
	        							<td>2014.12.16</td>
	        						</tr>
	        						<tr>
	        							<td>12562</td>
	        							<td>130</td>
	        							<td>20</td>
	        							<td>130</td>
	        							<td>已付款</td>
	        							<td>2014.12.16</td>
	        						</tr>
	        						<tr>
	        							<td>12562</td>
	        							<td>130</td>
	        							<td>20</td>
	        							<td>130</td>
	        							<td>已付款</td>
	        							<td>2014.12.16</td>
	        						</tr>
	        					</tbody>
	        				</table>
	        			</div>
	        		</div>
        		</div>
        	</div>
        </div><!-- content end -->
    </div>
</section>
<script type="text/javascript">
	$(function(){
		$('.view_list_app li').each(function(index){
			var $this = $(this);
			$this.click(function(){
				$this.siblings().removeClass('hover');
				$this.addClass('hover');
				$('.apply_cont').addClass('none');
				$('.apply_cont').eq(index).removeClass('none');
			})
		})
})
</script>
</body>
</html>