<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">推荐列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加推荐</a></li>
	</ul>
</div>

<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">分类</th>
			<td class="td">
			<select name="ptype">
				<option value="0">所有推荐</option>
				<option <?php if ($ptype == 1) echo 'selected';?> value="1">图标推荐</option>
				<option <?php if ($ptype == 2) echo 'selected';?> value="2">列表推荐</option>
			</select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>


<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="60">排序</td>
			<td>标题</td>
			<td>分类</td>
			<td>图片</td>
			<td width="120">开始时间</td>
			<td width="120">结束时间</td>
			<td width="60">状态</td>
			<td width="100">操作</td>
		</tr>
<?php foreach($recommends as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><?php echo $ptypes[$value['ptype']];?></td>
			<td><img src="<?php echo $attachPath.$value['img'];?>" style="width:100px;height:100px;"/></td>
		        <td><?php echo date('Y-m-d H:i:s', $value['start_time']);?></td>
		        <td><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
			<td><?php echo $value['status'] == 1 ? '开启' : '关闭';?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
