<?php echo $this->render("layout/header.phtml"); ?>
<form method="post" action="<?php echo $baseUrl; ?>" id="addFrom">
	<input type="hidden" name="token" value="<?php echo $token; ?>"/>

	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">选择日期</th>
				<td class="td">
					<input class="input" type="text" maxlength="30" id="sdate" name="sdate" value="<?php echo $sdate; ?>"> 至
					<input class="input" type="text" id="edate" maxlength="30" name="edate" value="<?php echo $edate; ?>">

				</td>
			</tr>
			<tr class="tr">
				<th class="th">选择合作商</th>
				<td class="td">
					<select name="cooperate_id" id="cooperate_id">
						<?php foreach ($cooperator as $k => $v) { ?>
							<option value="<?php echo $v['id']; ?>" <?php if ($v['id'] == $cid) echo 'selected' ?>><?php echo $v['name']; ?></option>
						<?php } ?>
					</select>
				</td>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<div class="h_a">
	<span><input type="button" value="导出" id="downLoad"></span><span style="margin-left: 920px">总点击量：<font id="amount" style="color:red"><?php echo $amount; ?></font></span>
</div>
<div class="table_list">
	<table width="90%">
		<tr class="ct">
			<td class="td">日期</td>
			<td class="td">合作商</td>
			<td class="td">点击数</td>
		</tr>
		<?php $sum = 0;
		foreach ($list as $k => $v) {
			$sum += $v['val']; ?>
			<tr class="ct">
				<td class="td"><?php echo $v['date']; ?></td>
				<td class="td"><?php echo $ventor; ?></td>
				<td class="td"><?php echo $v['val']; ?></td>
			</tr>
		<?php } ?>
		<tr class="ct">
			<td>本页汇总</td>
			<td></td>
			<td class="td"><?php echo $sum; ?></td>
		</tr>
	</table>
</div>

<div class="mr10 cc">
	<?php echo $pager; ?>
</div>

<script src="<?php echo $staticPath; ?>/js/admin/highcharts.js"></script>

<script type="text/javascript">
	$(document).ready(function () {
		$("#sdate").datepicker({
			dateFormat: 'yy-mm-dd'
		});
		$("#edate").datepicker({
			dateFormat: 'yy-mm-dd'
		});
	})

	$("#downLoad").bind('click', function () {
		var sdate = $("#sdate").val();
		var edate = $("#edate").val();
		var cooperate_id = $("#cooperate_id").val();

		window.location.href = '<?php echo $baseUrl;?>?export=1&sdate=' + sdate + '&edate=' + edate + '&cooperate_id=' + cooperate_id + 'export=1';

	})
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
