<?php echo $this->render("layout/header.phtml"); ?>

<div class="h_a"><span><a href="/Admin/stat/suggestion">返回列表页</a></span></div>
<div class="table_list">
	<table width="90%">
		<tr class="ct">
			<td class="td2">专题名称</td>
			<td class="td2">意见名称</td>
			<td class="td2">提交次数</td>
		</tr>
		<?php foreach ($data as $v) { ?>
			<tr class="ct">
				<td class="td2"><?php echo $topic['title'] ?></td>
				<td class="td2"><?php echo $v['name'] ?></td>
				<td class="td2"><?php echo $v['num']; ?></td>
			</tr>
		<?php } ?>
	</table>
</div>

<div class="mr10 cc">
	<?php echo $pager; ?>
</div>