<?php echo $this->render("layout/header2.phtml"); ?>
	<section class="main-content">
		<form action="<?php echo $baseUrl; ?>" method="POST">
			<input name="token" value="<?php echo $token; ?>" type="hidden"/>
			<table class="table table-bordered table-striped no-margin">
				<tr class="tr1">
					<td class="td1">
						<?php echo $name . '=>' . $date; ?>
					</td>
				</tr>
				<tr>
					<td>
						<table class="table table-bordered table-striped no-margin">
							<tbody>
							<tr class="ct">
								<td class="td2">消耗时间</td>
								<td class="td2">次数</td>
							</tr>
							<?php
							foreach ($list as $d => $n) {
								?>
								<tr class="ct">
									<td class="td2"><?php echo $d; ?></td>
									<td class="td2"><?php echo $n; ?></td>
								</tr>
							<?php } ?>
							</tbody>
						</table>
					</td>
				</tr>
			</table>

		</form>
	</section>

<?php echo $this->render("layout/footer2.phtml"); ?>