<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li><a href="<?php echo $censusUrl; ?>">PV/UV统计</a></li>
			<li><a href="<?php echo $userLogUrl ?>">新增激活用户</a></li>
			<li><a href="<?php echo $newRegisterUrl; ?>">新增注册用户</a></li>
			<li><a href="<?php echo $connected1Url; ?>">接通统计</a></li>
			<li><a href="<?php echo $periodUrl ?>">通话时段统计</a></li>
		</ul>
	</div>

	<div class="table_list">
		<table width="100%">
			<tr class="tr">
				<td class="td">序号</td>
				<td class="td">拔打用户</td>
				<td class="td">拔打日期</td>
				<td class="td">拔号次数</td>
			</tr>
			<?php foreach ($data as $k => $v) { ?>
				<tr class="ct">
					<td class="td"><?php echo $k + 1; ?></td>
					<td class="td"><?php echo $v['caller_phone']; ?></td>
					<td class="td"><?php echo date('Y-m-d', strtotime($date)); ?></td>
					<td class="td"><?php echo $v['times']; ?></td>
				</tr>
			<?php } ?>
		</table>
	</div>
	<div class="mr10 cc">
		<?php echo $pager; ?>
	</div>
<?php echo $this->render("layout/footer.phtml"); ?>