<?php echo $this->render("layout/webheader.phtml");?>
<body data-pagerole="body">
	<div class="module">
		<div class="invalid-page">
			<img src="<?php echo $staticRoot;?>/apps/gou/pic/pic_invalidPage.png" alt="">
			<p>尊敬的用户，积分换购已下线<br>现全新开放AMIGO商城，去逛逛吧！</p>
			<div class="web-btn"><a href="<?php echo $webroot?>/amigo/index/index">去官方商城逛逛</a></div>
		</div>
	</div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>