<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">广告列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加广告</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="60">排序</td>
			<td>标题</td>
			<td>图片</td>
			<td width="120">开始时间</td>
			<td width="120">结束时间</td>
			<td width="60">状态</td>
			<td width="100">操作</td>
		</tr>
<?php foreach($ads as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><img src="<?php echo $attachPath.$value['img'];?>" style="width:200px"/></td>
		        <td><?php echo date('Y-m-d H:i:s', $value['start_time']);?></td>
		        <td><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
			<td><?php echo $value['status'] == 1 ? '开启' : '关闭';?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
