<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">公告活动管理</a></li>
    <li class="current"><a href="javascript:;">添加</a></li>
	</ul>
</div>
<div class="step mb10">
		<ul class="cc">
			<li class="current">创建</li>
			<li class="line"></li>
		</ul>
</div>
<div class="h_a">添加</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="0" id="sort"></td>
		</tr>
		<tr class="tr">
			<th class="th">参与游戏</th>
			<td class="td">
			    <label><input name="join_game_type" class="join_game_type" type="radio" checked value="0" />全部 </label> 
				<label><input name="join_game_type" class="join_game_type" type="radio" value="1" />定向</label> 
				<label><input name="join_game_type" class="join_game_type" type="radio" value="2" />排除</label> 
				(输入游戏ID，并以英文逗号隔开)
	         </td>
		</tr>
		<tr >
			<th class="th"></th>
			<td ><textarea disabled="disabled" style="width:350px; height:150px" class="textarea" name="game_ids" id="game_ids" ></textarea></td>
		</tr>
		
		<tr class="tr">
			<th class="th">显示范围</th>
			<td class="td">
			    <label><input name="show_type[]" type="checkbox" checked value="1" />公告 </label> 
				<label><input name="show_type[]" type="checkbox" value="2" />活动 </label> 
	         </td>
		</tr>
	
		<tr class="tr">
			<th class="th">名称</th>
			<td class="td"><input type="text" class="input wc" name="title" value="" id="title"></td>
		</tr>
		<tr class="tr">
			<th class="th">生效时间</th>
			<td class="td"><div><input class="input" type="text" maxlength="30" style="width:143px;" id="start_time" name="start_time" value="<?php echo date('Y-m-d H:00:00'); ?>" /> 至 <input class="input" type="text" maxlength="30" style="width:143px;" id="end_time" name="end_time" value="" /></div>
			</td>
		</tr>
				<tr class="tr">
			<th class="th">图片</th>
			<td class="td">
				<ul class="uploadImg">
					<li id="AdImg">
						<img src="<?php echo $staticPath;?>/img/content/nopic.jpg"/>
						<input type="hidden" name="img" value="">
					</li>
				</ul>			
				<p style="clear:both;">
	                  <iframe name="upload" src="<?php echo $uploadUrl.'/?imgId=AdImg';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no"></iframe>
				</p></td>
		</tr>
		<tr class="tr">
			<th class="th" id="th_link">内容</th>
			<td class="td" > 
		        <textarea  style="width:600px; height:300px" class="textarea" name="ad_content" id="ad_content" ></textarea>
			</td>
		</tr>
		<tr class="tr" id="is_payment" >
			<th class="th" >是否出现充值快捷方式</th>
			<td class="td">
				<label class="mr20"><input  name="is_payment"  value="1" type="radio" checked >是</label>
				<label class="mr20"><input  name="is_payment"  value="0" type="radio" checked >否</label>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">状态</th>
			<td class="td"><select name="status">
                	<option value="1">开启</option>
                	<option value="0">关闭</option>
            </select></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">完成</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/admin/kindeditor/kindeditor.js?v=<?=$version?>"></script>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">

$(document).ready(function(){
	var editor;
	 KindEditor.ready(function(K) {
			K.token = '<?php echo $token;?>';
		    editor = K.create('textarea[name="ad_content"]', {
		        resizeType : 1,
		        allowPreviewEmoticons : false,
		        allowImageUpload : true,
		        uploadJson : '<?php echo $uploadImgUrl;?>',
		        items : EDITOR_ITEMS
		    });
		});
	 $('#start_time').datetimepicker({
         timeFormat: "hh:00:00",
         dateFormat: "yy-mm-dd"
     });
     $('#end_time').datetimepicker({
         timeFormat: "hh:00:00",
         dateFormat: "yy-mm-dd"
     });
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
     //提交表单
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Sdk_Ad_Activity/index');
	},function(){
		editor.sync();
	});
	$("input[name='join_game_type']").click(function(){
		 value = $('input[name="join_game_type"]:checked').val();
	     if(value == '0'){
			$('#game_ids').attr('disabled','disabled');
			 $('#game_ids').val('');
	     }else{
	    	 $('#game_ids').removeAttr('disabled');
		} 
	 });

})

</script>
<?php echo $this->render("layout/footer.phtml");?>
