<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">跳转列表</a></li>
    <li class="current"><a href="javascript:;">添加跳转</a></li>
	</ul>
</div>
<div class="h_a">添加跳转</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
	<tr class="tr">
			<th class="th">分类</th>
			<td class="td"><select name="sort">
<?php foreach($sorts as $key => $value) {?>
                <option value="<?php echo $key;?>"><?php echo $value;?></option>
<?php }?>
            </select></td>
		</tr>
		<tr class="tr">
			<th class="th">预置名称</th>
			<td class="td"><input type="text" class="input" name="name" value="" size="30"></td>
		</tr>
		<tr class="tr">
			<th class="th">预置地址</th>
			<td class="td"><input type="text" class="input" name="url" value="" size="60"></td>
		</tr>
		<tr class="tr">
			<th class="th">跳转网站</th>
			<td class="td"><input type="text" class="input" name="redirect_name" value="" size="30"></td>
		</tr>
		<tr class="tr">
			<th class="th">跳转地址</th>
			<td class="td"><input type="text" class="input" name="redirect_url" value=""  size="60"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Redirect/index');
	});
})

</script>
<?php echo $this->render("layout/footer.phtml");?>
