<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">跳转列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加跳转</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td>编号</td>
			<td>预置名称／地址</td>
			<td>跳转名称／地址</td>
			<td>操作</td>
		</tr>
<?php foreach($redirects as $key => $value) {
?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
            <td><?php echo $value['name'].' / '. $value['url'];?></td>
			<td><?php echo $value['redirect_name'].' / '.$value['redirect_url'];?></td>
			<td>
				<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
