<?php echo $this->render("layout/header.phtml"); ?>
<div class="table_full">
	<form action="<?php echo $baseUrl; ?>" method="POST">
		<input type="hidden" name="token" value="<?php echo $token; ?>"/>
		<table width="100%" cellspacing="0" cellpadding="0">
			<tr class="tr1">
				<td class="td1">
					日期：
					<input class="input" type="text" maxlength="30" id="ym" name="ym" value="<?php echo $ym; ?>">
					类型：
					<select name="type">
						<?php foreach ($types as $value) { ?>
							<option <?php echo ($value == $type) ? 'selected="selected"' : ''; ?> value="<?php echo $value; ?>"><?php echo $value; ?></option>
						<?php } ?>
					</select>
					<input type="submit" value="查询"/>
				</td>
			</tr>
		</table>
	</form>
</div>


<div class="h_a"><span>总访问量: </span>&nbsp;&nbsp;<span id="amount" style="color: red"></span>
</div>
<div class="table_list">
	<table cellspacing="0" cellpadding="0" width="100%">
		<tbody>
		<tr class="ct">
			<td class="td2" width="200px">时间</td>
			<td class="td2" width="70px">数量</td>
		</tr>
		<?php
		$sum = 0;
		foreach ($lineData as $k => $v) {
			$sum += $v['total'];
			?>
			<tr class="ct">
				<td class="td2"><?php echo $v['date']; ?></td>
				<td class="td2"><?php echo $v['total']; ?></td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>


<script src="<?php echo $staticPath; ?>/js/admin/highcharts.js"></script>
<script src="<?php echo $staticPath; ?>/js/admin/exporting.js"></script>
<script src="<?php echo $staticPath; ?>/js/admin/stat.js"></script>

<script type="text/javascript">
	$(document).ready(function () {
		$("#ym").datepicker({
			dateFormat: 'yymm'
		});

	})
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
<script>
	$("#amount").text('<?php echo $sum?>');

</script>