<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">商家列表</a></li>
	</ul>
</div>
<form action="<?php echo $indexUrl;?>" method="get">
    <input name="token" type="hidden" value="<?php echo $token;?>" />
    <input name="goods_id" value="<?php echo $search['goods_id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<td class="td">商品名称</td>
			<td class="td">
				<input class="input wb" type="text" name="title" value="<?php echo $search['title'];?>">
			</td>
			<td class="td">商家</td>
			<td class="td">
                <select name="mall_id" class="wa">
                    <option <?php if (!$search['mall_id']) echo 'selected';?>  value="">不限</option>
                    <?php foreach ($malls as $item) {?>
                        <option <?php if ($search['mall_id'] == $item['id']) echo 'selected = selected';?>  value="<?php echo $item['id'];?>"><?php echo $item['name'];?></option>
                    <?php }?>
                </select>
			</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">ID</td>
			<td>商品ID</td>
			<td width="200">商品</td>
			<td>商家</td>
			<td>商家类型</td>
			<td>最低价</td>
            <td>最高价</td>
            <td width="320">商品地址</td>
			<td>操作</td>
		</tr>
<?php foreach($data as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['goods_id'];?></td>
            <td><?php echo $goods[$value['goods_id']]['title'];?></td>
            <td><?php echo $malls[$value['mall_id']]['name'];?></td>
            <td><?php echo $malls[$value['mall_id']]['type_id']==1 ? '线上' : '线下';?></td>
            <td><?php echo $value['min_price'];?></td>
			<td><?php echo $value['max_price'];?></td>
			<td><?php echo $value['url'];?></td>
			<td>
				<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
				<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
