<?php 
    $source = strpos(Util_Http::getServer('REQUEST_URI'), 'debug') ? '.source' : '';
?>
<script src="<?php echo $staticRoot;?>/apps/dhm/asset/build/lib/libs<?php echo $source;?>.js"></script>
<script src="<?php echo $staticRoot;?>/apps/dhm/asset/build/js/page<?php echo $source;?>.js"></script>

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?075223dc664020f18fb4db59340bf3b0";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
</body>
</html>

