<!DOCTYPE HTML>
<html>
<head>
	<meta charset="UTF-8">
	<title><?php echo $title;?></title>
	<meta name="keywords" content="<?php echo $keywords;?>" />
    <meta name="description" content="<?php echo $description;?>" />
	
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="email=no" />
    <?php 
    $source = strpos(Util_Http::getServer('REQUEST_URI'), 'debug') ? '.source' : '';
    ?>
    <link type="text/css" rel="stylesheet" href="<?php echo $staticRoot;?>/sys/reset/phonecore<?php echo $source;?>.css?t=<?php echo $version;?>">
    <link type="text/css" rel="stylesheet" href="<?php echo $staticRoot;?>/apps/dhm/asset/build/css/style<?php echo $source;?>.css?t=<?php echo $version;?>">
</head>
