<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">分辨率列表</a></li>
    <li class="current"><a href="javascript:;">添加分辨率</a></li>
	</ul>
</div>
<div class="h_a">添加分辨率</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
	
		<tr class="tr">
			<th class="th">分辨率</th>
			<td class="td"><input type="text" class="input" name="size" value="">(如320＊480)</td>
		</tr>
		<tr class="tr">
			<th class="th">排序</th>
			<td class="td"><input type="text" class="input" name="sort" value="0">（填写一个数字，数字越大越靠前）</td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
//表单数据提交
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Size/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
