<?php echo $this->render("common/navigator.phtml"); ?>

<style type="text/css">
    .addcolor{
        background-color: #EBEBEf;
    }
</style>
<!-- 导航栏Ajax加载 指向navagator.html  menuOn表示分别需要高亮的菜单栏id 用下划线_隔开 eg:bz_taotu_taotuPack-->


<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <!-- wp01-壁纸详情-->
    <div id="lbz_hot">
        <!-- 页面内容区域 注意：每个页面无论是否有内容 必定有一个content-->
        <div class="content">
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">分类</label>
                    <div class="tb_cont tb_cell">
                        <ul class="tag_list tag_one"><!-- tag_one 一级标签 只能选中一个 -->
                            <a href="/Admin/wallpaperlive/hot">
                                <li class="<?php if (!$tid) echo 'on'; ?>">全部</li></a>
                            <?php foreach ($livewallpaperType as $k => $v) { ?>
                                <a href="/Admin/wallpaperlive/hot?tid=<?php echo $k ?>">
                                    <li class="<?php if ($k == $tid) echo 'on'; ?>"><?php echo $v ?></li></a>
                            <?php } ?>
                        </ul>
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->

            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">搜索:</label>
                    <div class="tb_cont tb_cell">
                        <input type="text" style="width:350px;" class="rd_1 search_name" value="<?php echo $search ?>">
                        <button class="btn_s2 search_btn">搜索主题</button>
                    </div>
                </div>
            </div><!-- com_tb end -->
        </div><!-- com_tb_wrap end -->

        <!-- 列表模式 -->
        <section class="view view_list show" id="viewList">
            <!-- 批量管理内容 默认隐藏 -->
            <div class="view_admin view_list_admin">
                <!-- checkClass表示 点击后 哪些class要被选中 -->
                <button class="btn_check btn_check_all" checkClass="btn_check_list"></button><label>全选</label><span class="btn btn_s1 pack_approve">批量通过</span><span class="btn btn_s1 pack_del">批量删除</span>
            </div>
            <table class="view_list_tb">
                <thead>
                    <tr><th>壁纸</th><th>名称</th>
                        <th>上线时间</th>
                        <th>上传时间</th>
                        <th>下载量</th>
                        <th>点赞</th>
                        <th>排序</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($wallpaperlive as $v) { ?>
                        <tr class="<?php if ($v['wallpaperlive_type'] == 2) echo "addcolor"; ?>">
                            <td><button class="btn_check btn_check_list"></button>
                                <img src="<?php echo $v['imgs'][0] ?>">
                            </td>
                            <td><?php echo $v['wallpaperlive_name'] ?></td>
                            <td><?php if ($v['wallpaperlive_onlinetime']) { echo date("Y-m-d H:i:s", $v['wallpaperlive_onlinetime']);} else {echo '-';} ?></td>
                            <td><?php echo date("Y-m-d H:i:s", $v['wallpaperlive_uploadtime']); ?></td>
                            <td><?php echo $v['wallpaperlive_down']; ?></td>
                            <td><?php echo $v['wallpaperlive_like']; ?></td>
                            <td val="<?php echo $v['wallpaperlive_id'] ?>"><input class="numSort" size="12" type="text" value="<?php echo $v['hot_sort'] ?>"></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </section>

        <!-- 分页模块 -->
        <?php echo $this->render("common/pageshow.phtml"); ?>
    </div><!-- content end -->

</div>
</section>

<script>
    $(function () {
         $(".numSort").change(function () {
            var sort = $(this).val();
            var id = $(this).parent().attr("val");

            if (isNaN(sort)) {
                alert("请输入有效的数字");
                return 0;
            } else {
                var uri = "sort=" + sort + "&id=" + id + "&token=" + token;
                var url = "/Admin/wallpaperlive/updateHot";
                $.post(url, uri, function (data) {
                    if(data == 1){
                        window.location.href = "/Admin/wallpaperlive/hot";
                    }
                })
            }

        });
        $(".search_btn").on("click", function () {
            var name = $(".search_name").val();
            window.location.href = "/Admin/wallpaperlive/hot?keyword=" + name;
        });
    })
</script>
</body>
</html>