<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li><a href="<?php echo $listUrl.'/?column_version=1.5.2';?>">1.5.2</a></li>
		<li><a href="<?php echo $listUrl.'/?column_version=1.5.3';?>">1.5.3-1.5.7</a></li>
		<li><a href="<?php echo $listUrl.'/?column_version=1.5.8';?>">1.5.8及以上</a></li>
		<li class="current"><a href="javascript:;">查看栏目配置</a></li>
	</ul>
</div>
<div class="h_a">查看栏目配置</div>
<div class="step mb10">
	<ul class="cc">
		<li style="width:25%;"  class="current" ><span class="fl"><em>设置栏目</em></span></li>
		<li class="line" style="left:25%"></li>
		<li style="width:25%"><span class="fl"><em>设置频道</em></span></li>
		<li class="line" style="left:50%"></li>
		<li style="width:25%"><span class="fl"><em>频道排序</em></span></li>
		<li class="line" style="left:75%"></li>
		<li  style="width:25%"><span class="fl"><em>设置时间</em></span></li>
	
	</ul>
</div>
<div class="table_list">
	<table width="100%">
	<tr class="hd" >
		<td width="10%">位置</td>
		<td width="10%">名称</td>
		<td width="10%">状态</td>
		<td width="35%" >选中图片</td>
		<td width="35%">默认图片</td>
	</tr>
	<?php foreach ($info as $key=>$value) {?>
	<tr class="ct" >
	    <td><?php echo $value['position'];?></td>
		<td><input type="text" class="input" name="name" value="<?php echo $value['name']?>" size="10" disabled="disabled"></td>
		<td>
			<select name="status" class="select" disabled="disabled">
				<option  value="1" <?php ($value['status'] == 1)?'SELECTED':''; ?> >开启</option>
				<option  value="0" <?php ($value['status'] == 0)?'SELECTED':''; ?> >关闭</option>
			</select>
		</td>
		<td>
			<ul class="uploadImg">
				<li id="icon_choose<?php echo ($key+1) ;?>">
					<img src="<?php echo ($value['icon_choose'])?$attachPath.$value['icon_choose']:$staticPath.'/img/content/nopic.jpg';?>"/>
					<input type="hidden" name="icon_choose<?php echo ($key+1);?>" value="<?php echo $value['icon_choose'];?>">
				</li>
			</ul>			
		</td>
		<td>
			<ul class="uploadImg">
				<li id="icon_default<?php echo ($key+1) ;?>">
					<img src="<?php echo ($value['icon_default'])?$attachPath.$value['icon_default']:$staticPath.'/img/content/nopic.jpg';?>"/>
					<input type="hidden" name="icon_default<?php echo ($key+1);?>" value="<?php echo $value['icon_default'];?>">
				</li>
			</ul>			
	   </td>
	</tr>
	<?php }?>
	</table>
	<table width="100%">
		<tr class="tr"><td class="td">默认打开</td>
		<td>	
		   <select name="default_open" class="select wa" disabled="disabled">
	   		 <?php foreach ($info as $value) { ?>
				<option <?php if ($value['default_open'] == 1) echo 'selected';?> value="<?php echo $value['position'];?>"><?php echo $value['position'];?></option>
			 <?php }?>
			</select>
		</td>
		</tr>
	</table>
</div>
<div class="mb10 tac">
<a href="<?php echo $viewChannelSetUrl.'/?log_id='.$log_id.'&column_version='.$value['column_version']; ?>" style="color: #fff;padding: 6px;display: inline-block;background: #c83f38;border-radius: 2px;width: 50px;text-decoration:none;">下一步</a>
</div>
<?php echo $this->render("layout/footer.phtml");?>
