<?php echo $this->render("layout/header.phtml"); ?>
<div class="nav">
	<ul class="cc">
		<li class="current"><a href="<?php echo $listUrl; ?>">PUSH列表</a></li>
		<li><a href="<?php echo $addUrl; ?>">添加PUSH配置</a></li>
	</ul>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="120">type</td>
			<td width="120">title</td>
			<td>text</td>
            <td>big_picture_url</td>
            <td>url</td>
			<td width="100">操作</td>
		</tr>
		<?php foreach ($pushtools as $key => $value) { ?>
			<tr class="ct">
				<td><?php echo $value['type']; ?></td>
				<td><?php echo $value['title']; ?></td>
				<td><?php echo $value['text']; ?></td>
				<td><?php echo $value['big_picture_url']; ?></td>
				<td><?php echo $value['url']; ?></td>
				<td>
				    <a href="<?php echo $showUrl; ?>/?id=<?php echo $value['pid']; ?>" class="mr10">查看</a>
					<a href="<?php echo $editUrl; ?>/?id=<?php echo $value['pid']; ?>" class="mr10">编辑</a>
					<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl; ?>/?id=<?php echo $value['pid']; ?>', '', event);">删除</a>
				</td>
			</tr>
		<?php } ?>
	</table>
</div>
<?php echo $this->render("layout/footer.phtml"); ?>
