<!DOCTYPE HTML>
<html>
<head>
<title>积分抽奖</title> 
<meta charset="UTF-8">
<meta name="keyword" content="金立, 金立游戏, 游戏大厅" />
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<meta name="format-detection" content="email=no" />
<link rel="stylesheet" href="<?php echo $staticroot; ?>/apps/game/apkv1/assets/css/prize.css?v=<?php echo $version;?>" />
</head>
<body>
<?php if($prize):?>
	<script type="text/javascript">
		var token = '<?php echo $token;?>';
		var isLogin = <?php echo $isLogin ? 'true' : 'false';?>;
 		var prizeId = <?php echo $prize['id'];?>;
	</script>
	<!-- 抽奖宣传图 -->
	<div class="banner-container">
		<img src="<?php echo $attachPath.$prize['img'];?>" alt="">
		<a class="btn-rule" data-type="0" data-source="lotterydes" data-viewType="WebView"  data-infpage=",<?php echo $webroot.'/client/prize/rule/?id='.$prize['id']?>" >规则说明&gt;</a>
		<div id="rolling" class="btn-rolling invisible" data-ajaxUrl="<?php echo  $webroot.'/api/point/prizeWin'?>"> <!-- 前10条中奖信息 -->
		</div>
	</div>
	<!-- 积分使用情况 -->
	<div class="points-container">
		<div class="pointLeft">
			<span>剩余 <em id="prize-totalPoints"><?php echo $userInfo['points'] ? intval($userInfo['points']) : 0 ?></em> 个积分</span>
			<span>每次抽奖消耗 <em id="prize-consumePoints"><?php echo $prize['point']?></em> 个积分</span>
		</div>
		<a  data-action="gamehall.daily.task"  class="btn-points">领积分</a>
	</div>

	<!-- 抽奖区域 -->
	<div class="prize-container">
		<div id="prize_wrap" class="prize-wrap" >
			<div class="box-wrap">
				<li id="prize-grid0" class="box prize-unit" data-id="1">
					<div class="content ">
						<img src="<?php echo $attachPath.$config[1]['img'];?>" alt=""/>
					</div>
				</li>
				<li id="prize-grid1" class="box prize-unit" data-id="2">
						<div class="content">
							<img src="<?php echo $attachPath.$config[2]['img'];?>" alt=""/>
						</div>
				</li>
				<li id="prize-grid2" class="box prize-unit" data-id="3">
					<div class="content">
						<img src="<?php echo $attachPath.$config[3]['img'];?>" alt=""/>
					</div>
				</li>
			</div>
			<div class="box-wrap">
				<li id="prize-grid7" class="box prize-unit" data-id="8">
					<div class="content">
						<img src="<?php echo $attachPath.$config[8]['img'];?>" alt=""/>
					</div>
				</li>
				<li id="prize-btn"  class="box" data-ajaxUrl="<?php echo $webroot.'/api/point/prizeStart'?>">
					<div class="content1">
					</div>
				</li>
				<li id="prize-grid3" class="box prize-unit" data-id="4">
					<div class="content">
						<img src="<?php echo $attachPath.$config[4]['img'];?>" alt=""/>
					</div>
				</li>
			</div>
			<div class="box-wrap lastLine">
				<li id="prize-grid6" data-id="7" class="box prize-unit">
						<div class="content">
							<img src="<?php echo $attachPath.$config[7]['img'];?>" alt=""/>
						</div>
				</li>
				<li id="prize-grid5" data-id="6" class="box prize-unit">
					<div class="content">
						<img src="<?php echo $attachPath.$config[6]['img'];?>" alt=""/>
					</div>
				</li>
				<li id="prize-grid4" data-id="5" class="box prize-unit">
					<div class="content">
						<img src="<?php echo $attachPath.$config[5]['img'];?>" alt=""/>
					</div>
				</li>
			</div>
		</div>
	</div>

	<div class="J_dialog dialog invisible">
		
	</div>
	<!-- 未中奖 -->
	<div class="J_noPrize no-prize-container invisible">
		<div class="img-container">
			<div class="box">
				<div class="content">
					<img src="" alt=""/>
				</div>
			</div>
			<span class="tips">呃，就差一点点了...</span>
		</div>
		<div class="btn-container tline">
			<a id="close">不抽了</a>
			<a id="continue" class="lline">继续抽奖</a>
		</div>
	</div>
	<!-- 实物奖励 -->
	<div class="J_entity entity-prize-container invisible">
		<div class="img-container">
			<div class="box">
				<div class="content">
					<img src="" alt=""/>
				</div>
			</div>
			<span class="tips">恭喜，人品爆发，抽中<em id="prizeName"></em></span>
		</div>
		<div class="addressinfo-container tline">
			<span class="address-tips">请填写信息领取奖品</span>
			<div class="ad-info">
				<em>收货人:</em><input id="name" class="btn-input" type="text" placeholder="姓名" />
			</div>
			<div class="ad-info">
				<em>联系电话:</em><input id="phone" class="btn-input" type="text" placeholder="手机或固话" />
			</div>
			<div class="ad-info">
				<em>收货地址:</em><textarea id="address" class="btn-input btn-textarea" rows="3"  placeholder="所在省市详细街道信息"></textarea>
			</div>
		</div>
		<div class="btn-container tline">
			<a id="submit" data-ajaxUrl="<?php echo $webroot.'/api/point/prizeSubmit'?>">提交信息</a>
			<a class="loading-btn hidden"><i class="icon-loading"></i>正在提交，请稍等...</a>
		</div>
	</div>
	<!-- a券奖励 -->
	<div class="J_acoin acoin-prize-container invisible">
		<div class="img-container">
			<div class="box">
				<div class="content">
					<img src="" alt=""/>
				</div>
			</div>
			<span class="tips">恭喜，抽中<em id="prizeName"></em>A券</span>
		</div>
		<div class="tips-container tline">
			<span>A券仅<em id="indate"></em>有效，请尽快使用！</span>
			<span>可在"我的A券"中查看A券详情</span>
		</div>
		<div class="btn-container tline">
			<a data-type="0" data-viewType="WebView" data-source="acertificate"  data-infpage="我的A券,<?php echo $webroot . '/client/task/myticket'; ?>" id="acoin">查看A券</a>
			<a id="continue" class="lline">继续抽奖</a>
		</div>
	</div>
	<!-- 积分奖励 -->
	<div class="J_points points-prize-container invisible">
		<div class="img-container">
			<div class="box">
				<div class="content">
					<img src="" alt=""/>
				</div>
			</div>
			<span class="tips">恭喜，抽中<em id="prizeName"></em>积分</span>
		</div>
		<div class="tips-container tline">
			<span>积分可用来抽奖！</span>
			<span>积分可在积分商城中兑换奖品！</span>
		</div>
		<div class="btn-container tline">
			<a id="close">不抽了</a>
			<a id="continue" class="lline">继续抽奖</a>
		</div>
	</div>
	<script src="<?php echo $staticroot; ?>/??/apps/game/apkv1/assets/js/sys/jquery.js,/apps/game/apkv1/assets/js/sys/fastclick.js,/apps/game/apkv1/assets/js/prize/prize.source.js?v=<?php echo $version;?>"></script>
	 <?php else:?>	
 	<div id="prizeEventClose" style="height:100%;width:100%;">
		<img src="<?php echo $attachPath.$defaultImg;?>" alt=""/>
	</div>
 <?php endif;?>
</body>
</html>