<?php echo $this->render("../../Front/views/layout/header.phtml");?>
<section id="page">
	<?php include '_header.php';?>
	<!-- 主体内容 -->
	<section id="content" style="padding-top:0;">
		<section class="order">
			<section class="coin-success">
			<div class="txt">
				<h3>可立即领取<span class="zt-orange">100</span>银币</h3>
				<p>在积分换购区中银币可充当现金使用，1银币=1人民币</p>
				
			</div>
			<div class="button"><a href="###" class="btn orange">马上领取</a></div>
			</section>
		</section>
	</section>
	<!--  /主体内容 -->
	<?php include '_footer.php';?>
</section>
</body>
</html>