<?php echo $this->render("../../Front/views/layout/header.phtml");?>
<section id="page">
	<!-- 主体内容 -->
	<section id="content">
		<section class="account">
			<section class="coin-detail">
				<p class="gold-info">
					<em class="zt-orange">金币在积分换购专区中可以无限制使用。</em><br>
					1金币=1人民币。<br>
					积分获取：<br>
					<span class="fr">敬请期待！</span>
				</p>

			</section>
		</section>
	</section>
	<!--  /主体内容 -->
</section>
</body>
</html>