<?php echo $this->render("../../Front/views/layout/header.phtml");?>
<section id="page">
	<!-- 主体内容 -->
	<section id="content">
		<section class="account">
			<section class="coin-detail">
				<ul class="mod-text-list">
					<li>
						<dl class="mod-dl-list">
							<dd>如何使用银币?</dd>
							<dd>&nbsp;&nbsp;&nbsp;&nbsp;1. 1银币=1人民币</dd>
							<dd>&nbsp;&nbsp;&nbsp;&nbsp;2. 银币在积分换购专区中可以根据商品使用限额抵现使用。</dd>
						</dl>
					</li>
					<li>
						<dl class="mod-dl-list">
							<dd>如何获取银币?</dd>
							<dd>&nbsp;&nbsp;&nbsp;&nbsp;1. 注册为金立购用户赠送100银币，即时可用40银币。剩余60银币将分三个星期陆续赠送，累积送满100银币为止。<br/></dd>
							<dd>&nbsp;&nbsp;&nbsp;&nbsp;2. 在金立购中非积分换购专区购物，可获得一定的积分奖励，在您确认收货后，奖励的积分将进入您的账号中。</dd>
						</dl>
					</li>
				</ul>
			</section>
		</section>
	</section>
	<!--  /主体内容 -->
</section>
</body>
</html>