

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>HotWifi安全认证</title>
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<meta name="format-detection" content="email=no" />

<link rel="stylesheet" href="/static/css/ptner.source.css" />
</head>
<body>

	<div class="module panel2">
		<header class="hd-wifi">
			<nav>
				<ul>
					<li><a href=""><img src="/static/pic/shop-intro.png" alt=""><br/>店铺介绍</a></li>
					<li><a href=""><img src="/static/pic/shop-event.png" alt=""><br/>优惠活动</a></li>
					<li><a href=""><img src="/static/pic/shop-new.png" alt=""><br/>店铺新品</a></li>
					<li><a href=""><img src="/static/pic/shop-eva.png" alt=""><br/>店铺点评</a></li>
					<!-- <li><a href="">身边优惠</a></li> -->
				</ul>
			</nav>
			<div class="search-bar">
				<form action="">
					<input type="text" value="泰国看守政府总理英拉宣布"><button></button>
				</form>
			</div>
			
		</header>

		<section class="main-wifi">
			<div class="sudoku-box">
				<ul>
					<li><a href="http://www.baidu.com"><img src="/static/pic/ico_baidu.jpg"><em>百度</em></a></li>
					<li><a href="http://www.sina.com.cn"><img src="/static/pic/ico_sina.jpg"><em>新浪</em></a></li>
					<li><a href="http://3g.gionee.com"><img src="/static/pic/ico_3g.jpg"><em>3G</em></a></li>
					<li><a href="http://www.sohu.com"><img src="/static/pic/ico_sohu.jpg"><em>搜狐</em></a></li>
					<li><a href="http://m.taobao.com"><img src="/static/pic/ico_taobao.jpg"><em>淘宝</em></a></li>
					<li><a href="http://http://www.qq.com/"><img src="/static/pic/ico_tencent.jpg"><em>腾讯</em></a></li>
					<li><a href="http://www.youku.com"><img src="/static/pic/ico_youku.jpg"><em>优酷</em></a></li>
					<li><a href="http://game.gionee.com"><img src="/static/pic/ico_game.jpg"><em>游戏</em></a></li>
					<li><a href="http://3g.gionee.com"><img src="/static/pic/ico_zhangyue.jpg"><em>掌阅</em></a></li>
				</ul>
			</div>
			<div class="banner"><a href="http://3g.gionee.com"><img src="/static/pic/wifi_pic_fbanner.jpg"></a></div>
			<div class="news-box">
				<div class="title">
					<span class="title-left">生活</span>
					<nav class="tab">
						<span>购物</span>
						<span>美食</span>
						<span>健康</span>
						<span class="selected">情感</span>
					</nav>
				</div>
				<div class="content">
					<div class="head-line">
						<a href="http://3g.gionee.com">
							<h3>美国代购正麦迪逊真皮手提<span class="sub">美国代购正麦迪逊真皮手提</span></h3>
							<p><img src="/static/pic/wifi_pic_headline.jpg"></p>
						</a>
					</div>
					<ul>
						<?php foreach($news as $key=>$value) {?>
						<li><a href="<?php echo $value['newsUrl'];?>">▪ <?php echo $value['title'];?></a></li>
						<?php }?>
					</ul>
				</div>
		</section>
	</div>
</body>
</html>