<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">专题列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加专题</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">关键字</th>
			<td class="td"><input type="text" class="input" name="title" value="<?php echo $search['title'];?>"></td>
		</tr>	
		
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">ID</td>
			<td>名称</td>
			<td>图片</td>
			<td>专题内容</td>
			<td>发布时间</td>
			<td>操作</td>
		</tr>
<?php foreach($subjects as $key => $value) {?>

		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><img src="<?php echo $attachPath,$value['img'];?>" style="width: 150px; heigh:100px;"/></td>
			<td><?php echo $value['title'];?></td>
        	<td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
			<td>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
