<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $gameListUrl;?>">游戏列表</a></li>
    <li><a href="<?php echo $privilegeGiftListUrl;?>">特权礼包</a></li>
        <li><a href="<?php echo $hotUrl;?>" style="width:150px">新手礼包(热门礼包)</a></li>
    <li class="current"><a href="javascript:;">编辑兑奖码</a></li>
	</ul>
</div>
<div class="h_a">
    <a href="<?php echo $giftlogUrl.'?id='.$gift_info['id'];?>">
    <input type="button" value="兑奖码管理"/>
    </a>
</div>
<div class="table_full">
<dl style="display:-webkit-box">
	<dt style="width:64px;height:64px; " >
	<img style="height: 100%;width:auto;" src="<?php echo $game_info['img'];?>" alt="" >
	</dt>
	<dd style="padding-left: 64px">
		<p><span class="name">礼包名称:<?php echo $gift_info['name'];?></span></p>
		<p><span class="id">游戏名称:<?php echo $game_info['name'];?></span></p>
	</dd>
</dl>
</div>
<form method="post" action="<?php echo $editlogPostUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="gift_id" value="<?php echo $gift_info['id'];?>" type="hidden" />
<input name="id" value="<?php echo $log_info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
			<th class="th">兑奖码</th>
			<td class="td"><input type="text" class="input wc" name="activation_code" value="<?php echo $log_info['activation_code'];?>"></td>
		</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Client_Gift/log?id=<?php echo $gift_info['id'];?>');
	});
})
</script>


<?php echo $this->render("layout/footer.phtml");?>
