<?php echo $this->render("layout/header.phtml"); ?>
	<div class="nav">
		<ul class="cc">
			<li><a href="<?php echo $bussinessUrl; ?>">业务列表</a></li>
			<li><a href="javascript:;">添加业务信息</a></li>
			<li><a href="<?php echo $linkListUrl; ?>">业务链接列表</a></li>
			<li class="current"><a href="<?php echo $editLinkUrl; ?>"><?php echo $data['id'] ? '编辑' : '添加'; ?>业务链接</a>
			</li>
		</ul>
	</div>
	<div class="h_a">添加页面</div>
	<form method="post" action="<?php echo $postLinkUrl; ?>" id="addFrom">
		<input name="token" value="<?php echo $token; ?>" type="hidden"/>

		<div class="table_full">
			<table width="100%">
				<tr class="tr">
					<th class="th">合作商名</th>
					<td class="td">
						<select name="pid" id="pid">
							<option value="0">请选择</option>
							<?php foreach ($parters as $k => $v) { ?>
								<option value="<?php echo $v['id']; ?>" <?php if ($data['pid'] == $v['id']) echo 'selected'; ?>><?php echo $v['name']; ?></option>
							<?php } ?>
						</select>
					</td>
				</tr>
				<tr class="tr" style="display:<?php echo empty($data) ? 'none' : '' ?>" id="b_tr">
					<th class="th">业务名称</th>
					<td class="td">
						<select name="bid" id="bid">
							<?php if (!empty($data)) { ?>
								<option value="0">请选择</option>
								<?php foreach ($business as $k => $v) { ?>
									<option value="<?php echo $v['id']; ?>" <?php if ($v['id'] == $data['bid']) echo 'selected'; ?>><?php echo $v['name']; ?></option>
								<?php }
							} ?>

						</select>
					</td>
				</tr>

				<tr class="tr">
					<th class="th">链接</th>
					<td class="td">
						<input type="text" name="url" id="url" class="input" value="<?php echo $data['url']; ?>"></td>
				</tr>
				<tr class="tr">
					<th class="th">链接名称</th>
					<td class="td">
						<input type="text" name="url_name" id="price" class="input" value="<?php echo $data['url_name']; ?>">
					</td>
				</tr>

				<tr class="tr">
					<th class="th">状态</th>
					<td class="td"><select name="status">
							<option value='0'   <?php if ($data['status'] == 0) echo 'selected'; ?>>关闭</option>
							<option value='1' <?php if ($data['status'] == 1) echo 'selected'; ?>>开启</option>
						</select></td>
				</tr>
			</table>
			<input type="hidden" value="<?php echo $data['id']; ?>" name="id">

			<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
			</div>
		</div>

	</form>

	<script type="text/javascript">
		//表单数据提交
		$(document).ready(function () {

			$("#sdate").datepicker({dateFormat: 'yy-mm-dd'});
			$("#edate").datepicker({dateFormat: 'yy-mm-dd'});

			ajaxForm('addFrom', function (ret) {
				ajaxRedirect(ret, baseurl + '/Admin/Parter/linklist');
			});
		})

		$("#pid").bind("change", function () {
			var pid = $("#pid option:selected").val();
			if (pid > 0) {
				$.ajax({
					'url': '/Admin/Parter/ajaxGetBussinessList',
					'type': 'post',
					'dataType': 'json',
					'data': {'token': '<?php echo $token;?>', 'pid': pid},
					'success': function (e) {
						if (e.data) {
							var html = "<option value='0'>请选择</option>";
							$.each(e.data, function (i, m) {
								html += "<option value='" + m.id + "'>" + m.name + "</option>";
							});
							$("#bid").html(html);
							$("#b_tr").show();
						}
					}
				});
			} else {
				$("#b_tr").hide();
			}
		});
	</script>
<?php echo $this->render("layout/footer.phtml"); ?>