<!DOCTYPE HTML>
<html>
<head>
	<title>端午“粽”动员，新品M5手机等你赢</title>
	<meta charset="utf-8">
	<meta name="viewport"
	      content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no"/>
	<meta name="apple-touch-fullscreen" content="yes"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no"/>
	<link rel="stylesheet" href="<?=$staticResPath?>/events/css/duanwu.min.css"/>
	<script>
		var __CONFIG__ = {
			pz_tt: "<?=$data['pz_tt']?>",
			pz_ur: "<?=$data['pz_ur']?>",
			pz_rm: <?=$data['pz_rm']?>, // 剩余次数
			pz_rk: <?=$data['pz_rk']?>, // 是否中奖 1,1,2,3,4,5
			pz_ep: <?=$data['pz_ep']?>
		};
	</script>
</head>
<body>
<div class="app">
	<div class="main">
		<div class="part1">
			<img src="<?=$staticResPath?>/events/img/duanwu_bg01.jpg"/>
			<div class="tips"><h3>今天还有 <strong><?=$data['pz_rm']?></strong> 次机会</h3></div>
			<a id="J_btnRule" href="javascript:;" class="btn-rule">活动规则</a>
			<span class="zz-random"></span>
			<span class="zz-animate"></span>
			<span class="btn btn-start" style="display: none;">开始</span>
			<span class="btn btn-stop" style="display: none">停</span>
			<span class="btn btn-over" style="display: none">结束</span>
		</div>
		<div class="part2">
			<img src="<?=$staticResPath?>/events/img/duanwu_bg02.jpg"/>
			<a class="btn-gnm5" href="<?=Common::clickUrl('1','duanwu_jd','http://item.jd.com/1574334.html')?>"></a>
		</div>
		<div class="part3">
			本活动最终解释权归金立浏览器所有<br>
			如有问题请联系微信公众号：jizhuanxiang
		</div>
	</div>
	<div class="mask" style="display: none;"></div>

	<!-- 中奖信息弹窗-->
	<div id="J_popPrizeBox" class="dialog dialog-prize" style="display:none;">
		<div class="dialog-wrap">
		</div>
	</div>

	<!-- 活动规则弹窗 -->
	<div id="J_popRuleBox" class="dialog dialog-rule" style="display: none;">
		<div class="wrap">
			<h2>活动规则</h2>

			<div class="txt">
				1、同一个用户每天可玩三次；<br>
				2、活动期间（2015.6.19~.6.21）所有<br>
				活动页面奖品可以多次重复中奖；<br>
				3、点击 放弃领奖 后奖品后期不再补发；<br>
				4、如有作弊行为，一经发现，取消当<br>
				日所中全部奖品。
			</div>
			<div class="btn-wrap">
				<span class="btn btn-yellow">我知道了</span>
			</div>
		</div>
	</div>
	<!-- 网络异常 -->
	<div id="J_netErrorTips" class="toast-tips" style="display: none;">网络异常，请稍后再试</div>
	<!-- /网络异常-->
</div>
<script>var token = "1ad23f";</script>
<script src="<?=$staticResPath?>/events/js/zepto.min.js?v=20150620"></script>
<script src="<?=$staticResPath?>/events/js/duanwu.min.js?v=20150620"></script>
</body>
</html>