<?php echo $this->render("layout/singleheader.phtml");?>
<body id="lottery" data-pagerole="body">
	<div class="module">
		<section class="lottery-main">
			<div class="ly-plate">
				<div class="roulette" id="J_lotteryBoard"></div>
				<div class="pointer abled" id="J_lotteryBtn" data-count="<?php echo $user['time']?>" data-score="<?php echo $user['score']?>" data-ajaxurl="<?php echo $webroot;?>/api/lottery/index?>"></div>
				<marquee class="scroll-marquee">
					<?php if (!empty($top10Winners)): foreach ($top10Winners as $val):?>
					<span>恭喜 <?php echo empty($val['phone_num']) ? $val['weixin'] : $val['phone_num'];?> 获得 <?php echo $val['award_name'];?></span>
					<?php endforeach; endif;?>
				</marquee>
			</div>
			<div class="ly-rule">
				<div class="item">
					<h3>活动规则</h3>
					<p>
						1、活动时间：2月16日-2月25日；<br>
						2、每日免费抽奖3次。使用分数可以兑换额外抽奖次数,每次抽奖消耗50分，每日仅限抽奖5次；<br>
						3、中奖后请输入昵称和11位手机号码，以便核对信息发送奖品；<br>
						4、此次活动最终解释权归购物大厅所有。<br>
					</p>
				</div>
				<div class="item">
					<h3>兑奖流程</h3>
					<p>
						1、输入昵称和正确的手机号，提交兑换信息；<br>
						2、购物大厅会通过手机号联系中奖用户，请保持手机畅
						   通；<br>
						3、奖品将于2月26日活动结束后统一发放。<br>
					</p>
				</div>
			</div>
		</section>
	</div>
	<div class="full-mask J_fullMask"></div>
	<div class="dialog-box J_dialogBox"></div>
	<?php echo $this->render("layout/tj.phtml");?>
</body>
</html>
