<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">文件列表</a></li>
    <li class="current"><a href="javascript:;">修改状态</a></li>
	</ul>
</div>
<div class="h_a">修改状态</div>
<form method="post" action="<?php echo $editStatusPostUrl;?>" id="editForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<input name="ostatus" value="<?php echo $info['status'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<tr class="tr">
				<th class="th">状态</th>
				<td class="td"><select name="status">
	<?php foreach($status as $key=>$value) { ?>
						<option value="<?php echo $key;?>" <?php if($info['status'] == $key) echo 'selected="selected"';?>><?php echo $value;?></option>
	<?php }?>
					</select></td>
			</tr>
		<tr class="tr">
			<th class="th">备注</th>
			<td class="td">
				<textarea name="message" style="width: 800px; height: 100px;"></textarea>
			</td>
		</tr>		
		
	</table>
</div>
<div class="mb10 tac"><span  class="btn"><span><button type="button" onclick="javascript:history.back(-1)">返回</button></span></span><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>

<div class="h_a">日志</div>
<div class="table_list">
	<table width="100%">
		<?php foreach($logs as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['message'];?></td>
			<td width="140"><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
		</tr>
<?php } ?>
	</table>
</div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('editForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/File/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
