<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">文件列表</a></li>
    <?php if($groupid == 1) {?><li class="current"><a href="javascript:;">上传文件</a></li><?php }?>
	</ul>
</div>
<div class="h_a">编辑文件</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="editForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
<div class="table_full">
	<table width="100%">
	<tr class="tr">
			<th class="th">文件上传</th>
			<td class="td">
				<ul class="uploadFile">
					<li id="File">
					<input type="hidden" name="file" value="<?php echo $info['file'];?>">
					缩略图：<img src="<?php echo $attachPath.$info['icon'];?>" />&nbsp;
					<input type="hidden" name="icon" value="<?php echo $info['icon'];?>">
					预览图gif：<img src="<?php echo $attachPath.$info['img_gif'];?>" />&nbsp;
					<input type="hidden" name="img_gif" value="<?php echo $info['img_gif'];?>">
					预览图png：<img src="<?php echo $attachPath.$info['img_png'];?>" />&nbsp;
					<input type="hidden" name="img_png" value="<?php echo $info['img_gif'];?>">
					<input type="hidden" name="file_size" value="<?php echo $info['file_size'];?>">
					</li>
				</ul>
				<p style="clear: both;">
					<iframe name="upload"
						src="<?php echo $uploadUrl;?>"
						style="height: 50px; width: 100%;" frameborder="0" scrolling="no"></iframe>
				</p>
			</td>
		</tr>
		<tr class="tr">
			<th class="th">标题</th>
			<td class="td"><input type="text" class="input" name="title" value="<?php echo $info['title'];?>"></td>
		</tr>
		<tr class="tr">
			<th class="th">分类</th>
			<td class="td">
			<?php foreach ($file_type as $key=>$value) { ?>
						<input type="checkbox" name="file_type[]" value="<?php echo $value['id'];?>" <?php if($file_types[$value['id']]) echo 'checked="ckecked"';?> ><?php echo $value['name'];?>
			<?php }?>
			</td>
		</tr>		
		<tr class="tr">
			<th class="th">简要描述</th>
			<td class="td"><input type="text" class="input wc" name="summary" value="<?php echo $info['summary'];?>">(最多11个字)</td>
		</tr>			
		<tr class="tr">
			<th class="th">详细描述</th>
			<td class="td">
				<textarea name="descript" style="width: 800px; height: 100px;"><?php echo $info['descript'];?></textarea>(最多200字)
			</td>
		</tr>
		<tr class="tr">
			<th class="th">设计师</th>
			<td class="td"><input type="text" class="input" name="designer" value="<?php echo $info['designer'];?>">(设计师姓名)</td>
		</tr>
		<tr class="tr">
			<th class="th">单价</th>
			<td class="td"><input type="text" class="input" name="price" value="<?php echo $info['price'];?>">(不填写表示免费)</td>
		</tr>
		<tr class="tr">
			<th class="th">分辨率</th>
			<td class="td">
			<?php foreach ($size as $key=>$value) { ?>
						<input type="checkbox" name="size_id[]" value="<?php echo $value['id'];?>" <?php if($file_size[$value['id']]) echo 'checked="ckecked"';?> ><?php echo $value['size'];?>
			<?php }?>
			</td>
		</tr>		
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('editForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/File/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
