<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">文件列表</a></li>
		<?php if($groupid == 1) {?><li><a href="<?php echo $addUrl;?>">上传文件</a></li><?php }?>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post" id="searchForm">
	<input name="token" type="hidden" value="<?php echo $token;?>" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">标题</th>
				<td class="td">
				<input type="text" class="input" name="title" value="<?php echo $search['title'];?>">
				</td>
			</tr>
			<tr class="tr">
				<th class="th">分类</th>
				<td class="td">
				<select name="file_type">
				<option value="">所有分类</option>
<?php foreach($file_type as $key => $value) {?>
                <option <?php echo ($search['file_type'] == $value['id']) ? 'selected="selected"' : '';?> value="<?php echo $value['id'];?>"><?php echo $value['name'];?></option>
<?php }?>
	            </select>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">分辨率 </th>
				<td class="td">
				<select name="size_id">
					<option value="">所有分辨率</option>
	<?php foreach($file_size as $key => $value) {?>
	                <option <?php echo ($search['size_id'] == $value['id']) ? 'selected="selected"' : '';?> value="<?php echo $value['id'];?>"><?php echo $value['size'];?></option>
	<?php }?>
		            </select>
	            </td>
			</tr>
			<tr class="tr">
				<th class="th">状态 </th>
				<td class="td">
				<select name="status">
					<option value="">所有状态</option>
	<?php foreach($status as $key => $value) {?>
	                <option <?php echo ($search['status'] == $key) ? 'selected="selected"' : '';?> value="<?php echo $key;?>"><?php echo $value;?></option>
	<?php }?>
		        </select>
	            </td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button type="submit">搜 索</button></span></span>
	</div>

<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td  width="80">id号</td>
			<td  width="100">标题</td>
			<td>缩略图</td>
			<td  width="80">大小</td>
			<td  width="200">包名</td>
			<td  width="100">添加时间</td>
			<td  width="100">修改时间</td>
			<td  width="80">点击</td>
			<td  width="80">下载</td>
			<td width="80">状态</td>
			<td width="200">
			<span style="float:right">
					<select name="order_by" onchange="submitForm(this.value)">
					<option value="">排序方式</option>
	                <option <?php echo ($order_by == 'create_time') ? 'selected="selected"' : '';?> value="create_time">上传时间</option>
	                <option <?php echo ($order_by == 'update_time') ? 'selected="selected"' : '';?> value="update_time">修改时间</option>
	                <option <?php echo ($order_by == 'hit') ? 'selected="selected"' : '';?> value="hit">点击量</option>
	                <option <?php echo ($order_by == 'down') ? 'selected="selected"' : '';?> value="down">下载量</option>
		        </select></span>操作</td>
		</tr>
<?php foreach($files as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['title'];?></td>
			<td><img src="<?php echo $attachPath.$value['icon'];?>" width="40" height="40"/></td>
			<td><?php echo Util_File::size($value['file_size']);?></td>
			<td><?php echo basename($value['file']);?></td>
            <td><?php echo date('Y-m-d', $value['create_time']);?></td>
            <td><?php echo $value['update_time'] ? date('Y-m-d', $value['update_time'])  : '' ;?></td>
            <td><?php echo $value['hit'];?></td>
            <td><?php echo $value['down'];?></td>
            <td><?php echo $status[$value['status']];?></td>
			<td>
				<?php if($groupid == 1 && $value['status'] != 4) { ?><a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a><?php }?>
				<?php if($groupid != 1) {
						if(($groupid == 3 && $value['status'] > 2) || ($groupid == 2 && $value['status'] < 4)) {
				?>
				<a href="<?php echo $editStatusUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">修改状态</a>
				<?php }} ?>
				<?php if($value['status'] != 4 && in_array($groupid, array(1,3))) { ?><a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a><?php } ?>&nbsp;
				<a href="<?php echo $detailUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">预览</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
</form>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script type="text/javascript">
$(document).ready(function(){
	submitForm = function() {
		$("#searchForm").submit();
	};
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
