<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>">店铺列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加店铺</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="get">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<div class="table_full">
	<table width="100%">
        <tr class="tr">
            <th class="th">昵称</th>
            <td class="td">
                <input type="text" class="input" name="nick" value="<?php echo $search['nick']; ?>">
            </td>
            <th class="th">店铺</th>
            <td class="td">
                <input type="text" class="input" name="shop_title" value="<?php echo $search['shop_title']; ?>">
            </td>
            <th class="th">标签</th>
            <td class="td">
                <select name="tag_id" >
                    <option value="">不限</option>
                    <?php foreach($tags as $tag) {?>
                    <option value="<?php echo $tag['id']; ?>" <?php if($tag['id']==$search['tag_id'])echo 'selected="selected"' ?>><?php echo $tag['name']; ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">排序</td>
			<td width="30">ID</td>
			<td>店铺名称</td>
			<td>店铺类型</td>
			<td>商品图片</td>
			<td>logo</td>
			<td>状态</td>
			<td width="165">操作</td>
		</tr>
<?php foreach($shops as $key => $value) {?>
		<tr class="ct">
			<td><?php echo $value['sort'];?></td>
			<td><?php echo $value['id'];?></td>
			<td><?php echo $value['shop_title'];?></td>
			<td><?php echo $shop_type[$value['shop_type']];?></td>
			<td><?php if(!empty($pic[$value['shop_id']])){
                foreach ($pic[$value['shop_id']] as $img):?>
                    <img src="<?php echo $img ?>" alt="" height="50" width="50"/>
                    <?php endforeach;} ?>
            </td>
			<td><img src="<?php if(strpos($value['logo'], 'http://') === false) {echo $attachPath,$value['logo'];}else{echo $value['logo'];};?>" width=50></td>
			<td><?php echo $value['status'] == 1 ? '开启' : '关闭';?></td>
			<td>
			<a href="<?php echo $value['shop_url'];?>" target="_blank" class="mr10">查看店铺</a>
			<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>" class="mr10">编辑</a>
			<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
			</td>
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
