
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<!-- UC应用模式 -->
<meta name="browsermode" content="application">
<!-- QQ应用模式 -->
<meta name="x5-page-mode" content="app">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />
<title>畅聊免费打电话</title>
<link rel="stylesheet" type="text/css" href="<?php echo $staticResPath;?>/call/css/call.min.css?v=<?php echo $version;?>" />
<script type="text/javascript">
	var token = "<?=$token?>";
</script>
</head>
<body class="ui-app" style="background:#fafafa;">
<div class="ui-top-bar">
	<span class="ui-top-txt">请绑定手机号码</span>
</div>

<div class="ui-page page1 js-active">
	<div class="ui-page-content">
		<div class="call-panel-box">
			<div class="call-tips">
				温馨提示：非手机号登陆的用户，必须绑定手机，才可以继续使用服务。
			</div>
		</div>
		<div class="call-form-box call-step-box">
			<input id="ref" type="hidden" name="f" value="<?php echo $f;?>" />
			<input id="redirect" type="hidden" name='redirect'  value="<?php echo $redirect;?>"/>
			<ul>
				<li>
					<label>手机号码</label>
					<span class="inp-wrap ui-border">
						<input id="inp-mobile" class="inp-txt" type="tel" name="mobile" maxLength="11" autoFocus="true" placeholder="请填写11位手机号" value="" />
					</span>
				</li>
				<li class="step1">
					<label>验证码</label>
					<span id="js_checkcode" class="inp-wrap inp-btn-wrap inp-w100 ui-border">
						<input id="inp-smscode" class="inp-txt inp-btn" type="button" value="获取验证码" />
					</span>
				</li>
				<li class="none step2">
					<label>验证码</label>
					<span class="inp-wrap inp-w80 ui-border">
						<input class="inp-txt" type="text" name="smscode" maxLength="4" value="" />
					</span>
					<span id="js_countdown" class="countdown"><em>0</em>s</span>
					<span id="js_recheckcode" class="getcode none">重新获取</span>
				</li>
				<li class="none step3">
					<label></label>
					<span id="js_btnsmt" class="inp-wrap inp-btn-wrap inp-w80 ui-border">
						<input class="inp-txt inp-btn" type="button" value="确认" />
					</span>
				</li>
			</ul>
		</div>
	</div>
</div>
<div class="toast-wrap"><p></p></div>
<script src="<?php echo $staticResPath;?>/call/js/lib/zepto.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticResPath;?>/call/js/binding.min.js?v=<?php echo $version;?>"></script>
</body>
</html>