<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    	<li><a href="<?php echo $indexUrl . '?version_type=' . $info['version_type'];?>">分类列表</a></li>
		<li class="current"><a href="<?php echo $editUrl . '?version_type=' . $info['version_type'];?>">修改分类</a></li>
	</ul>
</div>
<div class="h_a">修改分类</div>
<form method="post" action="<?php echo $editPostUrl;?>" id="addForm">
	<input name="token" value="<?php echo $token;?>" type="hidden" />
	<input name="id" value="<?php echo $info['id'];?>" type="hidden" />
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">名称</th>
				<td class="td"><input type="text" class="input wc" name="title" value="<?php echo $info['title']?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">排序</th>
				<td class="td"><input type="text" class="input wb" name="sort" value="<?php echo $info['sort']?>"></td>
			</tr>
			<tr class="t">
				<th class="th">版本</th>
				<td class="td">
					<select name="version_type">
						<?php foreach ($info_version_array as $key => $val): ?>
							<option
								value="<?php echo $key; ?>" <?php if ($key == $info['version_type']) echo 'selected="selected"' ?>><?php echo $val; ?></option>
						<?php endforeach; ?>
					</select>
				</td>
			</tr>
			<tr class="tr">
				<th class="th">状态</th>
				<td class="td">
					<select class="wa" name="status">
						<option value="1" <?php if($info['status'] == 1){echo 'selected="selected"';}?>>开启</option>
						<option value="0" <?php if($info['status'] == 0){echo 'selected="selected"';}?>>关闭</option>
					</select>
				</td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span></div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $indexUrl . '?version_type=' . $info['version_type'];?>');
	});
});
</script>
<?php echo $this->render("layout/footer.phtml");?>
