<!DOCTYPE HTML>
<html>
<head>
<title>装机必备</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />

<link rel="stylesheet" href="<?php echo $staticSysPath;?>/reset/phonecore.css?v=<?php echo $version;?>" />
<link id="linkMain" rel="stylesheet" type="text/css" href="<?php echo $staticResPath;?>/assets/css/main.source.css?v=<?php echo $version;?>">
<script src="<?php echo $staticSysPath;?>/lib/zepto/zepto.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticSysPath;?>/icat/1.1.6/icat.js?v=<?php echo $version;?>" data-main="<?php echo $staticResPath;?>/assets/js/main.source.js?v=<?php echo $version;?>"></script>
<script>var token="<?php echo $token;?>"</script>
</head>
<body>