<?php echo $this->render("common/navigator.phtml"); ?>
<section class="ajax_wrap">
<div class="nav">
	<ul class="cc">
    <li><a href="<?php echo $listUrl;?>">用户列表</a></li>
    <li class="current"><a href="javascript:;">编辑用户</a></li>
	</ul>
</div>
<div class="clear-fix"></div>
<div class="h_a"></div>
<form method="post" action="<?php echo $editPostUrl;?>" id="editUserFrom">
    <input name="uid" value="<?php echo $userInfo['uid'];?>" type="hidden"/>
    <input name="token" value="<?php echo $token;?>" type="hidden" />
<div class="table_full">
	<table width="100%">
		<thead>
			<tr>
				<td colspan="2" style="text-align:center">编辑用户</td>
			</tr>
		</thead>
		<tbody>
		<tr class="tr">
			<td class="th">用户名</th>
			<td class="td"><input type="text" class="input rd_1 w300" name="username" maxlength="30" value="<?php echo $userInfo['username'];?>" disabled="disabled"></td>
		</tr>
		<tr class="tr">
			<td class="th">用户Email</th>
			<td class="td"><input type="text" maxlength="30" name="email" class="input input_wa rd_1 w300" disabled="disabled" value="<?php echo $userInfo['email'];?>"></td>
		</tr>
		<tr class="tr">
			<td class="th">用户密码</th>
			<td class="td"><input type="password" maxlength="20" name="password" class="input rd_1 w300"></td>
		</tr>
		<tr class="tr">
			<td class="th">重复密码</th>
			<td class="td"><input type="password" maxlength="20" name="r_password" class="input rd_1 w300"></td>
		</tr>
		<tr class="tr">
			<td class="th">用户组</th>
			<td class="td">
				<div class="select_box">
					    <div class="tb_cont tb_cell">
	                        <label class="select_val">运营</label>
	                        	<ul class="select_option">
			                        <li>设计师</li>
			                        <li>测试</li>
	                            </ul>
	                    </div>
                </div>
<!--<?php if ($userInfo['groupid'] == 0) { echo '超级管理员';} else {	?> 
			<select name="groupid">
			<?php foreach($groups as $key => $value) {?>
			                <option <?php echo $userInfo['groupid'] == $value['groupid'] ? 'selected="selected"' : '';?> value="<?php echo $value['groupid'];?>"><?php echo $value['name'];?></option>
			<?php }?>
            </select>
<?php }?>-->            
            </td>
		</tr>
		<tr class="tr">
			<td class="th">状态</th>
			<td class="td">
				<div class="select_box">
					    <div class="tb_cont tb_cell">
	                        <label class="select_val">启用</label>
	                        	<ul class="select_option">
			                        <li>禁用</li>
			                        <li>启用</li>
	                            </ul>
	                    </div>
                </div>
			<!--<select name="status" min-width="100px">
                	<option <?php if($userInfo['status'] == 1) echo 'selected="selected"';?> value="1">启用</option>
                	<option <?php if($userInfo['status'] == 0) echo 'selected="selected"';?> value="0">禁用</option>
            </select>-->
            </td>
		</tr>
		</tbody>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button class="btn_s2" onfocus="blur();" type="submit">保存</button></span></span></div>
</form>
</section>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
	ajaxForm('editUserFrom',function(ret){
		if (ret) {
    		if (ret.success) {
    			showMsg('', ret.msg);
    			setTimeout(function() {
    						logout(baseurl+'/Admin/Index/index');
    					}, 500);
    		} else {
    			showError('', ret.msg);
    		}
    	}
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
