<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
     <li><a href="<?php echo $listUrl;?>">客户端</a></li>
      <li ><a href="<?php echo $gameFeedbackUrl;?>">游戏反馈</a></li>
	 <li><a href="<?php echo $rlistUrl;?>">H5反馈</a></li>
	 <li class="current"><a href="<?php echo $addUrl;?>">标签管理</a></li>
	</ul>
</div>
<div class="h_a">标签管理</div>
<form method="post" action="<?php echo $addPostUrl;?>" id="addForm">
<input name="token" value="<?php echo $token;?>" type="hidden" />
	
	<div class="table_full">
		<table width="100%">
			<tr class="tr">
				<th class="th">设置标签</th>
				<td class="td">
					 <textarea name="game_free_label" class="textarea wc" style="height:200px; width:800px"><?php echo $labels;?></textarea>
					 <br/>
					 <br/>
					 <span style="color:red">请以"|"区隔每个标签</span>
				</td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>
	</div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Freedl_Feedback/add');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>