<div class="aside">
	  <ul class="side-bar">
		  <li><a href="/ptner/user/manage"><span class="icon-member"></span>商家空间<span class="icon-arrow"></span></a></li>
		  <!--<li><a href="/ptner/user/ad"><span class="icon-ads"></span>认证页<span class="icon-arrow"></span></a></li>-->
		  <!-- <li><a href="/ptner/user/router"><span class="icon-router"></span>路由器<span class="icon-arrow"></span></a></li>-->
		  <li><a href="/ptner/user/tj"><span class="icon-sta"></span>统计<span class="icon-arrow"></span></a></li>
		  <li><a href="/ptner/user/setting"><span class="icon-setting"></span>设置<span class="icon-arrow"></span></a></li>
          <li><div style="text-align:center"><img src="http://chart.apis.google.com/chart?chs=150x150&cht=qr&chld=L|0&chl=<?php echo $webroot,$authUrl,"?ht=",$device['ht'];?>" alt="QR code"/></div>
              <div style="text-align:center">手机扫描预览首页</div>
          </li>
	 </ul>
</div>