<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
		<li class="current"><a href="<?php echo $listUrl;?>">背景图列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加背景图</a></li>
	</ul>
</div>
<form action="<?php echo $listUrl;?>" method="post">
	<input name="token" type="hidden" value="<?php echo $token;?>" /> <input
		name="ad_type" type="hidden" value="<?php echo $ad_type;?>" />
	<div class="table_full">
		<table width="100%">
			<tr>
				<th class="th">状态</th>
				<td class="td"><select name="status" class="wa">
						<option value="0">全部</option>
						<option <?php if($inputVars['status'] == 2) echo 'selected';?>
							value="2">开启</option>
						<option <?php if($inputVars['status'] == 1) echo 'selected';?>
							value="1">关闭</option>
				</select></td>
				<th class="th">标题</th>
				<td class="td"><input type="text" class="input" name="title"
					value="<?php echo empty($inputVars['title'])?'':$inputVars['title'];?>"></td>
			</tr>
			<tr class="tr">
				<th class="th">背景图有效时间</th>
				<td class="td"><div>
						<input class="input" type="text" maxlength="30"
							style="width: 143px;" id="start_time" name="start_time"
							value="<?php echo $inputVars['start_time'];?>" /> 至 <input
							class="input" type="text" maxlength="30" style="width: 143px;"
							id="end_time" name="end_time"
							value="<?php echo $inputVars['end_time'];?>" />
					</div></td>
			</tr>
		</table>
	</div>
	<div class="mb10 tac">
		<span class="btn"><span><button type="submit">搜 索</button></span></span>
	</div>
</form>
<form id="batchForm" action="<?php echo $batchUpdateUrl;?>"
	method="post">
	<input name="token" type="hidden" value="<?php echo $token;?>" /> <input
		name="action" id="action" type="hidden" value="" />
	<div class="h_a">
		 <span>共<?php echo $total;?>条结果</span>
	</div>
	<div class="table_list">
		<table width="100%">
			<tr class="hd">
			     <td width="80">id</td>
				<td width="120">标题</td>
				<td>类型</td>
				<td>图片</td>
				<td width="120">开始时间</td>
				<td width="120">结束时间</td>
				<td width="60">状态</td>
				<td width="100">操作</td>
			</tr>
<?php foreach($data as $key => $value) {?>
		<tr class="ct">
		          <td><?php echo $value['id'];?></td>
				<td><?php echo $value['title'];?></td>
				<?php 
				    $ad_ptype = $value['ad_ptype'];
				    list($dayImgUrl, $nightImgUrl) = Account_BgimgController::parseImgUrl($ad_ptype, $value['img']);
				?>
				<td><?php echo $ad_ptype ? $ad_ptypes[$ad_ptype] :'';?></td>
				<td><img src="<?php echo $attachPath.$dayImgUrl;?>"
					style="width: 70px; height: 70px;" />
					<?php if(1 == $ad_ptype) {?>
    					<img src="<?php echo $attachPath.$nightImgUrl;?>"
    					style="width: 70px; height: 70px;" />
					<?php }?>
					</td>
				<td><?php echo date('Y-m-d H:i:s', $value['start_time']);?></td>
				<td><?php echo date('Y-m-d H:i:s', $value['end_time']);?></td>
				<td><?php echo $value['status'] == 1 ? '开启' : '关闭';?></td>
				<td><a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>"
					class="mr10">编辑</a> <a href="javascript:"
					onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $value['id'];?>', '', event);">删除</a>
				</td>
			</tr>
<?php } ?>
	</table>
	</div>
</form>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script
	src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Admin/Account_Bgimg/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
