<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
      <li class="current"><a href="<?php echo $indexUrl;?>">游戏分类列表</a></li>
      <li><a href="<?php echo $addUrl;?>">添加游戏主分类</a></li>
	</ul>
</div>
<form id="batchForm" action="<?php echo $batchUpdateCategoryUrl;?>" method="post">
	<input name="token" type="hidden" value="<?php echo $token;?>"/>
<div class="h_a">
	<span class="btn2"><span><button type="submit">批量排序</button></span></span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td width="20"><input type="checkbox" onclick="checkAll('.checkbox')"></td>
		    <td width="20">ID</td>
			<td width="50">排序</td>
			<td width="100">名称</td>
			<td width="100">子分类</td>
			<td width="20">状态</td>
			<td width="100">操作</td>
		</tr>
	<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><input class="checkbox" name="ids[]" value="<?php echo $value['id'];?>" type="checkbox"></td>
			<td><?php echo $value['id'];?></td>
			<td><input type="text" class="input" style="width:30px" name="sort[<?php echo $value['id'];?>]" value="<?php echo $value['sort'];?>"></td>
			
			<td><?php echo $value['title'];?></td>
			<td>
			<?php 
				if($value['subCategory']){
					$subTitle=array();
					foreach ($value['subCategory']  as $items){
						$subTitle[]=$items['title'];
					}
					echo implode(',', $subTitle);
				}
			?>
			</td>
			<td><?php echo $value['status'] ? '开启' : '关闭';?></td>
			<td>
				<a href="<?php echo $editUrl;?>/?id=<?php echo $value['id'];?>">编辑</a>
				&nbsp;&nbsp;&nbsp;&nbsp;
				<?php if($value['editable'] != 1) {?>
				<a href="<?php echo $subListUrl;?>/?id=<?php echo $value['id'];?>">管理子分类</a>
				&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="<?php echo $gameListUrl;?>/?id=<?php echo $value['id'];?>">游戏排序</a>
				<?php }?>
			</td>
		</tr>
	<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
</form>
<script>
$(document).ready(function(){
	ajaxForm('batchForm', function(data) {
		ajaxRedirect(data, baseurl+'/Admin/Resource_Category/index');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
