<?php echo $this->render("layout/header.phtml");?>
<script>
var token = '<?php echo $token;?>';
</script>
<body>
<div id="list-page">
	<section class="wrap">
		<div class="item-list J_gameItem">
			<ul>
				<?php foreach($pageData as $key=>$value) {?>
				<?php
                    $intersrc = 'CATEGORY'.$id.'_GID'.$value['gameid'];
				    $href = $webroot.'/client/index/detail/?id='.$value['gameid'].'&pc=1&intersrc='.$intersrc.'&t_bi='.$source;
				    $evaluateStr = '';
				    if ($value['evaluation']){
					 	$evaluateStr = ',评测,' . $webroot.'/client/evaluation/detail/?id='.$value['evaluation'].'&pc=3&intersrc='.$intersrc.'&t_bi='.$source;
					}
					if (($checkver >= 2)) {
						$data_info = '游戏详情,'.$href.','.$value['gameid'] . $evaluateStr;
					} else {
                        $profile =  $value['gameid'] . ',' . $value['link'] . ',' . $value['package'] . ',' . $value['size'] . ',' . 'Android1.6,240*320-1080*1920';
						$data_info = $value['name'] . ',' . $href . ',' . $profile;
					}
				  ?>
				<li>
					<a <?php if ($checkver >= 2) {?> data-type = '1' <?php }?> data-infpage="<?php echo $data_info;?>">
						<span class="icon"><img src="<?php echo $staticResPath; ?>/pic/blank.gif" alt="" data-src="<?php echo $value['img'];?>"></span>
						<span class="desc">
							<em><?php echo $value['name'];?></em>
							<p>
							<em>大小：<?php echo $value['size'] . 'M';?></em>
							<em class="tips">
							<?php if ($checkver >= 2) {?> 
								<?php if ($value['evaluation']) {?><span class="comment">评</span> <?php }?>
								<?php if ($value['gift']) {?> <span class="gift">礼</span> <?php } ?>
							<?php }?>
							 </em>
							</p>
							<b><?php echo $value['resume'];?></b>
						</span>
					</a>
				</li>
				<?php }?>
			</ul>
		</div>
	</section>
   <?php if($hasnext){ ?>
		<div class="loading J_loadMore" style="display:none;" data-ajaxUrl="<?php echo $webroot.'/client/category/moreCt/?id='.$id.'&intersrc='.$intersrc.'&t_bi='.$source.'&sp='.$sp;?>" data-hasnext="<?php echo $hasnext;?>" data-curpage="<?php echo $page;?>">
			<span class="load"></span>
		</div>
  <?php } ?>
</div>
	<?php echo $this->render("layout/footer.phtml");?>
</body>
</html>