<?php echo $this->render("layout/header.phtml"); ?>
<div class="h_a">配置管理</div>
<form method="post" action="<?php echo $this->baseUrl; ?>" id="editForm">
	<input name="token" value="<?php echo $token; ?>" type="hidden"/>

	<div class="table_full">

		<table width="100%">

			<?php foreach ($types as $k => $v): ?>
				<tr class="tr">
					<th class="th"><?=$v?></th>
					<td class="td">
						<textarea style="width:300px;" name="feedback_tip[<?=$k?>]"><?=$feedback_tip[$k]?></textarea>
					</td>
				</tr>
			<?php endforeach; ?>


		</table>
	</div>
	<div class="mb10 tac"><span class="btn"><span><button onfocus="blur();" type="submit">提交</button></span></span>

</form>
<script src="<?php echo $staticPath; ?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
	$(document).ready(function () {
		ajaxForm('editForm', function (ret) {
			ajaxRedirect(ret, <?php echo $this->baseUrl; ?>);
		});
	})
</script>
<?php echo $this->render("layout/footer.phtml"); ?>

