<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
        <li><a href="<?php echo $listUrl;?>">专题列表</a></li>
        <li class="current"><a href="javascript:;">添加游戏</a></li>
	</ul>
</div>
<form id="batchForm" action="<?php echo $customGamesSortPostUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="id" value="<?php echo $id;?>" type="hidden" />
<input name="item_id" value="<?php echo $item_id;?>" type="hidden" />

<div class="h_a">
	<span>共<?php echo count($list);?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="30">排序</td>
			<td width="30">ID</td>
			<td width="50">图标</td>
			<td width="50">标题</td>
			<td width="30">分类</td>
			<td width="30">大小</td>
		</tr>
		<?php foreach($list as $key => $value) {?>
		  <tr class="ct">
			<td><input type="text" class="input" style="width:30px" name="sort[<?php echo $value['game_id'];?>]" value="<?php echo $value['sort'];?>"></td>
			<td><?php echo $value['game_id'];?></td>
			<td><img src="<?php echo $value['gameIcon']?>" style="width:70px;height:70px;"/></td>
			<td><?php echo $value['gameName'];?></td>
			<td><?php echo $value['gameCategory'];?></td>
			<td><?php echo $value['gameSize'];?>M</td>
		</tr>
	 <?php } ?>
	</table>
</div>
<div class="mb10 tac">
    <span class="btn"><span><a href="<?php echo $costomGamesAddUrl.'?id='.$id.'&item_id='.$item_id.'&view_tpl='.$view_tpl;?>"><button type="button">返回</button></a></span></span>
    <span class="btn"><span><button onfocus="blur();" type="submit">保存</button></span></span>
</div>
</form>
<script type="text/javascript">
$(document).ready(function(){
	ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $gamesAddUrl . "?id=" . $id;?>');
	});
})
</script>
<?php echo $this->render("layout/footer.phtml");?>
