<?php echo $this->render("../../Front/views/layout/header.phtml");?>
<body class="bg-coin-success">
<section id="page">
	<!-- 主体内容 -->
	<section id="content" style="padding-top:0;">
		<section class="order">
			<section class="coin-success">
			<div class="txt">
				<h3>可领取<span class="zt-orange">100</span>银币</h3>
				<p>在积分换购区中银币可充当现金使用，<span class="zt-orange">1银币=1人民币</span></p>
				<p>注册为金立购用户赠送100银币，即时可用40银币。</p>
				<div class="button"><a href="###" data-ajaxUrl="<?php echo $webroot,'/user/index/gain_post';?>" id="J_getCoinLink" class="btn orange">马上领取</a></div>
			</div>
			</section>
		</section>
	</section>
	<!--  /主体内容 -->
</section>
</body>
</html>