<?php echo $this->render("common/navigator.phtml"); ?>

<!-- 导航栏Ajax加载 指向navagator.html  menuOn表示分别需要高亮的菜单栏id 用下划线_隔开 eg:bz_taotu_taotuPack-->
<section class="navigator" menuOn="bz_taotu_taotuList">

</section>

<!-- 内容包裹层 根据不同页面替换里面内容-->
<section class="ajax_wrap">
    <!-- 页面唯一id标识符  一般情况下id=文件名  eg:bz_admin_taotu02-->
    <div id="bz_admin_taotu_list01">
        <!-- 页面内容区域 注意：每个页面无论是否有内容 必定有一个content-->
        <div class="content">
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">套图标签</label>
                    <div class="tb_cont tb_cell">
                        <ul class="tag_list tag_one"><!-- tag_one 一级标签 只能选中一个 -->
                            <li>风景</li>
                            <li>情感</li>
                            <li>简约</li>
                            <li>美女</li>
                            <li>动漫</li>
                            <li>帅哥</li>
                            <li>款式</li>
                        </ul>

                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->
            <div class="com_tb_wrap">
                <div class="com_tb">
                    <label class="tb_cell">状态</label>
                    <div class="tb_cont tb_cell">
                        <div class="select_box">
                            <label class="select_val">全部</label>
                            <ul class="select_option">
                                <li>美女</li>
                                <li>帅哥</li>
                            </ul>
                        </div><!-- select_box -->
                        <div class="select_box">
                            <label class="select_val">上传时间</label>
                            <ul class="select_option">
                                <li>美女</li>
                                <li>帅哥</li>
                            </ul>
                        </div><!-- select_box -->
                    </div>
                    <div class="tb_cell">
                        <ul class="tb_switch">
                            <li class="txt_switch">批量管理</li>
                            <li class="btn_switch switch_pics" openId="viewPics">宫格</li><!-- openId 表示点击时 显示哪个id下的内容 -->
                            <li class="btn_switch switch_list on" openId="viewList">列表</li>
                        </ul>
                    </div>
                </div><!-- com_tb end -->
            </div><!-- com_tb_wrap end -->

            <!-- 列表模式 -->
            <section class="view view_list show" id="viewList">
                <!-- 批量管理内容 默认隐藏 -->
                <div class="view_admin view_list_admin">
                    <!-- checkClass表示 点击后 哪些class要被选中 -->
                    <button class="btn_check btn_check_all" checkClass="btn_check_list"></button><label>全选</label><span class="btn btn_s1 pack_approve">批量通过</span><span class="btn btn_s1 pack_del">批量删除</span>
                </div>
                <table class="view_list_tb">
                    <thead>
                        <tr><th>壁纸</th><th>名称</th><th>颜色</th><th>数量</th><th>套图标签</th><th>上线次数</th><th>打包时间</th><th>操作</th><th>状态</th></tr>
                    </thead>
                    <tbody>
                        <tr><td class="tb_img"><button class="btn_check btn_check_list"></button><img src="image/test_img01.png"></td><td>趣味生活</td><td><span class="color_pan"></span><span class="color_val">#f07804</span></td><td>10</td><td>风景</td><td>5</td><td>2014-09-17</td><td><a class="btn_txt" href="bz_admin_taotu_list02.html">编辑</a> <a class="btn_txt pop_btn" openPopId="fixTipView">删除</a></td><td>已上线</td></tr>
                        <tr><td class="tb_img"><button class="btn_check btn_check_list"></button><img src="image/test_img02.png"></td><td>趣味生活</td><td><span class="color_pan"></span><span class="color_val">#4b5ff8</span></td><td>41</td><td>风景</td><td>5</td><td>2014-09-17</td><td><a class="btn_txt" href="bz_admin_taotu_list02.html">编辑</a> <a class="btn_txt pop_btn" openPopId="fixTipView">删除</a></td><td>已上线</td></tr>
                    </tbody>
                </table>
            </section>

            <!-- 宫格模式 admin_mode显示各子项目的管理按钮-->
            <section class="view view_pics " id="viewPics">
                <!-- 批量管理内容 默认隐藏 -->
                <div class="view_admin view_pics_admin">
                    <!-- checkClass表示 点击后 哪些class要被选中 -->
                    <button class="btn_check btn_check_all" checkClass="btn_check_pics"></button><label>全选</label><span class="btn btn_s1 pack_del">批量删除</span>
                </div>
                <h1 class="block_name">全部壁纸</h1>
                <ul class="view_pics_wrap "><!--  -->
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>

                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>
                    <li class="view_pics_list">
                        <div class="pic_cont">
                            <img src="image/test_img02.png">
                            <button class="btn_check btn_check_pics"></button>
                            <div class="view_pics_btns"><button>修改</button><button>删除</button></div>
                        </div>
                        <p class="pic_name">趣味生活</p>
                    </li>


                </ul>
                <div class="clear-fix"></div>
            </section>

            <!-- 分页模块 -->
            <div class="com_tb_page">
                <a href=""><span class="pageBtn"><</span></a>
                <p class="pageList">
                    <a href=""><span class="pageBtn">1</span></a>
                    <a href="" class="on"><span class="pageBtn">2</span></a><!-- 选中状态加class=on -->
                    <a href=""><span class="pageBtn">3</span></a>
                    <a href=""><span class="pageBtn">4</span></a>
                    <a href=""><span class="pageBtn">5</span></a>
                    <a href=""><span class="pageBtn">6</span></a>
                    <a href=""><span class="pageBtn">7</span></a>
                    <a href=""><span class="pageBtn">8</span></a>
                    <span class="pageFont">...</span>
                </p>
                <a href=""><span class="pageBtn">></span></a>
                <span class="pageFont">到第</span>
                <span class="pageFont"><input class="pageInput" type="text"></span>
                <span class="pageFont">页</span>
                <span class="pageFont"><button class="pageOk">确定</button></span>
                <span class="pageFont">601条记录，共23页</span>
            </div>

        </div><!-- content end -->

    </div>
</section>

<!-- 弹窗 消息+按钮-->
<div class="pop_wraper" id="fixTipView">
    <div class="pop_outer">
        <div class="pop_inner">
            <div class="pop_content">
                <!-- 这里的内容根据设计调整 外层的4个pop包裹层必须要有-->
                <div class="pop_cont_tip">
                    <p class="tip_mes">是否删除<span>特仑苏</span></p>
                    <div class="tip_btns"><button class="btn_s2">确定</button><button class="btn_s2 btnCancel">取消</button></div>
                    <div class="pop_close"></div>
                </div>

            </div><!-- pop_content 结束 -->
        </div><!-- pop-inner 结束 -->
    </div><!-- pop-outer 结束 -->
</div><!-- pop-wraper 结束 -->

</body>
</html>