<script src="<?php echo "$staticroot/apps/game/apkv1/assets/js/sys/jquery.js?v=$version";?>"></script>
<script src="<?php echo "$staticroot/apps/game/apkv1/assets/js/sys/Form.js?v=$version";?>"></script>
<script src="<?php echo "$staticroot/apps/game/apkv1/assets/js/sys/Model.js?v=$version";?>"></script>
<script src="<?php echo "$staticroot/apps/game/apkv1/assets/js/sys/Common.js?v=$version";?>"></script>
<script src="<?php echo "$staticroot/apps/game/apkv1/assets/js/sys/fastclick.js?v=$version";?>"></script>






